### ISSUE TITLE
Patchy code intel support on PR diffs

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#7196] opened 2019-12-13 19:00 UTC
macOS Catalina
Extension version: v19.12.6.2155
Chrome: 79.0.3945.79

File: https://bitbucket.sgdev.org/projects/SGDEMO/repos/sourcegraph/pull-requests/2/diff#cmd/frontend/graphqlbackend/search.go 

Configured to use https://demo.sgdev.org

![code-intel-issues-bitbucket-pr](https://user-images.githubusercontent.com/133014/70824745-9f68dd00-1e2e-11ea-8b57-dea32430cb3a.gif)

**Comment by lguychard** [comment] 2019-12-13 21:13
@ryan-blunden I have transferred this to sourcegraph/sourcegraph since it was reproduced using the browser extension.

**Comment by lguychard** [comment] 2019-12-13 22:11
Ugh, sorry for not realizing right away that this was a duplicate of https://github.com/sourcegraph/sourcegraph/issues/4808

Switch to side-by-side view, and code intel will work on that PR:

![image](https://user-images.githubusercontent.com/1741180/70835584-84b14c80-1dcb-11ea-83ce-3b602ec40e3f.png)

**Closed by lguychard** 2019-12-13 22:11 UTC
Labels: bitbucket, browser-extension, bug
