### ISSUE TITLE
Sourcegraph.com hitting CPU max

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4755] opened 2019-07-01 21:19 UTC
- **Sourcegraph version:** Sourcegraph.com

#### Steps to reproduce:

1. This is hard to reproduce as I haven't been able to narrow down when the CPU starts going up. While on Sourcegraph.com, it seems like normal searches will trigger the CPU to go overboard and kill all Sourcegraph.com tabs. My last search was "repo:sourcegraph/sourcegraph we-are-thorn" (searching for the thorn case study).
2. If you hit this fringe case, dev tools will also become unresponsive/ not show any content anywhere, not even with static things like local storage.
![Empty dev tools](https://d2ddoduugvun08.cloudfront.net/items/3n1j1F383p0f281f2z24/Screen%20Recording%202019-07-01%20at%2002.17%20PM.gif)
3. Notice that the CPU for Sourcegraph tabs is over the top:
![image](https://user-images.githubusercontent.com/9110008/60467139-9383b880-9c0a-11e9-95bc-2018c5f86c6c.png)

#### Expected behavior:
Sourcegraph.com to not freeze and overload CPU.
#### Actual behavior:
Frozen Sourcegraph.com tabs and necessity to kill those processes and reload website.

**Comment by beyang** [comment] 2019-07-01 21:35
@felixfbecker or @lguychard anything we can do pin down the source of this issue?

**Comment by felixfbecker** [comment] 2019-07-02 16:30
Yes, capturing a CPU profile with the dev tools profiler when this happens.

A git bisect could also help. If it has something to do with searches, it might be some infinite loop with results display.

**Comment by nicksnyder** [comment] 2019-07-11 14:24
Closing this in favor of #4853 since it is a likely duplicate and the other issue has reproduction steps.

**Closed by nicksnyder** 2019-07-11 14:24 UTC
Labels: web
