### ISSUE TITLE
Scip indexer not recognizing golang vanity URLs

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#56549] opened 2023-09-12 14:45 UTC
Sourcegraph's Code Intel faces a challenge when resolving precise indexes for Go module dependencies that use vanity URLs. A specific example, when attempting to look up the precise index for the module [go.something.dev/example](http://go.something.dev/example), it draws a blank. The reason being, its precise indexes are stored under a different name, let's say "https://github.com/something/example".

Vanity URLs enable Go modules to have a module name that's not tied to the code host, providing flexibility and continuity. This feature of the Go toolchain allows teams to transition between code hosts seamlessly, ensuring that module names and corresponding import paths remain consistent.

Sourcegraph should prioritize extracting module names directly from the "go.mod" file, instead of relying on assumptions derived from the code host's information.

**Comment by varungandhi-src** [comment] 2023-09-12 15:02
Example from gopher-luar, which uses a vanity URL.

Here's a reference from the Sourcegraph monorepo: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/luasandbox/util/util.go?L3-6

![](https://github.com/sourcegraph/sourcegraph/assets/93103176/c26a8ca8-c805-46cc-a236-b1a87bae0f55)

They use the vanity URL.

Definitions in the gopher-luar repo on GitHub also use the vanity URL

https://sourcegraph.com/github.com/layeh/gopher-luar@2aa5885def8a7168875e5d2e469e4116584707c0/-/blob/array.go

<img width="1033" alt="" src="https://github.com/sourcegraph/sourcegraph/assets/93103176/77427433-5dbb-48d8-b5e7-fe0b1729e76c">

So both of these match (as they should), which seems inconsistent with the reported issue.

**Comment by jasonhawkharris** [comment] 2023-09-13 14:45
Important clarification from the customer: 
"Indexing the code is working, the part where it fails is the Precise Code Intel for a dependency that uses a vanity URL. The tooltip will show the code intel as search-based for a dependency that has been indexed which uses a vanity URL."

**Comment by varungandhi-src** [comment] 2023-09-19 14:31
@Galindo-J, @Strum355 said you were handling this issue. Could you please do the following:

- Describe what the actual issue the customer faced was (apparently, it was unrelated to vanity URLs?)
- What the resolution was

And then close this issue?

Thanks!

**Comment by Galindo-J** [comment] 2023-09-21 21:35
The issue stemmed from the version identifier being used by the customer was the canonical commit hash instead of a versioned tag value. This meant that the reference site and definition site don't match up exactly.

Auto-indexing not having access to git tags by default is ultimately the cause. In order to address this, a site config update was required. 

The workaround offered was:

1. Set the site config: [executors.lsifGoImage](https://docs.sourcegraph.com/admin/config/site_config#executors-lsifGoImage) 
2. re-index a repo that has a known version tag connected to it
3. Confirm that the version rather than the commit hash appeared. 

The user completed the steps and confirmed. We then provided guidance on how to reindex multiple repos using the auto-indexing policies. 


**Feedback:** The config [executors.lsifGoImage](https://docs.sourcegraph.com/admin/config/site_config#executors-lsifGoImage) is not visible enough for customers setting up code intel when this is required and in what cases might lead to it's need.

It might also be worth investigating if auto-indexing not having access to git tags by default is the desired behavior. @varungandhi-src

**Closed by Galindo-J** 2023-09-21 21:35 UTC
Labels: bug
