### ISSUE TITLE
Go To Definition missing for TypeScript interfaces when using the extension

### ISSUE THREAD

**Issue by TobiaszCudnik** [sourcegraph/sourcegraph#2049] opened 2019-01-28 22:04 UTC
- **Sourcegraph version:** v19.1.23.1746
- **Platform information:** FF 65.0b12, Chrome 71.0.3578.98

#### Steps to reproduce:

1. Go to https://github.com/TaskSync/taskBot.app/blob/10bd3e063fc5fb81ccf49e83f7a8e2c1b27ffc34/src/app/app.ts#L42
2. Wait for the TS server to start
3. Hover over `IConfig` on line 42

#### Expected behavior:

Popup with 2 buttons:
- Go to definition
- Find references

#### Actual behavior:

Popup with 1 button:
- Find references

#### Notes:

- interface definitions work properly on [sourcegraph.com](https://sourcegraph.com/github.com/TaskSync/TaskBot.app/-/blob/src/app/app.ts#L42)
- class definitions work properly with the extension (only interfaces are affected)

**Comment by sqs** [comment] 2019-01-29 02:16
Thanks for the report and sorry for the issue.

I can repro the failure at your GitHub link. I see the following error message in devtools:

```
i: Expected response to be of content type application/x-tar, was text/html; charset=utf-8
```

This comes from the TypeScript extension (https://sourcegraph.com/search?q=repo%3Asourcegraph%2Flang-+expected+response). 

I am guessing this is related to how extensions get file contents from the DOM when running on GitHub. (Incidentally, extensions getting file contents from the DOM is being removed in #2051, which would cause similar problems to what you're seeing, but that hasn't been shipped yet.)

@felixfbecker  Is this a known issue? I don't recall seeing this before. I am tentatively tagging this as 3.0 but if I am missing something that makes this much harder to fix, it can be backlogged.

**Comment by felixfbecker** [comment] 2019-01-29 12:46
@keegancsmith assigning to you since you worked on the raw API recently, please reassign if not appropiate

**Comment by keegancsmith** [comment] 2019-01-30 13:59
I'll only have time to look into this tomorrow. What is the priority of it? @felixfbecker not sure if you have any bandwidth to look into it. cc @slimsag 

In the meantime I just reverted the commit you suspect caused this issue. ad52c581f7fad15bd9e373a4e128b186ef7f289d So it may just fix this issue (but will need to be followed up on)

**Comment by keegancsmith** [comment] 2019-01-30 15:23
I have deployed the reverts, this is still happening. Unrelated to what I did. As I said, I think this is gorilla/mux doing this since I believe it strips slashes and it is the router we use. I already have a release blocker on my plate so don't have the appropriate bandwidth to deal with this issue in a timely matter.

**Comment by felixfbecker** [comment] 2019-01-30 15:33
If it's gorilla/mux, how come it didn't happen before?
gorilla/mux does strip slashes, which is not great but okay and it has always done this, but why would it redirect the no-trailing-slash version to the root of the repo?

> I already have a release blocker on my plate so don't have the appropriate bandwidth to deal with this issue in a timely matter.

Me neither and I have little knowledge about our backend routing. Could you find an owner for this?

**Comment by nicksnyder** [comment] 2019-01-30 21:58
I am not able to reproduce this locally, so I am wondering if this is related to ingress nginx configuration changes in prod cc @ggilmore 

http://localhost:3080/github.com/TaskSync/taskBot.app@10bd3e063fc5fb81ccf49e83f7a8e2c1b27ffc34/-/raw

**Comment by nicksnyder** [comment] 2019-01-30 22:01
This endpoint ALSO appears to work on dogfood.

https://sourcegraph.sgdev.org/github.com/TaskSync/taskBot.app@10bd3e063fc5fb81ccf49e83f7a8e2c1b27ffc34/-/raw

**Comment by nicksnyder** [comment] 2019-01-30 23:34
Meta: Here is how Geoffrey and I solved this issue without having any special knowledge.

We started by looking at the [request trace](https://app.lightstep.com/sourcegraph-prod/trace?span_guid=76dd885dc6cf9f74&at_micros=1548888706848130#span-65c7e19d3c419609) for the suspicious redirects. This confirmed that execution was reaching the [serveRaw](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/raw.go#L56:6) handler.

We did not see any http.StatusMovedPermanently in that direct codepath but noticed [a comment about repo redirection](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/raw.go#L65:7) and jumped in to [newCommon](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/handlers.go#L94:6) which does have [a permanent redirect](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/handlers.go#L123).

After reading that code and seeing URLMovedError, we suspected that the repo had been renamed. We then queried the database to verify that the name in the database was different than what was on github.com.

To double check our work, we searched for other `http.StatusMovedPermanently` and that is how we found [RedirectToNewRepoName](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/pkg/handlerutil/repo.go#L65:14) which might be part of the solution.

**Comment by ggilmore** [comment] 2019-01-31 00:58
More context, I ruled out an issue with `nginx-ingress` by looking through the following logs:

-  `nginx-ingress`: https://console.cloud.google.com/logs/viewer?interval=PT1H&project=sourcegraph-dev&organizationId=1006954638239&minLogLevel=0&expandAll=false&timestamp=2019-01-30T22:37:29.990000000Z&customFacets=&limitCustomFacetWidth=true&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22dot-com%22%0Aresource.labels.namespace_id%3D%22ingress-nginx%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.zone:%22us-central1-f%22%0Aresource.labels.container_name%3D%22nginx-ingress-controller%22%0Aresource.labels.pod_id%3D%22nginx-ingress-controller-64d4468f8f-45rks%22%0AtextPayload:%22TaskSync%22&scrollTimestamp=2019-01-30T22:20:22.155688649Z&dateRangeStart=2019-01-30T21:37:29.990Z&dateRangeEnd=2019-01-30T22:37:29.990Z

- `sourcegraph-frontend`: https://console.cloud.google.com/logs/viewer?interval=PT1H&project=sourcegraph-dev&organizationId=1006954638239&minLogLevel=0&expandAll=false&timestamp=2019-01-30T22:38:36.362000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-01-30T22:20:29.273390353Z&dateRangeStart=2019-01-30T21:39:33.090Z&dateRangeEnd=2019-01-30T22:39:33.090Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22dot-com%22%0Aresource.labels.namespace_id%3D%22prod%22%0Aresource.labels.project_id%3D%22sourcegraph-dev%22%0Aresource.labels.zone:%22us-central1-f%22%0Aresource.labels.container_name%3D%22frontend%22%0AtextPayload:%22TaskSync%22

**Closed** 2019-01-31 14:52 UTC
Labels: bug, feature:code-intel
