### ISSUE TITLE
Svelte: Syntax highlighting bug with first line

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#62275] opened 2024-04-30 11:35 UTC
Seems to be a bug if the first line of a file is a comment. The `//` isn't highlighting as a comment.

See: [https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@b22c054002b6c796ed7efbab90312d702631c01b/-/blob/cmd/frontend/auth/auth.go?L22-28=](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@b22c054002b6c796ed7efbab90312d702631c01b/-/blob/cmd/frontend/auth/auth.go?L22-28=)

![CleanShot 2024-04-30 at 12 34 43@2x](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/a8c3ba25-b9eb-4416-a19c-15ebb89ae832/906f5b07-970c-466f-aba5-ef2ad7cd166e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9hOGMzYmEyNS1iOWViLTQ0MTYtYTE5Yy0xNWViYjg5YWU4MzIvOTA2ZjViMDctOTcwYy00NjZmLWFiYTUtZWYyYWQ3Y2QxNjZlIiwiaWF0IjoxNzE0NTI1OTkzLCJleHAiOjMzMjg1MDg1OTkzfQ.RXvc2oQdPWstaZzevJ7EwLW17EAMjjr7AAld0ZV-Mhs "=409x")

**Comment by varungandhi-src** [comment] 2024-05-01 01:15
Duplicate of [https://github.com/sourcegraph/sourcegraph/issues/60852](https://github.com/sourcegraph/sourcegraph/issues/60852)

**Closed** 2024-05-01 01:15 UTC
