### ISSUE TITLE
Breadcrumbs are spaced equally instead of left aligned 

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#14628] opened 2020-10-12 16:17 UTC
Set your browser to less than 1440 pixels wide and view a file with a long filename such as [this one](https://sourcegraph.com/github.com/0015/IdeasNProjects/-/blob/Esp32_temperature_humidity_ble_FLUTTER/flutter_ble_app/flutter_ble-master/ios/gen/Flutterblue.pbobjc.h?subtree=true).

Note all the breadcrumb elements take up equal width at sizes less than the XL media query size. See the screenshot:

![image](https://user-images.githubusercontent.com/539268/95768182-c8364a80-0c6a-11eb-8aa0-ec0e1aa28b9a.png)

**Comment by Joelkw** [comment] 2020-10-12 17:34
seems like a duplicate of #14336 so closing

**Closed by Joelkw** 2020-10-12 17:34 UTC
Labels: design, team/web, webapp
