### ISSUE TITLE
CodeMirror: Should we notify user that they have a new blob experience?

### ISSUE THREAD

**Issue by scalabilitysolved** [sourcegraph/sourcegraph#40513] opened 2022-08-17 19:56 UTC
### Problem

@leonore raised some good feedback about the transition to the new blob view:

> that was the most jarring to me. a piece of feedback regarding that is I genuinely thought something had failed to render rather than it being an official change. I don’t know if there could be a signal to the user that the view has changed, 

Should we be considering a way to notify to the user (when we do finally go live with this) that the blob view has indeed changed (and for the better)!  I imagine this effect will lessen as we fix up some of the current obvious differences in fonts/line padding but still something for you to consider.

**Comment by jjinnii** [comment] 2022-08-18 06:11
I'll let @olafurpg speak to the effort associated to fixing the UI differences (font, font weight, and padding), but I am assuming that these are low-effort (why I tagged them with the x-small tag). If this is indeed the case, I think it makes a lot more sense for us to fix these differences, rather than working on an alert/notification to communicate to the user about CodeMirror! This is for a few reasons:

- CodeMirror is an implementation choice for us to improve performance of our file view. It isn't a UI-impacting feature that users _need_ to know about.
- These UI differences are not intentional. Unless they pose a significant effort, I think we should resolve them for UI consistency across our product. As we're seeing with the feedback, as the fileview is such a core view, it's immediately noticeable when there are minor differences in our UI. 

cc: @macraig

**Comment by olafurpg** [comment] 2022-08-18 06:58
+1 to Sara's comment that we should prioritize the low-effort fixes for obvious differences that we're aware of. 

> CodeMirror is an implementation choice for us to improve performance of our file view. It isn't a UI-impacting feature that users need to know about.


The change with Cmd+F is a big impact on the UX and I think we should spend some time brainstorming how to minimize that gap. Ideally, users shouldn't need to learn a new workflow so that we avoid having to document the change.

**Comment by jjinnii** [comment] 2022-08-18 07:06
@olafurpg Good point on the Cmd + F! I've mentioned in issue #40542 that some thinking is required here. To tie it back to this issue though, I think what's required is onboarding the users to the changes in the Cmd + F behavior, as opposed to introducing them to CodeMirror.

**Comment by olafurpg** [comment] 2022-08-18 09:03
I'm going to experiment with auto-focusing the blob view so that Cmd+F picks the CodeMirror search bar by default, while allowing users to fallback to the browser's Cmd+F by clicking anywhere outside the blob view. If we implement that solution then I think we'll be positioned to collect user feedback and validate if it's sufficiently intuitively or if more onboarding is needed.

**Comment by jjinnii** [comment] 2022-09-22 04:30
@macraig @fkling @olafurpg Do we feel comfortable closing out this issue since we are actively working towards UI parity with the old file view before releasing CodeMirror?

**Comment by fkling** [comment] 2022-09-22 07:25
@jjinnii The new blob view handles line selection differently (click/drag on line numbers instead of whitespace). How do we feel about that? If we keep that then I think we would have to call this out somehow.

**Comment by jjinnii** [comment] 2022-09-28 15:11
I'm going to close this issue until we've confirmed that there are aspects of the UI/UX that are intentionally being changed and/or improved that we should communicate to our users. At that point, we can always create a new issues with the specific behavior changes we feel we need to onboard users on to!

cc: @fkling @macraig

**Closed by jjinnii** 2022-09-28 15:11 UTC
Labels: team/code-intelligence, needs-design, team/code-navigation, codemirror
