### ISSUE TITLE
code-intel-qa pipeline was disabled due to a flake

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#25389] opened 2021-09-27 12:03 UTC
- PR: https://github.com/sourcegraph/sourcegraph/pull/25386
- context https://sourcegraph.slack.com/archives/CMBA8F926/p1632733591338100 

> We’re currently seeing failures other on the code-intel-qa pipeline, which prevents us to finally go back to green green. Some builds still went through it, pointing possibly toward it being flake.

No obvious solution was in sight, so we disabled them for now. Sorry for the inconvenience 🙏  Please reach out if it's hard to reproduce and you believe that the CI context is involved (i.e CI flake). 

cc @sourcegraph/code-intel

**Comment by olafurpg** [comment] 2021-09-27 12:13
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/25387 ? Linked by @pdubroy during code review https://docs.sourcegraph.com/dev/background-information/testing_principles#flaky-tests

**Comment by bobheadxi** [comment] 2021-09-27 12:53
Let's merge this into the other issue!

**Closed by bobheadxi** 2021-09-27 12:53 UTC
Labels: team/code-intelligence, flake, ci
