### ISSUE TITLE
Hover tooltips show different class that the one hovered on

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#14629] opened 2020-10-12 18:02 UTC
- **Sourcegraph version:** Sourcegraph.com, not logged in
- **Platform information:** Chromium Edge on Windows 10

Reported by @asklar

For this search:
https://sourcegraph.com/github.com/microsoft/react-native-windows@781e60daab2ba7f0e0e241f67d3f82efbfd07c4a/-/blob/vnext/Microsoft.ReactNative/Modules/Animated/EventAnimationDriver.h#L16:29

Hovering over `NativeAnimatedNodeManaager` initially gave a hover tooltip for a different class, `TransformAnimatedNode`:

![image](https://user-images.githubusercontent.com/206864/95776809-e5bee080-0c79-11eb-8eec-9ee975ef3f8c.png)

However, when trying again a few hours later, the issue was resolved:

![image](https://user-images.githubusercontent.com/206864/95776871-025b1880-0c7a-11eb-9e4a-490eebf285ab.png)

**Comment by macraig** [comment] 2020-10-20 17:09
This is a known limitation of basic code intelligence, maybe the search team can help here @poojaj-tech ?

**Comment by efritz** [comment] 2020-10-20 17:11
Hey, we mentioned the search team here as it might be that the difference in results are due to either (1) not having something indexed (zoekt ctags) in the first response but having something better indexed in the second response, or (2) having non-stable search result rankings.

**Comment by poojaj-tech** [comment] 2020-10-20 22:46
@efritz thanks for sharing how this impacts search. Is this something the code-intel team is prioritizing in an upcoming iteration?
Perhaps @keegancsmith can help here.

**Comment by keegancsmith** [comment] 2020-10-21 07:31
I can't reproduce. I tried both on indexed and not indexed commits and got the correct results. What instrumentation can we add to improve this? Maybe the backend could somehow inform if the results came from indexed vs non-indexed sources. Then we could log that?

**Comment by efritz** [comment] 2020-10-21 18:01
@poojaj-tech Sorry if I was unclear. I think the relationship is actually the other way. Basic code intelligence _uses_ search to find candidate definitions and references, so if search performance (symbol search in particular) is bad or if symbol results are non-stable (we get different results from the same query, either now or over time), you will see those same things in the code intelligence side.

This doesn't affect search, but _search affects this_.

@keegancsmith Where would these logs go? In a trace? I would have assumed that the search backend would have already made this information available in open tracing.

**Comment by tistru** [comment] 2020-10-21 19:23
Customer reported this same issue with their C++ code base using search based code intel. Upon reloading the page, they got correct references or got references in cases that didn't appear on the initial load. This was mostly reproducible in their code base when viewing files in Sourcegraph.

Reported by: https://app.hubspot.com/contacts/2762526/contact/25700601

**Comment by keegancsmith** [comment] 2020-10-22 08:09
@efritz can you explain exactly what search is done for hover and how the result is interpreted? In particular for the report description. Can you also explain how references is done for the example @tistru gave above? The explanations will help narrow down misbehaviour between search and basic code intel, since I can't seem to rely on reproducing it.

> @keegancsmith Where would these logs go? In a trace? I would have assumed that the search backend would have already made this information available in open tracing.

Search backend has this information (if tracing is enabled), but hard to collect for a specific hover interaction unless its easy to reproduce. Lets pause on the logs idea for now, I think with the information above on what is done I can maybe come up with an approach to narrow this down.

**Comment by efritz** [comment] 2020-10-22 13:21
@keegancsmith How extensions resolve hover text is detailed in https://docs.sourcegraph.com/dev/background-information/codeintel/extensions.

In this case, we will do a symbol search for the token being hovered, and if there's a single one that's our jump target. The hover text will also come from the definition by trying to parse the surrounding text to look for doc comments.

We do one query to look for local definitions in the same repo:
`^{searchToken}$ type:symbol patternType:regexp case:yes file:.({ext[0]}|{ext[1]}|...)$ repo:^{repo}$@commit`

If that finds nothing, we look everywhere else:
`^{searchToken}$ type:symbol patternType:regexp case:yes file:.({ext[0]}|{ext[1]}|...)$ -repo:^{repo}$ index:true`

It could be that the same query is returning different results, or that the first query wasn't yet indexed on the first request but was on the second. Similarly, it could be that the set of indexed things changed between queries. Seems like a lot of moving parts here. Would be good to get a cross-team understanding of this behavior.

**Comment by keegancsmith** [comment] 2020-10-29 10:44
I'm not really sure how to debug this further. I've read the docs, and they matched my expectation on how it works. I'm not sure how this happened. Really need something I can reproduce to understand. Investing in tooling to proactively catch this is hard to justify right now. However, if a user has repeatedly run into this then it makes sense to work on.

**Comment by christinelovett** [comment] 2020-11-04 23:28
[Customer](https://app.hubspot.com/contacts/2762526/company/1021335057) has deployed via Docker Compose in GCP and upgraded to 3.21.2. They are stilling receiving incorrect data on the tooltip feature. They would like to know the best way to capture and share this with us?

**Comment by justdueck** [comment] 2020-11-05 22:24
To add to @christinelovett 's comment:

The customer has shared a screencap demonstrating the issue. You can access it here: https://drive.google.com/file/d/1ogNKV1Dgb-uXf5At0wKmag_UKvZ570Xy/view?usp=sharing

**Comment by keegancsmith** [comment] 2020-11-09 12:16
@beyang filed this potential repro which may be the same issue https://github.com/sourcegraph/sourcegraph/issues/14629

**Comment by efritz** [comment] 2020-11-10 19:14
Fixed by https://github.com/sourcegraph/code-intel-extensions/pull/524.

**Closed by efritz** 2020-11-10 19:14 UTC
Labels: ce/p0, team/code-intelligence
