### ISSUE TITLE
deploy  on docker 

### ISSUE THREAD

**Issue by vaniot-s** [sourcegraph/sourcegraph#1238] opened 2018-12-05 05:05 UTC
lvl=eror msg="langservers: error deleting Docker lsp bridge network" error="exec: \"docker network rm lsp\": error: signal: interrupt stderr:\n"

**Comment by sqs** [comment] 2018-12-05 05:08
Are there any other errors? When does this problem occur?

**Comment by vaniot-s** [comment] 2018-12-05 16:41
> Are there any other errors? When does this problem occur?

05:02:57          frontend | t=2018-12-05T05:02:57+0000 lvl=warn msg="docker events failed. Will try again in 30s" error="exec: docker events: error: signal: interrupt stderr:\n"
05:02:57          frontend | t=2018-12-05T05:02:57+0000 lvl=eror msg="langservers: error deleting Docker lsp bridge network" error="exec: \"docker network rm lsp\": error: signal: interrupt stderr:\n"

**Comment by vaniot-s** [comment] 2018-12-05 16:45
I had deployed on docker normal running,when I restart the container it happend some error

**Comment by sqs** [comment] 2018-12-06 06:52
@slimsag 	Any quick ideas here?

**Comment by slimsag** [comment] 2018-12-06 23:09
Hi @vaniot-s -- can you run `docker network rm lsp`? If it errors out, delete any containers attached to it (look under `docker ps -a`).

Is the problem that you are not receiving code intelligence? Or are you seeing some other problem caused by this error?

**Comment by slimsag** [comment] 2018-12-06 23:10
You may also try restarting the host machine which would cause Docker to re setup the network stack + connect containers to it.

**Comment by vaniot-s** [comment] 2018-12-07 03:47
> You may also try restarting the host machine which would cause Docker to re setup the network stack + connect containers to it.

I reinstall sourcegraph on docker ,it occur the error as follow:
```
03:44:20 zoekt-indexserver | 2018/12/07 03:44:20 Post http://127.0.0.1:3090/.internal/repos/list: dial tcp 127.0.0.1:3090: connect: connection refused
```
but it don't influnce program running,when I restart it,the program can't normal running

**Comment by vaniot-s** [comment] 2018-12-07 03:52
thaks @slimsag  I wanna know what's service of  port 3090

**Comment by slimsag** [comment] 2018-12-07 05:34
Service port 3090 is an internal service running within the Docker container (the `frontend` service). This error indicates it did not start up properly.

There must be an earlier error indicating why: could you post the full log output (and redact any private information) or email it to me (stephen@sourcegraph.com)?

**Comment by vaniot-s** [comment] 2018-12-07 07:57
> Service port 3090 is an internal service running within the Docker container (the `frontend` service). This error indicates it did not start up properly.
> 
> There must be an earlier error indicating why: could you post the full log output (and redact any private information) or email it to me ([stephen@sourcegraph.com](mailto:stephen@sourcegraph.com))?

I have sent to you,thanks for your help

**Comment by slimsag** [comment] 2018-12-07 21:56
I have reviewed the logs you sent over. This error seems unrelated to your problem, as it appears to only be occurring on startup and then auto-resolving itself (we need to make this less verbose / not an error):

> 2018/12/07 03:51:05 Post http://127.0.0.1:3090/.internal/repos/list: dial tcp 127.0.0.1:3090: connect: connection refused

I do see this error as well:

> 06:49:29          frontend | t=2018-12-07T06:49:29+0000 lvl=eror msg="langservers: error deleting Docker lsp bridge network" error="exec: \"docker network rm lsp\": error: exit status 1 stderr:\nError response from daemon: error while removing network: network lsp id 1e347277b865ce15870e4fc8771a40f8c4a421406a96a25db15fd9132820726f has active endpoints\n"

It may be the case that this is not causing you problems either, but it is hard to say with certainty. We are fixing this in our upcoming 3.0 release in a few months, though.

Error messages aside, what problem do you observe using the product?

**Closed** 2018-12-09 03:35 UTC
Labels: bug
