### ISSUE TITLE
Blob view: cannot copy content when line is selected

### ISSUE THREAD

**Issue by jtibshirani** [sourcegraph/sourcegraph#59394] opened 2024-01-08 20:21 UTC
When a blob view links to a particular line, you can no longer select text on that line.

For example, when opening this link from dot com, I cannot select the `expected-sha256` value: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@es/grpc-cleanup/-/blob/wolfi-packages/p4-fusion.yaml?L60

Feel free to close if this is a duplicate!

**Comment by jtibshirani** [comment] 2024-01-08 20:47
Update: I now see that the text can be selected and copied, the selection just isn't highlighted. This still feels worth fixing, as I was really thrown off by it.

**Comment by fkling** [comment] 2024-01-17 13:33
Closing as duplicate of #59096.

(thank you though 🙂 )

**Closed by fkling** 2024-01-17 13:33 UTC
Labels: code-search
