### ISSUE TITLE
browser-extension: Requests fail against dogfood

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#2725] opened 2019-03-13 13:59 UTC
I am logged in to sourcegraph.sgdev.org using Chrome, but the browser extension fails to send requests to dogfood. The requests fail with status code 401 and the text "Private mode requires authentication.".

I am unsure if this is due to an issue with the auth stack, or how we send requests from the background page. The below snippet from the network inspector is for browsing a private repo which is on sgdev.

![image](https://user-images.githubusercontent.com/187831/54284448-9c437680-45a8-11e9-8f7d-70aae0830a76.png)

![image](https://user-images.githubusercontent.com/187831/54284421-9188e180-45a8-11e9-9227-792d2a14ff03.png)

**Comment by lguychard** [comment] 2019-03-13 14:54
@sqs could this be an unforeseen side-effect of https://github.com/sourcegraph/sourcegraph/pull/2689/files#diff-16c810a296953d51a6e43ae5f7d5fd74 (specifically the changes to `isTrustedOrigin`)?

@keegancsmith is using the prod extension here, and I'm also reproducing this with an extension built from the 3.1 branch, which leads me to think that this is not due to recent extension changes.

Bumping to 3.2 since this could affect customers with similar auth stacks.

**Comment by lguychard** [comment] 2019-03-13 18:15
I just realized why this was happening while debugging something else.

- https://github.com/sourcegraph/sourcegraph/pull/2689/files#diff-16c810a296953d51a6e43ae5f7d5fd74  removed a special `corsAllowed` case checking whether the requestOrigin was our dev or prod extension in order to allow the request.
- Following this, the only two cases where a request is allowed are:
    - The request has a non-empty `X-Requested-With` header
    - The origin of the request is specifically allowed by configuration through `corsOrigin` (should only be necessary for the native Phabricator integration)

This is OK because #2689 also made sure to always set the `X-Requested-With` header. However, those changes have not yet made it into the prod extension, which still relies on `isExtensionRequest`.

**Comment by sqs** [comment] 2019-03-14 02:56
@lguychard 	Ah - so this is fixed by publishing the latest browser extension for Chrome and Firefox, right? (And it would've broken for anyone whose Sourcegraph version build includes #2689, which is really just us on sourcegraph.sgdev.org and sourcegraph.com?)

Since it sounds like only we are affected and so it's not time-sensitive, can you please follow through on this instead of me (publishing latest and closing this issue)? Thank you!

**Comment by sqs** [comment] 2019-03-15 05:58
@lguychard 	Reopening because I don't see the latest extension version has been published, and #2747 	was just reported (which seems to indicate the problem is still occurring).

**Comment by lguychard** [comment] 2019-03-15 09:35
Sorry about that, CI failed on the bext release branch I forgot to reopen this after opening the PR that would fix CI.

**Comment by lguychard** [comment] 2019-03-15 10:19
Browser extension v19.3.15.1012 has been published and does not fail against dogfood.

**Closed by lguychard** 2019-03-15 10:19 UTC
Labels: browser-extension, bug
