### ISSUE TITLE
search: streaming search does not render errors

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#17974] opened 2021-02-04 10:09 UTC
If your streaming search returns an error it will always fail with:

> The connection was closed before your search was completed. This may be due to a problem with a firewall, VPN or proxy, or a failure with the Sourcegraph server.

The backend is sending error event then done event. However, it seems the webapp is failing somewhere. I spent a little bit of time fixing it, but wasn't sure what to do. One thing I did notice is that the "error" event now expects an `Error` as the payload. Even fixing that it still fails to work.

An example search which returns an error:

```
repo:^github\.com/sourcegraph/sourcegraph$@*refs/heads/ foobarbaz count:1000 timeout:2s index:only
```

See details below for a patch for backend to send error event with payload matching TS Error. However, we don't have good "name", only a message to send. IE error event's payload is just a string without this patch (and more correct for what the backend has)

<details>

```diff
diff --git a/cmd/frontend/graphqlbackend/search_alert.go b/cmd/frontend/graphqlbackend/search_alert.go
index 1b3af05686..b4cd897c08 100644
--- a/cmd/frontend/graphqlbackend/search_alert.go
+++ b/cmd/frontend/graphqlbackend/search_alert.go
@@ -692,7 +692,7 @@ type alertObserver struct {
 	// Error state. Can be called concurrently.
 	mu    sync.Mutex
 	alert *searchAlert
-	err   error
+	err   *multierror.Error
 }
 
 // Update AlertObserver's state based on event.
@@ -743,5 +743,15 @@ func (o *alertObserver) Done(stats *streaming.Stats) (*searchAlert, error) {
 		return o.alert, nil
 	}
 
-	return o.alert, o.err
+	var err error
+	if o.err != nil {
+		errs := o.err.WrappedErrors()
+		if len(errs) == 1 {
+			err = errs[0]
+		} else {
+			err = o.err.ErrorOrNil()
+		}
+	}
+
+	return o.alert, err
 }
diff --git a/cmd/frontend/graphqlbackend/zoekt.go b/cmd/frontend/graphqlbackend/zoekt.go
index f654538123..659b0adbf8 100644
--- a/cmd/frontend/graphqlbackend/zoekt.go
+++ b/cmd/frontend/graphqlbackend/zoekt.go
@@ -120,7 +120,7 @@ func newIndexedSearchRequest(ctx context.Context, args *search.TextParameters, t
 	// Fallback to Unindexed if the query contains ref-globs
 	if containsRefGlobs(args.Query) {
 		if indexParam == query.Only {
-			return nil, fmt.Errorf("invalid index:%q (revsions with glob pattern cannot be resolved for indexed searches)", indexParam)
+			return nil, fmt.Errorf("invalid index:%q (revisions with glob pattern cannot be resolved for indexed searches)", indexParam)
 		}
 		return &indexedSearchRequest{
 			Unindexed: repos,
diff --git a/cmd/frontend/internal/search/search.go b/cmd/frontend/internal/search/search.go
index 040684e9da..95bac967f3 100644
--- a/cmd/frontend/internal/search/search.go
+++ b/cmd/frontend/internal/search/search.go
@@ -6,6 +6,7 @@ package search
 import (
 	"context"
 	"errors"
+	"fmt"
 	"net/http"
 	"net/url"
 	"time"
@@ -65,7 +66,10 @@ func (h *streamHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 		VersionContext: strPtr(args.VersionContext),
 	})
 	if err != nil {
-		_ = eventWriter.Event("error", err.Error())
+		_ = eventWriter.Event("error", eventError{
+			Name:    fmt.Sprintf("%T", err),
+			Message: err.Error(),
+		})
 		return
 	}
 	resultsStream, resultsStreamDone := newResultsStream(ctx, search)
@@ -190,7 +194,10 @@ func (h *streamHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	final := <-resultsStreamDone
 	resultsResolver, err := final.resultsResolver, final.err
 	if err != nil {
-		_ = eventWriter.Event("error", err.Error())
+		_ = eventWriter.Event("error", eventError{
+			Name:    fmt.Sprintf("%T", err),
+			Message: err.Error(),
+		})
 		return
 	}
 
@@ -471,3 +478,8 @@ type proposedQuery struct {
 	Description string `json:"description,omitempty"`
 	Query       string `json:"query"`
 }
+
+type eventError struct {
+	Name    string `json:"name"`
+	Message string `json:"message"`
+}
```

</details>

**Comment by limitedmage** [comment] 2021-02-24 17:17
Duplicate of #18576, fixed with #18579

**Closed by limitedmage** 2021-02-24 17:17 UTC
Labels: team/search
