### ISSUE TITLE
Upgrade failure on a Sourcegraph instance with the frontend database in a separate server with other databases

### ISSUE THREAD

**Issue by airamare01** [sourcegraph/sourcegraph#60162] opened 2024-02-05 13:40 UTC
- **Sourcegraph version:**  v5.1.9
- **Platform information:** 

#### Steps to reproduce:

1. In a Kubernetes cluster, set up Sourcegraph.
2. Move/create the frontend database in a separate cluster with other databases running on it.
3. Attempt to upgrade from v5.1.9 to v5.2.0.

#### Expected behavior:
Performing an upgrade, with the frontend database in a separate cluster with no conns open to Sourcegraph works
#### Actual behavior:
Frontend returns `warning: named postgres connections found, waiting for them to shutdown, manually shutdown any unexpected ones.`

#### Detailed write-up
If Sourcegraph's Postgresql database is outside the Kubernetes cluster Sourcegraph is deployed on, for example, on a server shared with other databases. Performing an upgrade fails.

https://github.com/sourcegraph/sourcegraph/blob/v5.2.0/cmd/frontend/internal/cli/autoupgrade.go#L328 - This query checks if there are other connections.  `frontend-autoupgrader` in the external DB returns other application names related to other databases running on that server. However, if you add a condition based on DB name (… AND datname = ‘$DB_NAME’), the query works as expected, returning 0 rows.

This is a bug that forces a move the sourcegraph-related Postgresql DBs to dedicated servers or back to the Sourcegraph’s k8s cluster

#### Fix

This draft [PR](https://github.com/sourcegraph/sourcegraph/pull/58588) attempts to fix the above condition

cc: @DaedalusG

**Comment by DaedalusG** [comment] 2024-02-06 07:07
Thanks for the tracking issue Stompy --
> Performing an upgrade, with the frontend database in a separate cluster with no conns open to Sourcegraph works

> Move/create the frontend database in a separate cluster with other databases running on it.

We haven't got a Sourcegraph instance in test setup with a configuration quite like this, and I'm afraid in the current planning the autoupgrade path isn't being worked on. I'll try to reproduce and review this soon since the fix may be easy. 

For now I'd advise customers with the suggested setup to use manual invocations of migrator for Multiversion upgrades, and conduct minor version upgrades via the built in migrator up command.

**Comment by gabtorre** [comment] 2024-02-07 19:06
Also reported by https://github.com/sourcegraph/accounts/issues/8343

**Comment by airamare01** [comment] 2024-02-21 13:10
One thing to note about this issue is that it's not a MVU. It's an upgrade from one minor version @DaedalusG. I'd suggest taking a look at the draft PR in the original post to review what we're trying to achieve here.

Just FYI. This is still a blocker for https://github.com/sourcegraph/accounts/issues/8445

**Comment by DaedalusG** [comment] 2024-02-22 22:42
@airamare01 @gabtorre Its actually the case that all autoupgrades hit the MVU upgrade path so the upgrade policy (version range) for autoupgrades isnt that big of a thing

This is next up on my plate, should have a fix out fairly quickly once I have a reproduction of the issue -- will make it into v5.3.2 patch release by 3/7/24 or so

**Comment by airamare01** [comment] 2024-02-23 13:44
Thanks for the update @DaedalusG

**Comment by DaedalusG** [comment] 2024-03-07 19:13
This is expected to be fixed by: https://github.com/sourcegraph/sourcegraph/pull/60771

**Closed by DaedalusG** 2024-03-07 19:13 UTC
Labels: bug, team/release-ship
