### ISSUE TITLE
Store Git commits in Postgres

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#11169] opened 2020-06-01 09:18 UTC
### Context

Many features implemented across different infrastructure components at Sourcegraph currently require RPC calls to gitserver to get needed git related information (i.e. commits, etc)

This information being locked behind an RPC layer that runs git commands on the fly is elegant but has a few problems:

1. Lots and lots of N+1 queries.
2. Slower than having it indexed and queried in Postgres.
3. Harder to work with for engineers.

To solve this, we want to experiment with storing commit information of all gitserver repos in Postgres with an appropriate schema. This information would be directly readable, but not writable, by all other services at Sourcegraph, and, later on, potentially by customers directly.

### Open questions

- What's the right initial schema? (see discussion below) Do we need [table partitioning](https://www.postgresql.org/docs/12/ddl-partitioning.html)? (I think so)
- What are the resource requirements for this in Sourcegraph Cloud? Memory and disk.
- If we move forward with this, how do we smoothly roll out this change to customers?
- What is the exact list of use cases that should be refactored to use this capability?
- How do we quickly validate the scalability of Postgres for this use case?

**Comment by tsenart** [comment] 2020-06-01 09:22
@keegancsmith: Feel free to elaborate here, this is a first draft of the work to be done and open questions.

**Comment by keegancsmith** [comment] 2020-06-04 13:07
I'm interested if we should go with a flexible schema (ie key/value for each repo), or use a schema where each column is a field we care about. Whatever we pick, I would want it to be performant since there is a good chance we join against this table for search.

In my mind v0 should improve the perf of "repohascommitafter:" searches, know what resolve-rev HEAD is, and know when that last changed. Everything else isn't as useful just yet. But that gives us big gains, and gets all the relevant infra in place to apply it in other places.

> Which architecture component is responsible for writing this information to Postgres?

The only reasonable option here is gitserver, otherwise the information will become out of date. Alternatively gitserver could expose an append only log of repos that are updated/cloned, then a new component could do this. I think I actually prefer that :)

> What initial set of information do we want to index?
> All Branches SHAs

Do we want all branches? This can be huge, and begs for an alternative ref backend. I could imagine introducing this though, but I think it should not be part of v1.

> Latest commit date

Latest HEAD commit date :) I think all meta information on the latest commit would be best. Initially I'd just target a date, but with scope to increase that. Something I think is a requirement is a serial counter which can be relied on to detect all repos that changed.

> Cloning status

I'm a maybe on this. I think if its easy to add it makes sense to include. Either way whatever maintains this data will need to consolidate with what is actually on disk and what is in the table. So it needs to be aware of this.

> Do we store this information in the repo table or a separate table and join with it at read time?

Separate seems much more flexible.

**Comment by tsenart** [comment] 2020-06-04 14:09
> Alternatively gitserver could expose an append only log of repos that are updated/cloned, then a new component could do this. I think I actually prefer that :)

And we're back to the Redis Streams idea? :D

**Comment by tsenart** [comment] 2020-06-04 14:20
> Separate seems much more flexible.

Why? It introduces yet another table, when we can have all the information of a repo in the same table.

**Comment by tsenart** [comment] 2020-06-04 14:57
@keegancsmith: I've sketched out a schema that I think addresses all of these requirements, proceeding with the idea that git-server writes to this table directly.

```sql
-- At first, we'll only store the last commit from each branch in a repo.
CREATE TABLE git_commits (
  repo_id int NOT NULL REFERENCES repo(id),
  sha text PRIMARY KEY,  -- e.g. 7fd1a60b01f91b314f59955a4e4d4e80d8edf11d
  message text NOT NULL,
  refs text[] NOT NULL,  -- e.g. [master, develop]
  author_date timestamptz NOT NULL,
  author_name text NOT NULL,
  author_email text NOT NULL,
  committer_date timestamptz NOT NULL,
  committer_name text NOT NULL,
  committer_email text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz,
);
```

This also solves the last requirement without having a separate "cloning" state captured like this:

```sql
-- Get all repos in cloning state, assuming that those repos still don't have rows in git_commits.
SELECT * FROM repo WHERE NOT EXISTS (SELECT 1 FROM git_commits WHERE repo_id = repo.id)
```

**Comment by eseliger** [comment] 2020-06-04 15:38
@tsenart that would not account for empty repos, would it?

**Comment by keegancsmith** [comment] 2020-06-04 18:41
> > Alternatively gitserver could expose an append only log of repos that are updated/cloned, then a new component could do this. I think I actually prefer that :)
> 
> And we're back to the Redis Streams idea? :D

Possibly :)

> > Separate seems much more flexible.
> 
> Why? It introduces yet another table, when we can have all the information of a repo in the same table.

I like the idea of repo-updater owning repos table, then gitserver (or something new) owning this new table. I also like to think that the repos table is about info from the codehost api, while this table will be about data from git. We may also want a 1 to many relationship.

> @tsenart that would not account for empty repos, would it?

Good point. I'm torn between not having entries for these (and keeping cloning info separate) and having a nullable column. I think I prefer the former.

> `CREATE TABLE git_commits (`

Thanks for this and its really cool :)

General comments: This doesn't allow to answer the query: give me all repos that have changed since X. You could write a query which does a `select distinct(repo) from git_commits where created_at > x` but that seems like it may be a lot of data to query.

> At first, we'll only store the last commit from each branch in a repo.

A repo can have _lots_ of refs. It is likely easier for us to first focus on a limited scope (eg just HEAD). When we move to all refs / all commits this table will be incredibly large and likely won't scale without some partitioning/etc. So we should narrow the scope to what we know we need for now (and can grow it).

> `sha text PRIMARY KEY,  -- e.g. 7fd1a60b01f91b314f59955a4e4d4e80d8edf11d`

Lets store this as a `bytea` type rather. More compact and the same type that [pgcrypto](https://www.postgresql.org/docs/11/pgcrypto.html) returns for hashing. Something to take into account is git is moving to sha256 in the future, so we can expect bigger digest strings.

This can't be a primary key, a commit can appear in more than one repo.

>  ` refs text[] NOT NULL,  -- e.g. [master, develop]`

I would rather denormalize this since querying on the ref name will be the most common query.

>  `author_date timestamptz NOT NULL,`
> ... snip
> `committer_email text NOT NULL,`

Most of these fields I don't expect us to query on (except for commiter_date). Is it worth storing them when they can be accessed from git?

> `created_at timestamptz DEFAULT now() NOT NULL,`

This field is useful, but ideally I'd want a serial field which we can rely on to order events. ie if I am an index server and last time I did an index the serial field was `N`, give me all repos where serial > N. timestamps don't give the same gaurentees.

**Comment by tsenart** [comment] 2020-06-05 13:50
> General comments: This doesn't allow to answer the query: give me all repos that have changed since X. You could write a query which does a select distinct(repo) from git_commits where created_at > x but that seems like it may be a lot of data to query.

`select distinct (repo_id) from git_commits where created_at >= x` seems perfect. Why do you think that'd be a lot data to query? Given the right index, it'd be fine.

**Comment by tsenart** [comment] 2020-06-05 14:01
> A repo can have lots of refs. It is likely easier for us to first focus on a limited scope (eg just HEAD). When we move to all refs / all commits this table will be incredibly large and likely won't scale without some partitioning/etc. So we should narrow the scope to what we know we need for now (and can grow it).

Sounds good.

> Lets store this as a bytea type rather. More compact and the same type that pgcrypto returns for hashing. Something to take into account is git is moving to sha256 in the future, so we can expect bigger digest strings.

How is `bytea` more compact? 

> Good point. I'm torn between not having entries for these (and keeping cloning info separate) and having a nullable column. I think I prefer the former.

If we have a separate `git_refs` or `git_branches` table and normalize the relationship between `git_commits`, we can use that for the cloning status since I believe every repo has git refs.

> This can't be a primary key, a commit can appear in more than one repo.

We can have a composite primary key on `(repo_id, sha)`.

> I would rather denormalize this since querying on the ref name will be the most common query.

It would still be fast, with indexing, but given the other use case for a separate `git_refs` table, then +1.

> Most of these fields I don't expect us to query on (except for commiter_date). Is it worth storing them when they can be accessed from git?

We don't need to store these now, but we could. The whole point of this table is to reduce load and network round trips to git server. Are you concerned with storage or performance?

> This field is useful, but ideally I'd want a serial field which we can rely on to order events. ie if I am an index server and last time I did an index the serial field was N, give me all repos where serial > N. timestamps don't give the same gaurentees.

We can add an auto incrementing ID to the table, but not sure I understand the need for it. The way I was thinking of this, each time `repoUpdate2` is called in gitserver, we upsert commits and refs to these tables.

**Comment by keegancsmith** [comment] 2020-06-08 08:13
Something I forgot to mention before. This doesn't handle symrefs. IE how do we know what HEAD is? A useful operation we do quite often is finding out the ref for HEAD as well as the commit for it.

> > General comments: This doesn't allow to answer the query: give me all repos that have changed since X. You could write a query which does a select distinct(repo) from git_commits where created_at > x but that seems like it may be a lot of data to query.
> 
> `select distinct (repo_id) from git_commits where created_at >= x` seems perfect. Why do you think that'd be a lot data to query? Given the right index, it'd be fine.

It's a lot of data if the table contains all commits or even all refs. I suppose the index `(created_at, ref)` would be fast, and if you include repo_id it would only need to query the index. I imagine the most common query we will do is the "give me all repos/refs that have changed since CURSOR" since our indexing systems will poll that. For indexing systems that doesn't have to be the fastest possible, since that isn't an interactive request. repohascommitafter: is interactive, but I suppose that doesn't necessarily have to query this table (although an index just for it does make sense)

> > Lets store this as a bytea type rather. More compact and the same type that pgcrypto returns for hashing. Something to take into account is git is moving to sha256 in the future, so we can expect bigger digest strings.
> 
> How is `bytea` more compact?

Instead of storing the hex encoded string (40 char), you store the digest value (20 bytes). For sha256 it is 64 chars vs 32 bytes. So half the size. Also the same type that pgcrypto uses (although that isn't the best reason). After more thought it may be better to just use `text` for easier interactive use of the table.

> > Good point. I'm torn between not having entries for these (and keeping cloning info separate) and having a nullable column. I think I prefer the former.
> 
> If we have a separate `git_refs` or `git_branches` table and normalize the relationship between `git_commits`, we can use that for the cloning status since I believe every repo has git refs.

Empty repos do not have refs.

> > This can't be a primary key, a commit can appear in more than one repo.
> 
> We can have a composite primary key on `(repo_id, sha)`.

:+1:.

> > Most of these fields I don't expect us to query on (except for commiter_date). Is it worth storing them when they can be accessed from git?
> 
> We don't need to store these now, but we could. The whole point of this table is to reduce load and network round trips to git server. Are you concerned with storage or performance?

I think git server is still the best source of truth, but that does make sense. My initial vision for this was to target operations we do across repos on gitserver (eg resolve revision, find out what has changed, etc). However, if we did store more information we could avoid git server completely for displaying search results (I think we do though?)

> > This field is useful, but ideally I'd want a serial field which we can rely on to order events. ie if I am an index server and last time I did an index the serial field was N, give me all repos where serial > N. timestamps don't give the same gaurentees.
> 
> We can add an auto incrementing ID to the table, but not sure I understand the need for it. The way I was thinking of this, each time `repoUpdate2` is called in gitserver, we upsert commits and refs to these tables.

Target use case: zoekt last indexed at version N. Tell me all repos which have changed since N and give me N'.

**Comment by felixfbecker** [comment] 2020-06-24 08:59
I trust you all to find the right solution, but out of curiosity: How much of this problem would still be an issue if the frontend didn't do N+1 queries in general? For a side project I was able to implement all git data queries with batching, but obviously the scale here is very different. Would we still need this if the frontend would only send e.g. 1 batched git exec request with all the commit hashes it needs metadata for? Is that generally something we're also looking to solve at some point, also for non-git things?

**Comment by keegancsmith** [comment] 2020-06-24 09:17
Frontend doing a single graphql query in most cases (so that the backend can avoid extra work) would help with perf. It would require quite a bit more work on the backend part to know to avoid extra work in that case as well. However, this proposal is more about: knowing what HEAD is for 10k repos quickly, knowing which repo was last changed out of 50k total, etc. So it is targeting our aggregate operations where currently we avoid it (and provide a worse experience), or it is just slow on large installations.

Note: what you propose in general is useful, since it would allow us to do less work no matter if we are talking directly to git or to the DB.

**Comment by tsenart** [comment] 2020-06-24 10:18
Related:
- https://gqlgen.com/reference/dataloaders/
- https://github.com/graph-gophers/dataloader

**Comment by efritz** [comment] 2020-06-24 12:49
Another use case:

Precise code intel services have this table already but without any useful metadata. I think the table schema you proposed above got almost everything, but would like to suggest you add a parent(s) column so we can trace ancestry and descendants: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/codeintel/store/ctes.go#L45:52

It would be good to have gitserver own this new table and be able to remove the one code intel uses. We may also like to write some additional state to commit rows(which LSIF indexes are available at this commit). I’m not sure if this is better as a typed column or as an unstructured blob that other parts of the system can write keys to.

**Comment by keegancsmith** [comment] 2020-06-24 13:23
> Precise code intel services have this table already but without any
> useful metadata. I think the table schema you proposed above got
> almost everything, but would like to suggest you add a parent(s)
> column so we can trace ancestry and descendants:
> https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/codeintel/store/ctes.go#L45:52

Including parent sounds good since it would help your use case. However,
the initial use case for this won't be putting all commits into the
table. In particular we are focussed on cross-repo queries, and those
usually are about a particular ref. This sounds like a query you do on a
particular repository?

Additionally having all commits is bit more of a tricky beast to get
right as well, so not sure if we will want to expand scope. We should
probably break this discussion out, but have you had any performance
issues with the CTE approach? If so, I imagine something more targetted
to git and a DAG would be much faster. (See work on Git Commit Graph by
Microsoft or Reftable by Google).

> We may also like to write some additional state to commit rows(which
> LSIF indexes are available at this commit). I’m not sure if this is
> better as a typed column or as an unstructured blob that other parts
> of the system can write keys to.

I would suspect this is better as a seperate table you join on by
commit? However, for practicality I can imagine this table having a
bunch of extra columns maintained by other services as reasonable.

**Comment by efritz** [comment] 2020-06-24 15:10
> This sounds like a query you do on a particular repository?

Yes. We have a source rev on a repo and need to know the closest rev in either direction with some property.

Really, what I'd want to see for my use case is to be able to add some metadata flags on particular commits, and then find the nearest commit with a particular flag from some arbitrary commit. Maybe this means loading all commits into the table, maybe not.

I'll be writing an RFC soon, let's continue discussion in https://github.com/sourcegraph/sourcegraph/issues/11627.

**Comment by tsenart** [comment] 2020-06-25 10:58
@keegancsmith, @efritz, @asdine: I updated the title and issue body, PTAL. @asdine will be working on this in 3.18.

**Comment by keegancsmith** [comment] 2020-06-25 12:23
### Context

Just want to make sure we have the right reasons for tackling this. Right now the ones listed I'm not so sure about, but I believe we have _exact_ use cases we should target. By listing out some exact current use cases, and some potential future use cases I think that would best inform the design of the schema, how quick it needs to update, and what is put in the table.

> Lots and lots of N+1 queries.

What are examples? Off the top of my head I can't think of one outside of what code intel does to find ancestor information. This would require all commits in the DB.

> Slower than having it indexed and queried in Postgres.

How much slower? When doing a query within a repo it is fast enough. I think we should emphasize that this is important for aggregating across repositories. For example the `repohascommitafter` feature. But when using indexed search we don't speak to gitserver. When doing non-indexed search we do speak to gitserver (to do a resolve rev), but this is an insignificant portion of time compared to the actual search. So just looking for some more concrete use cases.

Another example is just resolve-rev HEAD which is done all over our codebase. This would indeed be faster in postgres. But its already fast in gitserver and never the bottleneck in generating a response for a user.

> Harder to work with for engineers.

This is the biggest plus, potentially unlocking other features which are easier to implement. It would be great if we could work out some examples were this would make it much easier to implement. Ideally product focussed, but also backend focussed.

### Open Questions

To me the biggest open question isn't listed. How do we update the table after a git fetch? I'm concerned about performance here. In particular I would target something like the kubernetes repo (including all pull request refs) to help guide this. There are then other concerns about detecting things gone wrong (eg we git fetch but fail to update table, etc. How to ensure we converge on reality in face of failures). But those seem much more solvable, but useful to think about when designing our approach.

- If we just focussed on HEAD, this would be easy to do.
- If we just focussed on small number of branches, this would be easy to do.
- If we just focussed on all refs, I imagine an approach where we parse in the refs before and after a fetch would be performant. We may even get away with just an upsert against the table after parsing in all refs.
- If we did all commits, I doubt just upserting would work. This would be quite tricky to get right.

Notice how answering this question also decides which use cases would be applicable. eg if we can't do all commits, then we wouldn't be able to support the above code intel use case.

**Comment by tsenart** [comment] 2020-06-25 13:09
> This is the biggest plus, potentially unlocking other features which are easier to implement. It would be great if we could work out some examples were this would make it much easier to implement. Ideally product focussed, but also backend focussed.

I think that by itself, the requirement from the code intel team for ancestry look up is enough to justify evaluating if this is possible. The other examples you have listed are good too. Another thing: We considered later on working on HA for gitserver. If Postgres already has most information that gitserver would write to, then we could get away with not doing that work and rely on services across Sourcegraph querying from the database directly (rather than gitserver). But that may require us storing more than just commits.

As for product features, some ideas that would be easier to do with pure SQL queries:

1. Code Insights (cc @felixfbecker) comes to mind, but that would probably require storing file contents too, ala https://github.com/src-d/gitbase/blob/master/docs/using-gitbase/examples.md#get-commits-per-committer-per-year-and-month
2. Scalable diff search across repos?
3. Scalable commit search across repos (i.e. git log -S)?
4 ... Do you have other ideas?

> If we did all commits, I doubt just upserting would work. This would be quite tricky to get right.


We should test this assumption. I'm sure scale challenges will pop up, but are they insurmountable with a pure Postgres approach?

**Comment by felixfbecker** [comment] 2020-06-25 13:21
> Code Insights (cc @felixfbecker) comes to mind, but that would probably require storing file contents too, ala src-d/gitbase:docs/using-gitbase/examples.md@master#get-commits-per-committer-per-year-and-month

I don't immediately see how code insights could benefit from this directly - code insights usually doesn't care about commits and their metadata, but about the data _at_ those commits, i.e. search results which depends on file contents (like you mentioned), LSIF data (which is huge and stored per commit), external data, ... Maybe the aggregated numbers could be stored to be joined on the commits, but not all code insights have commits on the X axis (or cartesian axes at all), so code insights would likely use a more generic data format like just storing the JSON data of the chart returned by the extension. Specific data sources for _some_ code insights could be stored in the DB though, e.g. LSIF total diagnostic counts per commit, but that would be more of an optimization/implementation detail of the LSIF GraphQL API. Code insights will likely never do SQL queries directly, because third-party insights should probably not have direct SQL access to our database.

**Comment by keegancsmith** [comment] 2020-06-25 14:05
I think over all listing the different examples, then grouping them by what features they would require would be big. Most of the examples you gave are much more than just commit information.

> > This is the biggest plus, potentially unlocking other features which are easier to implement. It would be great if we could work out some examples were this would make it much easier to implement. Ideally product focussed, but also backend focussed.
> 
> I think that by itself, the requirement from the code intel team for ancestry look up is enough to justify evaluating if this is possible. 

I agree we should evaluate if possible.

> Another thing: We considered later on working on HA for gitserver. If Postgres already has most information that gitserver would write to, then we could get away with not doing that work and rely on services across Sourcegraph querying from the database directly (rather than gitserver). But that may require us storing more than just commits.

This would require us storing more than commits. It would require emulating git essentially. Git's access patterns aren't the best when it comes down to actually using a "remote" blob store. Unless we start implementing some git algorithms in SQL, but that makes me think this is not a good route.

> 1. Code Insights (cc @felixfbecker) comes to mind, but that would probably require storing file contents too, ala [src-d/gitbase:docs/using-gitbase/examples.md@`master`#get-commits-per-committer-per-year-and-month](https://github.com/src-d/gitbase/blob/master/docs/using-gitbase/examples.md?rgh-link-date=2020-06-25T13%3A09%3A45Z#get-commits-per-committer-per-year-and-month)
> 2. Scalable diff search across repos?
> 3. Scalable commit search across repos (i.e. git log -S)?
> 4. ... Do you have other ideas?

All of these require storing file contents / or more. What exactly you would store would change per idea you had for it to work well. I don't see how we could extend this to get it "for free", nor how it would scale nicely unfortunetly. I don't have many ideas to be honest, which is why I am trying to keep this simple. Do you have any other ideas?

> > If we did all commits, I doubt just upserting would work. This would be quite tricky to get right.
> 
> We should test this assumption. I'm sure scale challenges will pop up, but are they insurmountable with a pure Postgres approach?

The issue is somewhat independent of DB, but DB choice will dictate what is the reasonable approach. I agree we should validate with a PoC.

**Comment by tsenart** [comment] 2020-06-25 16:01
> Most of the examples you gave are much more than just commit information.

Should we then investigate this as well as part of this work? Or is there a subset of all of this that you have in mind which you'd feel more comfortable with us pursuing in 3.18?

**Comment by keegancsmith** [comment] 2020-06-25 19:31
I think exploring indexing all commits (but not contents) is practical and scoped enough. It can also be extended to indexing more data (like contents or diffs). It will also allow us to do ballpark math to work out how big our postgres cluster will be, cost, and any db sharding that may require / etc.

Personally I'm still enamoured by keeping the dataset as small as possible so we can keep using a single postgres DB. All the use cases I know of today (except for code intels) are solved by this. Less chance of running into unknowns, so more chance of shipping sooner. If I was tasked with doing this I'd just focus on keeping track of HEAD (or other refs in the version contexts). That seems shippable as a full project in an iteration and a half. It also gives us confidence in doing more and can be extended.

**Comment by tsenart** [comment] 2020-07-07 12:15
After discussing live with @keegancsmith and @asdine, we determined that addressing this to fix `repohascommitafter` performance and answering the question "which repos changed since I last looked" (i.e. for Zoekt and LSIF indexing) isn't enough of a priority at this point in the context of RFC 151 roadmap, so I'm removing this from the milestone and roadmap.

**Closed** 2023-01-02 05:55 UTC
Labels: perf, team/core-application, estimate/10d
