### ISSUE TITLE
site ConfigMap changes on sourcegraph.com still require a pod restart

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#14019] opened 2020-09-22 00:52 UTC
https://github.com/sourcegraph/sourcegraph/pull/13646#issuecomment-696451666 was merged which should have fixed this but for some reason it doesn't work still.

The configmap was updated properly, but the file on disk didn't appear to be updated so the frontend couldn't do anything.

This was the case for a little over an hour - maybe the cache times mentioned here need to be lowered or something? https://kubernetes.io/docs/concepts/configuration/configmap/#mounted-configmaps-are-updated-automatically

**Comment by keegancsmith** [comment] 2020-09-30 08:45
Fixed by https://github.com/sourcegraph/deploy-sourcegraph-dot-com/commit/2f3e74fb5c57b20975f36d0d60b9451725c1c1d1

Updating documentation for other installations at https://github.com/sourcegraph/sourcegraph/pull/14297

Note: updates still take about 1min. This is as documented in the k8s documentation.

Root cause: using subPath prevents kubernetes updating configs.

**Closed by keegancsmith** 2020-09-30 08:45 UTC
Labels: team/distribution
