### ISSUE TITLE
increasing limit twice leads to broken query with 2 count filters

### ISSUE THREAD

**Issue by stefanhengl** [sourcegraph/sourcegraph#17909] opened 2021-02-02 07:48 UTC
I ran a query and increased the limit twice. It seems as if we don't respect existing count filters?
<img width="828" alt="image" src="https://user-images.githubusercontent.com/26413131/106568018-fb129000-6532-11eb-9d30-632663b7e646.png">

**Comment by lguychard** [comment] 2021-02-02 12:12
I think this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/17789

**Comment by limitedmage** [comment] 2021-02-02 16:28
Yes, dupe of #17789.

**Closed by limitedmage** 2021-02-02 16:28 UTC
Labels: team/search
