### ISSUE TITLE
Ability to delete branches pushed by Sourcegraph to code hosts when a batch change is closed/deleted

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50299] opened 2023-04-03 17:00 UTC
"Source control hygiene" -- there's a lot of extra cost associated with keeping those branches around

**Comment by BolajiOlajide** [comment] 2023-05-30 22:11
Duplicate of #50354.

**Closed** 2023-06-01 19:47 UTC
