### ISSUE TITLE
Go code intelligence failing in browser extension

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#1147] opened 2018-11-27 21:31 UTC
* Go to https://github.com/sourcegraph/sourcegraph/blob/master/pkg/env/env.go
* Attempt to hover, no tooltips show up. Error in console:

![selection_004](https://user-images.githubusercontent.com/1646931/49112837-abe0be80-f248-11e8-9899-70ddedb10fd4.png)

This is with "Use extensions" checked. If the box is unchecked, I see a "Error fetching hover from language server" error in the UI.

Hovers on gorilla/mux seem to work fine.

**Comment by ijsnow** [comment] 2018-11-27 21:39
@chrismwendt do you know what could be going on here? I've seen errors related to a workspace on TS files too so don't think its specific to your go extension work but you may know more than me about extension API changes.

**Comment by ijsnow** [comment] 2018-11-27 21:44
This appears to be the same issue as https://github.com/sourcegraph/sourcegraph/issues/1146. The issue is that the commit isn't being resolved. Could this be a repo updater issue?

**Comment by chrismwendt** [comment] 2018-11-27 21:45
Sourcegraph.com's sourcegraph/sourcegraph's HEAD is ~13 hours old. The most recent commit was ~1h ago.

![image](https://user-images.githubusercontent.com/1387653/49113477-8785e180-f24a-11e8-9020-abcbb6fd9446.png)

![image](https://user-images.githubusercontent.com/1387653/49113497-940a3a00-f24a-11e8-8735-f34823e29131.png)

**Comment by nicksnyder** [comment] 2018-11-27 21:52
Sourcegraph.com doesn't run repo-updater logic, so we depend on updates happening when a user directly visits the repo. It does seem to be the case that the repo is not getting refreshed when accessed directly.

**Comment by ijsnow** [comment] 2018-11-27 21:54
I thought that the `ResolveRev` graphql requests kick off updates in the background. Is that repo-updater logic? How can the browser extension do this without the repo-updater logic?

**Comment by nicksnyder** [comment] 2018-11-27 21:57
> I thought that the ResolveRev graphql requests kick off updates in the background.

Yes, it is supposed to

**Comment by nicksnyder** [comment] 2018-11-27 22:10
I am unable to reproduce the original issue as described; however sourcegraph/sourcegraph is still not updating which is still a bug.

**Comment by ijsnow** [comment] 2018-11-27 22:43
Enabling the [debug extension](https://sourcegraph.com/extensions/isaac/debug-extension), you'll see that the browser extension is able to display tooltips and decorate the line so the problem/error displayed is coming from the go extension. My assumption is that the go extension is failing because it can't fetch the file at the provided revision. Does that sound plausible to you @chrismwendt?

**Comment by chrismwendt** [comment] 2018-11-27 22:47
Yes, the Go extension is unable to download the zip archive of the repository at that exact commit because that exact commit doesn't exist on Sourcegraph.com.

The Go extension could fall back to GitHub's codeload endpoint, but that would require either the raw API to support lightweight HEAD requests and/or changes to the way zips are fetched in the Go buildserver code.

**Comment by ijsnow** [comment] 2018-11-27 22:51
Ok, so that seems like feature work on the Go extension that would probably be unnecessary without this repo-updater bug. I'll close this issue. If we want to do that work, we can link to this issue from an issue for that specifically. In addition to this, we could use this issue as a reference for more robust error handling/displaying to the user.

**Closed by ijsnow** 2018-11-27 22:51 UTC
Labels: browser-extension, bug
