### ISSUE TITLE
Maximum number of folders/files displayed in tree view on repo is 2500

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#41750] opened 2022-09-19 16:35 UTC
- **Sourcegraph version:** 3.42.1
- **Identified by:** https://github.com/sourcegraph/accounts/issues/6716

#### Description

When a repository directory has > 2500 folders+files, the view is cut off and does not indicate to the user that they are not seeing all the folders/files in that repo.

#### Steps to reproduce:

1. On a repository with more than 2500 files, navigate to the repository (and optionally sub-folder if the folder with more than 2500 files/folders is not the top folder)
2. Wait for page to load and notice the list of file and folders is cut off after 2500

#### Expected behavior:

The page shows all files/folders.  Or, alternatively, it shows an indicator if the list was cut off with a way to expand the list to show more/all files/folders.

#### Actual behavior:

The view is cut off arbitrarily [at 2500](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/repo/tree/TreePage.tsx?L150:28).

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

/cc @jplahn @ryphil

**Comment by mrnugget** [comment] 2023-07-24 10:27
Code has changed. Next step would be confirm that this is still an issue.

**Comment by mrnugget** [comment] 2023-07-26 12:39
Alright, steps to reproduce:

1. Add this repository to your instance: https://github.com/sourcegraph-testing/lotta-files
2. Open repository

Good news: we display *more than 2500* files.

Bad news: we display ~3247 files. And, what made me laugh out loud is that we display the last file in the sidebar as a folder with this message in it:

<img width="587" alt="screenshot_2023-07-26_14 39 02@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1185253/7456a28b-fb85-4304-b71f-5fa22e828158">

**Comment by mrnugget** [comment] 2023-07-26 12:43
Correction: it is ~2500 files. I miscounted. Here is the code: https://github.com/sourcegraph/sourcegraph/blob/e541001f732aea5109ca90cfe30917863d581664/client/web/src/repo/RepoRevisionSidebarFileTree.tsx#L626-L628

It's also worth noting that GitHub doesn't display more than 1000 files: 
<img width="792" alt="screenshot_2023-07-26_14 42 49@2x" src="https://github.com/sourcegraph/sourcegraph/assets/1185253/aa5b40fc-7c9a-4327-86c6-635a7c7cc976">

**Comment by fkling** [comment] 2023-07-26 12:57
I think we can still improve the messaging and include the file count like GitHub does, but afaik we do not currently provide that information from the server.

**Comment by mrnugget** [comment] 2023-07-26 14:10
> but afaik we do not currently provide that information from the server.

We do have that information though, at least in some sense. Backend code actually reads _all_ files from a folder and only then applies filtering to it. So we do know how many files there are in the folder.

The problem is that we do `limit` before we do `filter`: we first cut down to 2500 files, _then_ filter that list, vs. the other way around.

https://github.com/sourcegraph/sourcegraph/blob/584e29dce181852cdc2634bb91fbc2b9b3007e71/cmd/frontend/graphqlbackend/git_tree.go#L48-L74

**Comment by mrnugget** [comment] 2023-10-12 09:56
won't fix (for now)

**Closed by mrnugget** 2023-10-12 09:56 UTC
Labels: bug, customer
