### ISSUE TITLE
Insights: add single frontend datapoint to backend insights so you don't have to wait a month to get "current" results

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#24186] opened 2021-08-20 07:31 UTC
_This is a stretch issue, and if necessary the user can non-optimally solve this now by running the search in sourcegraph themself._

Because we now have a backend, if you wanted to "use the frontend" to help with insights, all we really need is a single present-time point. This means it doesn't matter how many repos you include because we can use the normal search API to just run the search. 

Visual concept of what I am imagining: 

![image](https://user-images.githubusercontent.com/11967660/130196645-f5cffdd3-3955-4d20-b9e0-70ab83a2e7a1.png)

This was never _not_ part of the "historical insights over all my repos" concept (there's no reason a user wouldn't want to see today but would want to see the first of the month) but it was cut for scope originally. 

I will defer to others as to whether we could get this done in time, but it would be awesome and our users would love it (and we need to do this in 3.32 if we don't do it in 3.31). The use case of "actively tracking a migration" means a user cares about these present-time points as well as the history. 

The considerations (reasons it might be trickier/not possible in the 2.5 days next week): 
- it needs to match filters that might be on the insight (so we can't just use the data series query; we also must honor the filters)
- it needs to match the backend (what this means, specifically, is that it should modify from just an "indexed search" to "an indexed search with `archived:yes fork:yes`attached, since that's what the backend currently does. Of course, if the insight data series query has a `fork:no` in it, this should override that).

**Comment by felixfbecker** [comment] 2021-08-20 14:28
So my gut assessment of this is that the part of actually doing the query for the latest point is easy, but the points you raised about filters and `archived:yes fork:yes` is a major complication.

- We can't just add a `repo:` operator for the include filters to the query with string concatenation, because that would be `OR`ed with the existing `repo:` operators (set union), not `AND`ed (set intersection).
- We must only append `archived:yes` and `fork:yes` if those operators are not already specified, otherwise we would get a duplicate operator error. We could do a naive regex check for the presence of the operator in the query, but that would break down if there are parenthesized `AND`/`OR` expressions where only one part of the query already has the operator already.

We could technically use the webapp's search query parser to analyze the AST and transform it accordingly, but it would probably be very complex.

@rvantonder do you have any thoughts on how to do this best?

**Comment by Joelkw** [comment] 2021-08-20 16:22
@felixfbecker 

I understand the archived/fork situation is a bit complicated – I'm wondering if it would be all that bad to not address it directly in 3.31 even, since we already note on the query field setup for the insight "if you want to set up an insight that matches searches today, make sure to include fork:no archived:no" so we've already given folks early warning, and we will have a docs page like "FAQ why do my insights not match a sourcegraph search" that covers this stuff (and we could note the latest-in-time point is still a search). 

For the `repo:` question, I actually think it's easy because in my tests it seems like we `AND` repos? Example: 38 results for joel in [this search](r:sourcegraph/about|sourcegraph/sourcegraph joel count:all ), 34 results in [this search](https://k8s.sgdev.org/search?q=context:global+r:sourcegraph/about%7Csourcegraph/sourcegraph+joel+count:all++r:sourcegraph/about&patternType=literal), 4 results in [this search](https://k8s.sgdev.org/search?q=context:global+r:sourcegraph/about%7Csourcegraph/sourcegraph+joel+count:all++r:sourcegraph/sourcegraph&patternType=literal). 

Given that, if we said "let's just not worry about archived/forked", could this be possible for 3.31?

**Comment by felixfbecker** [comment] 2021-08-20 16:42
> since we already note on the query field setup for the insight "if you want to set up an insight that matches searches today, make sure to include fork:no archived:no"

I'm not sure I understand how that makes things easier – if they added the operators (as that help text says) it would error with a duplicate operator error if we don't add complex logic. Or if we don't add the operators automatically for the last data point to avoid duplicate operator errors (and don't add complex logic either), the last point would likely always be way off the previous data values for no apparent reason if the user didn't make them explicit in the query (the help text doesn't say that you MUST provide them in all cases).

> For the repo: question, I actually think it's easy (or easier, at least) because in my tests it seems like we AND repos? Example: 38 results for joel in this search, 34 results in this search, 4 results in this search.

Looks like you're right (counter to what I would have expected). That part is indeed a bit easier then.

**Comment by Joelkw** [comment] 2021-08-20 20:48
> the last point would likely always be way off the previous data values for no apparent reason if the user didn't make them explicit in the query (the help text doesn't say that you MUST provide them in all cases).

@felixfbecker What if we make this more explicit? Again, I'm just thinking of lightweight ways we could get this into the release, because values do change in short times even for long-running migrations and it'd be really useful (especially if you were in the second half of the month). 

Right now we have something like "tip: include fork:no archived:no" – I would be okay with changing this to a much bolder callout (with color/border/design treatment), something like "You **must** include `fork:no archived:no` if you want the historical searches to mimic the default behavior of sourcegraph searches. If you don't include these, you may see a "drop" between the historical data and the rightmost datapoint due to present-time searches ignored forked and archived repos." 

Is it the cleanest message or long term solution? No. But is the experience of viewing the insight (which we now have data to show happens way more often, like greater than 5-10x more often, than making an insight) significantly improved if it always shows the current value? I think so strongly!

**Comment by rvantonder** [comment] 2021-08-20 21:55
> @rvantonder do you have any thoughts on how to do this best?

Code insights needs to think about what set of expressivity/operations they want to support, and user-triggered operations on those. It sounds like that representation is currently something along the lines of "a subset of the search query language and user operations that add more repos, which we internally do with or-operations". 

> We could technically use the webapp's search query parser to analyze the AST and transform it accordingly, but it would probably be very complex.

Indeed. I think it's usable right now, but it doesn't have a `toString` function yet, which I think you would find pretty convenient. Anyway, you're going to have to choose either (a) deal with the level of complexity of expressive power that you want to support in code insights, or (b)say "no we don't want to support that level of expressivity yet because we're not ready to deal with subexpressions/trees". I think it's dangerous to go with (a) but not do it in a principled way. That said, for this parcticular issue, I don't think this it's that intimidating, nor "very complex", but you do need to be principled in what you do. Example:

- We allow users to add repos. We're going to support that with some kind of `or` operation. Let's call the result of this thing `subexpr`
   - you manipulate the query accordingly, I think you use a text representation for this currently
- We want to include `archived:<whatever>` and `fork:<whatever>`
  - if this is all you want to do, and want it to apply to all of `subexr`, all you do is create the query `(subexpr) archived:<whatever> fork:<whatever>`. I.e., you just wrap `subexpr` in parens, and the filters for `fork` and `archived` will apply globally. The way to think about this is that filters are distributed into the subexpression. You could _probably_ get away with doing this textually today, if you only need to add some `archived` and `fork` filters to a `subexpr`. I would not recommend that (at all) as a long term strat. Instead, you can compose an expression using our internal types (nodes) in the frontend, and then pass that to the (currently absent) `toString` function that will make sure it's valid.
 
Now, if you start saying "ok but now I want to include `repo:<pattern> fork:yes` or `repo:<pattern> fork:no`, well now you're going to have to build the tree in the shape that corresponds to this meaning like `(repo:foo ...) or (repo:bar ...)`. I don't get the sense that you need this today, but just laying out that: There is no shortcut or way to do this sort of manipulation at a textual level, that's simply the cost of having more expressivity and dealing with trees. At the same time constructing the query with nodes in a tree isn't (or shouldn't be) a big a deal.

> "FAQ why do my insights not match a sourcegraph search"

So in general it is OK for code insights to have its own set of rules and internal representation for queries. But, I think it's a worthwhile investment to think about translating a code insights representation to an equivalent sourcegraph search query. E.g., expose a button on output that shows what a code insights query looks like when you run it to sourcegraph (i.e., it would add all the hidden defaults that diverge from a sourcegraph search and make it explicit what's going on). And then test that :-) Otherwise, I could easily see this spin off to a FAQ with ad-hoc set of rules that's not enforced or implemented anywhere, and then you get divergence, and divergence leads to confusion and bugs. Following from my explanation above, for this specific `fork/archive` business, and based on my current assumptions of the simplicity in code insights queries, you can just generate the query `(<code-insights query>) archived:no fork:no`

**Comment by felixfbecker** [comment] 2021-08-24 11:17
> if this is all you want to do, and want it to apply to all of subexr, all you do is create the query (subexpr) archived:<whatever> fork:<whatever>. I.e., you just wrap subexpr in parens, and the filters for fork and archived will apply globally. The way to think about this is that filters are distributed into the subexpression. You could probably get away with doing this textually today, if you only need to add some archived and fork filters to a subexpr. I would not recommend that (at all) as a long term strat. Instead, you can compose an expression using our internal types (nodes) in the frontend, and then pass that to the (currently absent) toString function that will make sure it's valid.

@rvantonder that is great insight, thank you so much! I wasn't aware the query could just be parenthesized like that.

However, I just tested this and it doesn't seem to avoid the "duplicate operator" error if the user specifies the `archived` filter manually in the query. Let's say the user said "I **do** want to include archived repos" by making the query (`subexpr`) `test archived:yes`, and we always apply `archived:no` to ensure consistent behavior between unindexed (historical) and indexed (latest point) search. That would make the final query `(test archived:yes) archived:no`, which still results in the error "Unable To Process Query. Field "archived" may not be used more than once". See [test search](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph+%28test+archived:no%29+archived:yes&patternType=literal).

![image](https://user-images.githubusercontent.com/10532611/130605526-04d7d79f-e91f-439a-8011-2c6dc8927280.png)

So it seems the parenthesis trick doesn't actually help us here...


I also want to point out that to my understanding the root problem here is that indexed and unindexed search have different defaults in search for `archived` and `fork` (indexed excludes by default, unindexed includes by default). I think that is unexpected behavior even ignoring code insights and imo the ideal fix for this would be to remove that discrepancy in search. Would you agree with that @rvantonder? This discussion was from the perspective of "is there a quick workaround we can do in code insights" for this discrepancy. Ideally, I really would prefer us to not be in the business of manipulating search queries with operators at all, both from a technical and a UX perspective, making code insights searches === search searches.

We still, of course, need to modify the revision/time dynamically, but if we can do that in a robust, clean, search-team-blessed way (also thinking of supporting search contexts etc) and otherwise leave the search query alone (no workarounds for fork/archived etc) that would be ideal.

To @Joelkw: I think at this point it seems rather risky to me to build this feature into the release before Beta even if we find a workaround, as there may be bugs in it we can't find in time. So we should probably shift this discussion from "what is a quick workaround" to what is a "proper" fix for this, or one that could take longer than just a day.

**Comment by Joelkw** [comment] 2021-08-24 22:17
@felixfbecker yep, I'm with you on that 100% – I don't think it makes sense to aim for this release. I think we do need to answer the question "why would customers check insights weekly" with something like this by 3.32 – good to have this info for the next few weeks!

**Comment by coury-clark** [comment] 2021-08-30 21:26
re: query syntax manipulation
This search query issue is already present in code insights with how we naively append a `repo:` to the search query, and how we run global searches for 'current' time recordings (the fork / archive issue) Therefore, I've opened #24432 to solve that separately.

With respect to the issue of generating a data point for the current time:
1. We probably cannot get away with running this just-in-time. On any reasonably sized Sourcegraph installation the just-in-time query would take much longer than is acceptable for a user loading a page of insight charts.
2. We can keep daily snapshots without too much trouble and union them against the normal set of time series data. We have much of the architecture in place to do something like this - it would likely just require keeping some extra state on the insight tables and slightly modifying one of the recorders. This would be very fast at query time.
3. The filters on an insight are all post-processed, so I don't see any reason that would impact the underlying query we would need to snapshot.

**Comment by Joelkw** [comment] 2021-09-02 02:45
@coury-clark Thanks for these thoughts!

The snapshot sounds good to me as enough of a reason to "check your insights daily" (a 30x improvement over monthly :) ) and at the right level of complexity/user value tradeoff for us for 3.32. I agree with this plan. 

I assume snapshots would handle the "discrepancies" between old points, like whether the other points include forks and the snapshot includes forks?

In the short-medium term (2-3 releases from now), would this let us go in a direction that lets you "refresh live" an insight after loading from the cache, at which point we'd run just that insight's search if you asked for it (a lot of data platforms have a similar "refresh" button for the purpose of "use a cache but if a user really wants current data, they can trigger a refresh now).

**Closed** 2021-09-09 19:12 UTC
Labels: team/code-insights, feature, backend, insights-3.32
