### ISSUE TITLE
Sourcegraph UI Sometimes Displaying Stale Repository History 

### ISSUE THREAD

**Issue by tistru** [sourcegraph/sourcegraph#15026] opened 2020-10-23 19:59 UTC
Reported by: https://app.hubspot.com/contacts/2762526/company/554275594

- **Sourcegraph version:** 3.18

Customer is reporting that viewing a repository's landing page sometimes returns stale history. The "changes" list sometimes shows the last commit as "8 days ago" when in reality it was "14 hours ago". Seems more like a caching issue as sometimes it's correct and others it's not. No issues with the repo-updater and the latest commits are available. Issue seems limited to just the UI displaying the incorrect data.

#### Steps to reproduce:

1.Navigate to different repos from the repo viewer and examine the commit history
2. Compare to code host value and note some missing updates

Example page:
![image](https://user-images.githubusercontent.com/25908288/97048825-af6e4480-1548-11eb-8d00-0c28ab302581.png)

#### Expected behavior:
Repo landing page history should reflect truth with regards to commit history.

#### Actual behavior:
Sometimes repo landing page shows old history that does not reflect latest updates to repo. Behavior is inconsistent as sometimes it shows correctly

**Comment by felixfbecker** [comment] 2020-10-23 20:05
Without a clear reproduction, can we get any details?
- Does it get updated with a page reload 🔄?
- Is a `TreeCommits` request made in the network tab, and does it show the stale data? (if yes, this is a backend issue for `team/cloud`)

**Comment by tistru** [comment] 2020-10-23 20:13
Sure @felixfbecker . I followed up with the customer and requested this info. I will update the issue details above once I hear back.

**Comment by pdubroy** [comment] 2021-06-25 13:07
I'm going to close this since we are missing details that would help us debug the issue. Please feel free to re-open if/when we have those details.

**Closed by pdubroy** 2021-06-25 13:07 UTC
Labels: team/frontend-platform
