### ISSUE TITLE
Browser extension does not detect expanded diff views on GitHub

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#18337] opened 2021-02-16 17:12 UTC
### Steps to reproduce

- Navigate to a PR with large diffs that need to be expanded ([example](https://github.com/sourcegraph/sourcegraph/pull/17964/files))
- Click "Load diff" on a large diff
- Note that "Code view added" is _not_ logged to the console, and Sourcegraph extensions do not work

**Comment by mrnugget** [comment] 2021-04-08 09:05
Ran into this again and realised that this is the bug that's been haunting me forever: https://sourcegraph.slack.com/archives/CHXHX7XAS/p1617870765285700

I personally think this is a *high priority* bug since it makes the whole use-Sourcegraph-for-reviewing-code experience really frustrating.

**Comment by Joelkw** [comment] 2021-04-08 16:13
Thanks @mrnugget for bumping. Oddly still haven't heard this from any customers, but given that you've now run into it twice I'll note this is higher priority.

**Comment by efritz** [comment] 2021-04-08 16:35
I'm also a user of Sourcegraph and I've run into this many times (look at the size of my PRs).

**Comment by mrnugget** [comment] 2021-04-09 08:26
> Oddly still haven't heard this from any customers, but given that you've now run into it twice I'll note this is higher priority.

I can only speak in anecdotes here, of course, but "hover tooltips sometimes stop working" is something that I've heard other Sourcegraph colleagues say in the past few years. Of course they might not all point to this issue, but the point I'm trying to make: I think more people ran into this than there are tickets describing the issue.

Maybe because it's such a hard thing to reproduce and nail down and sometimes it might even be fixed with a reload (because you reviewed some files and then something _is_ expanded when you reload etc.)

**Comment by kkom** [comment] 2021-05-02 22:30
Hey, I'm a potential customer and I strongly agree with this from @mrnugget :

> I personally think this is a high priority bug since it makes the whole use-Sourcegraph-for-reviewing-code experience really frustrating.

now reviewing a PR I have to jump to the sourcegraph native diff view (without the github context) or even worse - to an IDE

a big piece of the whole value prop of code intelligence in one place disappears...

**Comment by Joelkw** [comment] 2021-05-04 03:26
Hey @kkom ! Thanks for the feedback. We've already moved this up in our priority list, and it should get resolved in the next 2 weeks or so (sometimes there's a wait in Chrome/FF/Safari approval for new versions of our browser extension). Our team is at 30% reduced capacity this month, so apologies for the delay.

**Comment by kkom** [comment] 2021-05-04 13:16
Thank you @Joelkw !

**Closed** 2021-05-12 01:25 UTC
Labels: browser-extension, bug, team/extensibility
