### ISSUE TITLE
New component for complex dropdowns

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19022] opened 2021-03-10 09:32 UTC
More info TBD.

- New component that meets shared needs for interactive dropdowns:
  - Filters, contexts, rev selection, repo selection, etc.

**Comment by pdubroy** [comment] 2021-11-19 12:57
Closing as I believe this is a dupe of #22053.

**Closed by pdubroy** 2021-11-19 12:57 UTC
Labels: accessibility, needs-design, design-debt, team/frontend-platform, RFC-345
