### ISSUE TITLE
Non-low-latency connection to PostgreSQL database causes problems in initial DB migration

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#4097] opened 2019-05-17 04:13 UTC
When there is ~150-200ms+ of latency between Sourcegraph and the PostgreSQL DB host (most common when using external databases per https://docs.sourcegraph.com/admin/external_database), the first-run DB initialization steps are likely to fail. This can happen if using us-east-1 from the West Coast, using a home Internet connection, etc.

The reason is that there are many query roundtrips to perform all of the migrations' queries, and the following 2 types of errors occur that cause the DB initialization process to crash while only partially complete:

```
03:40:30     syntect_server | Configured for production.
03:40:45  zoekt-indexserver | 2019/05/17 03:40:45 POST http://127.0.0.1:3090/.internal/repos/list giving up after 5 attempts
03:40:47          gitserver | 2019/05/17 03:40:47 received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
03:40:47       repo-updater | 2019/05/17 03:40:47 received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
... many more of the above 2 log lines ...
03:41:00           frontend | panic: deadlock detected: you have called conf.Get or conf.Watch before the frontend has been initialized (you may need to use a goroutine)
03:41:00           frontend | goroutine 34 [running]:
03:41:00           frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*Store).WaitUntilInitialized(0xc0000d37c0)
03:41:00           frontend | 	/buildkite/builds/buildkite-agent-7d4775c8-mr448-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/pkg/conf/store.go:134 +0x13b
03:41:00           frontend | github.com/sourcegraph/sourcegraph/pkg/conf.(*client).Watch(0xc0000e1180, 0x1fbf1c8)
03:41:00           frontend | 	/buildkite/builds/buildkite-agent-7d4775c8-mr448-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/pkg/conf/client.go:111 +0xb8
03:41:00           frontend | github.com/sourcegraph/sourcegraph/pkg/conf.Watch(...)
03:41:00           frontend | 	/buildkite/builds/buildkite-agent-7d4775c8-mr448-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/pkg/conf/client.go:94
03:41:00           frontend | github.com/sourcegraph/sourcegraph/pkg/trace.init.0.func1()
03:41:00           frontend | 	/buildkite/builds/buildkite-agent-7d4775c8-mr448-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/pkg/trace/httptrace.go:59 +0x3a
03:41:00           frontend | created by github.com/sourcegraph/sourcegraph/pkg/trace.init.0
03:41:00           frontend | 	/buildkite/builds/buildkite-agent-7d4775c8-mr448-1/sourcegraph/.golang/sourcegraph/src/github.com/sourcegraph/sourcegraph/pkg/trace/httptrace.go:58 +0x117
```

```
xq:~ $ docker run --publish 7080:7080 --publish 2634:2633 --rm -e PGUSER=postgres -e PGPASSWORD=... -e PGHOST=... -e PGDATABASE=sg --volume /tmp/sg2/config:/etc/sourcegraph --volume /tmp/sg2/data:/var/opt/sourcegraph sourcegraph/server:3.3.7
03:41:31     syntect_server | Configured for production.
03:41:46  zoekt-indexserver | 2019/05/17 03:41:46 POST http://127.0.0.1:3090/.internal/repos/list giving up after 5 attempts
03:41:46          gitserver | 2019/05/17 03:41:46 received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
03:41:48            symbols | received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
03:41:48           searcher | received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
03:41:48       repo-updater | 2019/05/17 03:41:48 received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
03:41:48       github-proxy | 2019/05/17 03:41:48 received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
03:41:48       query-runner | 2019/05/17 03:41:48 received error during background config update, err: unable to fetch new configuration: Post http://127.0.0.1:3090/.internal/configuration: dial tcp 127.0.0.1:3090: connect: connection refused
03:41:48           frontend | Failed to migrate the DB. Please contact support@sourcegraph.com for further assistance: timeout: can't acquire database lock
03:41:48           frontend | Terminating frontend
```

### Repro

Repro against a clean PostgreSQL database that your Sourcegraph instance has 150-200ms of latency to. You can set up a PostgreSQL AWS RDS instance, or (much simpler) you can just add Go `time.Sleep(whatever)` code to inject latency into each DB call in the app. It is not necessary to use the official Docker image build to repro this.

### Workaround

Right now, you can use the following workaround to get everything working (after which you should not experience any other problems related to DB latency):
Run the query `UPDATE schema_migrations SET dirty=false;` in the PostgreSQL database you are using for Sourcegraph.

For example, the following shell command would work: PGUSER=postgres PGPASSWORD=your-password-here PGHOST=your-host-here PGDATABASE=your-db-name-here psql -c 'UPDATE schema_migrations SET dirty=false;'
Attempt to rerun the Docker container.
If it fails again, repeat steps 1 and 2. You may need to repeat this a few times. Each time, it will make progress on more of the initial DB setup.

### Affected customers

Affected https://app.hubspot.com/contacts/2762526/company/554338610 and will affect anyone else who fits the latency profile above.

**Comment by slimsag** [comment] 2019-05-17 07:44
I fixed this (the first error, which i believe leads to the second) just
yesterday actually. Ill link the issue when back at my computer

**Comment by slimsag** [comment] 2019-05-17 20:00
https://github.com/sourcegraph/sourcegraph/pull/3986 is the PR that fixed this. This was a duplicate of #2812 effectively.

Previously all migration work had to complete in under 30s, now we use a more lenient 5m timeout before this would occur. I think that's a reasonable enough amount of time for the migrations to go through. Let me know if you disagree.

Closing.

**Closed by slimsag** 2019-05-17 20:00 UTC
Labels: distribution
