### ISSUE TITLE
Add quick disable toggle to options popup

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5104] opened 2019-08-06 14:20 UTC
If our extension is causing performance issues or has a bug, it is better that users have an easy way to temporarily disable all features than for them to uninstall the extension.

This could be a quick toggle in the options page, below the URL. Example mock:

![image](https://user-images.githubusercontent.com/10532611/62546856-8f2f6880-b864-11e9-986c-347f6d671884.png)

The options page is defined here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/browser/src/libs/options/OptionsMenu.tsx#L47:14

The toggle needs to set a boolean flag in the local settings (not synced).

The content script needs 
- if the flag is false, do not init features and set a listener for changes that initializes
- if the flag is true, initialize features and set a listener that `.unsubscribe()`s the features to remove them and set listener described above.

All initialization of code intel features goes through this function: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/browser/src/libs/code_intelligence/inject.ts?utm_source=VSCode-1.0.14#L12:23

However, injecting the style sheet is currently duplicated for native integrations and the browser extension: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22document.createElement%28%27link%27%29%22+f:browser/

This would be best to refactor into a shared function too.

There also seems to be this old `disableExtension` storage flag that is not set anywhere and inconsistently checked for: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/browser/src/extension/scripts/inject.tsx#L69:17

This should be removed.

To get started with browser extension development, check out https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/browser/README.md

**Comment by christinaforney** [comment] 2019-08-06 14:50
This might be out of scope, but it would be great to "dim" or grey out the extension icon when disabled - many extensions do this, for example hubspot:
![image](https://user-images.githubusercontent.com/1559622/62550202-b105fc80-b81e-11e9-939f-8c66266fa776.png)
![image](https://user-images.githubusercontent.com/1559622/62550219-bb27fb00-b81e-11e9-9404-46c19edaed41.png)

**Comment by unknwon** [comment] 2019-08-06 19:31
https://github.com/sourcegraph/sourcegraph/pull/5110 is a baby step on solving this issue as proposed. But if the issue is urgent, changes made are minimal.

**Comment by unknwon** [comment] 2019-08-12 20:46
One use case for toggling I have is that:

1. I know the extension can be toggled
2. I know there are a lot files could cause problems loading the page
3. Turn off the extension before reviewing, or turn off ASAP and hit cmd+r to reload the PR page to prevent it from freezing 

cc @christinaforney

**Comment by unknwon** [comment] 2019-09-13 15:12
Closed as implemented and merged in https://github.com/sourcegraph/sourcegraph/pull/5110.

**Closed by unknwon** 2019-09-13 15:12 UTC
Labels: browser-extension
