### ISSUE TITLE
Search 504s

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#12347] opened 2020-07-20 22:33 UTC
This search causes sourcegraph.sgdev.org to 504: https://sourcegraph.sgdev.org/search?q=r:sourcegraph/ghdump+node_id+count:1000&patternType=literal

I suspect that this is the combination of a really high result count plus each result being on a line that is really long (I stumbled across this repo when trying to reproduce https://github.com/sourcegraph/sourcegraph/issues/12346).

**Comment by nicksnyder** [comment] 2020-07-20 22:43
Perhaps related:

If I do this search: https://sourcegraph.com/search?q=r%3A%5Egithub.com%2Fsourcegraph%2F+blacklist%7Cwhitelist+count%3A1000&patternType=regexp

I get this error:

> text search failed: failed to search github.com/sourcegraph/ghdump@: searcher request failed: Get "http://10.164.7.219:3181?CombyRule=&Commit=9a03687232c53b8aa7ef0c520d57f1ae28028ec1&Deadline=2020-07-20T22%3A39%3A44.864669685Z&ExcludePattern=&FetchTimeout=54.380202344s&FileMatchLimit=1000&IsRegExp=true&PathPatternsAreRegExps=true&Pattern=blacklist%7Cwhitelist&PatternMatchesContent=true&PatternMatchesPath=true&Repo=github.com%2Fsourcegraph%2Fghdump&URL=": EOF

**Comment by rvantonder** [comment] 2020-07-22 19:13
Related to #12378

**Comment by rvantonder** [comment] 2020-07-23 01:53
In this case, adding `index:only` alleviates the `count:1000`, bringing the search to around 6s for [query](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/+blacklist%7Cwhitelist+count:1000+index:only&patternType=regexp) and seems similar to https://github.com/sourcegraph/customer/issues/61 (searcher code path issue).

Side note: the 6s delay on that is still long, but it is almost entirely attributable to resolving repos (which takes ~6 seconds on its own for:

- [`r:^github.com/sourcegraph/`](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/&patternType=literal) 

but if you modify it to 

- [`r:^g.thub.com/sourcegraph/`](https://sourcegraph.com/search?q=r:%5Eg.thub.com/sourcegraph/&patternType=literal) it takes only 0.5 seconds

Yes, _the more general_ regex makes it faster. How come? I've long had my suspicions that this is due to a separate PSQL [trigram lookup issue](https://gist.github.com/rvantonder/7745c2360cfced6f12c922588bfbef79) that has been dismissed/ignored before, but the evidence is still there. I will defer dealing with that later, it is not the cause of the 504s, just agonizing slowness.

**Comment by keegancsmith** [comment] 2020-07-23 03:43
Best to investigate some jaeger traces here.

A few avenues to explore that I noticed on sg.com recently (ordered in rough order of importance to investigate)
1. Slow SELECT on repos table (as you mentioned)
2. Missing repos slowing search down.
3. Slow user setting queries (now used in search path)
4. Slower searcher disks since migrating to new cluster.
5. Slower gitserver due to increased load

**Comment by rvantonder** [comment] 2020-07-23 03:44
Really strange behavior here. No clues trying to reproduce anything locally (so restricted to looking at behavior of Sourcegraph.com short looking at infra behavior which I'm not sure where to go looking). I've reduced down the pathological behavior to:

- `r:^github.com/sourcegraph/ blacklist|whitelist count:10` this is OK
- `r:^github.com/sourcegraph/ blacklist|whitelist count:100` something goes wrong, this query never finishes. 504 or 502 or any of these kinds of things. Strange, since it's only a slightly higher count. 
- Adding `index:no` does the same, no success
- Adding `index:only` is OK, the search completes. 

So at face value it looks like something related to the unindexed code path, possibly related to caching/zip archives, or https://github.com/sourcegraph/sourcegraph/issues/9001, unsure.

**Comment by keegancsmith** [comment] 2020-07-23 04:10
Anecdotally I am seeing a lot of issues with our pods, which I haven't spotted in the last few days. It isn't all the time, but a few bursts of activity like this while I was asleep.

![image](https://user-images.githubusercontent.com/187831/88251425-13b00c80-ccab-11ea-82e7-aa7c69ad7065.png)

**Comment by rvantonder** [comment] 2020-07-30 21:27
Issue is a bit better after indexing repo names, so I can minimize the slowness to the following queries now:

- Instant with `index:only`: [`r:^github.com/sourcegraph/ blacklist|whitelist count:1000 index:only`](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/+blacklist%7Cwhitelist+count:1000+index:only&patternType=regexp)

- The really slow/timeout case without `index:only`: [`r:^github.com/sourcegraph/ blacklist|whitelist count:1000](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/+blacklist%7Cwhitelist+count:1000&patternType=regexp)

- The really surprising thing where omitting repo above is instant: [blacklist|whitelist count:1000](https://sourcegraph.com/search?q=blacklist%7Cwhitelist+count:1000+&patternType=regexp)

I still suspect that there is some weirdness with how we resolve repos and/or commits in the middle query, but this time we can rule out DB lookup as the culprit.

**Comment by keegancsmith** [comment] 2020-07-31 11:49
no `repo:` on sourcegraph.com goes through a different code path (the default_repos table).

**Comment by rvantonder** [comment] 2020-07-31 20:28
> no repo: on sourcegraph.com goes through a different code path (the default_repos table), which is why it is so fast.

Right, what I'm trying to point out here (to myself) is that the repo filter [`repo:^github.com/sourcegraph`](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/+count:10000&patternType=literal) only shows 160 repos in the results. Even with `index:no` (or `index:yes`), I don't expect this slowness/timeout. It's strange that resolving "just" 160 repos, some of which are indexed, completely borks, compared to the default repos table (which is like 10K+).

Haven't had a chance to look into this more, will look at some traces in the next couple hours.

**Comment by keegancsmith** [comment] 2020-08-03 09:49
> Haven't had a chance to look into this more, will look at some traces in the next couple hours.

What did ya find?

**Comment by rvantonder** [comment] 2020-08-04 04:47
Ah I didn't get a chance to do this, nor today. Will follow up when I have another chance.

**Comment by rvantonder** [comment] 2020-08-04 21:11
Ran [with trace](https://sourcegraph.com/search?q=r:%5Egithub.com/sourcegraph/+blacklist%7Cwhitelist+count:1000&patternType=regexp&trace=1) and the trace is at https://sourcegraph.com/-/debug/jaeger/trace/5e966ae81d540792. A ton of `Git: ResolveRevision` calls are being made. Digging some more...

**Comment by keegancsmith** [comment] 2020-08-05 07:07
We don't seem to be getting searcher traces. But I would suspect the issue isn't the speed of "grep", but that we are struggling to fetch an archive of ghdump. Our searcher code doesn't do per line searching, but uses the same technique in rg of searching the whole body and hydrating in line breaks.

**Comment by rvantonder** [comment] 2020-08-05 09:02
>  But I would suspect the issue isn't the speed of "grep", but that we are struggling to fetch an archive of ghdump.  Our searcher code doesn't do per line searching, but uses the same technique in rg of searching the whole body and hydrating in line breaks.

Whoops, guess my diagnosis is off then. I'll remember that part of our searcher now :-) The downloaded zip (at master) is only about 200MB , which is about the size of the Linux and we don't have any issues with that IIRC (git clone of ghdump is 2.6GB). So seems like there's still something else going on.

**Comment by keegancsmith** [comment] 2020-08-05 13:13
Rijnard van Tonder <notifications@github.com> writes:

>>  But I would suspect the issue isn't the speed of "grep", but that we are struggling to fetch an archive of ghdump.  Our searcher code doesn't do per line searching, but uses the same technique in rg of searching the whole body and hydrating in line breaks.
>
> Whoops, guess my diagnosis is off then. I'll remember that part of our searcher now :-) The downloaded zip (at master) is only about 200MB , which is about the size of the Linux and we don't have any issues with that IIRC (git clone of ghdump is 2.6GB). So seems like there's still something else going on.

Ok then it likely is us being slow at searching lol. We have integration
benchmarks which can easily plug in any repo@hash. So if you feel like
playing with our oldest search code have fun :D

**Comment by rvantonder** [comment] 2020-08-06 05:34
OK so after cloning locally and running a search, it seems these files are actually wrecking havoc on syntect server (not searcher)

<details>
  <summary>Expand for example logs</summary>
  
<pre>
frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-go__star-001442__ppg-100__pg-02.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":1130,\"incomplete_results\":false,\"items\":[{\"id\":11162159,\"node_id\""…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-go__star-000279__ppg-100__pg-02.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":4119,\"incomplete_results\":false,\"items\":[{\"id\":13910780,\"node_id\""…
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 120: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 106: restarting due to timeout
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-c++__star-000141__ppg-100__pg-05.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":7232,\"incomplete_results\":false,\"items\":[{\"id\":98503256,\"node_id\""…
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-php__star-000069__ppg-100__pg-08.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":10663,\"incomplete_results\":false,\"items\":[{\"id\":1346804,\"node_id\""…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-php__star-000021__ppg-100__pg-05.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":28383,\"incomplete_results\":false,\"items\":[{\"id\":264199730,\"node_i"…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-javascript__star-000038__ppg-100__pg-08.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":75790,\"incomplete_results\":false,\"items\":[{\"id\":162595548,\"node_i"…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-go__star-000037__ppg-100__pg-05.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":16439,\"incomplete_results\":false,\"items\":[{\"id\":5313975,\"node_id\""…
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 120: EOF
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-python__star-000101__ppg-100__pg-10.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":26085,\"incomplete_results\":false,\"items\":[{\"id\":30264349,\"node_id"…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-javascript__star-000211__ppg-100__pg-07.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":20122,\"incomplete_results\":false,\"items\":[{\"id\":54505054,\"node_id"…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-java__star-000024__ppg-100__pg-04.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":47544,\"incomplete_results\":false,\"items\":[{\"id\":17690143,\"node_id"…
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 120: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 120: 
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 120: signal: killed
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 120: EOF
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-go__star-000021__ppg-100__pg-05.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":23608,\"incomplete_results\":false,\"items\":[{\"id\":204168441,\"node_i"…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-java__star-001269__ppg-100__pg-08.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":2004,\"incomplete_results\":false,\"items\":[{\"id\":95203155,\"node_id\""…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-javascript__star-000597__ppg-100__pg-06.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":8359,\"incomplete_results\":false,\"items\":[{\"id\":40485527,\"node_id\""…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-java__star-001269__ppg-100__pg-07.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":1652,\"incomplete_results\":true,\"items\":[{\"id\":283325,\"node_id\":\"M"…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-java__star-000042__ppg-100__pg-09.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":31952,\"incomplete_results\":false,\"items\":[{\"id\":121508984,\"node_i"…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-javascript__star-000047__ppg-100__pg-06.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":64664,\"incomplete_results\":false,\"items\":[{\"id\":137706555,\"node_i"…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-javascript__star-000033__ppg-100__pg-03.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":84013,\"incomplete_results\":false,\"items\":[{\"id\":218937429,\"node_i"…
22:24:48                          frontend | WARN syntax highlighting took longer than 3s, this *could* indicate a bug in Sourcegraph, filepath: api_response_dump/lang-javascript__star-002315__ppg-100__pg-04.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":2374,\"incomplete_results\":false,\"items\":[{\"id\":92652320,\"node_id\""…
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-python__star-000061__ppg-100__pg-10.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":39202,\"incomplete_results\":false,\"items\":[{\"id\":26034643,\"node_id"…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-python__star-000110__ppg-100__pg-03.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":24225,\"incomplete_results\":false,\"items\":[{\"id\":102413247,\"node_i"…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-php__star-000120__ppg-100__pg-09.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":6719,\"incomplete_results\":false,\"items\":[{\"id\":20015974,\"node_id\""…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-python__star-000055__ppg-100__pg-01.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":34631,\"incomplete_results\":true,\"items\":[{\"id\":139160363,\"node_id"…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135: started on port 46503
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135: Configured for production.
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => address: 0.0.0.0
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => port: 46503
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => log: critical
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => workers: 12
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => secret key: provided
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => limits: forms = 32KiB, json* = 10MiB
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => keep-alive: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135:     => tls: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 135: Rocket has launched from http://0.0.0.0:46503
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: restarting due to timeout
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 106: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 106: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 106: 
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 106: signal: killed
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 106: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 106: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150: started on port 33341
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150: Configured for production.
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => address: 0.0.0.0
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => port: 33341
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => log: critical
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => workers: 12
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-python__star-000054__ppg-100__pg-08.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":43088,\"incomplete_results\":false,\"items\":[{\"id\":151285266,\"node_i"…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-ruby__star-000021__ppg-100__pg-07.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":21461,\"incomplete_results\":false,\"items\":[{\"id\":26945890,\"node_id"…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                          frontend | ERROR syntax highlighting failed (this is a bug, please report it), filepath: api_response_dump/lang-python__star-000105__ppg-100__pg-01.json, repo_name: github.com/sourcegraph/ghdump, revision: 0b04aa0167b403f5fc7ed43ecf15a34e76eb1978, snippet: "{\"total_count\":25166,\"incomplete_results\":false,\"items\":[{\"id\":4200468,\"node_id\""…, error: http://localhost:9238: HSS worker timeout while serving request
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => secret key: provided
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => limits: forms = 32KiB, json* = 10MiB
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => keep-alive: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150:     => tls: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 150: Rocket has launched from http://0.0.0.0:33341
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: 
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 77: signal: killed
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: 
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: signal: killed
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 92: EOF
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164: Configured for production.
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => address: 0.0.0.0
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => port: 43955
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => log: critical
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => workers: 12
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => secret key: provided
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => limits: forms = 32KiB, json* = 10MiB
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => keep-alive: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164:     => tls: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164: started on port 43955
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 164: Rocket has launched from http://0.0.0.0:43955
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178: started on port 40397
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178: Configured for production.
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => address: 0.0.0.0
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => port: 40397
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => log: critical
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => workers: 12
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => secret key: provided
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => limits: forms = 32KiB, json* = 10MiB
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => keep-alive: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178:     => tls: disabled
22:24:48                    syntect_server | 2020/08/06 05:24:48 worker 178: Rocket has launched from http://0.0.0.0:40397
  </pre>
</details>

Paging @slimsag :-) One of the example files in the log that breaks is https://github.com/sourcegraph/ghdump/blob/master/api_response_dump/lang-python__star-000105__ppg-100__pg-01.json.

**Comment by slimsag** [comment] 2020-08-07 03:48
sourcegraph/server does not have resource isolation, which means a single service can harm it in negative ways if they use up a lot of resources. This is a known issue.

Syntect is a complex stack machine with lots of arbitrary regexp thrown into the mix, some files are going to take a *really* long time to highlight or get the stack machine stuck, unfortunately. This is also a known issue and is why we use a subprocess model in syntect-server to enable us to kill/escape those cases.

That subprocess model does not exist in sourcegraph/server: https://github.com/sourcegraph/sourcegraph/issues/5841

I wouldn't say this is a wont-fix, but it's a low priority thing to fix I think.

**Comment by keegancsmith** [comment] 2020-08-07 06:43
> Syntect is a complex stack machine with lots of arbitrary regexp
> thrown into the mix, some files are going to take a *really* long time
> to highlight or get the stack machine stuck, unfortunately. This is
> also a known issue and is why we use a subprocess model in
> syntect-server to enable us to kill/escape those cases.

Don't we already have heuristics in the frontend client for syntect that
prevents asking it to highlight some files? It seems completely
reasonable to me to skip highlighting a file with a long line or that is
large?

**Comment by slimsag** [comment] 2020-08-24 21:19
It's not about "it taking too long" it's about "it going down a code path that will never return" i.e. a complete deadlock in the syntect state machine that leads to it never completing and consuming all available resources. Yes, technically that *shouldn't* be possible and we *should* be able to debug where that is happening in syntect, we just need to invest time in doing that. We definitely need to do that, but it's tracked elsewhere and not a high priority in other deployments because we spin off syntect_server worker subprocesses and kill them if they take too long via https://github.com/slimsag/http-server-stabilizer which is not present in sourcegraph/server https://github.com/sourcegraph/sourcegraph/issues/5841

**Closed** 2022-04-27 10:28 UTC
Labels: bug, team/search-core
