### ISSUE TITLE
CI pipeline ordering does not make sense

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#810] opened 2018-11-06 15:19 UTC
![image](https://user-images.githubusercontent.com/10532611/48073624-70217e80-e1df-11e8-8f77-b476e6bffe87.png)

It doesn't make sense to me why the enterprise steps need to wait for the OSS steps to complete first. Since they mostly build the same things, this means our build time is roughly twice as long as it would need to be.
Some things also seem duplicated, for example I don't see a reason why we need two prettier steps or two codecov steps.

**Comment by beyang** [comment] 2018-11-07 00:44
Dupe of https://github.com/sourcegraph/sourcegraph/issues/559

**Closed by beyang** 2018-11-07 00:44 UTC
Labels: ops & tools & dev
