### ISSUE TITLE
Diff/commit search UX over thousands of repositories is extremely poor

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5519] opened 2019-09-09 22:41 UTC
### Use case from a customer (generalized for anonymity)

> There has been a critical change somewhere in one of our repositories from URL A to URL B and I need to know where that change was made. I don't know which repository changed it, just the previous value URL A and I need to find a diff with that.

### Issue

Diff and commit search is unindexed because we built it with the assumption that most use cases would involve searching in a small set of repositories. A side effect of this is that the UX is extremely poor when actually trying to do diff/commit search over thousands of repositories, even in the up-and-coming UX redesign.

For example, the following query: https://k8s.sgdev.org/search?q=type:diff+jre8

![image](https://user-images.githubusercontent.com/3173176/64570762-6fcda480-d316-11e9-961c-7cfd141ae1ba.png)

Most of the repositories here have timed out, because we just simply cannot handle searching that many all at once. There isn't a way to go through the results by e.g. scrolling either, because again most repositories timed out.

Assuming you do see the timeout warning (it doesn't stick out much), specifying a larger timeout parameter won't always help. For example specifying the max `timeout:2m` ends up showing the following error since we're now hitting a single empty repository and not finding results in the others quick enough (we are searching others, though):

https://k8s.sgdev.org/search?q=type:diff+jre8+timeout:2m

![image](https://user-images.githubusercontent.com/3173176/64571149-c8ea0800-d317-11e9-871a-2846a2fc70d2.png)

### Solution: Option 1

The most obvious solution is to warn people that we don't expect them to search thousands of repositories with diff search at once:

1. Provide the user with an error indicating to reduce the number of repositories being searched over by using a `repo:` regex.
2. Indicate that doing a text search first to find the repositories you are interested in may help.

### Solution: Option 2

Make the UX around search more clear that diff/commit search is targeted towards a subset of repositories and not a global search. This is a design question.

Reported by a user at https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by slimsag** [comment] 2019-10-04 09:20
@christinaforney I just want to flag this as having got a lot worse with the new tab UX. Previously, it was harder to discover `type:diff` which also meant it was uncommon for users to perform global searches with it. Now with it front and center, it is easy to click on it and immediately notice everything is timing out and it looks quite bad.

**Comment by dadlerj** [comment] 2019-10-18 05:21
Also reported by a user at https://app.hubspot.com/contacts/2762526/company/557475593

**Comment by slimsag** [comment] 2019-11-18 21:53
Just heard more feedback from https://app.hubspot.com/contacts/2762526/company/407948923 about this being a very poor experience overall. Effectively, the product appears completely broken when using diff/commit search which is very bad. You just get an error like this:

![image](https://user-images.githubusercontent.com/3173176/69097026-ebcd2280-0a12-11ea-9e1d-a84e80e7d3a8.png)

@christinaforney Proposal: If your diff/commit search would go over more than 50 repositories, return an error that informs the user it does not currently support >50 repositories and they should use `repo:` regex filters to narrow down the search area & link them to this GitHub issue to provide feedback.

**Comment by nicksnyder** [comment] 2019-11-20 00:20
Is there an equally easy change we could do that would improve the error message to say that a timeout happened?

**Comment by rvantonder** [comment] 2019-11-20 17:44
I will implement the suggested proposal [as per slack](https://sourcegraph.slack.com/archives/C0W2E592M/p1574216767205500?thread_ts=1574114006.199500&cid=C0W2E592M):

> Proposal: If your diff/commit search would go over more than 50 repositories, return an error that informs the user it does not currently support >50 repositories and they should use repo: regex filters to narrow down the search area & link them to this GitHub issue to provide feedback.

How we scale diff/commit search is still an open problem.

**Comment by slimsag** [comment] 2019-11-26 18:14
@rvantonder unfortunately this appears to still be an issue in master and 3.10.1:

---

https://k8s.sgdev.org/search?q=error+type:diff&patternType=literal

![image](https://user-images.githubusercontent.com/3173176/69660447-95c53400-103d-11ea-8ac3-b74dcc802db0.png)

---

https://k8s.sgdev.org/search?q=error+type:commit&patternType=literal

![image](https://user-images.githubusercontent.com/3173176/69660496-b1303f00-103d-11ea-965b-27010da21af3.png)

---

http://theoa.sgdev.org/search?q=hello+type:commit&patternType=literal

![image](https://user-images.githubusercontent.com/3173176/69660522-c2794b80-103d-11ea-8ada-1f18c86d2090.png)

---

http://theoa.sgdev.org/search?q=hello+type:diff&patternType=literal

![image](https://user-images.githubusercontent.com/3173176/69660563-d58c1b80-103d-11ea-9db3-eb9fd3eb702d.png)

**Comment by rvantonder** [comment] 2019-11-26 18:49
Can't reproduce locally or on sourcegraph.com. Is the patch really live on k8s?

Locally, with about 117 repos:

<img width="572" alt="Screen Shot 2019-11-26 at 11 46 42 AM" src="https://user-images.githubusercontent.com/888624/69662966-90b6b380-1042-11ea-8518-27332d7874d5.png">

<img width="627" alt="Screen Shot 2019-11-26 at 11 46 55 AM" src="https://user-images.githubusercontent.com/888624/69662986-9613fe00-1042-11ea-844f-8dc1e504c70a.png">

Sourcegraph.com, with <many> repos:

<img width="664" alt="Screen Shot 2019-11-26 at 11 47 11 AM" src="https://user-images.githubusercontent.com/888624/69663010-9f04cf80-1042-11ea-883d-56af96ebd818.png">

<img width="647" alt="Screen Shot 2019-11-26 at 11 47 20 AM" src="https://user-images.githubusercontent.com/888624/69663019-a3c98380-1042-11ea-9f53-d739d070a163.png">

**Comment by rvantonder** [comment] 2019-11-26 22:17
@slimsag I now ran `IMAGE=sourcegraph/server:3.10.1 ./dev/run-server-image.sh` and can reproduce that the warning does _not_ come up. Since this is not the case on sourcegraph.com and local dev on master, it makes me wonder if the change got into the patch release.

**Comment by slimsag** [comment] 2019-11-26 22:29
k8s.sgdev.org is also on 3.10.1 not `master` currently, for reference

**Comment by slimsag** [comment] 2019-11-26 22:30
Indeed, the commit is not in the `3.10` branch so this didn't make the cut. I thought from your comment at https://github.com/sourcegraph/sourcegraph/issues/6823#issuecomment-558072308 and the fact it was checked off in the list that the commit was cherry-pick'd into the `3.10` branch already, but I guess not

**Comment by slimsag** [comment] 2019-11-26 22:31
Will have to cut another patch release -- I'll see about doing that next week perhaps

**Comment by slimsag** [comment] 2019-11-26 22:31
Thanks for investigating!

**Comment by rvantonder** [comment] 2019-11-26 22:36
I think this is what happened (from my side):

I merged the change into master. Then I _did_ hit the checkbox. Then I looked at the instructions, which said that the checkbox should be checked once it's cherrypicked. So then I _unchecked_ the checkbox (maybe a less than a minute window). I _assumed_ it would still get cherrypicked (by you or Beyang, but didn't mention this), since the box was unchecked and I assumed the correct format in the tracker would read `[x] - <commit>` and not `[x] PR#`. So the comment really did mean 'merged' (into master) but not 'cherry-picked'.

**Comment by slimsag** [comment] 2019-11-26 22:50
![](https://media.giphy.com/media/Dvw2lJqlTuJmo/giphy.gif)

we should probably make the template more clear what checked off means 🤣

**Comment by slimsag** [comment] 2019-12-02 21:53
Update: This will be in 3.11 or the next patch release we cut (if you need this, please speak up)

**Comment by keegancsmith** [comment] 2019-12-13 14:15
> Update: This will be in 3.11 or the next patch release we cut (if you need this, please speak up)

Can we close this now?

**Closed** 2020-01-09 21:21 UTC
Labels: bug, design, search, team/distribution 🚢📦💨
