### ISSUE TITLE
Suddenly getting no/wrong results

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18581] opened 2021-02-23 20:21 UTC
<img width="934" alt="image" src="https://user-images.githubusercontent.com/3173176/108902738-b7fb8800-75d9-11eb-9bea-2a5797f3f346.png">

I ran a search for `repo:^github\.com/sourcegraph/sourcegraph$ file:insights` and didn't get any results and was confused for a long time. The error message provided no help to me:

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:insights&patternType=literal&context=%40slimsag

I am very worried this is going to confuse a lot of users:

1. The error message needs to be improved.
2. I feel quite strongly that the default should NOT be just repositories I own (at least for enterprise instances, Sourcegraph.com may be an exception.) - this will lead to users sometimes getting results "but not all of them" without noticing why.

**Comment by rvantonder** [comment] 2021-02-23 20:23
Duplicate of #18580. Useful context, I will leave it to you to close and/or copy paste to #18581?

**Comment by stefanhengl** [comment] 2024-02-09 12:05
This issue has been inactive for a long time. To reopen the ticket,  please let us how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.

**Closed by stefanhengl** 2024-02-09 12:05 UTC
Labels: team/search-platform
