### ISSUE TITLE
repo-updater: race condition on inserting repo without ID

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#7750] opened 2020-01-15 08:27 UTC
There is a potential race condition when inserting a repo. This is new and is most likely related to the work done to support soft deleting a repository. #6859

```
18:37:41        repo-updater | panic: repo.id is zero
18:37:41        repo-updater | goroutine 184 [running]:
18:37:41        repo-updater | github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos.(*schedule).upsert(0xc00036e100, 0xc001bfdda0, 0x0)
18:37:41        repo-updater |  /Users/thorstenball/work/sourcegraph/cmd/repo-updater/repos/scheduler.go:622 +0x364
18:37:41        repo-updater | github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos.(*updateScheduler).upsert(0xc000279600, 0xc0017980e0)
18:37:41        repo-updater |  /Users/thorstenball/work/sourcegraph/cmd/repo-updater/repos/scheduler.go:259 +0x70
18:37:41        repo-updater | github.com/sourcegraph/sourcegraph/cmd/repo-updater/repos.(*updateScheduler).Update(0xc000279600, 0xc001c13988, 0x1, 0x1)
18:37:41        repo-updater |  /Users/thorstenball/work/sourcegraph/cmd/repo-updater/repos/scheduler.go:249 +0x17d
18:37:41        repo-updater | github.com/sourcegraph/sourcegraph/cmd/repo-updater/shared.watchSyncer(0x2ff1be0, 0xc000052110, 0xc00038c180, 0x2fcbf60, 0xc000279600, 0xc000279940)
18:37:41        repo-updater |  /Users/thorstenball/work/sourcegraph/cmd/repo-updater/shared/main.go:251 +0x325
18:37:41        repo-updater | created by github.com/sourcegraph/sourcegraph/cmd/repo-updater/shared.Main
18:37:41        repo-updater |  /Users/thorstenball/work/sourcegraph/cmd/repo-updater/shared/main.go:186 +0x2051
```

**Comment by mrnugget** [comment] 2020-01-15 10:29
@keegancsmith and I synced on this this morning after I could reliably reproduce the issue by running e2e tests locally.

How we reproduced it:
1. Run `./enterprise/dev/start.sh` (important that it's enterprise!). That inserts the repos in `dev-private`.
2. Run e2e tests: `yarn --cwd web run test-e2e`. That inserts the e2e repos.
3. **Restart** `./enterprise/dev/start.sh`. That soft-deletes the e2e repos because the external services are synced with the ones in `dev-private`
4. Run e2e tests. The e2e repos will now be reinserted with the "streaming sync" `syncSubset` method:  https://github.com/sourcegraph/sourcegraph/blob/e7c2d32c2aa9888c1f7ff3101157fa31d7b403f2/cmd/repo-updater/repos/syncer.go#L188-L198
5. The e2e repos will be inserted/un-soft-deleted, **but** (!!!) the repos will be returned without an ID from the database, meaning that `ID == 0`.
6. The newly inserted repos are sent to the scheduler's `upsert` method, which crashes because `repo.id is zero`

I wrote a failing test case that includes the assertion that a re-inserted repo's ID should not be 0: https://github.com/sourcegraph/sourcegraph/pull/7752

**Closed** 2020-01-15 13:24 UTC
Labels: team/core-services
