### ISSUE TITLE
Explicit private repository mirroring does not work unless access token is provided (SSH cloning)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1858] opened 2019-01-13 23:58 UTC
It is my expectation as a user that the following configuration would allow me to clone an explicit list of my private GitHub repos, but it doesn't work (neither does it in other code host types):

![image](https://user-images.githubusercontent.com/3173176/51092369-9b7e9780-1753-11e9-8dd0-7b401d1e27fb.png)

After saving this, there is no error and the repository does not show up under `/site-admin/repositories`. Only if I add a PAT does the repository show up.

1. I expect not to have to do this, given I am using SSH cloning and configuring access via that.
2. If my expectations are wrong, Sourcegraph should warn me that my config is wrong.

@nicksnyder who should own this?

**Comment by nicksnyder** [comment] 2019-01-15 03:00
Need to triage this to see if it is a regression from 2.13.5 or not.

**Comment by tsenart** [comment] 2019-01-23 14:01
Starting to investigate this.

**Comment by tsenart** [comment] 2019-01-23 15:05
> After saving this, there is no error and the repository does not show up under /site-admin/repositories. Only if I add a PAT does the repository show up. I expect not to have to do this, given I am using SSH cloning and configuring access via that.

A personal access token is always required because we need to use the Github API to read the repository metadata, even if we clone the repo with SSH in git-server.

> If my expectations are wrong, Sourcegraph should warn me that my config is wrong.

This is the actual issue and will be done in https://github.com/sourcegraph/sourcegraph/issues/1721

Closing this issue as a duplicate of #1721.

**Closed by tsenart** 2019-01-23 15:05 UTC
Labels: bug
