### ISSUE TITLE
Clicking search result or find references result sporadically doesn't scroll down to specified line

### ISSUE THREAD

**Issue by Strum355** [sourcegraph/sourcegraph#18332] opened 2021-02-16 15:17 UTC
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Chromium version 88.0.4324.150 (Official Build) Arch Linux (64-bit)

#### Steps to reproduce:

1. Do an action such as search or find references
2. Click the line number or highlighted text in a result

This isnt always consistently happening, but it shouldnt take much clicking around to trigger it

#### Expected behavior:
Line is highlighted and document is scrolled to that line

#### Actual behavior:
Correct document loads, URL fragment contains the right line number, git-blame extension shows blame for the correct line, but the line isnt highlighted and I am shown the top of the document instead of being taken to the actual line

https://user-images.githubusercontent.com/18282288/108081930-68f9a400-7069-11eb-9330-cb95532e151e.mp4

cc @sourcegraph/frontend-platform

**Comment by pdubroy** [comment] 2021-06-25 12:04
Possibly related to #21578

**Comment by pdubroy** [comment] 2021-06-25 12:10
After clicking around for a few minutes, I'm unable to reproduce this. I'm going to close this for now, but please feel free to re-open if you can reliably reproduce it.

**Closed by pdubroy** 2021-06-25 12:10 UTC
Labels: bug, team/frontend-platform
