### ISSUE TITLE
docs: table striping style references an undefined variable for background colors

### ISSUE THREAD

**Issue by zephyrtronium** [sourcegraph/sourcegraph#19858] opened 2021-04-09 01:16 UTC
#### Describe the issue
The CSS rule for background-color for table striping uses `var(--table-row-bg-1)`, which does not seem to be defined anywhere. On most browsers, this appears to default to `inherit`, but on my browser, it is instead white.

![Screenshot of table with unreadable coloring](https://cdn.discordapp.com/attachments/287739410286379019/829867673495666738/unknown.png)

Browser version is Firefox 87.0 64-bit, although @Strum355 could not reproduce on the same version. The only extensions I have installed are uBlock Origin and the Sourcegraph extension. The inspector in Chrome verifies that the variable is not defined.

#### Where is the issue located?
This appears to affect all Markdown tables on docs.sourcegraph.com.

#### Suggested resolution
Defining `--table-row-bg-1` would ensure consistent behavior across all browsers.

**Comment by Joelkw** [comment] 2021-04-09 01:57
Hey @zephyrtronium ! Weirdly, it seems like we do define that variable [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/_resources/assets/docsite.css#L33:5) and my chrome inspector shows that it is defined. I'm also not able to reproduce this on 87.0, but we had a teammate who ran into something similar and the solution found was – "Firefox has a setting that allows you to override site CSS in high-contrast themes in some circumstances. Setting it to never do that and restarting fixed the issue." Does that work for you? 
![image (21)](https://user-images.githubusercontent.com/11967660/114117742-349da980-989c-11eb-9462-69fa87a08d8a.png)

**Comment by zephyrtronium** [comment] 2021-04-09 02:46
I don't see a setting like that when I search for `contrast` or `disp*color` in about:config. Do you have more info on how to check for that setting? I did realize that I spaced on having a theme installed, but disabling it didn't change anything.

A few more notes:
- While the page is loading, the table renders with the correct colors. The bg-1 rows only become white once the page finishes loading.
- I do indeed see that definition of --table-row-bg-1 in the inspector when I scroll to the very bottom level of style rules, but the definition appears before that of --body-bg. Even your inspector screenshot shows that it's undefined; it renders color squares next to other definitions of the same form. cf, from Chrome 89: ![image](https://user-images.githubusercontent.com/1428115/114120988-94577d00-98bb-11eb-93a1-1b1377e06fbf.png)

Sorry about my lack of specificity here, I only have cursory familiarity with CSS.

**Comment by Joelkw** [comment] 2021-04-10 01:38
@zephyrtronium, huh, I'll take a closer look at the css given all that. In the meantime, it sounds like the setting was "about:preferences > language and appearance > font and colors > colors (button) > override the colors on the page with the colors you select above > Never" – does that fix your issue?

**Comment by zephyrtronium** [comment] 2021-04-10 02:06
No change with that setting, including after relaunching Firefox and full refreshing the page.

**Comment by emchap** [comment] 2021-04-12 23:42
@zephyrtronium Are you running the Sourcegraph browser extension? Does uninstalling fully (removing it, not just disabling it) fix the issue?

**Comment by zephyrtronium** [comment] 2021-04-13 02:01
@emchap 
Even better, just disabling it and refreshing fixes the issue. Should I try uninstalling as well, or is that sufficient?

**Comment by emchap** [comment] 2021-04-13 15:20
@zephyrtronium If that's working for you, feel free to keep things as they are! This is a known issue with the browser extension and Firefox; our team is actively working on a fix but does not have an ETA. For now as a workaround, you can disable/reenable the extension as needed, use light mode on the docs (which doesn't have the issue), or use Chrome (which doesn't have the issue). Thanks for flagging this for us!

**Comment by muratsu** [comment] 2021-05-19 17:21
Fixed on browser extension v21.5.12.144. Please use the latest version from Firefox Addon store

**Closed by muratsu** 2021-05-19 17:21 UTC
Labels: browser-extension, bug, docs, team/extensibility
