### ISSUE TITLE
vscode-cody v1.3+ autocompletion doesn't work with AzureOpenAI

### ISSUE THREAD

**Issue by rakeshjosh2003** [sourcegraph/sourcegraph#59265] opened 2024-01-02 00:12 UTC
#### Feedback

Customer has shared a feedback regarding autocompletion not working with cody-vscode version 1.3 and above when using AzureOpenAI.

400 could not decode request body error is encounetered when using autocomplete, this is not specific to any particular programming language and they tried different codefiles.

The same works fine when the cody version is changed back to V1.2. In version 1.3 a change was introduced for autocompletion removing temperature and topP from codecompletionparams and adding [topk](https://github.com/sourcegraph/cody/blame/807ea71d868fb7a1e74471bb67396b52acb704d8/vscode/src/completions/providers/unstable-openai.ts#L131). Looks like this is creating the issue as when in the code topk is replaced with topP, it works fine.

Sourcegraph version: **5.2.1, 5.2.5**
Deployment type : **EKS**

**Error snippet from logs:**

getInlineCompletions:error: Request to https://sourcegraph-eks-trial.stg.devops.aslead.cloud/.api/completions/code failed with 400 Bad Request: could not decode request body
 Error: Request to https://abc.cloud/.api/completions/code failed with 400 Bad Request: could not decode request body
    at complete (c:\Users\abc\.vscode\extensions\sourcegraph.cody-ai-1.0.4\dist\extension.node.js:176535:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async c:\Users\abc\.vscode\extensions\sourcegraph.cody-ai-1.0.4\dist\extension.node.js:174937:22 {
  "error": {
    "status": 400
  }

#### Customer

[Customer](https://sourcegraph2020.lightning.force.com/lightning/r/Account/0013t00001Xib6sAAB/view)
[slack thread](https://sourcegraph.slack.com/archives/C04N8TD31R7/p1703223833536249)

**Comment by chwarwick** [comment] 2024-01-02 12:30
Duplicate of https://github.com/sourcegraph/cody/issues/2524

**Closed** 2024-01-02 12:32 UTC
Labels: feedback, cody/vscode
