### ISSUE TITLE
Upgrade to beta.4 from previous version produces double definitions

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2123] opened 2019-02-01 19:33 UTC
### Run 3.0 beta

- Clear previous state (`~/.sourcegraph`)
- Run container using `sourcegraph/server:3.0.0-beta`
- Create external GitHub service
- Add `github.com/sourcegraph-demo/buildkit` repository
- Enable basic code intel
- Go to `/github.com/sourcegraph-demo/buildkit/-/blob/cache/blobs/blobs.go#L52:22`
- Observe definition with a single result.
- Terminate docker container
 
### Upgrade to beta 4

- Run container using `sourcegraph/server:3.0.0-beta.4`
- Go to `/extensions`. Observe basic code intel is enabled, as well as lang specific extensions

<img width="1207" alt="screen shot 2019-02-01 at 11 23 52 am" src="https://user-images.githubusercontent.com/133014/52144760-0d8c2300-2614-11e9-9a53-79d1d7febccf.png">

- Go to `/github.com/sourcegraph-demo/buildkit/-/blob/cache/blobs/blobs.go#L52:22`
- Observe two definitions provided.

<img width="1071" alt="screen shot 2019-02-01 at 11 23 37 am" src="https://user-images.githubusercontent.com/133014/52144771-12e96d80-2614-11e9-9eda-9e76f1889f5b.png">

**Comment by chrismwendt** [comment] 2019-02-01 19:59
This can be solved in the same way as https://github.com/sourcegraph/sourcegraph/issues/2116 (hard-code migration to disable basic-code-intel), closing in favor of that one.

**Comment by chrismwendt** [comment] 2019-02-01 22:00
Reopening because there are other solutions to this problem of double tooltips/defs/refs that are not solutions to #2116:

- Release a new version of `sourcegraph/basic-code-intel` that deactivates itself when there's already a language extension enabled
- Delete `sourcegraph/basic-code-intel` (this will cause a console warning that says the extension was not found)

**Comment by chrismwendt** [comment] 2019-02-01 23:32
I plan to update the basic-code-intel extension to be a no-op when you have a language extension running.

**Comment by chrismwendt** [comment] 2019-02-02 00:19
I updated basic-code-intel in https://github.com/sourcegraph/sourcegraph-basic-code-intel/commit/59328060970efe4e4e25065c88618f8fd1660986?w=1 so that it turns itself into a no-op when the user already has a `sourcegraph/$LANG` extension enabled.

You should no longer see double hovers. @ryan-blunden Can you check and close if this is fixed?

**Comment by chrismwendt** [comment] 2019-02-02 05:45
@ryan-blunden confirmed that this is fixed.

**Closed by chrismwendt** 2019-02-02 05:45 UTC
Labels: bug, extensions
