### ISSUE TITLE
Search: highlights darken each time you hit enter

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#6996] opened 2019-12-02 20:51 UTC
- Visit https://sourcegraph.com/search?q=blade+test+f:client&patternType=regexp
- Notice the level of highlighting:

![image](https://user-images.githubusercontent.com/1387653/69993996-2b633680-150a-11ea-8740-f900cd4dc10b.png)

- Hit enter a few times
- Notice highlights are darker:

![image](https://user-images.githubusercontent.com/1387653/69993984-256d5580-150a-11ea-8395-2f8e8e25e0cd.png)

cc @sourcegraph/web

**Comment by rvantonder** [comment] 2019-12-02 21:37
Duplicate of #6441

**Closed** 2019-12-02 22:44 UTC
Labels: bug, search, web
