### ISSUE TITLE
Protect the preprod branch with a lock on deploy-sourcegraph-cloud

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#32875] opened 2022-03-22 09:12 UTC
As discussed during our last sync about RFC-592 with the @sourcegraph/cloud-devops team, we want to make sure it's not possible to push on the `preprod` branch of https://github.com/sourcegraph/deploy-sourcegraph-cloud without going through a PR. 

@daxmc99 and @danieldides at the time of writing this, I don't have access to the settings to list here what's currently in place. 

In the eventuality of a PR needing to be expedited, `pr-auditor` will always raise an exception if it sees a PR not being reviewed. 

TODO:

- [ ] Define the policy 
- [ ] Document the policy 
- [ ] Enact the policy 
- [ ] Post an announcement over Slack + include it newsletters.

**Comment by bobheadxi** [comment] 2022-03-22 22:07
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/32876 ?

**Closed** 2022-03-22 22:07 UTC
Labels: dx, team/devops, okr/RFC-592
