### ISSUE TITLE
History / bookmarking / pinning / note-taking feature

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#425] opened 2018-10-16 22:29 UTC
#### Feature request description

We've had a few attempts at adding a history/bookmark-like feature to Sourcegraph to assist with explorations that span multiple files where the user wants to be able to jump quickly between recent interest points in the code.

Latest request is from a user:

> I've used Sourcegraph for several months now and I've had a great experience exploring golang/go with it. It's a great tool to dive deep into unfamiliar codebases. A feature I would love to see is to have a dashboard of relevant semantic structures. 
> 
> As you jump around the codebase from references to invocations, it's easy to lose track of where you started. It would be awesome if there was a sidebar where you could pin these semantic structures that you are actually interested in. For example: we could pin gin-gonic/gin's engine struct and then pin net/http's ListenAndServe method so we can easily hop back and forth. It's kinda like placing markers so we don't get lost exploring the codebase. 
>
> Another occasion that this would be helpful is when you are curious about the implementation of a specific function. However, this function calls other functions and those functions call other functions and so on. It gets messy jumping from function definition to function definition. This is the case with many of Go's standard library packages as several of them can be traced back to the syscall package after many layers of function calls.

This feature tracks further discussion for what this feature should look like.

cc @attfarhan

**Comment by attfarhan** [comment] 2019-03-17 23:21
Dupe of https://github.com/sourcegraph/sourcegraph/issues/2065. Going to close this in favor of that one since more are subscribed there.

**Closed by attfarhan** 2019-03-17 23:21 UTC
Labels: feature-request
