### ISSUE TITLE
Match highlight at the end of a long result snippet freezes browser tab

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#6489] opened 2019-11-07 15:14 UTC
For example, in this link, the first two matches are on really long lines in HTML files, and are outside of the viewport: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22deprecated:%22+&patternType=regexp

This causes the browser tab to freeze

**Comment by unknwon** [comment] 2019-11-07 19:36
A bit more notes: Firefox has no problem, chromium-based ones are freezing (i.e. Microsoft Edge, Chrome).

**Comment by slimsag** [comment] 2020-02-04 00:48
I just got two user reports from https://app.hubspot.com/contacts/2762526/company/407948923/ and reproduced this before finding this issue; the behavior is MUCH worse when there are several results that have really long lines: it can make scrolling completely unbearable and even lock up the browser tab in Chrome entirely, requiring a browser restart to fix it.

I think the simplest solution here would be to place a limit on the length of lines so we don't generate and display a table with ultra long entries. This would be done in the Go code as a post-processing step before we return the HTML here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@e4b294f4778cc87a267cb509266c971228260565/-/blob/internal/highlight/highlight.go#L207

It could be an option passed into the GraphQL layer (in case we later want to add an "render extremely long lines" button in the web UI).

Anyone interested in taking this on?

**Comment by nicksnyder** [comment] 2020-02-04 03:19
Is there no quick/easy frontend solution for this @lguychard @felixfbecker @eseliger ?

**Comment by lguychard** [comment] 2020-02-04 14:59
We could bail on match highlighting after a large number of visited nodes.

That being said, the sheer number of nodes returned in the generated tables for the example query makes the page sluggish (although not frozen) even without match highlighting. Not generating those tables in the first place sounds like the right fix to me.

**Comment by nicksnyder** [comment] 2020-02-04 16:31
@tsenart This sounds like a small issue. Can someone on @sourcegraph/core-services do this for 3.13?

**Comment by keegancsmith** [comment] 2020-02-06 15:53
@slimsag is this easier to fix in the go or rust code for this? IE is there some config we can tweak in the rust code, or do we need to parse the returned results from the rust service in go to determine "too many nodes"? If both of those sound like too much work, I suppose just not syntax highlighting lines over a certain length should be fine?

**Comment by slimsag** [comment] 2020-02-10 20:52
I assume because we're all still discussing the implementation here that my last message lacked detail (combined with the fact that nobody else has worked on this code), so here is a different attempt.

@unknwon @keegancsmith here is a draft PR with all of the frameworking written out for you, as well as two test cases (one simple one, one complex one). I think with this it should be straightforward to implement this with the right approach: https://github.com/sourcegraph/sourcegraph/pull/8349 Can someone own this PR from here?

@nicksnyder Solving this problem in the frontend is NOT a good idea, because it means we're still transferring all of that extra data to the browser. On these long lines, this can be a few KB of data (e.g. a minified JS file) and that can add up quick after we load ~40 search results. This is why I suggested doing it on the backend and making it an optional parameter the frontend could pass via GraphQL (in case in the future we _do_ really want a way to say "Hey, highlight these ultra-long lines because" or maybe even having it on-by-default for Firefox which appears to handle this rendering much better). For now, it can just be off-by-default (until we get user feedback saying otherwise).

@keegancsmith Solving this in the Rust code is not possible without delving into the Syntect internals, and even then I'm not sure this change would be upstreamable unless we made it a config option. I know nobody here knows Rust, and that's why we already do some post-processing in the Go code of what Syntect gives us. It makes sense to do it in the Go side.

**Comment by unknwon** [comment] 2020-02-11 05:12
Thanks @slimsag ❤️ I'll own the #8349.

**Comment by keegancsmith** [comment] 2020-02-11 07:06
> I assume because we're all still discussing the implementation here that my last message lacked detail (combined with the fact that nobody else has worked on this code), so here is a different attempt at communicating how this should work:

Thank you for the detailed response + PR. Sorry I actually missed your comment above!

**Comment by unknwon** [comment] 2020-02-11 13:47
PR finished: https://github.com/sourcegraph/sourcegraph/pull/8349

**Closed** 2020-02-12 07:15 UTC
Labels: bug, estimate/1d, search, team/core-services
