### ISSUE TITLE
500 when navigating to URL for newly created repo

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#1101] opened 2018-11-21 20:23 UTC
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** Mac, Chrome

#### Steps to reproduce:

1. Navigate to https://sourcegraph.com/github.com/sourcegraph/sourcegraph-debug-extension

#### Expected behavior:

Repo would clone and then we'd see the repo data

#### Actual behavior:

Get a 500 error

**Comment by slimsag** [comment] 2018-11-21 20:34
The lightstep trace shows the real error:

```
pq: new row for relation "repo" violates check constraint "check_name_nonempty"
```

In the call to `Repos.Add`

https://app.lightstep.com/sourcegraph-prod/trace?span_guid=6a27486a1c848f10&at_micros=1542832356165410#span-40191d5dbf8e8f5b

So this looks like a regression

**Comment by nicksnyder** [comment] 2018-11-21 21:58
Possibly caused by https://github.com/sourcegraph/sourcegraph/pull/954; I will check

**Comment by nicksnyder** [comment] 2018-11-21 22:09
Apparently my change is not deployed yet, so couldn't be that.

**Comment by slimsag** [comment] 2018-11-21 22:16
It could be an old regression that we just never caught, actually. i.e. not a recent regression

**Comment by slimsag** [comment] 2018-11-21 22:16
either way this is pretty serious I think, we should check if it happens on other repositories or not

**Comment by sqs** [comment] 2018-11-21 23:47
It is working now (https://sourcegraph.com/github.com/sourcegraph/sourcegraph-debug-extension shows the repo).

The error about the `check_name_nonempty` constraint violation does suggest there was a new error. My guess is that a very old `repo-updater` got deployed that was before my commit a ~month ago that renamed `uri` to `name`. It was sending a `uri` field in the JSON from repo-updater to frontend, and frontend was seeing an empty `name`.

@nicksnyder's deploying the latest repo-updater fixed it (see https://sourcegraph.slack.com/archives/C08JA8Q1H/p1542838405218400).

Since this was caused by a bad deploy, I am closing this. We are already working on a fix to reduce the rate of bad deploys (@ggilmore's deployment project).

**Closed by sqs** 2018-11-21 23:47 UTC
Labels: bug
