### ISSUE TITLE
dhall: implement postgres service in deploy-sourcegraph-dhall

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#16258] opened 2020-11-30 20:22 UTC
- [ ] implement postgres with support for shared + sourcegraph.com customization
- [ ] write documentation for the implemented customization
- [ ] write tests for each customization

**Comment by pecigonzalo** [comment] 2020-11-30 20:59
Duplicate of: https://github.com/sourcegraph/sourcegraph/issues/16262

**Closed by pecigonzalo** 2020-11-30 20:59 UTC
Labels: dhall, team/distribution
