### ISSUE TITLE
Hover erroring out in the Sourcegraph web UI

### ISSUE THREAD

**Issue by lawrence-tan** [sourcegraph/sourcegraph#12161] opened 2020-07-14 15:12 UTC
- **Sourcegraph version:** 3.16.1

#### Steps to reproduce:

1. Browse to any C++ file in either Chrome or Firefox (these are the browsers I tested)
2. Mouse over a symbol

#### Expected behavior:
A pop up appears with documentation, and 2 buttons.

#### Actual behavior:
Nothing happens. The browser console logs errors every time I mouse over.
<img width="676" alt="Screen Shot 2020-07-14 at 11 04 05 AM" src="https://user-images.githubusercontent.com/2185478/87442775-b0472000-c5c2-11ea-89f4-4d16ec913474.png">

Users report this issue seems to have started some time yesterday.

**Comment by dadlerj** [comment] 2020-07-15 15:20
Reported by https://app.hubspot.com/contacts/2762526/company/2931649618

**Comment by efritz** [comment] 2020-07-15 15:57
Hi, sorry abut this. Looks like I didn't properly format an introspection query that checks for a feature that's only available in the upcoming release. This should be fixed by https://github.com/sourcegraph/code-intel-extensions/pull/424 and will get this merged as soon as possible (GitHub is having some stability issues right now which is affecting our build/deploy pipeline).

**Comment by lawrence-tan** [comment] 2020-07-15 16:20
Sounds good - thanks!

**Comment by efritz** [comment] 2020-07-15 17:06
The extensions are begin published now. Please let me know if you can still reproduce this issue.

**Comment by lawrence-tan** [comment] 2020-07-15 18:12
This appears to work correctly now. Thanks for the quick response!

**Closed** 2020-07-15 18:40 UTC
Labels: bug, team/code-intelligence
