### ISSUE TITLE
GitHub auth: Restrict signup based on organization affiliation

### ISSUE THREAD

**Issue by KattMingMing** [sourcegraph/sourcegraph#2801] opened 2019-03-18 16:50 UTC
When using GitHub auth (GitHub.com) for a self-hosted Sourcegraph instance – admins need to specify `allowSignup=false` to prevent arbitrary GitHub users from signing up.

We should make it possible for admins to allow members of their organization to sign up with requiring an admin to manually create an account and verify the email address.

Somewhat related to: https://github.com/sourcegraph/sourcegraph/issues/2419

Additional context: https://sourcegraph.slack.com/archives/C0B2RU51Q/p1552926270224900

Requested by https://app.hubspot.com/contacts/2762526/company/1305798737

**Comment by beyang** [comment] 2019-03-18 18:42
Trying to understand the goal here. If permissions are enabled on the instance, then arbitrary GitHub users will be able to authenticate to Sourcegraph, but they *won't* have access to private repositories. This is similar to authenticating to signing into any cloud app that supports sign-in via GitHub.

If the concern is general access to the instance, then the instance should be placed behind an auth proxy. If the concern is permissions, then enabling GitHub permissions should resolve that. Restricting sign-up to org users doesn't really add anything as far as security is concerned.

**Comment by KattMingMing** [comment] 2019-03-18 21:15
I think the goal here is very similar to: `"requireEmailDomain"` for OpenIDConnect (but for GitHub auth). Restrict access to a subset of users who are part of a GitHub organization so that the admin does not need to manually create accounts or worry about unauthorized users accessing the instance.

It's possible that a site admin only wants the dev team (those added to the GitHub organization) to be able to create accounts so that other employees or non-employees can access the instance.

There might be a better option like #2419. Support GitHub ACLs without GitHub configured as auth provider would be helpful in this scenario and many others so I think that would be higher priority. Thoughts?

**Comment by sqs** [comment] 2019-03-19 06:36
Is this a fair description of the (desired) use case?

> As a site admin, I would like to make it so only members of a certain GitHub organization can use Sourcegraph. And:
>
> - (A) If I remove a user from the GitHub organization, they should not be able to use Sourcegraph anymore (subject to a short time period for syncing, like 5 minutes).
> - (B) Users should only be able to view/search a repository on Sourcegraph if they can also do so on GitHub (i.e., use GitHub repository permissions).
> - (C) Users not in the organization should not even be allowed to sign into my Sourcegraph instance.
> - (D) My Sourcegraph instance will be Internet-accessible (i.e., not behind another auth proxy or VPN).

Let me know if any of these are NOT important.

I think nailing this would be the holy grail as it would make setup much easier. If this is right, we should work toward making this happy path possible and easy to configure.


---

One tricky difference with `requireEmailDomain` is that a GitHub user's organizations can change (i.e., when a person leaves a company) and I think the expectation is that the user loses access then. This isn't really a problem with `requireEmailDomain` because a user who leaves a company won't have an OpenID Connect account anymore, so *we* don't need to handle that case.

**Comment by KattMingMing** [comment] 2019-03-22 16:37
@sqs – Yes that's correct

**Comment by sqs** [comment] 2019-03-23 08:37
:+1: I am thinking we need to prioritize a holistic way to "make my instance work well with my GitHub org" that includes repos, SSO, permissions, certain extensions, etc. (And same for other code hosts, but GitHub is the first.) I have this in the updated product roadmap #2932 and will come up with a plan with @beyang 	soon.

**Comment by beyang** [comment] 2019-11-25 17:39
Dupe of https://github.com/sourcegraph/sourcegraph/issues/4195

**Closed by beyang** 2019-11-25 17:39 UTC
Labels: auth, customer
