### ISSUE TITLE
Symbol search input not full width

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#16598] opened 2020-12-09 20:07 UTC
![image](https://user-images.githubusercontent.com/10532611/101681487-7ccdcc00-3a62-11eb-95e3-4229150ee64d.png)

**Comment by umpox** [comment] 2021-01-13 15:39
Regression from https://github.com/sourcegraph/sourcegraph/pull/16194

**Comment by umpox** [comment] 2021-01-19 17:05
@tjkandala I believe this is fixed after the changes made in https://github.com/sourcegraph/sourcegraph/pull/17385?

**Comment by tjkandala** [comment] 2021-01-19 17:11
@umpox Yeah, this is a duplicate of #16268 (same root cause), which is fixed now 👍

**Closed by tjkandala** 2021-01-19 17:11 UTC
Labels: bug, team/web
