### ISSUE TITLE
Hovering over Go func name does not bring up tooltip for find references

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4910] opened 2019-07-16 18:02 UTC
![out](https://user-images.githubusercontent.com/15530/61318114-2bf86c00-a7b9-11e9-9f2b-449c836e0a55.gif)

**Comment by ggilmore** [comment] 2019-07-16 18:04
@ijt Please put this in the 3.6 milestone and label it appropriately so that it can be tracked.

**Comment by ijt** [comment] 2019-07-16 18:53
I cloned `sourcegraph/zoekt` locally then ran `fakehub ~/src/github.com/` and added an external service for the fakehub process. Then I navigated to a Go file in `repos/sourcegraph/zoekt` and moused over a func name. I expected a tooltip to come up with a button for Find References, but that didn't happen.

**Comment by keegancsmith** [comment] 2019-07-17 10:58
I tested basic code intel several times and it worked. Do you mind including any console output incase others can't reproduce. Additionally failing network requests related to code intelligence.

@chrismwendt I have assigned to you. If you don't have bandwidth to fix today (Wednesday), please ensure you assign to someone else appropriate who can fix.

**Comment by chrismwendt** [comment] 2019-07-17 22:15
Can you post your external service config? I don't know how to configure fakehub, and I couldn't find any docs in sourcegraph/sourcegraph. User/org/global settings will be helpful, too.

I'm curious which extensions you have enabled. Can you set `localStorage.debug=true` in the browser and refresh the page then expand the little Ext menu in the bottom right?

Try clicking on the Symbols sidebar on the left to see if any symbols are found for this repository.

**Comment by ijt** [comment] 2019-07-18 00:00
To set up fakehub, `cd sourcegraph/dev/fakehub; go build`, then run
something like `./fakehub dir/containing/repos` and the paste the config
from `http://localhost:3434` into sourcegraph for a single git repositories
external service.

I'll try one more time and then post my external service config.

**Comment by ijt** [comment] 2019-07-18 00:10
One caveat, for an image like this, it's necessary to replace `127.0.0.1` with `host.docker.internal` in the config generated by `fakehub`.

**Comment by ijt** [comment] 2019-07-18 00:13
Okay, the same problem is still occurring, and I verified that the Go code intelligence extension is enabled. Here is my external service config:
```
// Paste this into Site admin | External services | Add external service | Single Git repositories:
{
  "url": "http://host.docker.internal:3434",
  "repos": [
    "/repos/Depado/bfchroma/.git",
    "/repos/acroca/go-symbols/.git",
    "/repos/alecthomas/chroma/.git",
    "/repos/alecthomas/gometalinter/.git",
    "/repos/bminor/bash/.git",
    "/repos/cweill/gotests/.git",
    "/repos/danwakefield/fnmatch/.git",
    "/repos/davidrjenni/reftools/.git",
    "/repos/dlclark/regexp2/.git",
    "/repos/emirpasic/gods/.git",
    "/repos/fatih/gomodifytags/.git",
    "/repos/fatih/motion/.git",
    "/repos/fsnotify/fsnotify/.git",
    "/repos/gitolite/.git",
    "/repos/go-delve/delve/.git",
    "/repos/golangci/golangci-lint/.git",
    "/repos/google/zoekt/.git",
    "/repos/graph-gophers/graphql-go/.git",
    "/repos/graphql-go/graphql/.git",
    "/repos/ijsnow/env/.git",
    "/repos/ijt/hammer/.git",
    "/repos/ijt/home/.git",
    "/repos/ijt/mempig/.git",
    "/repos/ijt/reponames/.git",
    "/repos/ijt/reponames2/.git",
    "/repos/ijt/zoekt/.git",
    "/repos/ijt/zoekt.bak/.git",
    "/repos/jbenet/go-context/.git",
    "/repos/josharian/impl/.git",
    "/repos/jstemmer/gotags/.git",
    "/repos/karrick/godirwalk/.git",
    "/repos/kevinburke/ssh_config/.git",
    "/repos/kisielk/errcheck/.git",
    "/repos/klauspost/asmfmt/.git",
    "/repos/koron/iferr/.git",
    "/repos/mattn/go-runewidth/.git",
    "/repos/mdempsky/gocode/.git",
    "/repos/mitchellh/go-homedir/.git",
    "/repos/nsf/termbox-go/.git",
    "/repos/opentracing/opentracing-go/.git",
    "/repos/pelletier/go-buffruneio/.git",
    "/repos/pkg/browser/.git",
    "/repos/pkg/errors/.git",
    "/repos/ramya-rao-a/go-outline/.git",
    "/repos/rogpeppe/godef/.git",
    "/repos/russross/blackfriday/.git",
    "/repos/sergi/go-diff/.git",
    "/repos/shurcooL/sanitized_anchor_name/.git",
    "/repos/sitaramc/gitolite/.git",
    "/repos/sourcegraph/codeintellify/.git",
    "/repos/sourcegraph/deploy-sourcegraph/.git",
    "/repos/sourcegraph/deploy-sourcegraph-dogfood-k8s/.git",
    "/repos/sourcegraph/deploy-sourcegraph-dot-com/.git",
    "/repos/sourcegraph/dev-private/.git",
    "/repos/sourcegraph/docsite/.git",
    "/repos/sourcegraph/go-jsonschema/.git",
    "/repos/sourcegraph/infrastructure/.git",
    "/repos/sourcegraph/infrastructure/docker-images/zoekt-webserver/zoekt/.git",
    "/repos/sourcegraph/interviews/.git",
    "/repos/sourcegraph/jsonschemadoc/.git",
    "/repos/sourcegraph/sourcegraph/.git",
    "/repos/sourcegraph/src-cli/.git",
    "/repos/sourcegraph/test-saved-searches/.git",
    "/repos/sourcegraph/zoekt/.git",
    "/repos/sqs/goreturns/.git",
    "/repos/src-d/gcfg/.git",
    "/repos/stamblerre/gocode/.git",
    "/repos/uudashr/gopkgs/.git",
    "/repos/xanzy/ssh-agent/.git",
    "/repos/zmb3/gogetdoc/.git",
  ]
}
```

**Comment by chrismwendt** [comment] 2019-07-18 00:15
Ok, I have a repro. I'm running `./enterprise/dev/start.sh` and I have 2 external services that both specify sourcegraph/zoekt:

- GitHub ✅ hovers appear
- Single git repository (from fakehub)  ❌ hovers do not appear (but the extension's `activate()` gets called)

I'm still looking into this.

**Comment by chrismwendt** [comment] 2019-07-18 00:51
Ah, here's what's happening:

When you hover, the Sourcegraph web app tests the current document URI against file patterns associated with hover providers with "globstar" `**`:

https://github.com/sourcegraph/sourcegraph/blob/6fef4bf23ac3c562bf686f16e9f3e9ec9f63514d/shared/src/api/client/types/textDocument.ts#L127-L130

Document URIs look like this:

`git://127.0.0.1-3434/repos/.git?51c44e6be08627c613f787032a2759162bf6f7c2#web/api.go`

Directories starting with `.` are considered by [minimatch](https://github.com/isaacs/minimatch) to be hidden and are ignored (unless you set [`dot: true`](https://github.com/isaacs/minimatch#dot)).

Single git repositories usually have `/.git` somewhere in the document URIs, which causes minimatch to ignore everything after the `/.git`.

I'm considering specifying `dot: true` to fix this now, but I'm open to ideas (e.g. only testing the file path in the fragment of the URI).

**Closed** 2019-07-18 04:36 UTC
Labels: bug, code-nav, release-blocker

**Comment by keegancsmith** [comment] 2019-07-18 12:35
I just tested this using fakehub on the latest rc (rc3), and code intel worked. Marking the testing grid as done.
