### ISSUE TITLE
search query parse error on `(" ")`

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#4562] opened 2019-06-17 22:13 UTC
It seems like this should work:

<img width="493" alt="Screen Shot 2019-06-17 at 15 12 13" src="https://user-images.githubusercontent.com/15530/59640250-4edc2580-9112-11e9-990c-bea6fc58f821.png">

**Comment by slimsag** [comment] 2019-06-18 03:36
I think the reason it doesn't is because `("` and `")` are treated as separate regexes.

**Comment by rvantonder** [comment] 2020-07-20 17:41
Confirmed fixed by adding `search.migrateParser` flag in https://github.com/sourcegraph/sourcegraph/pull/12184 (available in user/org/global settings). Will close this issue when we flip the switch.

**Comment by lguychard** [comment] 2020-10-06 13:47
The switch has been flipped.

**Closed by lguychard** 2020-10-06 13:47 UTC
Labels: bug, team/search
