### ISSUE TITLE
Sourcegraph explore page not loading

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4084] opened 2019-05-17 00:25 UTC
- **Sourcegraph version:** "Sourcegraph.com" 

#### Steps to reproduce:

1. Go to https://sourcegraph.com/explore
2. It never loads.

Probably related to: https://github.com/sourcegraph/sourcegraph/issues/4057

#### Expected behavior:
See the explore page.
#### Actual behavior:
![image](https://user-images.githubusercontent.com/9110008/57895109-da565400-77fe-11e9-9d6f-763131ff130d.png)

**Comment by slimsag** [comment] 2019-05-17 00:26
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/4057 for certain

**Closed by slimsag** 2019-05-17 00:26 UTC
