### ISSUE TITLE
Routine background task that cleans up users that are inactive

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40626] opened 2022-08-19 20:42 UTC
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 via [Slack thread](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1659431596108699)

#### Feature request description

It would be nice if there was a background task that could be configured to automatically clean up "inactive" users (defined as users that have not had any activity in more than X days).

#### Is your feature request related to a problem? If so, please describe.

Customers would like that if users logged in and never came back, they should be removed.

Currently, customers are running a [custom cleanup_users.py script](https://github.com/sourcegraph/customer-assets/blob/main/ce-tools/pysdk/cleanup_users.py) (or in the future using [`src users cleanup`](https://github.com/sourcegraph/sourcegraph/issues/40102).  

#### Describe alternatives you've considered.

Running the above mentioned scripts in a cron job.

/cc @sourcegraph/iam

**Comment by unknwon** [comment] 2022-08-24 07:15
Assuming this is coming from inactive users consuming the license seats, I feel we need to address this at the root cause (how we bill customers) instead of providing "official" hacks.

**Comment by DaedalusG** [comment] 2022-08-28 08:59
Just noting an MVP for this is ready for review: https://github.com/sourcegraph/src-cli/pull/826

**Comment by ryphil** [comment] 2022-10-27 21:34
Going to close this issue for now since we have the hacky solution done and new billing introduced.

**Closed by ryphil** 2022-10-27 21:34 UTC
Labels: feature-request, customer, team/iam
