### ISSUE TITLE
symbols: implement sub-repo perms filtering in symbols client

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#28245] opened 2021-11-26 23:20 UTC
Implement filtering in the [symbols client](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@738e0b5b152def3b172baa927e46f049eef6a56f/-/blob/internal/symbols/client.go?L46) 

-   The client API returns a [Symbol with a Path field](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@738e0b5b152def3b172baa927e46f049eef6a56f/-/blob/internal/search/result/symbol.go?L17-20) that we can use for path-based filtering.
- Alternative: implement in the [symbols service](https://github.com/sourcegraph/sourcegraph/blob/738e0b5b152def3b172baa927e46f049eef6a56f/cmd/symbols/internal/symbols/search.go#L237)

**Comment by ryanslade** [comment] 2021-12-13 13:28
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/28273

**Closed by ryanslade** 2021-12-13 13:28 UTC
Labels: estimate/5d, team/repo-management, PD-503
