### ISSUE TITLE
syntect server fails with large files

### ISSUE THREAD

**Issue by ijsnow** [sourcegraph/sourcegraph#3421] opened 2019-04-16 01:30 UTC
[After adding the search.largeFiles config flag,](https://github.com/sourcegraph/sourcegraph/pull/3337) we get an error from syntect server when making requests to syntax highlight a file.

![Screenshot 2019-04-15 18 29 24](https://user-images.githubusercontent.com/11557758/56175541-6d0b9500-5fac-11e9-82ba-44efb87f07f0.png)

To reproduce, follow the steps for testing https://github.com/sourcegraph/sourcegraph/pull/3337.

**Comment by keegancsmith** [comment] 2019-04-16 08:33
That error message usually indicates we need to update the client to parse non-json responses (can happen with non-200 responses)

**Comment by slimsag** [comment] 2019-04-16 09:11
Most likely the way syntect_server (really, Rocket.rs) responds to JSON
posts that are too large has changed and this wouldve been a regression
from a few months back.

We will need to update the error handling for that case:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/highlight/highlight.go?suggestion#L85

**Comment by ijsnow** [comment] 2019-04-16 21:57
Yea, looks to be coming from here https://sourcegraph.com/github.com/sourcegraph/gosyntect@HEAD/-/blob/gosyntect.go#L101:1

**Comment by ijsnow** [comment] 2019-04-16 21:59
However, suggesting that we only update error handling has some disconcerting implications. With https://github.com/sourcegraph/sourcegraph/pull/3337 we'll be able to search large files but then never get to see the results. Do you mean that syntect just can't handle files that large? Does this mean we should come up with some new UX for searching large files such as "results found in file but file is too large to display"?

**Comment by slimsag** [comment] 2019-04-16 22:39
@ijsnow If you look at what happens when the error case above that I linked to runs, it falls back to rendering plaintext. `syntect_server` rejects files that are too large to highlight, so we display them without syntax highlighting.

**Comment by ijsnow** [comment] 2019-04-17 21:16
@slimsag so the error is because rocket.rs [kills streams over a certain size.](https://sourcegraph.com/github.com/SergioBenitez/Rocket@v0.4/-/blob/core/lib/src/data/data_stream.rs#L38) I'm not sure what changed to it to send html responses about malformed data instead of a JSON response as our code seems to expect.

Proposal: we short circuit requests to highlight files that are larger than what rocket.rs will accept. We can just return early in `client.Highlight` if the [json encoded request body](https://sourcegraph.com/github.com/sourcegraph/gosyntect/-/blob/gosyntect.go#L69:2) is too big.

**Comment by slimsag** [comment] 2019-04-17 22:02
@ijsnow the code that you linked to in rocket.rs is not it killing streams over a certain size (1024 bytes would be ridiculously low), that code is just flushing the network stream if Rocket has already decided to kill the stream for some other reason.

The real limit is self-imposed in our Rocket.rs configuration, you can find it here: https://github.com/sourcegraph/syntect_server/blob/master/Dockerfile#L21

I would suggest we do not short-circuit the requests and instead let Rocket handle terminating them and just properly respond to the error it responds with. If we try to short-circuit it, then we are keeping that upper limit on JSON in two locations and making it harder to configure which isn't good.

The way to do this would be seeing if Rocket.rs returns an error status code here and returning a different Go error type if so: https://sourcegraph.com/github.com/sourcegraph/gosyntect/-/blob/gosyntect.go#L98

**Comment by ijsnow** [comment] 2019-04-17 22:07
The error is a response with code 400 and an html body saying the request was malformed. Going with your suggestion and the data we get from rocket, we'll silently swallow all 400 errors even if they aren't due to the max size being exceeded. If we're alright with that, I'll make that change. @slimsag

**Comment by slimsag** [comment] 2019-04-17 22:08
Yep, that's what I would expect & that sounds like the right approach.

**Comment by slimsag** [comment] 2019-04-17 22:10
You can define the error type here:

https://sourcegraph.com/github.com/sourcegraph/gosyntect/-/blob/gosyntect.go#L46-49

Also, in light of this info we should update the API section of syntect_server here to say a 400 response indicates trying to highlight a file that is too large: https://github.com/sourcegraph/syntect_server#api

**Comment by slimsag** [comment] 2019-04-17 22:54
Reopening b/c we still need to update API docs of syntect_server mentioned above

**Comment by nicksnyder** [comment] 2019-07-16 16:41
A customer reported seeing `aborted fetching highlighted contents` today and requested fallback to non-highlighted results: https://sourcegraph.slack.com/archives/G9EN3TJDD/p1563292689228100?thread_ts=1563208733.221700&cid=G9EN3TJDD

**Comment by slimsag** [comment] 2019-07-16 21:47
It appears that customer is at latest on 3.4.4 because that error only exists in 3.4.4, and this issue was fixed in 3.4.5. The solution here is to upgrade to 3.4.5 or later.

**Closed by slimsag** 2019-07-16 21:47 UTC
Labels: bug, customer
