### ISSUE TITLE
cloning does not restart after gitservers are replaced

### ISSUE THREAD

**Issue by davejrt** [sourcegraph/sourcegraph#11091] opened 2020-05-28 21:16 UTC
- **Sourcegraph version:** 3.16
- **Platform information:** GKE version 1.14

A large (140,000k) of repositories were waiting to be cloned after the gitserver stateful set had to be redeployed due to disk issues. However the gitservers, nor the repo-updater were acting on the queue on repos after redeployment. Only manually triggering the repos one by one would start a clone. The external source was then removed again. 

There was no log evidence to suggest a problem with either service. In the notifications in the UI, the ony message suggested that the repos were waiting to be cloned, with nothing happening. 

When removing the external source, and adding it back again, the repo-updater ran out of memory. This was increased, which then appeared to shift the load to postgres, which then had a memory limit increase and the sync completed with the repos from the external source no longer being in the queue. 

- **Expected behaviour**

This is potentially an extreme example, but not outside the realms of possibly for larger customers who need to increase storage on their cluster. At a minimum it should be possible to trigger a re-clone of the repos via the UI or src-cli. 

- **Actual behaviour**

When repos need to be cloned, there is no way to manually kick off this process, or evidence that something is happening when a large number of repos is in the queue

**Comment by tsenart** [comment] 2020-06-01 08:51
@davejrt, @uwedeportivo: Please assign team/core-services issues to me for triage. Otherwise they'll fall through the cracks :)

**Comment by tsenart** [comment] 2020-06-01 08:53
@keegancsmith: Is this a duplicate of https://github.com/sourcegraph/sourcegraph/issues/2485?

**Comment by keegancsmith** [comment] 2020-06-01 09:46
Related but not a duplicate. The issue here is in the repo-updater git fetch/clone queue. I'm unsure if we have a bug where we don't reclone until manually visited, or just that the queue is so big that it takes us a long time to check if a repo exists again. Either way it is visible as nothing working.

The likely solution is related to #2485 were we need to notice repos missing and update the state in the git clone queue so they get correctly prioritized.

**Comment by slimsag** [comment] 2020-06-19 04:43
PR for this here: https://github.com/sourcegraph/sourcegraph/pull/11602

**Comment by keegancsmith** [comment] 2020-06-22 16:36
Fixed in https://github.com/sourcegraph/sourcegraph/pull/11628

Does this need to be cherry-picked anywhere? If so please reopen.

**Closed by keegancsmith** 2020-06-22 16:36 UTC
Labels: RFC-151, bigdata, team/cloud, team/web

**Comment by slimsag** [comment] 2020-06-23 02:37
Shipping as part of https://github.com/sourcegraph/sourcegraph/issues/11642 -- thanks for the improved/better fix!
