### ISSUE TITLE
Impossible to sync repositories on new instance on latest insiders (external service id=1 config error: failed to parse JSON: [InvalidSymbol])

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#14644] opened 2020-10-13 00:08 UTC
1. Run the latest `sourcegraph/server:insiders` image (make sure it is up to date and starting clean):

```
docker pull sourcegraph/server:insiders
rm -rf ~/.sourcegraph/
docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:insiders
```

2. Go to **Manage repositories** and add **GitHub.com** repositories with the very basic config:

```
{
  "url": "https://github.com",
  "token": "<your token with repo scope>",
  "orgs": []
}
```

3. Repositories do not clone, there is an error in the code host cloud icon indicator (impossible for me to copy the text due to issue #14643):

![image](https://user-images.githubusercontent.com/3173176/95800345-e96b5b00-0cab-11eb-9cdb-798d50e83268.png)

The server logs indicate:

```
23:38:12                          frontend | ✱ Sourcegraph is ready at: http://127.0.0.1:7080
23:55:04                      repo-updater | t=2020-10-12T23:55:04+0000 lvl=warn msg="Handling rate limiter sync" err="getting rate limit configuration: loading service configuration: failed to parse JSON: [InvalidSymbol]"
23:55:04                      repo-updater | t=2020-10-12T23:55:04+0000 lvl=eror msg="Getting normalised URL from service" err="parsing config: failed to parse JSON: [InvalidSymbol]"
23:55:08                      repo-updater | t=2020-10-12T23:55:08+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
23:55:13                      repo-updater | t=2020-10-12T23:55:13+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
23:55:13                      repo-updater | t=2020-10-12T23:55:13+0000 lvl=warn msg="Marked record as errored" name=repo_sync_worker id=1 err="syncer.sync.sourced: 1 error occurred:\n\t* external service id=1 config error: failed to parse JSON: [InvalidSymbol]\n\n"
23:55:18                      repo-updater | t=2020-10-12T23:55:18+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
23:55:23                      repo-updater | t=2020-10-12T23:55:23+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe." seriousProblems="[Could not parse config of external service 1: failed to parse JSON: [InvalidSymbol]]"
...
```

Connecting to the psql DB shows the config is not the previously entered JSON (encrypted I assume?):

```
sourcegraph=# select kind,display_name,config from external_services;
  kind  | display_name |                                                                                         config                                                                                          
--------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 GITHUB | GitHub       | 98194a$QxF90bX560zokRVhWddUTOBcSLjKy+ZZ5D/1au6heihLLgUCtUVk4iEa7AlUaM0kdeU2sWz9oWtxUD+OV/zTFkparDwjWEtgTe+uouX8Nh9SAH8DHRM26/7OfXtpOu3NQedRqbW72OvhfWafm2SVWXtnM7F28hmgp59ujCRdyClI8Q==
(1 row)
```

**Comment by slimsag** [comment] 2020-10-13 00:09
I suspect that maybe `external_services` DB `config` column is now being encrypted, but not being decrypted properly somewhere by accident? cc @sourcegraph/security @sourcegraph/cloud

**Comment by unknwon** [comment] 2020-10-13 06:36
Located root cause: decryption layer is not inject here:

https://github.com/sourcegraph/sourcegraph/blob/eaf75eeb50e6316065ae5febfa2e1fdaad3db3b3/cmd/repo-updater/repos/store.go#L1406

Working on it.

**Comment by unknwon** [comment] 2020-10-13 07:37
Although https://github.com/sourcegraph/sourcegraph/pull/14652 addresses this issue directly, I would also like #14653 to be merged as part of the fix, because we used to automatically turn on encryption for single-docker-container but look back now I think it was a mistake.

IMO we should only turn on encryption when the customer explicitly chooses to (cc @sourcegraph/security ). If we agree on my opinion, we need to add a migration note for single-docker-container users:

> Please delete `/var/lib/sourcegraph/token` inside container before upgrade to 3.21.

**Comment by chayim** [comment] 2020-10-13 09:57
> IMO we should only turn on encryption when the customer explicitly chooses to (cc @sourcegraph/security ). If we agree on my opinion, we need to add a migration note for single-docker-container users:
> 
> >

Agreed! The original thinking when developed involved generating a key for the single docker use case, but there's genuinely no need. Thanks @unknwon

**Comment by uwedeportivo** [comment] 2020-10-14 19:03
since #14653 got merged, is this still a release blocking issue ?

**Comment by unknwon** [comment] 2020-10-15 10:50
@uwedeportivo Thanks for the reminder, closed.

**Closed** 2020-10-15 10:49 UTC
Labels: estimate/0.5d, qa-tests, regression, release-blocker, repo-updater
