### ISSUE TITLE
Long filename/path spacing issue on responsive size

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#14336] opened 2020-10-01 10:50 UTC
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** FF 81.0

#### Steps to reproduce:

1. Open a file with a long path
2. Make the window narrow enough to trigger a responsive breakpoint

#### Expected behavior:

Short term, should probably just wrap with `justify-content: flex-start`.

![Screenshot 2020-10-01 at 12 49 06](https://user-images.githubusercontent.com/6304497/94800158-80026700-03e4-11eb-9a18-c7daeb89133a.png)

#### Actual behavior:

Uses `justify-content: space-between`, which breaks the visual connection of the path.

![Screenshot 2020-10-01 at 12 50 10](https://user-images.githubusercontent.com/6304497/94800290-a7593400-03e4-11eb-9edb-5425787fcdbb.png)

https://www.loom.com/share/2148e891f9064e2b88a68cfd59ee3a43

**Comment by tjkandala** [comment] 2020-10-02 18:00
I believe that this is caused by the `container-fluid` class, which adds `flex-wrap: wrap`. A possible quick fix is to add the `flex-nowrap` utility. This change was introduced in #14138, and I don't know about the background/context/motivation, so cc @eseliger @felixfbecker @AlicjaSuska.

**Comment by eseliger** [comment] 2020-10-02 18:30
Interesting! That must be a side effect, we only wanted to fix the margin on the left.

**Comment by felixfbecker** [comment] 2020-10-02 19:28
That sounds like the right fix @tjkandala

**Comment by rrhyne** [comment] 2020-10-12 17:38
There is another issue associated with this behavior. The right side items conflict with the breadcrumb and should drop to their own line at small sizes. 

I believe @AlicjaSuska did a comp of this at one point? 

![image](https://user-images.githubusercontent.com/539268/95775264-f3bf3200-0c76-11eb-9efc-3aba097ea76e.png)

**Comment by Joelkw** [comment] 2020-12-03 03:43
Not an exact duplicate, but similar type of bug to #16373

**Comment by 5h1rU** [comment] 2021-01-18 19:35
@Joelkw Can you please confirm if this is still an issue? I took a look at sourcegraph.com, and the breadcrumb shown in the description isn't there anymore.

**Comment by Joelkw** [comment] 2021-01-20 08:43
@5h1rU Sorry, just catching up on my Github from being out on Monday – looks like [you got an answer](https://sourcegraph.slack.com/archives/C01EM5J1NF8/p1610997525029900)! Feel free to close if this isn't an issue anymore now.

**Comment by AlicjaSuska** [comment] 2021-01-20 14:35
There is one more thing @5h1rU - repository icon drops unnecessarily to the next line:
<img width="1077" alt="Screenshot 2021-01-20 at 15 34 29" src="https://user-images.githubusercontent.com/20326070/105189338-29f13500-5b35-11eb-9152-ff90c4ed6cf9.png">

**Comment by 5h1rU** [comment] 2021-01-20 17:14
Thanks for point this out @AlicjaSuska 

The linked PR is the fix for this issue.

**Closed** 2021-01-21 15:29 UTC
Labels: bug, team/web, webapp
