### ISSUE TITLE
Search results are duplicated

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#56676] opened 2023-09-15 09:48 UTC
Reported in Slack here: https://sourcegraph.slack.com/archives/C07KZF47K/p1694704136468579

Reproduce here: https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24%402bf80de+go.etcd.io%2Fbbolt&patternType=standard&sm=1&groupBy=path

## Evidence

![image](https://github.com/sourcegraph/sourcegraph/assets/1185253/fff4d7be-6f9b-4d74-b338-17ea51ac8a15)

![image](https://github.com/sourcegraph/sourcegraph/assets/1185253/bfe8e212-9197-48ff-8a02-5338aa1dc649)

**Comment by stefanhengl** [comment] 2023-10-04 08:43
I cannot reproduce this


![Image](https://github.com/sourcegraph/sourcegraph/assets/26413131/2936ddd8-46f4-4b5f-801d-380c46e2ff0c)

I tried a couple of times with variations in the query (different revisions), reloads etc, no luck. I move this query to backlog to keep it in mind once we see this happening again.

**Comment by keegancsmith** [comment] 2023-11-03 14:57
This seems to have disappeared. Worth closing out @stefanhengl?

**Closed** 2023-11-06 09:17 UTC
Labels: bug, team/search-platform
