### ISSUE TITLE
Cannot sign out of k8s.sgdev.org

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#6159] opened 2019-10-23 09:29 UTC
![2019-10-23 11 29 04](https://user-images.githubusercontent.com/10532611/67378951-5b70fe80-f588-11e9-84fe-fbe419b016b7.gif)

It is running 3.9.1 (latest)

**Comment by tsenart** [comment] 2019-10-23 09:37
Strange. Worked for me. How did you login?

**Comment by felixfbecker** [comment] 2019-10-23 09:41
I was already logged in - how can I find out?

**Comment by tsenart** [comment] 2019-10-23 09:44
I think it's likely that this is happening due to the release testing back and forth of creating / deleting / updating auth providers in the critical site config. If you clear your cookies / local storage and try to login with Google, then log-out, does this still happen?

**Comment by felixfbecker** [comment] 2019-10-23 09:47
I cleared cookies and am still signed in. On which page do I need to clear cookies?

**Comment by felixfbecker** [comment] 2019-10-23 09:49
I used incognito mode to sign in again with Google, and can reproduce the same behavior as soon as I am signed in.

**Comment by beyang** [comment] 2019-10-23 15:27
I cannot reproduce. Can you post what requests it makes in the Chrome network tab when you try to log out?

**Comment by unknwon** [comment] 2019-10-23 19:45
This is not a spam... it worked for me.

1. I have a non-admin test account left from 3.9 release test, and able to sign out.
2. Then signed in with my G Suite, and able to sign out.

**Comment by unknwon** [comment] 2019-11-23 00:14
What is the status of this issue right now? Is it still happening?

**Comment by beyang** [comment] 2020-01-07 00:29
Closing this as "cannot repro".

**Closed by beyang** 2020-01-07 00:29 UTC
Labels: auth, bug
