### ISSUE TITLE
Using an extension which provides line decorations breaks codecov extension

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2216] opened 2019-02-08 19:09 UTC
Code discussions is disabled by default on Sourcegraph.com, so this is not an issue for customers, but it does point to a flaw in the extension API (if one extension can break another).

https://cl.ly/fe1a6446fc1b

cc @slimsag

**Comment by slimsag** [comment] 2019-02-08 19:51
I renamed the issue title to clarify that this is an issue with extensions generally, not something specific to the code discussions ext.

**Comment by slimsag** [comment] 2019-02-08 19:51
I believe this would also happen with codecov + the blame extension for example.

**Comment by sqs** [comment] 2019-02-14 05:46
duplicate of #740

**Closed by sqs** 2019-02-14 05:46 UTC
Labels: bug, extensions
