### ISSUE TITLE
Add (back) inline git blame for the current line

### ISSUE THREAD

**Issue by halseth** [sourcegraph/sourcegraph#1113] opened 2018-11-23 15:00 UTC
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** macOS Mojave, Chrome 70.0.3538.102

#### Steps to reproduce:

1. Browse open source repo on sourcegraph.com
2. Select a line: https://sourcegraph.com/github.com/lightningnetwork/lnd/-/blob/htlcswitch/switch.go#L354

#### Expected behavior:
The commit message, date and author shows on the line.

#### Actual behavior:
Nothing shows up:
<img width="1510" alt="screenshot 2018-11-23 at 15 52 54" src="https://user-images.githubusercontent.com/3765732/48949573-b2192700-ef38-11e8-84e7-71f853fa2d2d.png">

This used to work before, but stopped working a few months back IIRC. I have also tried installing and enabling the `git-extras` extension, with no luck.

**Comment by sqs** [comment] 2018-11-24 04:19
Do you see a **Blame** button in the file header? When clicked, it should toggle on/off blame information, as seen below.

![screenshot from 2018-11-23 22-16-48](https://user-images.githubusercontent.com/1976/48964464-806e8300-ef6d-11e8-91e5-8479c39a647e.png)

We changed how this worked, as you noticed. If the problem is that you didn't notice the new **Blame** button, do you have any ideas on how we could have made it easier to spot?

**Comment by halseth** [comment] 2018-11-26 07:51
I did notice it, but I didn't realize it was a replacement for the oneliner-blame. 

IMO it clutters up the fileview way too much, and I cannot even tell if the blame applies to the lines above or below the selected line. (It is also extremely slow to load in my experience, which IIRC weren't the case for the oneliner version).

Possible to bring back the oneliner as an option? 😄

**Comment by sqs** [comment] 2018-11-26 07:57
Thanks, this is helpful to hear. Yes, we will add back some kind of current-line-only behavior to https://github.com/sourcegraph/sourcegraph-git-extras. That is blocked on https://github.com/sourcegraph/sourcegraph/issues/702 (the extension API does not tell extensions the currently selected line yet, but it will soon).

**Comment by sqs** [comment] 2019-01-30 07:31
Prioritizing for the [Sourcegraph 3.1](https://docs.sourcegraph.com/dev/roadmap#3-1) release

**Comment by lguychard** [comment] 2019-02-04 21:03
Reassigning to myself because I have an open PR for this: https://github.com/sourcegraph/sourcegraph-git-extras/pull/14

**Comment by nicksnyder** [comment] 2019-02-12 17:36
I am removing the release-blocker tag from this since this wouldn't block release.

**Closed** 2019-02-13 16:31 UTC
Labels: code-nav, extension-request, extensions, web
