### ISSUE TITLE
No hover information tooltip shown on variables where type is known

### ISSUE THREAD

**Issue by taiyab** [sourcegraph/sourcegraph#60915] opened 2024-03-07 08:56 UTC
We know what types the variables referenced in this function are, yet we don't surface that when hovering over the variable names:

https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1709791565057039

>When I hover over variables, such as clonedAllowedModels in [https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@071c24ee0e10831c64d[…]internal/httpapi/completions/upstream.go?L291:28-291:51](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@071c24ee0e10831c64d513063036fb6df1384b99/-/blob/cmd/cody-gateway/internal/httpapi/completions/upstream.go?L291:28-291:51), is it meant to show "No hover information available" even though it knows the type? When you click/hover a function, it shows the full type.

From @toolmantim 

Link to reproduce: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@071c24ee0e10831c64d513063036fb6df1384b99/-/blob/cmd/cody-gateway/internal/httpapi/completions/upstream.go?L291:28-291:51

<img width="930" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/c056c848-2ed9-4b6d-95b2-0cf9ed881987">

<img width="956" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/627069dc-d6cb-4aaa-bbe1-9b30f49dd05c">

<img width="638" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/5337876/ff5b25b5-83cc-4411-8c49-c8a64ddc2031">

**Comment by varungandhi-src** [comment] 2024-03-07 09:31
Small suggestion: When reporting issues, I recommend copying the main content from Slack into the issue description (e.g. in this case, it would've been useful to include the link https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@071c24ee0e10831c64d513063036fb6df1384b99/-/blob/cmd/cody-gateway/internal/httpapi/completions/upstream.go?L291:28-291:51). We have limited Slack retention, so sometimes the information can be lost if the issue is not fixed soon.

**Comment by varungandhi-src** [comment] 2024-03-07 10:34
Closing this issue in favor of https://github.com/sourcegraph/scip-go/issues/79

**Closed by varungandhi-src** 2024-03-07 10:34 UTC
Labels: bug, code-navigation
