### ISSUE TITLE
Docs for bare metal executors

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#25961] opened 2021-10-12 14:07 UTC

**Comment by mrnugget** [comment] 2022-01-13 09:02
I think this one's a duplicate of https://github.com/sourcegraph/sourcegraph/issues/26781 and also closed by

* https://github.com/sourcegraph/sourcegraph/pull/28127
* https://github.com/sourcegraph/sourcegraph/pull/28174

Feel free to re-open if you disagree.

**Closed by mrnugget** 2022-01-13 09:02 UTC
Labels: team/code-intelligence, team/batchers, auto-index-on-prem
