### ISSUE TITLE
UX: Line-wrapping in diff view make diffs hard to read

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#29709] opened 2022-01-13 18:02 UTC
See https://sourcegraph.slack.com/archives/C01FXGSJW5R/p1642083336018800

Line-wrapping creates weird indentation differences.

Fix: add horizontal scrolling

**Comment by adeola-ak** [comment] 2022-02-02 03:31
While trying to reproduce this issue I learned that the code text that is displayed in each line is actually made up of HTML blobs generated on the backend that are injected into a `<div>` with `dangerouslySetInnerHTML`. Since each word/symbol is wrapped in its own `<div>` or `<span>` this way, we can’t just apply a word-wrap CSS property to the line as initially expected.

![385FD322-EB0C-45BD-9917-897C6D91C453_1_105_c](https://user-images.githubusercontent.com/67931373/152088846-073df7cc-403f-4aa7-9a19-a01087e11c68.gif)

Ultimately, since the component that renders these lines is used so heavily across many different areas of the application, I decided the risk introduced by making this change is not worth the pay-off of the problem the user reported here, as modifying the `display` property is hard to thoroughly test the impact of would require much more thorough testing, so this could introduce worse regressions elsewhere. Furthermore, the initial line break behavior is apparently consistent with GitHub’s own line rendering, so the issue is not too bad?

<img width="867" alt="Screen Shot 2022-02-01 at 10 21 13 PM" src="https://user-images.githubusercontent.com/67931373/152088206-98be2f00-9349-49c1-a862-333f56d870ee.png">

**Comment by adeola-ak** [comment] 2022-02-10 19:21
@sourcegraph/batchers This was the issue from the brief discussion in todays retro

**Comment by eseliger** [comment] 2022-02-10 21:06
I do agree, that's a good assessment and thank you for doing the comparison to GitHub. If no one else feels strongly about this, I think that's our resolution here and we can close it out. :)

**Closed** 2022-02-21 00:35 UTC
Labels: good first issue, estimate/1d, team/batchers, ux

**Comment by malomarrec** [comment] 2022-02-21 11:24
Given this was the quickfix we'd discussed for a broader issue:

> Is there any way to download a patch file for what a sourcegraph batch would create? If I look in the UI for the batch preview I see some alignment issues, as you can seen in the image attached.
There's seemingly a linebreak and an indentation difference. I suspect this is the sourcegraph UI introducing that due to line wrapping, but I don't see any way that I could tell if that is the case or not. I could fire off the batch update and hope it's correct of course. 

I'll open a follow-up ticket for downloading the diff. It sounds reasonable for a user to want to check that the diff is actually what they want before opening a PR.
