### ISSUE TITLE
[deploy-sourcegraph] redis-cache deployment upgrade from 2.x to 3.2 had incorrect perms on data dir

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#3254] opened 2019-04-05 15:13 UTC
We just had a customer call were they are upgrading from 2.x to 3.2. redis-cache was broken since /redis-data directory was owned by root, but the redis process was running as redis.

cc @slimsag or @ggilmore  I think you did some changes around the user we use in containers?

**Comment by slimsag** [comment] 2019-04-05 18:06
This sounds basically the same as https://github.com/sourcegraph/sourcegraph/issues/1761. That change has not been re-merged, but it looks like @ggilmore didn't revert the same change for redis-_cache_, so that is probably the issue here. I think what happened is:

1. Before my change, we would run the container as root (via k8s security setting). It would mingle some files as `root`, then would downgrade to a plain `redis` user and operate.
2. After my change https://github.com/sourcegraph/infrastructure/blob/master/docker-images/redis-cache/Dockerfile#L3, we explicitly run always as the user `redis` -- but this broke old deployments where the AOF is owned by root because I guess the redis container does some mingling on that file before downgrading its (previously root) user to `redis`.
3. @ggilmore reverted my change to `redis-store`, but not `redis-cache`. So now we see the same bug in redis-cache deployments.

tbh this is quite a mess, because it is unclear what redis image is actually deployed. I think the right thing to do here is undo the revert @ggilmore did for https://github.com/sourcegraph/sourcegraph/issues/1786 then resolve whatever the issue is in our redis-cache and redis-store dockerfiles in https://github.com/sourcegraph/infrastructure/tree/master/docker-images -- because deploy-sourcegraph is otherwise relying on an image that we can't build

**Comment by ggilmore** [comment] 2019-04-09 00:24
Reverting https://github.com/sourcegraph/deploy-sourcegraph/pull/158 still creates a broken cluster that has `redis-store` in `CrashLoopBackoff`. 

I think we need just proceed by looking into the underlying issue with the Dockerfiles.

**Comment by slimsag** [comment] 2019-04-09 02:22
Oh, wait, so https://github.com/sourcegraph/sourcegraph/issues/1761 is still an issue too then?

**Comment by slimsag** [comment] 2019-04-09 02:24
In that case, let's merge my changes back in (because without those changes we don't have a way to ship a new redis-store or redis-cache image, it was broken for like ~6 months before my changes even landed, nobody noticed because we don't update those images often).

After that, we can just investigate whatever is going on in the base image.

Should me or you own this @ggilmore ? (I won't have time to investigate for a bit)

**Comment by ggilmore** [comment] 2019-04-16 17:48
A possible fix is ready (along with more questions) in https://github.com/sourcegraph/deploy-sourcegraph/pull/216

**Closed** 2019-04-25 19:25 UTC
Labels: deploy-sourcegraph, team/core-services
