### ISSUE TITLE
insights: escape whitespace for aggregation drilldown queries

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#40707] opened 2022-08-22 22:25 UTC
When author fields have whitespace they will break the semantic of a drilldown query unless whitespace is escaped. For example:

Aggregation query:
`type:commit insight`

Returning drilldown:
`type:commit author:Santa Claus insight`

In reality we need to generate:
`type:commit author:Santa\ Claus insight` or `type:commit author:Santa\sClaus insight`

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by felixfbecker** [comment] 2022-08-23 19:54
I think simple quoting works too: `author:"Santa Claus"`. Quotes are not valid as git names or emails so that should be easy.

**Comment by coury-clark** [comment] 2022-08-23 21:36
@felixfbecker I ended up just leaning into the fact its a regexp pattern and [wrapped it in a group](https://github.com/sourcegraph/sourcegraph/pull/40757)

**Comment by coury-clark** [comment] 2022-08-23 21:42
To be more specific, I think with quotes it will still overmatch as a regexp, for example:
`repo:^github\.com/sourcegraph/sourcegraph$ type:commit author:"coury"` will still match `coury-clark`

**Comment by felixfbecker** [comment] 2022-08-24 16:45
I'll close this for now since the issue is fixed, using quotes is more of an aesthetic follow-up

**Comment by leonore** [comment] 2022-08-25 14:40
closed by #40757

**Closed by leonore** 2022-08-25 14:40 UTC
Labels: team/code-insights, backend, insights-search-aggregation-4.0
