### ISSUE TITLE
Cody Fixups comments, blathers about its changes

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/sourcegraph#50955] opened 2023-04-21 01:41 UTC
Cody-vscode 0.0.7

Feedback from @steveyegge and @malomarrec about Cody Fixups infelicities:

> Fixups prompting needs to tell it not to emit an explanation of what changes it made — I still see that sometimes (and they are occasionally very long).

> Instead of seeing  the Cody blinking terminal prompt (which I find confusing in general, kinda tells me I need to be writing stuff whereas it should be clearer that it's a loading state), show a "Cody is improving your selected code inline" ... Replace the Here is my attempt at rewriting the selected code: by, "done", or "code improved!". The current message makes me expect something in the chat UI, and when nothing comes it just feels broken

#### Steps to reproduce:

1. VScode, select a bunch of code, Ask Cody: Fixup ...

#### Expected behavior:

Fix the darn code.

#### Actual behavior:

Cody provides commentary along the lines of "here's the fix" and then there's a long wait while the LLM output is buffered before being placed in the editor.

**Comment by mrnugget** [comment] 2023-04-25 10:06
Duplicate of #50914

**Closed by mrnugget** 2023-04-25 10:06 UTC
Labels: cody, cody/vscode
