### ISSUE TITLE
Slow search when regexp is enabled, fast when not

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14351] opened 2020-10-01 18:24 UTC
https://sourcegraph.com/search?q=config+override&patternType=regexp

https://sourcegraph.com/-/debug/jaeger/trace/235792550f91f829

Takes ~20 sec. If you turn regexp off, it is almost instant.

![image](https://user-images.githubusercontent.com/1976/94848274-a3bfb000-03d8-11eb-916c-455ec431be06.png)

**Comment by lguychard** [comment] 2020-10-02 15:15
@keegancsmith @stefanhengl this is because #14093 only impacts literal search right? And in that sense the fast result in literal search is an improvement, but the slow result in regex search is not a regression?

**Comment by keegancsmith** [comment] 2020-10-05 06:48
This is an example of the kind of query that zoekt can be very slow at. In regexp mode we replace spaces with `.*`. This means the actual query being run is `(config)(?-s:.)*?(override)`. The way zoekt works is it interprets `config` and `override` independently, then merges the results. So the reason literal search is so quick very few documents contain `config override`. However, lots of documents contain `config` and `override`, just not on the same line. I don't think we look at all documents that contain config OR override, but that might also be the case.

This is the sort of thing I originally envisioned working on when we set out on this perf project (ie core zoekt work). However, there is lower hanging fruit which affects all types of queries which we are doing first on the way to 500k. So we are just focussed on literal queries. I'm not sure how to prioritize work like this, but this seems like a very reasonable query to run and it just doesn't work.  So maybe we should be spending some time on improving regex queries like this before scaling the indexed set to be larger. WDYT @sqs / @stefanhengl?

**Comment by sqs** [comment] 2020-10-06 03:20
I don't know, it's tough to prioritize precisely. I would guess that this slowness is only likely to occur on Sourcegraph.com and not on most customer instances (which have less code), so making 500k repos work smoothly in general is higher priority.

**Comment by stefanhengl** [comment] 2020-12-18 13:51
@keegancsmith and I worked on a fix for this issue. See https://github.com/sourcegraph/zoekt/commit/9b867fb6188e91f3b2cd04921acc919f648a4152. As described in the commit, performance has improved considerably. As of today, the same query `config override` run in around 2s.

https://sourcegraph.com/search?q=config+override&patternType=regexp
<img width="2146" alt="image" src="https://user-images.githubusercontent.com/26413131/102621738-4e29b280-4140-11eb-9190-7ffa6671fb54.png">

**Closed by stefanhengl** 2020-12-18 13:51 UTC
Labels: bug, team/search

**Comment by sqs** [comment] 2020-12-18 14:00
Awesome, thank you!
