### ISSUE TITLE
Model already exists error

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#3511] opened 2019-04-19 16:09 UTC
Go to https://github.com/sourcegraph/sourcegraph/pull/2937/files and switch back between discussions and files changed.
No codeintel and error in console:

```
chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1 Uncaught Error: model already exists with URI git://github.com/sourcegraph/sourcegraph?6da6418d89a81c7056f25497f7e95534fb67f66a#client/browser/src/libs/code_intelligence/code_intelligence.tsx
    at Object.addModel (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:17)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:74)
    at t.__tryOrUnsub (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t._next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:74)
    at t.next (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at e.observe (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t.dispatch (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t._execute (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t.execute (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at t.flush (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
    at chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1
    at u (chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/js/inject.bundle.js:1)
```

Potentially related to @sqs refactor?

**Comment by lguychard** [comment] 2019-04-19 16:37
Dupe of https://github.com/sourcegraph/sourcegraph/issues/3458

**Closed by lguychard** 2019-04-19 16:37 UTC
Labels: browser-extension, bug
