### ISSUE TITLE
insights: the insightViews resolver chain is really slow

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#42128] opened 2022-09-26 23:57 UTC
While load testing a new storage format I noticed there is something consuming a huge amount of time that _isn't_ loading the data out of the database. It seems roughly ~650 ms can be attributed to this non-data loading latency. Here is an example:

25000 unique timeseries (100 repos * 250 captures) over 12 points = 300,000 samples

1. Old format: ~5000ms, 4100ms to fetch and aggregate
2. New format: ~900ms, 210ms to fetch and aggregate

What this means is we can load 300k rows and aggregate in 210ms, but we are still spending nearly **3x** the time to fill out the remaining resolvers. Worth a note this was for an insight with dynamic series (capture groups)

/cc @joelkw @felixfbecker @vovakulikov

**Comment by coury-clark** [comment] 2022-09-27 00:30
My guess is this is the culprit: https://sourcegraph.sourcegraph.com/search?q=context%3Aglobal+NewStatusResolver&patternType=standard&groupBy=repo

**Comment by coury-clark** [comment] 2022-10-12 22:03
p2

**Comment by coury-clark** [comment] 2022-10-13 16:43
timebox to 2d

**Comment by coury-clark** [comment] 2022-10-26 22:42
possibly related to https://github.com/sourcegraph/sourcegraph/issues/43498

**Comment by chwarwick** [comment] 2022-12-07 18:30
@leonore Was thinking about this some today as I saw things slow but was then unable to reproduce.  In a way it almost felt like a cold start.   I wonder if it's possible with lower usage all the connections timeout and are closed and then when a new request comes with a rush of new sql it has to pay the cost of reestablishing a number of them.

**Comment by leonore** [comment] 2022-12-08 10:13
> I wonder if it's possible with lower usage all the connections timeout and are closed and then when a new request comes with a rush of new sql it has to pay the cost of reestablishing a number of them.

I'm not sure I understand the first part of what you're describing. what situation would "lower usage" cover?

**Comment by leonore** [comment] 2022-12-08 10:13
cc @chwarwick

**Comment by leonore** [comment] 2022-12-08 11:52
two things I've been able to find with the tracing:
1. for some reason `GetUnauthorizedRepoIDs` spends a couple ms in the sql query, but the whole function consistently takes ~300ms.
2. this doesn't explain the slowness we see in some insights, where we hit thousands of ms graphql calls and the traces do not account for this time. however this is not easily reproduceable. this was an insight affected by it: https://sourcegraph.sourcegraph.com/insights/insight/aW5zaWdodF92aWV3OiIySVlLT2VUWVdteG40SjhmZE1EWDZ6akpiMjci?trace=1 

I will investigate 1. a little bit further to determine which part of the function is slow, as this amount of time is consistent across insights. search insights will be slower there because we do the cache once per series. maybe we could cache it? I'm not sure there since it involves touchy perms.

For 2. I don't believe there is much to be done immediately pending another spike.

slow trace:
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/29406849/206439307-e1af0130-41e3-4c6f-922d-3eabd43d63ce.png">

faster trace (same insight as above): 
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/29406849/206439403-6fd479e1-3df1-4303-8ac1-3c0d40b9c4a8.png">

another example trace for search insight (i.e. multiple repo id calls):
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/29406849/206439545-0b30a43c-84ea-4394-bbad-2af5f2b221bb.png">

**Comment by chwarwick** [comment] 2022-12-08 16:35
> > I wonder if it's possible with lower usage all the connections timeout and are closed and then when a new request comes with a rush of new sql it has to pay the cost of reestablishing a number of them.
> 
> I'm not sure I understand the first part of what you're describing. what situation would "lower usage" cover?

@leonore  as in if no one had hit any of the insights pages recently.  The default Idle Connection time is 1 min, so if there wasn't any activity to the insightsdb those connections could get closed and then at next insights related page opening a bunch of connections would need to get reestablished.

**Comment by leonore** [comment] 2022-12-09 10:39
so what's taking the consistent amount of time is the scanning the number of rows returned by the command. this is for c. 23,000 rows. (time on left is after query and time on right is after scan) 

<img width="691" alt="Screenshot 2022-12-09 at 10 30 45" src="https://user-images.githubusercontent.com/29406849/206682263-e0baab9d-c396-4081-8c95-1933f851215c.png">

immediately there is not much that can be done about this, as we're not going to change our model for insight permissions in the near future. caching this information wouldn't work as we'd need to record if any user permissions change and need confidence we don't hit cache errors (we also can't have transactionality when the permissions are updated in another service). 

closing this in favour of #45472

**Closed by leonore** 2022-12-09 10:39 UTC
Labels: api, spike, team/code-insights, backend, performance, strategic
