### ISSUE TITLE
Only "Find references" is visible in hover tooltip for Go code intel on GitHub PR split diff

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1770] opened 2019-01-10 17:18 UTC
![image](https://user-images.githubusercontent.com/754768/50985040-352a1880-14b8-11e9-9bde-35935dbf46d1.png)

Error in the JS console
```
Uncaught TypeError: Cannot read property 'title' of null
    at o (inject.bundle.js:1)
    at t.Object.pipe.e [as project] (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at t._next (inject.bundle.js:1)
    at t.next (inject.bundle.js:1)
    at e._subscribe (inject.bundle.js:1)
    at e._trySubscribe (inject.bundle.js:1)
    at e.subscribe (inject.bundle.js:1)
    at e.call (inject.bundle.js:1)
```

@chrismwendt @lguychard Can one of you investigate?

**Comment by sqs** [comment] 2019-01-10 18:03
This is a dupe of another issue filed on me already, will find issue number when I’m at my computer

**Comment by sqs** [comment] 2019-01-11 04:58
Thought it was a dupe of #1334, maybe not. Reopening until I determine for sure.

**Comment by sqs** [comment] 2019-01-11 05:49
It is not a dupe of #1334. It is an independent issue. Reassigning to @chrismwendt 	and @lguychard.

**Comment by chrismwendt** [comment] 2019-01-11 05:57
I think this is another off-by-one problem, potentially caused by GitHub changing their DOM. I fixed the unified view in https://github.com/sourcegraph/sourcegraph/pull/1644 and a similar fix probably needs to be made for split view. Assigning to myself.

**Closed** 2019-01-12 20:08 UTC
Labels: release-blocker
