### ISSUE TITLE
Searching from main search page prepends unrelated string to query

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#11428] opened 2020-06-11 09:39 UTC
#### Steps to reproduce:

1. visit sourcegraph.com/search
2. type any query (eg. `repo:github.com/sourcegraph/sourcegraph`) in the search field
3. submit query

#### Expected behavior:

Search is performed with the query you typed in.

#### Actual behavior:

`,function () { [native code] }` is prepended to the query

![image](https://user-images.githubusercontent.com/1741180/84370153-29281600-abd8-11ea-8ad0-2eb18525f491.png)

**Comment by eseliger** [comment] 2020-06-11 09:43
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/11406

**Closed** 2020-06-11 09:44 UTC
Labels: bug
