### ISSUE TITLE
Querying repository by name with github.com prefix always returns empty string for name

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5125] opened 2019-08-07 15:08 UTC
Run this GraphQL query on k8s.sgdev.org:

```graphql
query {
  repository(name:"github.com/asdasd") {
    name
  }
}
```

[API console link](https://k8s.sgdev.org/api/console#%7B%22query%22%3A%22%23%20Type%20queries%20here%2C%20with%20completion%2C%20validation%2C%20and%20hovers.%5Cn%23%5Cn%23%20Here's%20an%20example%20query%20to%20get%20you%20started%3A%5Cn%5Cnquery%20%7B%5Cn%20%20repository(name%3A%5C%22github.com%2Fasdasd%5C%22)%20%7B%5Cn%20%20%20%20name%5Cn%20%20%7D%5Cn%7D%5Cn%22%7D)

You can use any repo name, as long as it starts with `github.com/` (even just that string).

it returns this result:

```json
{
  "data": {
    "repository": {
      "name": ""
    }
  }
}
```

An empty string should never be returned. A repo with an empty name obviously doesn't exist.

Interestingly, when you add other fields, you notice you can query for its `id`, but if you add e.g. `createdAt` or `description` those fields (not the `repository` field itself) fail with a "repo not found" error:

```graphql
query {
  repository(name:"github.com/asdasd") {
    name
    id
    createdAt
    description
  }
}
```

Result:

```json
{
  "data": {
    "repository": {
      "name": "",
      "id": "UmVwb3NpdG9yeTow",
      "createdAt": "2019-08-07T15:04:24Z",
      "description": null
    }
  },
  "errors": [
    {
      "message": "repo not found",
      "path": [
        "repository",
        "description"
      ]
    }
  ]
}
```

Note that the browser extension / native integrations do this query and interprets this result as the repo existing, which breaks code intelligence.

I cannot reproduce this with sourcegraph.com, so I suspect it only happens with certain external service configurations.

**Comment by keegancsmith** [comment] 2019-08-08 08:31
Added to my TODO list to investigate. To help understand, this issue leads to the browser extension breaking on some instances if the repo is not cloned? The instance needs to be configured in a certain way, and k8s.sgdev is an example?

**Comment by felixfbecker** [comment] 2019-08-08 13:45
It appears so, but it happens for any repo that does not exist, not just for repos that exist but are not yet cloned. Note this is not an edge case, because in Phabricator staging repos are not generally available on the Sourcegraph instance, and the browser extension needs to check whether they are first.
"The instance needs to be configured in a certain way" is a guess.

**Comment by felixfbecker** [comment] 2019-08-17 21:31
This reliably causes the Phabricator e2e test to fail, running against 
 umami.sgdev.org.

![image](https://user-images.githubusercontent.com/10532611/63217435-d4964480-c146-11e9-92b3-b3b4f525f2c5.png)

![image](https://user-images.githubusercontent.com/10532611/63217431-ccd6a000-c146-11e9-8798-2b0d24685cab.png)

Interestingly reloading the page makes it work, so it maybe it is some error that only happens on the first-ever request after a newly configured external service?

**Comment by mrnugget** [comment] 2019-08-19 08:40
Is this really a release-blocker? Because since we didn't change anything in the code involved here in the past release, I'm pretty sure this is not a regression from one release to another, but rather a "normal bug"

**Comment by felixfbecker** [comment] 2019-08-19 09:04
Well I am unable to test the browser extension on umami.sgdev.org with this bug, so while it may not be a regression, it blocks testing other items (that may be broken in other ways)

**Comment by keegancsmith** [comment] 2019-08-19 17:49
@felixfbecker I looked into this, and this is due to our support for the `RedirectURL` field. How is that used in the browser extension currently? There are likely other bugs going on here.

We should probably change what we are doing here and return an error instead of using the redirecturl field. WDYT? Also we do currently read this field in the webapp.

**Comment by felixfbecker** [comment] 2019-08-19 17:55
I am not familiar with that field - can you explain how it works? Why would it cause an empty string to be returned? Note how once you query additional fields, you get errors

**Comment by keegancsmith** [comment] 2019-08-20 07:35
> I am not familiar with that field - can you explain how it works?

It's a hack someone added. It is a field that is populated when the repo wasn't found, but it might be found at `redirectURL`. The only time we use this is for redirecting repos that are missing on a customers instance to sourcegraph.com. We don't validate the repo exists, we just check if the repo is missing locally and its name starts with `github.com/`. So if you ask for repo `github.com/a`, `redirectURL` will be `https://sourcegraph.com/github.com/a`. It is a bad hack.

> Why would it cause an empty string to be returned?

It is a bad hack, so doesn't cause all the other fields to fail.

> Note how once you query additional fields, you get errors.

This is a change of behaviour from 3.5. The extra fields cause us to try hydrate extra info from the database.


We really need to do something better here. What do you expect the ideal behaviour for the GraphQL API to be? Then lets implement that. As it stands this isn't a regression and has been existing behaviour for a long time. The error on additional fields is new, but either way this behavious has been this broken way pre sourcegraph 3.0.

**Comment by felixfbecker** [comment] 2019-08-20 08:37
We should definitely not return an empty string. If we can't fill in any data except `redirectURL`, then it feels wrong to return a repository resolver at all. Perhaps the cleanest solution would be a union type `Redirect | Repository`, but I believe that would be breaking. If we returned an error for repo not found, we could add it as a property on the error, but I believe we just return `null`.

The only way I see is exposing the redirect as another resolver adjacent to `repository`, so clients have to query it explicitly. But I don't even know which clients use the redirects.

Do you have any other ideas?

**Comment by keegancsmith** [comment] 2019-08-20 10:38
There seems to be only one place we query it: https://sourcegraph.com/search?q=r:github.com/sourcegraph/sourcegraph%24+%5Cbredirecturl%5Cb+f:tsx%24 

https://github.com/sourcegraph/sourcegraph/blob/eb3429fe51493728748178443e3a3fe5fcdb89c8/web/src/repo/backend.tsx#L20-L58

If you look at the implementation we explicitly handle the field being present and convert it into an error in JS land. This is the only known use of it that I know of, so lets just make this better. I'm not great at JS, could you open a PR which just implements that javascript change for that that you think is correct, then I'll make the backend conform to it.

**Comment by keegancsmith** [comment] 2019-08-22 08:42
@felixfbecker ping ^^

**Comment by tsenart** [comment] 2019-09-14 09:20
Moving this to Backlog since there's little chance it'll make it to 3.8 in time and it doesn't seem to be a release blocking bug.

**Comment by unknwon** [comment] 2020-01-16 18:55
Hmm, could someone conclude what's the expected behavior here? Should the following query just return an "repo not found" error instead of empty string?

```graphql
query {
  repository(name:"github.com/asdf") {
    name
  }
}
```

**Comment by tsenart** [comment] 2020-01-16 19:38
@unknwon: Chat with @felixfbecker 1:1 if he doesn't see this and have him explain what the desired behaviour is.

**Comment by felixfbecker** [comment] 2020-01-16 19:48
It should return the same response as when querying for `name: "aslkdjaslkdjasiodjasd"` :)

```graphql

query {
  repository(name:"sdfsdfsdfsdfsdfsdf") {
    name
  }
}
```

```json
{
  "data": {
    "repository": null
  }
}
```

**Comment by unknwon** [comment] 2020-01-18 14:34
Thanks @felixfbecker!

> If we can't fill in any data except `redirectURL`, then it feels wrong to return a repository resolver at all. Perhaps the cleanest solution would be a union type `Redirect | Repository`, but I believe that would be breaking.

Given your suggested solution and @keegancsmith's finding (https://github.com/sourcegraph/sourcegraph/issues/5125#issuecomment-522957105) that we only have one place in web app rely on the `redirectURL`, I prefer we should implement this, WDYT?

**Comment by felixfbecker** [comment] 2020-01-21 14:55
Apologies, it's been a while since we discussed this and I hadn't re-read the entire conversation again. I think my comment in https://github.com/sourcegraph/sourcegraph/issues/5125#issuecomment-522914757 still describes my preference:

> If we can't fill in any data except redirectURL, then it feels wrong to return a repository resolver at all. Perhaps the cleanest solution would be a union type `Redirect | Repository`, but I believe that would be breaking. If we returned an error for repo not found, we could add it as a property on the error, but I believe we just return null.
> 
> The only way I see is exposing the redirect as another resolver adjacent to repository, so clients have to query it explicitly. But I don't even know which clients use the redirects.

If any customers use the GraphQL API at all, they likely use the `repository` field. So we can't change its return type to a union, or make it return an error in a not found case when we didn't before.
The current behaviour of the `repository` field is clearly broken and unlikely to be relied upon though.

So the best we can do imo is to make the `repository` field return `null` even when a redirect exists, but add another field `redirectableRepository(name: String!): Redirect | Repository`. Naming up for debate, could also be `federatedRepository`, `repositoryRedirect`, ...

Does this give you enough info to unblock you?

**Comment by unknwon** [comment] 2020-01-21 15:09
@felixfbecker Thanks, SGTM.

**Comment by unknwon** [comment] 2020-02-03 16:53
The behavior to return null or not is actually controlled by [the site configuration `"disablePublicRepoRedirects"`](https://docs.sourcegraph.com/admin/config/site_config#disablePublicRepoRedirects). By default it is `false` (as on k8s.sgdev.org), which returns what's been reported in this issue (empty string for "name").

The question is, once we have a separate GraphQL query `repositoryRedirect`, is this config option still necessary? Should we remove it? cc @tsenart @nicksnyder

**Comment by felixfbecker** [comment] 2020-02-03 16:54
I think we still want it because the web app will query for redirects, but needs to know whether it should follow them or not. It means though that we need to add that setting to the public site config in `JSContext`.

**Closed** 2020-02-04 17:40 UTC
Labels: bug, estimate/1.5d, planned/3.13, team/core-services
