### ISSUE TITLE
Handle GitHub repositoryQuery that has more than 1000 results

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2562] opened 2019-03-04 19:29 UTC
GitHub's Search API will return at most 1000 results. This issue tracks discussion on how to solve this as well as the implementation of the solution. This is a blocker of some broader work we are doing on repository syncing https://github.com/sourcegraph/sourcegraph/issues/2025

**Comment by beyang** [comment] 2019-03-04 19:29
@felixfbecker any ideas here?

**Comment by ijsnow** [comment] 2019-03-04 23:04
The problem is that the repository's mirror isn't always there. I suspect this has to do with the customer's mirroring system in between GHE and Sourcegraph

**Comment by sqs** [comment] 2019-03-06 07:46
The customer reported that the problem (from the logs) is that GitHub Enterprise only returns the first 1000 search results for a repositoryQuery like `org:myorgname` if `myorgname` has more than 1000 repositories visible to the access token's user:

```
422: Only the first 1000 search results are available
```

@keegancsmith 	I believe you brought this up as a possible problem with repositoryQuery. Do you have any ideas for a workaround? My ideas are as follows (only the first 2 are necessary to solve customer problems, the rest would just be future possible solutions in case customers in the future need them):

1. Display errors like this one to the site admin in the UI.
1. Special-case repositoryQuerys of the form `org:FOO` to just use the [List organization repositories API](https://developer.github.com/v3/repos/#list-organization-repositories), which is not subject to the 1000-result limit.
1. For all other repositoryQuerys that have more than 1000 results, at sync time, split them into multiple queries that have terms like [`created:DATE`](https://help.github.com/en/articles/searching-for-repositories#search-by-when-a-repository-was-created-or-last-updated) appended to split the search space up until it's split up into sets of <1000.
1. The only repositoryQuerys this would NOT work for (without additional trickiness) AFAICT is repositoryQuerys that themselves contain a `created:` term. Those are probably quite rare, and the user can do manual workarounds in that case, so it's fine to just show the HTTP 422 error from GH to the site admin.

**Comment by keegancsmith** [comment] 2019-03-06 08:38
Alternatively we disallow queries with a `sort:`. Then we can always sort by created + paginate by created if we hit this issue. Otherwise we always sort by updated-at desc since we generally like to clone repos by the most recent first.

Another thing to note in the new syncer that returning full result sets is a requirement. Alternatively we could operate in a degraded mode where we never delete repos (but still detect new / renames if returned in search). Additionally, I need to confirm we haven't regressed on the order we clone repos in the new syncer. cc @tsenart

**Comment by tsenart** [comment] 2019-03-06 12:00
> Otherwise we always sort by updated-at desc since we generally like to clone repos by the most recent first.

How would we ensure there's a stable order between contiguous sub-queries?

**Comment by tsenart** [comment] 2019-03-06 12:06
Just for the record, can we re-iterate what validated use-cases we have that require us to rely on the search API instead of just listing all repos via the normal API and filtering on our side?

**Comment by sqs** [comment] 2019-03-06 20:02
@tsenart The validated use case are that customers want to be able to add GitHub repositories to their Sourcegraph instance that match the following kinds of descriptions:

- all GitHub repositories in one or more organizations
  - excluding archived repositories (in most cases)
  - including archived repositories (in some cases)
- a specific set of named GitHub repositories
- all GitHub repositories whose name contains a certain string (usually this is an intermediate step while someone is trying out Sourcegraph, when they want to add a bunch of repositories but not all of them, so they pick a common string like  "go" that appears in many of their repository names)
- all repositories affiliated with the token's user
- all repositories starred by the token's user
- all repositories visible to the token's user (GitHub Enterprise only, as this would include all public repositories on GitHub.com)
- some combination of the above
- any of the above, MINUS certain specific repositories (such as those that are  security-sensitive or very large)

These do not *require* us to use the GitHub search API, but it seemed like allowing users to specify repository queries was the easiest way to capture their intent. There are some alternatives that do not seem workable to me:

- allow users to configure their repository set using named config fields like `organizations`, `excludeRepositories`, `visibleToTokenUser`, etc. -- I think the precedence and combination logic (AND or OR?) of these would be confusing, and it would be hard for users to preview the set of repositories included on GitHub
- add our own custom query parser that lets us post-filter the result set without hitting the GitHub search API, or add a custom query parser for GitHub search queries -- seems confusing for users if we invent our own query syntax, and seems harder to implement and keep consistent if we mimic GitHub's search API
- require users to create a bot user that has precise access to the set of repositories they want -- this requires them to manage that set manually (in some cases), to create a new bot user (which may require GHE admin approval, which would slow down adoption), and does not work for making open-source repositories on GitHub.com accessible

**Comment by keegancsmith** [comment] 2019-03-07 06:44
btw we will have to disallow created in the search query as well, since github doesn't seem to support having created more than once. For example check this query out. I'd suspect it to range all repos to the dates in the first created, but it seems to only take into account the 2nd created (or it ors the two terms). Additionally I can't get it to sort by created in a descending order. But we could implement this via sorting in asc order only.

https://github.com/search?q=created%3A2019-03-01..2019-03-02+created%3A%3C2019-03-02T10%3A00+sort%3Acreated&type=Repositories

**Comment by keegancsmith** [comment] 2019-03-11 13:12
Note: This is not only an issue for GHE, Github.com has the same limitation. Requesting page 35 or higher will always result in this error message. This also is a blocker for https://github.com/sourcegraph/sourcegraph/issues/2025

**Comment by keegancsmith** [comment] 2019-03-11 13:24
Alternative solution: Don't use GitHub search due to this limitation / disallow it if we run into this many results. Add support for listing org repos.

**Comment by keegancsmith** [comment] 2019-03-11 20:44
This issue was a bit confusing since the original title and current description are a different problem to the current title and issue comments. As such I have filed https://github.com/sourcegraph/sourcegraph/issues/2677 to track the more important issue. This issue will now just be about repositoryQuery limitations and is tracked to ship in 3.3. (with the rest of the work we are doing on the new repository syncer).

**Comment by keegancsmith** [comment] 2019-03-28 13:12
### Proposal

A new GitHub configuration field `query` which has a Sourcegraph repository search query. We list affiliated repositories a token has access to and only include those the Sourcegraph repository search query would return.

#### Pros

- Consistent syntax across our product.
- Same approach can be used for other code hosts, even those without search endpoints.

#### Cons

- Can't do search on non-affiliated repositories. EG public github repositories. The admin would have to list those under `repos` field. Alternatively we keep supporting repositoryQuery as an escape hatch.
- No automatic migration from repositoryQuery.

#### Plan

1. *3.3* Display error to admin if repository query returns more than 1000 results.
2. *3.3 stretch* Implement `query` for GitHub.
3. *3.3 stretch/3.4* Deprecate repositoryQuery.
4. *3.4/3.5* Remove repositoryQuery

cc @sqs, @ijt

**Comment by sqs** [comment] 2019-03-28 15:51
@keegancsmith:

What about, for now, just doing:

> 3.3 Display error to admin if repository query returns more than 1000 results and link to workaround in docs. The workaround is to add multiple `repositoryQuery` entries with disjoint `created:A..B` terms in the query.
>
> 3.4/3.5 (if customers request it, or complain about the pain of the workaround above) Handle the most common case `repositoryQuery` case of `org:foo` specially by implementing it using the "organization repositories" GH endpoint (which is not subject to the 1000-repository limit) instead of the "repository search" GH endpoint.

The assumption is that a small percentage of customers have 1000+ repositories, and those who do will be able to comprehend the workaround.

---

Either way, for 3.3, I think you should just detect the 1000-limit-error-case and document the workaround.  No need to start on `query` or make it a stretch for 3.3. I think we should chat (sometime in the next few weeks) about the longer-term needs (6-month-plus), which would affect whether `query` is right. It may be, but I personally am not sure. For example, we may want to make repository permissions enabled by default, and make the repository universe configurable by users (not just site admins), so that the site admin would not need to even specify the set of repositories.

One additional wrench here is that I heard from a GitHubber on Monday that GitHub plans to remove or seriously break personal access tokens and force integrations like Sourcegraph to use the GitHub App model. In that model, the GitHub admin would choose the repo selection on GitHub, not on Sourcegraph. For example, here is how we select which repos to use with Codecov (which is on our org's GitHub settings page on GitHub.com):

![image](https://user-images.githubusercontent.com/1976/55172055-ab90fb00-5136-11e9-9693-75f67f78875f.png)

**Comment by keegancsmith** [comment] 2019-03-29 07:07
> Either way, for 3.3, I think you should just detect the 1000-limit-error-case and document the workaround.

Agreed. Given we may have some more discussion around the proper solution to this, it makes sense to leave it for another milestone.

> One additional wrench here is that I heard from a GitHubber on Monday that GitHub plans to remove or seriously break personal access tokens and force integrations like Sourcegraph to use the GitHub App model.

The GitHub App model would suit our new syncer well. It is extra friction for the admin. However, the page presented for repo selection by GitHub is pretty intuitive and would work well for our customers.

**Comment by keegancsmith** [comment] 2019-04-15 13:04
So will defer doing the nicer solution until a later date. For now here is a PR which improves the error message to include instructions / suggestions when a repositoryQuery returns too many results https://github.com/sourcegraph/sourcegraph/pull/3402

**Comment by tsenart** [comment] 2020-02-21 10:56
This is a won't fix, since there's no really good solution in sight, and customers have been fine using the documented work-around for pagination.

**Comment by tsenart** [comment] 2021-07-13 12:50
Re-opening this issue so that I can close it soon with the automated search query refinement solution.

**Closed** 2021-07-20 19:11 UTC
Labels: bug, team/core-application
