### ISSUE TITLE
Notebooks: Getting started improvements 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#34384] opened 2022-04-23 00:28 UTC
No estimate or timeline at present, just tracking for now. 

Per feedback from design team and others: 
- (not strictly limited to getting started) Condense "Create" "Import" and "Toggle Notepad" buttons into two ("Create" and "Actions") 
- (not strictly limited to getting started) Change capitalization of tabs to title case - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480)
- Re-record main video or create animation due to current video being small 
- Add "Create Notebook" CTA to main card, similar to Code Insights getting started - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480) 
- Edit some of the copy (e.g. tagline in top card) - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480)
- Interactive demo? 
- Change bottom CTAs to 1 column wide with empty column between them (or find a third CTA) - Addressed in [#33480](https://github.com/sourcegraph/sourcegraph/issues/34480)
- Add link to enable notepad to bottom CTAs

**Comment by sourcegraph-bot-2** [comment] 2022-04-23 00:28
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment] 2024-03-04 22:50
Closing since I cannot reproduce.

**Closed by camdencheek** 2024-03-04 22:50 UTC
Labels: needs-design, team/search-product, team/code-search, imported
