### ISSUE TITLE
Command palette doesn't close when menu dropdown opens

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#1843] opened 2019-01-13 06:09 UTC
![screen recording 2019-01-12 at 10 08 pm](https://user-images.githubusercontent.com/754768/51082158-a0413e00-16b6-11e9-80a1-4fba955691af.gif)

**Comment by sqs** [comment] 2019-01-14 16:08
For posterity and cross-linking: Dupe of #1736

**Closed** 2019-01-14 16:10 UTC
Labels: extensions
