### ISSUE TITLE
The last data point is not shown on Insight, if it is 0

### ISSUE THREAD

**Issue by c69-addepar** [sourcegraph/sourcegraph#44736] opened 2022-11-22 16:23 UTC
#### Steps to reproduce:

1. If granularity is large enough (ie: 6 months)
2. Then the last data points are only shown in Preview, but not on the dashboard insight.

#### Expected behavior:

All data points are shown, like they do on the Preview.

![image](https://user-images.githubusercontent.com/73544321/203366674-a2c686e2-c845-4501-af47-f77cd628b49f.png)

#### Actual behavior:

<img width="319" alt="image" src="https://user-images.githubusercontent.com/73544321/203366540-83cafe00-042b-49ad-8db4-14f8c955ff21.png">

Also, notice that number of data-points on the preview is LOWER (7) than the actual insight (9).

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by c69-addepar** [comment] 2022-11-28 13:37
Turns out,this is a duplicate of known issue https://github.com/sourcegraph/sourcegraph/issues/39883

**Comment by c69-addepar** [comment] 2022-11-28 13:40
Also, https://github.com/sourcegraph/sourcegraph/issues/43496

**Comment by c69-addepar** [comment] 2022-11-28 17:12
Seems like this is fixed in https://github.com/sourcegraph/sourcegraph/pull/43166 (per [4.2.0 release notes](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#4-2-0) )

I will test once 4.2 is rolled out.

**Comment by malomarrec** [comment] 2022-12-05 11:15
Hey @Joelkw, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by leonore** [comment] 2022-12-19 11:00
hi @c69-addepar, this should have been fixed- feel free to double check this on your side again, but I'll be closing this issue. if you see any unexpected behaviour again file a new issue to let us know :)

**Closed by leonore** 2022-12-19 11:00 UTC
Labels: triage-bot/needs-triage
