### ISSUE TITLE
Basic code intel showing incorrect results in C++

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#15561] opened 2020-11-09 00:34 UTC
Repro steps:

* Go to https://sourcegraph.com/github.com/osquery/osquery@da621067f828907f37744aff8aaade8d0db6f842/-/blob/osquery/filesystem/filesystem.cpp#L54:8&tab=references
* Click `Find references` on `writeTextFile` (line 54)
* Observe basic code intel reference results highlighting `size_t` tokens:

![image](https://user-images.githubusercontent.com/1646931/98488847-3f1a2100-21e0-11eb-9b25-97f48b32e519.png)

This seems similar to an issue one of our customers is reporting on their C++ repositories.

**Comment by macraig** [comment] 2020-11-09 10:23
I got semantic results and disabled LSIF but couldn't reproduce

![Screenshot 2020-11-09 at 11 19 30](https://user-images.githubusercontent.com/1657213/98529363-ce294680-227d-11eb-95b5-f7434ad7175d.png)

**Comment by efritz** [comment] 2020-11-09 15:04
@beyang @macraig Same experience as Maria. Could not reproduce with LSIF disabled.

**Comment by efritz** [comment] 2020-11-09 15:12
Related to https://github.com/sourcegraph/sourcegraph/issues/14629.

**Comment by efritz** [comment] 2020-11-10 19:14
Fixed by https://github.com/sourcegraph/code-intel-extensions/pull/524.

**Closed by efritz** 2020-11-10 19:14 UTC
Labels: team/code-intelligence
