### ISSUE TITLE
Code Insights: [BE] Strange behaviour of insight date when drill-down filters have been applied

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#27837] opened 2021-11-17 13:30 UTC
At the moment it seems like `UpdateLineChartSearchInsight` mutation doesn't work if we provide some filters in there (see gql error in steps to reproduce section). Also after any updates (via drill-down filters or via edit page) insight becomes in processing mode. Even if we change something like title or search query color or drill-down filters. 

_Insight after any updateInsight mutation_ 
<img width="395" alt="Screenshot 2021-11-17 at 16 28 21" src="https://user-images.githubusercontent.com/18492575/142209749-b18558da-7102-48fa-a4eb-6607443b52cd.png">

**Steps to reproduce:**
1. Go to any backend insight 
2. Type some value in any field of drill-down panel form.
3. Click on save filters button 
4. See gql errors about mutation 

GQL mutation input data 
```
{
    "input": {
        "dataSeries": [
            {
                "query": "FunctionComponent",
                "options": {
                    "label": "Function component",
                    "lineColor": "var(--oc-indigo-7)"
                },
                "repositoryScope": {
                    "repositories": []
                },
                "timeScope": {
                    "stepInterval": {
                        "unit": "WEEK",
                        "value": 2
                    }
                }
            }
        ],
        "presentationOptions": {
            "title": "Add insight 1.1 Test"
        },
        "viewControls": {
            "filters": {
                "includeRepoRegex": "",
                "excludeRepoRegex": "sourcegraph"
            }
        }
    },
    "id": "aW5zaWdodF92aWV3OiJzZWFyY2hJbnNpZ2h0cy5pbnNpZ2h0LmFkZEluc2lnaHQxMVRlc3Qi"
}
```

Errored response from the BE 
```
{
    "errors": [
        {
            "message": "graphql: got nil for non-null \"InsightView\"",
            "path": [
                "updateLineChartSearchInsight",
                "view"
            ]
        }
    ],
    "data": null
}
```

**Comment by coury-clark** [comment] 2021-11-18 16:33
So it seems we have two issues:
1. This response is returning nil (for some reason the permissions are not resolving when it fetches after the update)
2. Series are getting queued for historical processing globally that shouldn't be

Based on that, I'm splitting this into another issue for 2.

**Comment by coury-clark** [comment] 2021-11-18 17:05
I suspect the error for 1) is caused by the user's orgs [not getting propagated into the insight fetch ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/resolvers/insight_view_resolvers.go?utm_product_name=GoLand&utm_product_version=GoLand#L466:63)

**Closed** 2021-11-22 20:01 UTC
Labels: bug, team/code-insights, backend, insights-settings-migration
