### ISSUE TITLE
Search query with multiple case:yes|no is silently modified

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#13958] opened 2020-09-18 20:29 UTC
Repro:

1. Type `repo:^github\.com/sourcegraph/sourcegraph$ (Github case:yes) or (organisation case:no)` into the search bar on Sourcegraph.com
1. Press <kbd>Enter</kbd>

Expected: the query remains as I typed it in, and `Github` is matched case-sensitively and `organization` is matched case-insensitively

Actual: the query changes (when I press <kbd>Enter</kbd>) to `repo:^github\.com/sourcegraph/sourcegraph$ (Github ) or (organisation case:no)`, which is surprising and means my search doesn't do what I expected

I think I know why this happens (because we pull out `case:` tokens and reflect them in the input toggles), but this is still surprising. It also makes a legit use case harder (finding typos*). BTW, I am not sure if `case:` can even be applied within a parenthetical sub-expression.

(Not high priority.)

* I know `organisation` is not a typo universally, but from the POV of US English it is. :smile:

**Comment by rvantonder** [comment] 2020-09-18 20:43
> BTW, I am not sure if case: can even be applied within a parenthetical sub-expression.

In the current state: no, this shouldn't be allowed. What you should have gotten was a "Can't process that query" notification :-). I think the reason you didn't is because the web app actually transforms the query based on the presence of `case`.

But, when https://github.com/sourcegraph/sourcegraph/issues/13126 is done, a query like `(Github case:yes) or (organisation case:no)` is totally reasonable and will behave like expected (this is a cool example by the way). Once that functionality is available, it will be inconsistent with the toggle state (the webapp parser assumes there is only one `case` in the query ever, and will change state on that). How we resolve UI state with subexpressions is a known, but open issue. I am thinking about it.

**Comment by rvantonder** [comment] 2020-09-18 20:46
> You should have gotten was a "Can't process that query" notification :-). I think the reason you didn't is because the web app actually transforms the query based on the presence of case.

Indeed, I can confirm that the backend will reject that raw query, you can see here in the [console](https://sourcegraph.test:3443/api/console#%7B%22query%22%3A%22%23%20Type%20queries%20here%2C%20with%20completion%2C%20validation%2C%20and%20hovers.%5Cn%23%5Cn%23%20Here's%20an%20example%20query%20to%20get%20you%20started%3A%5Cn%5Cnquery%20%7B%5Cn%20%20parseSearchQuery(%5Cn%20%20%20%20query%3A%20%5C%22repo%3A%5Egithub%5C%5C%5C%5C.com%2Fsourcegraph%2Fsourcegraph%24%20(Github%20case%3Ayes)%20or%20(organisation%20case%3Ano)%5C%22%2C%20%5Cn%20%20%20%20patternType%3A%20regexp%5Cn%20%20)%5Cn%7D%5Cn%22%7D). So unfortunately the webapp transforms it before it hits the backend validation. There are a couple of ways to resolve this (e.g., I implement an improved webapp parser detects invalid queries), but that doesn't fix the toggle state issue.

**Comment by rvantonder** [comment] 2020-09-18 21:08
Shower thought: @attfarhan if I add a webapp parser, it would be straightforward to just disable (gray out) the case toggle if we see more than one `case` in a subexpression. I.e., we assume "the user is doing some advanced thing and knows what they're doing, these toggle states are now undefined/disabled". Similar if we see multiple `patterntype`, we just disable the patterntype toggles.

**Comment by rvantonder** [comment] 2020-09-18 21:11
The more involved solution would be to add a UI button per search pattern with case toggles, like:

`(Github case:yes) or (organisation case:no)` is transformed to:
`Github[X] or organisation[Y]` where `[X]` is a UI case button that is toggled on, and `[X]` is a UI case button toggled off. This would probably need a bunch of changes, so just disabling the current states is a good intermediate solution.

**Comment by attfarhan** [comment] 2020-09-21 12:18
> Shower thought: @attfarhan if I add a webapp parser, it would be straightforward to just disable (gray out) the case toggle if we see more than one case in a subexpression. I.e., we assume "the user is doing some advanced thing and knows what they're doing, these toggle states are now undefined/disabled". Similar if we see multiple patterntype, we just disable the patterntype toggles.

Yeah, this sounds like a good solution for now. If we add a separate page for multi-line editing or something along those lines we could explore more advanced UI, but that seems like it could be quite far down the line.

**Comment by sqs** [comment] 2020-09-21 12:23
Given https://sourcegraph.slack.com/archives/CHEKCRWKV/p1600443200010300 I don't think we will want to add more advanced UI anytime soon, so that simple solution to disable (gray out) the case toggle seems good to me as well.

**Comment by rvantonder** [comment] 2020-09-22 00:28
Sounds good to me. I've filed https://github.com/sourcegraph/sourcegraph/issues/14016 and referenced this issue in #13216.

**Closed** 2020-12-03 07:39 UTC
Labels: bug, team/search
