### ISSUE TITLE
Streaming search dropdown is not keyboard navigable

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#18195] opened 2021-02-11 23:37 UTC
Users can tab to the dropdown and open it, but not navigate to sub-items within it to open notices or interact with the form.

**Comment by limitedmage** [comment] 2021-02-11 23:39
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/18170

**Comment by limitedmage** [comment] 2021-02-11 23:40
Sorry not a dupe, this is streaming search skipped items popup, not search contexts :)

**Comment by limitedmage** [comment] 2021-03-05 21:36
@rrhyne  can you still repro this? I just tried it and tabbing through the dropdown menu works fine for me.

**Comment by limitedmage** [comment] 2021-03-05 22:30
Tabbing works but using enter/space to expand/collapse isn't working (see https://github.com/reactstrap/reactstrap/issues/2099) I'm sending out a fix for this.

**Closed** 2021-03-09 22:11 UTC
Labels: team/search
