### ISSUE TITLE
SYMBOLS_URL should allow specifying comma seperated list

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#479] opened 2018-10-22 20:26 UTC
Identical to https://github.com/sourcegraph/sourcegraph/issues/478, except for this environment variable:

https://github.com/sourcegraph/sourcegraph/blob/3d3ffe9c2a975b4dd2e623bfa16bb29d3c6ecde9/pkg/symbols/client.go#L26

**Comment by keegancsmith** [comment] 2018-10-23 09:06
symbols and searcher use the same pkg `endpoints`. So I would just update that pkg to support your use case (would be very straightforward TBH).

Duplicate of https://github.com/sourcegraph/sourcegraph/issues/478

**Closed by keegancsmith** 2018-10-23 09:06 UTC
Labels: deployment
