### ISSUE TITLE
Renamed repository leads to invalid redirect

### ISSUE THREAD

**Issue by chmllr** [sourcegraph/sourcegraph#1966] opened 2019-01-19 12:47 UTC
- **Sourcegraph version:**  Firefox extension `v19.1.12.2016`
- **Platform information:**  macOS 10.14.2, Firefox 64.0.2 (64-bit)

#### Steps to reproduce:

1. Open `https://github.com/chmllr/notehub/blob/master/render.go` with browser extension installed.
2. Right-Click on `statuses` on line 17 and select "Find References" option.

#### Expected behavior:

Sourcegraph extension opens the URL https://sourcegraph.com/github.com/chmllr/NoteHub/-/blob/render.go#L17:2&tab=references

#### Actual behavior:

Sourcegraph extension opens the URL https://sourcegraph.com/github.com/chmllr/NoteHub#L17:2&tab=references with **no source code or references** shown.

Moreover, only on this repository the following errors in the browser console can be observed:

<img width="1717" alt="screenshot 2019-01-19 at 13 13 57" src="https://user-images.githubusercontent.com/649785/51426579-f9e0c580-1bec-11e9-98f7-e891cf42d7f8.png">

A GET `curl` call on the URL from browser logs (https://sourcegraph.com/github.com/chmllr/notehub@20daaa82cec5a93686575fd0988561906222538e/-/raw) returns however `301 Moved Permanently` and not 405. In browser, it forwards me to https://sourcegraph.com/github.com/chmllr/NoteHub with repository's old name `NoteHub` although I renamed it to `notehub` long time ago (~1/2 year or so).

I'm happy to provide more info or submit a patch if I can receive some guidance.

**Comment by keegancsmith** [comment] 2019-04-17 13:27
This will be solved by https://github.com/sourcegraph/sourcegraph/issues/3459. Will fold into that issue.

Duplicate of https://github.com/sourcegraph/sourcegraph/issues/3459

**Closed by keegancsmith** 2019-04-17 13:27 UTC
Labels: bug, team/core-services, web
