### ISSUE TITLE
Provide a preview tab for HTML/CSS code

### ISSUE THREAD

**Issue by kaushikvapiwala** [sourcegraph/sourcegraph#1102] opened 2018-11-21 20:46 UTC
#### Feature request description

It is easy to view the HTML page and edit it if there is an option provided to preview the changes.

#### Is your feature request related to a problem? If so, please describe.

It is quite frustrating to change tabs and preview code on other websites and update the repo or preview code on a local machine.

**Comment by sqs** [comment] 2018-11-21 22:10
Would solving #49 solve your problem?

**Comment by kaushikvapiwala** [comment] 2018-11-22 01:50
I be

> Would solving #49 solve your problem?

I believe that would do the job.

**Comment by sqs** [comment] 2018-11-22 03:44
Great. Closing as duplicate of #49

**Closed by sqs** 2018-11-22 03:44 UTC
Labels: feature-request, web
