### ISSUE TITLE
Hide count and date info for autodefined search contexts

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#23891] opened 2021-08-13 10:38 UTC
Users who view an auto-generated search context will see inaccurate information for the number of repositories and last updated date, e.g.:

![image](https://user-images.githubusercontent.com/6304497/129344859-46ba85af-63de-4821-8a58-7d6875edb421.png)

@novoselrok identified that this is because we don't have the information about the repositories and last updated at timestamp, and that the easiest fix is to hide this information for auto-generated search contexts for the time being.

**Comment by lguychard** [comment] 2021-08-13 10:52
Closing as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/23892

**Closed by lguychard** 2021-08-13 10:52 UTC
Labels: bug, ux, team/search-product
