### ISSUE TITLE
No code intel on deleted files in unified PR diff view of Bitbucket Server

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#4904] opened 2019-07-16 14:17 UTC
- **Sourcegraph version:** 3.6.0-rc.1

#### Steps to reproduce:

1. Go to https://bitbucket.sgdev.org/projects/SOUR/repos/vegeta/pull-requests/2/diff#dump.go
2. Double click on a symbol like `command`.

#### Expected behavior:

Tooltip shows up.

#### Actual behavior:

No tooltip shows up and Javascript errors are logged to the console.

```
Error: document not found: git://bitbucket.sgdev.org/SOUR/vegeta?0f5577eaf11a136541b8c667273b6bc5eba51a8b#dump.go
    at f.get (extensionHostWorker.bundle.js:1)
    at f.getSync (extensionHostWorker.bundle.js:1)
    at async AsyncFunction.<anonymous> (extensionHostWorker.bundle.js:1)
    at async MessagePort.<anonymous> (extensionHostWorker.bundle.js:1)

Error: document not found: git://bitbucket.sgdev.org/SOUR/vegeta?0f5577eaf11a136541b8c667273b6bc5eba51a8b#dump.go
    at f.get (extensionHostWorker.bundle.js:1)
    at f.getSync (extensionHostWorker.bundle.js:1)
    at async AsyncFunction.<anonymous> (extensionHostWorker.bundle.js:1)
    at async MessagePort.<anonymous> (extensionHostWorker.bundle.js:1)

Error: document not found: git://bitbucket.sgdev.org/SOUR/vegeta?0f5577eaf11a136541b8c667273b6bc5eba51a8b#dump.go
    at f.get (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/ce690b9d-5521-446f-8869-87860d0ace6e:1:107587)
    at f.getSync (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/ce690b9d-5521-446f-8869-87860d0ace6e:1:107715)
    at async AsyncFunction.<anonymous> (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/ce690b9d-5521-446f-8869-87860d0ace6e:1:108305)
    at async MessagePort.<anonymous> (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/ce690b9d-5521-446f-8869-87860d0ace6e:1:3098)
```

**Comment by tsenart** [comment] 2019-07-16 14:18
cc @keegancsmith

**Comment by lguychard** [comment] 2019-07-18 13:25
Not release-blocking for 3.6. This is not a regression introduced in 3.6. The fix will be released independently in the browser extension, and will make it into 3.7 for the native integration.

**Comment by lguychard** [comment] 2020-03-13 11:36
Duplicate of #4808

**Closed by lguychard** 2020-03-13 11:36 UTC
Labels: bitbucket, browser-extension, bug, code-intel
