### ISSUE TITLE
Copying code does not work

### ISSUE THREAD

**Issue by atirjavid** [sourcegraph/sourcegraph#62361] opened 2024-05-01 21:43 UTC
Copying the generated code does not work. The only thing that works is the copy button which copies the whole code. You can't CTRL+C or use mouse to copy, it doesn't work.

This is really a breaking bug. We can't get our work done, because it's just extremely difficult to almost impossible to copy any code out, unless you copy everything. 

Hopefully this can be resolved quickly.

**Comment by varungandhi-src** [comment] 2024-05-02 13:21
Could you please attach a small video recording or similar or provide more details under what situations the operation doesn't work?

**Comment by atirjavid** [comment] 2024-05-02 14:21
Attaching a video isn't going to add any additional information. You generate code. You cannot copy and paste with a mouse or keyboard. The only thing that works is the copy all code button, and that's it. This is a seriously severe bug and I being a paid customer, not being to use the software, is a little annoying I'll be honest with you.

**Comment by hashborgir** [comment] 2024-05-02 15:24
I confirm. Copying code does not work. Neither Ctrl+C, nor mouse context menu copy. The only thing that works is the copyAll button, which is not what we want most of the time.

**Comment by atirjavid** [comment] 2024-05-02 18:18
https://github.com/sourcegraph/sourcegraph/assets/36868744/c09750e8-fb54-45f1-8c42-7dc09fa14f4b

**Comment by sqs** [comment] 2024-05-02 20:11
Definitely some weirdness going on here. Thank you for reporting it.

I can repro the issue on macOS when right-clicking on selected text in the chat response and choosing Copy. The text does not paste into the chat box; nothing gets inserted.

It works if I use Cmd+C to copy on macOS, although the report above is that even Ctrl+C fails on Windows.

https://github.com/sourcegraph/sourcegraph/assets/1976/5f437584-422f-4dd9-acd7-9067658113dd

**Comment by sqs** [comment] 2024-05-02 20:22
Appears to be caused by https://github.com/microsoft/vscode/issues/141080 and affects all VS Code extensions.

For me, this is fixed in VS Code 1.89.0. @atirjavid @hashborgir can you please try upgrading to VS Code 1.89.0+ and see if that fixes the issue for you? Thank you!

**Comment by varungandhi-src** [comment] 2024-05-03 08:28
Closing this since it is due to an upstream bug

**Closed by varungandhi-src** 2024-05-03 08:28 UTC
Labels: team/code-search

**Comment by vmdamn** [comment] 2024-06-25 06:11
This is a serious issue for paid users of Cody. I am using VS Code 1.90.2 on Ubuntu and I am facing the exact same issue. And why @varungandhi-src is closing down the requests than letting devs work on it.

**Comment by varungandhi-src** [comment] 2024-06-25 06:32
I misunderstood the issue as having been fixed upstream per this comment. https://github.com/sourcegraph/sourcegraph/issues/62361#issuecomment-2091490763

Since there is already another open issue here https://github.com/sourcegraph/cody/issues/4045, I don't think it makes sense to duplicate the issue/re-open this one.

**Comment by vmdamn** [comment] 2024-06-25 07:15
Thanks @varungandhi-src . I will have the conversation at https://github.com/sourcegraph/cody/issues/4045
