### ISSUE TITLE
Campaigns show "Revision not found" error when merged changeset's branch is deleted upstream

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#10542] opened 2020-05-11 06:37 UTC
A customer reports: 

> One thing I noticed now is this kind of error message appears.
> We usually delete the branches of a pull-request on merge and it seems like this makes sourcegraph lose track if the state

The error mesage is:

```
Revision not found: <remote-bitbucket-server-url>/PROJ/proj@refs/heads/<branch-name>
```

**Comment by ryanslade** [comment] 2020-05-19 16:02
I was able to reproduce this by merging in Bitbucket and setting the checkbox to delete the branch on merge:

<img width="1140" alt="Screenshot 2020-05-19 at 18 01 12" src="https://user-images.githubusercontent.com/25610/82349801-d7d29f80-99fa-11ea-8bc2-3896bc4dd018.png">

**Comment by ryanslade** [comment] 2020-05-19 16:06
I've also just seen this on a second attempt:

<img width="1140" alt="Screenshot 2020-05-19 at 18 05 33" src="https://user-images.githubusercontent.com/25610/82350265-69daa800-99fb-11ea-9d40-ab349f027bb4.png">

**Comment by ryanslade** [comment] 2020-05-20 10:00
This is happening because we are requesting the head ref for a branch that no longer exists.

<details>
<summary>
Example request / response
</summary>

```graphql
query CampaignChangesets($campaign: ID!, $first: Int, $state: ChangesetState, $reviewState: ChangesetReviewState, $checkState: ChangesetCheckState) {
  node(id: $campaign) {
    __typename
    ... on Campaign {
      changesets(first: $first, state: $state, reviewState: $reviewState, checkState: $checkState) {
        totalCount
        nodes {
          __typename
          id
          title
          body
          state
          reviewState
          checkState
          labels {
            text
            description
            color
          }
          repository {
            id
            name
            url
          }
          externalURL {
            url
          }
          head {
            abbrevName
            target {
              oid
            }
          }
          base {
            abbrevName
            target {
              oid
            }
          }
          externalID
          createdAt
          updatedAt
          nextSyncAt
          diff {
            fileDiffs {
              diffStat {
                ...DiffStatFields
              }
            }
          }
        }
      }
    }
  }
}

fragment DiffStatFields on DiffStat {
  added
  changed
  deleted
}

```

The response:

```json
{
  "errors": [
    {
      "message": "revision not found: bitbucket.sgdev.org/SOUR/automation-testing@refs/heads/ryan-test-2^0",
      "path": [
        "node",
        "changesets",
        "nodes",
        0,
        "head"
      ]
    }
  ],
  "data": {
    "node": null
  }
}
```

</details>

There are two problems:

1. gitserver doesn't know the oid so it tries to fetch it from the remote, which is slow and in this case will never succeed.
2. We return an error since `head` on `ExternalChangeset` is non nullable in our GraphQL schema.

I think we may need to make `head` nullable and handle missing refs in the client.

For 1, we could disable `EnsureRevision` if the changeset has been been merged.

@eseliger @mrnugget What do you think?

**Comment by ryanslade** [comment] 2020-05-20 10:51
I've hacked together the above and it sort of works but we no longer have a diff to display.

**Comment by eseliger** [comment] 2020-05-20 11:59
That was the case even before, isn't it? I think that's the reason `diff` on `ExternalChangeset` is nullable 🤔 So it would not be a regression, I guess.

**Comment by mrnugget** [comment] 2020-05-20 12:13
If we can't get to the commit, I think we should do what you proposed and make `head` nullable and do the same check as here for `diff`:

https://github.com/sourcegraph/sourcegraph/blob/859cb9b101390619de39aa4f7c518263131baf17/enterprise/internal/campaigns/resolvers/changesets.go#L301-L306

But I wonder whether there isn't a way to get to the merge commit 🤔 

1. gitserver doesn't have any reference to the branch anymore? Not even in `refs/remotes/origin/<branch>`?
2. Is there a way to get to the merge commit?
3. Does the same happen for GitHub?
4. GitHub also gives us `HeadOid` (in addition to `HeadRef`) — does that help in GitHub's case?

**Comment by eseliger** [comment] 2020-05-20 12:14
If we would find a way - could we still show the diff after merge? That would be awesome!

**Comment by mrnugget** [comment] 2020-05-20 12:15
@keegancsmith do you have an idea?

**Comment by ryanslade** [comment] 2020-05-20 12:39
I'm looking into whether we can find the merge commit

**Comment by ryanslade** [comment] 2020-05-20 13:33
I'm able to get the merge commit for Bitbucket via the merge activity.

**Comment by keegancsmith** [comment] 2020-05-20 14:31
We special case github pull requests refs: [`/refs/pull`]( https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+refs/pull&patternType=literal)

In particular you will need to atleast include `refs/pull-requests` when we fetch here https://github.com/sourcegraph/sourcegraph/blob/546b07457084c5858bbcef146193b8857e329531/cmd/gitserver/server/server.go#L1310

I see other mentions of `refs/pull`, I'm unsure if that special casing makes stuff just work.

**Comment by ryanslade** [comment] 2020-05-20 16:09
Summary of progress today:

GitHub actually seems to work correctly due to the special case that @keegancsmith mentioned above. So, if we allow diffs on changesets when they are in a `MERGED` state they display correctly.

For BitBucket I've got rid of the 'Revision not found' error by fetching the merge commit from the the pull requests events and using that as the head ref instead of the remote branch name. However, the diff always shows as empty.

We seem to be attempting to get the diff for the range `master...merge-commit`, which return an empty diff. (Notice the triple dot)

The code that decides this is here:
https://github.com/sourcegraph/sourcegraph/blob/494ad6806b8bacf4c3b0feacc053f91029b08349/cmd/frontend/graphqlbackend/repository_comparison.go#L213

If we use a double dot, we get the correct diff.

I'll dig into how to get the correct diff output tomorrow morning but any pointers would be helpful.

**Comment by mrnugget** [comment] 2020-05-21 11:30
> GitHub actually seems to work correctly due to the special case that @keegancsmith mentioned above. So, if we allow diffs on changesets when they are in a `MERGED` state they display correctly.

And these are never cleaned up? Even if the PR is merged and the branch has been deleted and we reclone the repository?

**Comment by keegancsmith** [comment] 2020-05-21 13:50
> And these are never cleaned up? Even if the PR is merged and the branch has been deleted and we reclone the repository?

GitHub doesn't clean them up, and I assume the same for Bitbucket. They likely rely on these refs internally to display the PR content. I would assume that if the PR is visible, so is the ref. A quick check I found no official looking docs (just community stuff) about the ref for bitbucket/stash.

**Closed** 2020-05-25 14:48 UTC
Labels: bug, campaigns, estimate/2d, planned/3.17, team/campaigns
