### ISSUE TITLE
Submit feedback button is invisible in dark theme

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4193] opened 2019-05-23 22:49 UTC
Bug report by @felixfbecker [in Slack](https://sourcegraph.slack.com/archives/C07KZF47K/p1556120418176600):

> FYI @chris the submit feedback button is invisible in dark theme
>
> ![image](https://user-images.githubusercontent.com/3173176/58291307-d3d15a80-7d71-11e9-9f25-671c7e6718d1.png)

**Comment by felixfbecker** [comment] 2019-05-23 22:50
Duplicate of #4815

**Closed by felixfbecker** 2019-05-23 22:50 UTC
