### ISSUE TITLE
New GitLab repos added to instance after initial setup do not get added properly

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#672] opened 2018-11-03 00:47 UTC
- **Sourcegraph version:** dev build
- **Platform information:** 

(Using gitlab2.sgdev.org)

#### Steps to reproduce:

1. Set up Sourcegraph to connect to your GitLab instance.
2. Verify that existing repos on the GitLab instance exist and are viewable on Sourcegraph
3. Add a new repository to GitLab instance
4. See that it doesn't appear in the site admin repositories page.
5. Go directly to the repo (e.g. http://localhost:3080/gitlab2.sgdev.org/root/test-updates)
6. Try to add the repository, and see this error: 
![image](https://user-images.githubusercontent.com/16265452/47946312-46a6e100-dec7-11e8-81c7-764fd4666ae8.png)

#### Expected behavior:

The new repo appears in the site admin repo page, and you can go directly to the repo and add it.

#### Actual behavior:

The repo does not appear, and cannot be added.

**Comment by beyang** [comment] 2018-11-04 02:13
Closing as dupe of https://github.com/sourcegraph/sourcegraph/issues/671

**Closed by beyang** 2018-11-04 02:13 UTC
