### ISSUE TITLE
Git server keeps re-cloning repos in dev that are no longer in any external service

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#5056] opened 2019-08-01 22:21 UTC
Whenever I have my dev instance running, this is its log output:

![2019-08-01 22 22 50](https://user-images.githubusercontent.com/10532611/62331119-3609b280-b4bb-11e9-95d6-170a83fba570.gif)

As you can see, it is constantly cloning repos from our GHE instance, bringing my fans to spin.
But, there is no GHE external service configured. I deleted it from both the UI and from the JSON config in dev-private (locally) quite a while ago. I even ran `drop-entire-local-database-and-redis` and restartet, and it still started cloning these repos again.
This makes my local instance almost unusable because it slows it down tremendously.

**Comment by mrnugget** [comment] 2019-08-02 04:48
Hmm, how can I reproduce this? I'm not running into this issue and I basically do the same: my `dev-private` copy has the `ghe.sgdev.org` config commented out and I regularily drop my local PSQL database and restart. I don't see `ghe.sgdev.org` being readded.

> I even ran `drop-entire-local-database-and-redis` and restartet, and it still started cloning these repos again.

Did it work? Did you make sure that the DB was empty?

What does this print? (Feel free to adjust username/pw/database):

```bash
$ psql -d sourcegraph -c "SELECT * FROM external_services WHERE kind = 'GITHUB';"
```

**Comment by felixfbecker** [comment] 2019-08-02 11:08
I don't know how to reproduce this. What I know is that I had quite a lot of GHE repos cloned at some point and it seems like instead of getting rid of them it keeps updating them or cloning more?

> Did it work? Did you make sure that the DB was empty?

Well I had to sign up again so I assume it worked.

> What does this print? (Feel free to adjust username/pw/database):

```
 id |  kind  | display_name |                         config                         |          created_at           |          updated_at           |          deleted_at           
----+--------+--------------+--------------------------------------------------------+-------------------------------+-------------------------------+-------------------------------
  1 | GITHUB | GITHUB #1    | {                                                     +| 2019-08-01 22:14:56.777941+02 | 2019-08-01 22:16:15.593649+02 | 2019-08-02 00:19:24.040325+02
    |        |              |   "authorization": {},                                +|                               |                               | 
    |        |              |   "repositoryQuery": [                                +|                               |                               | 
    |        |              |     "sourcegraph/codeintellify",                      +|                               |                               | 
    |        |              |     "gorilla/mux"                                     +|                               |                               | 
    |        |              |   ],                                                  +|                               |                               | 
    |        |              |   "token": "redactedredactedredactedredactedredacted",+|                               |                               | 
    |        |              |   "url": "https://github.com"                         +|                               |                               | 
    |        |              | }                                                      |                               |                               | 
  2 | GITHUB | GITHUB #1    | {                                                     +| 2019-08-02 00:19:24.073331+02 | 2019-08-02 00:19:24.073331+02 | 2019-08-02 00:24:20.274148+02
    |        |              |   "authorization": {},                                +|                               |                               | 
    |        |              |   "repositoryQuery": [                                +|                               |                               | 
    |        |              |     "gorilla/mux"                                     +|                               |                               | 
    |        |              |   ],                                                  +|                               |                               | 
    |        |              |   "token": "redactedredactedredactedredactedredacted",+|                               |                               | 
    |        |              |   "url": "https://github.com"                         +|                               |                               | 
    |        |              | }                                                      |                               |                               | 
  3 | GITHUB | GITHUB #1    | {                                                     +| 2019-08-02 00:24:20.276172+02 | 2019-08-02 00:24:20.276172+02 | 2019-08-02 00:32:49.513205+02
    |        |              |   "authorization": {},                                +|                               |                               | 
    |        |              |   "repositoryQuery": [                                +|                               |                               | 
    |        |              |     "gorilla/mux",                                    +|                               |                               | 
    |        |              |     "sourcegraph/codeintellify"                       +|                               |                               | 
    |        |              |   ],                                                  +|                               |                               | 
    |        |              |   "token": "redactedredactedredactedredactedredacted",+|                               |                               | 
    |        |              |   "url": "https://github.com"                         +|                               |                               | 
    |        |              | }                                                      |                               |                               | 
  4 | GITHUB | GITHUB #1    | {                                                     +| 2019-08-02 00:32:49.546924+02 | 2019-08-02 00:32:49.546924+02 | 2019-08-02 00:35:11.004979+02
    |        |              |   "authorization": {},                                +|                               |                               | 
    |        |              |   "repositoryQuery": [                                +|                               |                               | 
    |        |              |     "gorilla/mux",                                    +|                               |                               | 
    |        |              |     "sourcegraph/codeintellify"                       +|                               |                               | 
    |        |              |   ],                                                  +|                               |                               | 
    |        |              |   "token": "redactedredactedredactedredactedredacted",+|                               |                               | 
    |        |              |   "url": "https://github.com"                         +|                               |                               | 
    |        |              | }                                                      |                               |                               | 
  5 | GITHUB | GITHUB #1    | {                                                     +| 2019-08-02 00:35:11.032016+02 | 2019-08-02 00:35:11.032016+02 | 
    |        |              |   "authorization": {},                                +|                               |                               | 
    |        |              |   "repositoryQuery": [                                +|                               |                               | 
    |        |              |     "gorilla/mux",                                    +|                               |                               | 
    |        |              |     "sourcegraph/codeintellify"                       +|                               |                               | 
    |        |              |   ],                                                  +|                               |                               | 
    |        |              |   "token": "redactedredactedredactedredactedredacted",+|                               |                               | 
    |        |              |   "url": "https://github.com"                         +|                               |                               | 
    |        |              | }                                                      |                               |                               | 
(5 rows)
```

**Comment by mrnugget** [comment] 2019-08-02 11:59
So you only have 5 duplicate `github.com` external services, the database has been reset otherwise, and if you restart _everything_ `gitserver` still clones those repositories?

What happens when you stop every process, drop the database, comment out this line
https://github.com/sourcegraph/sourcegraph/blob/8db4e1f7d586c0f649a7a2fff745b358207856de/enterprise/dev/start.sh#L23
and then restart `./enterprise/dev/start.sh`?

**Comment by felixfbecker** [comment] 2019-08-02 13:19
I moved `ghe.sgdev.org` from `~/.sourcegraph/repos` and now they are not cloned anymore. Seems like the presence of folders in there represent some state?

**Comment by mrnugget** [comment] 2019-08-02 13:21
> I moved `ghe.sgdev.org` from `~/.sourcegraph/repos` and now they are not cloned anymore. Seems like the presence of folders in there represent some state?

Is that the _only_ thing you did?

**Comment by felixfbecker** [comment] 2019-08-02 13:23
Since reporting this issue and the actions I explained in the issue, yes.

**Comment by theonlydoo** [comment] 2019-08-05 07:03
same issue over here, SG keeps cloning my gitlab instance in a loop since a week ago

**Comment by mrnugget** [comment] 2019-08-06 07:35
Yay! @keegancsmith helped me to figure this out. It's actually not a bug, but a confusing combination of two features:

1. We changed how purging/cleaning up old repos works. Instead of immediately deleting the repos when you delete an external service, we now delay the deletion process (so people don't have to reclone their entire GitHub account, for example, if they re-create it). The result is that you have to be running Sourcegraph at 2am on a Saturday for the repos to be deleted. [See this for more information/background.](https://github.com/sourcegraph/sourcegraph/issues/2572)
2. `gitserver` has a functionality built in that reclones repo every ~45 days if they haven't been updated before. (Why a reclone? It's cheaper than running `git gc`) See code here: https://github.com/sourcegraph/sourcegraph/blob/435d582da1e69a27bd81cb23e5d77edfe52945d9/cmd/gitserver/server/cleanup.go#L84-L95

---

Now, what can we do to solve this issue? I personally think that we should keep these two features and they're there for a good reason, but maybe we could modify them and make it clearer what's happening.

Do you think changing the log message from "recloning expired repo" to "recloning repo because folder hasn't been updated in X days" would have avoided the confusion?

**Comment by theonlydoo** [comment] 2019-08-06 07:38
I, for one, trashed all my repos and config and started from scratch. It also worked.

**Comment by mrnugget** [comment] 2019-08-06 07:47
After further discussion with @keegancsmith we concluded that the best way forward would be to improve the purging process, because the _ideal scenario_ is that the repos shouldn't have existed anymore.

We have some ideas for how to improve the purging process. Instead of only purging every Saturday, we introduce two processes:
1. Process A runs every day and marks repos for deletion with a timestamp
2. Process B runs every day and checks whether repos have a deletion timestamp. If they do and it's older than X days (proposal: 3 days), then it deletes them.

Mark and sweep for repos :)

**Comment by iokhahon** [comment] 2022-02-28 20:50
Also could be a duplicate of the bug I opened [24607]( https://github.com/sourcegraph/sourcegraph/issues/24607).
This problem still exists in 3.37.0

**Comment by ryanslade** [comment] 2022-05-31 13:35
Closing this as it is no longer an issue, will the keep https://github.com/sourcegraph/sourcegraph/issues/24607 open as that is gitolite specific.

**Closed by ryanslade** 2022-05-31 13:35 UTC
Labels: bug, debt, team/core-application
