### ISSUE TITLE
Insights: datapoint click to diff search dates are wrong dates

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#38269] opened 2022-07-06 03:41 UTC
See [this insight](https://demo.sourcegraph.com/insights/insight/aW5zaWdodF92aWV3OiIyNWN5b1BZeWFLSVdmVllXeGRqTmtUYTl2Um4i) and [this loom ](https://www.loom.com/share/3c6b170cf7624c5aaa90349fe6166cc6). 

They are wrong in 2 ways: 
1. Sometimes the correct date for the before/after field, but then also it's repeated for the other field (so the time window is 0 and I get 0 results) 
2. Sometimes totally wrong before/after windows, like drawn from another datapoint.

**Comment by sourcegraph-bot-2** [comment] 2022-07-06 03:42
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment] 2022-07-07 04:43
Thanks @vovakulikov . How about we leave this open until we resolve the second issue you linked and verified that solved the problem?

**Comment by unclejustin** [comment] 2022-07-19 21:50
@Joelkw - following up on this after the BE fix was deployed. 

The insight from your loom appears to be sending the correct before/after dates. Interestingly [this link](https://demo.sourcegraph.com/search?q=repo:sourcegraph/sourcegraph%24++type:diff+after:2022-06-18T00:22:30-05:00+before:2022-07-04T20:46:01-05:00+docs.sourcegraph.com+file:client/web/src/enterprise&patternType=literal) still shows no matched results even though the dates seem correct.

I cannot reproduce this error anymore 🤔

**Comment by unclejustin** [comment] 2022-07-21 17:05
Fixed with other PRs

**Closed** 2022-08-09 09:12 UTC
Labels: bug, webapp, team/code-insights
