### ISSUE TITLE
Widening file tree sidebar on top of search suggestions

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7611] opened 2020-01-09 08:03 UTC
- **Sourcegraph version:** Sourcegraph.com

![image](https://user-images.githubusercontent.com/5589410/72049247-61b37480-3273-11ea-9411-dd0841d5f346.png)

#### Steps to reproduce:

1. Go to a file
2. Type in the search bar to get autocomplete suggestions
3. See that you can widen the sidebar on top of the suggestion

**Comment by felixfbecker** [comment] 2020-10-19 08:54
Closing since this search box is no longer in use and doesn't reproduce on the new search box.

**Closed by felixfbecker** 2020-10-19 08:54 UTC
Labels: bug, team/web, webapp
