### ISSUE TITLE
Following source code references entraps view in bottom right panel

### ISSUE THREAD

**Issue by seh** [sourcegraph/sourcegraph#41545] opened 2022-09-08 20:12 UTC
# Context
- **Sourcegraph version:** _Sourcegraph.com_
- **Platform information:** macOS 12.5.1, Chrome 105.0.5195.102

# Steps to reproduce:

1. View a source code file in a language such as Go.
1. Hover over a recognized symbol such as a struct field or function name.
1. Select the "Find References" button in the pop-up panel.
1. Select a found hit in the "References" section of the bottom panel's "References" tab.
1. Observe that the bottom panel splits and displays the referenced source code line.
1. Attempt to go to a definition displayed in this source code pane in the bottom panel.

# Expected behavior:

The target of the reference being followed should either appear in the main source code view, or there should be a gesture available to choose to focus on the target like that, if that can't be the default behavior.

# Actual behavior:

The target of the reference being followed appears in the source code pane in the bottom panel, and there's no apparent way to get anything selected in that pane to change the main source code view.

If I remember correctly, Sourcegraph _used to_ work like I expect that it should. I only noticed this change in behavior about a week ago. It now feels like using the "References" bottom panel leads to being trapped, trying to look through a narrow "keyhole," where I can't even see most of the pop-up menus well enough to use them.

**Comment by malomarrec** [comment] 2022-09-20 13:19
Hey @eugeniaft, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by varungandhi-src** [comment] 2023-11-22 10:52
The expected behavior matches the current behavior. Closing this as "can't repro"

![CleanShot 2023-11-22 at 18 51 43](https://github.com/sourcegraph/sourcegraph/assets/93103176/4d5c800f-389e-4c50-9352-6620e089b811)

**Closed by varungandhi-src** 2023-11-22 10:52 UTC
Labels: team/graph, team/code-navigation
