### ISSUE TITLE
insights: improve test suite to catch end-to-end regressions

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#18391] opened 2021-02-17 21:14 UTC
It's possible to introduce a bug/regression when _everything_ is wired up together. Example: https://github.com/sourcegraph/sourcegraph/pull/18390

We could benefit from having some `gqltest` perhaps, which go through the motions of using the GraphQL API to add insights to user settings and then querying info on them etc. and making sure stuff works as we expect. Of course, this will be a bit tricky to set up especially because insights population can take a while to go through.

**Comment by CristinaBirkel** [comment] 2022-02-11 22:02
Duplicate of in progress issue: https://github.com/sourcegraph/sourcegraph/issues/27552

**Closed by CristinaBirkel** 2022-02-11 22:02 UTC
Labels: team/code-insights, nice-to-have, backend
