### ISSUE TITLE
regression: horizontal divider between search result locations missing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7958] opened 2020-01-23 01:06 UTC
@chrismwendt noticed the horizontal divider between search result locations is missing, and I also noticed this (I was having some major confusion with some search results -- it showed me two near each-other just like this but when I clicked through I only got one). This is really bad:

![image](https://user-images.githubusercontent.com/3173176/72948233-c8d82b00-3d41-11ea-8c7f-6e3d1f44e3c1.png)

TODO: Is this in `master` or the currently released version?

**Comment by tsenart** [comment] 2020-01-23 10:13
@slimsag: I think it's best always assigning to the manager of the responsible team, in this case, @lguychard. Otherwise it's easy to miss this.

**Comment by lguychard** [comment] 2020-01-23 10:32
Confirmed that this is present in `sourcegraph/server:3.12.0`:

![image](https://user-images.githubusercontent.com/1741180/72977097-0e453880-3dd4-11ea-987c-56e3752185d6.png)

Likely caused by https://github.com/sourcegraph/sourcegraph/commit/75e4cb28b99e2d17aa901a2be2ca7ca8ffa463b1#diff-eb20230c8d9770faf3da8b98032cb1b6

**Closed** 2020-01-23 10:38 UTC
Labels: bug, p1, regression, web
