### ISSUE TITLE
Add a visual pulse to current line when user tries to go to a definition they're already at

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#12938] opened 2020-08-12 13:10 UTC
### Problem Statement

When users click "Go to definition" while already at that definition, there's no feedback in response to their action, which can lead to a "mental hiccup" at the lack of response. If we improve this, it'll improve usability of "Go to definition" by reinforcing the user is already at the definition.

![Kapture 2020-08-12 at 14 51 40](https://user-images.githubusercontent.com/6304497/90017148-62016b80-dcab-11ea-8884-407c4cb0372d.gif)

### Solution

When the user clicks "Go to definition" when they're already at that definition, pulse the background colour of the current line. Quick example (for demo purposes, not exactly how it would look):

![Kapture 2020-08-12 at 15 07 32](https://user-images.githubusercontent.com/6304497/90018713-a4c44300-dcad-11ea-9c66-f30b4e2fdec9.gif)

I don't think we'll be able to measure the impact of this, but it's a usability paper cut we ought fix!

**Comment by AlicjaSuska** [comment] 2020-09-07 16:55
This issue was confirmed in my recent usability testing as well. Testers were trying to go to definition from the line where the definition is. In my opinion, though, we need more than the background pulse. I would disable the 'Go to definition' button or add 'You're viewing the definition' label. @quinnkeast

**Comment by quinnkeast** [comment] 2020-09-08 08:07
I think there're two separate cases to address here: 

1. Experienced users in a flow state.
2. New users learning how code intel works.

The pulse solution solves the case for experienced users. When these users try to go to a line they're already at, it's a slip, rather than a mistake—their attention is focused on the task at hand, and they're not thinking actively about the rest of the UI. For these users, the pulse is intended to be a quick, nearly subconscious reminder.

For new users, attention is more direct. I agree the pulse may not be enough to communicate clearly. Adding a "this is the definition" label would be useful here. 

However, I'm not sure I like the idea of disabling or changing the "Go to definition" button—when users in a flow state click it, the pulse is a response reminding them they're at the line already. If we disable the button, instead of reminding them they're at the line, they'll be experiencing a new issue—the button not responding.

I'm also mindful about making several changes to this UI at once, since it's a relatively minimal UI to start with... how would you feel about first implementing the pulse, then doing a quick, similar usability study to see if the label is also then needed?

**Comment by AlicjaSuska** [comment] 2020-09-09 15:01
Sure, let's try it! Thank you for explaining your point @quinnkeast Let's try your approach and follow up on this issue 🎉

**Comment by macraig** [comment] 2020-10-21 17:25
@quinnkeast @AlicjaSuska this is really great! Was there any follow-up?

**Comment by AlicjaSuska** [comment] 2020-10-22 08:22
@macraig I think @quinnkeast 's solution (the pulse) is ready for implementation and should happen as soon as it is possible (maybe next iteration)? 🎉

**Comment by jjinnii** [comment] 2021-09-20 17:54
@quinnkeast Is there a Figma link to your pulsing line solution? Revisiting this now :)

**Comment by quinnkeast** [comment] 2021-09-27 09:59
Here you go!
- [Figma link](https://www.figma.com/file/DlEfljAnCYCmuPWGgjXhcy/12938-Already-at-definition-pulse?node-id=1%3A28)
- [Prototype link](https://www.figma.com/proto/DlEfljAnCYCmuPWGgjXhcy/12938-Already-at-definition-pulse?page-id=0%3A1&node-id=1%3A36&viewport=411%2C48%2C0.39&scaling=min-zoom&starting-point-node-id=1%3A20)

**Comment by jjinnii** [comment] 2021-09-27 18:59
Thanks Quinn! Agree with everything that's already been talked about in this issue. In particular, I think just disabling the original button is not effective in addressing the "mental hiccup" primary use case. That being said, also agree that the pulse is not directly communicating what the problem is, especially for a first time user. 

@quinnkeast @AlicjaSuska I know I'm re-visiting something that was more or less decided on, but thoughts on [this prototype](https://www.figma.com/proto/DlEfljAnCYCmuPWGgjXhcy/12938-Already-at-definition-pulse?page-id=0%3A1&node-id=21%3A1314&viewport=241%2C48%2C0.33&scaling=min-zoom&starting-point-node-id=19%3A18&show-proto-sidebar=1)? I know it's unconventional behavior to have a disabled button be clickable, but there are precedents of using motion to communicate an error or non actionable state (I'm blanking on a good example though 😅 ).

**Comment by olafurpg** [comment] 2021-09-28 07:12
Not sure if we can adopt similar behavior as IntelliJ and VS Code, which both address this problem by automatically doing "find references" when you trigger "goto definition" at the definition location. VS Code adopted the IntelliJ behavior not too long ago.

The first Cmd+Click navigates to the definition and the second Cmd+Click triggers find references on that symbol

### VS Code
![CleanShot 2021-09-28 at 09 10 37](https://user-images.githubusercontent.com/1408093/135040144-73d91fc5-f76c-4ef7-b9dd-42c5d4e7df74.gif)

### IntelliJ
![CleanShot 2021-09-28 at 09 09 23](https://user-images.githubusercontent.com/1408093/135040254-aea59eab-3a7a-461c-a71b-31f6d7c294b9.gif)

**Comment by jjinnii** [comment] 2021-09-28 16:36
Thanks @olafurpg, I like that idea a lot! Just a couple concerns with using that behavior: 
- Taking the user to the reference panel, when clicking on "go to definition" due to a mental hiccup is not necessarily communicating to the user that they're already at the definition 
- With IntelliJ especially, triggering find reference opens up references in-line, whereas we would have to open up the reference panel below. For a user who was not trying to view references, it wouldn't be a great experience to then navigate lower to the page and close out our reference panel. 

I think that behavior is something we can re-visit when we're thinking through the concept of hoverovers/panels as a whole! For this issue within the framework of our hoverovers, I think simply disabling and communicating that the user is at the definition is an effective solution. 

Feel free to lmk if you think otherwise!

**Comment by jjinnii** [comment] 2021-10-04 21:33
Rounding out this issue. There doesn't seem to be further feedback, so let's implement [this design ](https://www.figma.com/file/DlEfljAnCYCmuPWGgjXhcy/12938-Already-at-definition-pulse?node-id=19%3A18)with new disabled "you are at the definition" button + pulse. We can monitor for feedback after implementation!

**Comment by Numbers88s** [comment] 2021-11-01 21:24
Closed by https://github.com/sourcegraph/sourcegraph/pull/26892

**Closed by Numbers88s** 2021-11-01 21:24 UTC
Labels: feature-request, team/code-intelligence, design, needs-design, ux
