### ISSUE TITLE
Browser ext popup doesn't show

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#1439] opened 2018-12-14 19:54 UTC
Repro:

1. Click browser toolbar button, material design flash shows up but no popup

Error in background page that seems related:

```
background.bundle.js:1 Error: Invocation of form browserAction.setPopup(object, function) doesn't match definition browserAction.setPopup(object details)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:115)
    at Object.<anonymous> (extensions::binding:363)
    at t (background.bundle.js:1)
    at new Promise (<anonymous>)
    at Object.a (background.bundle.js:1)
    at T (background.bundle.js:1)
    at Object.v.a.setSync [as callback] (background.bundle.js:1)
    at safeCallbackApply (extensions::uncaught_exception_handler:27)
    at handleResponse (extensions::sendRequest:67)
(anonymous) @ background.bundle.js:1
```

**Comment by ijsnow** [comment] 2018-12-17 22:36
Can't reproduce. Won't fix.

**Closed by ijsnow** 2018-12-17 22:36 UTC
Labels: browser-extension, bug
