### ISSUE TITLE
Fully resolve "keep recloning" bug

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#22942] opened 2021-07-16 21:27 UTC
#### Steps to reproduce:

This stems from a conversation with @unknwon about https://github.com/sourcegraph/sourcegraph/issues/10274 . He suggested that the solution to that issue would confined the bug to off-hours but may not fully resolve it, and it was suggested that a new issue be recreated. 

See also https://github.com/sourcegraph/sourcegraph/issues/5056 and https://sourcegraph.slack.com/archives/C0W2E592M/p1626417583101700?thread_ts=1626104961.005400&cid=C0W2E592M

#### Expected behavior:

No clone loop.

#### Actual behavior:

Clone loop.

**Comment by iokhahon** [comment] 2022-02-28 20:49
Also could be a duplicate of the bug I opened [#24607](https://github.com/sourcegraph/sourcegraph/issues/24607).
This problem still exists in 3.37.0

**Closed** 2024-02-04 19:06 UTC
Labels: bug, team/source
