### ISSUE TITLE
user preferences documentation is missing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#8291] opened 2020-02-05 21:30 UTC
Where is the documentation for user preferences / settings such as `search.contextLines`? What other settings are in the user schema JSON that are not documented?

**Comment by dadlerj** [comment] 2020-02-05 21:33
This is unfortunately a known issue, and a duplicate of https://github.com/sourcegraph/sourcegraph/issues/7707 and https://github.com/sourcegraph/sourcegraph/issues/5328

CC @ryan-blunden

**Comment by aileenrose** [comment] 2020-10-20 20:21
no longer an issue

**Closed by aileenrose** 2020-10-20 20:21 UTC
Labels: docs
