### ISSUE TITLE
docs: Markdown heading symbols are misaligned on Firefox 

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#2246] opened 2019-02-11 22:34 UTC
**Platform information**: Firefox Developer Edition 66.0b6 

#### Steps to reproduce:

1. Open https://docs.sourcegraph.com/admin/install/docker/aws
1. Hover over a heading like "Install Sourcegraph with Docker on AWS" 
1. Notice that the `#` symbol is aligned _below_ the actual heading text 

See:

![](https://duaw26jehqd4r.cloudfront.net/items/0p373I2i1X2k0s2z1I2q/Screen%20Recording%202019-02-11%20at%2002.27%20PM.gif)

![screen shot 2019-02-11 at 2 34 00 pm](https://user-images.githubusercontent.com/9022011/52598300-2b266d00-2e0a-11e9-8717-4ce4315b26d9.png)

**Comment by leonore** [comment] 2022-07-29 15:36
closing as I couldn't reproduce anymore!

**Closed by leonore** 2022-07-29 15:36 UTC
Labels: docs, docathon
