### ISSUE TITLE
Code Insights historicalEnqueuer takes a long time (maybe does not complete), takes up CPU usage running Git operations constantly

### ISSUE THREAD

**Issue by arussellsaw** [sourcegraph/sourcegraph#19089] opened 2021-03-12 09:21 UTC
After debugging some high CPU usage bugs from gitserver on my local instance, @mrnugget & i noticed that it seems as though code insights is always reprocessing all frames in an infinite loop. I noticed that i could leave my instance idle for hours or even overnight, and i'd still see high gitserver utilisation. below is copied from PR #19088 

it seems like the enqueuer never stops re-enqueueing all frames, eg once a full 52 weeks are processed, it loops back to the beginning and starts again. 

you can see this below where 2020 loops back to 2021 and we start processing frames again.

![Screenshot 2021-03-12 at 09 08 41](https://user-images.githubusercontent.com/5236823/110919032-b76e2b80-8313-11eb-89b6-88dae8a53bb2.png)

right now this is manifesting as gitserver spawning git log & git rev-list commands in a tight loop permanently, eating a CPU core and spending a lot of time doing GC. I'll also raise this in a separate issue & ref here.

https://user-images.githubusercontent.com/5236823/110919270-f7351300-8313-11eb-8cba-db6d067534ba.mov

**Comment by slimsag** [comment] 2021-03-12 21:20
I'll think about if I can come up with a better strategy here, and definitely solve the "high CPU usage" issue you are describing in some way. I agree this is a problem.

Also FYI some of the stuff Thorsten ran into will be fixed in https://github.com/sourcegraph/sourcegraph/pull/19082

---

I do want to note that what you are describing is to a large extent how this is designed to work (excluding the high CPU usage issue ofc.)

> it seems like the enqueuer never stops re-enqueueing all frames, eg once a full 52 weeks are processed, it loops back to the beginning and starts again.

To be clear, _there is no queue of frames_. It is a for loop that continuously walks over the past 52 weeks and _looks for work to be enqueued_, the process you are describing is actually _what looks for work to be enqueued_ and not the actual work itself. It does this slowly (and with yielding, as you saw), with the intent of not placing impact on the overall system (but on weaker dev environments this may well still be an issue.)

The problem can be simply expressed as follows:

* Users can add insights to their settings _at any point in time._
* Insights may *just exist* from the past, i.e. there is no "event" under which we can detect that we need to backfill data or anything like that. New repos can be added at any time and we need to generate data for them still.
* So the problem is: We need to identify past timeframes that are missing data (by querying the DB for "do you have data in this timeframe for repo X?") and if it's missing then attempt to populate it.

_This is a continuous process that runs forever._ One part of this process is figuring out "what commit in the repository is closest to the timeframe we're looking for?" - which is the Git operations you're seeing. However, that Git operation should only happen if the insight doesn't have data for that timeframe+insight+repo (we ask first "are we missing data for this repo in this timeframe?")

There is also some pseudo-code here to explain how it is supposed to work: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@049b99763b10ddc7ef6f72c22b18f1fa5f4f7259/-/blob/enterprise/internal/insights/background/historical_enqueuer.go#L125-137

**Comment by mrnugget** [comment] 2021-03-15 09:07
That sounds like you're assuming that git history is rewritten, right? Because otherwise I don't understand why you'd need to recompute "insight X for repo Y at point in time T1 is Z" needs to be recomputed in a loop.

I'm wondering if you can't make some tradeoffs to lessen the load immensly and, for example, make this event-driven and only run this loop if: an insight was added/modified or a repo was added/modified/updated. Based on these two events you'd still get a ton of false positives (since 99% of updates to a repo won't have an affect on the insights I'd assume) but reduce the computation a lot.

You also have two [early exits](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@049b99763b10ddc7ef6f72c22b18f1fa5f4f7259/-/blob/enterprise/internal/insights/background/historical_enqueuer.go#L374-382) in your series-building function that make any historical computation for a given series useless. If you move that up to [the outer loop](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@049b99763b10ddc7ef6f72c22b18f1fa5f4f7259/-/blob/enterprise/internal/insights/background/historical_enqueuer.go#L182-201), couldn't you then save another every-repo-every-week loop?

**Comment by slimsag** [comment] 2021-03-15 17:02
> That sounds like you're assuming that git history is rewritten, right? Because otherwise I don't understand why you'd need to recompute "insight X for repo Y at point in time T1 is Z" needs to be recomputed in a loop.
> ...
> for example, make this event-driven and only run this loop if: an insight was added/modified or a repo was added/modified/updated. Based on these two events you'd still get a ton of false positives (since 99% of updates to a repo won't have an affect on the insights I'd assume) but reduce the computation a lot.

I think you may be mistaking where the computation time is actually spent.

You are completely correct that an event of "an insight was added/modified or a repo was added/modified/updated" is more optimal, but the part I think you may not be seeing is that we're still talking about the following regardless of what trigger we use:

```
num_unique_search_queries = num_distinct(insights_in_user_settings.search_queries)
num_actual_searches = num_unique_search_queries * num_repos_on_sourcegraph * 52 (weeks)
```

No matter what trigger we use, or how we structure the actual implementation, that is an _astounding_ number of search queries to perform. On a dev instance, with two search insights and 50 repositories that's 2*50*52 == 5200 search queries we need to perform.

Because of this astounding amount of search queries and potential for major load on the system, I made the process completely linear (so the more insights you add, or the more repos you add, we slowly run searches one-by-one, period.) For a single insight it can take an extremely long time to produce the historical data (on the order of days.)

**Comment by slimsag** [comment] 2021-03-15 17:07
> Edit: another "are you expecting git history to be rewritten?"-question: you're querying the "first commit made" in a repository for every repository in every frame. I'm not sure whether "first commit made" can become invalid, so I'm not sure if it's cacheable, but at least that request to gitserver can be computed once for every repository in your main loop, right?
>
> Edit 2: The "nearest commit for a point in time" could also be cached and invalidated when the repository is updated, right?

Yes, these are true and given this issue sounds worth doing.

**Comment by mrnugget** [comment] 2021-03-15 17:30
> You are completely correct that an event of "an insight was added/modified or a repo was added/modified/updated" is more optimal, but the part I think you may not be seeing is that we're still talking about the following regardless of what trigger we use:
> 
> ```
> num_unique_search_queries = num_distinct(insights_in_user_settings.search_queries)
> num_actual_searches = num_unique_search_queries * num_repos_on_sourcegraph * 52 (weeks)
> ```
> 
> No matter what trigger we use, or how we structure the actual implementation, that is an _astounding_ number of search queries to perform. On a dev instance, with two search insights and 50 repositories that's 2_50_52 == 5200 search queries we need to perform.

Ah, I see! So from reading the code again now it looks like that the requests to gitserver are not part of the "generate data for this repo at this point in time" but only a way to get there, which is why they were happening in an endless loop. The actual computation of "data in this repo at this point in time" is cached. Correct?

If so, yeah, after caching the gitserver calls the only other heavy thing this loop does would be to query each repository and its data, which I think is fine for now?

And if JOINs are possible in any way this could then be optimized to only iterate over the repositories that don't have data for the given series in the given timeframe, etc.

**Comment by slimsag** [comment] 2021-03-15 17:49
> requests to gitserver are not part of the "generate data for this repo at this point in time" but only a way to get there

Yes.

> which is why they were happening in an endless loop.

Note that `gitFindNearestCommit` is _never_ called unless data is missing. So once data exists for a given point in time, that's not going to be called again unless new repos are added or new insights are added. The gitserver operation that is called in an endless loop is _just_ `gitFirstEverCommit` and it is called _at most_ once every 100ms due to `yield()`s.

> The actual computation of "data in this repo at this point in time" is cached. Correct?

Yes, once data exists in the DB for a given `(timeframe, repo, search query)` tuple we never need to do that work again.

> If so, yeah, after caching the gitserver calls the only other heavy thing this loop does would be to query each repository and its data, which I think is fine for now?

I want to be clear: high gitserver CPU here is almost certainly going to come from one thing and one thing only: the searches themselves. All this loop does is slowly (every 100ms) enqueue search queries like `repo:...@rev <query>` to search the repo at a past point in time. The challenge is that we're talking about thousands of searches in the smallest case, and millions of searches in production-scale cases like k8s.sgdev.org. Gitserver runs these searches, they aren't indexed, and it's going to be costly. This is why we enqueue them slowly and linearly, specifically so we don't consume every gitserver instance available.

It sucks that this is so expensive/costly, both from a resource usage standpoint, from a "I have to wait days to see historical data for my insights", and from a "debugging this is a huge pain" standpoint. But that's because the direct user problem we have here ("please go back in time and tell me, per repository, how many results existed for my search query") is directly costly, challenging, expensive, complex, and time consuming. I don't like it and want to find a better/faster way to do this, but it's the best I could come up with.

> And if JOINs are possible in any way this could then be optimized to only iterate over the repositories that don't have data for the given series in the given timeframe, etc.

Yes, joins are not possible due to it being a separate DB. Note that 'only operate on the repositories that don't have data for the given series+timeframe' is exactly what happens today (it's just that we must iterate over each repo, and query "do we have data for this series+timeframe?" for each one.)

**Comment by slimsag** [comment] 2021-03-15 17:51
BTW, one obvious thing here is to just disable the historical enqueuer in dev mode. I will send a PR to do that.

**Comment by mrnugget** [comment] 2021-03-16 08:24
> I want to be clear: high gitserver CPU here is almost certainly going to come from one thing and one thing only: the searches themselves.

Yep, _after_ caching `gitFirstEverCommit` though, right? Because otherwise you're going to send 10 requests per second to `gitserver`. That's not a lot compared to the search queries, but it's also not nothing.

> Note that 'only operate on the repositories that don't have data for the given series+timeframe' is exactly what happens today (it's just that we must iterate over each repo, and query "do we have data for this series+timeframe?" for each one.)

Yeah, I understand. My point was more about having a single query vs. an N+1. Behaviour is the same, of course.

**Comment by slimsag** [comment] 2021-03-16 23:07
> Yep, after caching gitFirstEverCommit though, right? Because otherwise you're going to send 10 requests per second to gitserver. That's not a lot compared to the search queries, but it's also not nothing.

Correct. I've added a cache for that in #19201 just now, but also disabled the historical enqueuer in dev mode.

To be clear, gitserver executing thousands of `git grep` over repos is going to be a LOT more expensive than 10 calls/second to `gitFirstEverCommit` - definitely worth caching, but, yeah - it's gotta be multiple orders of magnitude more expensive.

**Closed** 2021-03-16 23:10 UTC
Labels: bug, team/code-insights

**Comment by slimsag** [comment] 2021-03-16 23:47
Feel free to re-open this if I missed anything or you think there is something else that should be done here, I think the two changes I made above should effectively fix all the complaints here
