### ISSUE TITLE
Alert if available file descriptors is low

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#11420] opened 2020-06-10 21:40 UTC
A common issue in docker compose deployments is file descriptors being configured incorrectly, e.g. see https://sourcegraph.atlassian.net/browse/SG-231

We should alert if available file descriptors are < 262144 and update docker compose installation docs to reflect this requirement.

**Comment by bobheadxi** [comment] 2020-08-24 00:50
duplicate of https://github.com/sourcegraph/sourcegraph/issues/11420

**Closed by bobheadxi** 2020-08-24 00:50 UTC
Labels: okr/distribution/admin-experience, team/distribution
