### ISSUE TITLE
Basic code intel definition ranges are off

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#9936] opened 2020-04-17 06:00 UTC
- Go to https://sourcegraph.com/github.com/microsoft/TypeScript@deb5bac520a1134e188fc6f01fa4f52b66d2899b/-/blob/src/tsserver/server.ts?action#L505:23&tab=def
- Definition panel should pop up, select the result in nodeTypingsInstaller.js
- Notice the range does not match the class name
- When clicking it, no hover tooltip pops up because the column number linked to is off

![image](https://user-images.githubusercontent.com/10532611/79536813-36fe6680-8081-11ea-9ec1-57f775614696.png)

@sourcegraph/code-intel

**Comment by efritz** [comment] 2020-04-28 16:39
I believe this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/7668.

**Closed by efritz** 2020-04-28 16:39 UTC
Labels: bug, team/code-intelligence
