### ISSUE TITLE
Unable to perform a literal search with a query that contains a `:`

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#10171] opened 2020-04-24 16:52 UTC
Performing this query:
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+https://codecov.io/bash&patternType=literal

Results in this:
![Screen Shot 2020-04-24 at 9 48 21 AM](https://user-images.githubusercontent.com/754768/80236947-bd322400-8610-11ea-8986-f096ab28c69c.png)

I try to add quotes:
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22https://codecov.io/bash%22&patternType=literal

And then I get this:
![Screen Shot 2020-04-24 at 9 49 11 AM](https://user-images.githubusercontent.com/754768/80237023-db981f80-8610-11ea-926a-58c244311e6b.png)

To get what I want, I have to enabled regex:
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%22https://codecov.io/bash%22&patternType=regexp

![Screen Shot 2020-04-24 at 9 49 38 AM](https://user-images.githubusercontent.com/754768/80237048-ebafff00-8610-11ea-8ae1-2e018c3a6d4e.png)

My feedback as a user (not as VPE) is that we should allow my original query to work and not treat it like an error. We should silently ignore things that look like fields, but aren't in our small list of known fields.

@tsenart This might be a good issue for @asdine. cc @rvantonder

**Comment by tsenart** [comment] 2020-04-27 13:11
@nicksnyder: @asdine will be focusing next on #10194 (part of [RFC 136 MVP](https://github.com/sourcegraph/sourcegraph/issues/10197)). @rvantonder please triage this once you're back.

**Comment by rvantonder** [comment] 2020-05-05 18:11
This is very much a known issue.

> We should silently ignore things that look like fields, but aren't in our small list of known fields.

I remember relaxing the validation being an idea we floated before but there wasn't a firm decision. The problem is also related to the introduction of literal search, i.e., incidental and not accounted for.

I agree we should do this, and since I've rewritten the query parsing this would be straightforward to implement and test. However, a big portion of the work is to still migrate our current query parsing to the new implementation I wrote. That was planned as part of 3.16 but deprioritized. 

Since this issue has existed in the last 6 months, I think it's better to invest time in migrating away from the current query parsing rather than making this change in our current parsing. Off the top of my head I'm not sure how long it would take to remove this check and test it well for our current implementation, and I'd like to avoid the context switch to figure that out.

**Comment by dadlerj** [comment] 2020-05-07 01:21
Also reported by https://app.hubspot.com/contacts/2762526/company/693777200

Also reported by https://app.hubspot.com/contacts/2762526/company/557476528 (see https://sourcegraph.slack.com/archives/C0117QDJACU/p1588274728017700)

The latter company called out that this is particularly bad for Ruby users:

>quick usage question! Ruby classes are defined and namespace with colons. Looking for `ModuleName::ClassName` causes a query parse error. Wrapping it in quotes gets a warning and also isn't what we want. I'm guessing the best way is to search with `content:"ModuleName::Event"`, but then we sort of lose out on being able to search for multiple things

**Comment by uwedeportivo** [comment] 2020-06-15 19:27
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment] 2020-06-16 10:38
Can this be closed @rvantonder?

**Comment by rvantonder** [comment] 2020-06-17 07:24
This depends on #10844 which I didn't get to for literal and regexp search in this iteration (which is why this task doesn't have a time estimate). That migration is planned for 3.18 (high confidence it'll happen). But, since this has been delayed I might spend a couple of days to ensure this is prioritized so it isn't blocked on the migration. Adding this issue to 3.18.

**Comment by daxmc99** [comment] 2020-07-13 18:01
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment] 2020-08-13 03:44
This issue is fixed by the new parser (the [original query](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+https://codecov.io/bash&patternType=literal) now works). It is active on Sourcegraph.com, and so far the migration is successful, I don't anticipate rolling it back. The new parser will be rolled out by default either in 3.19 (TBD), or at the latest, in 3.20, so I am closing this issue.

I filed #12961 for a cosmetic issue that affects that particular pattern.

**Closed by rvantonder** 2020-08-13 03:44 UTC
Labels: team/search
