### ISSUE TITLE
Search for "playwright" but looks for "playright"

### ISSUE THREAD

**Issue by javigomez** [sourcegraph/sourcegraph#45058] opened 2022-12-02 11:52 UTC
- **Sourcegraph version:** 4.2
- **Platform information:** Your own sourcegraph instance

#### Steps to reproduce:

1. go to https://sourcegraph.com/search?q=context:global+playwright&patternType=standard&sm=0
2. look at the results

#### Expected behavior:
return results of "playwright"

#### Actual behavior:
return results for "playright" (without W in playWright)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by camdencheek** [comment] 2024-05-21 19:25
Closing since I can no longer reproduce. All our searches _should_ be exact matches unless using some experimental features.

**Closed by camdencheek** 2024-05-21 19:25 UTC
Labels: triage-bot/needs-triage
