### ISSUE TITLE
Code Insights: Implement the cloud specific landing page

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#30166] opened 2022-01-25 11:10 UTC
[Related slack thread ](https://sourcegraph.slack.com/archives/C01RVEVPWLC/p1643094232095300?thread_ts=1643047355.076900&cid=C01RVEVPWLC)

@Joelkw 
> @Alicja is working on a separate sourcegraph.com landing page for the cloud site, I believe, which will basically be a watered-down version of the in-product one plus perhaps a video or similar

**Comment by Joelkw** [comment] 2022-02-03 06:41
Is this a duplicate of #29955 @vovakulikov ? If so, feel free to close one. I don't care which one you want to use!

**Comment by vovakulikov** [comment] 2022-02-03 10:42
@Joelkw I yeah it must be just a duplicate. I'm going to close https://github.com/sourcegraph/sourcegraph/issues/29955 then. Thanks for noticing.

**Closed** 2022-03-04 19:56 UTC
Labels: webapp, team/code-insights, insights-GA, insights-landing-page
