### ISSUE TITLE
Clojure fuzzy code intel punctuation issues

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7700] opened 2020-01-13 22:09 UTC
Reported by a customer: https://app.hubspot.com/contacts/2762526/company/694011992

>The code intelligence for Clojure fails to match function names containing hyphens and special characters. when there are hyphens, hovering highlights only part of the function name but shows the popup for the correct function. when there are special characters such as ! and >, no popup shows up:

![image](https://user-images.githubusercontent.com/5589410/72296215-f6b8c380-360d-11ea-996a-ca70b9b61c2b.png)

Screenshot is from an open source Clojure repo.

And I was able to repro the special character issues in an open source repo at https://sourcegraph.com/github.com/tonsky/FiraCode@master/-/blob/clojure/glyphs.clj#L25:7

**Comment by chrismwendt** [comment] 2020-01-13 22:12
Confirming this is still an issue, duplicate of https://github.com/sourcegraph/sourcegraph/issues/3614

The fix is to make the `identCharPattern` configurable per language https://github.com/sourcegraph/sourcegraph-basic-code-intel/blob/a74c0aa6b41a36ce99da9484f6a855a69e409a2f/package/src/handler.ts#L15

**Closed by chrismwendt** 2020-01-13 22:12 UTC
Labels: bug, code-intel
