### ISSUE TITLE
String literal search "/foo/bar" causes an error despite "/" not being a regex special character

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4194] opened 2019-05-23 22:55 UTC
```
Parse error at character 14: got TokenLiteral, want separator or EOF
```

- Doesn't work: [`/foo/bar`](https://sourcegraph.sgdev.org/search?q=/foo/bar)
- Doesn't work: [`repo:foo /foo/bar`](https://sourcegraph.sgdev.org/search?q=repo:foo+/foo/bar)
- Works: [`/foo`](https://sourcegraph.sgdev.org/search?q=/foo)
- Works: [`foo/bar`](https://sourcegraph.sgdev.org/search?q=foo/bar)
- Works: [`foo/bar/`](https://sourcegraph.sgdev.org/search?q=foo/bar/)

Workarounds:

- Quote the string literal: https://sourcegraph.sgdev.org/search?q=%22/foo/bar%22
- Escape the forward slashes with backslashes: [`\/foo\/bar`](https://sourcegraph.sgdev.org/search?q=%5C/foo%5C/bar)

Reported by a user at 407948923

**Comment by rvantonder** [comment] 2019-12-18 16:02
I can't reproduce so this may no longer be an issue. There have been a couple of updates to this logic in the code, but I haven't tracked down which commit(s). Mind quickly verifying your examples work as expected @slimsag?

**Comment by tsenart** [comment] 2019-12-19 14:55
@rvantonder: Since @slimsag is now off on holiday, is there another way to verify this is no longer happening?

**Comment by rvantonder** [comment] 2019-12-19 16:24
I don't think this is a problem anymore, and can't reproduce. It is pre default literal search, so I think this was solved since. Closing, feel free to reopen if it can be reproduced.

**Closed by rvantonder** 2019-12-19 16:24 UTC
Labels: bug, customer, search, team/core-services
