### ISSUE TITLE
Code Insights: [BE] [FE] Create env feature flag for gql insight API

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#27838] opened 2021-11-17 13:45 UTC
## Context

We have to introduce an environment non-overridable feature flag to be able to switch our setting-based with gql API. At the moment we use setting cascade to store features flat but they all could be easily overridden which doesn't fit in our tech constraints of data migration.

How to create env feature flag with `jsContext` object.
1. Extend FE `jsContext` type https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/jscontext.ts
2. Extend GO struct with feature flag here https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/jscontext/jscontext.go?subtree=true
3. After that it should be possible to use `window.context.<our feature flag>` in any place within the app. 
4. Replace this line with `window.context.<feature flag>` statement https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/enterprise/insights/InsightsRouter.tsx?L57&subtree=true

**Comment by coury-clark** [comment] 2021-11-17 20:26
@vovakulikov To standardize on an environment variable name, I propose the frontend looks for the same environment variable that the background sync has:
https://github.com/sourcegraph/sourcegraph/issues/27306#issuecomment-971959785

To be clear, this is null (false) by default and will only fall-back to enabled if the environment variable is set true.

**Comment by felixfbecker** [comment] 2021-11-29 17:17
Duplicate of #27914

**Closed by felixfbecker** 2021-11-29 17:17 UTC
Labels: team/code-insights
