### ISSUE TITLE
Add a github action to notify us of unlabeled tickets/PRs

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#16672] opened 2020-12-11 17:44 UTC
In the past we've often missed contributions by external contributors since they don't know whom to tag and also cannot add labels, so they largely remain unnoticed. This has happened to campaigns a couple of times the last month where customers reported issues and we only followed up on them a couple weeks later.

We want to have some sort of action that searches for keywords.

Another possibility would be to have a bot that checks for contributor status and asks externals via a comment to tag one team out of a provided table with descriptions which might be a good fit to tag.

**Comment by chrispine** [comment] 2020-12-11 18:20
Is this a duplicate of #15929?

**Comment by chrispine** [comment] 2020-12-11 18:21
Also, how are other teams solving this? Surely we aren't the only team to experience this.

**Comment by eseliger** [comment] 2020-12-11 18:36
Ah, yeah might be 🤔 
I apparently wasn't sure what it was about in the past already: https://github.com/sourcegraph/sourcegraph/issues/15929#issuecomment-731583047 😬 

I think I would want to keep this one open as well, since it mentions a more general approach that other teams might hook into as well.
As far as I know it's an unsolved problem for other teams as well.

**Comment by chrispine** [comment] 2020-12-11 20:15
Well, I will close the other one, then. 😄

**Comment by eseliger** [comment] 2020-12-18 17:27
I've investigated this a bit and it doesn't seem like there is an action that does exactly what we want here. So I'll spend another afternoon writing our own action to do this probably, but I doubt I'll get this done this sprint so I'm moving it to the next :) Sorry!

**Comment by mrnugget** [comment] 2021-02-18 11:47
Fixed: https://github.com/sourcegraph/sourcegraph/issues/18424

Let's see how it works in practice. We might need to extend the checks a bit.

**Closed by mrnugget** 2021-02-18 11:47 UTC
Labels: estimate/1d, planned/CampaignsSprint7, team/campaigns
