### ISSUE TITLE
git blame error message when logged out of Sourcegraph

### ISSUE THREAD

**Issue by fierro-fuego** [sourcegraph/sourcegraph#2209] opened 2019-02-07 23:32 UTC
- **Sourcegraph version: Sourcegraph.com, browser extension v19.1.29.2106
- **Platform information: MacOS High Sierra 10.13.6, Chrome browser v72.0.3626.81

#### Steps to reproduce:
1. Install Sourcegraph chrome extension.  Be logged out of Sourcegraph.
2. Open any file in any repo on Sourcegraph.com (for example https://sourcegraph.com/github.com/gorilla/mux@master/-/blob/bench_test.go#L18)
4. Click "Blame" in upper right hand corner

#### Expected behavior:
Personally, I would expect the git blame info displayed inline regardless of being logged in or not. However, it seems the intended behavior is to actually display an error message.

#### Actual behavior:
Error message pops up with the following
"Unable to update setting git.blame.lineDecorations becau...
Sign into Sourcegraph"
<img width="1440" alt="screen shot 2019-02-06 at 12 46 30" src="https://user-images.githubusercontent.com/47435467/52449174-2a7c9680-2aeb-11e9-937f-91187d3661ce.png">

#### Problems
- The full error message is in the HTML, but the flex boxes are too small for this line of text, and the `text-overflow` property is set to ellipsis. 
- Clicking blame multiple times leaves multiple error popups stacked on top of each other. Not sure if this is intended behavior in a single file, but they also don't go away when navigating out of the current file.
- As a user, I'd prefer to see a simpler message such as "Log in to use blame feature", instead of "Unable to update setting git.blame.lineDecorations"

#### Cause
This paragraph's containing div (three levels up) has class .w-100, which makes the div take 100% of available width.  The containing div two more levels up has class .sourcegraph-notifications, which has a fixed width of 28rem
<img width="1196" alt="screen shot 2019-02-07 at 15 30 27" src="https://user-images.githubusercontent.com/47435467/52449777-5862da80-2aed-11e9-893d-63ad8bb353a7.png">

Thanks :)

**Comment by lguychard** [comment] 2019-08-30 09:49
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/2239

**Closed by lguychard** 2019-08-30 09:49 UTC
Labels: bug, code-nav, extensions
