### ISSUE TITLE
gitlab-org/gitlab ResolveRev errors with 504 Gateway Timeout on sourcegraph.com

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10960] opened 2020-05-25 15:40 UTC
E.g. on https://gitlab.com/gitlab-org/gitlab/-/blob/master/app/assets/javascripts/star.js
no "View on Sourcegraph" button or code intel is shown because the `ResolveRev` query times out:

![image](https://user-images.githubusercontent.com/10532611/82827134-aea88800-9eae-11ea-91fd-8302761365bf.png)

Repro in the API console: [Link](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20ResolveRev(%24repoName%3A%20String!%2C%20%24rev%3A%20String!)%20%7B%5Cn%20%20repositoryRedirect(name%3A%20%24repoName)%20%7B%5Cn%20%20%20%20__typename%5Cn%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20mirrorInfo%20%7B%5Cn%20%20%20%20%20%20%20%20cloneInProgress%5Cn%20%20%20%20%20%20%20%20cloneProgress%5Cn%20%20%20%20%20%20%20%20cloned%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20commit(rev%3A%20%24rev)%20%7B%5Cn%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20tree(path%3A%20%5C%22%5C%22)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20url%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20defaultBranch%20%7B%5Cn%20%20%20%20%20%20%20%20abbrevName%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%20%20...%20on%20Redirect%20%7B%5Cn%20%20%20%20%20%20url%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22operationName%22%3A%22ResolveRev%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22repoName%5C%22%3A%20%5C%22gitlab.com%2Fgitlab-org%2Fgitlab%5C%22%2C%5Cn%20%20%5C%22rev%5C%22%3A%20%5C%2257e3d968caeea7fc94233a8711a66e0eca108914%5C%22%5Cn%7D%22%7D)

**Comment by tsenart** [comment] 2020-05-26 08:33
@felixfbecker: I don't see a "View on Sourcegraph" button.

<img width="1417" alt="Screenshot 2020-05-26 at 10 31 00" src="https://user-images.githubusercontent.com/67471/82878749-38526700-9f3c-11ea-9e05-1b19d74959da.png">
<img width="1417" alt="Screenshot 2020-05-26 at 10 30 38" src="https://user-images.githubusercontent.com/67471/82878757-3c7e8480-9f3c-11ea-8e23-2373ced4c08e.png">

**Comment by tsenart** [comment] 2020-05-26 08:43
@keegancsmith: Getting a lot of these logs on dotcom, any clue how to debug?

```
Slow fetch/clone for exec request" repo=gitlab.com/gitlab-org/gitlab args="[rev-parse 57e3d968caeea7fc94233a8711a66e0eca108914^0]" duration=1m0.000931536s
```

**Comment by tsenart** [comment] 2020-05-26 08:45
Is this because we're recloning too frequently, and this repo is massive so it takes too long, and because the timeout hits, we never really reclone it?

**Comment by tsenart** [comment] 2020-05-26 08:57
@keegancsmith: https://ui.honeycomb.io/sourcegraph/datasets/gitserver-exec/result/oPNXB15g8wT

**Comment by keegancsmith** [comment] 2020-05-26 09:53
I investigated this quickly. Our EnsureRevision logic was kicking in and kicking off fetches against the repo. However, the fetch failed since we tried fetching revisions in pull requests but our fetch logic excluded the refs for PRs on GitLab. I think this constant fetching lead to GitLab metering our fetch. From monitoring I had a fetch running for ages, ran one manually and it was quick.

I can't remember what our EnsureRevision timeout is, but it's likely the same or higher than our cloudflare timeout. Hence the 504s. I have sent a PR which fixes the underlying cause of EnsureRevision failing. Hopefully that resolves the issue.

It will require rolling out a new gitserver. @tsenart can you shephard out a new gitserver once https://github.com/sourcegraph/sourcegraph/pull/10979 is merged?

**Comment by keegancsmith** [comment] 2020-05-26 10:14
Re-opening until #10979 is deploy to gitserver and we can confirm it is fixed.

**Comment by felixfbecker** [comment] 2020-05-26 10:18
Thanks for investigating @keegancsmith !

> @felixfbecker: I don't see a "View on Sourcegraph" button.

Just to be clear, the button is not being shown because `ResolveRev` fails. If `ResolveRev` worked, it would be shown.

**Comment by tsenart** [comment] 2020-05-26 10:48
@keegancsmith: I don't know what special steps are required in rolling out gitserver and couldn't find documentation in the handbook. Can you give me some direction?

**Comment by keegancsmith** [comment] 2020-05-26 11:57
> @keegancsmith: I don't know what special steps are required in rolling
> out gitserver and couldn't find documentation in the handbook. Can you
> give me some direction?

Go to CI for master and see the tag built for gitserver. Update
deploy-sourcegraph-dot-com to use that tag. Run

  kubectl -n prod apply -f base/gitserver/gitserver.StatefulSet.yaml

For an example where I did this see commit
430e0ec099a403b0b8d16f6c9083a9b3a9a17c1b

**Comment by tsenart** [comment] 2020-05-26 13:43
@keegancsmith: It seems we are already using insiders for gitserver, so I assume it's already rolled out?

**Comment by keegancsmith** [comment] 2020-05-26 14:02
> @keegancsmith: It seems we are already using insiders for gitserver, so I assume it's already rolled out?

Woah, I wonder when that change happened? I see it isn't the only
service that we have made that change. This is has some potentially bad
implication. The default ImagePullPolicy is IfNotPresent, which means if
a node already has "gitserver:insiders" it just runs that. So there is a
good change that we have nodes running different gitservers. And this
will only get worse as time goes on.

If we want to stick to insiders then we need to update the
ImagePullPolicy to AlwaysPull. This makes it a bit annoying to roll out
a new version, since you need some way to trigger a rollout (not sure if
k8s has a command for that now, in the past we used to bump a dumby
envvar).

Alternatively we should set this to a specific version like we do in
other places. I see we seem to mostly use `:insiders@sha256...` so maybe
lets do that?

cc @uwedeportivo who that change blames to.

**Comment by uwedeportivo** [comment] 2020-05-27 14:21
sorry, wasn't intentional.  probably some bad merge from upstream. i'll fix

**Comment by tsenart** [comment] 2020-06-01 09:25
Can't reproduce anymore with the link in the issue description so this seems fixed. Thanks @keegancsmith!

**Closed by tsenart** 2020-06-01 09:25 UTC
Labels: api, bug, dot-com, gitlab, team/core-services

**Comment by felixfbecker** [comment] 2020-06-01 09:28
Confirmed, thanks!
