### ISSUE TITLE
Firefox extension seems to be enabled everywhere

### ISSUE THREAD

**Issue by saveman71** [sourcegraph/sourcegraph#8299] opened 2020-02-06 15:18 UTC
I've noticed some CSS from the Firefox browser extension is conflicting with some CSS on unrelated website, where I don't remember enabling it.

It seems the content script is injected on every page I navigate, this doesn't respect the following quote from the documentation:

>By default, the Sourcegraph browser extension will only provide code intelligence on github.com. It needs additional permissions in order to run on other code hosts.

Is there something I missed?

![Screenshot from 2020-02-06 16-18-50](https://user-images.githubusercontent.com/1615426/73950519-58620a00-48fc-11ea-8f10-634843e2517b.png)

Even if I right click the extension and uncheck "Enable on this domain", it seems the script is still injected.

**Comment by unknwon** [comment] 2020-02-06 16:20
Thanks for your feedback!

Our @sourcegraph/web team will look into it ASAP. Assigning @lguychard to triage.

**Comment by lguychard** [comment] 2020-02-06 16:22
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/760

**Closed by lguychard** 2020-02-06 16:22 UTC
Labels: browser-extension, firefox

**Comment by saveman71** [comment] 2020-02-06 16:52
Okay, makes sense. I'll uninstall for now, sorry ^^"
