### ISSUE TITLE
Search feature request: Query syntax to search at a date (instead of revision)

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10820] opened 2020-05-19 17:05 UTC
Search insights need to execute queries at specific points in time in the past. To accomplish this, they currently execute a commit search like `repo:${repo} type:commit count:1 before:${before}` to find the latest commit at each date of interest, and then executes a GraphQL bulk-search for those commits with `repo:${repo}@${commit}`.

It would be great if instead of having to do this upfront, I could specify the date I want to search at in the search query, and have the backend do this logic. This could be faster because it avoids the extra HTTP request, especially because if I wanted to do this over multiple repositories I would have to do 1 commit search _per repo_.

Other use cases for this could be running search queries when you know a bug was introduced at a certain date, but you don't have the commit. Or you may want to look up a pattern/API usage that was used in some removed code (e.g. our discussions code) and you know that code is now deleted but was still present last year, so you can quickly run the search over the state of last December instead of first having to dig up the SHA of the parent of the commit that removed it. 

## Syntax

I imagine something like this:

```
repo:^github.com/sourcegraph/@~2020-05-01T00:00:00Z
```
i.e. instead of a revision, you could provide any valid ISO date string, maybe with a qualifier like `~` to indicate it is a datetime and not a rev. The backend would then search over the latest commit reachable from the default branch at that point in time (you could imagine a way to specify a different "starting" branch too, like `@somebranch~2020-05-01T00:00:00Z`, but that is only a nice to have).

### Comparison to git revision selection

In my research, I found git actually has a related revision selection syntax: You can select a revision by a date [by querying the reflog](https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#_git_reflog), like `git show master@{yesterday}`. The `{...}` here is the syntax for reflog queries. This is not exactly the same semantics because it queries the reflog, not the committer date, meaning the branch must have been checked out at that point in time at the revision. Since that is not given, the semantics the proposed syntax should have instead is to look for the most recent commit at that point in time by the committer date, i.e. basically the output of `git log --before=... --max-count 1` (which is what the commit search above accomplishes). So I think we should not reuse the same syntax.

The tilde `~` in git revision selection already can be used to specify the nth ancestor of a commit like `master~5`, I think it would be natural to overload it with support for passing a date string to mean "closest ancestor of the commit at this point in time". Note we don't currently any of git's revision selector syntax like `~` or `^`, so there wouldn't be conflicts, but it makes sense to make them similar for familiarity.

/cc @sourcegraph/search-platform

**Comment by rvantonder** [comment] 2020-05-19 19:53
Am in favor of the general capability. As far as syntax:

GH uses `author-date:YYYY-MM-DD` and `committer-date:YYYY-MM-DD` [ref](https://help.github.com/en/github/searching-for-information-on-github/searching-commits#search-by-authored-or-committed-date) and I'd be in favor of doing something similar. What do you think of this?

Mainly because the thing I'm opposed to is tacking (more) information onto anything in `repo:` filter. This because we interpret that field as regex, and the syntax is already awkward with putting anchors (which, e.g., conflict with `git` caret syntax, etc.) and escaping regex operators. I understand that tacking things like `~` onto the repo name feels natural but my concern is the decision is already made that `repo:` is a regex-interpretable string and that makes syntax support hard. I.e., if we can tease out properties to other filters (like time) we should. If `repo:` were a plaintext string (and easily parseable as such), I would be less opposed to embedding syntax in the `repo:` filter. As it stands, that its not the case, and we don't have an alternative solution where a repo string can be interpreted as a plain string.

I realize that there also exists ways of inspecting syntactic cues in `repo:` to try and do magic so that`~` syntax works. IMO we already do too much of this sort of thing and I would still recommend a separation.

**Comment by felixfbecker** [comment] 2020-05-19 20:30
Awesome to hear you support the general idea!

The link for GitHub points to GitHub commit search - note this proposal is for our text search, not commit search. For commit search, we already have `before:` and `after:` filters, which are equivalent to GitHub's `committer-date:` with `>`/`<`.
If we added a `before:` filter to text searches, I think it would communicate a slightly different (wrong) semantic. The _revision to search over_ is specified in the repo filter after the `@` token, so you could specify both a revision and a `before:` filter. `before:` would communicate to me "search over this revision, but blame each result and filter them to those committed before `before`". Git blaming every result of course would not be performant so we'd not actually have it do that, but instead do the proposed thing of "pick the closest reachable commit committed before this date and search at that revision" and basically discard the revision in the `repo:` filter. This may sound like it would be equivalent and yield the same results, but there are important nuances when you consider merge commits. Git blaming would include all lines committed on a merged feature branch prior to the `before` date, while selecting the commit by the date _before_ searching would only include commits from the main ancestor line, which is the desired behavior (i.e. it won't include changes that were not _merged yet at the time_, while git blaming would).

I understand your concerns about adding special tokens to regexp and would agree, but afaict we only use regexp for the repo part (everything before the `@`), not the revision (everything after the `@`). So even `^` currently has no meaning in the revision part. Using a regexp would be quite unexpected I think for commit hash shorthands (which should prefix-match, not substring-match) or git tags (`v3.1` should not match `v3.15`), so I'd foresee us to stay closer to git revision selector syntax and not regexes (maybe globs if we ever want to support branch patterns, but this proposal would not preclude us from doing that).
For reference, our docs: https://docs.sourcegraph.com/user/search/queries#repository-revisions
Example attempt to use a regex as revision: https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%40%5Ebext/+test&patternType=literal

To me it feels like the right place to put this is the revision selector, because it matches the semantic of _selecting the revision to search over_. It also allows to do things like extending the syntax to specify the "start" revision for the ancestor search, specifying multiple repos with different dates, or multiple revisions for the same repo, which would be awkward or impossible with multiple `before:` filters.

WDYT?

**Comment by keegancsmith** [comment] 2020-05-20 12:01
From a performance perspective, could you not structure your feature to use the git log output to find commits for dates? Each date query requires us to walk the  log. So by doing N date queries we end up with O(N^2) perf, but if you just ask for log instead we have O(N) perf.

**Comment by felixfbecker** [comment] 2020-05-20 12:31
The backend could probably do that, it would be great if it did that, and that is exactly why I am proposing to move this logic to the backend. But as long as it's happening in the client, fetching the entire `git log` for each repo over HTTP to the client, and then plucking out the commits would still not be performant because the network would take a long time to fetch the entire log (despite the traversal being O(N)). I think using Big O notation with _N = number of `git log` calls_ is not helpful here since fetching the entire git log over HTTP is slower than asking the backend, in one GraphQL request, to run 7 `git log`s and return only the 7 commits that matched each date. The bottleneck is the network - the `git log --before=... --max-count=1` on the backend is almost instant, and we only run that for a small N. But if I could ask the backend right in the query, as this proposal would enable, to find the commits matching the date for me it could theoretically do it in the optimized way you proposed (as long as it can recognize "this GraphQL request contains multiple search requests with date filters that I can resolve in one go"). Does that make sense?

**Comment by keegancsmith** [comment] 2020-05-20 15:50
What are the days, just the last 7? If so then this should be performant as is since 7 is small and just looking at the commits for the last 7 days should be fast.

Perf question: How often will you run this query? Will you run it over lots of repos at once?

As for the proposal, this sounds like a useful feature to have. You are right, we don't use regex's for the bits after '@' (but we do support git ref globs). Additionally `~` is acceptable since it is not allowed in git refs/hashes/refglobs.

I agree with Rijnard though. I think it was a mistake to support `repo:foo@rev` syntax. Rather we should of had a `rev:` filter. I wouldn't want to make this worse, so I would encourage specifying the date to be its own filter and making it somewhat consistent with any other date filters we have so our language is easier to remember.

**Comment by rvantonder** [comment] 2020-05-21 01:41
> The link for GitHub points to GitHub commit search - note this proposal is for our text search, not commit search.

I just mean this could be a separate parameter. Name TBA, but let's call it `pancake` for the purposes of this discussion. It can apply to text search and not commit search.

> If we added a before: filter to text searches, I think it would communicate a slightly different (wrong) semantic. The revision to search over is specified in the repo filter after the @ token, so you could specify both a revision and a before: filter. before: would communicate to me "search over this revision, but blame each result and filter them to those committed before before". [...]

Without getting too much into this, the high-level idea is that any semantics you want to ascribe to `repo:^foo$@~date` would be exactly the same for `repo:^foo$ pancake:date`. I.e., it doesn't have to be connected to a temporal meaning of `before` in the context of commit search. Maybe this means that we can call it `on:<date>` or `at:<date>`, but I leave this to you to think about :-). 

Two key points:

(1) we control what combinations of this parameter are valid. This control (both implementation, and how we think about it) is simplified by not tacking on certain string syntax of values. It essentially means we don't have to do as much prefix/substring processing on the value but can rather reason about checking validity and evaluation at the expression level after parsing.  It becomes easier enforce that `pancake` only works with supported `repo:` values (e.g. "you specified a time that is not compatible with the repo `@` revision"). This is not only valid for the backend, but also applies to complexity of frontend code for quickly surfacing suggestions like 'this query you have written is bogus, how about...'. 

(2) The `repo:foo@~date` syntax creates redundancy in the expression language because it string concats to all of `repo` rather than its own entity. With `and/or` queries, this syntax will impose expressions like `repo:foo@~date or repo:foo@~other-date` for the same repo. By using a separate expression this can instead be written `repo:foo (date or other-date)` and should simplify the evaluator implementation in the backend. In addition, if you had two different repos but want to use the same date, you have to do `repo:foo@~date and repo:bar@~date` whereas if this were separate it is simply `(repo:foo and repo:bar) date` or similar.

The underlying principle I'm following here is "if an expression-like thing in our query can be a separate expression,  it should be". Because there is a one-to-many relationship for `repo <-> many time values` (and likewise, `repo <-> revs` like Keegan points out), and soon a `many repo` <-> `many time values` with and/or expressions, entities like `rev` and `pancake` appear to be good ones to separate at the expression level.

**Comment by felixfbecker** [comment] 2020-06-01 17:55
If the `rev:` filter is separate, would I still be able to express a search over two distinct repos at two distinct revisions (coupled to their respective repo)? I.e. would it be possible to do `searchTerm ((repo:repo1 rev:rev1) OR (repo:repo2 rev:rev2))`? That is my only concern with a separate `rev:` filter, as long as that is solved that sounds good to me (although the query is a bit longer).

Regardless I think this is a separate discussion from the date query feature, and I'd be happy to have this feature in either way, you own the syntax :)
Would moving the rev into a separate filter significantly delay this feature? In general, do you have an idea where this feature could fit into your priorities time-wise?

**Comment by rvantonder** [comment] 2020-06-01 22:17
> Regardless I think this is a separate discussion from the date query feature

Agree. But to tie up this thread: yes, certainly the idea is that the query `searchTerm ((repo:repo1 rev:rev1) OR (repo:repo2 rev:rev2))` would work as is, as well as things like `searchTerm ((repo:repo1 (rev:rev1 OR rev:other-rev)) OR (repo:repo2 rev:rev2))` and additionally we may support regex or globbing syntax for `rev` in the above as well (so that we can support a semantics of pattern matching and not just a discrete set. This is tracked in #11213). All that said _we will not be deprecating_ the `repo:...@rev1:rev2` syntax any time soon and will continue to support it. If we do introduce `rev`, it will be as an alternative syntax, not a replacement, for the time being.

> Would moving the rev into a separate filter significantly delay this feature? 

So to my mind supporting `rev` is not on the critical path to supporting the date feature here. My only suggestion was that the date feature, when introduced, does not go into the `repo` value, but rather set using its own `date-or-whatever-name` field. We can deal with introducing `rev` later (though it's probably at the same level of importance based on current customer requests).

> In general, do you have an idea where this feature could fit into your priorities time-wise?

Not a promise, but I want to say we/I could start hacking on this to support it in 3.18 (caveating other priorities)--it would be experimental at first, but if I understand this is basically to enable better code insights so that seems quite fine. Timeline is based on what I'm working now, which is query processing migration in 3.17 and once that's in place this would be easier to introduce.

**Comment by daxmc99** [comment] 2020-07-13 18:01
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment] 2020-08-13 13:36
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by nicksnyder** [comment] 2020-08-24 15:23
@rvantonder I have moved this out of 3.19. Please place it in the correct milestone.

**Comment by felixfbecker** [comment] 2020-11-13 14:17
@rvantonder are there any updates on this? This would be really helpful to show off cross-repo search insights like https://github.com/sourcegraph/sourcegraph/issues/15585 where querying each repo from the client for the commits to search by date becomes unfeasible.

**Comment by rvantonder** [comment] 2020-11-13 18:57
So reading over this again, I can write a prototype, but I'd like your help to spell out the expected behavior here, because the description and desire is difficult to quickly page in.

- First example thing you want to do: "Search repo `foo` on date `XYZ`, where we can do that by resolving the latest commit on date `XYZ` and then search for `repo:foo rev:commit`".

- Follow on example thing you want to do: "Search repo**s** specified by some repo pattern `ABC` on date `XYZ`, where the backend resolves the latest commit on date `XYZ` for each respective matching repo `ABC`."

- The way that you'd be happy to "resolve the latest commit on date `XYZ`" is to use the output of `git log --before=DATE --max-count 1 `.

Does that match what you functionally expect?

Proposal: I will prototype this by introducing an `on` filter (I was previously thinking `at`, but `on` seems better). We can solidify this later. So your queries become:

`repo:foo on:2020-05-01 yo`

`repo:.* on:2020-05-01 yo`

Limitations/concerns: we clamp commit/diff search to 50 repos max on sourcegraph.com, which we will probably have to do in the case of a pattern like `repo:.*`. For customer instances, we do not clamp this, but performance could be real slow, but I think you realize that.

**Comment by felixfbecker** [comment] 2020-11-13 19:11
Yes, I think that's all correct (trying really hard to think of edge cases...).

> Limitations/concerns: we clamp commit/diff search to 50 repos max on sourcegraph.com, which we will probably have to do in the case of a pattern like repo:.*. For customer instances, we do not clamp this, but performance could be real slow, but I think you realize that.

If you're going through the backend, you wouldn't do the date->commit resolution through a search, right? I imagine you could use gitserver directly. I confirm that I realize that can still be slow if _a lot_ of repos are involved. Also limiting on cloud seems fine.

I imagine that if we need this to be performant down the line #11169 would eliminate this performance problem, but we don't need to wait for that, I think there is intermediate value we can provide and this work wouldn't be stop-gap work but additive.

**Comment by rvantonder** [comment] 2020-11-13 19:31
> If you're going through the backend, you wouldn't do the date->commit resolution through a search, right? I imagine you could use gitserver directly.

There is no way that I know of to ask gitserver "give me a repository at DATE" (or resolve some commit at DATE). We can currently only [resolve repos, and optionally at a specified revision](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/gitserver/protocol/gitserver.go#L14-22). I don't know how much of https://github.com/sourcegraph/sourcegraph/issues/11169#issuecomment-638904705 (CC @tsenart) we need. So until then, I'd probably resolve date to a commit with a git command, yep. 

I don't see any inherent optimizations we can make on the backend, but it'll save the round trips and lookup logic on the client. I think `on` is a useful primitive to have in the backend/express in a query, which is why I'm in favor of adding this. We can optimize for it as we make progress with backend things.

**Comment by camdencheek** [comment] 2024-02-22 21:11
cc @sourcegraph/search-platform, reassigned this to your team. I do still think this is still relevant and likely worth doing. From the language side of things, we could support this with a predicate like `rev:branch.at.date(main, 2020-01-01)` or something.

**Comment by camdencheek** [comment] 2024-04-17 17:16
Oh! Yes, I think we can. Forgot this existed -- thanks!

**Closed** 2024-05-21 15:24 UTC
Labels: feature-request, team/search-platform
