### ISSUE TITLE
New search bar doesn't scale with browser window

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#8851] opened 2020-03-06 14:12 UTC
- **Sourcegraph version:** k8s.sgdev.org
- **Platform information:** Firefox 73.0.1 

Go to k8s.sgdev.org, resize the window to be relatively small, but not "mobile small". The right side of the search bar is hidden, along with the user menu, etc.

See GIF:

![search_bar_resize](https://user-images.githubusercontent.com/1185253/76090906-c57cc400-5fbc-11ea-9048-7b65aba48cfc.gif)

**Comment by lguychard** [comment] 2020-03-23 14:55
Duplicate of #7692

**Closed by lguychard** 2020-03-23 14:55 UTC
Labels: bug, search, team/web, webapp
