### ISSUE TITLE
Re-merge Stephen's refactor to search

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3242] opened 2019-04-05 04:14 UTC
Diff searches are omitting results that should exist. They are also being nondeterministic.

- https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+types+f:package.json+type:diff shows "No results"
- https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:package.json+type:diff sometimes shows results, sometimes it shows "No results"

This appears to have been a recent regression because the query https://sourcegraph.com/search?q=repo:sourcegraph/sourcegraph+http.%28Transport%7CRoundTripper%29+type:diff+author:keegan was returning results 100% reliably at dotGo on 2019 Mar 25. (It was part of our demo path.)

**Comment by ijt** [comment] 2019-04-05 14:14
@slimsag , do you think this might have something to do with your recent refactoring?

**Comment by ijt** [comment] 2019-04-05 16:22
It works fine with `dev/launch.sh` on my laptop. Maybe it's something to do with how sourcegraph.com is configured.

**Comment by ijt** [comment] 2019-04-05 16:36
It also works fine with an instance running like this on my laptop:
```
docker run --publish 7080:7080 --publish 2633:2633 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.2.0
```

**Comment by ijt** [comment] 2019-04-05 16:41
The query "repo:sourcegraph/sourcegraph http.(Transport|RoundTripper) type:diff author:keegan" also works fine with the local `docker run` instance.

**Comment by ijsnow** [comment] 2019-04-05 17:11
I think we should start by reverting https://github.com/sourcegraph/sourcegraph/commit/a08c7063fe8afd87b1581754d07b6b4b86e96d74

**Comment by ijsnow** [comment] 2019-04-05 17:17
If you note the difference between the links in the repro, we have problems when we add something to search in the diff. i.e. the link that works doesn't actually search any diffs, it essentially just grabs diffs in the correct repo. The link that doesn't work has a query field to search inside the diffs. The weird thing to me is that it is immediately failing. I added `after:"1 year ago"` and it immediately returns no results.

**Comment by slimsag** [comment] 2019-04-05 17:19
I'll fix or revert before EOD. I know what is happening

**Comment by ijt** [comment] 2019-04-05 17:53
I think it hasn't been reproducing for me locally because the latencies for services talking to each other aren't high enough on my laptop. It seems likely that the issue shows up when the services are on different machines.

**Comment by ijt** [comment] 2019-04-05 18:07
I reopened this because we haven't verified that reverting #3022 fixes it.

**Comment by slimsag** [comment] 2019-04-05 18:29
Sourcegraph.com is now running your reversion fix: https://sourcegraph.com/site-admin/updates

**Comment by slimsag** [comment] 2019-04-05 18:31
Indeed it looks like that resolved the issue for now. I'm not sure why, I'll need to investigate further. I'll keep this issue open for that.

**Comment by slimsag** [comment] 2019-04-13 02:27
I won't land this change in 3.3, will do so in 3.4 most likely.

**Comment by slimsag** [comment] 2019-05-14 02:58
Was going to re-land this but honestly at this point it will likely need to be completely redone due to conflicts, so closing for now.

**Closed by slimsag** 2019-05-14 02:58 UTC
Labels: search
