### ISSUE TITLE
binary assets turn up in search results, do not render cleanly

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2198] opened 2019-02-07 18:24 UTC
I added a bunch of random trending github repos to my instance and one had binary assets like images, they turned up in search results and rendered poorly. We should exclude them from search results:

![image](https://user-images.githubusercontent.com/3173176/52433701-e2e61280-2aca-11e9-90ad-939178ab3f32.png)

**Comment by keegancsmith** [comment] 2019-02-08 12:05
What search did you use? I'd be surprised if we match inside of binary files since we should be explicitly excluding them. However, we may just match on the filenames.

**Comment by sqs** [comment] 2019-04-25 00:01
The expected behavior for matched binary files that we can't render is to just show the file header and no container for contents.

**Comment by malomarrec** [comment] 2021-04-19 19:43
Tagging similar issue in #20158 to feed into prioritisation work.

**Comment by fkling** [comment] 2021-06-01 09:22
If this issue is about only rendering the file header, then it doesn't look like to still be an issue. https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+icon-active&patternType=literal renders as

![2021-06-01_09-20](https://user-images.githubusercontent.com/179026/120299576-6a26a800-c2cb-11eb-9487-cf38240bf165.png)

which looks right to me?

Rendering image previews seems to be tracked in a separate issue: https://github.com/sourcegraph/sourcegraph/issues/8387

**Comment by fkling** [comment] 2021-06-02 09:55
And the redesign changes this even more, so I'm going to close this as not relevant anymore.

**Closed by fkling** 2021-06-02 09:55 UTC
Labels: bug, team/search
