### ISSUE TITLE
Search URLs with `case:true` fail

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#8719] opened 2020-03-02 11:27 UTC
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** sourcegraph.com

#### Steps to reproduce:

1. Navigate to https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph%2Fsourcegraph%24+case:yes+-file:package%28-lock%29%3F%5C.json%7Cyarn%5C.lock+yarn-deduplicate

#### Expected behavior:

It shows search results

#### Actual behavior:

The query fails with an error, that seems wrong, since the search bar only shows `case:yes` once, in the actual api request, it is duplicated indeed though.

![image](https://user-images.githubusercontent.com/19534377/75672397-fb4e3f80-5c80-11ea-9099-9cbd9170c785.png)

**Comment by felixfbecker** [comment] 2020-03-03 08:53
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/8723

**Closed by felixfbecker** 2020-03-03 08:53 UTC
Labels: bug, team/web, webapp

**Comment by eseliger** [comment] 2020-03-03 13:31
technically, #8723 is the duplicate 😬
