### ISSUE TITLE
Searching for "Resource" in Kubernetes buries result

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#19911] opened 2021-04-11 19:25 UTC
Repro:
- I want to find [`func Resource`](https://pkg.go.dev/k8s.io/kubernetes/pkg/apis/core#Resource) in the Kubernetes codebase.
- Go to the Kubernetes repository on Sourcegraph and [search for `type:symbol Resource`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+type:symbol+Resource&patternType=literal)

Result: the top results are all partial matches in a vendored dependency:
![image](https://user-images.githubusercontent.com/1646931/114318042-f2ed4880-9abf-11eb-80df-0c39ff648c6e.png)

I can refine my search by [filtering out the `vendor/` directory](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+type:symbol+Resource+-file:vendor&patternType=literal) (note: a new user wouldn't know how to do this), but I still get noise:

![image](https://user-images.githubusercontent.com/1646931/114318100-48c1f080-9ac0-11eb-87e2-ec0a95c67b61.png)

I try [`repo:^github\.com/kubernetes/kubernetes$ type:symbol core.Resource -file:vendor`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+type:symbol+core.Resource+-file:vendor&patternType=literal) and get no results, timing out after 21s:

![image](https://user-images.githubusercontent.com/1646931/114318126-6d1dcd00-9ac0-11eb-8bff-fb10d1b1818c.png)

I try a regex search [`repo:^github\.com/kubernetes/kubernetes$ type:symbol \bresource\b -file:vendor`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+type:symbol+%5Cbresource%5Cb+-file:vendor&patternType=regexp). There are a lot of matches for "resource", but at least this shows me the whole-world matches.

![image](https://user-images.githubusercontent.com/1646931/114318249-2086c180-9ac1-11eb-90f1-1fdb329f625f.png)

Each new search is now taking 15-20s to complete for some reason.

I try a text search with a file path filter: [`repo:^github\.com/kubernetes/kubernetes$ func Resource file:core`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/kubernetes/kubernetes%24+func+Resource+file:core&patternType=literal&case=yes). This takes 15s, but it gives me what I want:

![image](https://user-images.githubusercontent.com/1646931/114318286-575cd780-9ac1-11eb-95b2-12c6ee590ed2.png)

If I didn't intend to keep trying until I was able to find what I want, I probably would have given up after the 2nd or 3rd search.

Our search query language is super powerful, but it seems to me there are a lot of UX issues that can derail the user along the way. If users can't consistently get to what they want easily inside a few seconds using our product, they're not going to come back to us again and again to find the answers they're looking for.

**Comment by rrhyne** [comment] 2021-04-12 18:48
This is great, thanks for documenting. I see several issues here:

* you started with the proper repository... many users struggle here. 
  * repo: autocomplete is slow 
  * repo: autocomplete results are not ranked
  * defining a specific repo query manually is difficult  
* you started with type:symbol... most users will not have that concept
* Lack of ranking (in this case of individual file results, not just repositories) @rmmh 
* need to understand dynamic filtering (vendor, test) to overcome the above
* understanding negation as a filter concept
* performance = ux


I'm curious... you started with type:symbol (which doesn't show code) and ended up with a string `func resource`. What made you stop trying to use the type:symbol filter? Did you need to see the code to make a proper determination of correctness?  Did the proper symbol not rank as highly in the results?

You also added a specific file filter,  `file:core`. How did you decide you needed to add that filter? Did you see the path `core` in previous results and decide to filter for it, or is this knowledge of the code base?

Was there a single file / function on the final page that was the desired result or were you looking for all instances of `func Resource`.

**Comment by beyang** [comment] 2021-04-21 15:06
> What made you stop trying to use the type:symbol filter? Did you need to see the code to make a proper determination of correctness? 

I wanted a symbol that was a function, and we don't have a way to specify that (no `type:func`).

> You also added a specific file filter, file:core. How did you decide you needed to add that filter? Did you see the path core in previous results and decide to filter for it, or is this knowledge of the code base?

IIRC, I saw the path "core" in previous results and decided to filter it.

> Was there a single file / function on the final page that was the desired result or were you looking for all instances of func Resource.

There was a single thing I was looking for (where Kubernetes defines the type for a Kubernetes resource), though it's possible there are multiple such types that map to the same logical concept, in which case, I'd want to see all of them and select which one is the one I actually want.

**Comment by camdencheek** [comment] 2024-02-22 23:11
Closing since ranking has since been significantly improved and I can no longer reproduce this bad ranking.

**Closed by camdencheek** 2024-02-22 23:11 UTC
Labels: ux, team/search-product, public-code, team/code-search, imported
