### ISSUE TITLE
insights: `case` searches are not respected in aggregation

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#41120] opened 2022-08-31 12:51 UTC
the parameter isn't passed in to the searchQueryAggregate query. 

steps to reproduce:
* [run a search with case:yes](https://k8s.sgdev.org/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+file%3Aweb+file%3AInsight++lang%3AtypeScript&patternType=standard&case=yes&groupBy=PATH)
* observe search results are case sensitive
* observe aggregation results are not
* observe aggregation graphql query does not contain `case:` parameter

/cc @joelkw @felixfbecker @vovakulikov @unclejustin

**Comment by leonore** [comment] 2022-08-31 13:08
when writing `case:yes` or `case:no` it is automatically set to the UI toggle and removed from the query so the issue might be coming from there. the query sent to stream search still contains the case field

**Comment by unclejustin** [comment] 2022-08-31 14:58
`case` is getting parsed out here: https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/web/src/stores/navbarSearchQueryState.ts?L77:5

We will need to add a `caseSensitive` parameter to `searchQueryAggregate` to pass along the value.

**Comment by felixfbecker** [comment] 2022-08-31 15:17
@leonore is this a duplicate of https://github.com/sourcegraph/sourcegraph/issues/41018?

**Comment by felixfbecker** [comment] 2022-08-31 16:01
So is this issue only about the drilldown functionality?

Sorry I can't fully follow the reproduction steps – what does "observe aggregation results are not" mean/what is being grouped by? In my mind you can only observe aggregation results being case insensitive in the sidebar when grouping by capture group (which would be https://github.com/sourcegraph/sourcegraph/issues/41018)

**Comment by leonore** [comment] 2022-08-31 16:09
> So is this issue only about the drilldown functionality?

the other issue is about reconciling behaviour in aggregation results vs drilling down, in my opinion. Which might end up not being required once this is fixed

> Sorry I can't fully follow the reproduction steps – what does "observe aggregation results are not" mean/what is being grouped by? In my mind you can only observe aggregation results being case insensitive in the sidebar when grouping by capture group (which would be #41018)

To be more specific:
1. Run this search, for example: https://k8s.sgdev.org/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fsourcegraph%2Fsourcegraph%24+file%3Aweb+file%3Acodeinsightsrouter++lang%3AtypeScript&patternType=standard&case=yes&groupBy=PATH 
2. (This isn't a capture group query)
3. See that we get an aggregation result, even if we don't get any search results. That's because aggregations don't respect case arguments at the moment

**Closed** 2022-09-05 16:54 UTC
Labels: bug, webapp, team/code-insights, insights-search-aggregation-4.0
