### ISSUE TITLE
Many repositories on GitLab may cause scaling issues with permissions

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#2056] opened 2019-01-29 16:57 UTC
If someone is using Sourcegraph and [repository permissions](https://docs.sourcegraph.com/admin/repo/permissions) with GitLab, and they have many (~10,000+) GitLab repositories, then it may be very slow. The slow operation would be querying the GitLab API for all repositories visible to a user, and doing that for each user on demand.

@beyang 	What is your assessment here? Would this indeed be slow? (I'm not familiar with the code to answer this.) Would it be fast after the initial computation? Is it possible to make it faster?

**Comment by beyang** [comment] 2019-01-29 17:17
Closing as dupe of https://github.com/sourcegraph/sourcegraph/issues/2007. I've a WIP branch to fix this issue.

**Closed by beyang** 2019-01-29 17:17 UTC
Labels: auth, repos
