### ISSUE TITLE
JavaScript: References not found on module.exports = { foo } 

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#524] opened 2018-10-25 17:06 UTC
- **Sourcegraph version:** Sourcegraph.com
- **Platform information:** macOS Mojave, Chrome 70.0.3538.67

#### Steps to reproduce:

![js find-references](https://user-images.githubusercontent.com/133014/47517537-54ac9000-d83d-11e8-82c3-dc639cfbf358.gif)

#### Expected behavior:

Local references would be found for https://sourcegraph.com/github.com/semantic-release/semantic-release/-/blob/lib/git.js#L121:16

#### Actual behavior:

References are found only for https://sourcegraph.com/github.com/semantic-release/semantic-release/-/blob/lib/git.js#L196:3

**Comment by KattMingMing** [comment] 2018-10-25 17:10
When calling `textDocument/references` from the definition no references are found. Also calling jump to `definition` will often return: 
![screenshot 2018-10-25 10 05 24](https://user-images.githubusercontent.com/4897310/47517735-0c41a200-d83e-11e8-93a9-f012c76bf874.png)

cc/ @felixfbecker - Any idea?

Also, I think this should be filed on the language server itself unless the issue is actually happening because of Sourcegraph.

**Comment by sqs** [comment] 2018-10-25 19:15
Assigned to @felixfbecker 	to investigate next month as he works on better TS/JS support. If he finds this is not supported by the underlying TSServer, then we will just defer to upstream and close this issue.

Filed the "Error finding definition" bug separately in https://github.com/sourcegraph/sourcegraph/issues/526

**Comment by felixfbecker** [comment] 2018-12-12 22:14
This is not fixed in the new TS support

**Comment by nicksnyder** [comment] 2018-12-14 19:00
> This is not fixed in the new TS support

Did you mean "this is _now_ fixed"?

It works for me https://sourcegraph.com/github.com/semantic-release/semantic-release@89ad3a0b61d2edeeeaf53e3885407304eca7504e/-/blob/lib/git.js#L121:16&tab=references

**Comment by felixfbecker** [comment] 2018-12-14 19:02
No, I meant it is _not_ fixed. References to `verifyAuth` in other files are not found.

**Comment by nicksnyder** [comment] 2018-12-14 19:13
The original issue was specifically about local references, which weren't found (and now they are).

**Comment by felixfbecker** [comment] 2018-12-17 20:54
I think @ryan-blunden  ment "same-repository" with "local". Same-file references were already shown before.

**Comment by felixfbecker** [comment] 2018-12-17 20:54
I am going to close this as wont-fix though because this is the same behaviour as VS Code / native tsserver.

**Closed by felixfbecker** 2018-12-17 20:54 UTC
Labels: bug, feature:code-intel
