### ISSUE TITLE
Searcher describes gitserver failing to clone repo as archive corruption error

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3798] opened 2019-05-02 21:12 UTC
When gitserver is failing to clone a repository, searcher propagates that error up to the user and presents it as if there is a corrupt archive on disk somewhere:

```
failed to copy and close missing archive cache item: archive/tar: invalid tar header
```

In reality, gitserver is just failing to produce a tar archive because the repo can't be cloned. The error message should indicate this because as an admin it is VERY difficult to debug this situation.

To reproduce this, you will just need to add a repo to sourcegraph then take down your codehost so that gitserver can't clone it (in my case, bitbucket server):

```
docker logs gitserver-16 2>&1 | grep 'ssw-scientific--nndd'
t=2019-05-02T20:20:21+0000 lvl=info msg="recloning expired repo" repo=50.112.230.151/TEST/ssw-scientific--nndd
t=2019-05-02T20:20:24+0000 lvl=eror msg="error running cleanup command" name="maybe reclone" repo=/data/repos/50.112.230.151/TEST/ssw-scientific--nndd/.git error="error cloning repo: repo 50.112.230.151/TEST/ssw-scientific--nndd (http://slimsag:<redacted>@10.0.0.34:7990/scm/test/ssw-scientific--nndd.git) not cloneable: exit status 128 (output follows)\n\nfatal: unable to access 'http://slimsag:<redacted>@10.0.0.34:7990/scm/test/ssw-scientific--nndd.git/': Failed to connect to 10.0.0.34 port 7990: Host is unreachable\n"
```

cc @sourcegraph/code-search

**Comment by ijsnow** [comment] 2019-05-06 22:41
I'm unable to reproduce this with the following steps:
1. Run `dev/launch.sh`
2. Set up code host: `go run dev/fakehub/main.go -addr 127.0.0.1:3434 $GOPATH/src`
3. Get external service config from http://127.0.0.1:3434/ and add it at http://localhost:3080/site-admin/external-services/new?kind=other
4. Wait for repositories to clone
5. Kill fakehub process
6. Wait to see errors from gitserver trying to re-clone repos
7. Try to search over a repo you saw in an error message

After these steps, I see search results from the existing clone. If I:
- run `rm -rf /tmp/searcher-archives` to remove the cache, I still see results
- run `rm -rf ~/.sourcegraph/repos` to remove repos from gitserver, I see "no results" in the UI

**Comment by ijt** [comment] 2019-05-07 21:43
Moving this off 3.4 due to lack of repro.

**Comment by keegancsmith** [comment] 2019-05-21 13:22
See my comment here https://github.com/sourcegraph/sourcegraph/issues/3799#issuecomment-494388349

My best guess as how this can possibly happen is some caching. I'll see if my guess is correct (I'm not as familiar with the search code as I used to be).

**Comment by keegancsmith** [comment] 2019-05-24 06:51
See my comment here https://github.com/sourcegraph/sourcegraph/issues/3799#issuecomment-495493001

The underlying issue has nothing to do with failing to clone. The repository in question triggers a bug in git archive causing it to generate bad archives. https://github.com/sourcegraph/sourcegraph/pull/4184 adds a workaround to ignore these repositories for now.

Does this ever happen at a customer? I'd be surprised, since my best guess as to why this bug is being triggered is commit metadata containing malformed unicode (see the repo in question). As such I am closing this issue out.

**Closed by keegancsmith** 2019-05-24 06:51 UTC
Labels: bug, release-blocker, search
