### ISSUE TITLE
Slow Precise Code-Intel Tooltips in C/C++ Code

### ISSUE THREAD

**Issue by tistru** [sourcegraph/sourcegraph#13733] opened 2020-09-09 23:37 UTC
Reporting Customer: https://app.hubspot.com/contacts/2762526/contact/25700601

- **Sourcegraph version:** 3.19

#### Steps to reproduce:

1. Find a public repo that has c/cpp code and has lsif uploaded. For example: https://sourcegraph.com/github.com/protocolbuffers/protobuf@f5bdd7cd56aa86612e166706ed8ef139db06edf2/-/tree/src/google/protobuf/compiler/cpp
2. Open a .cc/.cpp/.hpp file and hover over several identifiers. Observe that the time it takes to populate the code-intel tooltip ranges from instant  to >10s

#### Expected behavior:
TIme to load the tooltips should be near instant (within a few seconds)

#### Actual behavior:
See sporadic cases where the time to load the tooltip can take upwards of 60s. In the worst case, it never loads at all and the spinning icon remains with an eventual gateway timeout HTTP error in the browser dev tools.

**Comment by efritz** [comment] 2020-09-10 18:04
It turns out the slow hover tooltips were due to eagerly transforming a large payload in the code intel extension. While this extension runs in a webworker, it can still block calls to _itself_, which means that the UI is effectively unresponsive during this time.

The issue is that the Ranges request returns 20MB of content (I think choice of language exacerbates how _full_ a range request result will be), and on response the extension has to convert the structure into something that it wants to return to the extension host. The call to [`rangesResponseToCodeIntelligenceRangeNodes`](https://github.com/sourcegraph/code-intel-extensions/blob/master/shared/lsif/ranges.ts#L306) is what is causing this slowness.

**Comment by efritz** [comment] 2020-09-10 18:33
https://github.com/sourcegraph/sourcegraph/pull/13746 should help all 3.20+ instances. https://github.com/sourcegraph/code-intel-extensions/pull/483 and https://github.com/sourcegraph/code-intel-extensions/pull/484 should help all instances (including pre-3.20).

**Comment by efritz** [comment] 2020-09-10 19:50
Behavior seems better. Closing unless there's evidence otherwise 🎉

**Comment by gbrik** [comment] 2020-09-30 19:23
re-opening as a user reported that this is still an issue on a 3.20.1 instance @efritz

**Comment by tistru** [comment] 2020-10-07 19:54
cc @keegancsmith 

Update: The customer was able to reproduce this issue with lsif disabled. This indicates that the root cause is not in the lsif code specifically but does seem to be consistent with C++ code using either basic or precise code intelligence. Results are still inconsistent meaning that one file may not showing consistent latency for specific objects in the code. Example: one function definition may take 20s to show but closing the file and reopening to hover over the same object may display instantly. Customer also noted that there seems to be a "caching system in place" as evidenced how subsequent searches appear faster than the initial search.

Also, with lsif data uploaded but tested on a file that defaulted to search based results, the result provided the following stack trace from the frontend:



When | Elapsed (s) | Completed Requests
2020/10/07 18:19:49.068323 | 19.980490 | query: TextPatternInfo{"^IsEmpty$",re,case,nocontent,nopath,filematchlimit:30,F:"\\.(c\|cc\|cpp\|cxx\|hh\|h\|hpp\|ino\|m)$"}, numRepoRevs: 1
18:19:49.068327 | .     4 | ... parent: graphql.SearchResults
18:19:49.068504 | .   177 | ... searchErr:<nil> error.object:<nil> overLimitCanceled:false
18:20:09.048794 | 19.980289 | ... repo:<reponame> repoErr:context deadline exceeded timeout:true temporary:true

**Comment by tistru** [comment] 2020-10-12 18:36
Update from @keegancsmith:

> In 2 of the traces the customer provided we are doing unindexed symbol requests for it. They are hitting the symbols service, and the symbols service times out after 15s waiting to fetch a copy of the commit. 15s is a long time, so normally indicates a very large repo.
> 
> There is a trace where precise-code-intel is slow. On the critical path (before speaking to precise code intel service) there is a 8s long call to git log --all --pretty=%H %P and 15s spent in store.fix-commits (6s of which is running SQL). I am assuming you will find that trace very interesting.

> I don't have a next step here. The hovers are on a specific commit, which doesn't seem to be indexed. We don't have a good solution here for large repos




Also, we learned that they are testing a codebase with roughly 20 million LOC and ~230000 total commits. There doesn't appear to be an easy solution around performance issues when searching very large repos with unindexed search.

**Comment by justdueck** [comment] 2020-11-05 22:17
Adding to this to report that the customer recently provided some new info and is still experiencing this issue. Per the customer: "Looks like the JS on the page is confused about the location of various identifiers: the query itself is for the same wrong identifier that is later shown in the pop-up." See relevant screen cap here: https://drive.google.com/file/d/1ogNKV1Dgb-uXf5At0wKmag_UKvZ570Xy/view?usp=sharing

They have deployed on Docker Compose in GCP and are running 3.21.2 and are still seeing incorrect tooltip data after the upgrade. 

Is there anything we can do on the CE end to help gather information to diagnose this?

**Comment by efritz** [comment] 2020-11-10 19:15
Fixed by https://github.com/sourcegraph/code-intel-extensions/pull/524 (slow tooltips seemed to be caused by not having any data at the current cursor position in a stale file).

**Comment by efritz** [comment] 2020-11-10 19:15
Fixed by https://github.com/sourcegraph/code-intel-extensions/pull/524 (slow tooltips seemed to be caused by not having any data at the current cursor position in a stale file).

**Closed by efritz** 2020-11-10 19:15 UTC
Labels: in progress, lsif-clang, team/code-intelligence
