### ISSUE TITLE
Find lines of code in a repo/directory via API and UI

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1235] opened 2018-12-05 04:52 UTC
### Feature request description

Requested by a user at a customer:

>Hi, is there a way to get the number of lines of code in a repo via the API?

### Additional context

An alternative solution (or additional feature, depending on need) would be displaying this information in the UI via a Sourcegraph extension. Perhaps displaying output from https://github.com/boyter/scc in a given repo or directory on repo and directory pages.

### UI 
As a user who is not familiar with all of the repositories and who needs to review all code in multiple repositories, I want to be able to see the relative sizes of repositories. This will help me know how to divide up the work among my team and how to schedule the work.

https://github.com/AlDanial/cloc

Requested by @P3GLEG

**Comment by andymaule** [comment] 2018-12-05 16:59
We're actually interested in doing this in an automated way, so it would need to be via the API because we don't have the CLI on the boxes that do the automation.

**Comment by andymaule** [comment] 2018-12-05 19:17
Yeah, those heuristics seem fine. We're most interested in source code for a particular language. We use the repo language feature, so it'd be great if Linguist could also list LoC per language, instead of just the language, but I'm not sure how feasible that is.

**Comment by dadlerj** [comment] 2019-06-13 15:47
Partial overlap with https://github.com/sourcegraph/sourcegraph/issues/1517 @christinaforney

**Comment by christinaforney** [comment] 2019-06-17 16:54
Expanding this to include UI components from #1517.

**Comment by keegancsmith** [comment] 2019-07-12 14:39
Oops, I didn't notice this being added to the 3.6 milestone. It won't make it into branch cut. @christinaforney we can discuss this issue when we plan for 3.7.

**Comment by tsenart** [comment] 2019-12-18 10:52
Duplicate of #2587

**Closed by tsenart** 2019-12-18 10:52 UTC
Labels: api, feature-request, team/core-services
