### ISSUE TITLE
Codecov extension throwing 500s

### ISSUE THREAD

**Issue by emchap** [sourcegraph/sourcegraph#34131] opened 2022-04-19 16:38 UTC
- **Sourcegraph version:** 3.38.1, but this has been happening for months on different versions
- **Platform information:** Demo; I use Firefox but most of the team does not and has reported the same issue

#### Steps to reproduce:

1. Go to https://demo.sourcegraph.com/github.com/sourcegraph/sourcegraph@947423ea4f32fe4766d406b4ad1dff08407a1e20/-/blob/enterprise/internal/authz/github/authz.go?L40-65
2. The codecov integration will just fail to load about 60% of the time. Refreshing sometimes helps, waiting sometimes helps. 

Console showed a bunch of 500s when I last ran into this on 2022-04-19:

![image](https://user-images.githubusercontent.com/9934079/164052648-639f4974-074f-4a07-866f-e50efbe95543.png)

See also:

- https://sourcegraph.slack.com/archives/C0W2E592M/p1650384459379199
- https://sourcegraph.slack.com/archives/CU93UDUBV/p1649925764698179?thread_ts=1649924948.996879&cid=CU93UDUBV
- https://sourcegraph.slack.com/archives/C01JKF7KUBD/p1644425995140739?thread_ts=1644424693.113579&cid=C01JKF7KUBD
- https://sourcegraph.slack.com/archives/C01JKF7KUBD/p1644424693113579
- https://sourcegraph.slack.com/archives/C022SPMNR0W/p1643673077560749
- https://sourcegraph.slack.com/archives/C01JKF7KUBD/p1638309761013700?thread_ts=1638309450.007700&cid=C01JKF7KUBD
- 

#### Expected behavior

Consistently loads.

#### Actual behavior:

Regularly fails to load.

**Comment by sourcegraph-bot-2** [comment] 2022-04-19 17:00
Heads up @muratsu @jjinnii @ryankscott - the "team/integrations" label was applied to this issue.

**Comment by taras-yemets** [comment] 2022-05-19 12:57
Hey @emchap!
I tried it a couple of times on the latest Sourcergaph version and on 3.38.1 in Chrome and Firefox and it seems to work fine for me 🤔 
Is it still reproducible on your end?

**Comment by emchap** [comment] 2022-05-19 17:58
@taras-yemets Seems to be consistently loading on that page currently.

@sourcegraph/customer-engineering Is codecov still erroring out for y'all?

**Comment by christinelovett** [comment] 2022-05-19 18:43
Yes errors out for me

**Comment by alexfogg** [comment] 2022-05-19 18:48
Same for me

<img width="1417" alt="Screen Shot 2022-05-19 at 2 48 09 PM" src="https://user-images.githubusercontent.com/2609466/169377314-e6e82e6d-1d7d-448f-a8af-3aef6f002d5d.png">

**Comment by yowayb** [comment] 2022-05-20 07:50
It errors out for me intermittently

**Comment by taras-yemets** [comment] 2022-05-20 09:25
Thank you for your feedback @christinelovett, @alexfogg, @yowayb!
Which version of Sourcegraph do you use?

**Comment by yowayb** [comment] 2022-05-20 09:30
sourcegraph.com Version: 148472_2022-05-19_e8a56b922f79

**Comment by yowayb** [comment] 2022-05-22 15:20
Sorry, I was mistaken.  I'm seeing something different.  I'm opening a file without test coverage, but the icon hover says "inactive" while the console says "13594-sourcegraph-codecov.js?cflgdo2l6kyg--sourcegraph-codecov:407 No Codecov coverage found for..." which explains it, but "inactive" on hover, made me think the extension was not enabled.

**Comment by taras-yemets** [comment] 2022-05-23 16:02
Thank you for clarification, @yowayb!
Can you confirm that codecov extension works for you on the file with test coverage (for example, [the one from the issue description](https://demo.sourcegraph.com/github.com/sourcegraph/sourcegraph@947423ea4f32fe4766d406b4ad1dff08407a1e20/-/blob/enterprise/internal/authz/github/authz.go))?

**Comment by taras-yemets** [comment] 2022-05-24 10:14
It looks like we're facing some kind of a sync timeout on the codecov.io side.

When we open any file on Sourcegraph (or on the code host using the browser extension) and have codecov extension enabled, we try to fetch commit coverage data for the latest commit on the current branch. If the latest commit was added recently, it may have not been processed on the codecov.io side yet.

For example, when we request coverage data for a certain commit (https://codecov.io/api/gh/sourcegraph/sourcegraph/commits/cc2b7ee0a9dc734e92cf583a894e5c249a505ca7) we can end up in three states:
1. Commit is not available on codecov.io, and request errors out with 404 status printing [this message](https://sourcegraph.com/github.com/codecov/sourcegraph-codecov/-/blob/src/api.ts?L111) to console.
2. Commit data is available on codecov.io. But when we [include the `src=extension` search parameter](https://sourcegraph.com/github.com/codecov/sourcegraph-codecov/-/blob/src/api.ts?L129-130) to get coverage data for all files (what we actually need to create decorations) the server responds with a 500 error. 

| Commit data | Coverage data for all files |
| -- | -- |
|![image](https://user-images.githubusercontent.com/25318659/170002022-1a4d9231-6f16-449c-959e-b55787cde472.png) |![image](https://user-images.githubusercontent.com/25318659/170002238-7b986915-ae3e-4f49-a5bd-6d5dc732dab2.png)|


3. Commit coverage data is available when we query commit data with the `src=extension` search parameter (e.g. https://codecov.io/api/gh/sourcegraph/sourcegraph/commits/cc2b7ee0a9dc734e92cf583a894e5c249a505ca7?src=extension).

| Coverage data for all files |
| -- |
|![image](https://user-images.githubusercontent.com/25318659/170002401-60ec49c6-4389-4895-83a0-e20dbd922005.png)|

 
I think the second case is the one causing these 500 errors we receive from time to time.

It also explains why we rarely get 500 errors when browsing older revisions. For example, I still didn't manage to get 500 on the [link from the issue description](https://demo.sourcegraph.com/github.com/sourcegraph/sourcegraph@947423ea4f32fe4766d406b4ad1dff08407a1e20/-/blob/enterprise/internal/authz/github/authz.go?L40-65), but got a few 500 when browsing the code on `main` recently.

I found a potentially related [issue](https://community.codecov.com/t/i-am-receiving-500s-intermittently-while-using-the-rest-api-to-retrieve-codecoverage-metrics/1270) on codecov forum, but it doesn't seem very helpful. I'll browse the forum again and if nothing found will create a new issue.

**Comment by taras-yemets** [comment] 2022-05-24 11:49
Created an [issue](https://community.codecov.com/t/getting-500-response-when-requesting-a-single-commit-with-src-extension-search-parameter/3673) on the codecov community forum.

**Comment by muratsu** [comment] 2022-05-24 13:09
Thanks for chasing this issue @taras-yemets !

**Comment by ryankscott** [comment] 2022-08-11 08:11
Codecov let me know that this is likely fixed on their end. Closing because of this and the upcoming sunset.

**Closed by ryankscott** 2022-08-11 08:11 UTC
Labels: bug, extensions, team/integrations, make-extensions-enterprise-friendly
