### ISSUE TITLE
Unusual C++ syntax highlighting

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#40845] opened 2022-08-25 12:55 UTC
Wondering if this regressed with the syntect bump or something else. Pretty sure it highlighted keywords properly before.

![](https://user-images.githubusercontent.com/93103176/186670255-f3435ed8-bd65-469d-8e21-a17fc3fd59df.png)

**Comment by olafurpg** [comment] 2022-09-21 12:34
I'm still able to reproduce this on sourcegraph.com link  https://sourcegraph.com/github.com/llvm/llvm-project@8a774c35e9f8c6a200a8f4d00aae909840f5004a/-/blob/llvm/include/llvm/ADT/SmallSet.h?L35

![Image](https://user-images.githubusercontent.com/1408093/191504829-08049434-57b8-4b3c-aea2-f83c94b8bbba.png)

**Comment by olafurpg** [comment] 2023-03-13 13:24
Closing as fixed, most likely thanks to the new tree-sitter based highlighting. I'm unable to reproduce on sourcegraph.com 

<img width="726" alt="CleanShot 2023-03-13 at 14 23 38@2x" src="https://user-images.githubusercontent.com/1408093/224714624-b6550a45-10c1-4e68-92f0-562d435f5d40.png">

**Closed by olafurpg** 2023-03-13 13:24 UTC
Labels: team/code-intelligence, team/language-tools
