### ISSUE TITLE
Search match highlight is offset or absent on some diff results, or matching line of code is absent

### ISSUE THREAD

**Issue by marekweb** [sourcegraph/sourcegraph#21819] opened 2021-06-07 14:51 UTC
Query: [`usestate type:diff lang:TypeScript repo:sourcegraph/sourcegraph`](https://sourcegraph.com/search?q=context:global+usestate+type:diff+lang:TypeScript+repo:sourcegraph/sourcegraph&patternType=literal)

Observation 1: the result from file `UserAddCodeHostsPage.tsx` the highlighted match for `useState` is off.

<img width="1289" alt="Screen Shot 2021-06-07 at 10 33 55" src="https://user-images.githubusercontent.com/602886/121036482-c763a300-c77c-11eb-84d0-358d8097eb05.png">

Observation 2: the result from file `StreamingSearchResults.tsx` is off, and the line of code isn't shown for this match, just the file name line and context markers.

<img width="1154" alt="Screen Shot 2021-06-07 at 10 39 04" src="https://user-images.githubusercontent.com/602886/121037486-7b652e00-c77d-11eb-90d5-7d890b470e07.png">

Observation 3: the match is not highlighted, or the line of code is absent, in some results.

Updated query to include `file:` which produces multiple results that exhibit this behavior:

[`usestate type:diff lang:TypeScript repo:sourcegraph/sourcegraph file:streamingsearchresult`](https://sourcegraph.com/search?q=context:global+usestate+type:diff+lang:TypeScript+repo:sourcegraph/sourcegraph+file:streamingsearchresult&patternType=literal)

<img width="1274" alt="Screen Shot 2021-06-07 at 10 48 08" src="https://user-images.githubusercontent.com/602886/121038223-1c53e900-c77e-11eb-9c9c-f0cc563a236c.png">

**Comment by limitedmage** [comment] 2021-06-11 20:09
Thanks for reporting, this is definitely a duplicate of #20285, this is happening because `useState<Type>` is being stripped out to just `useState`

**Closed by limitedmage** 2021-06-11 20:09 UTC
Labels: bug, team/search
