### ISSUE TITLE
migrate transaction failed err="blank input is invalid jsonc"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1887] opened 2019-01-14 23:58 UTC
1. Run the latest insiders image using the instructions from docs.sourcegraph.com
2. Observe error in log output during startup:

```
t=2019-01-14T23:53:42+0000 lvl=eror msg="migrate transaction failed" err="blank input is invalid jsonc"
```

This appears to be an issue caused by external_services migration, possibly a regression due to @chrismwendt related change on how we interpret empty JSONC strings but I am not positive about this.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/db/external_services.go#L488

**Comment by chrismwendt** [comment] 2019-01-14 23:59
This is definitely caused by PR https://github.com/sourcegraph/sourcegraph/pull/1879

**Comment by slimsag** [comment] 2019-01-15 00:03
I think your PR may also be causing Nick's issue #1888 -- it may have changed how this code operates: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/pkg/conf/computed.go#L43-46

**Comment by nicksnyder** [comment] 2019-01-15 00:06
https://github.com/sourcegraph/sourcegraph/commit/5b7fbdc7dc85bf38fc25373a8b60f0cb35df3850

**Comment by nicksnyder** [comment] 2019-01-15 00:06
That is a workaround, I don't know if there is a more fundamental issue to fix

**Comment by nicksnyder** [comment] 2019-01-15 00:59
> I think your PR may also be causing Nick's issue #1888 -- it may have changed how this code operates: 

This doesn't appear to be the case. I tested after Chris reverted and was still able to reproduce the auth issue.

I am going to close this since reverting resolved this issue.

**Closed by nicksnyder** 2019-01-15 00:59 UTC
Labels: bug, release-blocker
