### ISSUE TITLE
Filter search to repos containing another search term

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#110] opened 2018-07-26 19:25 UTC
#### Describe the feature request.
Run a search, filtered to only repos that also have results for an initial search

#### Is your feature request related to a problem? Please describe.
A user would like to:
* Search for a word X, but;
* Only in repos that also have results for the word Y

#### Describe alternatives you've considered.
Execute two separate searches: 
* First, using the Sourcegraph API to find repos containing X, such as [this search on Sourcegraph.com's API console](https://sourcegraph.com/api/console#%7B%22query%22%3A%22%7B%5Cn%20%20search(query%3A%20%5C%22repogroup%3Asample%20test%5C%22)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20repositories%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%22%7D)
* Second, using the Sourcegraph API constrained by the search filter `repo:(r1|r2|...)` where `r1`, `r2`, and `...` are repos found in the first search

#### Additional context
Refer to full API access documentation at https://about.sourcegraph.com/docs/features/api

**Comment by beyang** [comment] 2018-07-26 19:29
Related: https://github.com/sourcegraph/issues-uber/issues/115 (but this is asking for all files that contain two terms, not all repos).

**Comment by keegancsmith** [comment] 2018-07-27 13:05
Proposal: I think the best approach here (and helps other issues as well) requires adjusting our query language to be hierarchical. Additionally we would need to specify that a sub-expression is only looking for repos which contain matches. With those two concepts I'd imagine the query would be

```
(type:repo Y) AND (X)
```

This solves this use-case, as well as many other use cases since it is very general. We don't necessarily need to expose that exact syntax to the user (but I like it).

**Comment by felixfbecker** [comment] 2018-07-27 19:04
I would also imagine some kind of subquery syntax:
```
foo repo:(bar)
```
(search for `foo` in all repos that had results for `bar`)

**Comment by sqs** [comment] 2018-10-25 09:38
This is currently being worked on. See **Sub-query support in search** at https://docs.sourcegraph.com/dev/roadmap#october-2018.

**Comment by keegancsmith** [comment] 2018-11-01 10:42
This will be part of our 3.0-preview release, and not our imminent 2.13 release. So moving to november milestone (but will be ready before november release)

**Comment by sqs** [comment] 2019-01-25 05:59
Closing as dupe of #1005

**Closed by sqs** 2019-01-25 05:59 UTC
Labels: feature-request, question, search
