### ISSUE TITLE
GitHub code intelligence doesn't work after soft page load; works after hard page load

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#750] opened 2018-10-24 20:15 UTC
Reproduction:
1. Go to https://github.com/sourcegraph/sourcegraph/pull/482
2. Click on "Files changed" tab
3. Hover over any symbol (e.g. ListRepositoriesForSearch)

Expected:
See hover tooltips.

Actual:
No hover tooltips.

Workaround:
Refresh the page or navigate directly to https://github.com/sourcegraph/sourcegraph/pull/482/files and hover tooltips work.

**Comment by lguychard** [comment] 2019-04-01 14:49
I have a repro for this:
- Using an extension built from https://github.com/sourcegraph/sourcegraph/pull/2909 (this is important, otherwise you run into https://github.com/sourcegraph/sourcegraph/issues/2958, and because there is only one file in the PR, you can never get code intelligence)
- Visit https://ghe.sgdev.org/beyang/mux/pull/1/files
- click "Conversation" (soft page load)
- witness error in console: `cannot determine delta info` (https://github.com/sourcegraph/sourcegraph/issues/3100)
- click "Files changed" (soft page load)
- witness code views are not resolved anymore, no code intelligence

**Comment by felixfbecker** [comment] 2020-03-31 14:53
I followed the above steps in https://github.com/sourcegraph/sourcegraph/issues/750#issuecomment-478610745 on https://ghe.sgdev.org/sourcegraph/gorilla-mux/pull/1/files (the linked PR did not exist anymore), and cannot reproduce it. The error also does not appear. I am closing this since it is over a year old and it is likely we fixed this in the meantime, but please reopen if you ever see it again :)

**Closed by felixfbecker** 2020-03-31 14:53 UTC
Labels: browser-extension, bug, github-enterprise, team/web
