### ISSUE TITLE
Insights: Move data points link generation from the frontend to the backend gql resolvers

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#38104] opened 2022-07-01 16:33 UTC
At the moment all data point link generation is happening on the frontend. We have to iterate over all points that we got from the backend and based on the insight filters/reposiotires/query we need to generate a data point link for the chart point. All this introduces 
- Complexity on the front end. Basically, we need to know about many insight fields to build the right URL for the chart. And very often we just miss this logic when we introduce new filters/insight metadata (recent example: https://github.com/sourcegraph/sourcegraph/issues/38097)
- Performance problems, the fact that we need to iterate over series points before chart rendering may add unnecessary perf problems on the frontend (this isn't a problem for 1 chart with 2 series with 12 points each, but imagine 20 insights with 20 series with 12 points on the page and for each point, we should generate a special URL it's 4800 points.)

**Comment by coury-clark** [comment] 2022-07-01 16:41
Is there a reason this can't be calculated on the click event instead of before render? There isn't going to be any performance different doing this on the webapp versus the backend if we do the same algorithm.

**Comment by vovakulikov** [comment] 2022-07-01 17:05
@coury-clark I also was thinking about creating URL on demand but this way will introduce other problems with a11y. Basically, we always have to have `a` element with a proper `href` attribute to be accessible through keyboard and voice-over. 

> There isn't going to be any performance difference doing this on the webapp versus the backend if we do the same algorithm.

I disagree, I assume we have a more powerful machine where our backend is running compared to the average user machine where we have other tabs in Chrome, Zoom screen sharing that consume all available resources, ...etc. So it should be better for user performance in general rather than having this generation on the frontend.

**Comment by coury-clark** [comment] 2022-07-01 17:24
> I disagree, I assume we have a more powerful machine where our backend is running compared to the average user machine where we have other tabs in Chrome, Zoom screen sharing that consume all available resources, ...etc. So it should be better for user experience in general rather than having this generation on the frontend.

In general you're probably backwards on this, but regardless - without a profile that shows a performance problem it's not going to be very useful to speculate about the cause outside of the algorithmic complexity (which is the same).

That we can't generate the link dynamically is disappointing. Is there no way accessibility allows for dynamically generated content?

**Comment by vovakulikov** [comment] 2022-07-01 17:46
@coury-clark technically speaking this isn't correct to say that time complexity would be the same. In terms of Big O notation of course algorithmic complexity would be the same, but I think in this case this is the wrong direction to think about it. 

In practice, iterations over the array on the front end (1 or 2 times) matter. So at the moment 
1. We iterate over points on the backend 
2. When we iterate over points to generate links on the frontend 
3. Render points which are also iterations over the list of points. 

Frankly speaking, we could merge steps 2 and 3 in one iteration on the frontend but it will introduce some complexity since we have to know and gather many fields on the frontend to build a proper URL and it seems to me that the backend will handle it better since all needed information fields are easily accessible on the backend. 

I could also say that we should keep FE clients as thin as possible and not have any runtime logic there. cc @unclejustin

**Comment by coury-clark** [comment] 2022-07-01 17:53
I don't see anywhere we are actually removing a pass over the array though. The webapp will still need to iterate once for each point to generate the `a` element, as well as prepend the host to the provided search query. That's the same number of steps as above, unless there is something else you're suggesting that I'm misunderstanding.

**Comment by vovakulikov** [comment] 2022-07-01 18:04
@coury-clark By moving it to the backend we reduce number of iterations on the frontend. You're right that at the end we still have the same number of iterations. But as I said it does matter how many array iterations we have on the frontend and in general data processing should live on the backend rather on the frontend and the frontend shouldn't change anything about data but just render it on the page IMO.

**Comment by coury-clark** [comment] 2022-07-01 18:26
To be clear, in general I'm not against this. From the descriptions above we will have the exact same performance characteristics on both the webapp and backend, for the reasons stated. It's not simply that I'm suggesting the overall load time won't change, but that the webapp is still going to have to do the same amount of work after this change due to the reasons listed above (element and host name).

So if the focus is to centralize this logic or something, we can consider this work with that in mind.

**Comment by unclejustin** [comment] 2022-07-01 18:31
I think speculating on performance, in this case, is a bit premature, but I also think that is not the real question here. 

The question to me is "In what domain does this logic belong?" I'm still digesting the core problem we had in the issue Vova sighted. My gut tells me too much "business logic" is happening on the frontend in this case.

I'm going to sit on this for a bit before I chime in any further.

**Comment by vovakulikov** [comment] 2022-07-01 18:45
> The webapp will still need to iterate once for each point to generate the a element

This is correct and as I mentioned above we could merge link generations and rendering steps in just one step but this will increase the complexity of our charts and we would have to be really careful there because the creation `new Objects` in the render loop might be a problem in terms of memory consumption. 
 
@coury-clark oh, I missed this part 

> as well as prepend the host to the provided search query

This actually is a redundant step, we can leave links without a host, and it still will be a valid link for example `<a href="/search?q=search_example_string">`

<img width="481" alt="Screenshot 2022-07-01 at 14 43 57" src="https://user-images.githubusercontent.com/18492575/176953139-2e377faa-bfb3-494e-8c15-566f6f78e1e0.png">


So, in general, I agree that it might be a bit premature optimization right now in terms of performance but I agree with Justin that there is another aspect of this change - we want to reduce the domain of FE as much as possible and keep our client as thin as possible. If it won't be a problem for the BE to do this I would advocate moving this logic from the FE and putting this issue in the Backlog.

**Comment by felixfbecker** [comment] 2022-07-01 20:42
@vovakulikov what @coury-clark means is that to render the points, you iterate anyway:
```tsx
{points.map(point =>
   <a href={buildLink(point, context)}>
       <Point {...point} />
   </a>
)}
```
and could build the link there _without_ increasing the number of iterations.

This is true, but for various reasons currently is not done, but the links are all added to each object beforehand. I can see reasons why that would be the better choice in certain cases when wanting to abstract into components.

The "Point" component likely needs additional metadata from the outer context/series/insight to build the link, so you need to pass additional metadata, but especially if we want to make our chart components reusable in the webapp for other areas you don't want to couple them to this specific link generation and the shape of the needed metadata. So you'd need to come up with generically-typed callback functions that can be passed in to build the link. Certainly all possible, just not as easy as it may seem at first if you consider reusability and component abstractions.

Regarding performance, one big consideration is that everything that runs in JS runs in one main thread that also renders the UI, so _anything_ expensive that is being done has detrimental effects on UX quickly. Agree that it may be premature to think about in this case but the argument in general is valid, computation on the client has a high cost.

**This discussion has gone a lot back and forth over something that seems like a relatively small thing, so I'd strongly suggest we just move into one direction** (the cost/time spent on discussing this seems to exceed the cost of possibly making the "wrong"/not-perfect choice).

Exposing URLs from GraphQL is pretty common (e.g. GitHub has a `url` field on any object that has a web UI page and we even have it in our own API in some places) and I'd imagine adding a resolver for it on the backend is low-effort, so I'd propose we do that. Maybe it's even something @vovakulikov can implement himself? Please correct me if my assumption is wrong and this is _significant_ effort/complexity to do in the backend.

**Comment by unclejustin** [comment] 2022-07-01 20:43
I went searching for other people's opinions on FE/BE separation and found [this comment](https://www.reddit.com/r/SoftwareEngineering/comments/mimh1c/comment/gt6ccpq/?utm_source=reddit&utm_medium=web2x&context=3) on reddit.

In particular point 4 made a lot of sense to me:

> avoid at all cost splitting similar in nature logic across multiple systems or layers. This creates confusion and maintenance headache.

If we're constructing the URL already on the BE then making adjustments to "finalize" the URL on the FE that feels wrong to me. We should put the duty of URL creations squarely in place unless there is a compelling reason not to.

In this instance I do agree with @vovakulikov since it seems we are already halfway there with anyway on the BE.

**Comment by coury-clark** [comment] 2022-07-01 22:07
> This discussion has gone a lot back and forth over something that seems like a relatively small thing, so I'd strongly suggest we just move into one direction

I probably haven't been clear - I support this issue in general and have no problem conceptually moving it. I just want to be clear that moving things to the backend is not automatically a performance benefit, and in some cases can be very difficult to do because of the hierarchy of revolvers (not likely the case here).

In this case, we don't really much of a concept of "insight type" on the backend right now, so I'm not sure how much this feature is influenced by that concept. We have a similar concept per-series (which is ultimately what this is on the backend) that may suffice.

I'd probably estimate this at a 5 and would not say its going to be a significant effort.

**Closed** 2022-12-23 16:57 UTC
Labels: team/code-insights, backend, feature/unify-insights, strategic, strategic-scoped-insights
