### ISSUE TITLE
Ensure frontend cache dir does not grow unbounded

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2445] opened 2019-02-25 22:16 UTC
The frontend appears to grow unbounded on the shared SSH cache. See https://github.com/sourcegraph/sourcegraph/issues/627#issuecomment-465143874

Here is a similar fix made to lang-go:
https://github.com/sourcegraph/go-langserver/pull/359

This general problem feels like it should be owned by the core services team @keegancsmith @tsenart , unless you have additional information that would indicate there is a better owner. Assigning to you to triage and prioritize.

**Comment by keegancsmith** [comment] 2019-02-26 06:14
Related to https://github.com/sourcegraph/sourcegraph/issues/627

**Comment by keegancsmith** [comment] 2019-04-17 13:23
#1995 would solve this by moving the cache out of the frontend. Honestly I think this is the correct solution to the problem, so gonna close this out.

Duplicate of #1995

**Closed by keegancsmith** 2019-04-17 13:23 UTC
Labels: team/core-services
