### ISSUE TITLE
Syntax highlighting not working for c#

### ISSUE THREAD

**Issue by IljaKroonen** [sourcegraph/sourcegraph#41493] opened 2022-09-08 08:15 UTC
- **Sourcegraph version: sourcegraph/server:3.43.1**
- **Docker version 18.09.3, build 774a1f4eee**

#### Steps to reproduce:

I am not sure if this is reproducible with a different set of sources.

1. Run sourcegraph (in an environment with no internet)

```
docker run -d --restart=always --publish 7080:7080 --publish 127.0.0.1:3370:3370 --publish 7443:7443 \
  --mount "type=volume,src=sourcegraph-config,dst=/etc/sourcegraph" \
  --mount "type=volume,src=sourcegraph-data,dst=/var/opt/sourcegraph" \
  sourcegraph/server:3.43.1
```
2. Connect to a github enterprise instance with many repositories, and a lot of c# code
3. Open some C# sources and notice there is no syntax highlighting
![image](https://user-images.githubusercontent.com/6551900/189068050-90953631-8932-4e34-83cb-f58514bbf296.png)

#### Expected behavior:

Syntax highlighting

#### Actual behavior:

No syntax highlighting

This message appears in logs (redacted)

```
07:48:05                  frontend | t=2022-09-08T07:48:05+0000 lvl=eror msg="syntax highlighting failed (this is a bug, please report it)" filepath=src/XXX.A.B/C/Something.cs filetype=c_sharp repo_name=ghe.xx.xx/XY/xxx revision=ada0ee40ade592fa129320d1afa5a12e14897a5d snippet="\"using XXX.Something.SomethingElse.Model;\\n\\nnamespace XXX.Something.SomethingElse.Servic\"…" error="http://127.0.0.1:9238: gosyntect internal error: resource_not_found"
07:48:05                  frontend | t=2022-09-08T07:48:05+0000 lvl=eror msg="syntax highlighting failed (this is a bug, please report it)" filepath=src/XXX.A.B/C/SomethingSomething.cs filetype=c_sharp repo_name=ghe.xx.xx//XY/xxx revision=ada0ee40ade592fa129320d1afa5a12e14897a5d snippet="\"using XYZ.Core;\\nusing System;\\nusing System.Collections.Generic;\\nusi\"…" error="http://127.0.0.1:9238: gosyntect internal error: resource_not_found"
07:48:05            syntect_server | Error: No matching routes for POST /lsif application/json.
07:48:05            syntect_server | Warning: Responding with 404 Not Found catcher.
```

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by malomarrec** [comment] 2022-09-20 13:19
Hey @quinnhare, it looks like this issue was created by someone outside Sourcegraph. Assigning you to triage it! Please answer and route to the right team by adding their team label, then **remove** the `triage-bot/needs-triage` label

**Comment by quinnhare** [comment] 2022-09-20 16:01
Assigning to to Code Intelligence

**Comment by olafurpg** [comment] 2022-09-21 12:51
@IljaKroonen Thank you for reporting! It is normal that this error happens when highlighting very large files (>5k lines of code). Can you confirm whether this error only happens for large files or does it happen for all C# files?

**Comment by IljaKroonen** [comment] 2022-09-21 13:19
Every single c# file suffers from this issue regardless of length (some are just a few lines of code).

**Comment by olafurpg** [comment] 2022-09-21 14:42
I just ran the docker setup locally and was able to reproduce this issue. Thank you for reporting this issue @IljaKroonen ! 🙏🏻

**Comment by olafurpg** [comment] 2022-09-21 17:07
Great to hear that you were able to work around this issue. I'll keep this issue open until we have fixed the root cause. It looks like we need to update a `Dockerfile` to reference a newer build of our syntax highlighting service. I can only reproduce this issue when using the Docker single container deployment option. Please note that this deployment option is not recommended for product, as explained in more details here https://docs.sourcegraph.com/admin/deploy/docker-single-container

**Closed** 2022-12-01 14:02 UTC
Labels: team/language-tools
