### ISSUE TITLE
"Unable to fetch GitHub external services" error although repos are still able to be cloned

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#1710] opened 2019-01-08 19:30 UTC
When creating a new Sourcegraph instance I get error `Unable to fetch GitHub external services: json: error calling MarshalJSON for type json.RawMessage: invalid character '/' looking for beginning of object key string` although the repos are able to be cloned.

Tested with:
GitHub Enterprise 2.15.4
User access token (Site admin on GHE instance) with `gist, repo, user` access
Sourcegraph/Server:Insiders `340fe9dbe822`
Ubuntu 16.04.5 LTS
Docker-CE 18.09.0, build 4d60db4

Logs:
```bash
19:15:32           frontend | ✱ Sourcegraph is ready at: http://127.0.0.1:7080
19:20:16           frontend | t=2019-01-08T19:20:16+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe."
19:20:21           frontend | t=2019-01-08T19:20:21+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe."
19:20:26           frontend | t=2019-01-08T19:20:26+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe."
19:20:31           frontend | t=2019-01-08T19:20:31+0000 lvl=eror msg="Repository authz config was invalid (errors are visible in the UI as an admin user, you should fix ASAP). Restricting access to repositories by default for now to be safe."
```

<img width="1606" alt="screen shot 2019-01-08 at 11 21 59 am" src="https://user-images.githubusercontent.com/11583013/50853908-7bf10480-1338-11e9-94a7-35413b349837.png">
<img width="1612" alt="screen shot 2019-01-08 at 11 22 10 am" src="https://user-images.githubusercontent.com/11583013/50853909-7bf10480-1338-11e9-880a-17cc5462e8a6.png">

**Comment by nicksnyder** [comment] 2019-01-08 21:34
I believe this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/1540 which was just fixed in master. Can you please retest on the latest insiders? Going to close this for now.

**Closed by nicksnyder** 2019-01-08 21:34 UTC
Labels: release-blocker

**Comment by francisschmaltz** [comment] 2019-01-08 21:39
Duplicate of  #1540 and resolved in 19b2b1ce2ed8ef523786ecff8501a1710a15cbf810d562dad5aa031cfed8863e
