### ISSUE TITLE
deploy-sourcegraph-helm is missing tags and releases

### ISSUE THREAD

**Issue by kevinwojo** [sourcegraph/sourcegraph#36833] opened 2022-06-08 18:29 UTC
# Problem
It looks like somewhere during the release process, the `sourcegraph-3.40.0`tag was not created. 

```sh
deploy-sourcegraph-helm % git tag
sourcegraph-0.1.0
sourcegraph-0.1.1
sourcegraph-0.1.2
sourcegraph-0.1.3
sourcegraph-0.1.4
sourcegraph-0.2.0
sourcegraph-0.2.1
sourcegraph-0.3.0
sourcegraph-0.4.0
sourcegraph-0.5.0
sourcegraph-0.6.0
sourcegraph-0.7.0
sourcegraph-0.7.1
sourcegraph-3.39.0
sourcegraph-3.39.1
sourcegraph-migrator-0.1.0
sourcegraph-migrator-3.39.0
sourcegraph-migrator-3.39.1
```

Even though the release branch was created:

```
  origin/release/3.38
  origin/release/3.39
  origin/release/3.40
```

Additionally the helm chart is being published and updated.

# Next steps
Is this desired?

**Comment by caugustus-sourcegraph** [comment] 2022-06-08 19:03
#36832 describes the cause, so closing this out as a duplicate.

**Closed by caugustus-sourcegraph** 2022-06-08 19:03 UTC
