### ISSUE TITLE
RFE: Provide a way for users to know what is indexed on their Sourcegraph instance

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#41232] opened 2022-09-01 21:42 UTC
**Requested by:** https://github.com/sourcegraph/accounts/issues/6716 [via Slack](https://sourcegraph.slack.com/archives/C01P4R0RZH9/p1662054420858839), https://github.com/sourcegraph/accounts/issues/486 via Email

#### Feature request description

Provide a UI for showing users what code host and repositories are indexed by their Sourcegraph instance.

It would also be nice to be able to sort the list by most recently added so users know what was recently added to Sourcegraph.

#### Is your feature request related to a problem? If so, please describe.

At large customers, it's often a challenge for users to know exactly what has been added to a Sourcegraph instance.  They do a search and don't see an expected result.  They aren't sure if that means the repo isn't included or if the result isn't there. 

This often leads to a separate list being maintained that is not kept up-to-date with Sourcegraph.

/cc @jplahn @ryphil

**Comment by mrnugget** [comment] 2022-10-04 09:53
@mike-r-mclaughlin I know it's not a good solution, but I'm wondering if I get what the problem is exactly: wouldn't the search query `repo:<foobar>` help with answering whether "the repo isn't included or if the result isn't here"?

**Comment by mike-r-mclaughlin** [comment] 2022-10-04 14:39
@mrnugget yes that would answer the question: "is this specific repo (or group of repos) indexed in Sourcegraph?".  However, I think these customers are trying to be more proactive and avoid support issues.  This list would allow users to know ahead of time what is indexed (since they can't see the code host configuration).  From one customer in [this slack message](https://sourcegraph.slack.com/archives/C01P4R0RZH9/p1662055733289229?thread_ts=1662054420.858839&cid=C01P4R0RZH9):
> It’s more in line with the user being able to see what repos and code hosts are available for them to search in Sourcegraph. The format of that information, and the in-depth nature may vary but just a panel that says - “This is all we have for you to search…”

**Comment by mrnugget** [comment] 2023-10-12 10:05
Closing this because we do have ability to filter by `indexed` in site-admin now: https://sourcegraph.sourcegraph.com/site-admin/repositories?status=indexed

Bigger picture is the idea of showing "recently added repos" somewhere, but that seems out of scope for this ticket.

**Closed by mrnugget** 2023-10-12 10:05 UTC
Labels: feature-request, customer
