### ISSUE TITLE
Bitbucket server: Repo not found error when the hostname is different from the perspective of the client vs Sourcegraph

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#4055] opened 2019-05-16 00:59 UTC
- Spin up a new Sourcegraph instance on localhost:7080
- Spin up a new Bitbucket Server instance and add a repository
- Point the browser extension to http://localhost:7080
- Visit a file on Bitbucket Server and hover over some code to trigger a GraphQL request
- Open the browser console and see this error:

![image](https://user-images.githubusercontent.com/1387653/57818056-2ccc3d80-7737-11e9-8b1d-4582d6e601fd.png)

The Sourcegraph icon and TypeScript toggle buttons look ok:

![image](https://user-images.githubusercontent.com/1387653/57818171-a6642b80-7737-11e9-9c49-7a8b4ee9ec6a.png)

![image](https://user-images.githubusercontent.com/1387653/57818260-fcd16a00-7737-11e9-9dd7-dd7f2405e5a5.png)

My `sourcegraphURL` in chrome sync storage is `"http://localhost:7080"`:

![image](https://user-images.githubusercontent.com/1387653/57818194-be3baf80-7737-11e9-8bed-9eaed598b65c.png)

I don't think this is a basic-code-intel bug because basic-code-intel makes the request [through the Sourcegraph API](https://github.com/sourcegraph/sourcegraph-basic-code-intel/blob/6ae527dc8440aab19b0d5b9c464ca19b3873a207/package/src/api.ts#L226-L230).

**Comment by lguychard** [comment] 2019-05-16 14:28
@chrismwendt was that repository synced to your Sourcegraph instance?

**Comment by beyang** [comment] 2019-05-16 16:08
Should this be fixed before we ship to https://app.hubspot.com/contacts/2762526/company/407948923?

**Comment by chrismwendt** [comment] 2019-05-16 18:03
> was that repository synced to your Sourcegraph instance?

Ah, it has a different name:

- On Sourcegraph: `host.docker.internal/SOUR/sourcegraph`
- On Bitbucket, the open-file-on-Sourcegraph button links to: http://localhost:7080/localhost/SOUR/sourcegraph (`host.docker.internal` has been replaced with `localhost`)

Here's my Bitbucket external service configuration:

```jsonc
{
  "url": "http://host.docker.internal:7990",
  "username": "test",
  "token": ".......",
  "repositoryQuery": [
    "?name=SOUR"
  ]
}
```

Any idea what's causing this discrepancy?

**Comment by felixfbecker** [comment] 2019-05-16 18:19
@chrismwendt what browser extension version are you running?

**Comment by lguychard** [comment] 2019-05-16 18:31
@felixfbecker could this TODO be the cause of the discrepancy?: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/browser/src/libs/bitbucket/scrape.ts#L13:4

@chrismwendt are you using `repositoryPathPattern`?

I also suspect the original bug was caused by the following:
- The version of the browser extension you were running still had the sourcegraph.com fallback code
- The request to your instance failed, probably because of the naming discrepancy
- The fallback to sourcegraph.com then errored

Could you retry with the latest version of the browser extension? Thanks!

**Comment by chrismwendt** [comment] 2019-05-16 19:32
@felixfbecker I was running v19.4.26.1859 (see screenshot)

Now on v19.5.16.1439 I get a different error saying the repository doesn't exist:

![image](https://user-images.githubusercontent.com/1387653/57880811-8e8eb500-77d4-11e9-8527-e1a5e55ad651.png)

@lguychard That sequence of events sounds right to me.

Is this case (different hostname from the perspective of the client vs Sourcegraph) worth addressing? If so, here are some ideas:

- Run a Sourcegraph search for `SOUR/sourcegraph$` (i.e. leave off the hostname) and most likely there will be 1 hit with the Sourcegraph repository name
- Expose the hostnames of all of the external services over GraphQL so that the browser extension can try all of them
- Add an external service configuration field `"clientHostname": "localhost"` to set up some kind of alias for the repository name

**Comment by lguychard** [comment] 2019-05-16 20:47
I think it's worth addressing for robustness' sake, but the fact that clients haven't run into it up until now makes it low priority.

**Comment by slimsag** [comment] 2019-05-16 21:52
@chrismwendt was this intentionally closed?

**Comment by chrismwendt** [comment] 2019-05-16 21:54
Yeah, I figured we'd reopen it when we plan to work on it, but I suppose it's ok to leave open in the meantime in the backlog.

**Comment by vdavid** [comment] 2022-10-05 09:17
Thoughts:
 - This doesn't effect production
 - When we develop the BExt, we use the workaround to hard-code the URL of the repo temporarily in the BExt code
 - We don't really see a better way to do it, but if the above workaround is documented, we're fine with it.

So we think we're fine to close this.

**Closed by vdavid** 2022-10-05 09:17 UTC
Labels: browser-extension, bitbucket, team/integrations, icebox
