### ISSUE TITLE
Does SourceGraph support file extension based language mapping?

### ISSUE THREAD

**Issue by liamwarfield** [sourcegraph/sourcegraph#21375] opened 2021-05-25 21:30 UTC
#### Question description
Does SourceGraph support file extension language mapping?

Does SG have anything like Opengroks -A option for indexing and highlighting. For example:
```
-A .foo:org.opengrok.indexer.analysis.c.CxxAnalyzerFactory
```
This would have Opengrok treat files that end in `.foo` as c++ files
```
-A .bar:org.opengrok.indexer.analysis.python.PythonAnalyzerFactory
```
This would have Opengrok treat files that end in `.bar` as python files.

**Comment by camdencheek** [comment] 2021-06-30 20:00
Hi @liamwarfield! There is no current way to do this without compiling your own version of `syntect_server`. Some related discussion on how we might solve this for highlighting can be found [here](https://github.com/sourcegraph/sourcegraph/issues/20227), but I don't think there is any immediate effort planned to implement that. 

I'm going to close this since I believe it's a duplicate of the discussion in that issue, but feel free to reopen if I'm mistaken

**Closed by camdencheek** 2021-06-30 20:00 UTC
Labels: team/search-product
