### ISSUE TITLE
search: buggy handling of escapable characters in quoted strings for field values

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#10442] opened 2020-05-06 06:14 UTC
- **Sourcegraph version:** sourcegraph.com (62791_2020-05-06_9c3ecdc)
- **Platform information:** macOS, Chrome 81.0.4044.129

The quoting behavior from interactive search mode caused problems when I built a search query that used a file negation filter as seen below.

![ScreenFlow](https://user-images.githubusercontent.com/133014/81142445-0db36500-8fb3-11ea-847a-88b75753e848.gif)

To reproduce:

1. Go to https://sourcegraph.com
1. Enable interactive mode
1. Search for `changeset`
1. Add `github.com/sourcegraph/sourcegraph$` as a `repo` filter
1. Add `typescript` as a `lang` filter
1. Add `campaigns` as a `file` filter
1. Add `\.test` as a `-file` filter

That should produce [no search results with weird quoting](https://sourcegraph.com/search?q=changeset+repo:%22%5Egithub%5C%5C.com/sourcegraph/sourcegraph%24%22+lang:%22typescript%22+file:%22campaigns%22+-file:%22%5C%5C.test%22&patternType=literal) that you can see if you revert back to plain text mode. Removing the quotes produces the expected results.

**Comment by attfarhan** [comment] 2020-05-06 07:55
Thanks for flagging. It seems like the negated file filter doesn't like quoted inputs 🤔

**Comment by attfarhan** [comment] 2020-05-15 17:33
@rvantonder could this potentially be a backend issue? While there may be a different issue here with parsing between plain text and interactive mode (I do see the weird query when switching back and forth sometimes, not reliably though), it seems that the correct query is being sent to the backend (see the query variable in request payload):

![image](https://user-images.githubusercontent.com/16265452/82079131-e841fc00-9714-11ea-8ece-1c8d16cc1754.png)

You can see it sending the proper query at this link, with interactive mode enabled: https://sourcegraph.com/search?q=repo:%22github.com/sourcegraph/sourcegraph%22+-file:%22%5C%5C.test%22+changeset&patternType=literal

**Comment by rvantonder** [comment] 2020-05-15 20:15
Yeah this looks like a backend scanner issue. I mentioned in previous PRs that we can always enclose values for fields in quotes, like `file:"foo"` (some didn't know about this). But, it looks like our scanner code is wrong for the case where the quoted string contains escape characters, specifically the `-file:"\\.test"` part is the issue here. It should be interpreting the `\\` as `\` but my guess is that it interprets this string literally. We can't do  `-file:"\.test"` because a `\` is a special character in quoted strings, so that's not a valid quoted string. So this is a bug and it is inexpressible to specify `\` in a quoted string for field values. :/

I'm assuming this has always been the case based on the age of the scanner code. It likely didn't surface because people don't typically manually enclose quotes around the fields that also contain special characters like `\` that need to be escaped. But as of #9315 we have a convention  for interactive mode that mechanically quotes/escapes these so that they are faithfully interpreted (and rightfully, it should be able to!). This problem should disappear when I migrate away from the current scanner. I'm going to see if I can perhaps migrate away rather than trying to fix this in the current scanner code, will keep posted.

**Comment by rvantonder** [comment] 2020-06-17 07:09
Depends on #10844, moved to 3.18.

**Comment by daxmc99** [comment] 2020-07-13 18:01
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by rvantonder** [comment] 2020-07-20 17:56
Confirmed fixed by adding `search.migrateParser` flag in #12184 (available in user/org/global settings). Will close this issue when we flip the switch. [URL to check](https://sourcegraph.com/search?q=-file:%22%5C%5C.test%22+changeset&patternType=literal).

**Comment by lguychard** [comment] 2020-09-30 11:27
@rvantonder `search.migrateParser` is now [`true` by default](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@a8e9732ea76de0c1879ba611891273f2a66a4234/-/blob/schema/settings.schema.json?subtree=true#L229-234). Can this be closed?

**Comment by lguychard** [comment] 2020-10-15 11:55
@rvantonder closing as per my comment above.

**Closed by lguychard** 2020-10-15 11:55 UTC
Labels: bug, team/search

**Comment by rvantonder** [comment] 2020-10-15 17:51
Yep!
