### ISSUE TITLE
Python basic code intelligence flaky

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#4606] opened 2019-06-19 19:10 UTC
- **Sourcegraph version:** 3.5
- **Platform information:**  k8s.sgdev.org

#### Steps to reproduce:

1. go to https://k8s.sgdev.org/ghe.sgdev.org/sourcegraph/flask-admin-flask-admin/-/blob/flask_admin/base.py#L109:16 , see how it works ok
2. got to https://k8s.sgdev.org/ghe.sgdev.org/sourcegraph/MrGemy95-Tensorflow-Project-Template/-/blob/utils/logger.py#L40:34 . Here it acts flaky

#### Expected behavior:
Show code intelligence should work perfectly.
#### Actual behavior:
Doesn't always show hovers and every now and then starts loading the hover but then ends up disappearing, misleading the user.
Video: https://cl.ly/74557d0aebeb

**Comment by ggilmore** [comment] 2019-06-19 20:32
Thanks for finding this, but this isn't a regression (verified with sourcegraph/server:3.4.4.

One interesting thing I noticed: requests for https://k8s.sgdev.org/ghe.sgdev.org/sourcegraph/MrGemy95-Tensorflow-Project-Template/-/blob/utils/logger.py#L40:34 don't include the repo name
```js
{"Query string":{"Search":""},"JSON":{"query":"
                    
                            query Search($query: String!) {
            search(query: $query) {
              results {
                __typename
                limitHit
                results {
                  ... on FileMatch {
                    __typename
                    file {
                      path
                      url
                      commit {
                        oid
                      }
                    }
                    repository {
                      name
                      url
                    }
                    limitHit
                    symbols {
                      name
                      containerName
                      
                      url
                      kind
                      location {
                        resource {
                          path
                        }
                        range {
                          start {
                            line
                            character
                          }
                          end {
                            line
                            character
                          }
                        }
                      }
                    }
                    lineMatches {
                      preview
                      lineNumber
                      offsetAndLengths
                    }
                  }
                }
              }
            }
          }
                        
                ","variables":{"query":"^summary_writer$ case:yes file:.(py)$ type:symbol"}},"Request payload":{"EDITOR_CONFIG":{"text":"{"query":"\n                    \n                            query Search($query: String!) {\n            search(query: $query) {\n              results {\n                __typename\n                limitHit\n                results {\n                  ... on FileMatch {\n                    __typename\n                    file {\n                      path\n                      url\n                      commit {\n                        oid\n                      }\n                    }\n                    repository {\n                      name\n                      url\n                    }\n                    limitHit\n                    symbols {\n                      name\n                      containerName\n                      \n                      url\n                      kind\n                      location {\n                        resource {\n                          path\n                        }\n                        range {\n                          start {\n                            line\n                            character\n                          }\n                          end {\n                            line\n                            character\n                          }\n                        }\n                      }\n                    }\n                    lineMatches {\n                      preview\n                      lineNumber\n                      offsetAndLengths\n                    }\n                  }\n                }\n              }\n            }\n          }\n                        \n                ","variables":{"query":"^summary_writer$ case:yes file:.(py)$ type:symbol"}}","mode":"application/json"}}}
```

**Comment by chrismwendt** [comment] 2019-06-26 23:17
If you have any more specific thoughts on this, we can address them by adding to the list of ideas for improving basic code intel https://github.com/sourcegraph/sourcegraph/issues/2298

I'm unable to repro the slow hovers at the moment. The next time you see this, can you grab the LightStep trace from the request in the Network tab? From the video, it looks like they timed out after 10s.

**Comment by macraig** [comment] 2020-10-20 17:14
This might be fixed with the updates to the hover tooltip code. Reopen if it's reproducible.

**Closed by macraig** 2020-10-20 17:14 UTC
Labels: bug, team/code-intelligence
