### ISSUE TITLE
Improving monorepo unindexed searches

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#27042] opened 2021-11-03 21:45 UTC
For Q4 OKR for large mono-repos. [From Jamboard](https://jamboard.google.com/d/1-rNnz6v1MmXPV5wcVbT24S7FDcrBAIize6wkDSvqEJs/viewer?f=0)

### Investigate the following avenues:

1. Co-locate unindexed search with gitserver (no network transmission)
2. Alternative to co-locating unindexed search jobs on gitserver: streaming git archive format that allows us to search as soon as the first archive chunk is received
3. Alternative: keep clones on searcher. Use same ideas for incremental indexing to more quickly search new commits.
4. https://github.com/sourcegraph/sourcegraph/issues/28680

Potentially linked to #21855

**Comment by keegancsmith** [comment] 2021-12-06 14:25
I filed https://github.com/sourcegraph/sourcegraph/issues/28612 tracking the work I am doing to make searcher incremental.

**Comment by keegancsmith** [comment] 2022-01-18 08:50
@tsenart and I spent yesterday investigating this. You can see our notes at https://github.com/sourcegraph/search-scratch/blob/master/2022/journal.org#tomas--keegan-unindexed-search-on-monorepos-2022-01-17-mon-1225

> Co-locate unindexed search with gitserver (no network transmission)

From our research I don't think this helps. Network isn't the issue here, its the cost of getting all the blobs from git. So doing a naive git grep is slow. Whatever we do will need to have a better laid out data / index. Once we explore this more it may make sense to colocate, but I suspect that is unlikely.

> Alternative to co-locating unindexed search jobs on gitserver: streaming git archive format that allows us to search as soon as the first archive chunk is received

We already stream a tarball. The problem is how we handle it currently. So this approach will help time to first result when cache is cold. However, we will still be limited by how slow `git archive` is. So avoiding the need to make git do a bunch of work as much as possible will be part of our solution. Once we have done that, hopefully the interactions with gitserver are so minimal this change is not important anymore.

> Alternative: keep clones on searcher. Use same ideas for incremental indexing to more quickly search new commits.

This is a potential way for us to get faster incremental updates since we can rely on `git fetch` to do the smart stuff.

> SPIKE: Why is incremental approach for unindexed symbols failing #28680

I can't remember what our stance on this was, I think we are still hoping on rockskip here. Will comment on that issue.

> I filed #28612 tracking the work I am doing to make searcher incremental.

This work is on pause until we decide on our approach. It may indeed involve what is specced out in that issue. More likely will have the same spirit of solution, but in a different way. Will comment on the issue.

**Comment by keegancsmith** [comment] 2022-01-31 12:24
Status update from friday: @tsenart and I have a bit of indecision and find ourselves going back and forth on a few key items. As such I'll be writing up an RFC this week to help clarify our direction and give something concrete to debate. The main points of indecision are around making something work at the 60GB scale and considering use cases were we search over many commits (eg a batch use case of code insights). However, the RFC I plan to write will focus on the "normal" user request path / patterns to help draw a line in the sand.

**Comment by keegancsmith** [comment] 2022-04-08 13:01
Lets keep this as a general tracking issue. I filed https://github.com/sourcegraph/sourcegraph/issues/33656 for the prototype @stefanhengl and I are going to work on next week. For reference the older approach we considered is tracked here: https://github.com/sourcegraph/sourcegraph/issues/28612

**Comment by keegancsmith** [comment] 2022-06-13 11:13
hybrid searcher zoekt prototype seems to be doing well in prod. It is turned on for our org, will turn on for everyone tomorrow. https://sourcegraph.com/site-admin/feature-flags/configuration/search-hybrid

Filed this issue about getting it over the finish line https://github.com/sourcegraph/sourcegraph/issues/37112

Here is the effect on search-blitz. The big spikes are when we hit an uncached commit (the megarepo is updated). The bit where it goes dramatically down is when I enabled the feature flag. I suspect the graph to pretty much not change, even when megarepo is updated.

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/187831/173341578-1bd10f1e-c6aa-423e-84e1-1c5dc7cb14ca.png">

**Closed** 2022-12-15 20:20 UTC
Labels: team/search-core
