### ISSUE TITLE
SCIM: emails has a display value which is incompatible with Entra ID

### ISSUE THREAD

**Issue by morgangauth** [sourcegraph/sourcegraph#62185] opened 2024-04-25 18:27 UTC
- **Sourcegraph version:** v5.3 (potentially older)
- **Platform information:** SCIM setup with Entra ID

#### Steps to reproduce:

1. Set up SCIM with Entra ID following instructions in the [docs](https://sourcegraph.com/docs/admin/scim#how-to-use)
2a. Click "Test Schema" 
2b. Begin provisioning

#### Expected behavior:
1. Clicking "Test Schema" will result in a valid configuration. <img width="943" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/113058716/c4dbfc90-0846-40b7-834e-0edf44f81d0c">
2. Provisioning will create, update, and delete users as expected.

#### Actual behavior:
1. When clicking "Test Schema", the following error is displayed: `SCIM Validation failed. The attribute emails[type eq "work"].display for User is not supported by the SCIM protocol. Please refer to the SCIM RFC`
![image (11)](https://github.com/sourcegraph/sourcegraph/assets/113058716/464a2627-03b5-416f-9669-bcfadb7fda40)
**Note:** According to [SCIM schema](https://scim.cloud/), the `emails` schema can be found below, whereas Sourcegraph includes an additional sub-attribute [(code here)](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@1ff9bc70eb7f47acb494b31b78302a1d1ea342e0/-/blob/cmd/frontend/internal/auth/scim/user_schema.go?L65)`display` under email.
```
"emails":[
    {
      "value":"dschrute@example.com",
      "type":"work",
      "primary": true
    }
  ]
```
2. When provisioning users, the following errors arise for all user updates in the Entra ID provisioning logs. *Note:* user creation and deletion seems to be working as expected.
```
"246ff006-4f12-4fe3-96fc-f9f6223932b1","2024-04-17T11:06:38Z","EntryExportUpdate","export","failure","Failed to update User 'redacted@email.com' in customappsso"
```
```
"2024-04-17T11:06:20Z","2a35d8fd-574d-48e3-927c-8c398e225a01","scim.2a35d8fd574d48e3927c8c398e225a01.d3fe4109-8727-4d5b-bbce-880663f1d87a","246ff006-4f12-4fe3-96fc-f9f6223932b1","f7d15e8f-21c6-4d5f-8de5-d2f86c17e4d6","Update","10019","4c26daf3-d932-4604-b7fb-1c2320cadb52","SourceGraph","","Azure AD Provisioning Service","system","failure","SystemForCrossDomainIdentityManagementServiceIncompatible","StatusCode: BadRequest
Message: Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
Web Response: 
{""schemas"":[""urn:ietf:params:scim:api:messages:2.0:Error""],""scimType"":""invalidPath"",""detail"":""The \""path\"" attribute was invalid or malformed."",""status"":""400""}. This operation was retried 0 times. It will be retried again after this date: 2024-04-17T11:06:16.7694551Z UTC","","nonServiceFailure","","39397638-a5c3-4a4c-b3ea-6bf779ca2292","Microsoft Entra ID","eed31091-3a64-41a7-a6b0-34f58b75bf8e","customappsso","9e01e4f7-e451-4556-8faf-83562aaa2e20","Redacted_Name","User","1148","","urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"
```
3. Provisioning is quarantined.
![image (6) (1)](https://github.com/sourcegraph/sourcegraph/assets/113058716/2f18f327-38b4-4855-8ef2-286abff7089a)

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by morgangauth** [comment] 2024-04-25 18:44
Occurring at https://github.com/sourcegraph/accounts/issues/8206. Relevant Slack thread can be found [here].(https://sourcegraph.slack.com/archives/CV5KX7T70/p1712921356226079)

**Comment by pjlast** [comment] 2024-05-09 09:16
@morgangauth I seem to be unable to replicate this:

<img width="1121" alt="image" src="https://github.com/sourcegraph/sourcegraph/assets/6427795/89df7878-30b8-4e6b-bb0a-69bb79fde8c9">

Do we have any more information on how their setup might differ from what's normal?

**Comment by morgangauth** [comment] 2024-05-09 18:36
@pjlast Hm strange. I was able to reproduce it with the following steps:
1. Go to: https://scimvalidator.microsoft.com/ -> "Discover my schema"
2. Entering `https://sourcegraph.sourcegraph.com/.api/scim/v2` for SCIM endpoint, and the token from S2 for `"scim.authToken"`
3. Click "Discover Schema", and then "Test Schema"
Is there a step I am missing?

**Comment by pjlast** [comment] 2024-05-09 18:50
@morgangauth ah okay, I see, I did not select "Discover my schema". I adjusted the default attributes based on what's documented here: https://sourcegraph.com/docs/admin/scim#user-attributes . It seems like our schema discovery does not provide the correct schema. I'll have a look into that tomorrow

**Comment by pjlast** [comment] 2024-05-14 08:42
@morgangauth after looking into this I can conclude that our schema is actually correct. The Microsoft SCIM Validator is incorrect. There have been lots of complaints about this in the past as well: https://techcommunity.microsoft.com/t5/microsoft-entra/azure-ad-scim-validator-is-in-general-availability-ga-status/m-p/3637911

So we're not going to change anything on our side just now, but we might add a special case for the Microsoft SCIM Validator in the future so that we don't receive queries about it.

**Comment by pjlast** [comment] 2024-05-14 08:46
@morgangauth I also want to highlight the actual SCIM Schema: https://datatracker.ietf.org/doc/html/rfc7643

You mentioned the following:

> According to [SCIM schema](https://scim.cloud/), the emails schema can be found below, whereas Sourcegraph includes an additional sub-attribute [(code here)](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@1ff9bc70eb7f47acb494b31b78302a1d1ea342e0/-/blob/cmd/frontend/internal/auth/scim/user_schema.go?L65)display under email.

If you look at the actual SCIM Schema, then an optional `display` value is part of the schema. The link you pointed to has some examples of a SCIM schema, where there is no `display` value. But these are just examples, and the display value is optional. But the schema does actually allow it.

**Comment by morgangauth** [comment] 2024-05-14 19:05
@pjlast thank you for looking into this! I will relay this back to the customer and apologies for the mixup with the SCIM schema

**Comment by pjlast** [comment] 2024-05-15 10:10
Closing this for now since the issue is not with Sourcegraph

**Closed by pjlast** 2024-05-15 10:10 UTC
Labels: bug, rfh, scim, team/source

**Comment by morgangauth** [comment] 2024-05-20 22:31
Added a note to our docs mentioning that the SCIM validator will fail to avoid repeat inquiries. https://github.com/sourcegraph/docs/pull/331
