### ISSUE TITLE
Regex search mode will run last search with empty search box

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24395] opened 2021-08-28 20:03 UTC
On Sourcegraph Cloud, if I clear out the search bar, then click the regex search button, the previous search re-reruns but the search box stays empty.

It also doesn't look like the patternType URL parameter changes on click either, and neither does the pattern type button's status (regex pattern is never disabled)

![CleanShot 2021-08-28 at 15 02 07](https://user-images.githubusercontent.com/4605817/131229710-3465dc5a-8e8f-45dc-b21d-459af07c666a.gif)

**Comment by fkling** [comment] 2022-04-25 16:38
Look like this is fixed (maybe as part of the global state refactor). Can you confirm @benvenker ?

**Comment by camdencheek** [comment] 2024-02-23 19:53
Closing since I can no longer reproduce

**Closed by camdencheek** 2024-02-23 19:53 UTC
Labels: bug, team/search-product, search-ux, team/code-search, imported
