### ISSUE TITLE
Support multi-line searches

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#191] opened 2018-10-02 04:43 UTC
#### Feature request description

Find matches for a search query that occur across multiple lines. Right now, Sourcegraph only finds a match when it occurs on a single line.

#### Additional context

Reported by @lhorie (and others, before this repo was open-sourced) at https://news.ycombinator.com/item?id=18117755

**Comment by hho** [comment] 2019-01-04 21:07
Possible duplicate of #35

**Comment by keegancsmith** [comment] 2019-01-07 17:43
Duplicate of #35

**Closed by keegancsmith** 2019-01-07 17:43 UTC
Labels: feature-request, plan, search
