### ISSUE TITLE
Polish datadog extension appearance

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1746] opened 2019-01-09 16:34 UTC
![image](https://user-images.githubusercontent.com/10532611/50913492-c8216f00-1434-11e9-98e6-c830fd0a3689.png)

Improve readme and remove WIP label

**Comment by sqs** [comment] 2019-01-09 18:03
Duplicate of #1739

**Closed by sqs** 2019-01-09 18:03 UTC
Labels: extensions
