### ISSUE TITLE
[Accessibility]: Ghost elements cluttering diff view

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#34538] opened 2022-04-26 20:12 UTC
### Audit type

Keyboard navigation

### User journey audit issue

https://github.com/sourcegraph/sourcegraph/issues/34080

### Problem description

In between diffs, there is a ghost element that gets focussed when tabbing through and just links to `/`. That seems like an unnecessary additional tab press.

<img width="1059" alt="CleanShot 2022-04-26 at 22 09 35@2x" src="https://user-images.githubusercontent.com/19534377/165383826-b9b36e92-145a-4d36-8ab6-51f51b3529eb.png">

### Expected behavior

This element does not appear or links to something useful.

### Assigning labels

- [ ] Please give this issue an estimate by applying a label like `estimate/Xd`, where X is the estimated number of days it will take to complete.
- [ ] If this issue is specific to a specific Sourcegraph product, please assign the appropriate team label to this issue.
- [ ] If this issue will require input from designers in order to complete, please assign the label `needs-design`.

**Comment by gitstart-sourcegraph** [comment] 2022-05-26 13:10
With respect to the comment on code, at the point where the ancor link was added:
`The empty <a> tag is to allow users to anchor links to the top of this file diff node` [Ref here](https://sourcegraph.com/search?q=context:global+%7B/*+The+empty+%3Ca%3E+tag+is+to+allow+users+to+anchor+links+to+the+top+of+this+file+diff+node+*/%7D&patternType=literal), 
At the moment, looks like that purpose is not being fulfilled by the added link, since it navigates to `/` instead of top of Diff as mentioned in comment.

Should we remove this element, or modify to support expected behavior from code comment (would need some clarity on expected behavior of element).
CC: @eseliger @umpox @valerybugakov

**Comment by umpox** [comment] 2022-05-26 13:38
@gitstart-sourcegraph I fixed this in this PR: https://github.com/sourcegraph/sourcegraph/pull/35530/files#diff-1a6192688ba68661ae325edb3b315c5b95d37e6c68b1da6b9597481b7dbafdb5L104

I didn't notice this issue, sorry! Will close it. We'll have to watch out for duplicate bug reports here as some components are used across many journeys. Thanks for raising this

**Closed by umpox** 2022-05-26 13:38 UTC
Labels: accessibility, estimate/0.5d, gitstart, wcag/2.1/fixing, wcag/2.1
