### ISSUE TITLE
Identify metrics and alerts for batch changes executors on Cloud MI

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#39443] opened 2022-07-26 14:23 UTC
See https://docs.google.com/document/d/1Ss7ZffP82rV6nl4i5gBmICfuMK1xvSFI4Y5sLPXyDZc/edit?disco=AAAAc9qshb8 for more details, but essentially we have to define metrics and alerts to keep executors alive and healthy for cloud MI before the August release.

**Comment by chrispine** [comment] 2022-07-26 14:40
duplicate of #[39180](https://github.com/sourcegraph/sourcegraph/issues/39180)

**Closed by chrispine** 2022-07-26 14:40 UTC
Labels: estimate/2d, team/batchers
