### ISSUE TITLE
When try to search a context that has no repos, error message implies the user themselves hasn't added repos

### ISSUE THREAD

**Issue by quinnkeast** [sourcegraph/sourcegraph#19095] opened 2021-03-12 12:34 UTC
#### Steps to reproduce:

1. Make sure contexts are enabled (add your own repos).
2. Run a search query with a context that is public but has no repos (e.g. a Sourcegraph team member who hasn't added repos).

#### Expected behavior:

A message saying no results were found, and perhaps the suggestion to try searching with the `global` context instead.

#### Actual behavior:

The user is shown a message implying they should add repositories to see results in this context.

![image](https://user-images.githubusercontent.com/6304497/110940623-80117600-8337-11eb-99ee-799f06b3d0a2.png)

**Comment by malomarrec** [comment] 2021-04-19 19:26
Tagging similar issue in #20138 to feed into prioritisation work.

**Comment by lguychard** [comment] 2021-08-25 08:13
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/21616

**Closed by lguychard** 2021-08-25 08:13 UTC
Labels: bug, team/search, team/search-product
