### ISSUE TITLE
Cursor position hopping when navigating pages

### ISSUE THREAD

**Issue by jjinnii** [sourcegraph/sourcegraph#30252] opened 2022-01-26 16:38 UTC
#### Steps to reproduce:

Based on [internal feedback with video](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1643192047061600).

#### Expected behavior:

Cursor position should be set to end of search query on all pages, unless a user manually sets cursor position elsewhere. 

#### Actual behavior:

Cursor position jumps to start of search query when entering a search from the VSCE homepage and moving to search results page. However, if a user enters a new search from the search results page, the cursor position follows expected behavior, and cursor position correctly sets to end of search query.

**Comment by abeatrix** [comment] 2022-01-28 19:51
Fixed issue where:
#### 1.opening the SG VSCE does not focus on textarea ([mentioned in beyang's feedback](https://sourcegraph.slack.com/archives/C02E3HHDZ98/p1642177766009800))
  - root cause: we are loading search page before sidebar, so when sidebar comes online it removed the focus on search page
  - fix: load sidebar first before search page to make sure search page gets the focus
#### 2. cursor position hopping after search submitted 
- root cause: A new search bar is being used after a search query has been submitted by pressing enter
- fix: use the same search bar component and don't rerender the search bar again after a search has been performed

**Comment by abeatrix** [comment] 2022-02-04 16:20
This issue occurs again in the latest build as we have refactored the webview components. 
Current issues include:
1. search bar is not focused after submitting a search query
![cursor-not-focused](https://user-images.githubusercontent.com/68532117/152563206-a8c88737-cb8b-45b8-9230-7a64305875db.gif)
![search-not-focused](https://user-images.githubusercontent.com/68532117/152563225-20681365-c265-4248-b90d-fd7840312533.gif)

2. Applying filters from sidebar takes away the focus from search bar with no suggestions
![filter](https://user-images.githubusercontent.com/68532117/152564020-a280ccac-f631-48ec-a42d-8dedf592e26c.gif)
expected behavior: 
![filter-expected](https://user-images.githubusercontent.com/68532117/152564238-75e783a3-4c6d-4523-b397-46cec000f45a.gif)

3.  Search bar not focused when moving between tabs [resolved]
- resolved by @tjkandala

**Comment by tjkandala** [comment] 2022-02-04 16:40
I unfortunately cannot reproduce these issues :(. I'll try to get on another computer to see if there's some environmental cause

https://user-images.githubusercontent.com/37420160/152567455-8f558fce-5349-4307-b4f9-778a5a7ee22e.mov

https://user-images.githubusercontent.com/37420160/152567460-e1d51028-cef4-44ac-a918-ecb2d20a254d.mov

**Comment by abeatrix** [comment] 2022-02-04 16:56
@tjkandala Just joking. I just rebuilt it with the changes you added yesterday and now everything working as expected (except search types) 😅  Thanks for checking!!

**Comment by tjkandala** [comment] 2022-02-04 16:59
LOL no problem, and I think search types don't trigger focus on web either?

**Comment by abeatrix** [comment] 2022-02-04 19:26
> LOL no problem, and I think search types don't trigger focus on web either?

It works for me on Web 🤔 
![image](https://user-images.githubusercontent.com/68532117/152586133-ce0915d7-4890-40d4-8c51-7de6f2e7d597.png)

Also I was joking 🥴   I just realized the rebuild includes a hack I added to make it work. The issue still exists using the latest codes in [tjk/vsce-search-ui ](https://github.com/sourcegraph/sourcegraph/tree/tjk/vsce-search-ui) 😢

**Comment by tjkandala** [comment] 2022-02-04 19:50
I asked some other people to try to reproduce and they couldn't. I remember that we determined that the body was focused on submit, right? Can you add a focus event listener 
`document.body.addEventListener('focus', event => console.log(event))`
in the console? I'm curious what the [`relatedTarget`](https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent/relatedTarget) is

**Comment by tjkandala** [comment] 2022-04-20 16:28
We fixed this before v1 release, if you observe similar issues again feel free to re-open

**Closed by tjkandala** 2022-04-20 16:28 UTC
Labels: bug, team/integrations, vscode-extension
