### ISSUE TITLE
Version contexts: repos with `"rev": "HEAD"` do not use the indexed search path

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12064] opened 2020-07-09 22:33 UTC
Reported by https://app.hubspot.com/contacts/2762526/company/693777200

See discussion at https://sourcegraph.slack.com/archives/CHEKCRWKV/p1594333536054100

Notes:
> On the call, I asked the contact to:
> * Run the same search as above `X count:1000` with the version context (which is 100% repos at `"rev": "HEAD"`) and they hit the same 504
> * Run the same search `X count:1000` without a version context, and it returned instantly (despite having more repos included)
> * Run the same search again, with the version context, but also with `index:only`, and it failed with “No results”

**Comment by keegancsmith** [comment] 2020-07-10 13:00
This is a known issue in the code, where if you search a repo for HEAD and anything else, we end up not using indexed search. It is relatively easy to fix, but has some potential strange interactions with our reporting. All our code that reports timeouts/missing/etc is just based on the repo name, not on repo and revision. However, clearly those edge cases are not that bad compared to not using indexed search. I'll investigate this fix next week since it is touching code I rewrote last week :)

Here is a link to the code currently which explicitly calls this out:
https://github.com/sourcegraph/sourcegraph/blob/7b5cbd9dfcaa5e279ff8f6294d58e1f0dbecfa4b/cmd/frontend/graphqlbackend/zoekt.go#L644-L646

**Comment by dadlerj** [comment] 2020-07-10 14:37
Interesting, thanks! From this thread a few weeks ago, I thought `HEAD` would work here? https://sourcegraph.slack.com/archives/C0B2RU51Q/p1590709518461900?thread_ts=1590699734.460300&cid=C0B2RU51Q

If that's not the case, that's fine, but I'd then prioritize being able to use the indexed search path from version contexts (if an index exists, e.g. for `HEAD` of default branch) above even getting multiple versions indexed. But I'm not 100% sure about that and it might depend on how long it would take.

Thanks for owning next steps here, let me know if I can help any more.

**Comment by keegancsmith** [comment] 2020-07-11 07:48
> Interesting, thanks! From this thread a few weeks ago, I thought
> `HEAD` would work here?

"HEAD" should work. The problem is if there are any other version
context entries for the same repo we end up not using indexed search.

> If that's not the case, that's fine, but I'd then prioritize being
> able to use the indexed search path from version contexts (if an index
> exists, e.g. for `HEAD` of default branch) above even getting multiple
> versions indexed. But I'm not 100% sure about that and it might depend
> on how long it would take.

It should be working, but given we had a few weird surprises in this
code path I'll do a bit of intensive testing to make sure there are no
surprises.

**Comment by keegancsmith** [comment] 2020-07-14 13:54
I have a fix for this in #12154. However, we will be indexing all version context branches going forward so this might not be as important to fix since the branches should be indexed.

**Closed** 2020-07-16 20:20 UTC
Labels: RFC-136, team/search
