### ISSUE TITLE
Code Insights: Creation UI pages do not focus Monaco query like input if it's a first invalid field

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#28653] opened 2021-12-06 21:00 UTC
## Context

In the code insight creation UI pages we have a form logic that if a user clicks on submit button and this user hasn't filled in all fields properly our form autofocus a first invalid input. Since we use Monaco query input for the search query field and Monaco isn't native browser input our logic inside the useForm hook doesn't handle this case properly. As a result, if the search query field wasn't filled in correctly and the user clicks submit button nothing will happen. 

Steps to reproduce
- Go to search-based creation UI
- Fill in all fields correctly except the data series query field
- Click on submit button 
- See that search field wasn't focused by page automatically

Expected behavior 
- Go to search-based creation UI
- Fill in all fields correctly except the data series query field
- Click on submit button 
- See that search field is focused by page automatically

**Comment by fkling** [comment] 2022-07-04 18:51
FWIW, I just confirmed that this is still an issue when using CodeMirror (but maybe not surprising since it tried to be API compatible).

**Comment by taylorsperry** [comment] 2024-01-09 00:40
@vovakulikov @fkling this is sol old that I'm just going to go ahead and close it. If we need to reopen, lmk.

**Closed by taylorsperry** 2024-01-09 00:40 UTC
Labels: bug, webapp, spike, code-insights
