### ISSUE TITLE
Confetti after find-references has wrong z-index

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#5657] opened 2019-09-19 01:04 UTC
Confetti that appears after find-refs onboarding step should be *in front* of everything, instead of behind the code view:

![confetti-appears-after-find-refs](https://user-images.githubusercontent.com/1646931/65201390-84a8e700-da3e-11e9-80cb-2b0fd3f4e46f.png)

Repro steps:
* Run a local dev instance off master
* Check out the branch `bl/regression-onboarding`
* cd `web`
* Run `SOURCEGRAPH_SUDO_TOKEN='$YOURS' SOURCEGRAPH_SUDO_USER='$YOURS' GITHUB_TOKEN=$(cat ../../dev-private/enterprise/dev/external-services-config.json | grep sqs-test | sed "s/.*: \"\(.*\)\".*/\1/") SOURCEGRAPH_BASE_URL=http://localhost:3080 yarn run test-regression -t Onboarding` (replace $SOURCEGRAPH_SUDO_TOKEN and $SOURCEGRAPH_SUDO_USER with admin user token and username from your local instance)

**Comment by lguychard** [comment] 2020-02-24 14:01
Duplicate of #8527 which is more generic, let's track there.

**Closed by lguychard** 2020-02-24 14:01 UTC
Labels: bug, webapp
