### ISSUE TITLE
Diff/commit search should still show how many repositories timed out when a single repo error occurred

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#5520] opened 2019-09-09 22:46 UTC
### Problem

The following query shows an error for an empty repository, but fails to tell me how many repositories have timed out (in fact, almost all of them have -- see https://github.com/sourcegraph/sourcegraph/issues/5519):

https://k8s.sgdev.org/search?q=type:diff+jre8+timeout:2m

![image](https://user-images.githubusercontent.com/3173176/64571399-a3113300-d318-11e9-8815-6c44e6996aa9.png)

### Solution

We should always show how many repositories timed out, not just the error. i.e. the fact that a single repository was failed in our search should not affect the other potential results in this case.

Next steps: investigate why we aren't showing the # of timed out repositories here.

Reported by a user at https://app.hubspot.com/contacts/2762526/company/407948923

**Comment by slimsag** [comment] 2019-11-18 21:41
We just encountered this again with two different states: corrupt and empty repositories. In these states, diff/commit search fails entirely and you just get a single error like this:

```
1 error occurred: * commit search failed: failed to search commit log REDACTED@: git command [git show --no-patch --no-merges -z --decorate=full --format=format:%H%x00%D%x00%aN%x00%aE%x00%at%x00%cN%x00%cE%x00%ct%x00%B%x00%P%x00 --no-prefix --max-count=31 --extended-regexp --regexp-ignore-case --all-match --grep=REDACTED --all-match --author= --extended-regexp --] failed (output: ""): exit status 128 (stderr: "fatal: your current branch 'master' does not have any commits yet")
```

```
1 error occurred: * diff search failed: failed to search commit diffs REDACTED@: git command [git log --no-prefix --max-count=31 --unified=0 --extended-regexp --regexp-ignore-case --all-match --author= -z --no-abbrev-commit --format=oneline --no-color --source --no-patch --no-merges -GREDACTED --regexp-ignore-case --pickaxe-regex --extended-regexp --] failed (output: ""): exit status 128 (stderr: "error: packfile .git/objects/pack/pack-REDACTED.pack does not match ... (truncated)")
```

This should not fail the entire search.

**Comment by tsenart** [comment] 2020-01-14 08:30
@rvantonder: Checking in on this one. Are you going to have time to get this in for 3.12?

**Comment by rvantonder** [comment] 2020-01-14 20:17
> Next steps: investigate why we aren't showing the # of timed out repositories here.

I'm allocating 2 hours to investigate the issue and if it's low complexity will attempt a fix.

**Comment by rvantonder** [comment] 2020-01-14 20:21
FYI @slimsag I cannot reproduce from the link above, I see:

<img width="1205" alt="Screen Shot 2020-01-14 at 1 20 36 PM" src="https://user-images.githubusercontent.com/888624/72379452-b110ff00-36d0-11ea-9a8c-9800a1da3629.png">
I will

**Comment by rvantonder** [comment] 2020-01-14 20:24
> We should always show how many repositories timed out, not just the error. 

Or is the actual issue that instead of the above error, we want to show timed out repos if that happens? Either way, that search example fails immediately (there is no 2 minute timeout applied), so we need a different query to surface this behavior.

**Comment by tsenart** [comment] 2020-01-15 09:35
> so we need a different query to surface this behavior.

What would that query be? Is this issue still relevant if we now limit diff searches to 50 repos?

**Comment by keegancsmith** [comment] 2020-01-15 19:06
I can't reproduce this on sgtest/empty on sourcegraph.com https://sourcegraph.com/search?q=type:commit+jre8+timeout:2m+repo:github.com/sgtest/empty&patternType=literal

Is it possible this has been fixed?

**Comment by rvantonder** [comment] 2020-01-15 19:09
My guess is it's 'fixed' AKA suppressed because this search query is hitting the 50 repo cap on sourcegraph or sgdev instances. I _suspect_ that this _might_ surface if (a) the instance has less than 50 repos and (b) one of those repos is empty.

**Comment by keegancsmith** [comment] 2020-01-15 19:17
The example query I gave above has a sufficiently limited repo scope so that it actually runs + it runs on an empty repo.

**Comment by rvantonder** [comment] 2020-01-15 19:21
Ah, missed that. OK.

**Comment by beyang** [comment] 2020-01-16 01:17
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by tsenart** [comment] 2020-01-16 19:45
Closing this since it can't be reproduced (as @keegancsmith pointed out).

**Closed by tsenart** 2020-01-16 19:45 UTC
Labels: bug, customer, search, team/core-services
