### ISSUE TITLE
bundled alertmanager does not start up correctly in some environments with clustering enabled

### ISSUE THREAD

**Issue by nkiesel** [sourcegraph/sourcegraph#13079] opened 2020-08-17 22:11 UTC
Using `docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph sourcegraph/server:3.18.0` on Debian unstable 64bit with "Docker version 19.03.12, build 48a6621".

System starts up and shows "Sourcegraph is ready at: http://127.0.0.1:7080".  About 22 seconds later, It says "Terminating prometheus
prometheus died. Shutting down..." and instance terminates.  This is happening w/o even a login attempt.

`prometheus.log` shows:
```
t=2020-08-17T22:04:29+0000 lvl=info msg="running: [/prometheus.sh --web.listen-address=0.0.0.0:9092]" cmd=prom-wrapper
t=2020-08-17T22:04:29+0000 lvl=info msg="running: [/alertmanager.sh --config.file=/sg_config_prometheus/alertmanager.yml --web.route-prefix=/alertmanager]" cmd=prom-wrapper
t=2020-08-17T22:04:29+0000 lvl=info msg="waiting for alertmanager" cmd=prom-wrapper
level=info ts=2020-08-17T22:04:30.126Z caller=main.go:216 msg="Starting Alertmanager" version="(version=0.21.0, branch=HEAD, revision=4c6c03ebfe21009c546e4d1e9b92c371d67c021d)"
level=info ts=2020-08-17T22:04:30.126Z caller=main.go:217 build_context="(go=go1.14.4, user=root@dee35927357f, date=20200617-08:54:02)"
level=warn ts=2020-08-17T22:04:30.134Z caller=cluster.go:154 component=cluster err="couldn't deduce an advertise address: no private IP found, explicit advertise addr not provided"
level=error ts=2020-08-17T22:04:30.138Z caller=main.go:241 msg="unable to initialize gossip mesh" err="create memberlist: Failed to get final advertise address: No private IP address found, and explicit IP not provided"
t=2020-08-17T22:04:30+0000 lvl=eror msg="command [/alertmanager.sh --config.file=/sg_config_prometheus/alertmanager.yml --web.route-prefix=/alertmanager] exited: exit status 1" cmd=prom-wrapper
level=info ts=2020-08-17T22:04:30.160Z caller=main.go:295 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-08-17T22:04:30.161Z caller=main.go:331 msg="Starting Prometheus" version="(version=2.16.0, branch=HEAD, revision=b90be6f32a33c03163d700e1452b54454ddce0ec)"
level=info ts=2020-08-17T22:04:30.161Z caller=main.go:332 build_context="(go=go1.13.8, user=root@7ea0ae865f12, date=20200213-23:50:02)"
level=info ts=2020-08-17T22:04:30.161Z caller=main.go:333 host_details="(Linux 5.7.0-2-amd64 #1 SMP Debian 5.7.10-1 (2020-07-26) x86_64 78ac6066f06f (none))"
level=info ts=2020-08-17T22:04:30.161Z caller=main.go:334 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-08-17T22:04:30.161Z caller=main.go:335 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-08-17T22:04:30.165Z caller=main.go:661 msg="Starting TSDB ..."
level=info ts=2020-08-17T22:04:30.165Z caller=web.go:508 component=web msg="Start listening for connections" address=0.0.0.0:9092
level=info ts=2020-08-17T22:04:30.180Z caller=head.go:577 component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2020-08-17T22:04:30.182Z caller=head.go:625 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2020-08-17T22:04:30.187Z caller=main.go:676 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-08-17T22:04:30.187Z caller=main.go:677 msg="TSDB started"
level=info ts=2020-08-17T22:04:30.187Z caller=main.go:747 msg="Loading configuration file" filename=/sg_config_prometheus/prometheus.yml
level=info ts=2020-08-17T22:04:30.530Z caller=main.go:775 msg="Completed loading of configuration file" filename=/sg_config_prometheus/prometheus.yml
level=info ts=2020-08-17T22:04:30.530Z caller=main.go:630 msg="Server is ready to receive web requests."
t=2020-08-17T22:05:00+0000 lvl=crit msg="unable to reach Alertmanager" cmd=prom-wrapper error="alertmanager not reachable: Get \"http://127.0.0.1:9093/alertmanager/api/v2/status\": context deadline exceeded (last error: Get \"http://127.0.0.1:9093/alertmanager/api/v2/status\": dial tcp 127.0.0.1:9093: connect: connection refused)"
```

**Comment by slimsag** [comment] 2020-08-18 00:46
@nkiesel does our latest `3.19.0-rc.1` work for you?

@bobheadxi any idea what may be causing this?

@uwedeportivo @pecigonzalo I will tag this as a release blocker for now, we can remove if we find this isn't a major issue / doesn't affect all users of `sourcegraph/server`

**Comment by nkiesel** [comment] 2020-08-18 00:50
Nope, I already tried `3.19.0-rc.1` but that shows the same behavior.

I am currently trying the "docker-compose" route and that seems to work.  I do have other problems there though.  What is the correct place to ask these? Feels wrong to create an issue because most likely is just stupidity on my end.  Is there a public slack channel or something else?  Concrete Q: "I have a self-hosted gitlab with tons of repos.  I only want to use a subset of them, but even with `"id": 123` is starts cloning all of them.

**Comment by bobheadxi** [comment] 2020-08-18 00:51
this looks like alertmanager failing to start due to misconfiguration on Server, attempting to reproduce now - since the command you are using does not seem to use any additional config, seems unlikely to be user error :)

**Comment by slimsag** [comment] 2020-08-18 00:53
@nkiesel thanks for the additional info. You can file questions as GitHub issues or send to our support@sourcegraph.com address and we’ll follow up :)

**Comment by bobheadxi** [comment] 2020-08-18 02:05
@nkiesel I am unable to reproduce this (macos), and we have an internal deployment of Sourcegraph Server that is working fine. I suspect this is related to something like [this](https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/4556) or https://github.com/prometheus/alertmanager/issues/1610, where Alertmanager fails to deduce an appropriate address to advertise on (since clustering is enabled by default)

Can you try setting the following environment variable (with the `-e` flag for docker run) and let me know if this works for you?

```
ALERTMANAGER_ADDITIONAL_FLAGS="--cluster.listen-address="
```

This will disable Alertmanager's clustering feature.

**Comment by bobheadxi** [comment] 2020-08-18 02:07
Marking this as not a release blocker for now, but some potential followups - either:

* disable Alertmanager clustering by default for 3.20 (in a way such that it can be enabled)
* add documentation about this issue and solution

**Comment by nkiesel** [comment] 2020-08-18 06:58
Adding `-e ALERTMANAGER_ADDITIONAL_FLAGS="--cluster.listen-address="` works.

**Comment by bobheadxi** [comment] 2020-08-25 00:33
Thank you for reporting this and testing out the flag, @nkiesel !

**Closed** 2020-08-25 00:33 UTC
Labels: bug, planned/3.20, team/distribution
