### ISSUE TITLE
Phabricator native integration: CSP violation

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#4111] opened 2019-05-17 22:16 UTC
I was following the testing docs at https://docs.sourcegraph.com/dev/phabricator_gitolite#testing

- Run Sourcegraph v3.4.0-rc.4 in Docker
- Run `./dev/phabricator/start.sh latest`
- Run `ngrok http 7080`
- Set Phabricator config, Sourcegraph site config, and create a Phabricator external service on Sourcegraph (see screenshots below)
- Visit a file on Phabricator, open the browser console and notice this error:

> phabricator.bundle.js:186 Refused to create a worker from 'blob:https://127.0.0.1/99124cfb-fe8b-4ffb-b953-c0d09e3da847' because it violates the following Content Security Policy directive: "script-src 'self' https://127.0.0.1 https://22744c70.ngrok.io". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

![image](https://user-images.githubusercontent.com/1387653/57957659-d9cac580-78b1-11e9-9612-29f497f8f26e.png)

![image](https://user-images.githubusercontent.com/1387653/57958889-45af2d00-78b6-11e9-9edd-81b142d0e38c.png)

`blob:https://127.0.0.1/99124cfb-fe8b-4ffb-b953-c0d09e3da847` seems wrong because https://developer.mozilla.org/en-US/docs/Web/API/Blob has an example that looks like `blob:d3958f5c-0777-0845-9dcf-2cb28783acaf` and https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used seems to say that `blob:https://...` is invalid.

Did I configure something incorrectly?

Config screenshots:

![image](https://user-images.githubusercontent.com/1387653/57957668-e64f1e00-78b1-11e9-9d32-f8d6301a2dfe.png)

![image](https://user-images.githubusercontent.com/1387653/57957696-05e64680-78b2-11e9-9de4-8c4dd7285072.png)

![image](https://user-images.githubusercontent.com/1387653/57957716-1e566100-78b2-11e9-9095-24a8879074cd.png)

**Comment by beyang** [comment] 2019-05-18 00:26
Moving this to 3.4-c, as this likely only affects 2 customers, both of which are waiting for greenlight from us to upgrade.

**Comment by lguychard** [comment] 2019-05-20 12:18
I believe this is a dupe of https://github.com/sourcegraph/sourcegraph/issues/2415. 

I also believe that this wouldn't impact our customers, who don't run Phabricator `latest`. We should still ensure we work correctly on recent Phabricator versions, and at the very least document the most recent supported version.

**Comment by beyang** [comment] 2019-05-20 15:58
Closing as dupe of https://github.com/sourcegraph/sourcegraph/issues/2415

**Closed by beyang** 2019-05-20 15:58 UTC
Labels: browser-extension, phabricator
