### ISSUE TITLE
Missing email.smtp configuration warning points to broken documentation 

### ISSUE THREAD

**Issue by has-n** [sourcegraph/sourcegraph#47586] opened 2023-02-14 05:15 UTC
- **Sourcegraph version:** App 
- **Platform information:** MacOS

#### Steps to reproduce:

1. on fresh install, a warning is shown that `email.smtp` is not configured. The documentation links to [http://localhost:3080/help/admin/config/email](http://localhost:3080/help/admin/config/email) which is broken.

![image](https://user-images.githubusercontent.com/40180234/218645480-583a6235-e6ce-40e0-8d20-464edc276619.png)

![image](https://user-images.githubusercontent.com/40180234/218645617-9b4c998b-6c1e-4154-8611-8bee856db28a.png)

**Comment by slimsag** [comment] 2023-02-28 23:34
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/47906

**Closed by slimsag** 2023-02-28 23:34 UTC
