### ISSUE TITLE
Firefox extension should ask for limited URL access

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4508] opened 2019-06-13 22:12 UTC
The Firefox chrome extension currently asks for access to all websites. It should be updated to ask for the same limited set of sites that the Chrome extension asks for.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@4d84cd2b62888f584c514e67e46119dff43a3049/-/blob/browser/scripts/tasks.ts#L84:31

We originally wanted to use limited access but because of https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1382953 it made the on-boarding flow really terrible for users. This issue is fixed so we can revisit.

**Comment by felixfbecker** [comment] 2019-08-07 08:50
This is a duplicate of #760

**Closed by felixfbecker** 2019-08-07 08:50 UTC
Labels: browser-extension, code-nav, firefox
