### ISSUE TITLE
Rev dropdown doesn't close when repo dropdown opens, and vice versa

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#1867] opened 2019-01-14 16:06 UTC
- Navigate to a repository page
- Open the repository dropdown
- Open the revision dropdown
- Witness the repository dropdown stays open

Same behaviour if opening revision dropdown before repository dropdown.

_Expected behaviour_: rev/repo dropdown display is mutually exclusive.

Related: #1843 

![image](https://user-images.githubusercontent.com/1741180/51124535-cc77ce80-181e-11e9-87af-375650fe2e4d.png)

**Comment by sqs** [comment] 2019-01-14 16:08
Dupe of #1736

**Closed by sqs** 2019-01-14 16:08 UTC
