### ISSUE TITLE
Chrome extension broken on PR

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#2675] opened 2019-03-11 15:57 UTC
The Chrome extension hovers do not seem to work on https://github.com/sourcegraph/sourcegraph/pull/2672/files. No errors appear in the JS console.

**Comment by lguychard** [comment] 2019-03-11 16:02
![image](https://user-images.githubusercontent.com/1741180/54138109-2364e300-441f-11e9-8d79-19a5c53a33d1.png)

@beyang could not reproduce this, with either the prod extension or my debug extension from the latest master, on either the base or head part of the PR.

Which Sourcegraph URL is your extension pointing to?

If you run `localStorage.debug = true; location.reload()`, do you see the extension debug menu? Is `sourcegraph/go` active?

**Comment by beyang** [comment] 2019-03-11 16:16
Can you try this repro:
* Go to https://github.com/sourcegraph/sourcegraph/pull/2672/files
* Click one of the "expand hunk" buttons
* Check that the hover no longer works
* Refresh the page (ctrl-r)
* Check that the hover still no longer works

**Comment by felixfbecker** [comment] 2019-06-05 11:07
Cannot repro

![image](https://user-images.githubusercontent.com/10532611/58951967-cb761800-8792-11e9-9dda-839301409e3d.png)

@beyang does this still happen to you?

**Comment by lguychard** [comment] 2019-08-30 10:42
I can't reproduce this with the latest prod Chrome extension, this is pretty old, so closing.

**Closed by lguychard** 2019-08-30 10:42 UTC
Labels: browser-extension, bug, code-nav
