### ISSUE TITLE
Add support for parsing pom.xml (JVM dependencies)

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#32660] opened 2022-03-16 09:50 UTC

**Comment by efritz** [comment] 2022-05-13 14:26
[Slack context with implementation details](https://sourcegraph.slack.com/archives/C032G1CLM7X/p1652371566688969). From this thread:

A published Maven package typically contains the following artifacts:
- `pom.xml` metadata about the package, similar to package.json for JS/TS 
- `PACKAGE_NAME.jar` the compiled bytecode, what you run in production
- `PACKAGE_NAME-sources.jar` the code we display in package repos

Coursier can resolve the dependency tree of Maven packages. The cli interface has a `resolve --tree` option and the library API gives you full structured access to the data.

```
❯ cs resolve --tree 'com.amazonaws:aws-java-sdk:1.12.122'  | head
  Result:
└─ com.amazonaws:aws-java-sdk:1.12.122
   ├─ com.amazonaws:aws-java-sdk-accessanalyzer:1.12.122
   │  ├─ com.amazonaws:aws-java-sdk-core:1.12.122
   │  │  ├─ com.fasterxml.jackson.core:jackson-databind:2.12.3
   │  │  │  ├─ com.fasterxml.jackson.core:jackson-annotations:2.12.3
   │  │  │  └─ com.fasterxml.jackson.core:jackson-core:2.12.3
   │  │  ├─ com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.12.3
   │  │  │  ├─ com.fasterxml.jackson.core:jackson-core:2.12.3
   │  │  │  └─ com.fasterxml.jackson.core:jackson-databind:2.12.3
   │  │  │     ├─ com.fasterxml.jackson.core:jackson-annotations:2.12.3
```

Since JVM package repos correspond one-to-one with Maven packages, we could encode this dependency graph via repo->repo edges.

**Comment by stefanhengl** [comment] 2022-05-16 13:53
@olafurpg and I chatted today about how to implement dependency search for Java.

Constraints:
- The dependency resolution has to be fast because it is on the query path

Why don't we just call out to Coursier?
- Coursier is a dependency resolver, however it's resolution might differ from what is actually running in production because customers might use another resolver in their build pipline.
- Coursier is potentially too slow for being on the query path.

Approach:
- Dependency search should hook into the same table that LSIF uses to store dependencies. Customer that want dependency search have to set up precise code-intel which would give them precise code navigation and dependency search at the same time.
- We could use LSIF data as a fallback for all other supported languages if lockfiles are missing.

**Comment by tsenart** [comment] 2022-05-16 13:58
This approach is what @efritz and @mrnugget are already implementing as far as I'm aware!

**Comment by olafurpg** [comment] 2022-05-16 14:08
> Why don't we just call out to Coursier?

The main reason to not use Coursier is that Coursier can only resolve artifacts that have already been published to a Maven repository like Nexus or Artifactory. Coursier can't resolve an arbitrary Gradle/Maven/sbt codebase, you need to run the dependency resolvers of those build tools instead. However, we can run Coursier for JVM dependency repos and we could generate lockfiles for those repos similar to how we already generate `lsif-java.json`.

**Comment by mrnugget** [comment] 2022-05-19 11:55
> Constraints:
> 
> * The dependency resolution has to be fast because it is on the query path

Just want to comment on this specifically: I think this should no longer be a constraint.

@efritz and I are already working on moving the indexing of lockfiles to the background and from a UX standpoint it's also preferred, I think.

(Additionally, from what I could gather from customers (in Tiger Team conversations), it sounds like customers are absolutely fine with an explicit indexing step (and even want to provide additional data to be used in a dependency graph)))

**Comment by stefanhengl** [comment] 2022-05-23 09:24
@efritz can we close this. I believe this ticket turned out to be duplicate of https://github.com/sourcegraph/sourcegraph/issues/31638?

**Comment by efritz** [comment] 2022-05-23 12:59
@stefanhengl I don't think it's a directly duplicate. #31638 only handles things that have been auto-indexed, where reading the pom/gradle config from the lockfiles service would allow us to index dependencies on instances w/o LSIF support today.

**Closed** 2022-12-06 10:04 UTC
Labels: team/search-core
