### ISSUE TITLE
Codeowners file service supports resolving owners to {users, teams, github accounts, ...}

### ISSUE THREAD

**Issue by cbart** [sourcegraph/sourcegraph#47431] opened 2023-02-07 14:04 UTC

**Comment by eseliger** [comment] 2023-02-26 02:43
I think this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/46599 which has much more details, correct? 

If so, feel free to close this one :)

**Closed** 2023-03-01 05:51 UTC
