### ISSUE TITLE
Unable to get chrome extension working on private gitlab.com typescript repro

### ISSUE THREAD

**Issue by thinktopdown** [sourcegraph/sourcegraph#3033] opened 2019-03-28 22:48 UTC
- **Sourcegraph version:**
3.2.0

- **Platform information:** 
macOS 10.14
chrome Version 73.0.3683.86 (Official Build) (64-bit)
srcgrph ext v19.3.22.1110
Docker version 18.09.0, build 4d60db4

#### Steps to reproduce:

1. setup local srcgraph instance and typescript server via docker compse

```
version: '3'
services:
  sourcegraph:
    ports:
    - "7080:7080"
    - "2633:2633"
    volumes:
    - ~/.sourcegraph/config:/etc/sourcegraph
    - ~/.sourcegraph/data:/var/opt/sourcegraph
    image: sourcegraph/server:3.2.0
  typescript-lang:
    ports:
      - "7081:8080"
    image: sourcegraph/lang-typescript
```

2. configure srcgraph instance to work on gitlab.com using a personal access token.

3. enable private repos

4. configure global settings for ts lang server
{
"typescript.serverUrl": "ws://localhost:7081",
"typescript.sourcegraphUrl":"http://sourcegraph:7080"
}

4. verify "find refs/jump def" at http://localhost:7080

5. open chrome. add srcgraph extension.

6. give srcgrph chrome ext access to https://gitlab.com/*

7. connect srcgrph chrome ext to http://localhost:7080

8. open private PR on gitlab.com for enabled repro. 

#### Expected behavior:

- see "jump def/find refs" popup for my private gitlab repro

#### Actual behavior:

- doesn't appear. can't seem to find any logs...

**Comment by thinktopdown** [comment] 2019-03-28 22:54
working locally:
[
![Screen Shot 2019-03-28 at 10 53 04 PM](https://user-images.githubusercontent.com/81072/55198047-5c85ad00-51ac-11e9-9f1f-a6a5ed4b483f.png)
](url)

**Comment by thinktopdown** [comment] 2019-03-28 22:55
![Screen Shot 2019-03-28 at 10 55 02 PM](https://user-images.githubusercontent.com/81072/55198088-8c34b500-51ac-11e9-9dff-63ba8d7ca681.png)

**Comment by thinktopdown** [comment] 2019-03-29 16:13
![Screen Shot 2019-03-29 at 4 12 17 PM](https://user-images.githubusercontent.com/81072/55246640-876c1180-523d-11e9-9759-012763853777.png)

**Comment by ryan-blunden** [comment] 2019-03-29 17:04
@thinktopdown Thanks for all the info, I'll recreate your setup now to find out what's going on.

**Comment by ryan-blunden** [comment] 2019-03-29 23:58
Your configuration looks correct and I'm able to get it working which means the extension is likely in some weird state.

Could you: 

1. Take a screenshot/recording of the [extension console and network activity](https://docs.sourcegraph.com/integration/browser_extension#viewing-browser-extension-console-and-network-activity-in-chrome) and attach it to this issue.
1. Take a screenshot of the options panel when right-clicking on the extension icon.

I've added [more troubleshooting sections](https://docs.sourcegraph.com/integration/browser_extension#troubleshooting) to the browser extension page but it seems you've tried most of those.

As a result of some intensive testing by @chrismwendt and myself today, we've created a couple of issues for improving the extension configuration process (#3056, #3052)

**Comment by thinktopdown** [comment] 2019-04-23 03:06
sorry for delays on my end. i paused work on this since it was taking longer than expected to get it working. i'll follow up on above this week

**Comment by thinktopdown** [comment] 2019-04-23 03:13
getting a 521 error from:
https://docs.sourcegraph.com/integration/browser_extension#viewing-browser-extension-console-and-network-activity-in-chrome

i'll try again later

**Comment by sqs** [comment] 2019-04-23 04:01
@thinktopdown Looks like a blip - it’s back up now, sorry about that.

**Comment by felixfbecker** [comment] 2019-06-05 10:56
Hi @thinktopdown, is this still an issue?

**Comment by thinktopdown** [comment] 2019-07-22 20:34
i need to retry when i get a chance to eval this again

**Comment by lguychard** [comment] 2020-03-19 12:37
@thinktopdown we haven't been able to reproduce so I'm going to close this. Feel free to reopen if you have a reproducible scenario.

**Closed by lguychard** 2020-03-19 12:37 UTC
Labels: browser-extension, bug, gitlab
