### ISSUE TITLE
JetBrains: add custom notification when the user has no active account

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#56615] opened 2023-09-14 08:25 UTC
I got the "Open Cody" notification when I had 4 accounts in my settings. This happened because none of the accounts are marked as active. We should customize this notification with an action to "Log into" an existing account instead of opening the sidebar. Alternatively, the sidebar should handle this situation and encourage the user to log into one of the accounts instead of using "Sign in for free with sourcegraph.com"  

![Image](https://github.com/sourcegraph/sourcegraph/assets/1408093/ae98c877-e6ee-4b56-afea-81d49e7ac0de)

**Comment by szymonprz** [comment] 2023-09-14 11:47
Closing as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/56615

**Closed by szymonprz** 2023-09-14 11:47 UTC
