### ISSUE TITLE
sourcegraph.com alert: "gitserver: 100+ concurrent command executions (abnormally high load)"

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9355] opened 2020-03-26 21:08 UTC
On Sourcegraph.com, the new alerting has picked up the fact that we regularly exceed 100+ concurrent command executions on gitservers there, e.g. over a 6h period :

![image](https://user-images.githubusercontent.com/3173176/77696495-b610eb00-6f6a-11ea-8d2d-5de0713500b0.png)

[From here](https://sourcegraph.com/-/debug/grafana/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22src_gitserver_exec_running%22,%22interval%22:%221s%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D).

These appear to be occurring at regular 7 minute intervals, unfortunately we don't get much more information than that here. What could these be coming from? Any ideas @keegancsmith ?

I suspect this would cause issues or slowness for users if they try to e.g. run searches at the same time

**Comment by slimsag** [comment] 2020-03-26 21:12
> gitserver: echo command execution duration exceeding 1s

Is also regularly flapping, and may be related?

![image](https://user-images.githubusercontent.com/3173176/77697150-8f06e900-6f6b-11ea-8181-3439d681cc6e.png)

I wonder if the fact that gitserver disks are currently at 10% and are cleaning up old repos has anything to do with this? https://sourcegraph.slack.com/archives/CMBA8F926/p1585255501001700

**Comment by keegancsmith** [comment] 2020-03-27 04:23
I'll investigate this further. We have honeycomb which we pay for and haven't used in months! It would be perfect to find out what is going on here.

**Comment by keegancsmith** [comment] 2020-03-27 14:33
My internet is painfully slow at the moment and nearing the end of the workday for me. I highly recommend exploring our `gitserver-exec` dataset in honeycomb. https://ui.honeycomb.io/sourcegraph/datasets/gitserver-exec

**Comment by uwedeportivo** [comment] 2020-04-14 16:33
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by bobheadxi** [comment] 2020-07-21 23:40
@keegancsmith and I recently noticed a _lot_ of git activity in honeycomb that I'm assuming contributes towards the count that triggers this alert, for example in a 10-minute span:

![image](https://user-images.githubusercontent.com/23356519/88117421-ac805280-cbed-11ea-8581-3cf11c6a1615.png)

@aileenrose took a look at analytics and it seems that the top repo in this span has barely any traffic via sourcegraph.com, so this might be coming from extensions or some other automated source of requests (ie unnecessary git commands in certain paths - https://github.com/sourcegraph/sourcegraph/issues/9359#issuecomment-661712351)

**Comment by bobheadxi** [comment] 2020-07-21 23:48
Possibly related: https://github.com/sourcegraph/sourcegraph/pull/12379

**Comment by bobheadxi** [comment] 2020-08-28 01:26
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/23356519/91510724-82b6fb80-e910-11ea-9e84-bf9f72fff915.png">

https://sourcegraph.com/-/debug/grafana/d/gitserver/git-server?viewPanel=5&orgId=1&from=now-24h&to=now

It looks like https://github.com/sourcegraph/sourcegraph/pull/13386 possibly fixed this!

**Comment by keegancsmith** [comment] 2020-08-28 10:57
yeah this would be the root cause fixed :)

Fixed by #13386

**Closed by keegancsmith** 2020-08-28 10:57 UTC
Labels: bug, dot-com, gitserver, perf, silenced-alert

**Comment by bobheadxi** [comment] 2020-08-28 11:54
unsilencing in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/3303
