### ISSUE TITLE
Regression: Indexed symbol search broken for specific languages

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#10357] opened 2020-05-01 19:28 UTC
Edit: Updated to reflect that indexed symbol search has always been broken for certain languages.

### Regression: Indexed symbol search in 3.15.0 and 3.15.1 broken for specific languages

Haskall, JSONNet, Kotlin, Scala, Swift, Thrift, and TypeScript `type:symbol` searches fail to return results in 3.15.0 and 3.15.1, regardless of whether or not the zoekt-indexserver container is ran as root or not.

### Affected versions

- 3.15.0 and 3.15.1 are affected
- 3.14.1 is not affected

A patched version of 3.15 will be released soon.

### Workarounds

This regression affects only:

- Indexed `type:symbol` searches, you may add `index:no` to your search in order to workaround this issue temporarily.
- Basic code intelligence (hover, find-references, jump-to-definition) only when `basicCodeIntel.indexOnly` is set to `true` in your global/user settings. It is off by default.

#### Workaround for Kubernetes and Docker Compose users only

If you are affected by this change and are running 3.15.1, you may replace your `sourcegraph/search-indexer:3.15.1` image as a temporary workaround:

```diff
-index.docker.io/sourcegraph/search-indexer:3.15.1@sha256:354ed968e62a7d011b647476a63116813aea23bdada0a2fc4322df5381acb6b3
+index.docker.io/sourcegraph/zoekt-indexserver:0.0.20200429072931-1a9304f@sha256:8594efce8a5acb962430e8ac93f2ee5f2c75172f24c1004b25e6fd08dc0f57e0
```

Then, upon the next index of your repositories (once a new git commit has been pushed) the mentioned languages will be indexed once again as expected. If this is not an acceptable timeline, please contact support@sourcegraph.com for further help.

### Explanation

The zoekt image for 3.14.3 includes scala support when ran as root:

```
$ docker run -it --entrypoint=sh -u 0 sourcegraph/zoekt-indexserver:0.0.20200318141948-0b140b7 -c "whoami && ls -lah /.ctags.d && cd / && universal-ctags --list-languages | grep scala"
root
total 32K    
drwxr-xr-x    2 root     root        4.0K Mar 18 14:20 .
drwxr-xr-x    1 root     root        4.0K May  1 18:53 ..
-rw-r--r--    1 root     root         393 Sep  6  2019 additional-languages.ctags
-rw-r--r--    1 root     root         420 Sep  6  2019 haskell.ctags
-rw-r--r--    1 root     root        1.5K Sep  6  2019 kotlin.ctags
-rw-r--r--    1 root     root        1.4K Sep  6  2019 scala.ctags
-rw-r--r--    1 root     root        2.5K Sep  6  2019 swift.ctags
-rw-r--r--    1 root     root        1.2K Sep  6  2019 tsx.ctags
scala
```

Additionally, despite those files being owned by `root` in 3.14.3 it also worked 100% OK when running the container as a non-root user (so this regression _is_ new):

```
$ docker run -it --entrypoint=sh sourcegraph/zoekt-indexserver:0.0.20200318141948-0b140b7 -c "whoami && ls -lah /.ctags.d && cd / && universal-ctags --list-languages | grep scala"
sourcegraph
total 32K    
drwxr-xr-x    2 root     root        4.0K Mar 18 14:20 .
drwxr-xr-x    1 root     root        4.0K May  1 19:17 ..
-rw-r--r--    1 root     root         393 Sep  6  2019 additional-languages.ctags
-rw-r--r--    1 root     root         420 Sep  6  2019 haskell.ctags
-rw-r--r--    1 root     root        1.5K Sep  6  2019 kotlin.ctags
-rw-r--r--    1 root     root        1.4K Sep  6  2019 scala.ctags
-rw-r--r--    1 root     root        2.5K Sep  6  2019 swift.ctags
-rw-r--r--    1 root     root        1.2K Sep  6  2019 tsx.ctags
scala
```

However, the zoekt image for 3.15.1 which is `ef3ec2393b46a046da9ca00d8d63191bf88368d3`:

https://github.com/sourcegraph/sourcegraph/blob/37e9bb8014566e0dc0e2bc73f13f64e931ef72df/docker-images/search-indexer/build.sh#L5-L8

```
$ docker inspect -f '{{.ContainerConfig.Labels}}' sourcegraph/search-indexer:3.15.1
map[org.opencontainers.image.created:2020-04-01T20:30:25Z org.opencontainers.image.revision:ef3ec2393b46a046da9ca00d8d63191bf88368d3 org.opencontainers.image.source:https://github.com/sourcegraph/zoekt]
```

Does NOT contain the same `/.ctags.d` definitions. Instead the files appear to be dumped at `/` instead, where they are not picked up by universal-ctags as they are not in a `.ctags.d` directory:

```
$ docker run -it --entrypoint=sh -u 0 sourcegraph/search-indexer:3.15.1 -c "whoami && ls -lah /.ctags.d && cd / && universal-ctags --list-languages | grep scala"
root
ls: /.ctags.d: No such file or directory
```

```
$ docker run -it --entrypoint=sh -u 0 sourcegraph/search-indexer:3.15.1 -c "whoami && ls -lah / && cd / && universal-ctags --list-languages | grep scala"
root
total 112K   
drwxr-xr-x    1 root     root        4.0K May  1 18:56 .
drwxr-xr-x    1 root     root        4.0K May  1 18:56 ..
-rwxr-xr-x    1 root     root           0 May  1 18:56 .dockerenv
-rw-r--r--    1 root     root         393 Apr  1 20:27 additional-languages.ctags
drwxr-xr-x    2 root     root        4.0K Mar 23 20:12 bin
-rw-r--r--    1 root     root         707 Apr  1 20:27 clojure.ctags
drwxr-xr-x    1 sourcegr sourcegr    4.0K Apr  1 20:30 data
drwxr-xr-x    5 root     root         360 May  1 18:56 dev
drwxr-xr-x    1 root     root        4.0K May  1 18:56 etc
-rw-r--r--    1 root     root         703 Apr  1 20:27 graphql.ctags
-rw-r--r--    1 root     root        1009 Apr  1 20:27 groovy.ctags
-rw-r--r--    1 root     root         420 Apr  1 20:27 haskell.ctags
drwxr-xr-x    1 root     root        4.0K Apr  1 20:30 home
-rw-r--r--    1 root     root         260 Apr  1 20:27 jsonnet.ctags
-rw-r--r--    1 root     root        1.5K Apr  1 20:27 kotlin.ctags
drwxr-xr-x    1 root     root        4.0K Apr  1 20:30 lib
drwxr-xr-x    5 root     root        4.0K Mar 23 20:12 media
drwxr-xr-x    2 root     root        4.0K Mar 23 20:12 mnt
drwxr-xr-x    2 root     root        4.0K Mar 23 20:12 opt
dr-xr-xr-x  311 root     root           0 May  1 18:56 proc
drwx------    2 root     root        4.0K Mar 23 20:12 root
drwxr-xr-x    2 root     root        4.0K Mar 23 20:12 run
drwxr-xr-x    1 root     root        4.0K Apr  1 20:30 sbin
-rw-r--r--    1 root     root        1.4K Apr  1 20:27 scala.ctags
drwxr-xr-x    2 root     root        4.0K Mar 23 20:12 srv
-rw-r--r--    1 root     root        2.5K Apr  1 20:27 swift.ctags
dr-xr-xr-x   13 root     root           0 May  1 18:56 sys
-rw-r--r--    1 root     root         529 Apr  1 20:27 thrift.ctags
drwxrwxrwt    2 root     root        4.0K Mar 23 20:12 tmp
-rw-r--r--    1 root     root        1.2K Apr  1 20:27 tsx.ctags
drwxr-xr-x    1 root     root        4.0K Mar 23 20:12 usr
drwxr-xr-x   12 root     root        4.0K Mar 23 20:12 var
```

### When was this introduced?

[commit comparison](https://github.com/sourcegraph/zoekt/compare/0b140b7...ef3ec23) shows this regression was introduced with how we moved Dockerfiles from sourcegraph/infrastructure to sourcegraph/zoekt, specifically with the introduction of this line:

https://github.com/sourcegraph/zoekt/compare/0b140b7...ef3ec23#diff-326cbc18ca6cfceca38b073ac3b65267R16

### Related change and attempts to fix

@keegancsmith picked up on this in https://github.com/sourcegraph/sourcegraph/issues/9756#issuecomment-621028553 but thought it only affected non-root users, this is not the case.

His fixes there did solve the issue for when zoekt-indexserver is running as non-root:

```
$ docker run -it --entrypoint=sh sourcegraph/zoekt-indexserver:0.0.20200429072931-1a9304f -c 'whoami && ls -lah $HOME/ && cd $HOME && universal-ctags --list-languages | grep scala'
sourcegraph
total 12K    
drwxr-sr-x    1 sourcegr sourcegr    4.0K Apr 29 07:33 .
drwxr-xr-x    1 root     root        4.0K Apr 29 07:32 ..
drwxr-sr-x    2 root     root        4.0K Apr 29 07:33 .ctags.d
scala
```

However, it also broke support for when the container is running as `root` (something we must still support, and the default again in 3.15.1 onward). Because the fix moved `/.ctags.d` to `/home/sourcegraph/.ctags.d` anyone running the container as root will also find it does not work:

```
$ docker run -it --entrypoint=sh -u 0 sourcegraph/zoekt-indexserver:0.0.20200429072931-1a9304f -c 'whoami && ls -lah $HOME/ && cd $HOME && universal-ctags --list-languages | grep scala'
root
total 8K     
drwx------    2 root     root        4.0K Apr 23 06:25 .
drwxr-xr-x    1 root     root        4.0K May  1 19:05 ..
```

### Owners

- @keegancsmith can you own fixing this so both root and non-root work as expected?
  - [ ] Update go.mod/go.sum with the fixed version
  - [ ] Update docker-images/search-indexer/Dockerfile with the fixed version
  - [ ] Cherry-pick both of the above changes onto the `3.15` branch
- @uwedeportivo can you own cutting a patch release (3.15.2) once the above is completed?

**Comment by keegancsmith** [comment] 2020-05-02 08:34
Thanks for debugging and fixing this. I will push fixes at latest Monday
morning SAST.

> However, it also broke support for when the container is running as
> `root` (something we must still support, and the default again in
> 3.15.1 onward). Because the fix moved `/.ctags.d` to
> `/home/sourcegraph/.ctags.d` anyone running the container as root will
> also find it does not work:

Note there is a slight flaw in your testing methodology. ".ctags.d" is
checked in both PWD and $HOME. In all your tests you are doing a "cd
$HOME" or "cd /". Instead you should be relying on the containers PWD
(the WORKDIR). The regression was mainly due to the "WORKDIR" being
changed to /home/sourcegraph when we added the non-root case.

The new images should continue to work, even for root. As long as the
PWD remains /home/sourcegraph. I will validate though.

This is a very fragile aspect of our use of ctags and I plan on
proposing a fix for it soon, since we will inevitably regress on it
again.

**Comment by slimsag** [comment] 2020-05-02 10:15
Thank you!

And.. Haha, I would've never guessed `$HOME` and PWD would differ, you're totally right though:

```
$ docker run -it --entrypoint=sh -u 0 sourcegraph/zoekt-indexserver:0.0.20200429072931-1a9304f -c 'whoami && pwd && ls -lah $(pwd) && echo $HOME && universal-ctags --list-languages | grep scala'
root
/home/sourcegraph
total 12K    
drwxr-sr-x    1 sourcegr sourcegr    4.0K Apr 29 07:33 .
drwxr-xr-x    1 root     root        4.0K Apr 29 07:32 ..
drwxr-sr-x    2 root     root        4.0K Apr 29 07:33 .ctags.d
/root
scala
```

**Comment by keegancsmith** [comment] 2020-05-04 09:31
Surprisingly this has never worked. My script below found no ctags which supported scala.

```bash
for v in 3.{15,14,13,12,11,10,9,8,7}.0; do
  image=$(src search "repo:github.com/sourcegraph/deploy-sourcegraph\$@v${v} image.*(zoekt-indexserver|search-indexer)" | grep -o 'index.docker.io.*')
  echo "Users with working ctags in v$v ($image)"
  docker run      --rm=true --entrypoint=sh "$image" -c 'universal-ctags --list-languages | grep -i scala && whoami'
  docker run -u 0 --rm=true --entrypoint=sh "$image" -c 'universal-ctags --list-languages | grep -i scala && whoami'
done
```

Additionally I then checked the PR which added ctags to our zoekt container, it contains the same mistake <https://github.com/sourcegraph/infrastructure/pull/1588/files>

Our kubernetes resource never set the working dir.

As such this isn't a drop everything sort of task. I think it is a bad experience for customers so may justify a patch release.

Side-note: A cool use of src-cli above were I extract out the docker image version :)

**Comment by keegancsmith** [comment] 2020-05-04 11:35
Cherry-picked onto 3.15 branch. Handing over to @uwedeportivo. But I'd read what I said in the previous comment, we may not want to ship a patch version for this (unless a customer really wants it).

**Comment by uwedeportivo** [comment] 2020-05-04 15:48
got it, thanks 👍

**Closed** 2020-05-14 11:13 UTC
Labels: bug, team/search
