### ISSUE TITLE
Raw API redirects to sign in page (returning 200) if not authenticated

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#1248] opened 2018-12-06 02:19 UTC
This is I think the third time I had a bug because of this and took more than needed to track it down because the application just sees a 200 OK and continues, so filing this as an issue to track.

It should return a 401.

**Comment by slimsag** [comment] 2018-12-06 04:04
Agreed, I expect a 401 + the login page.

**Comment by keegancsmith** [comment] 2019-01-22 08:40
The issue here is the raw handler was added to the app router, rather than the api router. However, to move it to our api router would mean we have to change the path to it. This seems desirable to me, since the alternative is special case how we handle the raw endpoint.

Are there some other implications I may be missing? Either way I'll send a PR out and we can continue discussion on that.

**Comment by keegancsmith** [comment] 2019-01-22 08:51
This is a little more involved since we don't have any machinery setup to route repoRev URLS in httpapi. So I'll wait to hear back more before proceeding further on this task. cc @slimsag

**Comment by slimsag** [comment] 2019-01-22 19:38
The idea is that we can ultimately _also_ link users to the raw API. i.e., kind of like how GitHub has raw URLs like this: https://raw.githubusercontent.com/sourcegraph/sourcegraph/master/CHANGELOG.md

That is to say, the endpoint should support both plain users and our language server use case. Of course, the language server use case is more important and the plain user use case is not worth working on unless it is easy to do so.

I don't think fixing this issue needs to result in changing how we mount the handler. If you're unauthenticated, shouldn't we still return a 401 status code regardless of whether or not it is an app or api router endpoint? I think debugging where the 200 comes from + changing that to a 401 is the ideal solution here. 

My suspicion is the bug lies somewhere in https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/handlers.go#L94:1

**Comment by keegancsmith** [comment] 2019-01-23 11:35
The bug is in the auth layer. For app endpoints we redirect to the sign-in page. Maybe what we need to do is make the sign-in page return a 401 status code. This is still less than ideal for an API like endpoint, but will solve the underlying issue. Either way you'll see a PR out of me today with something that works.

**Comment by felixfbecker** [comment] 2019-01-23 12:03
For some context, in the original implementation we already had the API exposed on both the UI and API endpoints:
https://github.com/sourcegraph/sourcegraph/pull/800/commits/df4ad823337208d0a5c84cf643304ec814786c44

We went with only the UI route because of complexity and because it is confusing to have the same endpoints that work the same for the happy path (no auth needed / no errors), but have slight behaviour differences in the error and edge cases (auth needed, errors, ...). Devs are likely to use the wrong endpoint for their use case.

It's tricky because for normal users, a redirect to the sign in page is the better UX. For API consumers, a 401 is the better UX (and more correct).

The media type could potentially be controlled with `Accept` ([which also allows parameters](https://tools.ietf.org/html/rfc7231#section-5.3.2), e.g. `Accept: */*;errors=text/plain`. But `Accept` shouldn't really change the status code.

**Comment by beyang** [comment] 2019-12-24 19:44
@keegancsmith @slimsag @felixfbecker re-opening this because https://github.com/sourcegraph/sourcegraph/pull/7347 (which was merged separately) reintroduces this issue.

**Comment by felixfbecker** [comment] 2020-01-11 16:16
Please don't just backlog this - it has severe consequences for language servers (hence this issue was filed in the first place back then)

**Comment by keegancsmith** [comment] 2020-01-13 07:50
@beyang, @tsenart  we need to make a decision here before we release 3.12. This will be introducing pretty bad known regression for language servers. Hard to know what is worse, that or the SAML breakage. As such I propose someone fixes this for the 3.12 release (possibly via cherry-pick onto release branch). I don't have bandwidth to fix this right now, so it would be great if @beyang stepped in, or someone with spare capacity on @sourcegraph/core-services. This isn't drop everything and fix before branch cut, just fix before we tag our final release.

**Comment by beyang** [comment] 2020-01-13 20:02
The right fix IMO is the following:
* Return 200 on sign-in page (including redirects). This is technically correct, because the requested resource (the sign-in page) is being served.
* The raw API should not redirect to sign-in page. Instead, it should just return a 401 unauthorized.

I do not have a lot of bandwidth at the moment, but will take this on if necessary. I'm not sure why this needs to be fixed before release? Is it just a debugging pain for language servers, or does it affect end-user experience?

**Comment by keegancsmith** [comment] 2020-01-14 07:50
I'll own fixing this. I believe it breaks code intelligence if a user is not logged in.

**Comment by keegancsmith** [comment] 2020-01-14 14:40
Looked a bit into this. Feels very ugly to fix due to it being part of the app. But have an idea I will try out tomorrow which hopefully won't lead to unsafe code :)

**Comment by keegancsmith** [comment] 2020-01-15 19:08
Fix out at https://github.com/sourcegraph/sourcegraph/pull/7778 will cherry-pick onto 3.12 branch when approved.

**Comment by beyang** [comment] 2020-01-16 01:17
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.12 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Closed** 2020-01-16 08:28 UTC
Labels: api, auth, bug, team/core-services

**Comment by keegancsmith** [comment] 2020-01-16 08:33
Cherry-picked onto 3.12 release branch as a9f1aab698fa912136bbe8fc574afacd15aab7cc
