### ISSUE TITLE
Files tab doesn't show current file after I landed there through "references"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#9155] opened 2020-03-19 12:30 UTC
1. Go to https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph@8ac72992739396ff92403bea2458d2c84a468ce3/-/blob/internal/search/parser.go#L409:6&tab=references
2. Current file is `parser.go` and selected on the left in the `Files` tab is `parser.go`:
<img width="917" alt="Screen Shot 2020-03-19 at 13 26 47" src="https://user-images.githubusercontent.com/1185253/77067479-4c7e6300-69e5-11ea-805a-ed26b72b27af.png">
3. Click on the second reference shown, line 101 in `internal/search/query/searchquery.go`
4. I'm now in `internal/search/query/searchquery.go` but in the `Files` tab `parser.go` is still selected:
<img width="1022" alt="Screen Shot 2020-03-19 at 13 28 53" src="https://user-images.githubusercontent.com/1185253/77067685-ada63680-69e5-11ea-9d6f-d352357e5919.png">
5. Expand the `query` folder in the `Files` tab. Now `searchquery.go` is correctly selected.

I would expect that in step 4 `searchquery.go` is selected.

**Comment by attfarhan** [comment] 2020-03-23 04:27
This is most likely a dupe of https://github.com/sourcegraph/sourcegraph/issues/9155. Closing this in favor of #9155.

**Closed by attfarhan** 2020-03-23 04:27 UTC
Labels: bug, team/web, webapp
