### ISSUE TITLE
Add a "preview search" button to the search insight creation UI query section

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#21358] opened 2021-05-25 15:57 UTC
Internal and external users have asked about getting a "preview" function for the search, to validate that they're actually tracking the right things. 

While live preview is cool and helps you "trust" insights, if you want to verify your query's results, you can't just copy/paste it due to the repo filters being input separately (which makes sense for the use cases here). 

A simple version is just a button and was [already in our figma mock](https://www.figma.com/file/QfeID0EEYMEPdEv8pbGULB?node-id=9334:14962#82997688)

Note – this shouldn't just copy over your search query to a Sourcegraph search page, but also add `repo:` filters for every repo in the repositories field on this page.

**Comment by Joelkw** [comment] 2021-10-09 00:34
Also requested by [this customer](https://sourcegraph.slack.com/archives/C02BJ8T258D/p1633726286269200).

**Comment by vovakulikov** [comment] 2022-01-10 17:57
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/28878. Close is in favor of the last issue about it.

**Closed by vovakulikov** 2022-01-10 17:57 UTC
Labels: team/code-insights, crud-ui
