### ISSUE TITLE
Repo search suggestions in smart search field don't go directly to the repo

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#8882] opened 2020-03-09 03:37 UTC
Our new smart search field changed the behavior of selecting repo suggestions. Previously, it selecting a repo suggestion would take you directly to the repo, but now it simply adds the string to the query. A user provided feedback saying he prefers the old behavior, and finds it cumbersome to need to type `repo:` before the added string now.

#### Steps to reprxoduce:

1. Go to sourcegraph.com and type `torvalds/linux` into the search bar. 
2. Select the ^github.com/torvalds/linux suggestion. 
3. See that the string gets added to the query

#### Expected behavior: user gets taken to the repository page of the selected suggestion
![2020-03-09 11 33 58](https://user-images.githubusercontent.com/16265452/76180771-eed66380-61f9-11ea-99a0-f55902e2b7e9.gif)

#### Actual behavior: suggestion string gets added to query
![2020-03-09 11 31 46](https://user-images.githubusercontent.com/16265452/76180724-c484a600-61f9-11ea-8bc5-5ba09fe416e9.gif)

**Comment by lguychard** [comment] 2020-03-23 14:55
Duplicate of #8749

**Closed by lguychard** 2020-03-23 14:55 UTC
Labels: search, team/web, webapp
