### ISSUE TITLE
Sourcegraph Code Search VS Code Extension Auth Does Not Work

### ISSUE THREAD

**Issue by alexAtSourcegraph** [sourcegraph/sourcegraph#61269] opened 2024-03-19 16:13 UTC
- **Sourcegraph version:** 5.3.X
- **Platform information:** Sourcegraph Managed Enterprise

#### Steps to reproduce:

1. Download the Sourcegraph Code Search VS Code Extension 
2. Attempt to authenticate using a Sourcegraph Managed Enterprise instance

#### Expected behavior:
Successful authentication and searching being done in the IDE Extension

#### Actual behavior:
The extension times out and authentication is not successful with a **valid** access token.

<img width="1034" alt="vscode_code_search_plugin" src="https://github.com/sourcegraph/sourcegraph/assets/86978415/b5984097-3c8f-4715-9316-d65f4fc4a4e0">

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://sourcegraph.com/support/) on issues like there are for support requests).

**Comment by camdencheek** [comment] 2024-04-05 22:23
Closing in favor of https://github.com/sourcegraph/sourcegraph/issues/60710, which has a bit more detail about the root cause

**Closed** 2024-06-12 14:07 UTC
Labels: bug, vscode-search, team/code-search
