### ISSUE TITLE
"Cannot read property 'title' of null" when visit repo home of a tag

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#19185] opened 2021-03-16 17:13 UTC
https://sourcegraph.com/github.com/sourcegraph/sourcegraph@3.23

![CleanShot 2021-03-17 at 01 11 11@2x](https://user-images.githubusercontent.com/2946214/111351242-ee4e9380-86bd-11eb-8aec-3b73d007b195.png)

**Comment by umpox** [comment] 2021-03-16 17:16
Hey thanks for tagging us, I believe this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/19157#issuecomment-800391259 but please reopen if I'm wrong!

**Closed by umpox** 2021-03-16 17:16 UTC
Labels: bug, team/frontend-platform
