### ISSUE TITLE
Add confirmation to actually run exhaustive search

### ISSUE THREAD

**Issue by Piszmog** [sourcegraph/sourcegraph#55805] opened 2023-08-11 19:43 UTC
When a user runs a search with the command to run an exhaustive search (see #55804), the search result page should display the usual search results. However, a banner should be displayed to ask whether the user wants to run the search as an exhaustive search.

## Done

- Demo
- Storybooks

## Design

- See [wireframe](https://app.excalidraw.com/s/4Dr1S6qmmY7/AZ3e5sR7gBo)

**Comment by vovakulikov** [comment] 2023-08-15 14:28
This became a duplicate of https://github.com/sourcegraph/sourcegraph/issues/55707

**Closed by vovakulikov** 2023-08-15 14:28 UTC
Labels: exhaustive-search
