### ISSUE TITLE
Insights data point clicks return useless search results

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50885] opened 2023-04-19 21:20 UTC
when clicking on an insight graph point, it goes to the search page with a query that includes before and after and type:diff which then does not show any results since the actual data the insight is searching for was added to was before the generated before: value. Is this a bug or something I'm missing?

/cc @vovakulikov

**Comment by gl-srgr** [comment] 2023-05-15 02:08
I reached out to the customer who first brought this up in the same slack [thread](https://sourcegraph.slack.com/archives/C047N1SFJ4X/p1683689173750159?thread_ts=1676495693.987289&cid=C047N1SFJ4X) to get clarity on their specific insights configuration but I believe I know what the issue is.

I'm confident that this is not a bug. If a data point in an insights trend has the same value as the preceding data point (i.e. zero slope) then the type:diff search for the given time window may not necessarily have modifications from commits, but it's possible. That is, one of two possibilities:

- after the matching commits in the given time interval were committed the resulting search result count remained the same as the preceding time interval.
- there were zero matching commits in the given time interval, and therefore zero search results when clicking.

We will return results for the type:diff search in the first case and return zero results in the second.

I acknowledge where some of the confusion lies. If the trend shows a non zero value for a given data point then one expects clicking on the data point to display one or more search results. If the trend showed change in search results count instead of total search results count then one would recognize in the trend which of the two aforementioned search results scenarios we'd expect, which we cannot do with the current Track Changes trend.

Adding @sourcegraph/code-insights because I'm not sure we want to pursue changing this.

**Comment by chwarwick** [comment] 2023-05-17 14:20
This comes up quite often, as you discovered clicking on a data point runs a diff search to show the changes that attributed to the difference from the previous data point.  Several things can happen:

- There is no difference and therefore no results
- There is no difference but there are results because of an matching number of adds and removes in the commits over that time
- There is a difference and results appear
- The search hits a timeout before completing, there may be partial results

While it would be nice if clicking on a data point showed the specific results that attributed to that data point it is not realistic to do that at scale.  For example a historic data point for an insight run over all repos at a customer with 25,000 repos is built by combining the results of 25,000 historic searches that were run in the background.  There just isn't a way to put that into a single search that could be run again on click of a datapoint. 

Closing with the reason of won't fix

**Closed by chwarwick** 2023-05-17 14:20 UTC
Labels: team/code-insights
