### ISSUE TITLE
Google smtp-relay does not work as expected

### ISSUE THREAD

**Issue by topebali** [sourcegraph/sourcegraph#35943] opened 2022-05-24 13:48 UTC
# Google smtp-relay does not work as expected

- **Relative Priority**: p2
- **Deployment Type**: Docker
- **Sourcegraph Version**: 3.39
- **Impact to Customer**: They are not able to use email notifications
- **Slack Discussion(s)**: [slack thread](https://sourcegraph-community.slack.com/archives/C02BG0M0ZJ7/p1653246723058609?thread_ts=1652159759.607939&cid=C02BG0M0ZJ7)

## Customer Context

The customers mood at the moment is stable.

## Brief Description

This user is trying to set up email notifications using google workspace's SMTP relay.
`SendTestEmail `returns the error `Failed to send test email: EOF`. 
I asked that he telnet from the server to the SMTP host and he got a response. So that worked. Still, he is unable to send test emails. 
The following are my troubleshooting steps:

- I checked to see if 2FA is enabled on the Google workspace account because when its enabled SMTP does not work and the customer confirmed 2FA is off.

- I requested for logs and in the frontend we saw this error  `frontend | t=2022-05-11T16:43:49+0000 lvl=warn msg="Failed to send email to inform user of access token creation" error=EOF` which originated from [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/access_tokens.go?L92:15),

- I told the user to create an access token on their instance and attempt again, but no dice!

- I also confirmed that `Require SMTP Authentication` and `Require TLS encryption` in step 7 are enabled according to the [SMTP relay account](https://support.google.com/a/answer/2956491) doc .

## Steps to Reproduce
- I was able to reproduce the issue on my end and I discovered  when I use  “host”: “[smtp-relay.gmail.com](http://smtp-relay.gmail.com/)”,It throws the error the user is seeing. However when I use host”: “[smtp.gmail.com](http://smtp.gmail.com/)” it works.

## Expected Actions/Questions for Engineers

I came across this similar [issue](https://github.com/sourcegraph/customer/issues/643) with another user. I basically followed through all the steps outlined here. Tho, I see they eventually switched to AWS and the smtp-relay issue was technically unresolved.
I would definitely appreciate some leads as to what next I could be looking into or how to continue debugging further. Thanks

**Comment by sourcegraph-bot-2** [comment] 2022-05-24 13:49
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by RafLeszczynski** [comment] 2022-05-24 13:56
@ryphil could you please help with the prioritization of this issue?

**Comment by RafLeszczynski** [comment] 2022-05-30 15:58
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35943?planning-poker) with ZenHub @kopancek @miveronese @pjlast @unknwon @pietrorosa77

**Comment by unknwon** [comment] 2022-05-30 23:43
https://stackoverflow.com/a/57076378/1875015 in case this helps.

**Comment by topebali** [comment] 2022-05-31 15:05
Hi @unknwon 
I attempted changing the port in our test instance from port 587 to 465 and also tried with 25 but got the same error.
I am not sure if changing port requires some time to take effect tho.

**Comment by unknwon** [comment] 2022-06-01 08:30
Hey @topebali! I'm the support engineer for this issue, qq: do I need anything for using Google smtp-relay? Or it's available for any GMail account?

**Comment by unknwon** [comment] 2022-06-02 07:22
I can reproduce the error but I don't if it's because our Google Workplace hasn't enabled the SMTP relay or same issue as the customer, currently [waiting for IT tech ops](https://sourcegraph.slack.com/archives/C01CSS3TC75/p1654151137609749).

**Comment by unknwon** [comment] 2022-06-02 07:32
I think I fixed the EOF problem, but now need IT tech ops to change some settings to verify my fix.

**Comment by unknwon** [comment] 2022-06-07 06:49
Stilling waiting IT tech ops and security to approve my request to enable SMTP relay.

**Comment by unknwon** [comment] 2022-06-09 05:17
Security has approved my request, still waiting for IT tech ops to change settings.

**Comment by unknwon** [comment] 2022-06-13 07:06
Keep seeing the following error, and Gmail docs is very helpless:

```
send MAIL: 550 5.7.1 Invalid credentials for relay [101.87.97.103]. The IP address you've
5.7.1 registered in your G Suite SMTP Relay service doesn't match domain of
5.7.1 the account this email is being sent from. If you are trying to relay
5.7.1 mail from a domain that isn't registered under your G Suite account
5.7.1 or has empty envelope-from, you must configure your mail server
5.7.1 either to use SMTP AUTH to identify the sending domain or to present
5.7.1 one of your domain names in the HELO or EHLO command. For more
5.7.1 information, please visit
5.7.1  https://support.google.com/a/answer/6140680#invalidcred - gsmtp
```

I've requested to have a quick meeting with IT tech ops to eye-spot config settings on Tuesday.

---

@topebali Any reason they can't just use "smtp.gmail.com"? Sourcergaph isn't an email server (to forward emails to SMTP relay) but a client after all.

**Comment by topebali** [comment] 2022-06-13 15:11
@unknwon They are currently making use of `smtp.gmail.com` as an alternative. However, the customer prefers to use `smtp-relay` as it has more advantages than `smtp.gmail.com`, according to feedback from the customer.
Also, since we mentioned the use of `smtp-relay` in our [doc](https://docs.sourcegraph.com/admin/config/email#configuring-sourcegraph-to-send-email-via-google-workspace-gmail), we might want to be sure this is working and supported to prevent any reoccurrence of this issue.

**Comment by unknwon** [comment] 2022-06-14 08:20
@slimsag pulling you since you see you wrote the initial version of https://docs.sourcegraph.com/admin/config/email#configuring-sourcegraph-to-send-email-via-google-workspace-gmail.

Do you have some hunches here what might be going wrong?

**Comment by unknwon** [comment] 2022-06-14 15:05
Quick update: Just had a video call with IT tech ops and the "Require TLS encryption" wasn't checked last time, which we just did in the call. I'll wait for a few hours and test my patch again.

**Comment by topebali** [comment] 2022-06-14 15:44
Thanks for the update @unknwon

**Comment by unknwon** [comment] 2022-06-15 05:52
It's working! Currently in review: https://github.com/sourcegraph/sourcegraph/pull/37255

**Comment by topebali** [comment] 2022-06-15 11:27
@unknwon  Awesome!

**Comment by unknwon** [comment] 2022-06-16 05:59
PR merged, will be shipped in 3.41

**Closed** 2022-06-16 05:58 UTC
Labels: p2, rfh, team/iam-admin-experience

**Comment by topebali** [comment] 2022-06-16 10:11
@unknwon Thank you for looking into this!

**Comment by sourcegraph-bot-2** [comment] 2022-06-24 10:12
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.
