### ISSUE TITLE
code insights: make web UI clearly indicate that it is not supported in sourcegraph/server demo deployments (PREVENTS REMOVING FEATURE FLAG)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#17223] opened 2021-01-13 02:39 UTC
(See #17218 for general plan / explanation of the work being done on code insights.)

**IMPORTANT**: This prevents us from removing the feature flag. We need to fix this in order to remove the feature flag.

In small-scale Sourcegraph demo deployments (`sourcegraph/server` single-container Docker image) we do not deploy TimescaleDB as it would require a fair amount of effort to bake that into the server image (and we would need to handle _many_ other aspects, like for example we cannot upgrade Postgres in those deployments today.) Instead, [we've chosen to omit backend insights from this deployment type](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:insights+supported+in+single-container&patternType=literal) - which is fine because that deployment type is only for small-scale "I'm on a dev laptop" demo deployments. Any serious trial of Sourcegraph will use at least a Docker Compose deployment type.

However, we don't communicate this today - so turning on the code insights feature flag and adding backend insights will result in `insights are only available in enterprise` error messages. https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/graphqlbackend/insights.go#L46-52

**What we need to do:** Figure out how we want to present ourselves in the context of a `sourcegraph/server` deployment. One option would be to have all insights disabled in this context. Another option would be to have the frontend do something more demo-ey (fake data? frontend-only insights? etc.) and allude that non-demo deployments have an actual backend.

**Comment by Joelkw** [comment] 2021-04-21 18:21
@felixfbecker I'd like to bump the priority of changing the error message to something a bit more descriptive for when the issue is the deployment – a customer ran into this and ideally the error is self-descriptive.

**Comment by Joelkw** [comment] 2021-04-22 01:21
I'm going to close this in light of #20282 and #20283 which answer "what should it say" and "how should it behave," I believe. Thanks for creating the original tracker @slimsag .

**Closed by Joelkw** 2021-04-22 01:21 UTC
Labels: polish, team/code-insights, webapp
