### ISSUE TITLE
Phabricator: hover tooltips showing on wrong line in diff views

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#11378] opened 2020-06-09 15:27 UTC
Seen in a call with https://app.hubspot.com/contacts/2762526/company/554275594

On recent Phabricator (May 30), hover tooltips were showing on the wrong line in Differential diff views. We should see if we can reproduce + fix on the same version.

**Comment by daxmc99** [comment] 2020-07-13 18:01
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.18 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by marekweb** [comment] 2020-07-21 01:41
I wasn't able to reproduce this issue. More information might be needed in order to reproduce it. cc @dadlerj @lguychard 

It would be useful to narrow it down between two possible scenarios:

- the wrong range is being sent in the hover request to the server (which could be confirmed by looking in the Network tab in the browser dev tools)
- the correct range is being sent in the request but the hover is being rendered in the wrong location.

**Comment by muratsu** [comment] 2021-03-16 19:16
Closing this issue since it's irreproducible.

**Closed by muratsu** 2021-03-16 19:16 UTC
Labels: browser-extension, bug, customer, irreproducable, phabricator, planned/3.18, team/web
