### ISSUE TITLE
Unable to scroll when viewing a single commit 

### ISSUE THREAD

**Issue by daxmc99** [sourcegraph/sourcegraph#19240] opened 2021-03-18 00:19 UTC
- **Sourcegraph version:** "Sourcegraph.com" (/version: 90376_2021-03-17_2aad55a) 
- **Platform information:** Chrome (Mac OS)
#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/gitops-tools/image-updater/-/commit/ea820519fc4e791b3d86eff1dffeddfe06bdd30e 
2. Try to scroll 

#### Expected behavior:

1. I should be able to scroll (or have a loading indicator) 
2. Scrolling with the spacebar, page up & page down keys should also work

#### Actual behavior:

The page seems to freeze when viewing the commit. Clicking load more seems to cause the same freezing behavior.

**Comment by tjkandala** [comment] 2021-03-18 02:40
I was unable to reproduce this in Chrome (neither Linux (89.0.4389.90 (Official Build) snap (64-bit)) nor Mac OS). Can you post a screen recording and/or console logs?

<details>
<summary>Recording of scrolling working in Chrome</summary>
<img src="https://user-images.githubusercontent.com/37420160/111565332-85c0ee80-8771-11eb-80bd-83010c94cffd.gif" />
</details>

**Comment by pdubroy** [comment] 2021-03-19 12:54
@daxmc99 Could it be that your cursor was outside the scrollable area? On macOS, it's not very obvious what part of the page is scrollable. See here:

![CleanShot 2021-03-19 at 13 52 02@2x](https://user-images.githubusercontent.com/17293/111783385-75685b00-88ba-11eb-8964-c268cea69481.png)

@AlicjaSuska, any thoughts here?

**Comment by daxmc99** [comment] 2021-04-06 21:05
@pdubroy That is it! 

Could the entire page be scrollable?

**Comment by pdubroy** [comment] 2021-06-25 15:20
The full width is scrollable now, so I'm going to close this issue.

**Closed by pdubroy** 2021-06-25 15:20 UTC
Labels: bug, good first issue, team/frontend-platform
