### ISSUE TITLE
Toggle buttons on the Home page submit a search.

### ISSUE THREAD

**Issue by almeidapaulooliveira** [sourcegraph/sourcegraph#35260] opened 2022-05-10 18:42 UTC
#### Details 
On the Home page, if the user tries to toggle the actions: "Enable case sensivity," "Enable regular expression," or "Enable structural search," the page submits a search. 

<img width="1512" alt="Screen Shot 2022-05-10 at 11 44 06 AM" src="https://user-images.githubusercontent.com/64257673/167698068-25fe0faf-056e-48fa-8a36-f6aadbedad44.png">

There are some inconsistencies in the experience:
- Interrupts the user journey when formatting a search query.
- The user expects to activate an option and receives an unfinished search query submission.
- The same input field on the Search Page behaves differently.

<img width="1512" alt="Screen Shot 2022-05-10 at 3 33 03 PM" src="https://user-images.githubusercontent.com/64257673/167698354-559d6ab4-e518-49f2-8734-f35285094fa0.png">

#### Type of debt
- UX - inconsistent experiences throughout the product that negatively impacts the learnability and integrity of the flow.

#### Areas affected 
- Code Search

#### Impact 
- Consistency; Direct impact on customers.

#### Urgency 
Not critical but quite urgent as we'd be producing more debt over time without addressing this issue.

**Comment by sourcegraph-bot-2** [comment] 2022-05-10 18:42
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by limitedmage** [comment] 2022-05-10 19:28
Duplicate of #34718 (which may also be a duplicate of an older bug).

**Closed by limitedmage** 2022-05-10 19:28 UTC
Labels: design, design-debt, team/search-product
