### ISSUE TITLE
Remove repo filter requirement from code monitoring creation UI

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#31943] opened 2022-02-28 17:44 UTC

**Comment by lguychard** [comment] 2022-02-28 17:47
To take into consideration: should we keep a repo limit validation rule / hint on sourcegraph.com, where the number of repos will be considerably higher than the repo limit?

**Comment by camdencheek** [comment] 2022-04-25 16:21
Closing as duplicate of #31943

**Comment by limitedmage** [comment] 2022-04-25 21:59
@camdencheek is this a duplicate of #25803? This issue is to track the UI side of this (removing the restriction/requirement on the search box when creating the monitor)

**Comment by camdencheek** [comment] 2022-04-27 16:43
Oh lol. I just closed it as a duplicate of itself 🤦 Thanks Juliana 😄

**Closed** 2022-06-10 22:42 UTC
Labels: team/search-product, code-monitors
