### ISSUE TITLE
On a particular GitHub.com repo, latest commit isn't being synced

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#48710] opened 2023-03-06 09:09 UTC
From https://twitter.com/virus_dave/status/1631399368522706949:

I can't figure out why Sourcegraph is not working on [this query](https://sourcegraph.com/search?q=context%3Aglobal+repo%3A%5Egithub%5C.com%2Fgnuton%2Fasuswrt-merlin%5C.ng%24+EXTRA_KERNEL_CONFIGS&patternType=standard&sm=1&groupBy=path). Just tried recloning the repo to no avail.

1. We're not picking up the latest commit that is shown on the repo (https://github.com/gnuton/asuswrt-merlin.ng/commit/e94f94af70165842e203a7ca189be05bea692541).
2. The search shows a `backend down` error. - RESOLVED: https://sourcegraph.slack.com/archives/CHEKCRWKV/p1678097835423209?thread_ts=1678093772.330699&cid=CHEKCRWKV

**Comment by sqs** [comment] 2023-03-06 17:25
Something weird is going on with that repo...

**Comment by jtibshirani** [comment] 2023-03-06 20:00
I looked into this. I didn't see anything wrong with the `gnuton/asuswrt-merlin.ng` repo. It doesn't contain the literal `EXTRA_KERNEL_CONFIGS`, so it seems correct that there are no results.

The tweet actually refers to a different repo `RMerl/asuswrt-merlin.ng`, which does contain the string. Strangely, sourcegraph.com is not indexing that repo! It has over 4K stars, but looking at Site Admin/ Repositories, I don't see the repo being sync'd at all. 

CC @sourcegraph/repo-management maybe you have an idea as to what's happening?

**Comment by mrnugget** [comment] 2023-03-07 09:34
> CC @sourcegraph/repo-management maybe you have an idea as to what's happening?

I'm pretty sure that the problem is that we can't sync "GitHub Starburst" anymore: https://sourcegraph.com/site-admin/external-services/RXh0ZXJuYWxTZXJ2aWNlOjE4Njg=

Context: code host connections are "synced" to fetch a list of repositories on a regular interval. In this case, we attempt to paginate through all the GitHub search results for repos with over 5 stars. And that takes at least 17 hours (napkin math courtesy of @eseliger):

- GitHub's Search API allows 30 requests per minute
- We have roughly ~3100000 in this code host connection (plus/minus what we haven't synced yet)
- Page size is 100
- `3100000/100/30/60` means it'll take ~17h -- without any overhead

As you can see, we're running into errors there:

<img width="914" alt="screenshot_2023-03-07_10 32 16@2x" src="https://user-images.githubusercontent.com/1185253/223381477-d0b6e54a-6732-4e18-8a0d-0a26d3a2d16c.png">

But @pjlast is right now working to improve our rate limiting code. He already improved things for GitHub, but not for the Search API client, which is a bit separate. I'll let him answer whether this will fix the problem, but it might improve things.

to state the obvious: syncing ~3mil repositories every 8 hours is not the most scalable approach. Maybe we should split up the single code host connection into multiple (sync repos with stars between 5..10, 10..100, ...) etc. Or think of another system.

**Comment by jtibshirani** [comment] 2023-03-07 17:17
Thanks @mrnugget @eseliger ! That's helpful context. It does seem like there's area for improvement in terms of surfacing errors, I had some trouble tracking down that the repo was blocked (and why).

I think we can close this out, as we'll track any improvements separately.

**Closed** 2023-03-07 17:22 UTC
Labels: bug, sourcegraph.com
