### ISSUE TITLE
z-index of onboarding "Use with your code host" alert is behind search results

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4083] opened 2019-05-17 00:23 UTC
To reproduce:

1. Get these onboarding messages to show up:

![image](https://user-images.githubusercontent.com/3173176/57894947-f6a5c100-77fd-11e9-8564-abba49922fb8.png)

2. Search for something that returns a lot of repo results like this query https://k8s.sgdev.org/search?q=repo%3Agithub%5C.com

3. Notice that the message is behind every result:

---

![image](https://user-images.githubusercontent.com/3173176/57895226-73856a80-77ff-11e9-8d06-ce7f80a12c2a.png)

---

http://g.recordit.co/nHV1OdWHQ2.gif

**Comment by vanesa** [comment] 2019-05-17 17:36
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/4060.

**Closed by vanesa** 2019-05-17 17:36 UTC
Labels: bug, onboarding, release-blocker
