### ISSUE TITLE
Floating status bar looks awkward when no status bar items have been contributed yet/extensions haven't loaded yet

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#21577] opened 2021-06-01 10:03 UTC
![image](https://user-images.githubusercontent.com/10532611/120305532-2171ed80-c2d1-11eb-923e-09e4c8b76be9.png)

I'd suggest to just hide it if it's empty?

**Comment by tjkandala** [comment] 2021-06-01 14:54
Good call! Closing as it is a dupe of #21570

**Closed by tjkandala** 2021-06-01 14:54 UTC
Labels: team/extensibility
