### ISSUE TITLE
500 Internal server error when repository is not found

### ISSUE THREAD

**Issue by filmil** [sourcegraph/sourcegraph#4826] opened 2019-07-08 16:26 UTC
#### Steps to reproduce:

1. Go to https://sourcegraph.com/github.com/filmil

#### Expected behavior:

Anything but an error code 500.

Sourcegraph is probably not indexing my toy repos; but it shouldn't `500`-out either.

#### Actual behavior:

Error code 500.

**Comment by slimsag** [comment] 2019-07-08 22:59
Hi -- definitely agree this shouldn't 500, it should be a 404 instead. That URL is not valid, how did you get it?

You can find a list of your repositories and view them on Sourcegraph here: https://sourcegraph.com/search?q=repo:%5Egithub.com/filmil

Or perform a search across them all, e.g. like so: https://sourcegraph.com/search?q=repo:%5Egithub.com/filmil+error

**Comment by filmil** [comment] 2019-07-08 23:05
> [...] That URL is not valid, how did you get it?

I was playing smart on TV and tried to construct a URL that points to my repo, just to see what happens.  I made a mistake in the process, and that led to a `500`.  Which seemed like something to report, even though the query itself was a mistake.

**Comment by slimsag** [comment] 2019-07-08 23:27
Makes sense, and definitely we'll fix that! Thanks for reporting :)

(also, maybe we can optimize our UX for smart TVs a bit more as well, I'll keep you posted if anything develops there 😆)

**Comment by felixfbecker** [comment] 2019-11-11 17:40
I just met this too while testing the Gitlab native integration. @sourcegraph/core-services could this be prioritized in light of the Gitlab native integration?


![image](https://user-images.githubusercontent.com/10532611/68608115-701f2300-04b2-11ea-8fcc-8aceb2aecf84.png)

**Comment by unknwon** [comment] 2019-11-12 22:01
I want to be crystal clear before diving deeper. What is the expected behavior here? Should it be 404 [as @slimsag suggested](https://github.com/sourcegraph/sourcegraph/issues/4826#issuecomment-509422099)?

**Comment by felixfbecker** [comment] 2019-11-12 22:03
Yes.

**Comment by unknwon** [comment] 2019-11-14 08:28
I guess there is a history about why we show "could not be cloned" as 500.

https://github.com/sourcegraph/sourcegraph/blob/8cca88368a47efe03c61e0e04d716e85793f7d09/cmd/frontend/internal/app/ui/handlers.go#L149-L152

This block of code is basically [the only place that calls `dangerouslyServeError` function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/internal/app/ui/router.go#L406:6&tab=references). I have no idea why because the issue link in the godoc is invalid.... (we don't have an issue at number 9453)

https://github.com/sourcegraph/sourcegraph/blob/8cca88368a47efe03c61e0e04d716e85793f7d09/cmd/frontend/internal/app/ui/router.go#L405-L406

Maybe @slimsag have some clues?

**Comment by slimsag** [comment] 2019-11-14 10:40
https://github.com/sourcegraph/enterprise/issues/9453 is what that should link to (our old repo before we went OSS)

If a repository is not cloneable, though, I don't see why we would do anything other than give the user an error. For example, if the repository is a valid one but we can't clone it due to invalid credentials we would want to tell the user that. So maybe the question is: how to differentiate between "can't clone" and "invalid repository"

**Comment by unknwon** [comment] 2019-11-14 17:35
> So maybe the question is: how to differentiate between "can't clone" and "invalid repository"

This is a really hard problem IMO, given Git itself really does not have a standard format as long as the path/URL points to a Git repository. In that sense, "can't clone" == "invalid repository" to Git. What we can do at best effort is we know major public code hosting platforms need at least two layers (i.e. `<user>/<repo>`) to specify a repository, we could directly return an 404 without even trying to `git ls-remote` it.

**Comment by felixfbecker** [comment] 2019-11-14 17:39
I think a more precise term for this condition than "invalid" is "not found". When I run a `git clone` on a repo that doesn't exist, git correctly tells me as a user the repo was "not found". Why can't we handle that?

```
> git clone https://github.com/asdjasdklajsdsa/sadkasjdkasld
Cloning into 'sadkasjdkasld'...
remote: Repository not found.
fatal: repository 'https://github.com/asdjasdklajsdsa/sadkasjdkasld/' not found
```

**Comment by slimsag** [comment] 2019-11-14 18:23
What @felixfbecker said is basically what I was thinking, and would allow
us to differentiate I would think? If not, I guess just returning a 404 in
all cases is not _that_ bad

**Comment by unknwon** [comment] 2019-11-15 18:57
I'm closing it as the PR to fix this issue has been merged. Please feel free to reopen or file a new one.

Note: I don't think it's made before the branch cut. So won't be in the 3.10 release but will live on the sourcegraph.com.

**Closed by unknwon** 2019-11-15 18:57 UTC
Labels: gitlab, team/core-services
