### ISSUE TITLE
Provide No Authentication Mechanism

### ISSUE THREAD

**Issue by naturalwarren** [sourcegraph/sourcegraph#6785] opened 2019-11-24 02:12 UTC
#### Feature request description

I'd like a no authentication mechanism for Sourcegraph. We deploy Sourcegraph into a VPC that's only accessible via VPN. Instead of burdening users with having to create an account it would be nice if authentication/account creation could be dropped altogether.

#### Is your feature request related to a problem? If so, please describe.

No.

#### Describe alternatives you've considered.

Using basic user authentication at the moment. 

#### Additional context

I suspect this is a fairly common use case as it was brought up in #6709.

**Comment by slimsag** [comment] 2019-11-24 10:17
I am going to close this as a duplicate of #6783 and will follow up over there soon.

**Closed by slimsag** 2019-11-24 10:17 UTC
