### ISSUE TITLE
codeintel: Review alerts

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#13074] opened 2020-08-17 19:41 UTC
Why is this gitserver alert defined in this file? Should it be defined in git_server.go?

https://github.com/sourcegraph/sourcegraph/blob/439392ec7536f3b9fb4d99b6b2469705ba5de2d2/monitoring/precise_code_intel_indexer.go#L168-L200

**Comment by bobheadxi** [comment] 2020-08-17 23:59
cc @efritz, looks like you added this - is this expected?

I feel like it makes sense, this seems to be alerting on requests _from_ precise-code-intel-indexer _to_ gitserver

**Comment by efritz** [comment] 2020-08-18 00:15
Yes, I think it's generally better to have alerts on each service requiring another service (rather than one blanket alert on the target service) so that if one class of requests are slower (or from a certain source pod) there is more information to help troubleshoot root cause.

**Comment by bobheadxi** [comment] 2020-08-18 00:25
closing this for now then :) hope that answers the question @nicksnyder !

**Comment by nicksnyder** [comment] 2020-08-18 03:49
Thank you for the clarification! Something still feels off to me here: this is an alert defined by the code intel team but being routed to the search team.

In general, I think it is an important property that each team defines the alerts that they get alerted on. Team A can't opt-in team B to alerts.

To keep this alert, I think either the code intel team needs to be the one alerted, or you need to get buy-in from the search team to own this alert (and in this case it probably shouldn't be precise-code-intel-indexer specific and it should be in a different file). You could also do both.

**Comment by davejrt** [comment] 2020-09-14 19:10
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by efritz** [comment] 2020-09-16 20:17
The immediate issue is fixed by https://github.com/sourcegraph/sourcegraph/pull/13860.

**Closed by efritz** 2020-09-16 20:17 UTC
Labels: debt, estimate/0.5d, planned/3.20, team/code-intelligence
