### ISSUE TITLE
Set default context or remember users last-used context

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#24676] opened 2021-09-07 13:32 UTC
Slack thread for reference: https://sourcegraph.slack.com/archives/C0W2E592M/p1631020057048600

Users are reporting some frustration that they are unable to set a default search context and that it always resets to `global` when opening a new tab. We should either cache the user-specified context (or similar) or provide an affordance to set a default context in the UI.

Probably the right long-term solution is to provide a config in the settings, but I think storing users' most recent context gets us 90% of the way there.

**Comment by benvenker** [comment] 2021-09-17 14:52
@limitedmage was thinking about adding this to the next iteration and you seemed like the person who's done the most similar work most recently. Any thoughts on implementation difficulty?

**Comment by limitedmage** [comment] 2021-09-17 18:01
I believe this functionality should already exist, but might not be working as expected. @novoselrok  is probably the most knowledgeable in this area, but I can also take a look. 

We can also take advantage of this to move the default context from `localStorage` to temporary settings :)

**Comment by benvenker** [comment] 2021-09-17 18:03
Oh good idea! Yeah we should definitely do that as well. For temporary settings work, I'm guessing there is no UI work (being that they're temporary), but is that the correct assumption?

**Comment by limitedmage** [comment] 2021-09-17 18:16
Correct, this should not require any visual work, but all work would be in the front-end/client-side.

**Comment by benvenker** [comment] 2021-09-17 18:17
Got it, thanks :)

**Comment by limitedmage** [comment] 2021-09-20 17:52
I just tried this and it works fine for me (as long as it's on the same browser). Do you have repro steps for this?

**Comment by benvenker** [comment] 2021-09-20 18:02
On dogfood, I can repro if I change my context to non-global and then open
a new Sourcegraph tab. The context change doesn't persist if I do that,
which from what I can gether is what the user's talking about.

**Comment by limitedmage** [comment] 2021-09-20 18:11
I can't repro at all, on local, dogfood, or dotcom, on Chrome or Firefox. When switching contexts, the context is remembered. What browser are you using? Can you record a Loom?

**Comment by benvenker** [comment] 2021-09-20 18:46
Weird. Yeah, I'll get you a loom today.

**Comment by benvenker** [comment] 2021-09-20 23:33
@limitedmage Ok I was able to repro this on dogfood with firefox and chrome by doing the following:
- going to dogfood, changing my context, running a search
- opening a new tab by command clicking my link to my dogfood home bookmark 
- seeing that my context was defaulting to global
Videos attached (had to use Cleanshot because Loom wanted to just record a single tab).

Firefox: https://cln.sh/4KKKQ1
Chrome: https://cln.sh/njaF9A

**Comment by limitedmage** [comment] 2021-09-21 21:18
@benvenker  I see. This is because you have a search bookmarked. This is by design, we don't want your search results to change for the same query if you change your selected context. If you omit the context from the search, `global` is set as the default. Does this make sense?

**Comment by benvenker** [comment] 2021-09-22 01:18
It does, and when I updated the bookmark to be the default search page I
was also unable to replicate the issue. Thanks for catching that, sorry for
the confusion.

**Comment by limitedmage** [comment] 2021-09-22 20:37
I'll close this issue then since it seems to be working as designed 👍

**Closed by limitedmage** 2021-09-22 20:37 UTC
Labels: team/search-product
