### ISSUE TITLE
Batch Changes: Approved Status

### ISSUE THREAD

**Issue by johnwesonga** [sourcegraph/sourcegraph#50894] opened 2023-04-19 22:03 UTC
Chime has noticed that batch changes appear as `approved` in the UI when they are not able to be merged. This is b/c they have some weird code review requirements. Basically, for some repos the code has to be reviewed by the code owner. Someone else could approve review the PR but it cannot be merged until the code owner approves it.

Basically, while the PR is marked as `review required` in GitHub, it should not show up as `approved` in the batch changes UI.

**Comment by johnwesonga** [comment] 2023-05-18 18:47
Chime has noticed that batch changes appear as `approved` in the UI when they are not able to be merged. This is b/c they have some weird code review requirements. Basically, for some repos the code has to be reviewed by the code owner. Someone else could approve review the PR but it cannot be merged until the code owner approves it.



Basically, while the PR is marked as `review required` in GitHub, it should not show up as `approved` in the batch changes UI.

**Comment by marekweb** [comment] 2023-06-13 16:05
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/50874 - we can close this?

**Comment by johnwesonga** [comment] 2023-06-13 16:09
Go ahead!

**Closed** 2023-06-13 16:10 UTC
