### ISSUE TITLE
extension: on zeromq example, only getting Find References button

### ISSUE THREAD

**Issue by ijt** [sourcegraph/sourcegraph#2446] opened 2019-02-25 22:45 UTC
To reproduce, go to https://github.com/pebbe/zmq4/blob/master/examples/psenvpub.go and mouse over `zmq.NewSocket`.

![screen shot 2019-02-25 at 2 42 28 pm](https://user-images.githubusercontent.com/15530/53373956-cf7cd900-390b-11e9-91bc-3fe4e76cf8f9.png)

This might be related to #1802 or #1770.

**Comment by ijt** [comment] 2019-02-25 22:46
This error shows up in the console:
```
inject.bundle.js:17 Error: type/object not found at 14:21
    at blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/00869467-b680-4014-967d-8deb9055c4f0:613:7790
    at blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/00869467-b680-4014-967d-8deb9055c4f0:613:8084
    at O.size.setImmediate (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/00869467-b680-4014-967d-8deb9055c4f0:613:8445)
    at blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/cca461aa-5c09-4579-88b0-466fad8df1f2:1:56896
    at v (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/cca461aa-5c09-4579-88b0-466fad8df1f2:1:57006)
    at MessagePort.[object process].toString.call.t.MessageChannel.port1.onmessage (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/cca461aa-5c09-4579-88b0-466fad8df1f2:1:55947)
```

**Comment by punya** [comment] 2019-02-27 02:41
For me, it showed both buttons about 50% of the time, and just "Find references" in the remaining cases -- which suggests that some sort of race condition is happening.

**Comment by sqs** [comment] 2019-02-27 15:52
Tentatively assigning to @chrismwendt 	to repro and triage. Assuming you can verify it (which seems likely, given that the 2 folks above we know and trust have seen it occur), this is important enough to fix in 3.2.

**Comment by chrismwendt** [comment] 2019-02-28 05:28
I think go-langserver can't find the definition of `NewSocket` because the definition is in a file that has `import "C"`, which is CGO:

https://github.com/pebbe/zmq4/blob/7a493a642e7acbd03045d4f5fe9516908a62f86f/zmq4.go#L815

It looks like CGO is disabled in go-langserver's build server:

https://github.com/sourcegraph/go-langserver/blob/f9fdcbb3871320e0655530b707a3d276d561311a/buildserver/environment.go#L90

When I set that to `true`, I got an error about `libzmq` not found:

```
pkg-config --cflags libzmq failed: exit status 1: Package libzmq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libzmq.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libzmq' found
```

Some ideas come to mind:

- Modify go-langserver to install libs on the fly (from where? Is this safe?)
- Gracefully degrade code intelligence in the face of missing libs (might be difficult because go-langserver calls out to the `go/build` package)

**Comment by efritz** [comment] 2020-07-27 18:45
This appears to be related to go-langserver, and is otherwise sufficiently out of date to be reproduced.

**Closed by efritz** 2020-07-27 18:45 UTC
Labels: bug, extensions, team/code-intelligence
