### ISSUE TITLE
Experimental text field completion eats characters and acts wonky

### ISSUE THREAD

**Issue by uskudnik** [sourcegraph/sourcegraph#4798] opened 2019-07-03 21:03 UTC
- **Sourcegraph version:** v19.6.27.856
- **Platform information:** NixOS 19.03, Chromium 75.0.3770.90 (Developer Build) (64-bit)

#### Steps to reproduce:

1. Enable "Experimental text field completion"
2. Type on github (e.g. comment)

#### Expected behavior:

Characters are entered :slightly_smiling_face: 

#### Actual behavior:

Only every second character shows up, sometimes acts as if "insert" mode would be enabled, etc.

**Comment by sqs** [comment] 2019-07-03 21:52
This is a duplicate of #4072, but the good news is that it's fixed and will be out in the next browser extension release today. In the meantime, please disable the experimental feature flag. Sorry and thanks!

**Closed by sqs** 2019-07-03 21:52 UTC

**Comment by uskudnik** [comment] 2019-07-04 17:30
With `v19.7.4.1146` I'm not seeing any issues with typing :+1:
