### ISSUE TITLE
Extensions Action Bar: on inactive/disabled action items, provide reason in hover

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#19346] opened 2021-03-23 01:16 UTC
Right now, if codedov is disabled, it looks like this, and hovering gives me no additional information: 

![image](https://user-images.githubusercontent.com/11967660/112077932-b1a9ee80-8b3a-11eb-9289-2fe32b5781ce.png)

Instead, we might tell you why a button is inactive when you hover.

**Comment by tjkandala** [comment] 2021-03-23 01:31
Is this a dupe of #19338?

**Comment by Joelkw** [comment] 2021-03-23 01:36
(Yep, thank you! Still working my way through Monday's notifications.)

**Closed** 2021-03-23 01:36 UTC
Labels: team/extensibility
