### ISSUE TITLE
Hard page reload required after adding changeset from form

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#8010] opened 2020-01-24 04:48 UTC
Repros on master. When you add a changeset using the repo name and number form and press the button, the number field is cleared but nothing else happens. To see the changeset you just added, you need to hard-reload the page (ctrl+R/cmd+R). I expect that it would appear after submitting the form without needing to reload.

Might be related to #8009.

Blocks tomorrow's rollout at https://app.hubspot.com/contacts/2762526/company/608245740 cc @christinaforney

**Comment by mrnugget** [comment] 2020-01-24 08:51
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/7713

**Closed** 2020-01-24 09:46 UTC
Labels: automation, customer
