### ISSUE TITLE
Running sourcegraph under a non-root URL

### ISSUE THREAD

**Issue by yasushi-saito** [sourcegraph/sourcegraph#7876] opened 2020-01-17 23:27 UTC
#### Question description

I'm trying to run sourcegraph behind a GCP GKE Ingress rule, where an URL https://int.siliconbox.com/sourcegraph is routed to the sourcegraph docker container at port 7080. I can't get that to work.

When I set the ingress route URL to https://int.siliconbox.com and set externalUrl config parameter to the same stiring, everthing works fine. 

But when I set both the route URL and externalUrl to https://int.siliconbox.com/sourcegraph, sourcegraph tries to redirect the request to https://int.siliconbox.com/sign-in?returnTo=%2F, which doesn't exist. 

Is there some config option that I'm missing?

**Comment by sqs** [comment] 2020-01-20 02:51
Unfortunately, Sourcegraph does not support running at a non-root path. You will need to deploy it at an externalURL with a path `/`. Duplicate of https://github.com/sourcegraph/sourcegraph/issues/103. Could you please reply to that issue and answer https://github.com/sourcegraph/sourcegraph/issues/103#issuecomment-477865306 so we can understand your needs here?

**Closed by sqs** 2020-01-20 02:51 UTC
Labels: question, team/distribution 🚢📦💨
