### ISSUE TITLE
Provide affordance to increase context lines in search results

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#26165] opened 2021-10-15 17:44 UTC
Example from Reddit via Atom editor:

![image.png](https://images.zenhubusercontent.com/5467e9ba7c6ccc6277a5f103/d157dd30-fd18-43f8-b2a7-1d31aa378c83)

**Comment by lguychard** [comment] 2021-11-05 12:36
Duplicate of #2754

**Closed by lguychard** 2021-11-05 12:36 UTC
Labels: customer, team/search-product
