### ISSUE TITLE
Chrome plugin not working for certain typescript atoms

### ISSUE THREAD

**Issue by epelc** [sourcegraph/sourcegraph#509] opened 2018-10-24 19:27 UTC
- **Sourcegraph version:**  1.17.0
- **Platform information:**  Chrome Version 70.0.3538.67 (Official Build) (64-bit) and 70.0.3538.77 (Official Build) (64-bit) MacOS 10.14

#### Steps to reproduce:

1. Get the chrome plugin
2. Hover over `protected` on this line

![image](https://user-images.githubusercontent.com/5204642/47455897-0cd82b00-d7a1-11e8-82ac-5f2dfd2728e1.png)
https://github.com/angular/flex-layout/blob/master/src/lib/flex/layout/layout.ts#L46

Hovering over the field name works though.

![image](https://user-images.githubusercontent.com/5204642/47455914-18c3ed00-d7a1-11e8-8502-8857fdd46839.png)

#### Expected behavior:

Should show type info

#### Actual behavior:

You get an error. I've also seen errors like `Error fetching hover from language server:`. Not sure if this is intermittent issues on entire projects or just some local typescript problem? I've been seeing errors for a couple weeks like this. Today is the first time I noticed it halfway working on some things as pointed out by Dan.

**Comment by epelc** [comment] 2018-10-24 19:28
I've also noticed `limited functionality` in my sourcegraph plugin options for some reason. Not sure if this is related or how to fix.

![image](https://user-images.githubusercontent.com/5204642/47456043-71938580-d7a1-11e8-94b1-66922c9f11b9.png)

**Comment by epelc** [comment] 2018-10-24 19:56
Can be on non typescript atoms. See here in c++ code for chromium

**Comment by ijsnow** [comment] 2018-10-24 20:35
Hey, thanks for reporting! 

Looks like this is a [javascript-typescript-langserver](https://github.com/sourcegraph/javascript-typescript-langserver) issue. @felixfbecker would know for sure. I'll leave this issue open before moving it to that issue tracker so Felix can confirm.

And the "Limited Functionality" message is a misleading prompt and will be removed soon. It's just trying to tell you that you can't get all the features from sourcegraph.com that you can with your own instance of Sourcegraph (e.g. private repo support).

And FYI, the [browser extension is also open source](https://github.com/sourcegraph/browser-extensions) so feel free to file issues you're having with it in [it's issue tracker](https://github.com/sourcegraph/browser-extensions/issues)!

**Comment by felixfbecker** [comment] 2018-10-24 20:52
The official TypeScript service (that we use) doesn't show a hover for the visibility modifiers, only for the actual symbol name. I think that is as designed. You're seeing the errors cause there was an install error and when no hover is returned it _may_ be caused by this error so we show it, but we still try to get the hover and return it if we find it (which is what happens when you hover the symbol name)

**Comment by sqs** [comment] 2018-10-25 09:17
@epelc 	The `limited functionality` message is just because Sourcegraph.com does not support private code. We are improving that UX soon (WIP PR https://github.com/sourcegraph/browser-extensions/pull/271 if you're curious).

**Comment by sqs** [comment] 2018-12-06 07:06
@felixfbecker 	Is there any resolution/change, or is this wontfix?

**Comment by felixfbecker** [comment] 2018-12-07 18:00
I think there is nothing actionable here

**Closed by felixfbecker** 2018-12-07 18:00 UTC
Labels: feature:code-intel
