### ISSUE TITLE
GitHub: extensions-contributed notifications are no longer visible

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#6668] opened 2019-11-18 18:01 UTC
#### Steps to reproduce:

1. Activate the Codecov extension 
2. Navigate to github.com/sourcegraph/sourcegraph
3. In the command palette, click "Codecov: set up enterprise"

#### Expected behavior:

See error notification: `'To set a Codecov API token, navigate to a file and then re-run this command.'`

#### Actual behavior:

No error notification is shown.

The error notification is actually correctly emitted and rendered, but is not visible:

![image](https://user-images.githubusercontent.com/1741180/69077390-cf8ead00-0a35-11ea-863b-5f068807d96a.png)

**Comment by felixfbecker** [comment] 2019-11-18 18:08
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/6533 :)

**Closed by felixfbecker** 2019-11-18 18:08 UTC
Labels: browser-extension, bug, extensions
