### ISSUE TITLE
File autocomplete dropdown doesn't use correct file path

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#12100] opened 2020-07-10 18:04 UTC
Reported by https://app.hubspot.com/contacts/2762526/company/578600789

Can't share a video here, but repro:

1. visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph
1. type `main.go` in the search bar and wait for autocomplete to appear
1. select any of the results, and note that the search bar becomes:

`repo:^github\.com/sourcegraph/sourcegraph$ file:^main\.go$ `

which returns no results. The `file:^main\.go$` is missing the rest of the path.

**Comment by dadlerj** [comment] 2020-07-10 18:18
Note that this is not an issue with the old search field (the non-smart-search field)

**Comment by lguychard** [comment] 2020-07-23 14:22
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/12240, this is now fixed.

**Closed by lguychard** 2020-07-23 14:22 UTC
Labels: bug, team/search, team/web, webapp
