### ISSUE TITLE
insights: improve time metadata in legend 

### ISSUE THREAD

**Issue by leonore** [sourcegraph/sourcegraph#33533] opened 2022-04-06 12:57 UTC
As shown in the example below, it can be pretty confusing for some insights to gather what time a data point is referring to. in this case it's 01 Jan of every year (2022, 2021, etc.) The granularity of this insight is set at one data point every 9 months for reference.

<img width="458" alt="image" src="https://user-images.githubusercontent.com/29406849/161979037-6f2051b3-a433-42a3-b103-b443ef261462.png">

I don't think more time metadata would always be necessary so this might need a bit more design to decide what the best path to take is here.

**Comment by sourcegraph-bot-2** [comment] 2022-04-06 12:57
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by Joelkw** [comment] 2022-04-06 18:43
Closing as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/28766 :)

**Closed by Joelkw** 2022-04-06 18:43 UTC
Labels: team/code-insights, frontend, data-viz
