### ISSUE TITLE
Support images

### ISSUE THREAD

**Issue by ammar1x** [sourcegraph/sourcegraph#23] opened 2017-08-06 16:33 UTC
If I open an image it opens as a binary file. It would be nice if I could see an actual image instead.

**Comment by francisschmaltz** [comment] 2019-03-05 22:46
@sqs Where did we land with https://github.com/sourcegraph/enterprise/issues/10316#issuecomment-375221191 ?

**Comment by francisschmaltz** [comment] 2019-03-05 22:46
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/23

**Closed by francisschmaltz** 2019-03-05 22:46 UTC
Labels: feature-request, web

**Comment by sqs** [comment] 2019-03-06 06:32
@francisschmaltz: We are all set with respect to DMCA Safe Harbor, so there are no copyright concerns with serving raw files.
