### ISSUE TITLE
src-cli fails to run campaign with a branch name used in a previous campaign

### ISSUE THREAD

**Issue by chrispine** [sourcegraph/sourcegraph#13582] opened 2020-09-01 22:21 UTC
When creating a campaign that creates a changeset to fix something, and you run another campaign in the future for the same kind of problem (same branch name), publishing the changeset fails, because the branch name is already in use (but is in use for a closed/merged changeset and branch is removed on upstream).

(This is the bug we ran into at the end of our pairing.)

**Comment by eseliger** [comment] 2020-09-02 12:25
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/13405 :)

**Closed by eseliger** 2020-09-02 12:25 UTC
Labels: team/campaigns
