### ISSUE TITLE
repohascommitafter:'1 week ago' type:repo .+ returns empty result set

### ISSUE THREAD

**Issue by aisbaa** [sourcegraph/sourcegraph#8568] opened 2020-02-24 10:47 UTC
- **Sourcegraph version:** 3.12.7

#### Steps to reproduce:

I was not able to reproduce this on sourcegraph.com. Maybe it is related to the amount of repos we have.

1. Search `repohascommitafter:'1 week ago' type:repo .+` 
2. Result set is empty

#### Expected behavior:

A list of repositories that have been updated since a week ago.

#### Actual behavior:

Empty result set.

**Comment by unknwon** [comment] 2020-02-24 13:35
I also get empty result set while using the default literal search, but works with regexp search (your query string really looks like a regexp). Could you make sure this toggle is on?

![image](https://user-images.githubusercontent.com/2946214/75156620-71b4e400-574d-11ea-8347-cdd15032b5e5.png)

**Comment by aisbaa** [comment] 2020-02-24 16:21
I get empty result set with `patternType=regexp` as well. Also would be great if patternType would not disappear from search bar.

Full search query `repohascommitafter:'1 week ago' type:repo .+ patternType=regexp`

**Comment by unknwon** [comment] 2020-02-24 16:27
Maybe it's your typo while posting the comment, but just want to point out in case of any confusion:

```diff
-repohascommitafter:'1 week ago' type:repo .+ patternType=regexp
+repohascommitafter:'1 week ago' type:repo .+ patternType:regexp
```

cc @kzh since I believe you have recent work related to "repohascommitafter" filter?

**Comment by kzh** [comment] 2020-02-24 16:47
It's most likely a performance issue with the number of repositories. Improvements are planned for this 3.14 iteration. This work is being tracked in https://github.com/sourcegraph/sourcegraph/issues/6745.

**Comment by aisbaa** [comment] 2020-02-25 06:58
@unknwon thank you, it's a type in comment, I've copied that bit from url bar, since that keyword disappears after pressing enter.

@kzh thank you, we will be waiting for 3.14 then. Is sourcegraph indexing commits as well?

**Comment by keegancsmith** [comment] 2020-02-25 11:03
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/6745

@aisbaa the feature as currently implemented has poor performance characteristics (we check each repository to see if it passes the filter). We need to move to an indexed approach. Doing this properly is likely out of scope for 3.14. However, I am sure we can adjust the meaning slightly to bring it back into scope. If instead of finding any commit after a certain date, would just finding all repositories with HEAD past a certain date suffice? That way it would quite neatly fit into our current indexed search architecture.

Either way I'll see how we can make the reporting better on the search page / see if there is some lightweight caching we can do.

**Closed** 2020-02-25 11:03 UTC
Labels: customer, team/core-services

**Comment by aisbaa** [comment] 2020-02-25 11:13
Thank you, will track #6745 .

Just an idea and maybe you are already doing or going to do this. It would be really great if all commits would be indexed as well. It would allow to answer `repohascommitafter` as well as dig into commit history.

Here's example from developer:

> I’m trying to find the last time resource ub__message_redacted_redacted was used in java megareppo. It’s an old resource that is no longer used in code, but still around in the XML. I want to find and revert the diff that removed it.

**Comment by keegancsmith** [comment] 2020-02-27 08:04
> It would be really great if all commits would be indexed as well.

Do you mean all branch HEADS, or all commits? All commits is a big index :) But we have discussed implementing an index diff/commit search which would also achieve what you are interested in.

**Comment by aisbaa** [comment] 2020-02-28 13:26
I think indexing diff/commit is what I meant. The commit message author and diff itself.

**Comment by keegancsmith** [comment] 2020-02-28 13:56
aah ok, so just to confirm: indexed search on just commit metadata (message/author/timestamp/etc), not necessarily the file content diff. That is a more tractable problem than indexing the main commit data.

**Comment by aisbaa** [comment] 2020-03-12 13:22
Sorry for lag. It would be great to have diff content (patch part) as well. How much space would it require if it is put in index. Let's say if we would index [chromium/chromium](https://github.com/chromium/chromium) repository, how much would it be in the index?

Also would it be reasonable to use separate index for diff's? It would be nice if history search would not impact performance of code search.

**Comment by keegancsmith** [comment] 2020-03-13 11:45
I think it would be quite large, but we could probably use a solution more customized for this use case than zoekt to avoid the downsides I am thinking of. When we do tackle indexing the commit content it will likely be as a new service. We would probably tackle commit metadata before tackling everything else since that is much more tractable and smaller (and provides quite a bit of value)
