### ISSUE TITLE
Hovers do not appear after navigating to GitHub file

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3319] opened 2019-04-09 10:03 UTC
Repro:

- Go to https://github.com/theupdateframework/notary/tree/master/server/storage with the browser extension
- Click on any of the files (eg https://github.com/theupdateframework/notary/blob/master/server/storage/memory.go)
- Hover over any token in the files that should have a hover

Expected: see the hover
Actual: the yellow token highlight appears but no hover

Notes:

- The hover works on the initially loaded page but stops working after you navigate between pages. (It also breaks if you start on a file, then go to another file.)
- Tested on Chrome 19.4.8.1301
- I don't think this is caused by my recent refactors. The problem also occurs on the older commits 4ba8e271ac92d4ebf77e04fa7a93bf121523a288 and 1c2ff2dc5b330879a503e79da6bc3321ec93305c when running the dev build locally from those commits.

**Comment by felixfbecker** [comment] 2019-04-09 10:06
Likely duplicate of #3228

**Comment by felixfbecker** [comment] 2019-04-09 12:21
Can't repro anymore, probably fixed by #3318

**Closed by felixfbecker** 2019-04-09 12:21 UTC
Labels: browser-extension, bug
