### ISSUE TITLE
Major regression? Search is frequently unreliable, gives incorrect results

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#19733] opened 2021-04-07 04:51 UTC
After-hours Stephen here 👋 

I am regularly finding search on Sourcegraph.com is unreliable:

[`repo:^github\.com/ziglang/zig$ event` returns 11 results](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/ziglang/zig%24+event&patternType=literal), scrolling to the bottom of the page doesn't load any more or anything - it's shown to me as the absolute set:

<img width="885" alt="image" src="https://user-images.githubusercontent.com/3173176/113811895-eebcd600-9721-11eb-8601-08c55b0488aa.png">

Yet as soon as I [add `file:std` to the query](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/ziglang/zig%24+event+file:std&patternType=literal) - which should in theory give me a _subset_ of the results - I instead get 500+ results:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/3173176/113811972-1318b280-9722-11eb-89b7-947457f51d1b.png">

I don't know what's going on here but this seems like a really bad regression.

**Comment by slimsag** [comment] 2021-04-07 04:52
cc @sourcegraph/search

**Comment by rvantonder** [comment] 2021-04-07 06:08
Cross-posting as potentially same issue as https://sourcegraph.slack.com/archives/CHEKCRWKV/p1617753996250500

**Comment by keegancsmith** [comment] 2021-04-07 06:42
Agreed, this looks like a bad regression that we should investigate. I took a quick look this morning. When looking at the trace for your example search with 11 results, Zoekt is returning `1871` file matches. So something is going wrong between zoekt and the results that get streamed down.

My first thought was auth filtering gone awry. However, this is all in one repo so that seems unlikely. There is the possibility that zoekt streaming is the cause (the results where over two events).

More likely is our limiting code is misbehaving. Unsure if its the display limit or result limiting. We have had a few refactors around here so this seems like a legit possibility.

> Cross-posting as potentially same issue as https://sourcegraph.slack.com/archives/CHEKCRWKV/p1617753996250500

Thanks. This does indeed seem very similiar. For context the customer could reproduce on 3.26.2 and downgraded to 3.25 to fix. Also 3.26.2 was an unusual patch release since it included everything from main, rather than just cherry-picks on top of 3.26.1. I believe you (Rijnard) are currently doing a git bisect. Please post updates here :)

**Comment by rvantonder** [comment] 2021-04-07 06:48
Introduced by https://github.com/sourcegraph/sourcegraph/pull/19483.

I bisected on https://github.com/sourcegraph/sourcegraph/compare/v3.26.0...v3.26.1. I checked out the revisions and manually ran the exact same zig query as above (since I could reproduce the `11 result` issue locally). Once I landed on the above PR/commit, the expected `500+ result` message became `11 results`.

**Closed** 2021-04-07 11:37 UTC
Labels: regression, team/search

**Comment by keegancsmith** [comment] 2021-04-07 12:52
@stefanhengl and I tracked this down and the fix is deployed to Sourcegraph.com. This is a serious regression for large repos. We should do a patch release. Will follow-up with distribution in slack.
