### ISSUE TITLE
campaigns: merged imported changeset displays "changeset has no diff"

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#15039] opened 2020-10-26 06:01 UTC
When using the `importChangesets` feature, I can see the diff summary (+/-) but it seems the exact diff does not get displayed. This particular example is from [this test campaign](https://k8s.sgdev.org/organizations/sourcegraph/campaigns/release-sourcegraph-3.21.0), generated by https://github.com/sourcegraph/sourcegraph/pull/15032

![image](https://user-images.githubusercontent.com/23356519/97138620-973e3580-1793-11eb-95c1-8e6186b23974.png)

**Comment by bobheadxi** [comment] 2020-10-26 08:45
Doesn't seem to happen with open PRs - maybe related to the branch being deleted? (ie https://github.com/sourcegraph/sourcegraph/issues/10542)

![image](https://user-images.githubusercontent.com/23356519/97151601-af6d7f00-17aa-11eb-959a-3a71c0b8727a.png)

**Comment by eseliger** [comment] 2020-10-26 23:15
This is a [known limitation](https://github.com/sourcegraph/sourcegraph/issues/10959), but it should probably be communicated better. Ultimately, we also should want to implement it properly.

**Comment by eseliger** [comment] 2020-11-16 15:23
Closing as a duplicate of #14155

**Closed by eseliger** 2020-11-16 15:23 UTC
Labels: bug, team/campaigns
