### ISSUE TITLE
Ensure VS Code extension runs on the web

### ISSUE THREAD

**Issue by tjkandala** [sourcegraph/sourcegraph#28403] opened 2021-12-01 15:41 UTC
Ensure that the VS Code extension can run as a web extension (outlined [here](https://code.visualstudio.com/api/extension-guides/web-extensions#update-existing-extensions-to-web-extensions)).

Most of the work here involves our code sharing features, which depend on git. Search UI, remote browsing, and Sourcegraph extensions do not require any changes to run on the web.

We will first have to get the extension to run on web. We will probably have to output two different main extension bundles: one targeting node, the other targeting WebWorker (`main` vs `browser` path in `package.json`).

**Comment by abeatrix** [comment] 2022-02-08 23:10
Current status:
Finally got search to work after switching to use stream seach api with additional fallback modules on Chrome:
![Screen Shot 2022-02-08 at 2 34 41 PM](https://user-images.githubusercontent.com/68532117/153090810-ce93700e-a007-4c1e-9a36-b7df848dfb5f.png)

Sidebar is not working on Safari:
![Screen Shot 2022-02-08 at 3 06 56 PM](https://user-images.githubusercontent.com/68532117/153090959-dc23274e-4d6f-4fd4-9f72-5722c17b16b9.png)

Both sidebar and search view are not working on Firefox:
![Screen Shot 2022-02-08 at 3 02 54 PM](https://user-images.githubusercontent.com/68532117/153091081-3d27b5c1-a250-4d36-9a65-0876ffff393a.png)

**Comment by abeatrix** [comment] 2022-02-16 19:49
Everything is working as expected on Safari, Chrome, Chromebook, Edge, and Safari on iPad.

![Screen Shot 2022-02-16 at 10 07 29 AM](https://user-images.githubusercontent.com/68532117/154336091-f8e8fa9a-64a4-463c-b321-c3f0ed622b5d.png)

Was running into the same issue on Firefox but it looks like it was caused by the firefox internal setting where setting the `security.csp.enable` option in `about:config` to false has resolved the issue:
![image](https://user-images.githubusercontent.com/68532117/154344131-af7a920f-bcb0-475a-abf6-930f80a49164.png)
![Screen Shot 2022-02-16 at 11 47 18 AM](https://user-images.githubusercontent.com/68532117/154344233-7f608d1c-6568-4c4f-82dd-ee60cb301075.png)

**Comment by abeatrix** [comment] 2022-02-22 21:17
Released in v2.0.9: https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph

**Closed by abeatrix** 2022-02-22 21:17 UTC
Labels: team/growth-and-integrations, vscode-extension, vscode-architecture
