### ISSUE TITLE
"Enable error reporting" with Sentry breaks Firefox extension

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#7689] opened 2020-01-13 19:47 UTC
Reported by a user:

>Great work on Sourcegraph! I use it daily when conducting code reviews on GitHub, through the Chrome extension. However, AFAICT the Firefox extension doesn’t currently work. I think it used to, but when I hover over e.g. function calls in Firefox, Sourcegraph doesn’t respond. The extension is enabled and doesn’t report any problems - I’ve got version 20.1.5.708 and Firefox version 72.0.1 (64-bit) on OS X Catalina.

**Comment by aknuds1** [comment] 2020-01-13 21:55
I'm using the browser extension with https://sourcegraph.com, browsing the https://github.com/grafana/grafana repo.

**Comment by frenata** [comment] 2020-01-13 22:00
Possibly related: with sourcegraph extension `v20.1.10.1433` and FF `72.0.1 (64-bit)` on macOS Mojave, I currently get this error message when clicking on the sourcegraph menu icon:

```
Sourcegraph browser extension is running inject.bundle.js:37358
Detected code host: github inject.bundle.js:37358
Browser extension is enabled inject.bundle.js:37358
TypeError: "'requestAnimationFrame' called on an object that does not implement interface Window."
    ce inject.bundle.js:37358
    scheduleUpdate inject.bundle.js:37358
    _ inject.bundle.js:37358
    componentDidUpdate inject.bundle.js:37358
    Iu inject.bundle.js:37358
    unstable_runWithPriority inject.bundle.js:37358
    Ki inject.bundle.js:37358
    ku inject.bundle.js:37358
    Eu inject.bundle.js:37358
    Ji inject.bundle.js:37358
    unstable_runWithPriority inject.bundle.js:37358
    Ki inject.bundle.js:37358
    Ji inject.bundle.js:37358
    Zi inject.bundle.js:37358
    vu inject.bundle.js:37358
    enqueueSetState inject.bundle.js:37358
    setState inject.bundle.js:37358
    fn inject.bundle.js:37358
    P inject.bundle.js:37358
    P inject.bundle.js:37358
    R inject.bundle.js:37358
    value inject.bundle.js:37358
    o inject.bundle.js:37358
inject.bundle.js:37358
Promise rejection value is a non-unwrappable cross-compartment wrapper.
```

**Comment by slimsag** [comment] 2020-01-13 23:26
This looks like a duplicate of https://github.com/sourcegraph/sourcegraph/issues/7579 so I am going to close in favor of that issue. We're looking into this and will get this resolved soon!

**Comment by dadlerj** [comment] 2020-01-13 23:51
(@aknuds1 let us know if it doesn't sound like that issue, of course, and we can re-open)

**Comment by aknuds1** [comment] 2020-01-14 06:33
@dadlerj it looks as if the other issue describes a different scenario though, where the user configures a different Sourcegraph instance before switching back to the regular one. I haven't done that.

**Comment by felixfbecker** [comment] 2020-03-24 21:09
We're missing info to reproduce here unfortunately - I'm inclined to close this, as we have FF e2e tests back up that are passing and people on the team that use the extension with FF.

**Comment by seh** [comment] 2020-04-08 16:00
I've been having the same problem for at least a month. I have never configured my Sourcegraph add-on to talk to a private repository. It works maybe once or twice against a GitHub page, and then won't work again for a week or more. Uninstalling and reinstalling the plugin doesn't seem to help.

Inspecting the debug view (described in https://github.com/sourcegraph/sourcegraph/issues/7579#issuecomment-572572966) shows errors like the following:
- Error: page is undefined (from _background.js_)
- Promise resolved after context unloaded (from _content-script.js_)

**Comment by seh** [comment] 2020-04-08 19:07
More debugging information: The "Console" view of the extension inspector often reports:
> Error: _getUserID() Not logged in (_background.js:55:7539_)
That, despite me having logged into Sourcegraph's site again within the last few minutes.

Also, in the "Network" tab, I see the extension make about seven requests, and then stop issuing requests. Almostl of the issued requests succeed with HTTP status code 200 and populated response messages. For one of them, though, Firefox reports that it received a truncated response. Or, maybe it's just reporting that it's not showing the entire response.

The request is an HTTP POST against _https://sourcegraph.com/.api/graphql?Extensions_. The request payload is as follows (leaving in the newline escaping that Firefox shows):
```
{"query":"\n                query Extensions($first: Int!, $prioritizeExtensionIDs: [String!]!) {\n                    extensionRegistry {\n                        extensions(first: $first, prioritizeExtensionIDs: $prioritizeExtensionIDs) {\n                            nodes {\n                                id\n                                extensionID\n                                url\n                                manifest {\n                                    raw\n                                }\n                                viewerCanAdminister\n                            }\n                        }\n                    }\n                }\n            ","variables":{"first":34,"prioritizeExtensionIDs":["sourcegraph/clojure","sourcegraph/cpp","sourcegraph/csharp","sourcegraph/cuda","sourcegraph/dart","sourcegraph/elixir","sourcegraph/erlang","sourcegraph/git-extras","sourcegraph/go","sourcegraph/graphql","sourcegraph/groovy","sourcegraph/haskell","sourcegraph/java","sourcegraph/jsonnet","sourcegraph/kotlin","sourcegraph/lisp","sourcegraph/lua","sourcegraph/ocaml","sourcegraph/pascal","sourcegraph/perl","sourcegraph/php","sourcegraph/powershell","sourcegraph/protobuf","sourcegraph/python","sourcegraph/r","sourcegraph/ruby","sourcegraph/rust","sourcegraph/scala","sourcegraph/shell","sourcegraph/swift","sourcegraph/thrift","sourcegraph/typescript","sourcegraph/verilog","sourcegraph/vhdl"]}}
```
The response size is reported as 1.11 MB, 638.23 KB on the wire.

**Comment by seh** [comment] 2020-04-08 19:13
@felixfbecker, can you explain how your staff was able to get the extension to work in Firefox? I demonstrated this failure to @ah3rz a few weeks ago, and I'd be happy to demonstrate it again to someone there who can help get this extension to work with Firefox.

**Comment by seh** [comment] 2020-04-08 19:21
**A ha!** 🎉 

If I uncheck the "Allow error reporting" option in the Sourcegraph add-on settings, even with the other options enabled, and hard-refresh the GitHub pages, this extension works.

Does this relate to #3470?

**Comment by aknuds1** [comment] 2020-04-09 06:28
> If I uncheck the "Allow error reporting" option in the Sourcegraph add-on settings, even with the other options enabled, and hard-refresh the GitHub pages, this extension works.

@seh That works for me too! Thanks!

**Comment by aknuds1** [comment] 2020-04-09 06:29
@felixfbecker I think the issue should be reopened since both @seh and I are seeing the same problem and workaround.

**Comment by frenata** [comment] 2020-04-09 14:41
This has also resolved my issues.

**Comment by felixfbecker** [comment] 2020-04-09 14:43
Thanks for the awesome investigation, @seh! We'll investigate why Sentry breaks FF, because obviously we would like to be informed of other errors through Sentry so we can fix them :)

**Comment by felixfbecker** [comment] 2020-05-02 13:26
The cause of this seems to be https://github.com/getsentry/sentry-javascript/issues/2352.
Replacing `animationFrameScheduler` with `asyncScheduler` works around the issue (and should be better for performance too). https://github.com/sourcegraph/sourcegraph/pull/10367

**Comment by aknuds1** [comment] 2020-05-02 14:52
Good thing you found the culprit @felixfbecker :)

**Closed** 2020-05-02 17:18 UTC
Labels: browser-extension, bug, firefox, team/web
