### ISSUE TITLE
Flaky automation campaigns e2e tests

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#7356] opened 2019-12-23 00:41 UTC
`Create campaign preview for comby campaign type` and `Create campaign preview for credentials campaign type` tests were consistently flaky and disabled in https://github.com/sourcegraph/sourcegraph/pull/7353

**Comment by mrnugget** [comment] 2020-01-06 06:42
Thanks for reporting! I also raised this in the "Flaky CI builds" issue here https://github.com/sourcegraph/sourcegraph/issues/5721#issuecomment-567422137 and I think it's the same flake, but it's good to have an issue to track this.

**Comment by tsenart** [comment] 2020-01-06 10:21
Another: https://buildkite.com/sourcegraph/sourcegraph-e2e/builds/2564#69f9f0eb-339a-4acf-9eba-4fa6220ea898

**Comment by felixfbecker** [comment] 2020-01-12 13:53
According to the screenshot, the repository could not be found by the campaigns backend:

![image](https://user-images.githubusercontent.com/10532611/72219849-f1df0b80-354a-11ea-9b4c-4f0b3086d9c7.png)

Looking at the video recording and the test code, I can see that this repo is passed to `ensureRepos`, so it should be available.
So either there is a problem with `ensureRepos` (which is odd because it seems to work for all other tests, and it's in a `beforeAll`, so by the time it gets to the a8n test it should _really_ be available), or there is some kind of mismatch between repo being user-accessible and repo being available for campaigns. @mrnugget @ryanslade could such a mismatch be possible?

**Comment by mrnugget** [comment] 2020-01-13 11:21
> So either there is a problem with `ensureRepos` (which is odd because it seems to work for all other tests, and it's in a `beforeAll`, so by the time it gets to the a8n test it should _really_ be available), or there is some kind of mismatch between repo being user-accessible and repo being available for campaigns. @mrnugget @ryanslade could such a mismatch be possible?

I can't see how. What we do when we run a CampaignPlan is to run the search, get back `RepositoryResolver`s and then, for each of them, ask gitserver for the default branch.

When trying to run the e2e locally the browser opened the repo page, but I got an "invalid URL" message. The console was spammed with auth error messages:

```
12:16:45            frontend | ERROR Error prefetching SAML service provider metadata., error: fetching SAML Identity Provider metadata: Get http://localhost:3220/auth/realms/master/protocol/saml/descriptor: dial tcp [::1]:3220: connect: connection refused
12:16:45            frontend | ERROR Error prefetching OpenID Connect service provider metadata., error: Get http://localhost:3220/auth/realms/master/.well-known/openid-configuration: dial tcp [::1]:3220: connect: connection refused
12:16:45            frontend | ERROR Error prefetching SAML service provider metadata., error: fetching SAML Identity Provider metadata: Get http://localhost:3220/auth/realms/master/protocol/saml/descriptor: dial tcp [::1]:3220: connect: connection refused
12:16:45            frontend | ERROR Error prefetching OpenID Connect service provider metadata., error: Get http://localhost:3220/auth/realms/master/.well-known/openid-configuration: dial tcp [::1]:3220: connect: connection refused
12:16:49            frontend | ERROR Error prefetching OpenID Connect service provider metadata., error: Get http://localhost:3220/auth/realms/master/.well-known/openid-configuration: dial tcp [::1]:3220: connect: connection refused
12:16:49            frontend | ERROR Error prefetching SAML service provider metadata., error: fetching SAML Identity Provider metadata: Get http://localhost:3220/auth/realms/master/protocol/saml/descriptor: dial tcp [::1]:3220: connect: connection refused
12:16:49            frontend | ERROR Error prefetching OpenID Connect service provider metadata., error: Get http://localhost:3220/auth/realms/master/.well-known/openid-configuration: dial tcp [::1]:3220: connect: connection refused
12:16:49            frontend | ERROR Error prefetching SAML service provider metadata., error: fetching SAML Identity Provider metadata: Get http://localhost:3220/auth/realms/master/protocol/saml/descriptor: dial tcp [::1]:3220: connect: connection refused
12:16:55            replacer | INFO running command: comby "file files -zip /tmp/replacer-archives/9045163af2cb31afdb1d45427215ec1a36146fd70ef2b6c440f5c1af028ef20c.zip -json-lines -json-only-diff"
```

That makes me wonder whether this isn't related to https://github.com/sourcegraph/sourcegraph/issues/5286, which is coincidentally [waiting for your feedback](https://github.com/sourcegraph/sourcegraph/issues/5286#issuecomment-541720708) @felixfbecker

**Comment by mrnugget** [comment] 2020-01-13 11:31
<img width="1264" alt="Screen Shot 2020-01-13 at 12 29 28" src="https://user-images.githubusercontent.com/1185253/72252874-80619480-3600-11ea-9716-7005e36593b0.png">

This is what I got locally. But: this did _not_ stop the rest of the tests from executing.

**Comment by mrnugget** [comment] 2020-01-13 14:00
I cannot reproduce the "Repository does not exist" message (I don't even know, at the moment, where it originates). Even when I simulate a "slow cloning" (by hacking a sleep-statement in gitserver) the output is different and says "No changesets", because it couldn't find the repository.

**Comment by mrnugget** [comment] 2020-01-30 09:30
Closing this because the tests have been enabled again, not shown up as flaky and are fundamentally different than before (since we removed large parts of the UI flow in the past week)

**Closed by mrnugget** 2020-01-30 09:30 UTC
Labels: automation, bug, e2e-tests
