### ISSUE TITLE
Browser extension should gracefully handle auth proxies signing users out after inactivity

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#3440] opened 2019-04-16 18:35 UTC
Reported by https://app.hubspot.com/contacts/2762526/company/407948923 

It is common for authentication proxies to be configured to sign users out after some period of inactivity. When using such an auth proxy with Sourcegraph, this results in errors bubbling up through the browser extension UI without clear explanation on how to solve the problem.

How it looks:

1. You are using the Sourcegraph browser extension, everything works fine.
2. The next day, after your laptop was inactive, you've been signed out of Sourcegraph.
3. The browser extension shows 403 Unauthorized or 401 Unauthenticated errors in the UI at various UI points (e.g. when hovering over code).
4. As a user, the browser extension looks broken and it's not clear what you need to do to resolve these errors (the solution is to visit your Sourcegraph instance and re-authenticate via the auth proxy).

It would be much nicer if we could detect 403/401 status codes and display something more obvious like a panel / even JS alert which says `Please visit https://my-sourcegraph-instance to authenticate.`

**Comment by felixfbecker** [comment] 2019-04-16 18:55
Rel https://github.com/sourcegraph/sourcegraph/pull/3292

**Comment by nicksnyder** [comment] 2019-04-22 23:37
I suspect that this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/545 (if so close one or the other)

**Comment by felixfbecker** [comment] 2019-06-05 10:43
We now show a hint to log in when the user is not:

**Comment by chrismwendt** [comment] 2019-06-05 22:22
Someone else suggested surfacing that as a badge on the extension icon.

**Comment by lguychard** [comment] 2019-06-06 09:23
Yeah, we were already showing the hint in the popup when this issue was opened. It's good that we show it, but it's not discoverable enough for users who might start to experience unpredictable failures when they get signed out by their auth proxy. I would go for something more discoverable:
- In-page error notification when getting 401s on graphQL requests (although this may be too intrusive)
- Greyscaled + badged extension icon when this happens

**Comment by felixfbecker** [comment] 2020-03-24 17:23
Question for definition of success: Is it enough to only handle this on new page visits / reloads? Or do we need to catch errors on tabs that have been open for longer than the auth proxy timeout? The latter would be difficult, because requests are done within extensions, and we can't easily enforce what errors thrown by the extension look like on a 401.

**Comment by nicksnyder** [comment] 2020-03-24 17:30
> Is it enough to only handle this on new page visits / reloads

Solving this part would be a huge improvement from where we are today and I think we could close these issues if we just solved this part.

**Comment by lguychard** [comment] 2020-03-25 07:12
@felixfbecker it looks like your work on #9112 would de facto handle this on new page visits / reloads?

**Comment by felixfbecker** [comment] 2020-03-25 10:02
Exactly.

**Comment by slimsag** [comment] 2020-05-14 17:46
It looks like 401 is handled but 403 is not, which unfortunately is returned by this customer (and I suspect others) with proxies. Reopening to discuss supporting that / thinking about the impact of supporting that.

Additional context: https://sourcegraph.slack.com/archives/CMT39K56Z/p1589477130441100

**Closed** 2020-05-18 17:34 UTC
Labels: browser-extension, bug, estimate/2d, team/web
