### ISSUE TITLE
a8n: Querying/filtering changesets on campaign page

### ISSUE THREAD

**Issue by ryanslade** [sourcegraph/sourcegraph#7550] opened 2020-01-08 12:53 UTC
From [RFC 20](https://docs.google.com/document/d/1UY9B_kLlwRtYj-fuv7XZS1-Mu99Czx9Ojm7sgEmoQIA/edit)

Querying/filtering by 
* open/merged/close & review status
* labels

**Comment by tsenart** [comment] 2020-03-17 09:40
I believe this is a duplicate of #8462.

**Closed by tsenart** 2020-03-17 09:40 UTC
Labels: campaigns, team/core-services, team/web
