### ISSUE TITLE
Base URL?

### ISSUE THREAD

**Issue by STaRDoGG** [sourcegraph/sourcegraph#3567] opened 2019-04-24 00:41 UTC
I'm trying to get SourceGraph setup behind a Caddy reverse proxy but I'm not seeing any place to enter a base URL in SG, am I missing it somewhere?

**Comment by slimsag** [comment] 2019-04-24 01:38
I believe you may be looking for https://docs.sourcegraph.com/admin/url

**Comment by STaRDoGG** [comment] 2019-04-24 13:39
Hi @slimsag 

Can you give me a tested and working example? Perhaps I'm just doing it wrong, but it's not working for me.

**My reverse proxy URL using Caddy is like this:**
https://my.domain.rocks:9119/sourcegraphdoc

**So far I've tried using (with no success):**
"externalURL": "https://my.domain.rocks:9119/sourcegraphdoc"
"externalURL": "my.domain.rocks:9119/sourcegraphdoc"
"externalURL": "/sourcegraphdoc"

Typically when setting a base URL in web apps, the last example above is what would be used.

**Comment by STaRDoGG** [comment] 2019-04-24 14:20
Looks like I sorted it out.

I had to make a special subdomain just for SG in order to reverse proxy it with Caddy.

**So rather than:**
https://my.domain.rocks:9119/sourcegraphdoc

**It's now:**
https://sourcegraph.domain.rocks:9119

With "externalURL": "https://sourcegraph.domain.rocks:9119"

Would still like to have the standard Base URL setting available, though. =)

**Comment by dadlerj** [comment] 2019-04-24 15:23
Hi @STaRDoGG, glad that worked! I believe this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/103

If you disagree, please re-open

**Closed by dadlerj** 2019-04-24 15:23 UTC
