### ISSUE TITLE
Gitea integration support

### ISSUE THREAD

**Issue by lunny** [sourcegraph/sourcegraph#762] opened 2018-10-08 14:15 UTC
[Gitea](https://github.com/go-gitea/gitea) is a welcome open source self-host git service. It's better to support Gitea instance on sourcegraph browser extensions. Will resolve https://github.com/go-gitea/gitea/issues/5010

**Comment by sqs** [comment] 2018-11-21 05:48
Duplicate of #343

**Closed by sqs** 2018-11-21 05:48 UTC
Labels: browser-extension
