### ISSUE TITLE
Handle extension errors more gracefully

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#6772] opened 2019-11-22 18:31 UTC
When viewing https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/master/utils/get_remote_digest.py

I am seeing errors: 
![image](https://user-images.githubusercontent.com/1559622/69450822-e1f93700-0d12-11ea-9115-43e6009d12f2.png)

I am getting these even with my browser extension disabled, so they are coming through the native integration some how. Confirmed that by turning off the codecov extension on my Sourcegraph.com profile the errors go away.

**Comment by felixfbecker** [comment] 2019-11-22 18:35
This is caused by https://github.com/codecov/sourcegraph-codecov/issues/3

I don't know what we should do here though, or what the problem with the logs is? I think we do need to log extension errors, else we and extension errors would never know about them. Did you see actual broken functionality from this that reached beyond CodeCov's features?

**Comment by lguychard** [comment] 2020-02-24 13:25
@christinaforney the upstream issue https://github.com/codecov/sourcegraph-codecov/issues/3 was closed.

As per @felixfbecker's comment above, I think it is valuable to log extension errors when they happen (which should not be the norm). I'll go ahead and close this, please reopen if you think we should handle these logs differently.

**Closed by lguychard** 2020-02-24 13:25 UTC
Labels: browser-extension, extensions, team/web
