### ISSUE TITLE
Update campaigns documentation for new workflow

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#12784] opened 2020-08-06 09:58 UTC
We still have a ton of TODOs in our updated documentation:

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+f:doc/user/campaigns+TODO&patternType=regexp

Not all of them are valid, but this ticket should serve as a placeholder for a "fix the TODOs"

**Comment by poojaj-tech** [comment] 2020-08-10 20:48
@mrnugget heads up, I created a separate issue [12888](https://github.com/sourcegraph/sourcegraph/issues/12888) for a customer request for documentation. (I'm assuming this documentation request is for the old workflow)

**Comment by marekweb** [comment] 2020-08-13 13:35
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.19 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by LawnGnome** [comment] 2020-09-10 16:12
Duplicate of #13153.

**Closed by LawnGnome** 2020-09-10 16:12 UTC
Labels: team/campaigns
