### ISSUE TITLE
No hover tooltips for TypeScript tokens with "$"

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#6858] opened 2019-11-26 13:54 UTC
It looks like tokens that include a `$` break the hover. Look at this file: https://sourcegraph.sgdev.org/sourcegraph/sourcegraph@42be983d34238213c2c438fb855a533ad5d6d767/-/blob/shared/src/api/extension/api/search.ts

Hover over `$findTextInFiles`.

Only the `$` is highlighted and the hover shows `any`:

<img width="830" alt="Screen Shot 2019-11-26 at 14 51 27" src="https://user-images.githubusercontent.com/1185253/69639371-af29a880-105c-11ea-8893-e8da7958b15d.png">

**Comment by felixfbecker** [comment] 2020-03-24 19:11
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/2341

This only affects the highlighting - the hover on that particular property is `any` when dependencies are not installed yet, because the object is of a type from a dependency (`comlink`). Once dependencies finished installing (see progress bar in the top right), the hover shows the right type:

![image](https://user-images.githubusercontent.com/10532611/77467055-8b5c5080-6e0b-11ea-8295-9c84d325c2c6.png)

**Closed** 2020-03-24 19:11 UTC
Labels: bug, team/code-intelligence, team/web, webapp
