### ISSUE TITLE
OIDC authentication failed: "no OpenID Connect state cookie found"

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#5174] opened 2019-08-12 23:25 UTC
- **Sourcegraph version:** 3.6.0
- **Platform information:** Single-server Docker image

Reported by https://app.hubspot.com/contacts/2762526/company/814799425 

(Slack thread at https://sourcegraph.slack.com/archives/CHPC7UX16/p1565650447094000)

>I have a user that is not able to login with our OIDC provider…they get this message:
>`Authentication failed. Try signing in again (and clearing cookies for the current site). The error was: no OpenID Connect state cookie found (possible request forgery, or more than 15m0s elapsed since you started the authentication process)`

>in the logs I see:
>`t=2019-08-12T21:59:28+0000 lvl=eror msg="OpenID Connect auth failed: no state cookie found (possible request forgery)."`
>any idea how to toubleshoot?
>they cleared all their cookies, etc. I tried nuking their user.  neither helped.

**Comment by slimsag** [comment] 2019-08-13 21:17
I don't know the answer and @sourcegraph/core-services will be the ones to look into this, but from the description I am reminded of two prior issues from our private issue tracker long before we went OSS.

The 2nd is one I reported last year but we ended up not being able to reproduce it. I'm not positive they are related, but they appear to be on the surface, so could be helpful.

1. https://github.com/sourcegraph/enterprise/issues/9468

> If I go to 18.216.79.60 and I have configured an appURL of ec2-18-216-79-60.us-east-2.compute.amazonaws.com, then we should always redirect first.
>
> If we don't redirect first, and OIDC is enabled, then we see an error in auth callbacks because the domains don't match:
> SSO error: No OIDC state cookie found possible request forgery

This one would imply perhaps the user is being redirected to a wrong URL, somehow.

2. https://github.com/sourcegraph/enterprise/issues/11584

In the above, I ran into the same error but clearing my browser cookies & site data in Chrome worked around the issue.

**Comment by keegancsmith** [comment] 2019-08-14 06:06
I don't want to drop the ball on this and I am unsure how to prioritise/triage. @dadlerj can you provide some guidance?

**Comment by dadlerj** [comment] 2019-08-20 23:00
Thanks @slimsag and @keegancsmith, sorry for letting this slip. What's so odd here is that the issue is only affecting _one_ of 50+ users. Mismatched URLs would lead me to think about the `externalURL` setting, but I don't understand how it could only affect one person.

Would be nice to get someone to check it out during 3.8 if possible.

**Comment by eculver** [comment] 2019-08-20 23:17
I just confirmed with the affected user that the problem is no longer present. It's not a very satisfying outcome, but it's better than it not being resolved. Unless there's something else I can provide, I'm ok with closing this out.

**Comment by dadlerj** [comment] 2019-08-20 23:19
Got it, how strange, but thanks for the update @eculver. If the user knows of anything that could have changed, and of course if you see anything like it again, please just let us know.

Otherwise, closing this for now.

**Comment by eculver** [comment] 2019-08-20 23:20
The only thing that I'll add is that after the original report, I had applied an upgrade from 3.6.1 to 3.6.2 which rolled all the associated pods.

**Comment by dadlerj** [comment] 2019-08-20 23:24
Cool. I'll reopen and leave it up to the dev team to make the call on whether to close or not.

**Comment by tsenart** [comment] 2019-12-17 16:36
Closing this for now. Will open again if it resurfaces.

**Closed by tsenart** 2019-12-17 16:36 UTC
Labels: auth, bug, customer, team/core-services
