### ISSUE TITLE
Sign out automatically signs me back in (using GitHub auth after disabling basic auth)

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#1852] opened 2019-01-13 21:12 UTC
- Visit http://localhost:7080/search
- Disable basic auth
- Enable GitHub auth
- Sign in using GitHub
- Clicking "Sign out" reloads the page and signs me back in immediately

@beyang had explained to me that since there's only 1 auth provider (GitHub), Sourcegraph is redirecting me to the GitHub auth page, which succeeds and then redirects me back and signs me in to Sourcegraph.

One idea is for the "Sign out" button to take you to a different page. Another is to not show the "Sign out" button at all, and to actually sign out you have to sign out of GitHub.

**Comment by francisschmaltz** [comment] 2019-01-13 21:20
We should have a sign out page, or redurect to the auth provider site (GitHub.com) for example. 

I’d much prefer a dedicated sign out page with option to sign back in.

**Comment by beyang** [comment] 2019-01-13 23:10
Removing this as a release-blocker

@francisschmaltz which of the following flows?

* "Sign out" clicked on Sourcegraph -> delete user session (not user visible) -> redirect to https://github.com/logout.
* "Sign out" clicked on Sourcegraph -> Sign out page indicated they signed out with link to https://github.com/logout that gives the user the option to sign out of GitHub, as well.

**Comment by francisschmaltz** [comment] 2019-01-13 23:32
The second option. Sign out page with node to go to auth provider to logout of that session

**Comment by beyang** [comment] 2019-01-15 21:24
Closing as a dupe of https://github.com/sourcegraph/sourcegraph/issues/1834

**Closed by beyang** 2019-01-15 21:24 UTC
Labels: auth
