### ISSUE TITLE
search: highlighting incorrect lines and columns

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#17686] opened 2021-01-26 14:20 UTC
Unsure if this is a recent regression (changes to highlighting code for perf?) or an old issue. To reproduce search `zoekt` on sourcegraph.com. Results from https://sourcegraph.com/github.com/72crm/72crm/-/blob/vendor/phpexcel/PHPExcel/locale/nl/functions?subtree=true and https://sourcegraph.com/github.com/DirkJanJansen/Pandora/-/blob/bestelOrder.py?subtree=true are incorrect. See screenshot below.

![image](https://user-images.githubusercontent.com/187831/105856806-49370900-5ff2-11eb-94bc-5e1bf6a238e1.png)

cc @camdencheek

**Comment by camdencheek** [comment] 2021-01-26 20:12
Hey @keegancsmith! Am I cc'd on this because you think I might know something about it, or because it would be a good issue for me to tackle? If the former, I haven't touched highlighting yet

**Comment by keegancsmith** [comment] 2021-01-26 20:35
Stefan mentioned you made some changes around offset/ranges
recently. However, I didn't dig in to see if it was related, so was just
hoping for the best :)

**Comment by camdencheek** [comment] 2021-01-26 21:51
I believe that was @rvantonder -- maybe #17258?

**Comment by rvantonder** [comment] 2021-01-26 22:57
I did stuff with symbols. Symbols highlighting (offsets, etc.) is computed differently from file highlights. This looks like a dupe of an issue I filed already: https://github.com/sourcegraph/sourcegraph/issues/17394.

I think if you run that query against the GQL API the correct line/offsets will return, and the rendering is off. I confirmed I can reproduce your issue when `      "enableFastResultLoading": false` so I don't think that's the issue. Whoever would own #17394 probably owns this. I don't own this, and I feel like #17394 is a web issue due to GQL API test I did. So if this falls under a search label, I guess we need to find an owner for frontend highlighting.

**Comment by rvantonder** [comment] 2021-01-26 23:00
Though, because this is popping up again, I'm wondering if maybe the `enableFastResultLoading` changes had changes that are not protected by the flag. I shall investigate (but only that part, to rule out those changes as being the problem).

**Comment by rvantonder** [comment] 2021-01-26 23:20
Confirmed that the fast result loading work is likely not the cause and this has been an issue for at least 3 months: https://github.com/sourcegraph/sourcegraph/issues/17394#issuecomment-767893473. Seems that some file contents are just susceptible to this bug. I am noticing the presence of `#` being a common factor in these wrongly-offset highlights (and the wrong offsets seem to be somewhat similar, like, they are one line above, and slightly to the right of matches, in some cases).

**Comment by keegancsmith** [comment] 2021-01-27 06:47
@lguychard this seems like a pretty embarrassing bug to be honest, I'm surprised it has been going on for 3 months. Do you have an idea of who could tackle this?

**Comment by lguychard** [comment] 2021-01-27 16:30
I will dig into this tomorrow to verify if this is an issue with our frontend syntax highlighting code.

**Comment by Strum355** [comment] 2021-02-04 22:03
Reproduced this issue again. Two precise results with the file and column/offset right, but the wrong line numbers

https://sourcegraph.com/github.com/rust-analyzer/rust-analyzer@188db89/-/blob/editors/code/src/persistent_state.ts#L35:9&tab=references


![image](https://user-images.githubusercontent.com/18282288/106960901-b5bdb080-6734-11eb-9908-3c1729d83549.png)

**Comment by rvantonder** [comment] 2021-05-19 20:08
This issue appears to be fixed for all the examples in this thread. Probably thanks to @camdencheek 's touch ups?

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/72wukong/72crm-9%5C.0-PHP%24+file:%5Evendor/phpexcel/PHPExcel/locale/nl/functions+zoekt&patternType=literal

https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/DirkJanJansen/Pandora-Enterprise_Resource_Planning%24+file:%5EbestelOrder%5C.py+zoekt&patternType=literal

https://sourcegraph.com/github.com/rust-analyzer/rust-analyzer@188db89/-/blob/editors/code/src/persistent_state.ts#L35:9&tab=references

Closing.

**Closed by rvantonder** 2021-05-19 20:08 UTC
Labels: team/search
