### ISSUE TITLE
Detailed search counts

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#17618] opened 2021-01-25 18:40 UTC
We currently display only a summarized metric for search result count at the top of results. 

We have additional data that may be helpful to users such as the number of line matches, file matches, symbols, repositories, and other items that all can display in the same results. Displaying these detailed metrics will promote trust by providing a more complete understanding of search results. 

This data can be displayed at the bottom of results but should also be displayed as part of the search notifications.

**Comment by limitedmage** [comment] 2021-01-26 19:21
@rrhyne  is this a duplicate of #17573?

**Comment by rrhyne** [comment] 2021-01-26 21:22
It is, I thought we need an issue here. Thanks for the heads up.

**Closed** 2021-01-26 21:22 UTC
Labels: needs-design, team/search
