### ISSUE TITLE
Repository listing page has too much indentation.

### ISSUE THREAD

**Issue by tsenart** [sourcegraph/sourcegraph#2591] opened 2019-03-05 20:05 UTC
![image](https://user-images.githubusercontent.com/67471/53834431-3b55e600-3f8b-11e9-9b63-6cca4e9228df.png)

**Comment by nicksnyder** [comment] 2019-03-05 23:05
This is a regression since 3.1. I am going to git bisect to see if I can identify the commit.

**Comment by nicksnyder** [comment] 2019-03-05 23:47
This regressed in https://github.com/sourcegraph/sourcegraph/commit/d42ed0fc19e22603abb2a4358d257dcb2e8b77fb

Assigning to @chrismwendt .

**Comment by chrismwendt** [comment] 2019-03-05 23:48
Ah, looks like I missed a CSS selector somewhere. Looking now.

**Closed** 2019-03-06 07:51 UTC
Labels: bug
