### ISSUE TITLE
Error listing viewer's affiliated GitHub repositories

### ISSUE THREAD

**Issue by chaseconey** [sourcegraph/sourcegraph#218] opened 2018-10-02 17:32 UTC
- **Sourcegraph version:** 2.11.2

- **Platform information:**
Docker - `Docker version 18.06.1-ce, build e68fc7a`
OS Version - `macOS High Sierra 10.13.6`

#### Steps to reproduce:

Just running through the quickstart here

1. `docker run --publish 7080:7080 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock sourcegraph/server:2.11.2`
2. Go to [http://localhost:7080/site-admin/repositories](http://localhost:7080/site-admin/repositories) and click "Add Github Repositories"
3. Generate Personal Access Token and enter into configration. Final config looks like this:

```json
{
  "auth.providers": [
    {
      "type": "builtin"
    }
  ],
  "disablePublicRepoRedirects": true,
  "maxReposToSearch": 50,
  "github": [
    {
      "token": "xxx",
      "url": "https://github.com"
    }
  ]
}
```

#### Expected behavior:

Visible repositories to add and index.

#### Actual behavior:

UI states `No repositories`

Error in console:

```
17:31:46   repo-updater | t=2018-10-02T17:31:46+0000 lvl=eror msg="Error listing viewer's affiliated GitHub repositories" endCursor=<nil> error="json: cannot unmarshal number into Go value of type string"
```

**Comment by keegancsmith** [comment] 2018-10-03 14:51
Weird! I'll improve the error message here to try and make it more debuggable. However, I can't reproduce with my own access token. Do you mind sharing the output of the query? If you wanna keep it private you can email me keegan at sourcegraph.com

To run the query go to https://developer.github.com/v4/explorer/

query:
```graphql
query AffiliatedRepositories($first: Int!, $after: String) {
  viewer {
    repositories(first: $first, after: $after, affiliations: [OWNER, ORGANIZATION_MEMBER, COLLABORATOR], orderBy: {field: PUSHED_AT, direction: DESC}) {
      nodes {
        ...RepositoryFields
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
  rateLimit {
    cost
  }
}

fragment RepositoryFields on Repository {
  id
  nameWithOwner
  description
  url
  isPrivate
  isFork
  isArchived
  viewerPermission
}
```
query variables:
```json
{"first": 100, "after": null}
```

**Comment by chaseconey** [comment] 2018-10-04 01:42
Thanks for the response! Here is the output you requested:

```
{
  "data": null,
  "errors": [
    {
      "message": "Variable first of type Int! was provided invalid value",
      "locations": [
        {
          "line": 1,
          "column": 30
        }
      ]
    }
  ]
}
```

**Comment by keegancsmith** [comment] 2018-10-04 14:19
Hey, thanks for sending the information. Unfortunately that didn't help. It seems to happen on your last page of repos returned. That will be a bit painful to do manually, so rather I have sent a PR which improves the error message. https://github.com/sourcegraph/sourcegraph/pull/260 Once that is merged I'll give you instructions to try out a build of it. Thanks for your patience.

**Comment by chaseconey** [comment] 2018-10-04 22:46
Ok great - let me know and I can definitely give it a run.

Thanks!

**Comment by keegancsmith** [comment] 2018-10-11 13:27
Oops, forgot to give instructions! You use the insiders tag to use a version of server which includes the extra debugging information. Mind trying that out and pasting the extra output?

```
docker run --publish 7080:7080 --rm --volume ~/.sourcegraph/config:/etc/sourcegraph --volume ~/.sourcegraph/data:/var/opt/sourcegraph --volume /var/run/docker.sock:/var/run/docker.sock sourcegraph/server:insiders
```

**Comment by chaseconey** [comment] 2018-10-12 22:01
Looks like I am getting the same error message.

```
21:57:34   repo-updater | t=2018-10-12T21:57:34+0000 lvl=eror msg="Error listing viewer's affiliated GitHub repositories" endCursor=<nil> error="json: cannot unmarshal number into Go value of type string"
```

**Comment by keegancsmith** [comment] 2018-10-18 09:44
Ok so I wrote a mini program which runs the same code Sourcegraph does, but records the HTTP interactions so we can try and narrow down what is happening here.
- [code](https://github.com/sourcegraph/sourcegraph/commit/37072101fd1e617a2cc3c783a4667fb386dd1f21)
- [github-list-darwin.gz](https://github.com/sourcegraph/sourcegraph/files/2491250/github-list-darwin.gz)
- [github-list-linux.gz](https://github.com/sourcegraph/sourcegraph/files/2491251/github-list-linux.gz)

Download the relevant binary, `gunzip` it, then you can run it like so

```
$ ./github-list-darwin -token=XXXXXXXXX
```

where XXXX is your github token used to configure sourcegraph. You should then get a file that lookes like `githublist-20181018114211.yaml` which you can email to me. It should have secrets redacted.

**Comment by keegancsmith** [comment] 2018-10-23 19:31
@chaseconey if you use `12.2.1` this issue should be gone. We just switched away from using the graphql API so this will very unlikely occur for you now.

**Closed by keegancsmith** 2018-10-23 19:31 UTC
Labels: needs-more-info
