### ISSUE TITLE
search: Timeout alert with results

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#20319] opened 2021-04-22 18:49 UTC
A customer reported an [issue](https://github.com/sourcegraph/customer/issues/308) in which a timeout alert was shown even though the search returned results. The alert says "We weren't able to find any results", which is clearly not true. It appears alerts are being improperly propagated. A similar issue exists [here](https://github.com/sourcegraph/sourcegraph/issues/20193). 

I've been unable to reproduce this so far, but it seem pretty clear it's an issue.

**Comment by rvantonder** [comment] 2021-04-22 20:54
What I suspect is happening is that "we did not find any results" happens on one of the indexed branches, but we do find results on the other. The backend is capable of returning alerts _and_ results (this is a good thing if we want to surface both alerts and results), but incorrect when that alert is "there are no results".

For https://github.com/sourcegraph/sourcegraph/issues/20193 I suspect the underlying reason is the same, but this time it's because one of the expressions don't find results, and when we merge `<no result> intersect <some result>` we don't clear the "no result" alert. This fix will happen in a different place compared to wherever we are doing "<no result on some repo branch> union <some results>" (this issue).

**Comment by keegancsmith** [comment] 2021-04-23 12:39
@rvantonder is correct. I read the code a bit, and I believe the cause is our `allReposTimedout() bool` helper method returns true if all repos have a timed out status. In the linked search we found results on some branches, but others timed out. Those timeouts set the `timedout` bit for the repo. We should only show this alert if there are no results. This is a little tricky at this point of the code thanks to streaming :D But to be honest we (@stefanhengl) tried to remove this check here and have it all in one place (like the rest of the alerts). I think the proper fix is to make this alert behave properly like the rest, and not have a special `doResultsWithTimeoutSuggestions` function.

https://github.com/sourcegraph/sourcegraph/blob/5a1aee3a350c6a9d8ba9c10069a6664402728557/cmd/frontend/graphqlbackend/search_results.go#L989

**Comment by keegancsmith** [comment] 2021-04-23 13:05
@camdencheek I got started on a good fix for this, instead of the hacky stuff we have. Mind if I take this?

**Comment by camdencheek** [comment] 2021-04-23 13:06
@keegancsmith please do!

**Closed** 2021-08-30 04:21 UTC
Labels: bug, team/search, team/search-product, team/search-core
