### ISSUE TITLE
Allow Sourcegraph.com + private instance to work at same time on the extension.

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#15158] opened 2020-10-29 16:17 UTC
Users who want to use the Sourcegraph extension with a private repo and on public code currently have to switch the URL in their extension. We should support sourcegraph.com all the time on the extension and then also allow someone to input a private Sourcegraph instance (longer term: multiple private sourcegraph instances?).

**Comment by felixfbecker** [comment] 2020-10-29 16:28
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/643 ?

**Comment by Joelkw** [comment] 2020-10-29 16:31
Yep, thank you! Was trying to find that but poor connection this morning and search results weren't loading.

**Closed** 2020-10-29 16:31 UTC
Labels: browser-extension, needs-rfc, team/web
