### ISSUE TITLE
insights: scrollbar on large legends requires clicking to focus to use

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#31030] opened 2022-02-11 02:30 UTC
[From a user: ](https://sourcegraph.slack.com/archives/C02BJ8T258D/p1644546346188579?thread_ts=1642634786.042000&cid=C02BJ8T258D)
> The scrollbar is a bit clunky. I can't scroll by hovering my mouse over it and using the scroll wheel, I actually need to point and click

The optimal state is that you can simply hover your curser over the area to scroll.

**Comment by Joelkw** [comment] 2022-02-12 06:19
@vovakulikov hmm, they're on 3.36.2. Maybe it's something with their browser + mouse + other extensions or something? I can put you in touch with the user next week if you'd like to follow up with them or see if they can share a recording!

**Comment by unclejustin** [comment] 2022-06-29 16:25
@Joelkw we cannot reproduce. Can you either confirm this is still an issue or close, please?

**Comment by vovakulikov** [comment] 2022-07-18 05:41
@Joelkw I'm closing it for now as neither of us could reproduce this.

**Closed by vovakulikov** 2022-07-18 05:41 UTC
Labels: webapp, ux, team/code-insights
