### ISSUE TITLE
ci: add an annotation on soft fails 

### ISSUE THREAD

**Issue by jhchabran** [sourcegraph/sourcegraph#26079] opened 2021-10-14 09:40 UTC
Soft fails are hard to see when skimming over a build failure. By adding an annotation, we could make make that very obvious and avoid "jump scares".

**Comment by bobheadxi** [comment] 2021-12-15 16:39
cc @jhchabran  I'm closing this as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/28283

**Closed by bobheadxi** 2021-12-15 16:39 UTC
Labels: dx, ci, dx-announce, team/devx, RFC-496
