### ISSUE TITLE
Trailing backslash at end of expression: `` when searching for valid regexp

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7604] opened 2020-01-09 04:49 UTC
https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%28%5C+%7C%5C.%7C%29getOrganization%5C%28&patternType=regexp

This is a perfectly valid re2 expression: https://play.golang.org/p/qxzlrpx1ecm

The problem is by our query parser as two seperate regexp terms: `(\ |\.|)getOrganization\(` becomes `(\ ` and `|\.|)getOrganization\(` since we split using spaces.

AFAIK we have some planned work already to make this better in the near future I believe, filing this for tracking purposes anyway.

**Comment by slimsag** [comment] 2020-01-09 05:42
Better workaround than using `\s`:

**Comment by keegancsmith** [comment] 2020-01-09 07:50
@rvantonder I am guessing the fix here is in our query parser, to add support for escaping spaces. May interact weirdly with literal search though. cc @sourcegraph/core-services

**Comment by rvantonder** [comment] 2020-01-09 16:58
> I am guessing the fix here is in our query parser, to add support for escaping spaces. May interact weirdly with literal search though.

I think that's the quick fix. What we should really do is create separate regex and literal parsers and support escaping in one and not the other.

**Comment by noahbetzen-wk** [comment] 2020-01-09 18:01
I originally reported this issue via email, and the `\040` suggestion by Dan ended up resolving my issue. I also realized afterwards that `\s` works in my case as well, but the original `\ ` error confused me.

In the shorter term, I think even a check for escaped spaces and displaying a hint message would be helpful. Something like "It looks like you're searching for an escaped space character, try using `\040` instead."

This is assuming that implementing a hint message is significantly less work than implementing the separate regex/literal parsers. Either way, it's just an idea. 😄

**Comment by rvantonder** [comment] 2020-01-09 18:06
@noahbetzen-wk very much appreciate the feedback. A hint could be a good stopgap that doesn't affect the parser logic, so 👍for you suggestion. Will see if we can get a quick turnaround on that.

Aside, we need to separate these parsers anyway because it's causing related, but different issues elsewhere :-)

**Comment by slimsag** [comment] 2020-01-24 21:44
Another customer ran into this just now but in a different form: their regexp query `foo bar` effectively turned into `foo.*bar` which was not what they wanted as it turned up many more results than expected.

**Comment by rvantonder** [comment] 2020-01-27 18:28
>  their regexp query foo bar effectively turned into foo.*bar which was not what they wanted as it turned up many more results than expected.

This case is not a bug and intended behavior, implemented precisely [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@abbace9fffa33ed48a1fdbe24b8ffe679df75f04/-/blob/cmd/frontend/graphqlbackend/search_results.go#L1171), documented as potentially problematic in [RFC 75](https://docs.google.com/document/d/1iAWIOalYTZLRWmYw0r6_r_uThutLhanyTrxFSFtQAgE/edit?ts=5e161c26#bookmark=id.1zfv0e6ty3gi). This is WONTFIX until there is a proposal to change this behavior. We absolutely need to update user-facing documentation about this, but apparently this doesn't exist (I can do that).

Purportedly the `/.../` syntax would work as a current workaround, as I picked up in [RFC 75](https://docs.google.com/document/d/1iAWIOalYTZLRWmYw0r6_r_uThutLhanyTrxFSFtQAgE/edit?ts=5e161c26#bookmark=id.v7qi1w47eu4f). This is also not documented as far as I know, so I'm not sure if this is intended to be a known feature or not.

**Comment by tsenart** [comment] 2020-01-28 11:12
Sounds like documentation is the answer for now.

**Comment by tsenart** [comment] 2020-02-03 10:04
@rvantonder: You wrote that this was fixed in the https://github.com/sourcegraph/sourcegraph/issues/7719#issuecomment-581220572. Can it be closed?

**Comment by rvantonder** [comment] 2020-02-03 17:26
Soon--I'd like to refresh our documentation first (for this fix and the other things that cropped up in this thread).

**Comment by rvantonder** [comment] 2020-02-05 04:58
Docs updated to reflect interpretation of regexp re: https://github.com/sourcegraph/sourcegraph/issues/7604#issuecomment-578313967 and alternative syntax to avoid the fuzzy `.*?` matching

**Closed by rvantonder** 2020-02-05 04:58 UTC
Labels: bug, customer, estimate/1d, planned/3.13, search, team/core-services
