### ISSUE TITLE
Add repository getting started item does not register as complete

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#12985] opened 2020-08-13 16:52 UTC
I observed a user adding repositories on recent installation. The corresponding getting started item was not marked as complete. See the following screenshot:

![image](https://user-images.githubusercontent.com/539268/90163065-721c5800-dd4a-11ea-921b-28a2b54d5dd3.png)

**Comment by rrhyne** [comment] 2020-09-03 21:24
Additionally, this panel should link to the add repositories section of settings.

**Comment by felixfbecker** [comment] 2020-09-04 07:02
@eseliger @unknwon likely a regression from the external services refactors?
Would be good to have an integration test for this too

**Comment by felixfbecker** [comment] 2020-09-04 20:06
@eseliger assigned you to look into this, please reassign to the web team if this turns out to not be a regression from those changes.

**Comment by davejrt** [comment] 2020-09-14 19:10
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by unknwon** [comment] 2020-12-01 07:22
Should the @sourcegraph/web or @sourcegraph/cloud own fixing this? It is unclear to me.

**Closed** 2024-02-04 21:04 UTC
Labels: needs-team-triage
