### ISSUE TITLE
search field remains focused when it shouldn't

### ISSUE THREAD

**Issue by jasonhawkharris** [sourcegraph/sourcegraph#58193] opened 2023-11-08 13:35 UTC
Just hit on a keyboard related papercut, reproduce:

- Open https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/agent/src/agent.ts
- Cmd-F and search for graphql, press enter until you hit line 228
- Use the mouse the click on the line number in the gutter in preparation to share a link there
- Press `y` shortcut to canonicalize the URL (point to git hash instead of `main` branch)
- Expected behavior: URL becomes canonical
- Actual behavior: Cmd-F search input is still focused so it appends `y` to the existing `graphql` query

This may seem like a small issue, but papercuts like these add up quickly and they make it painful to use the blob view with the keyboard.

_Originally posted by @olafurpg in https://github.com/sourcegraph/sourcegraph/issues/57813#issuecomment-1780526096_

**Comment by camdencheek** [comment] 2024-01-10 16:44
Seems to work fine now. Closing because we either fixed it or can't reproduce

**Closed by camdencheek** 2024-01-10 16:44 UTC
Labels: code-navigation, code-search, keyboard-navigation
