### ISSUE TITLE
Kubernetes not found on sourcegraph.com

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#3237] opened 2019-04-05 00:15 UTC
From https://twitter.com/ahmetb/status/1113954726020653056

**Comment by nicksnyder** [comment] 2019-04-05 00:17
Related to https://github.com/sourcegraph/sourcegraph/issues/2773 ?

**Comment by KattMingMing** [comment] 2019-04-05 02:54
Also looks related to https://github.com/sourcegraph/sourcegraph/issues/2947

**Comment by keegancsmith** [comment] 2019-04-05 14:01
Duplicate of #2773

**Closed by keegancsmith** 2019-04-05 14:01 UTC
Labels: bug
