### ISSUE TITLE
"Can't perform a React state update on an unmounted component" error on Bitbucket Server PR view

### ISSUE THREAD

**Issue by lguychard** [sourcegraph/sourcegraph#3035] opened 2019-03-29 10:01 UTC
Bitbucket Server version: 15.5.1

- Navigate to a file diff on a Bitbucket Server PR
- Witness errors in console: 
![image](https://user-images.githubusercontent.com/1741180/55224984-e582ff80-5211-11e9-87b0-38da4f607ae9.png)

Code intelligence hovers and code view toolbar buttons seem to be working OK, but there is likely a real problem there.

**Comment by felixfbecker** [comment] 2019-04-01 21:56
I guess this was caused by async MutationObserver events and is now fixed that this code is removed

**Comment by felixfbecker** [comment] 2019-04-03 12:51
It also may be fixed by #3191

**Closed** 2020-03-24 21:10 UTC
Labels: bitbucket, browser-extension, bug, team/web
