### ISSUE TITLE
`src batch` fails on windows

### ISSUE THREAD

**Issue by malomarrec** [sourcegraph/sourcegraph#22402] opened 2021-06-27 09:27 UTC
See [thread](https://sourcegraph.slack.com/archives/CMMTWQQ49/p1624467371288100)

**Comment by LawnGnome** [comment] 2021-07-05 21:29
Fixed by #22374.

**Closed by LawnGnome** 2021-07-05 21:29 UTC
Labels: team/batchers

**Comment by malomarrec** [comment] 2021-07-06 06:28
@LawnGnome there was a [customer](https://docs.google.com/spreadsheets/d/1OEhzdMSlkGOaWyGKwdiAGlirsKKj9EN45Izn7kdKNTg/edit#gid=0&range=A94) that has an issue on windows. I think you were asking about their environment. 
Does this resolve their issue? Should someone investigate some more?

**Comment by LawnGnome** [comment] 2021-07-06 15:21
@malomarrec Yep, the issue I linked above was spawned from the same Slack thread, and the customer has confirmed it resolves their issue. I closed this issue because it's a duplicate.
