### ISSUE TITLE
Updating user settings fails on sourcegraph.com

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/sourcegraph#10235] opened 2020-04-28 18:07 UTC
Updating settings, and any extension with toggles that update settings like the Codecov extension, are broken on dotcom with this error when toggling:

![image](https://user-images.githubusercontent.com/10532611/80521632-a2064200-898b-11ea-8b43-557cdb288cb8.png)

![image](https://user-images.githubusercontent.com/10532611/80580141-5f844a00-8a0b-11ea-8544-406d5dc7acd1.png)

But the GraphQL request is updating user settings, not global settings:

![image](https://user-images.githubusercontent.com/10532611/80521685-b9452f80-898b-11ea-87ed-5eee75b02d1b.png)

![image](https://user-images.githubusercontent.com/10532611/80521729-ccf09600-898b-11ea-8786-b45d537a69d7.png)

I would guess this is a bug in the implementation of the new settings-from-file support?

**Comment by dadlerj** [comment] 2020-04-28 18:35
I ran into this during a demo as well 👍

**Comment by tsenart** [comment] 2020-04-29 10:21
This is probably a regression introduced in https://github.com/sourcegraph/deploy-sourcegraph-dot-com/pull/2428. Assigning to the distribution team.

**Comment by beyang** [comment] 2020-04-29 16:55
This is intended behavior. If you're configuring global settings and config from environment variable, editing it from the GUI should be disabled.

I claim the following:
* sourcegraph.com *should* be configured via env variable vendored somewhere in git. The reason being that we need to don't want to allow modifying the global config via the GUI on sourcegraph.com (too many things could go wrong, affect usage on the site).
* Those wishing to dogfood or demo editing global settings via the GUI should use k8s.sgdev.org or sourcegraph.sgdev.org.

If these claims are accepted, then I would propose as next steps that @davejrt revert his revert and reenable configuration via env vars on sourcegraph.com

**Comment by felixfbecker** [comment] 2020-04-29 17:01
@beyang I agree with you for ***global*** settings. But ***user*** (and org) settings are stored in the DB and need to be updatable by the user and extensions, and updating ***user*** settings fails with an error that ***global*** settings are not allowed to be updated. But there is no attempt to update ***global*** settings. This is a bug that needs to be fixed before reverting the revert.

**Comment by beyang** [comment] 2020-04-29 18:16
Oh I see, this is affecting user and org settings, in addition to global settings. Yes, I agree, we need to fix this bug.

@davejrt could you own fixing this bug? Here are the steps I would take to locate the code that needs to be changed:
1. [Search for the error message](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+Updating+global+settings+not+allowed&patternType=literal)
1. [Show references on the surrounding function](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@ccda05c7b041a166b2d6eb3bc6e998878c164cac/-/blob/cmd/frontend/graphqlbackend/settings.go#L60:6)
1. Make the appropriate changes to permit edits for non-global (i.e., user and org) settings.

**Comment by slimsag** [comment] 2020-04-29 20:59
Agreed, this is not the intended behavior and is my fault. This also means the same extensions have not worked on customer instances for quite a while (several months, at least).

The problematic code is here: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@2a83e183093e3f94b68add774536f7564287beeb/-/blob/cmd/frontend/graphqlbackend/settings.go#L56-63

I think it just needs to have `subject.site != nil` added to the if statement to only apply to "site" (global) configuration

**Closed** 2020-05-08 02:13 UTC
Labels: api, bug, dot-com, p1, team/distribution
