### ISSUE TITLE
GitHub.com rate limit error not displayed anywhere

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#1811] opened 2019-01-11 17:59 UTC
- **Sourcegraph version:** 3.0.0-alpha.9

I added a GH external service without a token, and added an open source repo:

![image](https://user-images.githubusercontent.com/5589410/51051012-6a516c00-1587-11e9-8f6c-b82468d6cbd2.png)

And nothing showed up on the **Repositories** page.

After checking the logs, I saw this error:

>17:54:06       repo-updater | t=2019-01-11T17:54:06+0000 lvl=eror msg="Error getting GitHub repository" nameWithOwner=jepafi/Free-JPDF-Pascal error="request to http://127.0.0.1:3180/repos/jepafi/Free-JPDF-Pascal returned status 403: API rate limit exceeded for 64.79.119.242. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

There was nowhere in the UI that indicated this to me.

My thinking for discussion:
* Short-term fix: note that a token helps prevent these issues
* Long-term fix: display repo-updater errors somewhere (e.g. on the Site-admin > Repositories page). @francisschmaltz can you link the mocks you've created for this (and/or link to the issue)?

**Comment by francisschmaltz** [comment] 2019-01-11 18:06
@nicksnyder @dadlerj The UI for error is in Zeplin here:
https://zpl.io/bz10R98
https://zpl.io/V4QJEd0

@nicksnyder can you add this to 3.1 or 3.2

**Comment by nicksnyder** [comment] 2019-01-11 19:16
Thanks for linking the mocks (is there another open issue related to those mocks that this might be a duplicate of?).

I don't expect this to be in 3.1 and we are not ready to plan for 3.2 (until 3.0 is out). The hard part here is not the UI but figuring out how to make the async errors available in the right way.

**Comment by mrnugget** [comment] 2019-09-16 09:10
I'm closing this, because these errors show up in the UI by now.

**Closed by mrnugget** 2019-09-16 09:10 UTC
Labels: bug, team/core-services
