### ISSUE TITLE
Missing code intel popover buttons for cross-repo references

### ISSUE THREAD

**Issue by varungandhi-src** [sourcegraph/sourcegraph#40658] opened 2022-05-11 03:06 UTC
(Tentatively putting this on lsif-go, not sure if this is an extension issue. The buttons do show up for in-repo references, as well as for cross-repo lsif-typescript references.)

[Sourcegraph URL](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@7501e22e54f45d0a58e631598eebbee19fbe1e0c/-/blob/internal/search/backend/index_options.go?L46:19&subtree=true)

![code intel popover with missing buttons](https://user-images.githubusercontent.com/93103176/167760785-3828242f-4a9c-49d7-b2a3-808a604407de.png)

This should be working, right?

**Comment by olafurpg** [comment] 2022-09-28 08:13
I'm unable to reproduce, although it's now "partially precise" instead of "precise"

![Image](https://user-images.githubusercontent.com/1408093/192725584-bcaec205-582b-42f1-92ce-44cd726ee518.png)

Should we closed this as wontfix?

**Closed** 2022-09-28 09:24 UTC
Labels: bug, team/code-navigation
