### ISSUE TITLE
Experimental paginated search API regression in 3.22

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#17120] opened 2021-01-07 20:42 UTC
It appears that starting in 3.22 the experimental paginated search API has had a major regression which causes it to return only a subset of the expected results, comparing the same request against 3.22 and 3.21. This was reported by a user relying on the experimental API at https://app.hubspot.com/contacts/2762526/company/407948923/ - and I can confirm it is true.

**Workaround:** Use the non-paginated search API, it does not suffer from the same issue.

We introduced the experimental paginated search API [back in v3.9 over a year ago](https://docs.sourcegraph.com/api/graphql/search#sourcegraph-3-9-experimental-paginated-search), and since then have not made any substantial progress on it or taken it out of experimental status. We are currently working on a new search streaming API, which will allow for getting search results in an un-ordered fashion as they come in which fits Sourcegraph's backend model better.

Questions for the @sourcegraph/search team to address:

1. When approximately (very rough estimate okay) will the streaming API be ready for users at https://app.hubspot.com/contacts/2762526/company/407948923/ to make use of in scripts, etc.?
2. Do we want to keep the paginated search API around or remove it? I imagine removing it makes sense given streaming will supersede it, but defer this decision to you. One thing of note is that it could merely be backed by the streaming API if we desired (i.e. nothing in its API design / promises prevents us from keeping it.)
3. If we do remove it, how do we communicate the removal? While we've been clear it is experimental and not for production use since we introduced it, there are likely a handful of users relying on it - I'd suggest we make it loud and clear in our CHANGELOG.

**Comment by keegancsmith** [comment] 2021-01-11 14:34
This month we hope to functionally wrap streaming search. February we are tackling the "exhaustive search" use case.  I assume once exhaustive search the existing users of paginated search will be happy to switch over. I think removing paginated search would then make sense.

From a technical PoV it has slowed down making more sweeping changes to our search codebase due to assumptions paginated search makes on our searchResultsCommon interface. FYI it was the first time I had deeply read the paginated search code, it is really nice :)

There have been some changes to paginated_search.go recently, but none in 3.22. If you can reproduce this in a dev environment, it may make sense for us to timebox a fix for this even though it is experimental.

**Comment by lguychard** [comment] 2021-10-20 11:37
Closing, as the paginated API has been removed.

**Closed by lguychard** 2021-10-20 11:37 UTC
Labels: regression, team/search-core
