### ISSUE TITLE
Cody stops responding when token is deleted/expired

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/sourcegraph#50973] opened 2023-04-21 09:12 UTC
When Cody can't talk to the Sourcegraph backend we currently don't give any indication of that to the user.

To reproduce:

- Setup Cody in VS Code
- Start a conversation
- Delete token on Sourcegraph instance
- Send another message to Cody

What happens: cursor keeps blinking

What I want to see: error/notice that cody doesn't work anymore

(I think that @eseliger has looked into this a bit with rate limiting, but not sure)

**Comment by vdavid** [comment] 2023-04-21 09:36
- I think @eseliger's PR (https://github.com/sourcegraph/sourcegraph/pull/50917) should cover this in [this line](https://github.com/sourcegraph/sourcegraph/pull/50917/files#diff-4cc6bcaa0ad4e8db04c589ac20e2febcea24c87af61887d7dbcce82b131e63b8R83). I think this is the code that runs when there's a timeout.

I think we could still improve the experience by introducing a much shorter timeout for the first byte to arrive (then let the response take long if there's data coming)

**Comment by abeatrix** [comment] 2023-04-21 09:49
The changes I made in https://github.com/sourcegraph/sourcegraph/pull/50748 should also cover this if I understand correctly. When a user update their access token or url that are invalid they will be logged out automatically with error message.

**Comment by mrnugget** [comment] 2023-04-21 12:48
I think they might only cover the case when you _start_ VS Code and the token is invalid. I just replicated the behaviour on `main`:

- Start Cody, set access token, start talking to Cody
- Delete access token on Sourcegraph instance

Cody then gets stuck in the blinking cursor:

<img width="391" alt="screenshot_2023-04-21_14 47 25@2x" src="https://user-images.githubusercontent.com/1185253/233639856-69ca9b64-cb11-4a68-8f41-9163e120f178.png">

And in the background this message is logged:

```
Error retrieving embeddings: Error: accessing Sourcegraph GraphQL API: Error: HTTP status code: 401
    at /Users/thorstenball/work/sourcegraph/client/cody-shared/src/sourcegraph-api/graphql/client.ts:176:29
    at processTicksAndRejections (/Users/thorstenball/work/sourcegraph/lib/internal/process/task_queues.js:96:5)
    at CodebaseContext.getEmbeddingsContextMessages (/Users/thorstenball/work/sourcegraph/client/cody-shared/src/codebase-context/index.ts:53:41)
    at ChatQuestion.getContextMessages (/Users/thorstenball/work/sourcegraph/client/cody-shared/src/chat/recipes/chat-question.ts:37:45)
    at Interaction.hasContext (/Users/thorstenball/work/sourcegraph/client/cody-shared/src/chat/transcript/interaction.ts:43:33)
    at Transcript.getLastInteractionWithContextIndex (/Users/thorstenball/work/sourcegraph/client/cody-shared/src/chat/transcript/index.ts:48:32)
    at Transcript.toPrompt (/Users/thorstenball/work/sourcegraph/client/cody-shared/src/chat/transcript/index.ts:57:49)
    at ChatViewProvider.executeRecipe (/Users/thorstenball/work/sourcegraph/client/cody/src/chat/ChatViewProvider.ts:248:24)
    at ChatViewProvider.onHumanMessageSubmitted (/Users/thorstenball/work/sourcegraph/client/cody/src/chat/ChatViewProvider.ts:216:9)
    at ChatViewProvider.onDidReceiveMessage (/Users/thorstenball/work/sourcegraph/client/cody/src/chat/ChatViewProvider.ts:100:17) {vslsStack: Array(10), stack: 'Error: accessing Sourcegraph GraphQL API: Err…ent/cody/src/chat/ChatViewProvider.ts:100:17)', message: 'accessing Sourcegraph GraphQL API: Error: HTTP status code: 401'}
```

This we should surface to the user.

**Comment by abeatrix** [comment] 2023-04-21 16:27
I just built from main but can't reproduce it. it will log the user out right away when the access token is invalid. Can you try pulling the changes from the latest main and see if the issue persists?
![auth](https://user-images.githubusercontent.com/68532117/233687456-f3f5220f-048d-4cf4-a675-36cf47e6ccba.gif)

**Comment by abeatrix** [comment] 2023-04-21 16:41
Ohhhhh i missed the important part of your message about deleting the token on sourcegraph instance and not on VS Cody!!!! ignore my last message, I can get a pr for that!

**Comment by abeatrix** [comment] 2023-04-25 20:40
Closing with https://github.com/sourcegraph/sourcegraph/pull/51005

![image](https://user-images.githubusercontent.com/68532117/234398316-aff4b5a7-6917-457d-b6d0-de90a4c89600.png)

**Closed by abeatrix** 2023-04-25 20:40 UTC
Labels: needs-design, cody, cody/vscode
