### ISSUE TITLE
Show reference one line below

### ISSUE THREAD

**Issue by JP3BGY** [sourcegraph/sourcegraph#3658] opened 2019-04-29 04:17 UTC
- **Sourcegraph version:** sourcegraph.com
- **Platform information:** latest Firefox and Chrome on Linux(Ubuntu 19.04) and Windows 10

#### Steps to reproduce:

Visit [here](https://sourcegraph.com/github.com/tianocore/edk2@master/-/blob/MdeModulePkg/Core/Dxe/Mem/Pool.c#L394)

#### Expected behavior:

show reference under a cursor

#### Actual behavior:

show reference one line below the line under a cursor
![Screenshot from 2019-04-29 12-40-48](https://user-images.githubusercontent.com/6635381/56876237-fe850780-6a80-11e9-8224-de5e56d7da62.png)

**Comment by chrismwendt** [comment] 2019-05-01 03:44
Sourcegraph has an extra empty line 45:

https://github.com/tianocore/edk2/blob/273190e189755d652de886b653d2c14bfceeb3ed/MdeModulePkg/Core/Dxe/Mem/Pool.c#L44-L46

![image](https://user-images.githubusercontent.com/1387653/57004919-16937e80-6b88-11e9-8942-8f6fed372e04.png)

https://github.com/tianocore/edk2/blob/273190e189755d652de886b653d2c14bfceeb3ed/MdeModulePkg/Core/Dxe/Mem/Pool.c#L44-L45

![image](https://user-images.githubusercontent.com/1387653/57004926-21e6aa00-6b88-11e9-9115-5e21fefbe658.png)

Could this be a syntax highlighting issue?

![image](https://user-images.githubusercontent.com/1387653/57004975-b18c5880-6b88-11e9-9165-42fc70931c12.png)

The blob content looks right:

![image](https://user-images.githubusercontent.com/1387653/57004981-bea94780-6b88-11e9-80d8-43116a49dbb7.png)

The highlighted content looks wrong:

![image](https://user-images.githubusercontent.com/1387653/57004963-9faab580-6b88-11e9-950f-350ee16462e6.png)

**Comment by efritz** [comment] 2020-08-05 20:57
Unable to reproduce this issue, closing for now, please re-open if this is not the case.

**Closed by efritz** 2020-08-05 20:57 UTC
Labels: syntect_server, team/code-intelligence
