### ISSUE TITLE
Sourcegraph for VSCode: Token not valid for authentication

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#50484] opened 2023-04-07 19:04 UTC
- **Sourcegraph version:** Sourcegraph.com 
- **Platform information:** Sourcegraph for VSCode v2.2.15  

It looks like the tokens are not working for authentication. 

<img width="328" alt="Screenshot 2023-04-07 at 11 25 49 AM" src="https://user-images.githubusercontent.com/69164745/230658966-c1c445c0-cb61-488b-92ba-12c35b9e00c0.png">

If you would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are no [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by enriquegh** [comment] 2023-04-07 21:06
Looks like this is being caused by #50051. The PR makes this change to the VS Code plugin but I think it hasn't been released yet.

**Comment by sqs** [comment] 2023-04-10 19:16
Looks like we need to release a new Sourcegraph VS Code (note: not Cody) extension after https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/d0c99a945bd703b314852aa9df1d84f9d78e091d was merged and deployed.

**Comment by philipp-spiess** [comment] 2023-04-11 14:48
Hey folks! I've pushed an update to the VS Code Marketplace and the Open VSX Registry which contains a fix for this issue. Let me know if there are still issues 🙂

**Closed by philipp-spiess** 2023-04-11 14:48 UTC
Labels: bug, vscode-extension, team/code-exploration
