### ISSUE TITLE
insights: dashboard pings backend work

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/sourcegraph#30633] opened 2022-02-03 17:40 UTC
Insights dashboard pings - backend
Related https://github.com/sourcegraph/sourcegraph/issues/29959

**Comment by CristinaBirkel** [comment] 2022-03-03 14:40
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/28374

**Closed by CristinaBirkel** 2022-03-03 14:40 UTC
Labels: analytics, team/code-insights, backend
