### ISSUE TITLE
Render front matter like GitHub does for markdown files

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#231] opened 2018-10-02 21:36 UTC
#### Feature request description

GitHub detects front matter in markdown files and renders it as a table.

#### Is your feature request related to a problem? If so, please describe.

The front matter at the moment looks like a content rendering bug. Rendering it as a table makes it more readable.

#### Describe alternatives you've considered.

I think the rendering of the front matter doesn't have an alternative, but the HTML it is converted to does not have to be a table. A definition list would be better.

#### Additional context

<img width="1680" alt="screen shot 2018-10-03 at 7 15 59 am" src="https://user-images.githubusercontent.com/133014/46378404-d0079f80-c6de-11e8-9e4a-cbaf6b25487e.png">

**Comment by sqs** [comment] 2018-10-02 21:58
Agreed but dupe of #153 😃

**Closed by sqs** 2018-10-02 21:58 UTC
Labels: feature-request
