### ISSUE TITLE
Rlimit error on Ubuntu 18.04.1 

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#2208] opened 2019-02-07 23:31 UTC
On Sourcegraph:Insiders and 3.0.0 I'm hitting this error when deploying:

```
23:27:09           frontend |  !!!!!  Rlimit is required
23:27:09           frontend | 	Problem: Insufficient file descriptor limit
23:27:09           frontend | 	Possible fix: Please increase the open file limit by running "ulimit -n 10000".
23:27:09           frontend | 	Skip this check by setting the env var SRC_SKIP_REQS="Rlimit" (separate
23:27:09           frontend | 		multiple entries with spaces). Note: Sourcegraph may not function
23:27:09           frontend | 		properly without Rlimit.
23:27:09           frontend | t=2019-02-07T23:27:09+0000 lvl=eror msg="System requirement checks failed (see above for more information)." failed=[Rlimit]
23:27:09           frontend |  
```

Digital Ocean droplet
Ubuntu 18.04.1
Docker 18.06.1-ce, build e68fc7a
Sourcegraph Insiders 058b55ec67d3
2vCPUs 4GB Ram 80GB SSD

**Comment by nicksnyder** [comment] 2019-02-08 00:00
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/2034

**Closed by nicksnyder** 2019-02-08 00:00 UTC
