### ISSUE TITLE
Bug: Incorrect interpretation of GH internal repository visibility rules

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/sourcegraph#21591] opened 2021-06-01 16:14 UTC
#### Steps to reproduce:

1. Internal repos are synced to Sourcegraph, with permissions syncing enabled
2. Orgs members cannot search for them on Sourcegraph if they are not direct members of those internal repos

#### Expected behavior:
Internal repos are searchable even if org members do not have direct roles

#### Actual behavior:
Internal repos are not searchable for org members who do not have direct roles to those internal repos

**Comment by kkom** [comment] 2021-06-01 17:38
This is consistently happening to us, which makes me think that it should be easy to track down. 

I haven't looked at Sourcegraph's code, but I believe that right now public repos are special-cased to be visible by everyone, even if turned on permission.

We need the same kind of special casing for repositories that are marked as internal, but only for users whose linked GitHub accounts belong to the org which owns those repositories.

**Comment by dan-mckean** [comment] 2021-10-18 17:28
Thanks @bobheadxi - super useful

**Comment by kkom** [comment] 2022-04-20 13:29
Hey! Wanted to let you know that we found a pretty elegant workaround for this with the help of the Sourcegraph support team. We just need to create a new code host like this:

```
// This is a workaround for https://github.com/sourcegraph/sourcegraph/issues/21591
//
// Sourcegraph does not interpret the visibility of GitHub repos of type "internal" correctly,
// and treats them as if they were private. Hence not all members of the GitHub org see them
// - only the ones that have an explicit role on them.
//
// By creating a new code host that explicitly includes just internal repos and turning off any
// authorization for it, anyone who is a member of the Sourcegraph instance can see them.
//
// (...)

{
  "url": "https://github.com",
  "token": "REDACTED",
  "repositoryQuery": [
    "org:Glovo is:internal"
  ],
}
```

**Comment by indradhanush** [comment] 2022-04-21 13:38
@kkmo This looks like a great find. Let me follow up on this.

**Comment by sourcegraph-bot-2** [comment] 2022-06-13 18:38
Heads up @sourcegraph/iam-and-admin-experience - the "team/iam-admin-experience" label was applied to this issue.

**Comment by sourcegraph-bot-2** [comment] 2022-06-24 10:06
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by kopancek** [comment] 2022-10-28 11:02
We fixed this on github by treating `internal` repositories as private. Maybe we should do the same for github as well: https://github.com/sourcegraph/sourcegraph/pull/42424

**Comment by kopancek** [comment] 2022-12-19 18:08
I dived deep into the code and could not find where this would fail. With GHE 3.3. the query to fetch repositories with `visibility=private` also returns the internal repositories. We treat the internal repositories as private as well.

I tried to reproduce the issue locally with internal repository setup on ghe.sgdev.org, permission syncing on, both with groups cache disabled and enabled and I was able to see the internal repository results just fine in the search.

Closing as I cannot reproduce and cannot think of a scenario when this would fail.

@kkom please feel free to reopen if this is still happening

**Closed by kopancek** 2022-12-19 18:08 UTC
Labels: bug, feature-request, team/repo-management, team/iam
