### ISSUE TITLE
stores/lsifstore: implement sub-repo perms filtering on all queries

### ISSUE THREAD

**Issue by bobheadxi** [sourcegraph/sourcegraph#28244] opened 2021-11-26 23:20 UTC
Implement filtering in the LSIFStore, [across all 28 functions exported by the store](https://sourcegraph.com/search?q=context:%40sourcegraph+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%4041bc6a1+file:%5Eenterprise/internal/codeintel/stores/lsifstore+func+%28s+*Store%29+:%5B%7E%5BA-Z%5D.*%5D&patternType=structural). Initial estimate based on the number of functions exported by the store, allocating ~0.5d to each.

-   This might not be as daunting as it looks, with some functions sharing underlying helper functions ([example](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@41bc6a137fb7565fc491e83d3a854fb49d533df4/-/blob/enterprise/internal/codeintel/stores/lsifstore/locations.go?L31:17#tab=references)) and some possibly not requiring filtering at all.

-   Note: many of these are write functionality, which we should not skip over when enforcing authorization.

**Comment by ryanslade** [comment] 2021-12-03 15:56
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/28271

**Closed by ryanslade** 2021-12-03 15:56 UTC
Labels: estimate/12d, team/repo-management, PD-503
