### ISSUE TITLE
k8s.sgdev.org: "err$0" returns 500

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#4604] opened 2019-06-19 18:36 UTC
- **Sourcegraph version:** k8s.sgdev.org running 3.5.0-rc.1

https://k8s.sgdev.org/search?q=r:sourcegraph/sourcegraph+err%240

![Screen Shot 2019-06-19 at 11 41 34 AM](https://user-images.githubusercontent.com/9022011/59791544-38a3a600-9287-11e9-82d1-c6d9e8e37420.png)

https://app.lightstep.com/sourcegraph-dev/trace?span_guid=60c21d9dc94694d2&at_micros=1560969669966493#span-60c21d9dc94694d2

I realize that `err$0` is an impossible regex to satisfy, but I would expect a more helpful error message than a simple 500. 

cc @sourcegraph/code-search

**Comment by ggilmore** [comment] 2019-06-19 18:40
additionally, it looks like tracing is broken for whatever reason

**Comment by ijt** [comment] 2019-06-20 00:07
I pinged the lightstep people about the tracing.

**Comment by ijt** [comment] 2019-06-20 00:08
This issue can be mitigated with `timeout:1m`:

![Screen Shot 2019-06-19 at 17 08 10](https://user-images.githubusercontent.com/15530/59809309-e24d5c00-92b4-11e9-97eb-1653492ff222.png)

**Comment by slimsag** [comment] 2019-06-20 00:22
I've already contacted Lightstep about this twice before btw. The problem is we are generating so many spans in these search traces due to the number of repositories we're searching over that the trace data gets lost (either on our side or theirs). Not an issue on their end.

**Comment by ijt** [comment] 2019-06-20 00:23
Okay, do you have any idea about how to fix this?

**Comment by slimsag** [comment] 2019-06-20 00:57
The tracing issue -> yes, I intend to send a PR that would help as part of perf work, but probably won't completely solve the issue yet since it's not just search doing this but many other places in our app.

This issue -> the response from the GraphQL search request is:

```
json: error calling MarshalJSON for type json.RawMessage: invalid character '}' looking for beginning of value
```

Given the behavior is also flaky, i.e. this doesn't reproduce reliably for me, I assume we're either flooding a service with requests or a service is restarting due to a panic.

**Comment by slimsag** [comment] 2019-06-20 07:14
Fixed in 3.5.0-rc.3 by the same solution as #4616 -- it now properly shows the error instead of 500ing:

![image](https://user-images.githubusercontent.com/3173176/59828645-50fbdb00-92f0-11e9-8f2a-80244f5552a1.png)

**Closed by slimsag** 2019-06-20 07:14 UTC
Labels: bug, search

**Comment by ijt** [comment] 2019-06-20 16:38
@slimsag, can you link to the PR you used to fix this?

**Comment by attfarhan** [comment] 2019-06-20 17:08
It's this commit @ijt: https://github.com/sourcegraph/sourcegraph/commit/0551b02dd0248dff57c7454af74660ee5015ef2a
