### ISSUE TITLE
Clearer error message for improper JSON escape sequence in `src actions scope-query`

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#10541] opened 2020-05-10 23:48 UTC
Repro:
* Enable Campaigns on your Sourcegraph instance. Add some `github.com/sourcegraph/*` repos to your instance. (You can just do this on k8s.sgdev.org, which already has those repos.)
* Create a `test.action.json` file with these contents:
```
{
  "scopeQuery": "repo:^github\.com/sourcegraph/",
}
```
* Run `src actions scope-query -f test.action.json`
* Observe no results returned, exit code 0.

The issue is that the `\.` is invalid JSON, but no error message or status code indicates it is invalid. Changing it to `\\.` or `.` makes `src actions scope-query -f test.action.json` print the expected repositories.

**Comment by mrnugget** [comment] 2020-05-11 07:49
Is there a way to detect that it's an invalid escape sequence?

If you use `src -v actions scope-query` the scope query will be printed and you can see that it's incorrect. I'm wondering whether we shouldn't make that the default behaviour, even when no `-v` is given?

**Comment by uwedeportivo** [comment] 2020-06-15 19:27
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.17 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by LawnGnome** [comment] 2020-06-24 01:22
Practically speaking, this is fixed by https://github.com/sourcegraph/src-cli/pull/221: the user will now get an error that points at the `repo` clause, and although it's not precise, it's probably good enough for most users to spot the problem or reformulate their query.

The root cause, however, is a bit more interesting, and is [a bug in sourcegraph/jsonx](https://github.com/sourcegraph/jsonx/issues/5). We'll have to decide what to do about that before we can close this out.

**Comment by mrnugget** [comment] 2020-06-24 05:53
> The root cause, however, is a bit more interesting, and is [a bug in sourcegraph/jsonx](https://github.com/sourcegraph/jsonx/issues/5). We'll have to decide what to do about that before we can close this out.

It doesn't sound like that would be a ton of work, so I'm inclined to say: let's fix it. But I'm wondering whether that doesn't break behaviour we rely on.

@attfarhan @lguychard do you know whether search/web relies on the fact that `jsonx` (our comment-aware JSON parser in Go) doesn't report an escaped dot (`\.`) as an error?

**Comment by LawnGnome** [comment] 2020-06-24 23:23
> @attfarhan @lguychard do you know whether search/web relies on the fact that `jsonx` (our comment-aware JSON parser in Go) doesn't report an escaped dot (`\.`) as an error?

I can't really imagine that it does, since we're silently mutating the search string by removing the `\.`, but it would definitely be good to get confirmation of that.

**Comment by lguychard** [comment] 2020-06-25 07:44
I don't know of any behaviour in search/web that would rely on this.

**Closed** 2020-06-30 06:17 UTC
Labels: bug, campaigns, estimate/0.5d, planned/3.17, src-cli, team/campaigns
