### ISSUE TITLE
Search alerts returned from the backend should use Markdown

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#16677] opened 2020-12-11 19:01 UTC
See this example search alerts returned from the server: 

![image](https://user-images.githubusercontent.com/206864/101813424-90fce200-3ad1-11eb-8438-edbbe48431b7.png)

From https://github.com/sourcegraph/sourcegraph/pull/16624#issuecomment-743074770:
> What do you think about rendering the alert as markdown? Currently the link is not a real link, and the filters would look better as code I think than with double quotes

**Comment by lguychard** [comment] 2021-05-18 13:41
Duplicate of #16576

**Closed by lguychard** 2021-05-18 13:41 UTC
Labels: team/search
