### ISSUE TITLE
Search results appear to not be up to date on umami.sgdev.org

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#4212] opened 2019-05-24 23:29 UTC
It appears to me that repo-updater is not updating https://umami.sgdev.org/github.com/chrismwendt/ctags-test as quickly as I would expect, given the update strategy in the source code:

https://github.com/sourcegraph/sourcegraph/blob/c1b3741dfdc035ba9007cf7c3caddd5ef7502717/cmd/repo-updater/repos/scheduler.go#L90-L93

- I made a commit `.` 25 minutes ago
- I visited the repository and saw the change
- I made another commit `.`
- I ran a search and did not see the change
- I waited 25 minutes and I still don't see the change

Here is the git log:

![image](https://user-images.githubusercontent.com/1387653/58360775-63910a80-7e3f-11e9-8ce8-d0fd87915fb9.png)

Here is the search result https://umami.sgdev.org/search?q=r:ctags-test+2019 (see only 1 date line matched):

![image](https://user-images.githubusercontent.com/1387653/58360914-224d2a80-7e40-11e9-8afb-290ad5528f5c.png)

The latest commit has 2 date lines:

![image](https://user-images.githubusercontent.com/1387653/58360933-3bee7200-7e40-11e9-85d2-8a0b126587db.png)

I'm unable to determine whether or not the repository contents are up to date because I don't have SSH access to that instance.

cc @sourcegraph/core-services @sourcegraph/code-search (I'm not sure which ownership area is more relevant)

**Comment by keegancsmith** [comment] 2019-05-28 07:07
I will need to double check, but I believe the customer this is simulating might have the update scheduler disabled. I'm unsure if we have setup webhooks to do the updates, but I would be surprised if we have. cc @beyang 

> I'm unable to determine whether or not the repository contents are up to date because I don't have SSH access to that instance.

Could you not just visit the repository on Sourcegraph and see what the latest commit is? Our update strategy also takes into account a user visiting a repo page, which would force an update. But if you had visited directly it would of confirmed if the issue was search index lag or gitserver update lag.

Either way this requires further investigation and is a good issue for @sourcegraph/core-services to investigate in 3.5 since this simulates a large customer.

**Comment by slimsag** [comment] 2019-05-28 08:53
> I will need to double check, but I believe the customer this is simulating might have the update scheduler disabled.

This is correct.

> I'm unsure if we have setup webhooks to do the updates, but I would be surprised if we have. cc @beyang

Am also unsure, I suspect not.

**Comment by keegancsmith** [comment] 2019-05-28 09:09
Given the above, I would suspect we need to close this issue out as working as expected. Alternatively, @sourcegraph/distribution needs to setup some sort of webhook system to simulate this customer accuretely.

**Comment by beyang** [comment] 2019-05-31 03:29
I will look into this as part of upgrading the customer, and if there is a general issue to file, I'll update the repro steps above and reassign to core-services if appropriate.

**Closed** 2019-11-25 16:47 UTC
Labels: gitserver, search, team/core-services
