### ISSUE TITLE
TypeScript hovers come from previous file after navigating to a different file

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5233] opened 2019-08-16 00:28 UTC
- Visit https://k8s.sgdev.org/github.com/sourcegraph/codeintellify@e97f3a439af148b271af1981114f956f44b07eaf/-/blob/src/hoverifier.test.ts#L30
- Make sure you're using the TypeScript language server
- Hover over `createCodeViews` and click j2d
- Hovers now appear on the wrong tokens

![2019-08-15 18 25 51](https://user-images.githubusercontent.com/1387653/63135223-2ba2ea80-bf8a-11e9-8b77-67f715b497be.gif)

@felixfbecker Because this appears to be related to the language server, do you want to look into this?

**Comment by felixfbecker** [comment] 2019-08-21 20:42
I saw this too, without doing a j2d. Seems like a bad bug to me

**Comment by felixfbecker** [comment] 2019-08-21 20:43
![2019-08-21 22 42 55](https://user-images.githubusercontent.com/10532611/63467145-108e1a00-c465-11e9-905e-8e205e4444e9.gif)

**Comment by lguychard** [comment] 2019-08-22 10:32
This can also happen when navigating between files using the sidebar. The hovered content / hovered token provided are for the *previously viewed file* at line/pos:
- Navigate to https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph/-/blob/shared/src/api/client/services/decoration.ts#L21:5, witness hover content on `ProvideTextDocumentDecorationSignature` is correct
- Navigate to `editorService.ts` using the side bar
- Hover the comment at line 21
- Witness the hover content provided is for `ProvideTextDocumentDecorationSignature`:
![image](https://user-images.githubusercontent.com/1741180/63507820-e70ed600-c4d8-11e9-95d8-74266ef39737.png)

**Comment by felixfbecker** [comment] 2019-08-22 10:41
This sounds like when a new file is selected, the extension API is not notified of the new file by the web app

**Comment by lguychard** [comment] 2019-09-17 11:11
Likely due to #5583, confirmed as fixed in `3.8.0-rc.2`.

**Closed by lguychard** 2019-09-17 11:11 UTC
Labels: bug, code-intel
