### ISSUE TITLE
Case sensitivity with file extensions affects syntax highlighting

### ISSUE THREAD

**Issue by Bobloblaw74329479279** [sourcegraph/sourcegraph#11327] opened 2020-06-06 05:34 UTC
- **Sourcegraph version:** 3.16.1
- **Platform information:** Ubuntu 20.04

#### Steps to reproduce:

1. Add a repo that has .CPP or .H files
2. Browse to the file.

#### Expected behavior:

The source file should be colorful and have syntax highlighting.

#### Actual behavior:

The entire source file is all gray. Sourcegraph needs to do a case insensitive check on the extension to determine the correct language for syntax highlighting.

**Comment by eseliger** [comment] 2020-11-18 04:15
Thanks for reporting! Please see https://github.com/sourcegraph/sourcegraph/issues/13007 for progress on this :)

**Comment by slimsag** [comment] 2020-11-23 23:05
Closing as duplicate of #13007 - will look into this soon.

**Closed by slimsag** 2020-11-23 23:05 UTC

**Comment by slimsag** [comment] 2020-11-26 00:39
@Bobloblaw74329479279 Just wanted to let you know, this has been fixed in the latest `insiders` build, on Sourcegraph.com, and will be in our next release Sourcegraph v3.23 on Dec 20th.
