### ISSUE TITLE
Global search on Sourcegraph.com should indicate that repo: filter is needed

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#3966] opened 2019-05-13 02:22 UTC
Global search isn't supported on Sourcegraph.com. If the user specifies a query that exceeds the maximum number of allowed repositories to search over (implemented in the code link below), they should see a helpful message instead of just a "context deadline exceeded" error.

Repro:

1. Go to https://sourcegraph.com/search?q=foo+bar

Actual: 
![image](https://user-images.githubusercontent.com/1976/57592358-234e9580-74eb-11e9-8dfe-4d40896407c6.png)

Expected: The "Too many matching repositories" alert at https://sourcegraph.com/github.com/sourcegraph/sourcegraph@6f954bbc1cfc4a54d715f42325cb2ea4037e93ec/-/blob/cmd/frontend/graphqlbackend/search_alert.go#L222:11

(From https://twitter.com/sqs/status/1127746584811192320)

**Comment by ijt** [comment] 2019-05-14 00:01
@nicksnyder [changed the default searchable number of repos to be unlimited](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/commit/f01bff3f10aad25b4b4064df078501e897879315), and sourcegraph.com appears to be using the default.

Instead of an error, I think we could show some repo results that could then be used to refine the query. Watch count could be a useful indicator of relevance. Here's a bigquery showing what that looks like for "vim":

![Screen Shot 2019-05-13 at 16 59 08](https://user-images.githubusercontent.com/15530/57661602-76ceeb00-75a0-11e9-96c9-3909f8a2fafb.png)

**Comment by ijt** [comment] 2019-05-14 00:26
To be clear, I'm not necessarily saying we should use bigquery for this. It just happens to have a dataset that helps to see what would happen with a simple approach like this.

One possibility that could work not just on github would be to periodically query the `recent_searches` table to find out how frequently each repo shows up in sourcegraph.com queries.

**Comment by ijt** [comment] 2019-05-14 00:56
To give a rough idea of what that could look like, here's some data from the `recent_searches` table:

```
sg=# create temp table rs as select substring(query from 'repo:([^ @]+)') as repo, count(*) from recent_searches where query like '%repo:%' group by repo order by count desc;    
SELECT 5211

sg=# select * from rs limit 20;
                                     repo                                      | count 
-------------------------------------------------------------------------------+-------
 ^github.com/tensorflow/tensorflow$                                            |  1381
 ^github.com/fastai/fastai$                                                    |  1334
 ^github.com/openai/baselines$                                                 |   618
 ^github.com/kaldi-asr/kaldi$                                                  |   528
 ^github.com/apache/spark$                                                     |   492
 ^github.com/sourcegraph/sourcegraph$                                          |   480
 ^github.com/numpy/numpy$                                                      |   465
 ^github.com/docker/compose$                                                   |   436
 ^github.com/pytorch/pytorch$                                                  |   435
 ^github.com/rlworkgroup/garage$                                               |   432
 ^github.com/huggingface/pytorch-pretrained-BERT$                              |   408
 ^github.com/akanimax/Variational_Discriminator_Bottleneck$                    |   395
 ^github.com/envoyproxy/envoy$                                                 |   358
 ^github.com/nearprotocol/nearcore$                                            |   355
 ^github.com/pytorch/vision$                                                   |   349
 ^github.com/ray-project/ray$                                                  |   342
 ^github.com/paritytech/parity-wasm$                                           |   334
 ^github.com/LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose$ |   296
 ^github.com/dmlc/tvm$                                                         |   283
 ^github.com/travislee8964/ocserv-auto$                                        |   273
(20 rows)

sg=# select * from rs where repo ~ 'vim[^/]*$' limit 20;
                    repo                     | count 
---------------------------------------------+-------
 ^github.com/autozimu/LanguageClient-neovim$ |    76
 ^github.com/amix/vimrc$                     |    19
 ^github\.com/neovim/neovim$                 |    18
 ^github.com/neovim/neovim$                  |    11
 ^github.com/daa84/neovim-lib$               |     6
 ^github.com/vim/vim$                        |     5
 ^github.com/crazyclerk/vimrc$               |     4
 ^github.com/sakhnik/nvim-gdb$               |     2
 ^github\.com/airblade/vim-gitgutter$        |     2
 ^github.com/JetBrains/ideavim$              |     2
 ^github.com/hmybmny/vim.cpp$                |     1
(11 rows)

where the 'vim[^/]*$' regex matches the last component of the repo path. The answer looks fairly reasonable as a result set for the query "vim".

**Comment by ijt** [comment] 2019-05-14 01:15
Of course we'd have to join `rs` against the `repo` table since the `repo` column in `rs` is actually a regex, not an actual repo name.

**Comment by ijt** [comment] 2019-05-21 23:02
Streaming (#3991) should make it unnecessary to require a repo: filter on sourcegraph.com since some results would show up pretty quickly in many cases and all of them would eventually show up at least for the repos that are currently cloned.

**Comment by slimsag** [comment] 2019-05-21 23:59
I have set `"maxReposToSearch": 50` back in the Sourcegraph.com site configuration. I have NO idea how this got removed or if it was just never added, but this was a huge gaping performance issue on our site and caused everything to slow down significantly just now.

This is fixed now, so closing.

**Comment by felixfbecker** [comment] 2019-05-22 00:04
@slimsag Imo this issue is not resolved. A private instance can still configure a higher number and run into the "Context deadline exceeded" error instead of the expected alert.

**Comment by slimsag** [comment] 2019-05-22 00:08
@felixfbecker point taken, `Context deadline exceeded` is not a helpful message and we should fix that.

However, the correct behavior in this case would be telling the user that they need to increase the `timeout` parameter. If I say I want my instance to be able to search over 1000 repositories and that's too slow, I don't expect it to tell me to specify a `repo:` filter.

**Comment by ijt** [comment] 2019-05-22 01:18
I would rather go with the cursor based solution we've been chatting about.
Then we won't have to rely so heavily on these less reliable timeouts and
max repo settings.

**Comment by ijt** [comment] 2019-06-14 23:08
Someone took care of this. Closing it.

![Uploading Screen Shot 2019-06-14 at 16.07.37.png…]()

**Closed by ijt** 2019-06-14 23:08 UTC
Labels: bug, search

**Comment by ijt** [comment] 2019-06-14 23:43
@felixfbecker, there should be a separate issue about the point you raised if we're able to reproduce it.
