### ISSUE TITLE
Go-to-definition does not select new file in tree

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#4710] opened 2019-07-01 01:13 UTC
Repro:

1. Go to https://sourcegraph.com/github.com/eslint/eslint/-/blob/lib/api.js#L9:29
2. Hover over the `"./linter"` in `require("./linter")` and `Go to definition` (the URL is https://sourcegraph.com/github.com/eslint/eslint/-/blob/lib/linter/index.js#L1:1)

### Actual

You're taken to the correct file, but the file tree sidebar still shows the previous file you were looking at (`lib/api.js`):

![image](https://user-images.githubusercontent.com/1976/60405051-ba86af80-9b62-11e9-8a8a-b00908f03cba.png)

### Expected

The file tree should open to and select `lib/linter/index.js`.

**Comment by attfarhan** [comment] 2020-03-23 04:27
From #9155: 

1. Go to https://k8s.sgdev.org/github.com/sourcegraph/sourcegraph@8ac72992739396ff92403bea2458d2c84a468ce3/-/blob/internal/search/parser.go#L409:6&tab=references
2. Current file is `parser.go` and selected on the left in the `Files` tab is `parser.go`:
<img width="917" alt="Screen Shot 2020-03-19 at 13 26 47" src="https://user-images.githubusercontent.com/1185253/77067479-4c7e6300-69e5-11ea-805a-ed26b72b27af.png">
3. Click on the second reference shown, line 101 in `internal/search/query/searchquery.go`
4. I'm now in `internal/search/query/searchquery.go` but in the `Files` tab `parser.go` is still selected:
<img width="1022" alt="Screen Shot 2020-03-19 at 13 28 53" src="https://user-images.githubusercontent.com/1185253/77067685-ada63680-69e5-11ea-9d6f-d352357e5919.png">
5. Expand the `query` folder in the `Files` tab. Now `searchquery.go` is correctly selected.

I would expect that in step 4 `searchquery.go` is selected.

**Comment by felixfbecker** [comment] 2020-03-31 15:47
I think this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/3439

**Comment by uwedeportivo** [comment] 2020-04-14 16:34
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Closed** 2020-04-15 05:12 UTC
Labels: bug, estimate/1.5d, team/web, webapp
