### ISSUE TITLE
[Bug] Initial password reset failed for new customer instance

### ISSUE THREAD

**Issue by sanderginn** [sourcegraph/sourcegraph#35420] opened 2022-05-13 12:35 UTC
The user was presented with a 'challenge' (unfortunately we don't have additional context on what this could be, perhaps a Cloudflare challenge) while resetting his password after initial account creation for a new managed instance. The reset did not come through properly. After validating on my end that I could successfully reset and login, tried again with a second link, this time with admin rights promoted. Still no luck. After deleting the user, recreating, promoting to admin and then sending over the link, the user could successfully login.

[Relevant Slack thread](https://sourcegraph.slack.com/archives/C02Q9G9A59S/p1652287006028409)

Since this is a pretty vague issue and the first report we've received of this behavior, I don't know if there's much to resolve right now, but if it happens again we'll update on this issue.

#### Steps to reproduce:
Unfortunately, I could not reproduce the issue on a fresh instance. The flow of events that occurred:

1. Created user
1. Generated link without admin rights
1. Failed
1. Added admin rights and regenerated link
1. Failed
1. Recreated user, promoted to admin, generated link
1. Success

**Comment by RafLeszczynski** [comment] 2022-05-23 11:06
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35420?planning-poker) with ZenHub @kopancek @pjlast @unknwon @miveronese

**Comment by RafLeszczynski** [comment] 2022-05-25 09:50
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/IAM-and-Admin-Experience-627aebcc9f8b7c00128a8ab6/issues/sourcegraph/sourcegraph/35420?planning-poker) with ZenHub @pietrorosa77

**Comment by pietrorosa77** [comment] 2022-05-25 11:26
difficult to add points here because we don't have a consistent repro. Should we add a ? to the poker votes?

**Comment by RafLeszczynski** [comment] 2022-05-30 15:51
@pietrorosa77 @unknwon  could we timebox the debugging time?

**Comment by unknwon** [comment] 2022-05-30 23:41
Updated my estimation for timebox.

**Comment by miveronese** [comment] 2022-06-13 13:14
Just to let you know that I also tested this bug report with a new fresh instance but couldn't reproduce it. 

Steps tested:
- Creates first/initial user  - Success 
- Resets password for the initial user - Success
- Admin user logs in and creates 2nd user without admin rights - Success
- 2nd user logs in - Success 
- Admin adds admin rights to 2nd user and regenerates link - Success
- 2nd user resets password  and logs in- Success
- Admin created 3rd user without admin rights - Success
- Admin promotes  3rd user to admin  (before the 3rd user logs in for the first time) - Success
- Admin resets 3rd user password - Success
- 3rd user logs in - Success

**Comment by unknwon** [comment] 2022-06-14 08:08
@miveronese thank you very much for the investigation. I think this issue can be closed until further information allows us to reliable reproduce it. If you agree, please go ahead and close it.

**Comment by sourcegraph-bot-2** [comment] 2022-06-24 09:59
Heads up @sourcegraph/iam - the "team/iam" label was applied to this issue.

**Comment by unknwon** [comment] 2022-08-03 05:47
Based on the silence, close until further information is provided.

**Closed by unknwon** 2022-08-03 05:47 UTC
Labels: bug, team/iam
