### ISSUE TITLE
Removing token in external service does not remove associated repositories

### ISSUE THREAD

**Issue by attfarhan** [sourcegraph/sourcegraph#1845] opened 2019-01-13 08:40 UTC
- **Sourcegraph version:** Insiders

#### Steps to reproduce:

1. Add an external service, include a GitHub token
2. Go to the repositories page, see the list of repos associated with the token.
3. Enable a private repo (e.g. sourcegraph/infrastructure)
4. Edit the external service you added, and remove the token field.
5. Go back to the repositories page and notice all the repositories are still listed there.
6. Go to the private repo you enabled previously and notice that you can still access it.

#### Expected behavior:

I would expect not to be able to access a private repo associated with the token that was removed, and also not see all the repositories listed in the repositories page that were associated with the old token. 

#### Actual behavior:

Can access any enabled repos associated with the old token, and can see all repos associated with the old token in the repositories list.

**Comment by nicksnyder** [comment] 2019-01-13 15:05
Yeah, this is a bigger issue that @tsenart is working on in https://github.com/sourcegraph/sourcegraph/issues/914, and in fact external services was a pre-req to solving exactly the issue you are describing (this isn’t a regression, it never worked this way).

Closing this as a duplicate of https://github.com/sourcegraph/sourcegraph/issues/914

**Closed by nicksnyder** 2019-01-13 15:05 UTC
Labels: bug
