### ISSUE TITLE
campaigns: notify Slack on issues with "campaigns"

### ISSUE THREAD

**Issue by LawnGnome** [sourcegraph/sourcegraph#15929] opened 2020-11-18 17:33 UTC

**Comment by eseliger** [comment] 2020-11-21 13:56
We probably talked about it already and I just forgot but what was this about again?

**Comment by chrispine** [comment] 2020-12-11 20:15
Closing as duplicate of https://github.com/sourcegraph/sourcegraph/issues/16672

**Closed** 2020-12-11 20:15 UTC
Labels: planned/CampaignsSprint5, team/campaigns
