### ISSUE TITLE
JetBrains: 3.1.0 not recognizing embeddings for enterprise user

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#56852] opened 2023-09-20 17:56 UTC
Customer who upgraded to 3.1.0 reports a few glitches: 
- Had to restart the IDE about 3-4 times for it to update and re-enable Cody
- It looks like the remote git URL replacement setting still isn't working--it can't find the embeddings. 
- Also noticed that scrolling is still disabled in the Cody window. (I think this is addressed by [issue](https://github.com/sourcegraph/sourcegraph/issues/56494)) 

Screenshots in [Slack](https://sourcegraph.slack.com/archives/C059N5FRYG3/p1695233068196769?thread_ts=1695233011.259119&cid=C059N5FRYG3).

**Comment by olafurpg** [comment] 2023-09-21 07:38
The "Remote URL replacements" setting is for Code Search and it's not used by Cody. To customize the codebase for embeddings, click on the repository in the Cody sidebar like this

![CleanShot 2023-09-21 at 09 37 11@2x](https://github.com/sourcegraph/sourcegraph/assets/1408093/cf692a6e-8fad-4896-a337-0829d7d4e340)

Closing with working as intended.

> Also noticed that scrolling is still disabled in the Cody window. (I think this is addressed by https://github.com/sourcegraph/sourcegraph/issues/56494)

Feel free to open a separate issue with more details.

**Closed by olafurpg** 2023-09-21 07:38 UTC

**Comment by huyz** [comment] 2023-09-30 18:02
I really wish `Code Search` were renamed to something clearer.  It's too much like `Cody` and it's right below `Cody` in the settings. How about `Sourcegraph Code Search`
