### ISSUE TITLE
A repository being removed from Sourcegraph breaks campaigns

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#9641] opened 2020-04-07 23:24 UTC
See https://sourcegraph.slack.com/archives/CMMTWQQ49/p1586299892072400

**Comment by slimsag** [comment] 2020-04-07 23:29
Some thoughts:

1. It is really surprising to me we didn't consider this case before to be honest. This seems like.a major oversight -- are there other "edge cases" like this we haven't thought of, or was this being tracked somewhere and just wasn't followed up on?

2. I would find it very surprising that changsets get deleted when repositories get deleted. Additionally, it would be horrible if by making a mistake with my repository synching in Sourcegraph that I could lose all of my campaigns. Being a system of record means we have to be cautious about not losing data in situations like this -- so IMO that is not an option here.

3. "One bad apple ruining the bunch" -> This is not really a limitation of GraphQL, this is a limitation of how we chose to use a node resolver in this situation. For example, one bad repo does not ruin an entire search and this is by design because we made it possible to express the fact that a search is missing repositories. It would be trivial to add a changeset resolver field here that indicates an error fetching the repository or that the repository is missing: https://sourcegraph.com/github.com/sourcegraph/sourcegraph@730f31fb13b8380ed02fd01fe4a8583e43b029d4/-/blob/enterprise/internal/campaigns/resolvers/changesets.go#L51-55 (of course that would need to be handled appropriately on the frontend client as well, so there is an argument for not doing this to reduce API surface area but it's not really a limitation of GraphQL)

**Comment by eseliger** [comment] 2020-04-08 01:09
I looked into it and it seems I was on the wrong path here, sorry for the confusion. We indeed do have a foreign key in place, I didn't see that in the `schema.md` when looking for it. 

Still, the current behavior would be to delete changesets when the repo is **hard** deleted. We can certainly revisit that decision and decouple that (to your 2. point), but not sure when that would happen (do we ever delete repos entirely from the db?)

So for this case, this seems to be a different issue. I took a peak into it and my guess now is that the repo from the reported error was deleted, the query checks for `deleted_at IS NULL`. When I soft delete some repo in my DB, I can reproduce that error message.

**Comment by eseliger** [comment] 2020-04-08 15:16
It pretty sure was a soft-deleted repo. I've updated the logic to exclude those changesets as we don't have access to all data we need to compute many properties when we don't have the repo at hand anymore. They will reappear once the repo is re-cloned.

To your first point, I cannot tell much about it as I'm usually not on that team but am jumping in for _mrnugget_ here. I'll mention it at the next sync and write a follow-up here.

**Comment by mrnugget** [comment] 2020-04-13 08:18
Post-merge (#9645) feedback and thoughts:

* I think the behaviour this is fixing might be a regression. See https://github.com/sourcegraph/sourcegraph/issues/6727 for a discussion on what should happen to Changesets when a repository is removed from Sourcegraph. Short version: it should be deleted. I implemented that here: https://github.com/sourcegraph/sourcegraph/commit/6f60e645b04ce5b5ce215f12a874ee117a552291 Or at least I tried to?
* The regression, I think, was introduced with the soft-deletion of repositories.
* With soft-deletion of repos, the deleting changesets is not as easy as hiding them.
* My first thought was that I don't like the `JOIN`s strewn about the codebase. It's easy to miss and can lead to wrong data. Second thought is: using JOINs has the nice property of the changesets showing up again after recloning.
* Is this now a good time to implement the "enhanced" deletion handling, as proposed in https://github.com/sourcegraph/sourcegraph/issues/6727?

> 
>  * As a future enhancement (not required immediately, we'll solicit customer feedback for priority), instead of removing the changesets from the campaign, they can be shown in a special "associated repository no longer exists" state in the campaign, so that the campaign author has confidence that the campaign is indeed affecting all of the repositories they originally intended to affect.
>  * Enhancement: Site admins should be warned when a configuration change will remove repositories that are part of a campaign.
>

**Comment by uwedeportivo** [comment] 2020-04-14 16:33
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.15 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by eseliger** [comment] 2020-04-14 16:36
As the originally reported bug seems done, and we got the post-merge review from @mrnugget, I am going to close this

**Comment by sqs** [comment] 2020-05-27 02:15
A user at https://app.hubspot.com/contacts/2762526/company/557475882 reported this same error at https://workiva.slack.com/archives/CTJUDV6JH/p1590525093016600. They are on version 3.15.1, which definitely contains the #9656 fix. @eseliger Do you have any ideas?

**Comment by eseliger** [comment] 2020-05-27 12:31
Found it, the same logic needs to apply to patches, we only found that issue for changesets. Fix upcoming soon.

**Closed** 2020-05-27 13:46 UTC
Labels: bug, campaigns, team/campaigns
