### ISSUE TITLE
Syntax highlighting on hovers failing for .cc files

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#9918] opened 2020-04-16 16:38 UTC
Reported by https://app.hubspot.com/contacts/2762526/company/2931649618

JS console error reported on syntax highlighting in hover tooltips.

See https://sourcegraph.slack.com/archives/CMT39K56Z/p1587053751152800 for details

**Comment by felixfbecker** [comment] 2020-04-17 07:40
I cannot reproduce this on https://sourcegraph.com/github.com/aferr/secverilog@5373abf58ebe895125c1f9d9c92cf3461abc907a/-/blob/verilog-0.9.6/parse_misc.cc#L49:7

**Comment by felixfbecker** [comment] 2020-04-17 07:51
The only way I could see this happening is if the hover markdown content had a code block literally including the dot as a language. But I have no clue how that could happen tbh... @sourcegraph/code-intel any ideas?

**Comment by pdubroy** [comment] 2021-06-25 14:03
Closing this — last update was over a year ago, so I'm assuming it's obsolete. Please feel free to re-open if I'm wrong.

**Closed by pdubroy** 2021-06-25 14:03 UTC
Labels: bug, team/frontend-platform, webapp
