### ISSUE TITLE
Diff rendering fails on root commits

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#24590] opened 2021-09-03 13:02 UTC
On root commits, an error is returned for highlighting the commit diff. https://sourcegraph.com/maven/org.springframework/spring-messaging/-/commit/09cafad43c52f42271965a8326076334054d1b95

```
Git command [git merge-base -- 4b825dc642cb6eb9a060e54bf8d69288fbee4904 09cafad43c52f42271965a8326076334054d1b95] failed (output: "error: object 4b825dc642cb6eb9a060e54bf8d69288fbee4904 is a tree, not a commit fatal: Not a valid commit name 4b825dc642cb6eb9a060e54bf8d69288fbee4904"): exit status 128
```

**Comment by camdencheek** [comment] 2021-09-03 15:17
Duplicate of #20464 and #21650

**Comment by camdencheek** [comment] 2021-09-03 15:18
Will try to get prioritized this next sprint

**Closed by camdencheek** 2021-09-03 15:17 UTC
Labels: bug
