### ISSUE TITLE
search: just repo search fails to find sourcegraph repo

### ISSUE THREAD

**Issue by keegancsmith** [sourcegraph/sourcegraph#9146] opened 2020-03-19 07:14 UTC
[`r:github.com/.*/sourcegraph$`](https://sourcegraph.com/search?q=r:github.com/.*/sourcegraph%24&patternType=regexp) does not find any repos. But [`r:github.com/sourcegraph/sourcegraph$`](https://sourcegraph.com/search?q=r:github.com/sourcegraph/sourcegraph%24&patternType=regexp) does. This is a regression. Tracing seems to not be enabled for sourcegraph.com, so hard to debug further.

**Comment by unknwon** [comment] 2020-03-19 07:42
I can reproduce this on a random repo I had on my dev instance.

**Comment by keegancsmith** [comment] 2020-03-19 07:47
I got some traces, this is likely not a new regression. The conversion to sql seems to be broken, this is the query we generate:

```sql
SELECT id,name,private,external_id,external_service_type,external_service_id
FROM repo
WHERE deleted_at IS NULL
AND deleted_at IS NULL AND name IN ($1) AND NOT fork AND NOT archived ORDER BY id ASC LIMIT $2 OFFSET $3
```

```
args=[github.com//sourcegraph 10001 0]
```

**Comment by keegancsmith** [comment] 2020-03-19 08:25
@unknwon Pushed a failing test case to `core/repo-search`

**Comment by unknwon** [comment] 2020-03-19 09:17
Update: This was a regressions since the fix of https://github.com/sourcegraph/sourcegraph/issues/4166. Which replaced all `.*` with empty string. But by fixing this one, it also breaks #4166. Looking for a fix works with both.

**Comment by keegancsmith** [comment] 2020-03-19 09:34
Thank you for tracking down. Given the age of the issue, this is not a release blocker.

**Comment by unknwon** [comment] 2020-03-19 10:22
Hack to make it work: https://github.com/sourcegraph/sourcegraph/pull/9152, someone else with more proficient regexp skills please take over :)

**Comment by unknwon** [comment] 2020-03-23 08:07
Patch is merged, closing.

**Closed by unknwon** 2020-03-23 08:07 UTC
Labels: bug, search, team/core-services
