### ISSUE TITLE
Test Plan Datadog extension

### ISSUE THREAD

**Issue by vanesa** [sourcegraph/sourcegraph#1732] opened 2019-01-09 05:19 UTC
Test Plan for Datadog Extension

- Sign into Datadog with this account: https://my.1password.com/vaults/dnrhbauihkhjs5ag6vszsme45a/allitems/z5x35v3vrjcrfkr63b6ls6zk44
- Go to https://sourcegraph.com/extensions and activate the Datadog extension
- Go to: https://sourcegraph.com/github.com/bbc/cops-dd-backup-lambda/-/blob/libs/datadog/dogstatsd/base.py#L150:42 or https://sourcegraph.com/github.com/cloudinsight/cloudinsight-python-sdk/-/blob/cloudinsight/onestatsd/base.py or https://sourcegraph.com/github.com/luckyjd/lms_edx/-/blob/edx-ficus.3-3/apps/xqueue/venvs/xqueue/lib/python2.7/site-packages/statsd.py
- Verify that the Datadog links only appear next to Datadog metrics.
-  Click on the Datadog links for the metrics: `active.connections`, `page.views`, `files.transferred` or `files.remaining`.
- Clicking on the Datadog extension link should take you to the graph view of the metric on the Datadog page.
- Find any other public code that contains metrics for `active.connections`, `page.views`, `files.transferred` or `files.remaining`. The links should lead you to the same graphs.
- Verify that the Datadog links are also rendering through the browser extension on GitHub, for example by visiting: https://github.com/luckyjd/lms_edx/blob/17b5ba6e21585c40fd87069649df95aa2ddf0015/edx-ficus.3-3/apps/xqueue/venvs/xqueue/lib/python2.7/site-packages/statsd.py or https://github.com/cloudinsight/cloudinsight-python-sdk/blob/21c8fdf3956e461956fbce53069a4d3a54649b29/cloudinsight/onestatsd/base.py or https://github.com/bbc/cops-dd-backup-lambda/blob/master/libs/datadog/dogstatsd/base.py#L150:42 etc.

**Comment by felixfbecker** [comment] 2019-01-09 16:37
All the examples in the post are metrics within comments. Is this expected? Could you show an example with actual code?

**Comment by felixfbecker** [comment] 2019-01-09 16:42
None of the metric links show me any graph. Is this expected?

![image](https://user-images.githubusercontent.com/10532611/50914004-ed62ad00-1435-11e9-9fa9-1b6280251284.png)

**Comment by attfarhan** [comment] 2019-01-10 07:39
I have the two same questions as Felix above, but LGTM otherwise.

**Comment by vanesa** [comment] 2019-01-10 16:27
The metrics aren't visible due to the display setting on the top showing only metrics created within the last hour. 
If you change that to 2 days or 1 week, you will see metrics.
![image](https://user-images.githubusercontent.com/9110008/50982226-3b0f1080-152f-11e9-9d21-3a89fb88921a.png)

**Comment by vanesa** [comment] 2019-01-10 16:48
Here is a link to code: https://github.com/NickEnvy/rowboat/blob/b58afbc79b839eb8c54dca391e922de7a5c3aa14/plugins/stats.py

I only generated some metrics for `gateway.events.received` and `guild.messages.create`.

**Comment by felixfbecker** [comment] 2019-01-10 21:14
Confirmed working

**Comment by nicksnyder** [comment] 2019-01-11 23:13
I am closing this issue since it has been tested.

**Closed by nicksnyder** 2019-01-11 23:13 UTC
Labels: test-plan
