### ISSUE TITLE
Unify how matches are counted across file, commit, and diff searches

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#18377] opened 2021-02-17 15:08 UTC
Currently, each fragment match within a file counts toward results, while multiple matches in a repository or path name and diffs or commits are counted as a single result. This leads to confusion as to what Sourcegraph considers to be a match.

The fidelity of result counts should be improved to count both the entities returned and the number of matches within those entities. This will improve the user's ability to understand what was matched and make it possible to create code insights that track matches such as the number of todos in commit messages. 

Related https://github.com/sourcegraph/sourcegraph/issues/18301

**Comment by keegancsmith** [comment] 2021-02-17 18:41
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/18301

**Closed by keegancsmith** 2021-02-17 18:41 UTC
Labels: team/search
