### ISSUE TITLE
pgsql failing health checks: "sorry, too many clients already"

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#2264] opened 2019-02-12 15:38 UTC
When investigating the recent [page load alert](https://sourcegraph.slack.com/archives/C0J618TTM/p1549985087003500), I noticed that the pgsql pod has restarted 4 times recently: 

`kubectl describe pod` output: 

```
Events:
  Type     Reason     Age                   From                                        Message
  ----     ------     ----                  ----                                        -------
  Warning  Unhealthy  34m (x13 over 23h)    kubelet, gke-dot-com-dot-com-93160456-s7zw  Readiness probe failed: psql: FATAL:  sorry, too many clients already
  Warning  Unhealthy  34m (x15 over 3d15h)  kubelet, gke-dot-com-dot-com-93160456-s7zw  Liveness probe failed: psql: FATAL:  sorry, too many clients already
```

I don't know if this caused the alert, but it looked odd to me.

**Comment by nicksnyder** [comment] 2019-02-12 20:00
@tsenart @keegancsmith Please triage this into an appropriate milestone (or backlog).

**Comment by nicksnyder** [comment] 2019-04-15 16:22
Closing as duplicate of https://github.com/sourcegraph/sourcegraph/issues/3384

**Closed by nicksnyder** 2019-04-15 16:22 UTC
Labels: deployment, ops & tools & dev, sourcegraph.com
