### ISSUE TITLE
Validate reconciler works correctly

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#13648] opened 2020-09-04 16:29 UTC
I've just ran a test campaign that creates changesets on GitLab, GitHub and Bitbucket Server, and the behavior seems odd to me.

1. The BBS PR has been created successfully.
2. The GitHub PR switched to "failed" correctly, because I reused a branchname.
3. The GitLab PR stayed queued for quite a long time (few minutes)
4. The GitHub PR keeps getting retried infinitely (according to the logs)
5. The GitLab PR failed pushing the commit, now has an error message, but is still "processing" and continuously retries as well.

Screenshot:
![image](https://user-images.githubusercontent.com/19534377/92263018-3ead9300-eedc-11ea-8c2f-298eb1ebdd7c.png)

<details>
<summary>Logs:</summary>

```
18:13:21                      repo-updater | INFO Dequeued record for processing, name: , id: 39
18:13:21                      repo-updater | INFO Reconciler processing changeset, changeset: 39, action: publish
18:13:21                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:13:21                      repo-updater | INFO Dequeued record for processing, name: , id: 37
18:13:21                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:13:21                      repo-updater | INFO Reconciler processing changeset, changeset: 37, action: publish
18:13:21                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:13:21                      repo-updater | INFO Handled record, name: , id: 38
18:13:21                         gitserver | INFO command ran successfully, prefix: 1 gitlab.sgdev.org/sourcegraph/automation-testing , command: git init, duration: 13.465183ms, output: Initialized empty Git repository in /Users/erik/.sourcegraph/repos/.tmp/patch-repo-696411267/.git/
18:13:21                         gitserver | INFO command ran successfully, prefix: 2 bitbucket.sgdev.org/SOUR/automation-testing , command: git init, duration: 10.256229ms, output: Initialized empty Git repository in /Users/erik/.sourcegraph/repos/.tmp/patch-repo-153787398/.git/
18:13:21                         gitserver | INFO command ran successfully, prefix: 1 gitlab.sgdev.org/sourcegraph/automation-testing , command: git reset -q 3b79a5d479d2af9cfe91e0aad4e9dddca7278150, duration: 11.265111ms, output: 
18:13:21                         gitserver | INFO command ran successfully, prefix: 2 bitbucket.sgdev.org/SOUR/automation-testing , command: git reset -q 1e256a405ec07c904f0a4e681c8136cc9fca3b87, duration: 9.065984ms, output: 
18:13:21                         gitserver | INFO command ran successfully, prefix: 1 gitlab.sgdev.org/sourcegraph/automation-testing , command: git apply --cached -p0, duration: 8.577269ms, output: 
18:13:21                         gitserver | INFO command ran successfully, prefix: 2 bitbucket.sgdev.org/SOUR/automation-testing , command: git apply --cached -p0, duration: 6.84489ms, output: 
18:13:21                         gitserver | INFO command ran successfully, prefix: 2 bitbucket.sgdev.org/SOUR/automation-testing , command: git commit -m Append Hello World to all README.md files, duration: 15.782106ms, output: [master 945ea51] Append Hello World to all README.md files
18:13:21                         gitserver |  1 file changed, 1 insertion(+)
18:13:21                         gitserver | INFO command ran successfully, prefix: 1 gitlab.sgdev.org/sourcegraph/automation-testing , command: git commit -m Append Hello World to all README.md files, duration: 18.903035ms, output: [master 8b15bcc] Append Hello World to all README.md files
18:13:21                         gitserver |  1 file changed, 1 insertion(+)
18:13:23                         gitserver | INFO command ran successfully, prefix: 2 bitbucket.sgdev.org/SOUR/automation-testing , command: git push --force https://milton:NDg0MTQ3NTE2OTIzOlKZVPDnk591b6NJwYRhvynMHwND@bitbucket.sgdev.org/scm/sour/automation-testing.git 945ea515c806f5665998b95a7dc09f23061e1773:refs/heads/hello-world, duration: 2.428522252s, output: remote: 
18:13:23                         gitserver | remote: Create pull request for hello-world:        
18:13:23                         gitserver | remote:   https://bitbucket.sgdev.org/projects/SOUR/repos/automation-testing/compare/commits?sourceBranch=refs/heads/hello-world        
18:13:23                         gitserver | remote: 
18:13:23                         gitserver | To https://bitbucket.sgdev.org/scm/sour/automation-testing.git
18:13:23                         gitserver |  * [new branch]      945ea515c806f5665998b95a7dc09f23061e1773 -> hello-world
18:13:23                         gitserver | INFO command ran successfully, prefix: 2 bitbucket.sgdev.org/SOUR/automation-testing , command: git update-ref -- refs/heads/hello-world 945ea515c806f5665998b95a7dc09f23061e1773, duration: 7.567189ms, output: 
18:13:26                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:13:26                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:13:26                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:13:26                      repo-updater | INFO Handled record, name: , id: 38
18:13:26                      repo-updater | INFO Marked record as complete, name: , id: 37
18:13:26                      repo-updater | INFO Handled record, name: , id: 37
18:13:33                    syntect_server | 2020/09/04 16:13:33 request / http://127.0.0.1:33043
18:13:34                    syntect_server | 2020/09/04 16:13:34 request / http://127.0.0.1:33043
18:13:36                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:13:36                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:13:36                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:13:36                      repo-updater | INFO Handled record, name: , id: 38
18:13:38                    syntect_server | 2020/09/04 16:13:38 request / http://127.0.0.1:33043
18:13:38                    syntect_server | 2020/09/04 16:13:38 request / http://127.0.0.1:33043
18:13:42                    syntect_server | 2020/09/04 16:13:42 request / http://127.0.0.1:42419
18:13:42                    syntect_server | 2020/09/04 16:13:42 request / http://127.0.0.1:42419
18:13:46                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:13:46                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:13:46                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:13:46                      repo-updater | INFO Handled record, name: , id: 38
18:13:56                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:13:56                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:13:56                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:13:56                      repo-updater | INFO Handled record, name: , id: 38
18:14:01                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:01                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:01                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:01                      repo-updater | INFO Handled record, name: , id: 38
18:14:06                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:06                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:06                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:06                      repo-updater | INFO Handled record, name: , id: 38
18:14:11                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:11                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:11                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:11                      repo-updater | INFO Handled record, name: , id: 38
18:14:21                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:21                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:21                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:21                      repo-updater | INFO Handled record, name: , id: 38
18:14:31                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:31                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:31                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:31                      repo-updater | INFO Handled record, name: , id: 38
18:14:41                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:41                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:41                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:41                      repo-updater | INFO Handled record, name: , id: 38
18:14:51                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:51                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:51                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:51                      repo-updater | INFO Handled record, name: , id: 38
18:14:56                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:14:56                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:14:56                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:14:56                      repo-updater | INFO Handled record, name: , id: 38
18:15:04                         gitserver | INFO command failed, prefix: 1 gitlab.sgdev.org/sourcegraph/automation-testing , command: git push --force https://git:Axusi-qWEEeNUBp-hv7s@gitlab.sgdev.org/sourcegraph/automation-testing.git 8b15bcc5ef306ce93ffb6ee15e75a6e59b998505:refs/heads/hello-world, duration: 1m42.896111205s, error: exit status 1, output: error: RPC failed; HTTP 524 curl 22 The requested URL returned error: 524
18:15:04                         gitserver | fatal: the remote end hung up unexpectedly
18:15:04                         gitserver | fatal: the remote end hung up unexpectedly
18:15:04                         gitserver | Everything up-to-date
18:15:04                         gitserver | ERROR Failed to push, ref: refs/heads/hello-world, commit: 8b15bcc5ef306ce93ffb6ee15e75a6e59b998505, output: error: RPC failed; HTTP 524 curl 22 The requested URL returned error: 524
18:15:04                         gitserver | fatal: the remote end hung up unexpectedly
18:15:04                         gitserver | fatal: the remote end hung up unexpectedly
18:15:04                         gitserver | Everything up-to-date
18:15:04                      repo-updater | WARN Marked record as errored, name: , id: 39, err: creating commit from patch for repository "gitlab.sgdev.org/sourcegraph/automation-testing": gitserver: pushing ref: exit status 1
18:15:04                      repo-updater | ```
18:15:04                      repo-updater | $ git push --force https://git:<redacted>@gitlab.sgdev.org/sourcegraph/automation-testing.git 8b15bcc5ef306ce93ffb6ee15e75a6e59b998505:refs/heads/hello-world
18:15:04                      repo-updater | error: RPC failed; HTTP 524 curl 22 The requested URL returned error: 524
18:15:04                      repo-updater | fatal: the remote end hung up unexpectedly
18:15:04                      repo-updater | fatal: the remote end hung up unexpectedly
18:15:04                      repo-updater | Everything up-to-date
18:15:04                      repo-updater | ```
18:15:04                      repo-updater | INFO Handled record, name: , id: 39
18:15:06                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:15:06                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:15:06                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:15:06                      repo-updater | INFO Handled record, name: , id: 38
18:15:11                               web | ℹ ｢wdm｣: Compiling...
18:15:11                      repo-updater | INFO Dequeued record for processing, name: , id: 39
18:15:11                      repo-updater | INFO Reconciler processing changeset, changeset: 39, action: publish
18:15:11                      repo-updater | INFO Dequeued record for processing, name: , id: 38
18:15:11                      repo-updater | INFO Reconciler processing changeset, changeset: 38, action: publish
18:15:11                      repo-updater | WARN Marked record as errored, name: , id: 38, err: cannot create changeset on the same branch in multiple campaigns
18:15:11                      repo-updater | INFO Handled record, name: , id: 38
18:15:11                         gitserver | INFO command ran successfully, prefix: 3 gitlab.sgdev.org/sourcegraph/automation-testing , command: git init, duration: 12.603589ms, output: Initialized empty Git repository in /Users/erik/.sourcegraph/repos/.tmp/patch-repo-142971176/.git/
18:15:11                         gitserver | INFO command ran successfully, prefix: 3 gitlab.sgdev.org/sourcegraph/automation-testing , command: git reset -q 3b79a5d479d2af9cfe91e0aad4e9dddca7278150, duration: 9.087691ms, output: 
18:15:11                         gitserver | INFO command ran successfully, prefix: 3 gitlab.sgdev.org/sourcegraph/automation-testing , command: git apply --cached -p0, duration: 8.225385ms, output: 
18:15:11                         gitserver | INFO command ran successfully, prefix: 3 gitlab.sgdev.org/sourcegraph/automation-testing , command: git commit -m Append Hello World to all README.md files, duration: 17.488747ms, output: [master 8b15bcc] Append Hello World to all README.md files
18:15:11                         gitserver |  1 file changed, 1 insertion(+)
```
</details>

**Comment by mrnugget** [comment] 2020-09-14 07:12
> but does leave the GitLab MR in the processing state.

I think that's when the reset-stalled-job/`MaxStalledAge` mechanism of `workerutils` should kick in.



> This would imply that the crash isn't rolling back the transaction.

I'm sure you've found this by now, but the dequeue-and-set-to-processing happens outside the transaction:

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/workerutil/dbworker/store/store.go#L259-275

So if a worker crashes while it's processing a record the transaction that modified the record is rolled back (well, it's not committed), but the status is still set to processing. The new worker process that you boot up should reset the stalled jobs after `MaxStalledAge`

**Comment by mrnugget** [comment] 2020-09-14 09:40
btw. continually retrying is a feature, not a bug, see https://github.com/sourcegraph/sourcegraph/issues/12700#issuecomment-685419544

**Comment by davejrt** [comment] 2020-09-14 19:09
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by LawnGnome** [comment] 2020-09-16 05:03
To be clear, this didn't restart after `StalledMaxAge`, so I'm going to investigate this further in 3.21, although the immediate issue was fixed (or at least obscured) by #13790.

**Comment by LawnGnome** [comment] 2020-10-06 16:54
This hasn't been observed again, so deprioritising for now.

**Comment by eseliger** [comment] 2020-10-27 16:44
Given that we had a couple of weeks to find this "by accident" and we didn't, I guess we can close this ticket? @sourcegraph/campaigns

**Comment by chrispine** [comment] 2020-10-27 16:49
Yes, that's fine with me.

**Closed by chrispine** 2020-10-27 16:49 UTC
Labels: bug, estimate/1d, planned/3.20, planned/CampaignsSprint1, team/campaigns
