### ISSUE TITLE
searcher and symbols deployments should switch to statefulsets

### ISSUE THREAD

**Issue by ggilmore** [sourcegraph/sourcegraph#32279] opened 2022-03-07 19:45 UTC
Note: all of the arguments below also apply to the `symbols` service: 

---

Right now, `searcher` is implemented [in Kubernetes as a plain deployment](https://github.com/sourcegraph/deploy-sourcegraph/blob/v3.37.0/base/searcher/searcher.Deployment.yaml). I believe that this is largely due to historical reasons (the implementation predates the existence of stateful sets). `searcher` also utilizes a local cache to store zips of `repo@commit` that it fetches from `gitserver`. However, searcher’s current implementation as a deployment doesn’t play nicely with this caching scheme:

1.  Because `searcher` is a deployment, we can’t cleanly assign a persistent disk to store each replica’s cache. This forces us to use rely on the node’s ephemeral storage instead:  [https://github.com/sourcegraph/deploy-sourcegraph/blob/81cd19ef60d5d236d193ffeb2c28500fb58d703f/base/searcher/searcher.Deployment.yaml#L67](https://github.com/sourcegraph/deploy-sourcegraph/blob/81cd19ef60d5d236d193ffeb2c28500fb58d703f/base/searcher/searcher.Deployment.yaml#L67) . This has two problems:
- Kubernetes will forcefully evict the the searcher pod once it uses up all of its ephemeral storage. See [customer/issues/740](https://github.com/sourcegraph/customer/issues/740) for an example of this affecting a customer.
 - The cache is wiped out whenever the pod is restarted (either through rescheduling or through a normal deployment - which happens frequently on [sourcegraph.com](http://sourcegraph.com/)). This forces the cache to be repopulated.

1. Because `searcher` is a deployment, each pod doesn’t get a stable network identifier. This identifier can change on every re-deployment. This means that a repository can bounce around between replicas during this team - which also harms cache performance.
 
Both of these issues can be fixed by switching searcher over to a statefulset. A [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) allows us to use easily assign a persistent volume to each replica for the cache and have a stable network identifier (`searcher-0`, ...) to get rid of the repo bouncing problem.

**Comment by mike-r-mclaughlin** [comment] 2022-04-29 19:04
Evictions of searcher happening at customers [1](https://github.com/sourcegraph/accounts/issues/284) and [2](https://github.com/sourcegraph/accounts/issues/3)

**Comment by keegancsmith** [comment] 2022-05-03 13:59
FYI I am tracking the more general issue here now https://github.com/sourcegraph/sourcegraph/issues/34828 I'll leave this issue open since it is suggesting a fix which we may implement. However, there may be a faster or better path to stopping the impact.

**Comment by daxmc99** [comment] 2022-05-04 18:32
Disagree with us moving to stateful sets for these services. I don't think we need the statefulset guarantees here and we can better solve this problem with [Generic Ephermeral Volumes](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes)

Context: https://sourcegraph.slack.com/archives/C022SPMNR0W/p1651689067844299?thread_ts=1651247664.038619&cid=C022SPMNR0W

**Comment by stefanhengl** [comment] 2024-02-09 13:53
This issue has been inactive for a long time. To reopen the ticket, please let us know how to reproduce the issue on latest main. For feature requests, please let us know what is still missing.

**Closed by stefanhengl** 2024-02-09 13:53 UTC
Labels: team/search-platform
