### ISSUE TITLE
insights: filtering `repo:` filter by more than 1 character broken on customer instance

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#43267] opened 2022-10-20 23:57 UTC
Sourcegraph version 3.43. 

Browser – not confirmed 

## Steps to reproduce 

Typing in a filter like so (pictured) returned filtered data: 
![image](https://user-images.githubusercontent.com/11967660/197080617-d7588133-6b5e-47c8-89c6-f5a26d937189.png)

Typing in a filter with more than 1 character never returned any data (insight totally blank):
![image](https://user-images.githubusercontent.com/11967660/197080673-8b2749ef-65cb-4cbe-88fb-03b0a1b9b6c8.png)

Expected behavior – should have still returned filter data. Actual behavior – returned no data. 

Note – during this testing, the insight was still processing, but that shouldn't have mattered: partial data still is returned in the filtered view (and in this case, though only when the filter was 1 character long). 

We test this on this customer https://github.com/sourcegraph/accounts/issues/578 with an insight running over just 5 repos. Single-letter filters returned filtered data but any two character string, or exact repo matches, did not. 

/cc @joelkw @felixfbecker @vovakulikov

**Comment by vovakulikov** [comment] 2022-10-21 01:15
@Joelkw I'm not sure what do you expect from filters with value that doesn't match any repo, I would expect the current behaviour where you have no data at all because there is no repositories that the current filter matches. 

@chwarwick I'm removing web app label from this issue since I don't think this is a web app problem, I checked 4.0.1 and 3.43 version in both cases FE sends correct filter values, BE just return zero point lists (which makes sense to me)

Feel free to add web app label back and assign this issue to me if you will find something FE related.

**Comment by Joelkw** [comment] 2022-10-21 05:20
@vovakulikov sorry, to be clear:
>  I would expect the current behaviour where you have no data at all because there are no repositories that the current filter matches
Was *not* the case. We were typing in repo names that we knew had data. (How? There were only 5 repos in the insight, and at least some data returned when filters were blank or had a single character. But typing in more characters of any of the 5 repos always returned blank, even just two characters. But surely, given all the repos together had data, at least one had to have data individually!) 

Just noting that for whoever looks at it, not saying that means it's webapp.

**Comment by chwarwick** [comment] 2022-10-21 20:13
I have not been able to reproduce this things I've tried:

- Basic filter include/exclude
- Scoped insight over 3 repos including a very large repo and filtering while the insight is backfilling in v3.43.2 and 4.0.1
- Using a repositoryPathPattern to change the repo name to see if I could filter by name generated by the repositoryPathPattern.

**Comment by Joelkw** [comment] 2022-10-26 06:38
This has come up multiple times but both times on old instances, so maybe it was since solved? https://sourcegraph.slack.com/archives/C01JR51JR5J/p1666766272905789?thread_ts=1666364757.074459&cid=C01JR51JR5J

**Comment by coury-clark** [comment] 2022-10-26 22:35
As I understand this is a customer issue and there is a call trying to get set up to debug. Until we have more reason to believe this isn't specific to customers with broken insights (which all of these cases seem to be), I'm going to close this. If we get information from the debug session that changes that we can reopen.

**Closed by coury-clark** 2022-10-26 22:35 UTC
Labels: bug, team/code-insights, backend
