### ISSUE TITLE
History tab should follow renames

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#19715] opened 2021-04-06 16:44 UTC
I was looking for old changes to a file (https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/licensing/user_count.go#L159&tab=history) and noticed that older commits don't appear there (even though I can see blame for 1+ year old changes). 

![image](https://user-images.githubusercontent.com/5589410/113747839-a8815b80-96bc-11eb-80bc-ab5740673f73.png)

![image](https://user-images.githubusercontent.com/5589410/113747870-afa86980-96bc-11eb-9afe-bc75aa860a4b.png)

Even just changing the history tab to say something like "X commits total in the last Y months. Click here to see all commits." or something would be a better UX!

**Comment by pdubroy** [comment] 2021-04-07 08:30
It looks like the cause of this is a difference between how `git blame` and `git log` deal with renames. By default, `blame` follows renames, while `log` does not.

By default `git log` only shows 3 commits for this file:

```
[sourcegraph] git --no-pager log --oneline ./enterprise/internal/licensing/user_count.go
057ded0f6f Enforce unconvert lint (#18746)
7b0f5c81a8 db: rename internal/db package to internal/database (#17607)
80337369ac chore: move up licensing package (#14940)
```

while adding the `--follow` option reveals several more:

```
[sourcegraph] git --no-pager log --follow --oneline ./enterprise/internal/licensing/user_count.go
057ded0f6f Enforce unconvert lint (#18746)
7b0f5c81a8 db: rename internal/db package to internal/database (#17607)
80337369ac chore: move up licensing package (#14940)
cc705fa198 enforce published user limit when no license (#9859)
1771a8face refactor license features/plans code (#9849)
73349c78bb all: migrate to github.com/inconshreveable/log15 (#9245)
cca599da17 Enforce free user limit on enterprise builds (#5922)
85fba22315 Rename pkg to internal (#5898)
e7b982df18 Use new redigo package path (#5352)
e5a5479376 Add a warning alert when usage exceeds the limit of free user accounts (#3359)
6183bf62bb Remove cycle between enterprise/internal/authz and db pkg (#2665)
b58d94d985 feat: make SSO available in Core, add 200-user limit to Core
9da467a9fb fix: calculate and show accurate count of max users per license (#586)
```

**Comment by felixfbecker** [comment] 2021-04-07 10:20
I think this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/4383 then

**Comment by sqs** [comment] 2021-11-28 22:02
dupe of #4383

**Closed by sqs** 2021-11-28 22:02 UTC
Labels: gitserver, team/core-application
