### ISSUE TITLE
Show repo metadata on repo result

### ISSUE THREAD

**Issue by benvenker** [sourcegraph/sourcegraph#40184] opened 2022-08-10 02:55 UTC
We'd like to display repo metadata in the repo result. The possible metadata will come in a `key: value` format, and there could potentially be multiple values for a given key. For example:
- `topics: [backend, frontend, middleware]`
- `languages: [javascript, go]`
- `tags: [private, draft, experimental]`

Users will be able to enter arbitrary metadata via our API so we'll have limited control content but we can do some things with how we display it.

cc @camdencheek can you either link to or provide here the currently-supported data types? I'd also like to know if there is a need to support any data that is atomic, and not part of a `key: value` pair.

**Comment by camdencheek** [comment] 2022-08-10 15:06
> there could potentially be multiple values for a given key

This is not currently the case. A `key:value` pair is unique per repo. At some point, we will likely add other value datatypes like arrays, but for now we only support strings. 

Right now, the two types of data that we'd need to make viewable are:
1) `key: value` pairs where both `key` and `value` are strings, and
2) `tag` where `tag` is just a string associated with the repo (implemented as `key: NULL`)

**Comment by benvenker** [comment] 2022-08-11 16:12
Ah ok. So we'd want a combination of structured UI for `key: value` pairs then and lightly/unstructured UI for tags I think

**Comment by lguychard** [comment] 2022-08-17 14:34
Duplicate of #40014

**Closed by lguychard** 2022-08-17 14:34 UTC
Labels: needs-design, team/search-product, cp-core-workflow
