### ISSUE TITLE
Batch Changes and Bitbucket: 409 error when updating batch changes after they were published

### ISSUE THREAD

**Issue by northyg** [sourcegraph/sourcegraph#28962] opened 2021-12-13 23:58 UTC
- **Sourcegraph version:** 3.34.2 
- **Platform information:** docker-container 

#### Steps to reproduce:

1. Attempted to update some batch changes after they have been published
2. Most of those changes are now in an error state and failing with errors like:

```
Updating changeset: Bitbucket API HTTP error: code=409 url="<url example here>" body="{"errors":[{"context":null,"message":"You are attempting to modify a pull request based on out-of-date information.","exceptionName":"com.atlassian.bitbucket.pull.PullRequestOutOfDateException","currentVersion":2,"expectedVersion":1,"pullRequest":{"id":89,"version":2,...
```
3. Updated step: This looks like it could have been caused by changing the PR title and/or description in the batch change. Reverting the title/description changes appears to get sourcegraph back in a better state.

#### Expected behavior:

Batch change should succeed without error or not get stuck in a failed state.

#### Actual behavior:

Stuck in a failed state.

If would like immediate help on this, please email support@sourcegraph.com (you can still create the issue, but there are not [SLAs](https://about.sourcegraph.com/support/) on issues like there are for support requests).

**Comment by malomarrec** [comment] 2021-12-14 16:54
@northyg what customer was impacted? was it https://github.com/sourcegraph/accounts/issues/1603 ?

**Comment by northyg** [comment] 2021-12-14 18:07
> what customer was impacted? was it [sourcegraph/accounts#1603](https://github.com/sourcegraph/accounts/issues/1603) ?

@malomarrec Yes! That would be the one.

**Comment by mrnugget** [comment] 2021-12-15 14:57
@northyg what exactly did you try to update?

> Attempted to update some batch changes after they have been published

The diff/description/etc. of changesets or the state of the batch changes themselves (by closing them)?

**Comment by mrnugget** [comment] 2021-12-15 15:52
Sorry @northyg, missed the last part of the ticket.

I figured out how to reproduce this. Good news: it doesn't happen with every update. Bad news: it's a race condition and a deadlock, a concurrency double whammy.

Steps to reproduce:

1. Publish changesets with title "foobar"
2. Go to Bitbucket instance, change title manually to "foobar 2"
3. _Immediately after_ (so that Sourcegraph hasn't synced the changeset yet and title still shows up as "foobar" in Sourcegraph): update batch spec and apply to change title to "foobar 3"
4. Updating changeset will fail, because BBS responds with version conflict: BBS instance has newer version than Sourcegraph has. 
5. On top of that: changeset syncer won't sync newest version, because changeset is in "retry" mode and syncer doesn't touch changesets that are being processed/retried to avoid race conditions.

Thinking about how to fix now

**Comment by northyg** [comment] 2021-12-15 18:02
@mrnugget No worries! I appreciate the update and glad you found a way to reproduce it. Bummer to hear it's a race condition. ☹️ 

Correct me if I'm wrong, but it sounds like a temporary work around is to wait for the Changeset to sync like in step 4. so the versions are the same. Does that sound accurate?

**Comment by mrnugget** [comment] 2021-12-15 19:29
Yes, kind of. The workaround would be to get things back into a working
state first, *then* sync the changesets (or wait for them to sync), *then*
apply the update.

**Closed** 2021-12-17 11:14 UTC
Labels: bug, team/batchers

**Comment by mrnugget** [comment] 2021-12-17 12:52
@northyg Fix is merged and will be in today's release cut.
