### ISSUE TITLE
[DESIGN] Prepare Readme page for JetBrains Plugin

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#52773] opened 2023-06-01 13:50 UTC
Context:https://sourcegraph.slack.com/archives/C059N5FRYG3/p1685622744981649

Before public launch we need to prepare the assets and contents for the Readme of the Jetbrains plugin:

![Image](https://user-images.githubusercontent.com/7814431/242618143-04aca324-849a-4e40-8cd9-2bbcfed8b918.png)

**Comment by danielmarquespt** [comment] 2023-06-27 14:03
Readme File:

https://gist.github.com/danielmarquespt/6839da1a2a4467627fcdfab78aa21f3e


Please have a look at the content. I stripped most of the things that apply to VSCode only

**Comment by danielmarquespt** [comment] 2023-06-27 14:04
Images for the top carousel

![AutoCompletion_IntelliJ_Promo](https://github.com/sourcegraph/sourcegraph/assets/7814431/bcfba706-8c15-4048-9f18-15bcf85f4895)
![Chat_IntelliJ_Promo](https://github.com/sourcegraph/sourcegraph/assets/7814431/d9e2bda5-08e0-45c9-83c5-6a21154cca4f)

**Comment by vdavid** [comment] 2023-06-27 14:10
Not no nit too much on it because I also just want this out the door, but I think both "Autocompletions" and "Codebase" are one word, and I think "Codebase-aware" is the correct spelling for the two words combined.

- [source for autocompletions](https://en.wiktionary.org/wiki/autocompletion)
- "codebase" is in our company Grammarly.

For "Autocompletions", maybe "Code autocompletion" is also good.

If you still have the vector version for the pics, I suggest fixing them because these are very prominent titles.

**Comment by vdavid** [comment] 2023-06-27 22:45
@danielmarquespt do you have these screenshots in better quality? Marketplace's recommended minimum is 1200 × 760 pixels.

**Comment by vdavid** [comment] 2023-06-27 22:49
@danielmarquespt, do you think I should remove the old screenshots and video (https://youtu.be/njbWvUrgm5c) that demo the search functionality? For now, I've removed the video and added the two new screenshots as the first ones, so it looks like this:



![Image](https://github.com/sourcegraph/sourcegraph/assets/2552265/686bb10c-035c-4ea4-a593-3fed63a5babf)


But you can still click some arrows and see the older screenshots, is that fine?

**Comment by vdavid** [comment] 2023-06-28 10:33
@danielmarquespt closing this up because the issue is solved. Feel free to respond in the comments if you think we should tweak it. The higher-res screenshots would be nice I think

**Closed by vdavid** 2023-06-28 10:33 UTC
Labels: cody, cody/jetbrains
