### ISSUE TITLE
Codecov: Set API token only appears in public repo or when signed out

### ISSUE THREAD

**Issue by joebowbeer** [sourcegraph/sourcegraph#763] opened 2018-10-05 19:05 UTC
I'm noticing some weird behavior with what I think is called the context menu, which may be preventing me from viewing codecov for a private GitHub repo.

If I'm viewing a private repo, the context menu either doesn't display or it shows only the Codecov documentation item. Then when I view a public repo, the menu shows more items, including the Codecov Set API item.

Even at sourcegraph.com, if I'm signed in, then the context menu only shows me one item: Codecov: Documentation and support. Then, if I sign out, the context menu shows me seven items, including Codecov: Set API token. 

(By the way, I'm also confused about the connection between my browser extension settings and the ones for my account at sourcegraph.com. What is the connection between my sourcegraph account and my GitHub or Codecov account? This may be related to discussion at #232?)

**Comment by ryan-blunden** [comment] 2018-11-09 19:23
@joebowbeer Is the Codecov extension working on private repositories for you now?

**Comment by lguychard** [comment] 2018-12-18 16:23
@joebowbeer Is the Codecov extension working correctly on private repositories for you now?

**Comment by lguychard** [comment] 2019-01-07 10:31
Closing this since we cannot reproduce on our side.

@joebowbeer if you're still experiencing this issue, let us know and we'll look into it!

**Closed by lguychard** 2019-01-07 10:31 UTC
Labels: browser-extension, bug
