### ISSUE TITLE
Search bar autopopulating with unknown/unexplained string

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#8834] opened 2020-03-05 21:16 UTC
Reported by a user at https://app.hubspot.com/contacts/2762526/company/419771425

> This happens the moment I open a page. And the text is always the same from the past few weeks. I’m not sure where it came from because it is not on my clipboard.

The search bar(s), whether on a file/repo or on the main /search route, appear to be populated with a long query of the form: `repo:<repo>@<sha> <long variable/function name>`

See https://sourcegraph.slack.com/archives/CMT39K56Z/p1583442628064500 for more context

**Comment by sqs** [comment] 2020-03-06 01:15
Chrome autocompletion? Chrome uses heuristics for autocompletion, and there may be some Chrome experiment that tweaked a heuristic and thinks that this field needs to be autocompleted. I saw this occur on Sourcegraph previously (on the main site admin page on localhost:3080, sometimes the search field in the global nav would be auto-filled with the management console password).

**Comment by attfarhan** [comment] 2020-03-06 02:26
We have `autoComplete="off"` on the input field in the `QueryInput` component, but it seems Chrome doesn't respect it (https://bugs.chromium.org/p/chromium/issues/detail?id=587466), so that could be possible. 

I'm not quite sure how to test this though, I can't reproduce even when setting autocomplete="on"

**Comment by dadlerj** [comment] 2020-03-06 19:41
Looks like LastPass was the problem, great call @attfarhan !

>Hi,
>
>Disabling LastPass helped. However, I’m going to need it enabled. Is there a way to disable it just for sourcegraph or make sure that it doesn’t fill anything in for sourcegraph?


I shared a link to https://support.logmeininc.com/lastpass/help/disable-lastpass-for-specific-sites-lp040006

Is there any reason to keep this issue open (e.g. maybe we need this somewhere in our docs)? I leave that call up to you @attfarhan

**Comment by attfarhan** [comment] 2020-03-08 04:57
@dadlerj I think the proper solution is to tell him that he accidentally added an entry for Sourcegraph, which contains the string that was getting autofilled, in LastPass. They should remove that entry, by searching in LastPass for the string that gets autofilled, and delete the entry. 

It's not an actual conflict between LastPass and Sourcegraph, the user just accidentally added a bad entry, so I'm going to close this.

**Closed by attfarhan** 2020-03-08 04:57 UTC
Labels: bug, team/web
