### ISSUE TITLE
Search results: Too many scrollbars on file page 

### ISSUE THREAD

**Issue by marisak** [sourcegraph/sourcegraph#34363] opened 2022-04-22 15:13 UTC
(courtesy of Thorsten) 

When viewing an individual file, two layers of scrollbars appear on what's presumably the file container and the page container. 

![image.png](https://images.zenhubusercontent.com/615f305588d61240b0ddcf0d/d45ab721-3a24-4a6e-86c8-10a9d90b35dc)
[Link to example file](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/internal/types/types.go) that exhibits this problem.

**Comment by sourcegraph-bot-2** [comment] 2022-04-22 15:14
Heads up @benvenker @lguychard - the "team/search-product" label was applied to this issue.

**Comment by camdencheek** [comment] 2024-03-04 22:50
Closing since I cannot reproduce.

**Closed by camdencheek** 2024-03-04 22:50 UTC
Labels: bug, needs-design, team/search-product, team/code-search, imported
