### ISSUE TITLE
Add support for controlling number of context lines displayed similar to `grep -C`

### ISSUE THREAD

**Issue by analogue** [sourcegraph/sourcegraph#2432] opened 2019-02-25 16:25 UTC
#### Feature request description

The immediate search results from a search query using the web interface displays each search result with 3 lines of context: the line before, the line containing the search hit, and the line after. 

For occasions where developers would like additional lines of context in the search results, a user has to click on every single search hit individually. This is cumbersome and a bit frustrating.  

The cmd line tool, grep, solves this by enabling context lines (taken from grep's man page):
```
Context Line Control

-A NUM, --after-context=NUM
    Print NUM lines of trailing context after matching lines. Places a line containing a group separator (--) between contiguous groups of matches. With the -o or --only-matching option, this has no effect and a warning is given. 
-B NUM, --before-context=NUM
    Print NUM lines of leading context before matching lines. Places a line containing a group separator (--) between contiguous groups of matches. With the -o or --only-matching option, this has no effect and a warning is given. 
-C NUM, -NUM, --context=NUM
    Print NUM lines of output context. Places a line containing a group separator (--) between contiguous groups of matches. With the -o or --only-matching option, this has no effect and a warning is given. 
```

Maybe a `context-lines` search directive could be added to support similar behavior in the web UI.

#### Describe alternatives you've considered.

Searching https://docs.sourcegraph.com/user/search/queries yielded no alternatives.

**Comment by sqs** [comment] 2019-02-27 15:47
This is a great idea (and is indeed not currently supported). Thanks!

**Comment by sqs** [comment] 2019-03-07 19:57
Adding to 3.2 milestone tentatively and will figure out if we can fit this in before assigning it to someone else. 

I believe the best impl would be to add a new setting that controls this (for file results only, not for diff results). Then it could be set globally or per-user.

**Comment by attfarhan** [comment] 2019-03-12 00:53
We've added a setting to configure the number of context lines shown in search results. You can set `search.contextLines` in your user settings on Sourcegraph.com to the number of context lines you prefer to see. This will be in the 3.2 release.

I'll leave this issue open since I haven't gotten around to implementing the search keyword to configure this at query time yet, but thought I'd post an update here since it's related.

**Comment by slimsag** [comment] 2019-03-14 18:28
(someone else has asked for the ability to set this via a search keyword)

**Comment by sqs** [comment] 2019-03-15 06:42
Closing because the only thing left is the search keyword, and I don't think we should do that. See my alternative proposal and reasoning in #2754. 

Note that https://github.com/sourcegraph/sourcegraph/pull/2755 adds a button to the global/org/user settings JSON editor pages to configure `search.contextLines`, which makes this a bit easier.

**Comment by analogue** [comment] 2019-03-16 16:38
Thanks folks for the quick turnaround! Much appreciated :smiley:

**Comment by sqs** [comment] 2020-03-18 02:52
Reopened per https://github.com/sourcegraph/sourcegraph/issues/2754#issuecomment-600339681.

**Comment by poojaj-tech** [comment] 2020-11-03 22:43
@attfarhan would you know if this is a small feature (<2d work)? Asking because I'd like to add it to search team backlog to track and prioritize if it is (currently the backlog is all bugs + small features).

**Comment by attfarhan** [comment] 2020-11-04 10:20
@poojaj-tech yes, this is likely doable in <2d

**Comment by kzahel** [comment] 2021-07-15 18:58
Find it pretty counter-intuitive that I have to go to my user settings and set `search.contextLines`, and then the search result isn't "linkable" to others.

**Comment by anovitskiy** [comment] 2021-11-03 22:57
Any progress made on this? Number of lines of context depends on the type of search that one is doing, so while the user setting is great for a default value, it should be overridable in any given search.

**Comment by lguychard** [comment] 2021-11-05 12:47
Duplicate of #2754

**Closed by lguychard** 2021-11-05 12:47 UTC
Labels: feature-request, team/search, customer

**Comment by ssbarnea** [comment] 2022-04-05 08:57
> search.contextLines

Sorry but that feature is extremely well hidden. At least you could add a sample commented config file to user profile to make it easier to discover.
