### ISSUE TITLE
Code Insights: [BE] Support filters in `createLineChartSearchInsight`

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#29293] opened 2021-12-21 20:40 UTC
At the moment we don't have a filters field in the input type for the `createLineChartSearchInsight` mutation. Because of this FE has to create insight without filters and then send another mutation `updateLineChartSearchInsight` to be able to set filters. 

All of this brings a lot of complexity to the FE so it would be good to support filters in the `createLineChartSearchInsight`

**Comment by vovakulikov** [comment] 2021-12-21 20:50
cc @coury-clark @CristinaBirkel

**Comment by CristinaBirkel** [comment] 2022-02-11 22:21
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/27836

**Closed by CristinaBirkel** 2022-02-11 22:21 UTC
Labels: team/code-insights, backend
