### ISSUE TITLE
Confusion when searching for literal

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#22976] opened 2021-07-19 14:39 UTC
From @JoshuaKGoldberg:

> Trying a basic literal search for `connect pure false` and also getting zero results. 
See image below. Amusingly, it both says there are no results and that I've hit the result count limit.

<img width="1127" alt="Sourcegraph No Results Limit" src="https://user-images.githubusercontent.com/1976/126177138-fad1369e-21a9-439f-8e5c-1c585449643e.png">

My comments:

- I can't reproduce the issue where the `Result limit hit.` alert shows up. I just see `No results.` But the screenshot proves it, so we should look into it.
- In this case, the user wanted something like regexp `connect.*pure.*false` and (understandably but mistakenly) thought that our literal search would yield that. (That is what you'd get if you clicked the `.*` icon to enable regexp search.) How can we address this confusion? If I enable regexp search, I do see [results](https://sourcegraph.com/search?q=context:global+connect+pure+false+lang:typescript&patternType=regexp). (Note that the higher-level intent was described in https://twitter.com/acemarke/status/1416585511565725696. The user really wanted something even simpler/higher-level, and we should absolutely make that work; see #22975. But we should also clear up this intermediate confusion.)

Related PR: #20356

**Comment by benvenker** [comment] 2021-08-24 23:24
Just tested this after @vanesa brought it to my attention. I was able to reproduce the `No results` as well but not `Result limit hit.`. @rvantonder it sounds like this isn't a bug but rather a use case to consider supporting – is that a fair assessment?

**Comment by benvenker** [comment] 2021-09-14 03:35
@rrhyne I wonder if this is a good first candidate for our "Did you mean..." approach, and one that could pretty easily be detected without being blocked on @fkling's exploratory work for more complex query analysis.

I wonder if we could do something like detect when there are two or more strings not attached to a search token and provide a "did you mean" result that included the unordered syntax, ideally with some explanation as to what's being shown.

**Comment by rrhyne** [comment] 2021-09-14 12:47
This is a perfect first candidate. This type of query is described in the ticket:

https://github.com/sourcegraph/sourcegraph/issues/24458

**Comment by benvenker** [comment] 2021-09-14 13:58
Great, I'll get it in our next iteration

**Comment by camdencheek** [comment] 2024-02-22 23:19
Closing since we now separate query patterns with `AND` by default, so this search will, in fact, return results.

**Closed by camdencheek** 2024-02-22 23:19 UTC
Labels: team/search-product, search-ux, team/code-search, imported
