### ISSUE TITLE
Change "Active" state of button to use "Hover" styles instead of "Focus" styles

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/sourcegraph#25218] opened 2021-09-22 09:27 UTC
#### Problem statement

The ["active" state for the button group](https://storybook.sgdev.org/?path=/story/branded-global-styles--button-groups) on the search homepage looks like a focus state. When a user opens the page button groups look confusing because it looks like that button is keyboard-focused, but clicking elsewhere doesn't unfocus it.

![image](https://user-images.githubusercontent.com/10532611/129232997-0d810b84-cd3f-4ef2-bc7f-006f28a596d2.png)

Looking at the CSS class, it uses `active`, and `active` is part of the same selector that applies `:focus` styles.

Related issue #23849

#### Success criteria

1. Button active state uses the styles as hover state.

#### Things to learn/practice during the implementation

CSS kung-fu.

#### Estimated amount of work

T-shirt size estimate: **S**.

**Comment by dharmelolar** [comment] 2021-10-05 22:46
Hello , Please can I work on this issue?

**Comment by vanesa** [comment] 2021-10-21 23:12
@OlushesiToheeb Are you still working on this PR? Else I would like to free up this issue so someone else can tackle it. Thank you!

**Comment by pidoxy** [comment] 2021-10-22 00:16
Can I work on this if it's free @vanesa ?

**Comment by umpox** [comment] 2022-10-04 13:49
Noticed this is a duplicate of another issue. Closed in favour of https://github.com/sourcegraph/sourcegraph/issues/35354 to avoid duplicating work

**Closed by umpox** 2022-10-04 13:49 UTC
Labels: good first issue, team/frontend-platform, sourcegraph-refinement-bot
