### ISSUE TITLE
Autocomplete menu doesn't disappear after user hits "enter"

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#7051] opened 2019-12-05 02:29 UTC
Repro:
1. Make a search on sourcegraph.com (e.g., https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24%405498219+%3CLink+file:.tsx&patternType=literal)
1. Observe the autocomplete menu drops down
1. Hit enter
1. Observe the autocomplete menu remains open, obscuring search results. It used to disappear when user hit enter.

**Comment by felixfbecker** [comment] 2019-12-05 02:54
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/6748

**Closed by felixfbecker** 2019-12-05 02:54 UTC
Labels: p1
