### ISSUE TITLE
Go code intel re-searches for matches when toggling basic-code-intel on and off

### ISSUE THREAD

**Issue by francisschmaltz** [sourcegraph/sourcegraph#1446] opened 2018-12-15 00:26 UTC
When toggling basic-code-intel on and off from the references panel go code intel reference matches disappear and are searched for again.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/frontend/auth/auth.go#L35:6&tab=references

![screen shot 2018-12-14 at 4 25 41 pm](https://user-images.githubusercontent.com/11583013/50036312-e7a3b400-ffbc-11e8-9e5a-3a8566b7f428.png)
![fuzzy-go-issue](https://user-images.githubusercontent.com/11583013/50036314-ed999500-ffbc-11e8-9b1e-fc87bb7c5adf.gif)

**Comment by sqs** [comment] 2018-12-15 00:37
@chrismwendt this may be caused by the Go extension un/reregistering each time settings change instead of only when necessary. If it’s not a Go extension problem, please reassign to @lguychard

**Comment by chrismwendt** [comment] 2018-12-15 02:06
Thanks for pointing that out, I [added `distinctUntilChanged`](https://github.com/sourcegraph/lang-go/commit/10abfa56dfb4cee87beb62f629fd64404efd5ab3) to the Go extension.

However, the problem persists. This appears to be an extension issue (not specific to the Go extension). References get recomputed even when the Go extension does not register/deregister the references provider. Assigning to @lguychard

**Comment by felixfbecker** [comment] 2019-01-09 19:23
Commented on the commit https://github.com/sourcegraph/lang-go/commit/10abfa56dfb4cee87beb62f629fd64404efd5ab3#r31887677

**Comment by sqs** [comment] 2019-01-30 07:44
This is still occurring, but it is much less of an issue given that the **Show/hide  fuzzy matches** action is going away in #2035 (for 3.0). Therefore I am closing it because it will be solved by #2035.

**Closed by sqs** 2019-01-30 07:44 UTC
Labels: feature:code-intel
