### ISSUE TITLE
Sourcegraph.com: global regex search returns no results, but results exist

### ISSUE THREAD

**Issue by beyang** [sourcegraph/sourcegraph#13105] opened 2020-08-18 15:56 UTC
Repro:

* Go to https://sourcegraph.com/search?q=chang.sets%5Csare%5Csonly&patternType=regexp. Note that no results are found.
* Go to https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+chang.sets%5Csare%5Csonly&patternType=regexp. Note this is the same search query, scoped to the repository that contains the target result.
* Note that other global queries return results over this repository (it is in `default_repos` and therefore part of the global index): https://sourcegraph.com/search?q=changesets+are+only+available+in+enterprise&patternType=regexp

Unclear if this indicates a general bug with global search (or if it's specific to the use of `default_repos` and therefore sourcegraph.com). I suspect the former, which means this is high priority, as it means we may be returning no results in some cases where results do exist.

**Comment by rvantonder** [comment] 2020-08-18 17:13
Extra data point: I noticed that the 3rd query at first returned no results for me, and later worked.

**Comment by rvantonder** [comment] 2020-08-18 17:14
Possibly related (since Zoekt/regex search on indexes affect structural search): https://github.com/sourcegraph/sourcegraph/issues/13090#issuecomment-675230402

**Comment by beyang** [comment] 2020-08-18 17:34
cc @keegancsmith @sourcegraph/search

**Comment by keegancsmith** [comment] 2020-08-18 19:14
Did a super quick look now, will likely stay focussed on streaming. If
you look at the trace we are timing out. For some reason we are not
reporting back to the user that indexed search timed out?

Could pair on Thursday?

@beyang Also noticed that the traces on zoekt are not being reported as
child spans of the client calls on on Sourcegraph.

**Comment by keegancsmith** [comment] 2020-08-24 08:38
@beyang assigning back to you. We fixed the timeout not being reported issue. We still have other timeout related issues here. Mainly the timeout reporting code is a bit brittle, it only reports timeout if no results.

Assigning back to you since the root cause is a timeout, and this is Sourcegraph.com specific. We can't make zoekt faster here with a code change, it needs more resources. We could increase the 20s timeout, but 20s sucks either way. I would rather increase the size of our zoekt cluster or reduce the number of repos we index (for now).

Medium term streaming may help here since it lets us be more aggressive with timeouts.

**Comment by keegancsmith** [comment] 2020-08-24 16:30
@beyang I keep thinking we should scale back Sourcegraph.com to 100k repos instead of the current 200k. For example when I type random regex searches (eg `foo.*bam`) it takes 4s. I think this bumping up has had other effects. WDYT @beyang @rrhyne @rvantonder?

**Comment by rvantonder** [comment] 2020-08-24 16:44
I'm in favor of scaling back. I think the tradeoff of a more comprehensive, but slower, super global search doesn't really have a use case we're going for right now. It creates a poor/slow impression if new users experiment with regexp for the first time without scoping to repo.

But I think we should keep the 100 or 200K _indexed_, just that the number of default repos included in global search is lower (maybe even just 10K like before). Could this be done by limiting count to N for for the `default_repos` table on global search? Though, this might not be the best, because ideally we want the default repos for global search to be the top 10K by, say, GH stars, not just an arbitrary top 10K of the 200K

**Comment by keegancsmith** [comment] 2020-08-24 17:22
> But I think we should keep the 100 or 200K _indexed_, just that the
> number of default repos included in global search is lower (maybe even
> just 10K like before). Could this be done by limiting count to N for
> for the `default_repos` table on global search? Though, this might not
> be the best, because ideally we want the default repos for global
> search to be the top 10K by, say, GH stars, not just an arbitrary top
> 10K of the 200K

This sounds very do-able. @beyang could you implement this? It's a bit
of a shame to have 200k repo indexes in memory, but never use them :) So
I'm a bit torn on this solution.

**Comment by beyang** [comment] 2020-08-31 20:54
Pushing back on this. If the current set of priorities on the search team has us working on stuff other than perf at scale while perf at scale is an issue (both because sourcegraph.com and because we have important customers in the pipeline that require perf at scale), then I question whether our current prioritization is correct. More thoughts here: https://docs.google.com/document/d/1kfYOjHXnS36Mv2E45WXUePllGU6x8unmyDVE9xGTPbE/edit

**Comment by keegancsmith** [comment] 2020-09-02 08:33
@beyang That is a question of prioritization. A good place for that discussion is in our weekly search syncs and here https://github.com/sourcegraph/about/pull/1462 I'll comment on that PR linking to your doc and I'm sure we will discuss it. Probably best to keep this discussion somewhat centralized, so will keep that discussion to that PR. Would be great if you could also join in :)

However, the current scale is having a real impact on users. Even if we made scale a larger prioritisation there is no need to keep us at the 200k scale, and rather scale up once we _do_ support it well.

**Comment by beyang** [comment] 2020-09-03 21:26
Makes sense, I'll reduce the search index today and join the next search sync.

**Comment by beyang** [comment] 2020-09-04 01:28
Okay, # repos in the global index down to 106k

**Comment by davejrt** [comment] 2020-09-14 19:10
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.20 release is scheduled for tomorrow**.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment] 2020-09-15 08:27
> Okay, the number of repos in `default_repos` has been reduced to 106k (I removed the top 100k largest `repo_id`s).

Did you scale this back up? I see a message in slack saying we have 200k again. What is the current status/plan for your work on this?

**Comment by beyang** [comment] 2020-09-17 20:43
I did scale it back up, to collect some more data. Scaled back down, sorry if this caused any issues!

**Comment by lguychard** [comment] 2021-11-05 10:54
Closing: we now have over 2 million repos on Cloud and the global regex query in the OP returns results 🙂

**Closed by lguychard** 2021-11-05 10:54 UTC
Labels: bug, team/search-core
