### ISSUE TITLE
Better way to handle go to defs when something goes wrong?

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#1868] opened 2019-01-14 16:16 UTC
I'm not sure if the odd behavior is due to the lang extension, the extension API or both, but wanted to document the behavior in any case.

I expected some indication that something went wrong so I know not to wait or try again.

I also expected that the hover would be dismissed after some arbitrary amount of time had passed.

![screenflow](https://user-images.githubusercontent.com/133014/51009146-d8544f80-1503-11e9-8acd-02a06ff79e75.gif)

**Comment by sqs** [comment] 2019-01-14 16:18
Assigning to @lguychard to determine the best contract between extensions and Sourcegraph here. 

The current intended behavior is for the Go-to-definition button to show an error tooltip if it fails. This makes sense for ActionItems that are persistent buttons but not for ephemeral buttons like in the hover. So the UX needs some work too (therefore assigning @francisschmaltz too).

**Comment by lguychard** [comment] 2020-04-17 08:19
The issues in the gif were caused by language servers, which have now been disabled. Closing this.

**Closed by lguychard** 2020-04-17 08:19 UTC
Labels: extensions, needs-design
