### ISSUE TITLE
automated release testing

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#2392] opened 2019-02-21 02:16 UTC
# Project

In the 3.0 retrospective, we discussed the need for more automated release testing. In specific, one action item was to ensure that when we perform a release manual testing by an engineer is not needed as it is a significant waste of an engineer's time.

Thus, the goal of this project is to automate the manual testing steps required in [the release issue template](https://github.com/sourcegraph/sourcegraph/blob/master/doc/dev/release_issue_template.md#3-working-days-before-release-yyyy-mm-dd).

All other forms of automated testing fall outside the scope of this project.

## About my earlier proposal of higher-level e2e testing

Initially, I suggested we may require some form of higher-level e2e testing. For example, something not browser based which would allow us to also test that our `docker run` commands, kubernetes commands, etc. work as expected.

I have looked into this a bit, and while I do think it could be incredibly valuable for us -- it is not the easiest way to solve the problem in this project.

Since I strongly believe in this being valuable, I may persue this as a side project outside of Sourcegraph and propose its usage later. In the meantime...

## Plan

The manual testing steps can be broken down into three parts:

1. Running Docker commands
2. Running Kubernetes commands, starting/tearing down clusters, etc.
3. Testing that the actual instance is functioning (adding repos, testing search & code intel)

Note that:

- The third bullet point is mostly solved by our existing e2e tests (however, we may require updating them to fully address the requirements of the issue template).
- It is unclear to me yet whether or not running the Kubernetes commands in an actual cluter or something like minikube is best.

Given this framing, I think the obvious approach is to:

1. Write a script/program which runs [docker/kubernetes] commands to start sourcegraph versions
2. Subsequently runs our existing e2e tests in order to test that the deployment works

This can come in incremental forms, not all of which may be completed:

1. [ ] Docker support (likely to be the easiest initially).
2. [ ] Kubernetes support (harder due to needing to pick between real clusters or minikube).
3. [ ] Running this e.g. on CI automatically, so that a dev does not need to run a script to start this entire process.

In terms of actually implementing the program which runs docker/kubernetes commands, I am investigating whether or not Pulumi makes sense here or not, and otherwise considering just a Go program which does it. EDIT: likely using https://github.com/sourcegraph/deploy-k8s-helper

My personal goal is to get at least #1 usable for performing the 3.2 release. It is possible the 3.2 release may be entirely doable with this (i.e. without the third point above), but not yet clear how hard that will be so I will not commit to it yet.

**Comment by slimsag** [comment] 2019-04-05 04:49
Given other work on my plate has increased and is taking more time than originally anticipated, this is cut.

**Comment by bobheadxi** [comment] 2021-01-05 06:10
Could this be a duplicate of our 1-day release project? https://github.com/orgs/sourcegraph/projects/90

**Comment by bobheadxi** [comment] 2021-01-05 06:14
Closing, since our e2e testing is live and the testing steps have already been removed from the release process.

**Closed by bobheadxi** 2021-01-05 06:14 UTC
Labels: ops & tools & dev, stretch-goal, team/distribution
