### ISSUE TITLE
Sourcegraph.com repo results in global search does not honor fork/archived/visibility filters

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#24206] opened 2021-08-20 20:22 UTC
We have a special-case block for Sourcegraph.com in `repos.go` as follows (simplified):

```go
	if envvar.SourcegraphDotComMode() && len(includePatterns) == 0 && !query.HasTypeRepo(op.Query) && searchcontexts.IsGlobalSearchContext(searchContext) {
		searchableRepos, err = searchableRepositories(ctx, r.SearchableReposFunc, r.Zoekt, excludePatterns)
		if err != nil {
			...
		}
		// Search all indexable repos since indexed search is fast.
		if len(searchableRepos) > limit {
			limit = len(searchableRepos)
		}
	}
```

[Reference](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@869ab42f78f8015ad3ac7a09e85479be49314056/-/blob/internal/search/repos/repos.go?L126-138&subtree=true)

Immediately after that, we do:

```go
	if len(searchableRepos) > 0 {
		repos = searchableRepos
		if len(repos) > limit {
			repos = repos[:limit]
		}
	} else {
           // logic that honors archived and fork options, by querying the DB
        }
```

[Reference](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@869ab42f78f8015ad3ac7a09e85479be49314056/-/blob/internal/search/repos/repos.go?L142-161&subtree=true).

Invariants: 

`len(searchableRepos)` is only ever `> 0` when:

- we're on Sourcegraph.com
- it's a global query (context global)
- the query has no ~`file:`~ `repo:` patterns or such (includePatterns)
- doesn't specify `type:repo`

When this happens, repo options `fork`, `archived`, and `visibility` are ignored.

- [Sample query](https://sourcegraph.com/search?q=fork:only&patternType=literal) showing how `fork:only` returns all repos, which satisfies the above invariants, and does not reutnr a list of only forked repos.
- [Sample query](https://sourcegraph.com/search?q=fork:only+type:repo&patternType=literal) where adding `type:repo` to bypass the above does show only forked repos. You can also just add `file:test`.

- There is evidence of another issue here. I'm quite confident, being familiar with our code, that our logic will honor the flags with patterns like `foo fork:only`, when searching file contents. This because (global) file content searches are processed separately by zoekt logic, and works correctly. This is because we skip any DB lookups entirely for patterns we actually search via Zoekt, and the Zoekt logic [does still honor the fork/archived values](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@869ab42f78f8015ad3ac7a09e85479be49314056/-/blob/internal/search/zoekt/indexed_search.go?L416-420&subtree=true) so this is OK. However! When we have a pattern like `foo fork:only`, we will do a search for all result types by default (content, file, and repo searches). The repo search will still trigger the above logic, and you can see it with a query like [`fork:only smicallef/spiderfoot select:repo`](https://sourcegraph.com/search?q=fork:only+smicallef/spiderfoot+select:repo&patternType=literal) when the pattern is matched against `smicallef/spiderfoot` the repo, which is not a fork. If we relax that query a bit to just be `spiderfoot`, you can run a couple of searches and hard refresh--and you'll see that sometimes we show forked repos, and sometimes we don't, because of the concurrent queries. [fork:only spiderfoot select:repo](https://sourcegraph.com/search?q=fork:only+spiderfoot+select:repo&patternType=literal). **TL;DR about this part:** for global searches with patterns, we process repo results correctly when we search inside contents. But, we also do a search for repos with the above logic concurrently, and may show incorrect "repo matches" when the query contains just a pattern as well. I.e., the above bug affects _all_ potential searches that don't have a `file:` filter, _not only pure repo searches_. We are just lucky when file content matches return first in fork-only repos from the Zoekt query, and when those results happen to be the only one that we see.

This behavior seems to be live since 2 months-ish ago, introduced by https://github.com/sourcegraph/sourcegraph/pull/22344.

Solution: I'm not sure how to fix this. Naively deleting the special-casing block will probably fix the root issue but I'm not sure that's the right call, and I don't think I'm the right person to make that call. It seems like we want to optimize for this `searchableRepos` case but then a fix that post-filters (?) to optimize for Sourcegraph.com. Looking at the searchableRepos data type though, I don't see fields that expose labels for fork/archived/visibility, so maybe a DB look up is required.

**Comment by keegancsmith** [comment] 2021-08-24 14:30
I can send out a fix, but would like @stefanhengl's advice here on the direction given he has done a lot of hard work around global queries + repos. In fact diving into this I have more questions than answers. @stefanhengl can we chat tomorrow and I'll write up the notes here.

Ideally I think we can remove this block and just not call resolveRepositories in global content search. This would mean we don't have the repo count anymore / we could cache it.

However, we probably need a more incremental fix. This is actually quite tricky, and makes me realise why Stefan chatted to me so much about keeping sets of repos with different states :) I have an idea for a minimal fix here which keeps the cache while introducing a bitfield per repo so we can do filtering. But I want to know how easy it is to just remove resolveRepositories since that is better than worrying about perf, since we just avoid the work in the common case.

**Comment by keegancsmith** [comment] 2021-11-29 07:29
I believe @tsenart fixed this with his work on repo resolution. I tried both above queries and I can no longer reproduce. The description also describes code which has been heavily changed with @tsenart's work. Closing out.

**Closed by keegancsmith** 2021-11-29 07:29 UTC
Labels: bug, team/search-core
