### ISSUE TITLE
zoekt-indexserver: Work out wobble (TM) in num_indexed graph

### ISSUE THREAD

**Issue by jjeffwarner** [sourcegraph/sourcegraph#29746] opened 2022-01-14 14:50 UTC
Currently running a gap of 2,000 repos on indexed 
https://sourcegraph.com/-/debug/grafana/d/zoekt-indexserver/zoekt-index-server?viewPanel=100000&orgId=1&from=now-30m&to=now

**Comment by keegancsmith** [comment] 2022-02-08 06:20
@stefanhengl moved this to in progress. I believe you have root caused this and it had something to do with compound shards and deleting of them. Not sure what your next steps are.

**Comment by stefanhengl** [comment] 2022-04-11 07:37
Yes we can close this. The wobble was due to deleting too small compound shards. [We implemented shard explosion](https://github.com/sourcegraph/zoekt/pull/271) which solved the issue.

**Closed by stefanhengl** 2022-04-11 07:37 UTC
Labels: team/search-core
