### ISSUE TITLE
Diffs for files that have been deleted do not have hover capabilities

### ISSUE THREAD

**Issue by christinaforney** [sourcegraph/sourcegraph#4088] opened 2019-05-17 00:43 UTC
#### Steps to reproduce:

1. Open up a PR that has a removed file (e.g https://github.com/sourcegraph/sourcegraph/pull/4031/files) 
2. Expand the deleted file (hidden by GitHub by default)
3. Hover does not show any results

![image](https://user-images.githubusercontent.com/1559622/57895713-f4ddfc80-7801-11e9-8126-1ba7fb55dd66.png)

Stacktrace:
```
Error: document not found: git://github.com/sourcegraph/sourcegraph?23f28cdb6e3b34488e81411ae5014164f144f480#cmd/repo-updater/repos/internal_api.go
    at v.get (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/0b60b415-4c2d-4d19-a6f2-db483f20a33e:1)
    at v.<anonymous> (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/0b60b415-4c2d-4d19-a6f2-db483f20a33e:1)
    at Generator.next (<anonymous>)
    at i (blob:chrome-extension://dgjhfomjieaadpoljlnidmbgkdffpack/0b60b415-4c2d-4d19-a6f2-db483f20a33e:1)
```

#### Expected behavior:
Hover works on deleted files

**Comment by slimsag** [comment] 2019-05-17 00:53
We support hover on removed lines so I am pretty sure we support hover on deleted files, indicating this may be a major regression. Tagging as release-blocker for @felixfbecker / @lguychard to confirm.

**Comment by felixfbecker** [comment] 2019-05-17 01:53
@slimsag deleted lines and deleted files are very different and I can't think of a code change that could have caused this. Given the browser extension is not coupled to our release cycle I don't think it's a release blocker.

**Comment by lguychard** [comment] 2019-05-17 16:14
This is not a regression, it's due to #3107 - `FileInfo` always assumes that the file exists at the head revision, an attempt at fetching the file then errors.

In addition, the error is swallowed by `fetchFileContents()` instead of being correctly reported, causing the `document not found` error downstream. The initial error is:

```
Error while fetching head file AggregateError: git ls-tree cmd/repo-updater/repos/internal_api.go: file does not exist
    at createAggregateError (chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:112861:61)
    at MapSubscriber.project (chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:113656:89)
    at MapSubscriber._next (chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:73516:29)
    at MapSubscriber.Subscriber.next (chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:66558:12)
    at SwitchMapSubscriber.notifyNext (chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:76332:22)
    at InnerSubscriber._next (chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:65612:17)
    at InnerSubscriber.Subscriber.next (chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:66558:12)
    at chrome-extension://bmfbcejdknlknpncfpeloejonjoledha/js/inject.bundle.js:79951:20
```

@felixfbecker let's put refactoring `FileInfo` at the top of our next refactoring priorities. It goes hand-in-hand with removing all the error swallowing in `fetchBlobContentLines()` and `fetchFileContents()` (we currently "need" it because so many attempts at fetching files shouldn't even happen in the first place).

**Comment by lguychard** [comment] 2020-10-26 14:17
@marekweb was this fixed by your work on FileInfo from a few months ago?

**Comment by marekweb** [comment] 2020-10-26 15:20
I can find out and confirm.

**Comment by erzhtor** [comment] 2021-12-03 12:38
Hey, I could not reproduce it, probably was fixed already.
<details>

![image](https://user-images.githubusercontent.com/6717049/144603841-04053c0a-bc69-43ee-8887-4e3b055ef566.png)

</details>

Please, let me know if you still run into this issue - we can re-open the issue in that case.

**Closed by erzhtor** 2021-12-03 12:38 UTC
Labels: bug, browser-extension, github, team/extensibility
