### ISSUE TITLE
Excluded GitLab repositories are synced 

### ISSUE THREAD

**Issue by christinelovett** [sourcegraph/sourcegraph#15763] opened 2020-11-13 18:51 UTC
3.21.2
Kubernetes

https://app.hubspot.com/contacts/2762526/company/578600789

User is using "exclude" in GitLab config and the named repositories are still visible in Repository Status and when searching. They have tried both by name/group and by ID. Example of their name/group format:

```json
"exclude": [ 
	{ 
		"name": "group/subdir1/subdir2/subdir3/repo" 
	} 
]
```

**Comment by christinelovett** [comment] 2020-11-13 19:33
```
{ 

"projectQuery": [ 

"?membership=false" 

], 

"token": "redacted", 

"url": "redacted", 

"repositoryPathPattern": "{pathWithNamespace}", 

"exclude": [ 

{ 

"name": "<group>/<subdir1>/<subdir2>/<subdir3>/<repo>" 

} 

], 

"nameTransformations": [ 

{ 

"regex": "
.d/", 

"replacement": "/" 

}, 

{ 

"regex": "-git$", 

"replacement": "" 

} 

] 

} 
```

**Comment by unknwon** [comment] 2020-11-16 09:18
Haven't checked but one thing come to mind is that `nameTransformations` might have invalidated the `exclude.name` (depends on which one happens first in the code).

**Comment by leahnp** [comment] 2020-11-16 18:41
is there something I can do to test if this is happening?

**Comment by dadlerj** [comment] 2020-11-17 15:23
https://app.hubspot.com/contacts/2762526/company/1686989427 is actually seeing something _very_ similar—also with GitLab. See https://sourcegraph.slack.com/archives/CV5KX7T70/p1603354333027000 for discussion.

**Comment by leahnp** [comment] 2020-11-17 16:25
Also @unknwon I tried the transformed path and un-transformed, neither of which seemed to exclude the repo.

**Comment by leahnp** [comment] 2020-11-17 16:44
@dadlerj I can't seem to sign into either of those platforms, I will send a note to Christine to get an invite to the Sourcegraph slack channel.

**Comment by dadlerj** [comment] 2020-11-17 16:47
Sorry @leahnp, yes, those are actually for our internal team's diagnostics because they reference a different user/customer! No need for you to get into those for now.

**Comment by asdine** [comment] 2020-11-24 13:26
@alan The `toml-syntax-highlighting` repositories in the table you provided have different external ids, could it be that you created one, deleted it then recreated it? (on Gitlab)

@christinelovett do you have information on how many external services are configured on that instance?
For example, if there are multiple ones that reference the same repo, that might explain why it's still appearing in the list.

I tried to reproduce locally with one single Gitlab external service but everything seems to be working fine. When modifying the configuration though, the synchronization can take some times (even after being redirected to the repository status page), it will depend on the number of repositories synchronized by this external service config. If that number is very large, it can take several minutes.
Do you know if the excluded repository is still listed several minutes / hours later?

If that's the case, can the user run this query and give us the result?

```sql
SELECT esr.repo_id, esr.external_service_id
FROM external_service_repos esr
JOIN repo r ON esr.repo_id = r.id
where r.name = '<name of the repo that should be excluded>';
```

Also, any `repo-updater` logs would help 🙏🏼

**Comment by asdine** [comment] 2020-11-30 15:42
@christinelovett did you have time to take a look?

**Comment by christinelovett** [comment] 2020-11-30 15:51
Hey @asdine I _just_ followed up with the customer :-) Will send an update ASAP!

**Comment by asdine** [comment] 2020-11-30 15:54
Thanks!

**Comment by christinelovett** [comment] 2020-12-01 00:14
hey @asdine! WRT external services - does this refer to the different code host connections (like multiple instances of gitlab) or db services referenced here: https://docs.sourcegraph.com/admin/external_services

**Comment by tsenart** [comment] 2020-12-01 12:02
@christinelovett: It refers to code host connections, sorry for the confusion!

**Comment by christinelovett** [comment] 2020-12-01 14:19
Thanks @tsenart :-)

**Comment by christinelovett** [comment] 2020-12-01 22:14
Hey @asdine here is the response from the customer:

Running select uri, count(*) as count from repo group by uri; most repos "count" is 1, I saw a few repos with "count" 2, but from a quick manual check it seemed a very small percentage (and none of them were repos I tried to exclude).

**Do you have information on how many external services are configured on that instance? We only have one GitLab cluster configured for Sourcegraph.**

I tried to reproduce locally with one single Gitlab external service but everything seems to be working fine. When modifying the configuration though, the synchronization can take some times (even after being redirected to the repository status page), it will depend on the number of repositories synchronized by this external service config. If that number is very large, it can take several minutes.

I did a test and excluded a repo (two ways, one with the .d and -git extensions and one with, so my config looked like:

{

  "projectQuery": [

    "?membership=false"

  ],

  "token": "<redacted>",

  "url": "<redacted>",

  "repositoryPathPattern": "{pathWithNamespace}",

  "exclude": [

        {

          "name": "group/subdir1.d/subdir2.d/subdir3.d/repo-git"

        },

        {

          "name": "group/subdir1/subdir2/subdir3/repo"

        }

   ],

  "nameTransformations": [

    {

      "regex": "\\.d/",

      "replacement": "/"

    },

    {

      "regex": "-git$",

      "replacement": ""

    }

  ]

}

 

**Do you know if the excluded repository is still listed several minutes / hours later?**

I applied the above config at night and checked the repo in the morning (~10 hours later) and it still displayed as usual.

 
**If that's the case, can the user run this query and give us the result?**

sg=# SELECT esr.repo_id, esr.external_service_id

sg-# FROM external_service_repos esr

sg-# JOIN repo r ON esr.repo_id = r.id

sg-# where r.name = 'group/subdir1/subdir2/subdir3/repo';

 

repo_id | external_service_id

---------+---------------------

   <redacted> |                   1

(1 row)

 

**Also, any repo-updater logs would help**

There are not a ton of unique logs, but here is an eror and warning I am seeing multiple times in the logs. If there is anything specific I should look for let me know.

 

t=2020-12-01T19:39:12+0000 lvl=eror msg=source.list-repos error="1 error occurred:\n\t* error listing GitLab projects: url=\"https://<redacted>/api/v4/projects?membership=false&order_by=created_at&owned=false&page=251&per_page=100&repository_checksum_failed=false&simple=false&sort=desc&starred=false&statistics=false&wiki_checksum_failed=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false\": unexpected response from GitLab API (https://<redacted>/api/v4/projects?membership=false&order_by=created_at&owned=false&page=251&per_page=100&repository_checksum_failed=false&simple=false&sort=desc&starred=false&statistics=false&wiki_checksum_failed=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false): HTTP error status 500\n\n"

**Comment by christinelovett** [comment] 2020-12-08 21:41
Hey @asdine following up on this item, the customer has 22k 'deleted' repos. The plan was to use the exclude feature and apply a new GitLab config each night via configMap, considering how large this file would be - does this raise any flags? Can we handle that large number?

**Comment by asdine** [comment] 2020-12-09 12:54
Hi @christinelovett! 

> the customer has 22k 'deleted' repos. The plan was to use the exclude feature and apply a new GitLab config each night via configMap, considering how large this file would be - does this raise any flags? Can we handle that large number?

I don't think the number of repositories is a problem, but looking at the error posted in the previous message we can see that the api url is wrong:

```
https:///api/v4/projects?...
```

It should be

```
https://<url of the gitlab instance here>/api/v4/projects?...
```

That would explain why the synchronization failed: The synchronizer failed to call the Gitlab API and thus didn't change anything to the set of repositories.
If that's the case, either there is a bug that's not using the url correctly, or the configuration simply doesn't contain the url (perhaps a typo on the configuration?).

I'm not familiar with configMap, so I'm gonna ask some basic questions to make sure we didn't miss anything:

- Is the configuration provided in the previous comments the one generated by configMap (minus sensitive information), is it handwritten, or is it the template version ? 
- Did the customer try with a handwritten config and experience the same bug?

**Comment by christinelovett** [comment] 2020-12-09 14:38
Thank you @asdine! Great find. I will confirm with them this AM whether or not it's a config user error. I'll get back to you re: configMap questions.

**Comment by asdine** [comment] 2020-12-18 12:48
After discussion, it turns out the configuration was trying to exclude sub directories of a monorepo, which is not supported.
However, when we tried to exclude regular Gitlab projects from a group, they were still sync'ed.
I still cannot reproduce the bug though, the only difference with the customer setup being that I tried with Gitlab.com while they tried with a custom Gitlab instance.

**Comment by asdine** [comment] 2020-12-18 15:03
We can close this one as everything works as intended:
- The customer was trying to filter subdirectories of a monorepo using the Gitlab exclude external service setting, which is not supported
- The customer then tried to exclude regular repositories but since the external service took some time to synchronize, the excluded repositories didn't immediately disappear, which is misleading. This will be fixed by the UI work the Cloud team is working on.

@christinelovett I'm closing this, please feel free to reopen if needed.

**Closed by asdine** 2020-12-18 15:03 UTC
Labels: ce/p2, customer, estimate/1.5d, team/cloud
