### ISSUE TITLE
GLOBAL_SETTINGS_FILE on Sourcegraph.com not auto-reloaded

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#14263] opened 2020-09-29 00:03 UTC
https://sourcegraph.slack.com/archives/CJX299FGE/p1601337726070300?thread_ts=1601337326.069600&cid=CJX299FGE

If @ggilmore's hypothesis is right about why it wasn't reloaded (that the file is invalid per the JSON Schema), then IMO that violates the user expectation. It should still be reloaded and applied, and a warning should be shown in the UI as it would be if the user manually entered invalid schema in the web UI.

**Comment by keegancsmith** [comment] 2020-09-29 09:56
Duplicate of #14019

**Closed by keegancsmith** 2020-09-29 09:56 UTC
