### ISSUE TITLE
Browser extension messes up highlight.js color schemes on other websites

### ISSUE THREAD

**Issue by h1nk** [sourcegraph/sourcegraph#5889] opened 2019-10-07 08:08 UTC
#### Steps to reproduce:

1. Install the [browser extension](https://docs.sourcegraph.com/integration/browser_extension).
2. Visit https://partner.steamgames.com/doc/webapi_overview#2

#### Expected behavior:
Preserve original highlight.js color scheme on website pages unrelated to sourcegraph.

![image](https://user-images.githubusercontent.com/12993584/66294614-e8556000-e8d8-11e9-9693-5c53b7e85c8c.png)

#### Actual behavior:
Browser extension injects a stylesheet that clobbers the page's original CSS:
```diff
+ /* style.bundle.css */
+ .hljs-attribute, .hljs-name, .hljs-tag {
+     color: navy;
+     font-weight: 400;
+ }
- /* railscasts.css */
- .hljs-tag, .hljs-name {
-     color: #e8bf6a;
- }
```
![image](https://user-images.githubusercontent.com/12993584/66294552-c2c85680-e8d8-11e9-8bfe-0a96c522d4b6.png)

**Comment by christinaforney** [comment] 2019-10-07 17:00
Hi @h1nk - thanks for reporting! I was able to reproduce this by granting the Sourcegraph extension access to steamgames.com. Is there a reason you granted access to that site in the first place? Sourcegraph should [only apply decorations to sites it has permissions on](https://docs.sourcegraph.com/integration/browser_extension#enabling-the-browser-extension-on-your-code-host), and it is designed to interact with [certain code hosts](https://docs.sourcegraph.com/integration).

I was going to tell you to just go into the extension settings and disable this individual site, but something appears to be broken and I have asked the @sourcegraph/web team to help take a look:

![image](https://user-images.githubusercontent.com/1559622/66332257-2c506100-e8e9-11e9-8cff-f9e2cb2d2943.png)

You _can_ toggle the top level "Automatically allow access on the following sites" and it will reduce the list to only github.com and sourcegraph.com.

Let us know if you have any questions!

**Comment by felixfbecker** [comment] 2019-10-07 17:41
This would be fixed by https://github.com/sourcegraph/sourcegraph/issues/2358

**Comment by bm-stschneider** [comment] 2019-10-18 05:56
just to add another case, pages with hljs and dark themed code snippets end up having black color on black ground for keywords highlighting making them pretty much unreadable.

**Comment by Sushisource** [comment] 2021-04-16 01:26
I recently ran into this. Installed the extension, which is great, love using it with GitHub, but I don't see any option to configure what sites it is activated for any longer like in the above screenshot (at least in Firefox). There's not much in the way of config at all. The extension seems to mangle any hljs anywhere it finds it, even if it doesn't actually produce any useful functionality to go along with it. EX: The entire Rust Book https://doc.rust-lang.org/book/ch01-02-hello-world.html

Wasn't fun to figure this out the hard way with the browser inspector, and even turning the extension off via it's own toggle doesn't solve the problem. Unfortunately I'll probably have to stop using the extension until it's fixed.

Out of curiosity, why inject CSS with such a broad brush like this, overriding `color` for *all* `.hljs` classes? Seems a bit extreme. Why not just leave the styling as is, overriding styling as necessary on hover, etc? If the intent was to let me know via coloring what I would be able to click or not, that was completely lost on me since syntax coloration is different all over the place on the web.

**Comment by taras-yemets** [comment] 2022-05-24 10:44
This issue was fixed in https://github.com/sourcegraph/sourcegraph/pull/18889.

Previously, we were injecting our CSS filter at the top level but since it broke websites we've decided to only inject when visiting the "sourcegraph url". The change has shipped for all browsers but a portion of firefox users was not able to get this update. The reason why they were not able to get it is that around the same time we've moved from releasing & hosting our own extensions to firefox add-on marketplace. We were previously packaging and shipping the extension ourselves and it was a painful process. We've run a small CTA campaign notifying users to upgrade the extension themselves (by uninstalling and re-installing from the marketplace) but a small percentage of users probably have missed the CTA. Unfortunately there's no easy way to migrate these users to the new extension. On the bright side only a small percentage of users are affected by this - you have to be an enterprise Sourcegraph user for (6 mo+) and a Firefox user.

**Closed by taras-yemets** 2022-05-24 10:44 UTC
Labels: browser-extension, team/integrations
