### ISSUE TITLE
SSBC-EM2.4: User workflows for create/edit are modeled

### ISSUE THREAD

**Issue by courier-new** [sourcegraph/sourcegraph#26796] opened 2021-10-28 17:19 UTC
#### Outcome

- "Empty" batch change model from [RFC](https://docs.google.com/document/d/1In0aivqY0CJA4FFvnnp47R8RaWDWKQkUYa9LlvR83FE/edit#) is implemented
- Users can get back to their unapplied batch specs
- User can update an existing batch change from SSBC UI

#### Scope

- [ ] Implement empty batch change model (**`~2d`**)
  - [x] Make `last_applied_at` nullable in DB (**`<0.5d`**)
  - [x] Implement resolver for new mutation `createEmptyBatchChange` (**`1d`**)
  - [ ] Update docs to better draw analogy between Batch Changes and GitHub repos (**`0.5d`**)
- [x] Change default access to batch changes in connection resolver to owner/admin-only for shallow batch changes (**`~1d`**)
  -  _Comment Thorsten: We need to check whether user is site-admin, and if not we need to filter our batch changes that are (a) shallow and (b) have a different author_
- [ ] Updated "Create" flow (**`~2d`**)
  - [x] Require (unique) name and namespace to create a new batch change, use `createEmptyBatchChange` (**`0.5d`**)
  - [ ] Add basic UI to set the batch change name and namespace before SSBC editor view (**`0.5d`**)
  - [x] ~Strip `name` from the batch spec YAML shown from the client UI from GraphQL layer (automatically insert for backend/DB) (**`0.5d`**)~
    - _(Punting this to later because it'll require AST parsing and manipulation on the backend to safely remove `name` when it's requested from the frontend, which blows the estimate of `0.5d` by quite a bit)_
  - [ ] Validate that if `name` is entered in SSBC editor, it matches the batch change name, otherwise show an error (**`0.5d`**)
- [ ] Updated "Edit" flow (**`~2d`**)
  - [ ] Add "Edit" button to get back to editor UI for a batch change from its details page (**`0.5d`**)
  - [ ] Add basic UI to enable updating the batch change name with `moveBatchChange` (**`0.5d`**)
  - [x] Update `createBatchSpecFromRaw` mutation to take required arg batch change id (**`<0.5d`**)
  - [x] Use `createBatchSpecFromRaw` to create a new batch spec for an existing batch change (**`<0.5d`**)

**Comment by mrnugget** [comment] 2021-11-01 14:13
Just because I ran into this and the other ticket just now: is this one here a duplicate of https://github.com/sourcegraph/sourcegraph/issues/23599?

**Comment by courier-new** [comment] 2021-11-01 17:49
The other one was just for the RFC, and this one's the actual implementation and its effects! We normally keep those as separate issues, right? I could clarify in the description of the other that it's "done" when the RFC is done.

**Comment by mrnugget** [comment] 2021-11-02 08:59
> The other one was just for the RFC, and this one's the actual implementation and its effects! We normally keep those as separate issues, right?

Not sure to be honest :smile: Either way it's fine. I think the other has the clearer title though :)

**Comment by mrnugget** [comment] 2021-12-10 10:11
@courier-new (and cc @eseliger) while looking at your other two PRs, it just occurred to me that we also need to update these resolver methods (and possibly the graphql schema) because they might be null now:

https://github.com/sourcegraph/sourcegraph/blob/d3321e7cae74fba427052938f220efe6ed8d4b3b/enterprise/cmd/frontend/internal/batches/resolvers/batch_change.go#L61-L79

And we also need to update this check here:

https://github.com/sourcegraph/sourcegraph/blob/d3321e7cae74fba427052938f220efe6ed8d4b3b/enterprise/internal/batches/service/service.go#L1224-L1230

And the duplicate of that check that I added in #28786. I can update the checks in #28786.

**Closed** 2021-12-16 00:29 UTC
Labels: estimate/5d, team/batchers, server-side
