### ISSUE TITLE
Feature request: call graph support in code navigation

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/sourcegraph#10499] opened 2020-05-08 15:23 UTC
We'd like to be able to show a call graph of projects, so that it's easy to navigate to and visualize the callers & callees of methods.

No work has been done to validate the feasibility of supporting this via basic code intelligence, but it seems possible in some scenarios.

Re precise code intelligence, there is starting to be some momentum around this feature in the LSP world. [Here](https://github.com/theia-ide/typescript-language-server/blob/2f1ef7286404e9c8f5e41480c6996eef6cffde3d/server/src/call-hierarchy.lsp.proposed.ts) is an example implementation using an unofficial interface. When the feature matures a bit more, we could consider adding it as a custom extension to the LSIF spec, as I don't think the official version is going to receive updates any time soon. This will require work in all of our indexers, and again calls out the importance of leveraging community work on language indexing to ease our language support burden.

High level steps to support:
- [ ] UI to expose this feature
- [ ] Basic code intel support for this feature
- [ ] Backend support for processing LSIF indexes containing this feature
- [ ] Add this feature to our indexers

Go support could be a project with ~a quarterly timeline, given we probably wouldn't want to dedicate anyone to it full time.

**Comment by felixfbecker** [comment] 2020-05-08 15:29
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/2882?

**Comment by gbrik** [comment] 2020-05-08 15:37
yup, I'll move this comment over to there

**Comment by felixfbecker** [comment] 2020-07-21 07:09
Just stumbled across this again, should this be closed?

**Comment by efritz** [comment] 2020-07-27 19:06
Yup!

**Closed by efritz** 2020-07-27 19:06 UTC
Labels: future-vision, team/code-intelligence
