### ISSUE TITLE
[DESIGN] Revamp the QuickStart tab with SSBC in mind

### ISSUE THREAD

**Issue by danielmarquespt** [sourcegraph/sourcegraph#43824] opened 2022-11-02 19:47 UTC
As of today, most of the information in the quickstart tab refers mostly to the CLI path of batch changes (the animation in the header section, links to docs, etc)

This page needs an update to reflect the SSBC when it is available (executors are setup for eg)

**Comment by courier-new** [comment] 2022-11-03 03:59
I think this is a duplicate of https://github.com/sourcegraph/sourcegraph/issues/23507, but given that you've written more than that ticket ever had on it, maybe let's keep this new one and close that one. 😛

**Closed** 2022-11-03 16:14 UTC
Labels: needs-design, team/batchers, server-side, ssbc-ga
