### ISSUE TITLE
Consider removing ambiguous HEAD support in the future (once k8s.sgdev.org is fixed)

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#4619] opened 2019-06-20 05:52 UTC
Support for handling ambiguous HEAD revisions (where a very bad repository contains BOTH a `HEAD` branch and a `remotes/origin/HEAD -> master` reference) was added in https://github.com/sourcegraph/sourcegraph/pull/4617 primarily for testing the feature on k8s.sgdev.org, and we should consider removing it in the future.

See https://sourcegraph.slack.com/archives/CHEKCRWKV/p1561004415100200?thread_ts=1560992541.075000&cid=CHEKCRWKV for context.

**Comment by keegancsmith** [comment] 2019-09-25 11:47
The change is incorrect, so will send out a revert PR. In the meantime what can we do instead to ignore bad repos rather? Context on why it is incorrect https://github.com/sourcegraph/sourcegraph/pull/4617/files#r328075059

**Comment by keegancsmith** [comment] 2019-09-25 11:52
Ok I see we only resolved for the use of commitafter. Nevermind then, this is fine to do.

@kzh can you make a decision on whether to revert the PR or add tests. If you do want to add tests, please close this issue and open the other related issue and do it in 3.9.

**Comment by keegancsmith** [comment] 2019-09-25 12:12
I will revert this change once I have fixed https://github.com/sourcegraph/sourcegraph/issues/5291

HEAD being a ref is a much more general problem and likely pops up as bugs in lots of features. So its better to solve the root problem.

**Comment by tsenart** [comment] 2019-10-14 14:18
Dear all,

This is your release captain speaking. 🚂🚂🚂

Branch cut for the **3.9 release is scheduled for tomorrow** at 10:00 CEST.

Is this issue / PR going to make it in time? Please change the milestone accordingly.
When in doubt, reach out!

Thank you

**Comment by keegancsmith** [comment] 2019-10-14 14:37
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/5291

Fixed by https://github.com/sourcegraph/sourcegraph/pull/5892

**Closed by keegancsmith** 2019-10-14 14:37 UTC
Labels: search
