### ISSUE TITLE
Duplicated hover tips on pull request

### ISSUE THREAD

**Issue by unknwon** [sourcegraph/sourcegraph#8629] opened 2020-02-26 23:26 UTC
Example PR: https://github.com/sourcegraph/sourcegraph/pull/8624/files

![image](https://user-images.githubusercontent.com/2946214/75397546-18f27080-5932-11ea-825c-24992b311b9e.png)

I verified it does not happen in other places (GitHub file view, sourcegraph.com file view) for the same identifier.

<details>
<summary>Sometimes, it could also go crazy like</summary>

![image](https://user-images.githubusercontent.com/2946214/75397630-50611d00-5932-11ea-9c32-11ccfa2ff855.png)

</details>

My sourcegraph.com account settings:

```json
{
  // "codeIntel.lsif": false,
  "go.accessToken": <REDACTED>,
  "typescript.accessToken": <REDACTED>,
  "git.blame.lineDecorations": false,
  "go.serverUrl": "wss://go.sourcegraph.com",
  "codecov.decorations.lineHitCounts": false,
  "discussions.decorations.inline": false,
  "discussions.hideDiscussionsButton": true,
  "codecov.decorations.lineCoverage": false,
  "codeHost.useNativeTooltips": false,
  "go.showExternalReferences": true,
  "panel.locations.groupByFile": false,
  "search.contextLines": 3,
  "codeOwnership.hide": true
}
```

**Comment by felixfbecker** [comment] 2020-03-06 20:37
This is a duplicate of #8602 I think

**Closed by felixfbecker** 2020-03-06 20:37 UTC
