### ISSUE TITLE
JetBrains: customize autocomplete color does not work in some cases with IntelliJ Ultimate EAP

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#56808] opened 2023-09-20 00:13 UTC

**Comment by olafurpg** [comment] 2023-09-21 10:32
De-prioritizing this issue to P3. @Sa1to managed to track down the root cause, this only happens with alt-backslash (not automatically triggered suggestions) AND when the user has installed Copilot alongside Cody. The custom color setting works as expected with automatically triggered completions and/or when Copilot is not installed.

**Comment by olafurpg** [comment] 2023-09-21 10:43
Closing since it's working as intended. The custom color was not picked up because the completion from alt-backslash was coming from Copilot (which understandably doesn't use the custom color setting from Cody).

**Closed by olafurpg** 2023-09-21 10:43 UTC
