### ISSUE TITLE
Nicer sign-out page

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/sourcegraph#2290] opened 2019-02-14 01:18 UTC
The sign-out experience could be improved by redirecting to `/search`/ `/start` or the `/sign-in` page.

https://sourcegraph.com/-/sign-out

![screen shot 2019-02-13 at 5 15 29 pm](https://user-images.githubusercontent.com/133014/52755536-24872980-2fb3-11e9-98fc-f800aaec48bc.png)

**Comment by sqs** [comment] 2019-02-14 02:33
The purpose of this (terrible looking) page is to provide the link to sign out of their auth providers too. We need to preserve that capability somehow. Just redirecting wouldn’t do it.

**Comment by sqs** [comment] 2019-02-14 04:36
dupe of #2031

**Closed by sqs** 2019-02-14 04:36 UTC
Labels: auth, feature-request
