### ISSUE TITLE
Major OSS regressions: saved searches, search scopes, user profiles, HTTP header auth all broken

### ISSUE THREAD

**Issue by svrx** [sourcegraph/sourcegraph#11990] opened 2020-07-07 10:31 UTC
#### Question description

What can be causing the problem described bellow?

#### Is your question related to a problem? If so, please describe or link to another issue.

I'm having this issue with my single node OSS test system where non-admin users can't search and get gateway timeouts (504). For admin users the access and search is working fast and reliably for the same queries.

For this reason I'm confident this is not an hardware or installation related problem, but rather some nuance caused by some configuration on Sourcegraph image side. 
Can someone give me at least some quick pointers of what can cause this behavior?

**Comment by dadlerj** [comment] 2020-07-07 14:14
Hey @svrx , have you enabled repository permissions by any chance: https://docs.sourcegraph.com/admin/repo/permissions? It's not available in the OSS code, but if you're using the single Docker image download, you would have access to it. 

The error you are reporting (users see search timeouts, admins don't) makes it sound like this may be the issue, as admins bypass the permissions check. If so, one potential fix would be to set the following in your site configuration to enable background permissions fetching instead of synchronous fetching (see https://docs.sourcegraph.com/admin/repo/permissions#background-permissions-syncing for more details):

```
"permissions.backgroundSync": {
	"enabled": true
}
```

**Comment by svrx** [comment] 2020-07-09 22:10
Thanks for you comment. I've one not configuration to enable user permissions. 
I've built the image that I'm using from the release tag on GitHub with `./dev/dev-sourcegraph-server.sh`.

Your suggestion of setting  `"permissions.backgroundSync"` to `true` made no difference.
The repositories I'm using with this instance are AWS Code Commit.

Any other setting that could be relevant in the scenario?

**Comment by slimsag** [comment] 2020-07-10 08:26
What does the gateway timeout error look like? Is there a port etc. mentioned with it?

What do the container logs looks like (with any secrets redacted, or you can fwd them to stephen@sourcegraph.com)

**Comment by svrx** [comment] 2020-07-10 12:57
This is what it looks like, nginx times out after 1 minute as for admins it returns straight away.
![image](https://user-images.githubusercontent.com/713996/87154504-4290b080-c2b1-11ea-89d0-5ce90c0dff63.png)

The only related logs I can find are from nginx about the timeout.

> 2:47:02                             nginx | 2020/07/10 12:47:02 [error] 3936642#3936642: *5203 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.52.3.188, server: [hostname], request: "POST /.api/graphql?ManyReposWarning HTTP/1.1", upstream: "http://127.0.0.1:8080/.api/graphql?ManyReposWarning", host: "brick.idev.spencerstuart.com:7443", referrer: "https://[hostname]:7443/search?q=IReferenceCategory&patternType=literal"
> 12:47:02                             nginx | 2020/07/10 12:47:02 [error] 3936642#3936642: *5200 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.52.3.188, server: [hostname], request: "POST /.api/graphql?Search HTTP/1.1", upstream: "http://127.0.0.1:8080/.api/graphql?Search", host: "brick.idev.spencerstuart.com:7443", referrer: "https://[hostname]:7443/search?q=IReferenceCategory&patternType=literal"

What info would be relevant?

**Comment by svrx** [comment] 2020-07-13 11:37
Let me know what other information you'd need me to collect to help narrowing down on the source of the issue.
My configuration is relatively vanilla, nothing special with the setup, you should be able to easily reproduce the issue.

From my side any pointer into which area of the code can potentially be causing this behavior would be hugely appreciated.
From quick look at code, seems like there is a list of users allowed to access which repository in DB, which is not available to OSS instance. 
There is some middle-ware or provider somewhere potentially expecting those. Any suspects or suggestions?

**Comment by svrx** [comment] 2020-07-14 12:03
Found the potential solution, still have to test it though.
Looks like the same issue was already discussed at #3847, but fix seems to only have been added to 3.16.

Going to back-port the fix to 3.15, as 3.16 started to reduce features available for OSS users. :|

**Comment by dadlerj** [comment] 2020-07-14 15:30
Thanks for the update @svrx , and sorry we didn't point to that issue sooner. Just curious, what features are missing in 3.16+ that you'd like to have in OSS?

**Comment by svrx** [comment] 2020-07-15 01:52
I can confirm that applying the fix referred has fixed the issue.

In relation to feature lost on 3.16+ there are several, due to new enterprise focused authorization.
First things I've stumbled on were:
- Saved Searches
- Search Scopes
- Entire User Profile Area (no that there is much in there, but basic profile self-service management is lost) 
- HTTP Header Authorization (removed a while ago, but also used to be OSS)

I love the product, and I think it's going in the right direction. 
At the same time this trends towards taking things away from the OSS version is very annoying and limits involvement from the community in the project.

**Comment by slimsag** [comment] 2020-07-15 01:55
hey @svrx I'm going to reopen this for tracking the regressions you mentioned - to be clear the four things you mentioned are, as far as I know (and I've worked here for 5yrs) NOT intentionally removed from the OSS version. We haven't given this enough love and it seems we've had some really bad regressions in the OSS version recently :/

**Comment by bobheadxi** [comment] 2020-07-15 02:01
related: #12191

**Comment by svrx** [comment] 2020-07-15 02:08
Appreciate the proactive attitude. 
Another example is with basic SSO providers, which seemed to have been on the OSS version at some point, if I got the code correctly. 
At the same time I'm relatively new to the code base and may have missed some relevant nuances.

**Comment by dadlerj** [comment] 2020-07-15 06:14
Sorry about all of this @svrx ! @slimsag is correct, none of those features were intentionally removed... This is unfortunately just due to a recent lack of regression testing in the OSS version.

SSO, however, actually is intentionally restricted to enterprise builds (and has been since we open sourced our code, or very soon after, I believe). Features required by enterprises, such as SSO and repository permissions, and some advanced features are part of the official builds, while the core search functionality is open source. Hope that helps!

**Comment by svrx** [comment] 2020-09-01 16:53
Just checking in. 
Are there any plans or work under other ticket  to resolve the unintended regression issues identified above?

**Comment by dadlerj** [comment] 2020-09-01 17:15
Hey @svrx sorry for not updating sooner. I know that the third item, the user profile area being broken, was fixed in 3.19.0 (see https://github.com/sourcegraph/sourcegraph/pull/12313). I'm not sure if that change fixed the other two or not, though— @unknwon are you aware of whether authz was the underlying issue for saved searches and search scopes as well?

**Comment by unknwon** [comment] 2020-09-01 19:02
> @unknwon are you aware of whether authz was the underlying issue for saved searches and search scopes as well?

I don't have context around saved searches but I think it is done in behalf of internal actor which bypasses authz. As for search scopes, I'm not clear what is exactly missing/broken here?

**Comment by lguychard** [comment] 2021-11-05 11:13
This doesn't appear relevant anymore.

**Closed by lguychard** 2021-11-05 11:13 UTC
Labels: bug, team/search
