### ISSUE TITLE
Code search nav item doesn't respect middle mouse click

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/sourcegraph#27499] opened 2021-11-12 12:22 UTC
When doing a middle mouse click on the Code Search nav bar item, a new tab is opened (as expected), but the current tab is _also_ navigating.

**Comment by camdencheek** [comment] 2024-02-24 00:14
Closing since I can't reproduce this. Probably an artifact of when code search was both a dropdown and a button.

**Closed by camdencheek** 2024-02-24 00:14 UTC
Labels: bug, team/search-product, team/code-search, imported
