### ISSUE TITLE
Query returns only one result, clicking "Show more" shows MANY more, why?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#7596] opened 2020-01-09 00:41 UTC
1. Start a Sourcegraph instance using 3.11.2.
2. Add all public GitHub.com repositories under the `user:Andoryuuta`
3. With regex toggled on, search for `MHF_.+`, only one result is returned.
4. Click `Show more` and MANY more are returned. This is weird because it makes it look like we don't have all of the results.

**Comment by rvantonder** [comment] 2020-01-20 23:07
I'll investigate at some point when I have some more time with that exact configuration, but: An easy way to reproduce this behavior is a query like:

`repo:^github\.com/sourcegraph/sourcegraph$ \w+`

Shows only two preview windows:

![Screen Shot 2020-01-20 at 4 06 41 PM](https://user-images.githubusercontent.com/888624/72762981-de611f80-3b9e-11ea-8053-d4419b2cf470.png)


https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+%5Cw%2B&patternType=regexp

I know [why that happens now](https://github.com/sourcegraph/sourcegraph/pull/7709#issuecomment-575150663). TL;DR we at least need better knobs for telling Zoekt to return more matching files if it finds a ton of matching file content. I don't know if that will solve this particular issue, but it will help with the 'why do we show so few results initially sometimes and "show more" behavior shows a ton?'

I'm not sure that the `MHF_.+` pattern runs into the same thing (depends on the how many matches there are in the repo). Will report back later.

**Comment by rvantonder** [comment] 2020-02-08 01:23
I know why this happens. Background context for those who are OOTL. This only happens with indexed search (and so can't be reproduced on sourcegraph.com). To reproduce locally, clone with 

```
  "repositoryQuery": [
    "user:Andoryuuta"
  ],
```

And queries must set `index:only`. If `index:no`, you'll see 60+ results, again, because this issue is due to indexed search.

Problem: We use a scaling factor in indexed search set how many matches/results we want to see based on how many repos are matched. The intuition is:

- low number of repos to search -> give us more results -> set a higher scaling factor `k`
- high number of repos to search -> give us fewer results -> set a lower scaling factor `k`

The code:

```
        k := 1                                                                                                                                                          
        switch {                                                                                                                                                        
        case numRepos <= 500:                                                                                                                                           
                k = 2                                                                                                                                                   
        case numRepos <= 100:                                                                                                                                           
                k = 3                                                                                                                                                   
        case numRepos <= 50:                                                                                                                                            
                k = 5                                                                                                                                                   
        case numRepos <= 25:                                                                                                                                            
                k = 8                                                                                                                                                   
        case numRepos <= 10:                                                                                                                                            
                k = 10                                                                                                                                                  
        case numRepos <= 5:                                                                                                                                             
                k = 100                                                                                                                                                 
        }  
```

But this is Go code, not C, so there is no fallthrough. `k` is basically always 2, unless numRepos > 500 in which case it is 1. So we basically ask for very few results for small number of repos. `numRepos` for `"user:Andoryuuta"` is 26. The scaling factor would be `5`, setting [searchopts](https://sourcegraph.com/github.com/sourcegraph/zoekt/-/blob/api.go#L290-319): `{false false 500 500 75 125 3s 2000}` versus the scaling factor of `2` which sets `searchopts: {false false 200 200 30 50 3s 2000}` .

Now, correcting this issue returns the 60+ results across more files for this issue report, so it solves the underlying issue.

I have some concern that the intended scaling factor hasn't been tested very well (I mean tested empirically, as in, user's have been exposed to this behavior) since it has basically never worked. It's worth fixing to the intended meaning and seeing how things go. Draft PR here, but I want to add actual unit tests because this is trivial to test for: https://github.com/sourcegraph/sourcegraph/pull/8332

I discovered this because I'm using the indexing stuff for structural search and this issue affects it also.

**Comment by rvantonder** [comment] 2020-02-10 17:29
Closing this, since I reproduced this issue using the exact steps and checked that the change fixes it (many more results are showing now). Feel free to reopen if this still crops up.

**Closed by rvantonder** 2020-02-10 17:29 UTC
Labels: bug, onboarding-test-1, search
