### ISSUE TITLE
Error when sideloading an extension in the OSS version

### ISSUE THREAD

**Issue by aidan-02** [sourcegraph/sourcegraph#24831] opened 2021-09-10 09:03 UTC
#### Question description

Hello,

We are using the OSS version (built manually with cmd/server  ./pre-build.sh ./build.sh) and I would like to sideload an internally developed extension as described [here](https://docs.sourcegraph.com/extensions/authoring/local_development).

When I try to load it, I got the error

```
no extension registry is available (use Sourcegraph Free or Sourcegraph Enterprise to access the Sourcegraph extension registry and/or to host a private internal extension registry
``` 

Even if I don't need an extension registry (I just need to side load a single extension).

Am I doing anything wrong or is this the expected behaviour?

**Comment by Joelkw** [comment] 2021-09-17 16:48
Hey @aidan-02 , thanks for the question (I'm the product manager for Sourcegraph extensions). 

You're correct that this is expected behavior. Extensions are not available on Sourcegraph OSS – they're a feature of "Sourcegraph Enterprise," which you can [deploy with Docker Compose](https://docs.sourcegraph.com/admin/install). Sourcegraph Enterprise is totally free for up to 10 users. 

What are you using Sourcegraph for, or what's the sideloaded extension use case? I may be able to give you a few other ideas or workarounds as well!

**Comment by ryankscott** [comment] 2022-09-28 13:35
Closing this due to the sunsetting of Sourcegraph extensions as of v4.0

**Closed by ryankscott** 2022-09-28 13:35 UTC
Labels: team/integrations
