### ISSUE TITLE
Searching by file name doesn't work

### ISSUE THREAD

**Issue by poojaj-tech** [sourcegraph/sourcegraph#12997] opened 2020-08-14 00:35 UTC
- **Sourcegraph version:** 
3.16

Reported from NPS feedback

#### Steps to reproduce:
Customer feedback

> Something changed in sourcegraph a few weeks ago and I can't search by file name.. this is like the number one thing I do in sourcegraph. I find that the search is now completely useless.
> 
> I've switched to using GitHub to search the codebase. It's not as good as how Sourcegraph used to be, but it's the only way I can reliably search for files now.
> 

Company: https://app.hubspot.com/contacts/2762526/company/693777177/
Customer: https://app.hubspot.com/contacts/2762526/contact/25300551/

**Comment by rvantonder** [comment] 2020-09-21 18:26
Closing since this refers to an autocomplete regression in 3.16 that is resolved in subsequent versions.

**Closed by rvantonder** 2020-09-21 18:26 UTC
Labels: team/search
