### ISSUE TITLE
Support negated terms

### ISSUE THREAD

**Issue by hho** [sourcegraph/sourcegraph#1636] opened 2019-01-04 21:22 UTC
I just found out about Sourcegraph, installed it, imported the repos from our GitLab and tried to find out, which of our projects use untagged GitLab runners.

So my query was: `file:.gitlab-ci.yml -tags`

The result was this error message:
![image](https://user-images.githubusercontent.com/478228/50711423-7b254d80-106e-11e9-83d4-7096e1e89a0d.png)

My feature request is: Please support negated terms (`-term`).

It'd be very helpful to find reliance on old and/or implicit defaults, missing settings etc.

Thank you!

**Comment by sqs** [comment] 2019-01-04 22:08
Thanks for filing. This will be supported soon; see #1005. It’s  possible that will be out behind a feature flag next week, and it is planned to be released and enabled by default in early Feb.

**Comment by keegancsmith** [comment] 2019-01-07 17:43
This is behind a feature flag at the moment, see the linked issue #1005. For example https://sourcegraph.com/search?q=%21hier%21+r:/gitlabhq/+file:.gitlab-ci.yml+-tags

**Comment by sqs** [comment] 2019-01-25 05:54
Closing as dupe of #1005. Please follow that issue for updates.

**Closed by sqs** 2019-01-25 05:54 UTC
Labels: search
