### ISSUE TITLE
LSIF: unknown range errors

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/sourcegraph#5619] opened 2019-09-16 22:56 UTC
- Visit https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/cmd/searcher/search/search.go#L220
- Notice that defs/refs buttons do not appear
- Notice this error in the Network tab:

```
Error: Unknown range '395801'.
    at Object.mustGet (/lsif/out/util.js:36:11)
    at mapRangesToLocations (/lsif/out/database.js:516:68)
    at Database.convertRangesToLspLocations (/lsif/out/database.js:195:42)
    at Database.definitions (/lsif/out/database.js:68:35)
    at async /lsif/out/server.js:93:22
```

That LSIF dump was generated with lsif-go at commit e23ba48fe09fe0af26ab96dc8853f588aaafcca4

```
$ lsif-go version
Go LSIF exporter: 0.4.1
Protocol version: 0.4.0
```

Original discussion https://sourcegraph.slack.com/archives/CHXHX7XAS/p1568666728016800

Also noticed in https://sourcegraph.slack.com/archives/CHXHX7XAS/p1568674275022100

**Comment by efritz** [comment] 2019-09-17 01:47
This appears to be related to the incorrect document value for item edges:

https://github.com/sourcegraph/lsif-go/blob/master/export/exporter.go#L117
https://github.com/sourcegraph/lsif-go/blob/master/export/exporter.go#L123
https://github.com/sourcegraph/lsif-go/blob/master/export/exporter.go#L465

This was an issue with the ocaml exporter, and something that's not clearly specified in the spec. This should be an easy(ish) fix in the lsif-go indexer and shouldn't require any change in this code base.

Leaving this issue open until this as the root cause is confirmed.

**Comment by efritz** [comment] 2019-09-17 13:37
Should be fixed via https://github.com/sourcegraph/lsif-go/pull/24.

**Comment by efritz** [comment] 2019-09-18 18:21
Looks like it's fine on dot-com now.

**Closed by efritz** 2019-09-18 18:21 UTC
Labels: bug, lsif
