### ISSUE TITLE
Deduplicate git objects across forks

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#40448] opened 2022-08-16 21:50 UTC
#### Feedback

For large customers, there can be hundreds of repos that are forks of a single repository.  It would be great to take advantage of something like [what GitLab does](https://docs.gitlab.com/ee/development/git_object_deduplication.html) using Git's `alternates` mechanism.  This would drastically reduce the amount of storage needed for these repository forks.

In https://github.com/sourcegraph/accounts/issues/6716's case, it would save [over 7 TB of disk space](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1660687143822539?thread_ts=1660682276.795329&cid=C01D50MSA7L) for just the top 1,000 repositories (out of > 170k).

#### Customers

* https://github.com/sourcegraph/accounts/issues/6716 [via Slack](https://sourcegraph.slack.com/archives/C01D50MSA7L/p1660685527297829?thread_ts=1660682276.795329&cid=C01D50MSA7L)
* https://github.com/sourcegraph/accounts/issues/554

/cc @jplahn @ryphil

**Comment by keegancsmith** [comment] 2022-09-09 09:40
I think if we do this, explicit opting in makes a lot of sense (ie the pools stuff mentioned). We should take a close look at how gitaly has it implemented. Few points:
- git gc or maintenance runs a prune job. The primary GIT_DIR needs to take into account all the alternates pointing at it, otherwise it will falsely declare something as loose. (cc @stefanhengl)
- we treat our clones as deletable/moveable/recloneable. The primary clones can't be treated that way. eg moving a primary to another gitserver will break the forks. Recloning will act like git prune, ie an object that was loose in the primary may still have been reachable in the fork.
- We must make sure to properly configure performance and security related features like git islands and namespaces.
- We need to find out best practices related to security. EG we don't ensure commits are reachable when viewing them (neither does github). So when viewing a commit, you can view it in a fork even though it isn't in it but is in the primary. IE if privacy stuff changes between primarys and forks, we need to make sure we don't leak info.

**Comment by mrnugget** [comment] 2022-12-19 15:23
Note from grooming: estimating this as a `3d` spike for now, since there's so many unknown unknowns involved that we first need to figure out how much work this would actually be.

**Comment by indradhanush** [comment] 2023-01-04 18:14
## Initial findings from deep dive, 2022-01-04

I've been deep diving this and here's what I've found out so far.
First a quick drill down of the terminologies we will need to understand / familiarise ourselves with.

### 📖 Terminologies

**Pool repository**
A unique copy of a repository that has been forked at least once stored at `$POOL_REPO`.

**Alternates**
A file at `$REPO_DIR/.git/objects/info/alternates` which contains a path to the `.git/objects` file of a pool repository.

**Forks**
A fork of the original repository with an `alternate` file.

**Source repository**
The original repository that has been forked. But it is also maintained as an alternate by having an entry in `$REPO_DIR/.git/objects/info/alternates` file that points to the `$POOL_REPO/.git/objects` file. This will be required to differentiate it as a non-fork repository.

### ⚙️ How this could work

If deduplication is enabled for a repo , then `gitserver` will clone the repo at `$POOL_DIR` (`/data/repos/pool`). This path should be different than our regular path for storing repos on disk to easily differentiate pool repos from regular ones.

1. Clone the repository under `$POOL_DIR` to create a **pool** repository
2. Also clone[1] the repository to `/data/repos/` 
3. Write to `/data/repos/$REPO_DIR/.git/objects/info/alternates` path to `$POOL_DIR/$REPO_DIR/.git/objects`
4. Run `git repack` and `git gc` in the repo with the `alternate` file
5. Repeat step 2 and 4 for any forks

❗Important: It seems it is pretty easy to corrupt your alternate repo as I found out myself when I was playing around with this if you get anything wrong or want to remove the `alternate` file as an afterthought. Leaving this as a note in case we want to be careful here. For me it turned out to be unstaged changes in the worktree of the `alternate` repo which was the culprit.
   
### 🌋 Evolution of a repo with this approach

I cloned the [example repo](https://github.com/indradhanush/probable-happiness) (it has only one commit) under `/tmp` locally. And this is what it looked like before adding the alternate repo:

```
➜ git clone git@github.com:indradhanush/probable-happiness.git  .
Cloning into '.'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.

➜ pwd
/tmp/probable-happiness

➜ tree .git/objects
.git/objects
├── info
└── pack
    ├── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.idx
    └── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.pack

2 directories, 2 files
```

And then cloned it again to a different path - `/tmp/fork`

```
➜ git clone git@github.com:indradhanush/probable-happiness.git fork
Cloning into 'fork'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.

➜ cd fork

➜ pwd
/tmp/fork

➜ tree .git/objects
.git/objects
├── info
└── pack
    ├── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.idx
    └── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.pack
```

Added the alternate file:

```
➜ echo "/tmp/probable-happiness/.git/objects" > .git/objects/info/alternates
```

Ran `git repack` and then `git gc`:

```
➜ git repack
Enumerating objects: 2, done.
Nothing new to pack.

➜ tree .git/objects
.git/objects
├── info
│   ├── alternates
│   └── packs
└── pack
    ├── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.idx
    └── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.pack

2 directories, 4 files

➜ git gc
Enumerating objects: 3, done.
Nothing new to pack.

➜ tree .git/objects
.git/objects
├── info
│   ├── alternates
│   ├── commit-graph
│   └── packs
└── pack

2 directories, 3 files
```

The original repo remained unchanged (as expected).

👉 Effectively the pack objects are gone from the `alternate` repo because it is common with the pool repo. This might have some effect on indexing since zoekt (based on my understanding so far) requires the git-objects to start indexing. This is where I am looking for input from @sourcegraph/search-core.

Sidenote: I also verified with the `git init --bare` followed by `git fetch` approach that we actually do in our code base to clone new repos to be sure and had the same result (not surprising but good to know).  

### 🧩 Sharding

Both the pool repo and all the alternate repo must be colocated on the same shard as the `alternate` file points to a path on the file system. We do have repository pinning support (`experimentalFeatures.gitServerPinnedRepos`) but it will have no effect on the forks. We will need to build that into account if deduplication is enabled.

### ⏳ Repo syncing

Regular repo syncing with `git fetch` can continue for all the `alternate` repos but we will also need to ensure that we update the pool repositories.

### 🧹 Git GC

When git-gc (which runs git-prune) runs it will remove all objects from the `alternate` repositories that are common with the `pool` repository. 

A pool repository can be considered as the super-set of all git objects for that repo. But `git-gc` is not able to ascertain for sure if an object is needed by one of the `alternate` repositories. As a result, we should ensure `git gc` or `git prune` is never ever run in any pool repository, failing which we may see repo corruption.

### 🌐 Repo fetching

Our default fetchCommand does a `git fetch --no-auto-gc --prune`. We may want to disable the `--prune` flag for pool repositories.


### 🦶🏽✏️ Footnotes
\[1\]: For large repositories, cloning again may not be such a great idea (some customers spend days cloning a repo). Maybe we can copy the directory instead?

**Comment by bobheadxi** [comment] 2023-01-04 19:13
@indradhanush note that `git clone` (and possibly other commands) natively supports a feature that looks like what you described, `--reference[-if-able] <repository>`: https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---reference-if-ableltrepositorygt

> If the reference repository is on the local machine, automatically setup .git/objects/info/alternates to obtain objects from the reference repository. Using an already existing repository as an alternate will require fewer objects to be copied from the repository being cloned, reducing network and local storage costs. When using the --reference-if-able, a non existing directory is skipped with a warning instead of aborting the clone.

If a repository is known to be a fork, you might be able to achieve the deduplication you want by using `--reference` on initial clone

**Comment by indradhanush** [comment] 2023-01-05 05:17
Hmm, it doesn't look like `git fetch` supports something similar to this yet. Maybe we can use `git clone --bare --reference-if-able` for forks as an exception which should be equivalent to the current approach of `git init --bare && git fetch` that we currently do for new clones.

Alternatively, maybe we can make use of `CloneFromShard` to clone locally from within the same shard in this case. I will keep this in mind as a `TODO/VERIFY` when creating the list of tasks for this issue.

**Comment by mrnugget** [comment] 2023-01-05 13:22
Thanks for that write-up @indradhanush!

A few questions:

1. "The original repository that has been forked. But it is also maintained as an alternate" -- it's not clear to me why that is required. In your example you clone the source-repo and then point the fork to the source-repo. Why doesn't that work? Is this related to this?
     > As a result, we should ensure git gc or git prune is never ever run in any pool repository, failing which we may see repo corruption.
2. In "Repo syncing" you wrote "but we will also need to ensure that we update the pool repositories" -- why? If you have a repository with an `alternatives` file pointing to a source-repo, is it not possible to `git fetch` in that fork repo and get the objects from the source _and_ the objects that are unique to the fork?
3. Say the answer to (1) is that need to treat forks _and_ _source_ repositories as `alternates`  -- does this mean we need to know whether to treat a repository as source _before_ we clone it? i.e. user adds repo A to instance, it gets cloned. User then enables fork-deduplication for repo A and adds repo A-fork to instance. Would we have to re-clone repo A (into a `POOL`) and only then clone repo A-fork?

**Comment by indradhanush** [comment] 2023-01-05 17:16
> 1. "The original repository that has been forked. But it is also maintained as an alternate" -- it's not clear to me why that is required. In your example you clone the source-repo and then point the fork to the source-repo. Why doesn't that work? Is this related to this?
>
>>    As a result, we should ensure git gc or git prune is never ever run in any pool repository, failing which we may see repo corruption.

Yes. Because not running git gc will lead to eventual performance bottlenecks on large monorepos. Maintaining the source repo as an alternate should help alleviate that. 


> 3. Say the answer to (1) is that need to treat forks and source repositories as alternates -- does this mean we need to know whether to treat a repository as source before we clone it? i.e. user adds repo A to instance, it gets cloned. User then enables fork-deduplication for repo A and adds repo A-fork to instance. Would we have to re-clone repo A (into a POOL) and only then clone repo A-fork?

I don't think there's a reliable way to know ahead of time if we should treat a repository as source (unless we add support via code host config). Here's how I am envisioning this happening:

1. A source repo is cloned
1. A new repo is picked up which is a fork of the source
1. Git deduplication is enabled already
1. Clone a pool repository (we can most likely clone directly from the current source repo)
1. Set up `alternate` in `source` repo
1. Clone the fork repo which was kick started this whole process above in step 2
1. If step 2 is not the first fork of the source repo and a pool already exists, we should be able to jump to step 6 directly with Git deduplication enabled

🧪 I did a little test locally by cloning the `pool` repo and then the `source` and the `fork` from the `pool` repo using @bobheadxi's suggestion:

```
➜ pwd
/tmp/dedup-test

➜ git clone git@github.com:indradhanush/probable-happiness.git pool
Cloning into 'pool'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.

➜ git clone git@github.com:indradhanush/probable-happiness.git --reference-if-able ./pool source
Cloning into 'source'...

➜ git clone git@github.com:indradhanush/probable-happiness.git --reference-if-able ./pool fork
Cloning into 'fork'...

➜ tree pool/.git/objects
pool/.git/objects
├── info
└── pack
    ├── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.idx
    └── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.pack

2 directories, 2 files

/tmp/dedup-test on ☁️  (eu-central-1)
➜ tree source/.git/objects
source/.git/objects
├── info
│   └── alternates
└── pack

2 directories, 1 file

/tmp/dedup-test on ☁️  (eu-central-1)
➜ tree fork/.git/objects
fork/.git/objects
├── info
│   └── alternates
└── pack

2 directories, 1 file
```

Seems to work quite well. Note that in this example we're expecting to clone the pool before the source. But if it's the other way round we cannot use the `--reference-if-able` for cloning from `source` to `pool`.



> 2. In "Repo syncing" you wrote "but we will also need to ensure that we update the pool repositories" -- why? If you have a repository with an `alternatives` file pointing to a source-repo, is it not possible to `git fetch` in that fork repo and get the objects from the source _and_ the objects that are unique to the fork?

This did make me think. I would have expected the new objects to appear in the `pool` after a new objects were added to `source` and `git repack` and `git gc` were run.  [GitLab's documentation](https://docs.gitlab.com/ee/development/git_object_deduplication.html#deduplication-factor) also seems to suggest as such:

> The effectiveness of Git object deduplication in GitLab depends on the amount of overlap between the pool repository and each of its participants. Each time garbage collection runs on the source project, Git objects from the source project are migrated to the pool repository. One by one, as garbage collection runs, other member projects benefit from the new objects that got added to the pool.

So I tested this hypothesis:

1. Create a new commit on `source` and push upstream

```
➜ cd source

➜ touch foo

➜ git add foo

➜ git commit -m 'add foo'
[main d9eab18] add foo
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo

➜ git push -u origin HEAD
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 10 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 275 bytes | 275.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:indradhanush/probable-happiness.git
   d6cfb32..d9eab18  HEAD -> main
branch 'main' set up to track 'origin/main'.
```

2. Check the new objects in `source`

```
➜ tree .git/objects
.git/objects
├── d9
│   └── eab187754f386e626de8ea1f48f699392d2edc
├── e6
│   └── 9de29bb2d1d6434b8b29ae775ad8c2e48c5391
├── f7
│   └── 1de8cb2208daabfbdb9737ed1bcd887523874f
├── info
│   └── alternates
└── pack

5 directories, 4 files
```

3. Run `git-repack` and `git-gc` in `source`
   
```
➜ git repack
Enumerating objects: 4, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 10 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0

➜ git gc
Enumerating objects: 6, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 10 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), done.
Total 3 (delta 0), reused 3 (delta 0), pack-reused 0

➜ cd ..
```

4. Check latest state of `.git/obejcts` after `git-gc` in `source`

```
➜ tree source/.git/objects
source/.git/objects
├── info
│   ├── alternates
│   ├── commit-graph
│   └── packs
└── pack
    ├── pack-dd635bb9d640faac432fe9c3c500b933469192cf.idx
    └── pack-dd635bb9d640faac432fe9c3c500b933469192cf.pack

2 directories, 5 files
```

5. Check if new objects appear in `pool`

```
➜ tree pool/.git/objects
pool/.git/objects
├── info
└── pack
    ├── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.idx
    └── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.pack

2 directories, 2 files
```

They don't. Hmm.

6. Run `git-fetch` in `pool`:

```
➜ cd pool

➜ git fetch
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 255 bytes | 255.00 KiB/s, done.
From github.com:indradhanush/probable-happiness
   d6cfb32..d9eab18  main       -> origin/main
```

7. Now check latest status of `.git/objects` in `pool`:

```
➜ cd ..

/tmp/dedup-test on ☁️  (eu-central-1)
➜ tree pool/.git/objects
pool/.git/objects
├── d9
│   └── eab187754f386e626de8ea1f48f699392d2edc
├── e6
│   └── 9de29bb2d1d6434b8b29ae775ad8c2e48c5391
├── f7
│   └── 1de8cb2208daabfbdb9737ed1bcd887523874f
├── info
└── pack
    ├── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.idx
    └── pack-cfc6c21b11dc9eaa483c01a909dec157e68fbbb3.pack

5 directories, 5 files
```

The new objects are in `pool` now. 

Maybe I missed something but if I didn't it looks like we would have to run `git fetch` in the `pool` repository.

**Comment by mrnugget** [comment] 2023-01-12 13:44
Thanks for that writeup @indradhanush! Very clear (and I love me some grade-A Markdown formatting).

@ryphil @mike-r-mclaughlin I can't give a good estimate, but I would say this is decidedly non-trivial. It's a multi-months project for 1-2 engineers. It's not undoable, but it requires reworking how we handle the lifecycle of repositories in gitserver (which is pretty dumb at the moment).

**Comment by mrnugget** [comment] 2023-01-16 14:58
@ryphil Ryan, moving this back to backlog in sprint planning, because it's quite a bit of effort and should likely be a separate job fair project.

**Comment by indradhanush** [comment] 2023-01-16 15:01
Adding a note on performance benefits / regressions apart from disk space saved:

We haven't looked at git performance in this case to see if git operations slow down significantly on a large monorepo with a large number of forks and it might be worth another spike to look into that.

**Comment by keegancsmith** [comment] 2023-02-07 20:56
To add on to this, this won't automatically make the services which consume commits from git more space efficient. EG zoekt would still create "duplicate" shards per fork. It would require extra work on zoekts side to more natively understand these concepts. I'm sure the same is true for all our other systems which compute stuff from gitserver.

This also points that if the suggestion to just not include the forks on the customer is possible, then that is low hanging fruit that will reduce usage across all services.

**Closed** 2024-06-03 09:00 UTC
Labels: feature-request, customer, team/source
