### ISSUE TITLE
Browser extension: Fall back to public sourcegraph.com server when browsing public code that's unknown by configured server

### ISSUE THREAD

**Issue by byrongrogan** [sourcegraph/sourcegraph#8550] opened 2020-02-21 17:43 UTC
#### Feature request description

I use a self-hosted Sourcegraph instance for my company's internal code, but I often like to use Sourcegraph's public server when browsing or searching through public open-source code on github.com. This means that I have to continually switch the server settings in the browser extension, or else go without code intelligence on public github repos and just use sourcegraph.com/search.

Two things would be nice to make this sort of switch automatic:

* I usually search in the address bar with `src <query>`. If there was an alternate keyword, e.g. `srcp <query>`, that would search using public sourcegraph.com, that would be ideal for searching public repos.

* When browsing public open-source code that is unknown by the configured sourcegraph server, it would be nice to fall back to public sourcegraph.com for code intelligence and display of the "view on sourcegraph" button.

#### Describe alternatives you've considered.

The `srcp <query>` solution I described above is probably possible by manually configuring keyword searches in Chrome settings.

**Comment by unknwon** [comment] 2020-02-21 21:14
Thanks for the feedback! But I think this is duplicated to https://github.com/sourcegraph/sourcegraph/issues/643? cc @sourcegraph/web

**Comment by lguychard** [comment] 2020-02-24 08:27
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/643

**Closed by lguychard** 2020-02-24 08:27 UTC
Labels: browser-extension
