### ISSUE TITLE
Add support for grouping generated compute series

### ISSUE THREAD

**Issue by unclejustin** [sourcegraph/sourcegraph#39162] opened 2022-07-20 16:34 UTC
Pre-req for https://github.com/sourcegraph/sourcegraph/issues/38832

Need backend support for grouping generated series. See the linked issue for more information.

**Comment by sourcegraph-bot-2** [comment] 2022-07-20 16:34
Heads up @joelkw @felixfbecker @vovakulikov @unclejustin - the "team/code-insights" label was applied to this issue.

**Comment by CristinaBirkel** [comment] 2022-07-21 16:08
@unclejustin It's not a given that this should go on the backend. Let's discuss this more?

**Comment by coury-clark** [comment] 2022-07-21 16:48
It isn't clear what is being asked for here. Without changing our response shape there isn't much we can do to make this calculation easier. It's relatively straightforward as-is, see below. Can you clarify, is this issue just looking for live preview support? 

For non-live-preview:
Below is the algorithm use the current response to map by series, and therefore by color. 

Here is an example response with two series (two queries).

``` json
{
  "data": {
    "insightViews": {
      "nodes": [
        {
          "id": "aW5zaWdodF92aWV3OiIyQ0dGbmdQTFpsdXpma3htWk1QZE05RTlaQnEi",
          "dataSeries": [
            {
              "seriesId": "2CGGBqkLWjQqIZXWVItoBDGRX7D-enterprise/internal/insights/store/insight_store.go",
              "label": "enterprise/internal/insights/store/insight_store.go",
              "points": [
                {
                  "dateTime": "2022-07-21T16:36:16Z",
                  "value": 38,
                  "__typename": "InsightDataPoint"
                }
              ],
              "status": {
                "backfillQueuedAt": "2022-07-21T16:36:15Z",
                "completedJobs": 1,
                "pendingJobs": 0,
                "failedJobs": 0,
                "__typename": "InsightSeriesStatus"
              },
              "__typename": "InsightsSeries"
            },
            {
              "seriesId": "2CGGBr8iGRCldcW4YLyLOLaOk8y-enterprise/internal/insights/background/historical_enqueuer.go",
              "label": "enterprise/internal/insights/background/historical_enqueuer.go",
              "points": [
                {
                  "dateTime": "2022-07-21T16:36:16Z",
                  "value": 37,
                  "__typename": "InsightDataPoint"
                }
              ],
              "status": {
                "backfillQueuedAt": "2022-07-21T16:36:15Z",
                "completedJobs": 1,
                "pendingJobs": 0,
                "failedJobs": 0,
                "__typename": "InsightSeriesStatus"
              },
              "__typename": "InsightsSeries"
            }
          ],
          "__typename": "InsightView"
        }
      ],
      "__typename": "InsightViewConnection"
    }
  }
}

```

The set of `seriesId` on the insight must already be available (this is a property of the `dataSeriesDefinitions` array).

```
For series_id on insight:
    For dataSeries in response:
        if dataSeries.seriesId startsWith series_id then map dataSeries to series_id
```

Then you can render based on the metadata associated with `series_id`, and you now have all of the response data that comes from each one.


For live preview:
The live preview doesn't accept multiple queries. Therefore the options are:
1. Send multiple requests (by which you would group per request)
2. Create a new live preview resolver that accepts multiple queries

**Comment by vovakulikov** [comment] 2022-07-22 10:28
@coury-clark This is correct that we need to support this in live preview (and technically this is correct that we could support this already in insightViews query) 

But live preview is a blocker for us because we can't have live preview and insight on the dashboard page with different appearance. 

A few thoughts around linking dataSeries definition and its data in dataSeries field. This is a huge pain point on the frontend. This actually that GQL should do by design but because of long history of API we have to handle all this linking on the FE. As a result we don't have type safety in our API, our API is full of corrupted patterns. (for example dataTime field means nothing in compute powered insight, ....) 

I want to raise attention that in my opinion we shouldn't implement any further versions of compute-powered insight without changes in our API. FE complexity has reached maximum level of complexity long time ago I think it time to revisit this problem with linking. 

In my opinion we should
- Create a new live preview resolver that accepts multiple queries
- Create a new insight type (similar to SearchBasedInsight type or PieChart type in our API), and this is short version of change, the full fix would be revisit our insight types in API from the scratch 

cc @unclejustin

**Comment by felixfbecker** [comment] 2022-08-17 21:29
@vovakulikov you marked this as part of the aggregation project, but I'm still not clear what is asked with this issue from the issue. Could you (or @unclejustin) update the issue description and explain how it connects to the 4.0 scope?

**Comment by vovakulikov** [comment] 2022-08-18 11:41
@felixfbecker basically, this issue is about supporting multi-series for compute-powered insight preview in the creation UI. But since we decided to go with single series mode for the V1 of the aggregation project (see this comment https://github.com/sourcegraph/sourcegraph/issues/38832#issuecomment-1206468022), this issue is no longer relevant for the aggregation project. I remove the label from it.

**Closed** 2022-09-21 16:55 UTC
Labels: team/code-insights, backend, needs-triage, compute-insight
