### ISSUE TITLE
GitLab auth error on sign-in

### ISSUE THREAD

**Issue by dadlerj** [sourcegraph/sourcegraph#3917] opened 2019-05-09 22:30 UTC
- **Sourcegraph version:** 3.3.7
- **Platform information:** GItLab auth

A user at https://app.hubspot.com/contacts/2762526/company/547190400 reported that they experience an oauth error after signing in via GitLab SSO.

Repro:
* Sign out of Sourcegraph
* Sign out of GitLab
* Sign back in to GitLab
* Click to sign in to Sourcegraph via GitLab SSO
* Grant access to Sourcegraph on the GitLab permissions screen
* Land on `sourcegraph.example.com/.auth/gitlab/callback?code=...` to a blank page with the error: `Oath2: context missing state value`

Refreshing the page seems to indicate that the user was successfully signed in, but into their "first user" admin account (which supposedly wasn't associated with their GitLab user account). 

Other users are able to sign in and follow this flow with no problems (the other user wasn't (1) a Sourcegraph site admin, and (2) didn't have a preexisting account on Sourcegraph).

I will ask the user to validate that this accurately captures the issue.

Also reported here: https://github.com/sourcegraph/sourcegraph/issues/2263

**Comment by drgone** [comment] 2019-05-10 21:21
looks correct

**Comment by dadlerj** [comment] 2019-05-13 20:21
Great, I'll leave it to @beyang to triage and/or assign an owner. To confirm, it sounds like you're able to use Sourcegraph with a workaround (signing in as the admin) today @drgone? Definitely let us know if this pops up for any other users.

**Comment by drgone** [comment] 2019-05-20 21:55
Just tried to sign up a new user, it turns out that all gitlab-only users are getting the oath2 error unless they have created a local account. 

In short, only local accounts work.

**Comment by dadlerj** [comment] 2019-05-20 21:58
Thanks, then this is a big deal — we're in release mode right now, but @beyang will help triage shortly.

**Comment by remcoros** [comment] 2019-07-24 12:18
I am evaluating sourcegraph and it seems this is still an issue in 3.6 (installed latest using docker). Is that correct?

**Comment by tsenart** [comment] 2019-07-24 23:57
@beyang: Any clues what "Oath2: context missing state value" could refer to?

**Comment by beyang** [comment] 2019-08-22 23:37
I am having trouble reproducing this. The error originates [here](https://sourcegraph.com/github.com/dghubble/gologin@e01b96bc6ca179658a1f12488b34c92cff2d0810/-/blob/oauth2/context.go#L27:34), the function that reads the OAuth state parameter from the HTTP request context, which is set from the cookie value. The value of the state as read from the cookie/context is then compared to the value of the state passed in the OAuth callback URL for equality. I think there are 2 possibilities here:
1. There is a race condition in our code that causes the state value to be erased from the context before it is read either [here](https://sourcegraph.com/github.com/dghubble/gologin@e01b96bc6ca179658a1f12488b34c92cff2d0810/-/blob/oauth2/login.go#L80:22) or [here](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@0407b0e8667bc6f80dcd257116d4429ad75959c6/-/blob/enterprise/cmd/frontend/auth/oauth/session.go#L65:32)
2. There is something that prevents the state value from being read from the session cookie. Perhaps some intermediate auth proxy that swallows this.

@remcoros @drgone is this against your own GitLab instance or GitLab.com? Is there anything in your setup that might interfere with cookies (nginx, Apache, or another proxy that sits between Sourcegraph and the public Internet)?

**Comment by remcoros** [comment] 2019-08-23 08:09
We had a proxy server in between, but can't imagine it would fiddle with cookies. At least, we haven't experienced any issues with it before.

We recently removed the proxy server though, and also I am testing 3.7.1 now, and it seems it works now.

**Comment by dadlerj** [comment] 2019-08-23 16:27
Thanks! @drgone how about on your end?

**Comment by keegancsmith** [comment] 2020-01-13 10:51
Closing for now, will re-open if this resurfaces. (cc @drgone in case this issue isn't gone for you)

**Closed by keegancsmith** 2020-01-13 10:51 UTC
Labels: auth, bug, team/core-services
