### ISSUE TITLE
Find References gives error: "Git ls-tree ....: file does not exist"

### ISSUE THREAD

**Issue by Taytay** [sourcegraph/sourcegraph#126] opened 2018-08-22 16:11 UTC
- **Sourcegraph version:** 
Chrome Plugin: 1.10.3
- **Platform:** 
Chrome Plugin on Chrome for Mac

#### Steps to reproduce:

1. Install Plugin 
2. Go to this Rails file in the Rails repo: https://github.com/rails/rails/blob/HEAD/activerecord/lib/active_record/connection_adapters/abstract/schema_definitions.rb#L446-L446
3. Hover over any text. I recommend AlterTable on line 446. 
4. Click on "Find References"

#### Expected: 
I assume it is supposed to not give an error and find references somehow.

#### Actual:
Browser takes you to this URL: https://sourcegraph.com/github.com/rails/rails@master/-/blob/activerecord%2Flib%2Factive_record%2Fconnection_adapters%2Fabstract%2Fschema_definitions.rb#L446:11&tab=references

And gives this error: 
```
Error
Git ls-tree activerecord%2Flib%2Factive_record%2Fconnection_adapters%2Fabstract%2Fschema_definitions.rb: file does not exist
```

**Comment by Taytay** [comment] 2018-08-22 17:46
Doh! I don't know how I missed the link in my bug report. Adding it now.

**Comment by chrismwendt** [comment] 2018-08-22 20:47
I'm not seeing the "Git ls-tree" error:

![2018-08-22 13 44 38](https://user-images.githubusercontent.com/1387653/44489895-9dfc1b80-a611-11e8-9535-7afc538d6a14.gif)

This is the same Chrome extension version 1.10.3

I noticed your URL has a bunch of `%2F`s, which are URL-encoded `/`s, but I'm not sure where that could be coming from.

**Comment by ijsnow** [comment] 2018-08-23 00:38
Hmmm, something strange is going on indeed. Thanks for reporting and sorry this is happening!

If I:

1. follow your exact repro steps, I see the same thing @chrismwendt see's in the gif above. If I click "Find references", it goes to sourcegraph.com and opens the references panel and then see the following error:
> Error getting local references: Other goroutine failed to connect and initialize LSP server: [RuntimeError] Error parsing /tmp/proxy-cache/d011ef08-0870-443f-b8c6-f13452c312a8/actioncable/test/client_test.rb: [ArgumentError] invalid byte sequence in US-ASCII
2. wait for the hover information to come back just to see what it says, I see the *same error* as (1).
3. click on your direct link with all of the `%2f`'s, I see the same error you're reporting.

So I think that the [experimental Ruby language server](https://github.com/castwide/solargraph) is definitely not helping us as it seems like we're all seeing different outcomes. However, I don't think that's the cause of your issue. My biggest question that's left standing is why was the URL encoded as it was? That's definitely not expected and is most likely causing the errors in the file lookup. 

Are you still able to consistently reproduce this following your steps(not just following the link)?

**Comment by sqs** [comment] 2019-01-30 07:47
We removed the Ruby experimental lang server that caused this (see https://about.sourcegraph.com/blog/java-php-experimental_language_servers-temporarily-unavailable).

The preferred way to get Ruby code intelligence is now to use the basic-code-intel extension; see https://about.sourcegraph.com/blog/sourcegraph-3.0-beta-is-now-available#basic-code-intelligence-for-all-languages for info. (On Feb 4, 5 days from when I'm currently writing this, Sourcegraph 3.0 will be released, at which point there will be a **Ruby** extension that is enabled by default on all instances; see #2035. Then this will just work out of the box.)

**Closed by sqs** 2019-01-30 07:47 UTC
Labels: bug, feature:code-intel
