### ISSUE TITLE
Wildcard button: text in disabled buttons is too bright in dark mode

### ISSUE THREAD

**Issue by limitedmage** [sourcegraph/sourcegraph#35755] opened 2022-05-19 22:08 UTC
## Problem statement

In dark mode, the text color in disabled buttons, especially of the `primary` variant, but to some extent also in the `success` and `danger` variants, is too bright. It's not visually clear, in isolation, if the button is disabled or not. Using gray text would make it clearer that the button is disabled.

![image](https://user-images.githubusercontent.com/206864/169412590-0ff074ec-1f97-4958-be55-5ead9ac46bdf.png)

## Success criteria

The disabled button styles in the dark mode are updated to reflect the latest changes in [Figma mockups](https://www.figma.com/file/NIsN34NH7lPu04olBzddTw/%E2%9C%B3%EF%B8%8F-Wildcard-Design-System?node-id=908%3A2513).

## Time estimate

- Pull requests with ~450 lines changed should take **2 hours** at maximum. Ping the reviewer in the spec pull request if time-consuming changes are required.
- Split the work into multiple pull requests if the total diff is bigger than 450 lines of code.

**Comment by jasongornall** [comment] 2022-08-01 13:52
cc @AlicjaSuska for thoughts here

**Comment by AlicjaSuska** [comment] 2022-08-01 22:02
Thank you for bringing this up. It's a change I'd like to consult with the design team. I'll post on slack and give updates here.

**Comment by limitedmage** [comment] 2022-09-01 20:49
@AlicjaSuska @sourcegraph/frontend-platform any updates on this? Here is a customer feedback about this being confusing: https://sourcegraph.slack.com/archives/C01D50MSA7L/p1661498490250479

**Comment by limitedmage** [comment] 2022-09-07 15:36
@AlicjaSuska @sourcegraph/frontend-platform more feedback on this: https://sourcegraph.slack.com/archives/C03CSAER9LK/p1662538140496789

**Comment by valerybugakov** [comment] 2022-09-08 06:11
@limitedmage, I've updated the issue description and assigned GitStart to implement the required changes because the issue is already fixed in mockups.

**Comment by valerybugakov** [comment] 2022-09-08 06:12
Porting valuable comments from Slack to the issue:
> This was also recently reported by Salesforce: https://app.slack.com/client/T02FSM7DL/C01D50MSA7L


> This is solved (or at least mitigated) on the Figma file for Wildcard. It seems that in that disabled button we are using white, but on figma we use a 60% opacity for the text.

**Comment by limitedmage** [comment] 2022-10-10 20:17
Reopening this issue. The success and danger buttons look good, but the text on the primary button is still too bright.
![image](https://user-images.githubusercontent.com/206864/194945598-61c5a1b0-5488-4a47-a272-56d597ca6706.png)

**Closed** 2022-10-12 03:59 UTC
Labels: design, team/frontend-platform, Wildcard DS, gitstart, wildcard-v3, sourcegraph-refinement-bot
