### ISSUE TITLE
Tighten up language/concept usage in campaigns UI

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph#13629] opened 2020-09-03 18:07 UTC
I think we need to tighten up the words we use. For example:

"Click create campaign to publish it" implies the changesets will be published, but that isn't accurate. 

The "Create campaign" button is equivalent to "apply"ing the campaign spec. We use the term "apply spec" in the breadcrumb but "Create campaign" in the button.

"Not publish" doesn't sound grammatical.

If "Preview mode" is a real mode, what is the name of the non-preview mode? I don't think there is a useful name for the other mode, so we should use the term "mode" here. Something like "You're previewing this campaign." is clearer and avoids introducing a new concept of modality.

"Beta" implies the campaign is beta, not that the "Sourcegraph campaigns feature" is beta.

See this screenshot for where these terms occur:

![image](https://user-images.githubusercontent.com/1976/92151226-a1683700-edd5-11ea-9cce-71682ab123e1.png)

**Comment by mrnugget** [comment] 2020-09-04 07:16
@chrispine @eseliger @rrhyne I'd say this definitely needs to go into 3.20.

**Comment by chrispine** [comment] 2020-09-04 16:00
Totally agree. This might be a duplicate of other issues, but Erik would know best. In any case, I'll assign this to you, @eseliger .

**Comment by rrhyne** [comment] 2020-09-04 19:25
@chrispine and I have been working on this and updated the design and copy. @sqs @efritz can you review? 

 ![image](https://user-images.githubusercontent.com/539268/92278184-85ce6080-eea9-11ea-8862-c0c07810ab7f.png)

Figma frame in question for commenting, changes:
https://www.figma.com/file/kRf5i7xf1p4zs3OyX0DUVp/Campaigns?node-id=257%3A47

**Closed** 2020-09-11 13:53 UTC
Labels: estimate/0.5d, team/campaigns

**Comment by chrispine** [comment] 2020-09-16 23:09
#13729 was merged, so I'm closing this one
