### ISSUE TITLE
regression: what is the difference between "discussions" and the "chat bubble" icon?

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/sourcegraph#1851] opened 2019-01-13 20:51 UTC
@attfarhan @francisschmaltz @sqs After https://github.com/sourcegraph/sourcegraph-code-discussions/pull/11 was merged, we now have a link saying `Discussions` and a chat bubble which shows discussions on Sourcegraph.com:

![image](https://user-images.githubusercontent.com/3173176/51090525-2eaad380-173a-11e9-9047-4d13c0174488.png)

i.e. `Inline discussions` above will become just `Discussions`.

This is obviously going to be confusing for users: which one does what? The only way I will know is via tooltips, which is not good.

**Comment by francisschmaltz** [comment] 2019-01-13 20:54
Can we chose to not show the "discussions" word on the Sourcegraph nav?

**Comment by slimsag** [comment] 2019-01-13 21:05
One opens the discussions panel, the other toggles inline display of discussions.

We may be able to not show the inline display toggle on Sourcegraph.com and instead rely on users going to the command palette for that, but I am worried about the inconsistency in terms of UX between github and sourcegraph if we do that.

**Comment by attfarhan** [comment] 2019-01-14 00:48
We have a command palette on GitHub too, so we could rely on users using that on both, right? But that may create a discoverability problem. I personally very rarely use the command palette. What do you think @francisschmaltz @slimsag?

**Comment by francisschmaltz** [comment] 2019-01-14 00:49
I think @attfarhan is hitting at a much larger problem. The UX of the buttons vs command pallet is unclear and probably not great.

**Comment by slimsag** [comment] 2019-01-14 01:47
Inline code discussions is on by default, which is important for discoverability _of code discussions_, but not having an easily discovered way _to turn it off_ would be bad. This is actually why it's an inline button and named `Inline discussions` -- I didn't have a better way to solve it than this originally.

**Comment by attfarhan** [comment] 2019-01-14 17:00
@slimsag I noticed the discussions panel is not part of the extension. Do you have an idea of how much time it would take to build the discussions panel into the extension using the [`createPanelView`](https://unpkg.com/sourcegraph@20.1.0/dist/docs/modules/_sourcegraph_.app.html#createpanelview) API? It seems like it will take some work since it uses `FilteredConnection`, updates history in the react app, etc., and the API only takes in Markdown for content. If we wanted to spend time on this, my proposal would be to repurpose the chat bubble icon to be the toggle for inline discussions. Then, we would build the discussions panel into the extension, and add the toggle for that in the command palette only. 

I don't have any other good alternatives, and I think the original proposal (replacing "Inline discussions" with a chat bubble icon) would obviously aggravate this problem. To be honest, though, I don't think removing "Inline" is that bad of a regression. My hunch would be that most people (myself included) will refer to the tooltips to differentiate between the two regardless of the "Inline" prefix. And, it helps the cluttering problem. So, we can decide to publish the new version of the extension (with the "Discussions" label) or just revert the change. 

I am going to move this to 3.0 rather than 3.0-beta since we don't have a good solution and it's not release blocking.

**Comment by felixfbecker** [comment] 2020-05-11 12:11
Closing since we removed discussions from the webapp.

**Closed by felixfbecker** 2020-05-11 12:11 UTC
Labels: bug, needs-design
