### ISSUE TITLE
search: No rev name in results when streaming search is enabled

### ISSUE THREAD

**Issue by camdencheek** [sourcegraph/sourcegraph#18022] opened 2021-02-05 17:31 UTC
When streaming search is enabled, results in the UI don't include the revision name for non-default revisions. Comparison below.

Streaming search enabled:
<img width="879" alt="Screen Shot 2021-02-05 at 10 30 04" src="https://user-images.githubusercontent.com/12631702/107067970-3a441980-679d-11eb-8d2e-60ab6dedf885.png">

Streaming search disabled:
<img width="841" alt="Screen Shot 2021-02-05 at 10 29 20" src="https://user-images.githubusercontent.com/12631702/107067978-3c0ddd00-679d-11eb-9dca-124943030fc4.png">

**Comment by limitedmage** [comment] 2021-02-19 21:19
Duplicate of #17975

**Closed by limitedmage** 2021-02-19 21:19 UTC
Labels: bug, team/search
