### ISSUE TITLE
JetBrains: completion suggestions at the cursor are difficult to use

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/sourcegraph#56809] opened 2023-09-20 00:16 UTC
Report from customer around completion UX. 

> I find the automatic code suggestions that appear at the cursor quite difficult to use. Sometimes the suggestion is good, but because the suggestions are so slow, I’ve already typed half of the suggestion and using it becomes awkward because i now have to make an edit after having accepted the suggestion. Other times, I usually want the suggestion to go on the next line rather than where the cursor is. When I’m reading the code, the suggestions distract me from the code that is actually there that I’m trying to understand.

[Thread](https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1695143189714289)

**Comment by olafurpg** [comment] 2023-09-21 09:57
@taylorsperry Is this feedback for 3.1? If it's pre-3.1 then I propose we close this as "unable to reproduce"

**Closed** 2023-09-21 09:59 UTC
