### ISSUE TITLE
Streaming search: 6 missing repositories are not actionable 

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#18040] opened 2021-02-06 00:16 UTC
On cloud, the search:

`auth provider  r:^github.com/sourcegraph/* count:1000` results in 6 missing repositories. They are listed as UNKNOWN{ID=xxxxx}. This isn't actionable by the user.  If we cannot resolve a repository name, this should probably be a different level of error. 

![image](https://user-images.githubusercontent.com/539268/107100427-29110200-67c9-11eb-89dc-9ffabd2025af.png)

**Comment by keegancsmith** [comment] 2021-02-08 14:20
This is probably a duplicate of https://github.com/sourcegraph/sourcegraph/issues/18019#event-4303579972 which @stefanhengl just fixed with https://github.com/sourcegraph/sourcegraph/pull/18056

Once that is in production will try reproduce and see if it is fixed.

**Comment by stefanhengl** [comment] 2021-02-08 14:50
Just confirmed, #18056 fixes it.
<img width="2472" alt="image" src="https://user-images.githubusercontent.com/26413131/107235626-2d395b80-6a25-11eb-8530-afde5fce502a.png">

**Closed by stefanhengl** 2021-02-08 14:50 UTC
Labels: team/search

**Comment by keegancsmith** [comment] 2021-02-08 14:52
Fixed by #18056
