### ISSUE TITLE
Email signups should redirect to /get-cody

### ISSUE THREAD

**Issue by rrhyne** [sourcegraph/sourcegraph#54402] opened 2023-06-28 20:19 UTC
Currently, when a user clicks on the about page to signup to get Cody, we are redirecting them to the search/homepage. 

What should happen, is when the user completes email registration, they should land on /get-cody.

The &redirect=/get-cody required by the Oauth forms has been added to about that the logic doesn't exist in the app email signup process to cause this redirect to occur.

**Comment by BolajiOlajide** [comment] 2023-06-28 22:38
I'm unable to reproduce it.

https://www.loom.com/share/364a192a1c2b4e4794e63d8c50bfba6f?sid=e0a02013-2a93-4f72-a39e-87c96557faec

**Comment by indradhanush** [comment] 2023-06-29 06:08
@BolajiOlajide I think Rob is referring to Email signups. I just reproduced it and landed on /search instead.

**Comment by BolajiOlajide** [comment] 2023-06-29 06:22
Oh, my bad! I'll try again.
Thanks.

**Comment by pjlast** [comment] 2023-06-29 06:25
Fix here: https://github.com/sourcegraph/about/pull/6370

**Closed** 2023-06-29 06:37 UTC
