### ISSUE TITLE
Extensions API Directory Decorations

### ISSUE THREAD

**Issue by Joelkw** [sourcegraph/sourcegraph#15586] opened 2020-11-09 17:30 UTC
https://www.figma.com/file/zenC7UHayCK84KNFavAPA0/%F0%9F%8F%80Alicja-playground?node-id=380%3A5234

**Comment by felixfbecker** [comment] 2020-11-09 17:41
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/721

**Closed by felixfbecker** 2020-11-09 17:41 UTC
