### ISSUE TITLE
Cody for VS Code not rendering "Read files" in the chat when navigated from history view

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/sourcegraph#52848] opened 2023-06-02 12:41 UTC
It appears that "Read files" isn't rendered for a historical conversation until a new message is added to a chat:

https://github.com/sourcegraph/sourcegraph/assets/153/40d88f73-cd89-45ae-8bde-ae5333fbd273

## Steps to reproduce

1. Start a chat that reads some files
2. Start a new chat
3. Go to the history view, and load your first chat
4. See the "Read files" is missing
5. Send Cody a new message on that chat
6. See the "Read files" has re-appeared on the previous message

**Comment by abeatrix** [comment] 2023-06-02 17:54
>  Is this the expected behaviour?

If it is expected, I don't like it 😞

**Comment by deepak2431** [comment] 2023-06-02 18:00
> > Is this the expected behaviour?
> 
> If it is expected, I don't like it 😞

For me, too, it doesn't seem good, but I think it's not the expected behaviour. As I was checking the Cody web history it works perfectly fine will try to make the VS code history work in the same way which would require some other cleanup too.

**Comment by abeatrix** [comment] 2023-06-02 18:06
@deepak2431 are you planning to work on this issue? I'm wondering if this issue overlaps with https://github.com/sourcegraph/sourcegraph/issues/52544 so want to check with you to avoid duplicate works :)

**Comment by deepak2431** [comment] 2023-06-02 18:16
@abeatrix Yeah, I was working on this and handling the complete history implementation, as I feel it needs some cleanup and updates too.

Oh, I saw your draft PR for the other part of this. Shall I continue working on or will you be handling it entirely in your PR?

**Comment by abeatrix** [comment] 2023-06-02 18:20
I think there will be works overlapped so I'm happy to close my PR if you want to work on that as well, or I can continue after you're done with yours. 
I haven't really looked into how it works currently so I don't know if these two issues depend on each other, what do you think?

**Comment by deepak2431** [comment] 2023-06-02 18:26
> I think there will be works overlapped so I'm happy to close my PR if you want to work on that as well, or I can continue after you're done with yours. I haven't really looked into how it works currently so I don't know if these two issues depend on each other, what do you think?

I think that both overlapped a bit as when you would work on either you need to do the rework of how the Transcript is rendered, and stored. Doing this will handle both cases of it.  
It would be best not to close your PR for now, as I can possibly make a PR for this by Monday including other cleanup required for history and if the covers both the case it would be great. As I will try to take care of another part of your PR too :)

**Comment by abeatrix** [comment] 2023-06-02 19:00
My PR was just a workaround hoping to solve the issue raised by tim without needing to refactor the view, but it looks like refactoring is needed for it to work as how Tim described, so what i have in my PR is just rubbish at this point :P

**Comment by deepak2431** [comment] 2023-06-02 19:23
Looking at Tim's comments in your PR that makes sense. Thanks, @abeatrix

**Comment by SuperAuguste** [comment] 2023-06-15 21:40
Closed in #52904.

**Closed by SuperAuguste** 2023-06-15 21:40 UTC
Labels: cody, cody/vscode
