### ISSUE TITLE
[Accessibility Audit] Batch Changes: Perform a bulk operation on changesets for an open batch change

### ISSUE THREAD

**Issue by umpox** [sourcegraph/sourcegraph#34086] opened 2022-04-19 13:17 UTC
### Steps to replicate journey

Taken from the [user journey list document](https://docs.google.com/document/d/1XgG0udYL37G3RxuT5shizulpHgb6xVtY5L9kBeSkXYk/edit?usp=sharing). Use this for further context.

- Follow the workflow to view the changesets for an open batch change
- Toggle the checkboxes of the changesets that you want to perform a bulk action on
- Click the dropdown on “Select action”, above the list and to the right
- Select the bulk action you wish to perform from the popover menu
- Click the button for the bulk action you selected
- (Depending on the action you selected, you may be prompted to confirm or provide an additional detail in a modal. E.g. for “Create comment”, enter the text to post as a comment on the changesets, and then click “Post comments”. For “Publish changesets”, optionally toggle the checkbox, and then click “Publish”.)
- Click the “Bulk operations” tab
- The list of bulk actions, with the latest on top, will be visible

### How to audit

Follow the instructions here: [Auditing a user journey](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#auditing-a-user-journey)

**Note:** We are planning on arranging thorough third-party audit in the future, so our focus here is just to find the _majority_ of accessibility issues. Don't worry if you feel you haven't found 100% of potential issues, it is better to focus on the core essentials to complete the journey rather than spending lots of time going through every possible problem.

### How to raise discovered problems

Follow the instructions here: [Raising an accessibility bug](https://docs.sourcegraph.com/dev/background-information/web/accessibility/how-to-audit#raising-a-bug)

**Comment by courier-new** [comment] 2022-04-22 00:12
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/34085

**Closed by courier-new** 2022-04-22 00:12 UTC
Labels: accessibility, wcag/2.1/auditing, wcag/2.1
