### ISSUE TITLE
Code Insights: [BE] Add insights to dashboard mutation doesn't work 

### ISSUE THREAD

**Issue by vovakulikov** [sourcegraph/sourcegraph#27889] opened 2021-11-18 06:34 UTC
Steps to reproduce:
1. Open add/remove insights modal UI.
2. Select a few insights in the list and click save
3. See Dashboard not found error

GQL Request body 
```
operationName: "AddInsightViewToDashboard"
query: "mutation AddInsightViewToDashboard($insightViewId: ID!, $dashboardId: ID!) {↵ addInsightViewToDashboard(↵ input: {insightViewId…"

dashboardId: "ZGFzaGJvYXJkOnsiSWRUeXBlIjoiY3VzdG9tIiwiQXJnIjo0MDQwMTN9"
insightViewId: "aW5zaWdodF92aWV3OiIyMHhJTXNYTHk5MlU3TDZaTWVSbHM1ZGpubk4i"
```

GQL Responce 
```
data: null

errors: [
 {
   message: "dashboard not found"
   path: ["addInsightViewToDashboard"]
 }
]
```

But if we try to get this insight via gql API
<img width="797" alt="Screenshot 2021-11-18 at 09 34 17" src="https://user-images.githubusercontent.com/18492575/142364658-c80ad094-a547-4910-9977-063fea89ca8d.png">

**Comment by coury-clark** [comment] 2021-11-18 15:44
@CristinaBirkel was able to reproduce. Triaging as need-to-have

**Comment by coury-clark** [comment] 2021-12-06 16:46
This issue seems to have been resolved by one of the other bug fixes, since I am unable to reproduce by using the GraphQL API on k8s.

**Closed by coury-clark** 2021-12-06 16:46 UTC
Labels: bug, team/code-insights, backend, insights-settings-migration
