### ISSUE TITLE
insights: Backend series not being calculated correctly

### ISSUE THREAD

**Issue by CristinaBirkel** [sourcegraph/sourcegraph#28504] opened 2021-12-02 20:43 UTC
I'm seeing this on `k8s` right now. A lost of the BE insights are not showing the right data. Lots of them are straight lines, and lots of them are saying they couldn't find any data. I'll update this issue when I have some more information.

**Comment by coury-clark** [comment] 2021-12-08 16:03
Okay, digging into why we aren't getting some correct results, looking at this insight
<img width="391" alt="CleanShot 2021-12-08 at 09 01 40@2x" src="https://user-images.githubusercontent.com/5090588/145241119-def77fb4-2c54-420d-a39c-bfe0238c5add.png">

Here is what I see looking at the queue:
<img width="515" alt="CleanShot 2021-12-08 at 09 00 57@2x" src="https://user-images.githubusercontent.com/5090588/145241184-2a8ce08a-83d0-4271-b44d-c202ee6e6e69.png">

A few things to note:
1. The number of jobs queued for the first datum seems low, but could be plausible
2. The rest of the numbers seem impossibly low
3. `2021-02-01` is missing entirely

**Comment by coury-clark** [comment] 2021-12-08 16:35
Running the same insight locally:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/5090588/145246768-f89d307d-1889-4035-adaa-ecba9b0a8096.png">

These numbers seem far too low, even for a highly compressed series. Possibly something is wrong with the compression algorithm?

**Comment by coury-clark** [comment] 2021-12-08 16:37
Unfortunately it seems a bug in the debug logging always outputs the same set of series so there is no way to determine if compression is working without changing this:
https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/enterprise/internal/insights/background/historical_enqueuer.go?utm_product_name=GoLand&utm_product_version=GoLand#L335:130-335:136

**Comment by coury-clark** [comment] 2021-12-08 16:43
Back to looking at the series on k8s, here are the distinct dates for the actual timeseries data:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/5090588/145247899-3ac5e68e-0594-4dd1-ba19-27ebae184477.png">

I think I didn't account for the dependent records in the images above, so maybe there isn't a problem with backfilling but instead with querying?

**Comment by coury-clark** [comment] 2021-12-08 16:58
Okay, so a couple of observations:
1. When I reconstruct the timeseries query, I see that we are losing all of the historical data points because of https://github.com/sourcegraph/sourcegraph/issues/25061

If we remove this filter condition, we see the following:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/5090588/145250204-4faef665-cc42-4050-960f-43c43efe43e5.png">

So the next question is - why are all of the historical values the same? How many (repo, value) pairs don't have duplicates?

``` SQL
SELECT repo_id, value, count(*)
FROM series_points
WHERE series_id = '21uzti6xXtI1F0UvKuPYdfdG4QG'
group by repo_id, value
having count(*) < 12
```

<img width="401" alt="image" src="https://user-images.githubusercontent.com/5090588/145250291-f78ce335-1a25-4020-8c35-655f44a3fcdd.png">

Whoa, only one?? Okay, that strongly implies something is wrong in the backfill path, and not the query time path. There should be substantially more change than a single datum over 26k repos.

**Comment by coury-clark** [comment] 2021-12-08 18:02
I've managed to narrow the problem down to the compression algorithm, for some reason it seems almost every repository is getting no results when it searches for commits in the timeframe
<img width="785" alt="CleanShot 2021-12-08 at 10 58 59@2x" src="https://user-images.githubusercontent.com/5090588/145260023-4e5278d3-caa3-4a35-9cac-b3939cb8800d.png">
:

**Comment by coury-clark** [comment] 2021-12-09 17:19
Recalculating the series `21uzti6xXtI1F0UvKuPYdfdG4QG` on k8s with some new log output to get a sense of what might be going on here.

**Comment by coury-clark** [comment] 2021-12-09 17:46
Statistics from the fresh backfill on k8s
``` json
{"Skipped":0,"Compressed":26321,"Uncompressed":20,"Preempted":48,"Errored":0}
```

**Comment by coury-clark** [comment] 2021-12-09 17:57
Results after a fresh backfill
<img width="910" alt="CleanShot 2021-12-09 at 10 52 02@2x" src="https://user-images.githubusercontent.com/5090588/145450240-de37cfca-c9f3-46ab-aea2-0e49a65b058e.png">

**Comment by coury-clark** [comment] 2021-12-13 16:17
It seems like this issue was causing by some data conflicts on K8s, and is not currently reproducible. Closing for now, and will reopen if we observe it again.

**Comment by coury-clark** [comment] 2021-12-14 23:38
Still getting series that are just massive under populated

### Santa series 22EmvTsvNqWfHZ14VuP2tnEaIp1
2021-12-13T16:09:54.609587474Z stderr F t=2021-12-13T16:09:54+0000 lvl=info msg="backfill statistics" seriesId=22EmvTsvNqWfHZ14VuP2tnEaIp1 stats="{\"Skipped\":0,\"Compressed\":146,\"Uncompressed\":0,\"Preempted\":1,\"Errored\":0}"

### Snow series 22EmvPuj2KhZOB70LFoOS4fLnHm
2021-12-13T16:09:54.609598459Z stderr F t=2021-12-13T16:09:54+0000 lvl=info msg="backfill statistics" seriesId=22EmvPuj2KhZOB70LFoOS4fLnHm stats="{\"Skipped\":0,\"Compressed\":146,\"Uncompressed\":0,\"Preempted\":1,\"Errored\":0}"

**Comment by coury-clark** [comment] 2022-01-10 16:31
This issue has not been observed since some stability / error handling improvements in the backfiller. Closing until we can reproduce.

**Closed by coury-clark** 2022-01-10 16:31 UTC
Labels: bug, team/code-insights, backend, insights-settings-migration
