### ISSUE TITLE
Provide a way to filter by repository type ("User" or "Organization")

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/sourcegraph#18937] opened 2021-03-08 15:35 UTC
#### Feature request description

Add a new search parameter to filter by repository type.  This is particularly useful on GitHub Enterprise accounts where repositories can be either `User` or `Organization` associated repositories (see `type` property on repository response object in the [GitHub API](https://docs.github.com/en/rest/reference/repos#get-a-repository)).   It could be similar to `fork:` and `archive:` parameters (i.e., `user:(yes|no)`, `organization:(yes|no)`) or something more general like `repotype:(user|organization|all)`

#### Is your feature request related to a problem? If so, please describe.

Large GitHub Enterprise organizations that allow users to create their own repositories in their user namespace find it difficult to filter those "personal" repositories out.  This is especially challenging if these organizations use the GitHub `Organization` to mimic internal structure such as Team or Divisions (i.e., create a GitHub Organization for a Team).  When this happens, it's impossible to filter out the User repositories effectively.

#### Describe alternatives you've considered.

Using regex works but it is not perfect.  For example, you can remove all repositories that match a particular naming scheme that matches usernames. 

#### Additional context

* [Recording on discussion about this with a customer](https://hello.chorus.ai/listen?guid=02859c8e07354f88b33f7ba57f5e50a6)
* [Slack Conversation](https://sourcegraph.slack.com/archives/CTQ5LTF8D/p1614723806022300)

**Comment by camdencheek** [comment] 2024-02-23 16:59
Closing as duplicate of https://github.com/sourcegraph/sourcegraph/issues/13632

**Closed by camdencheek** 2024-02-23 16:59 UTC
Labels: team/search-product, team/code-search, imported
