### ISSUE TITLE
Zoekt behavior wrong when matching for regex like `(.|\n)`

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/sourcegraph#28429] opened 2021-12-01 22:13 UTC
- Regex to match something ending in a newline, like `",\n` matches: [link](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Epackage%5C.json+%2C%5Cn&patternType=regexp)

- Regex `",(.|\n)"` which matches of superset of `",\n` finds NO matches (bug): [link](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Epackage%5C.json+%22%2C%28.%7C%5Cn%29&patternType=regexp)

This bug does not happen when `index:no` is set, so it seems like a problem with Zoekt's interpretation of `(.|\n)`: [link](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/sourcegraph%24+file:%5Epackage%5C.json+%22%2C%28.%7C%5Cn%29+index:no&patternType=regexp)

This behavior breaks ways for matching multiple lines. E.g., `(.|\n)*` should match across multiple lines but will often yield no results.

**Comment by varungandhi-src** [comment] 2021-12-14 08:25
I believe I'm hitting this same issue with [a query to find usages of HashMap<URL](https://sourcegraph.com/search?q=context:global+language:Java+import+java.net.URL%28.%7C%5Cn%7C%5Cr%5Cn%29%2BHashMap%5C%3CURL&patternType=regexp) in Java.

I saw on Twitter that [URLs aren't supposed to be used for hash keys](https://twitter.com/brunoborges/status/1470652630615552001) in practice since 2001, so I wanted to check the usages. However, the query above doesn't seem to be picking up matches properly, such as this one in [Ghidra](https://sourcegraph.com/github.com/NationalSecurityAgency/ghidra/-/blob/Ghidra/Framework/Docking/src/main/java/docking/help/HelpManager.java?L22-67).

**Comment by rvantonder** [comment] 2022-07-25 20:31
query, `index:no` works great: 

## [link](https://sourcegraph.com/search?q=context:global+repo:%5Egithub%5C.com/sourcegraph/src-cli%24+streamsearchsequentialline%28.%7C%5Cn%29*search-border+index:no&patternType=regexp)
<img width="1509" alt="Screen Shot 2022-07-25 at 1 30 49 PM" src="https://user-images.githubusercontent.com/888624/180868735-61a50511-9f31-468c-80cb-80c7de2c1672.png">

zoekt does not work great:
<img width="1492" alt="Screen Shot 2022-07-25 at 1 31 25 PM" src="https://user-images.githubusercontent.com/888624/180868821-f01ac548-3244-4a39-ac87-06230c0cbfd2.png">

**Comment by keegancsmith** [comment] 2022-07-26 15:02
this is a fun one to fix, since you can likely work within just the zoekt repo + have a simple unit test to reproduce.

From Camden:

> My spidey senses are pointing me to a syntax -> match tree translation issue. This issue existed long before the chunk matches and multiline searches like `LineMatch{[^\}]*}` still work fine. The character class “anything but `}`” correctly matches newlines, but the alternation “anything but newline or newline” does not. Another datapoint is that the `(?s:...)` flag does not work either. That should make `.` match newlines, but it does not.

**Comment by jjeffwarner** [comment] 2022-07-26 17:17
Thanks for raising this. We will get this resolved during Q3.

**Comment by jjeffwarner** [comment] 2022-10-13 22:45
I think we can close this now?

**Closed** 2022-12-07 08:35 UTC
Labels: bug, team/search-core
