### ISSUE TITLE
Sourcegraph for VS Code: VPN issue

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/sourcegraph#30916] opened 2022-02-09 20:41 UTC
- **Sourcegraph version:** 3.36.3 
- **Platform information:** Extension Version: 2.0.6, VSCode Version: 1.64.1, MacOS 11.6

#### Steps to reproduce:

1. Connect to VPN to access private instance
2. Add Access Token and instance URL to settings.json

#### Expected behavior:
Search results are returned.

#### Actual behavior:
`The connection was closed before your search was completed. This may be due to a problem with a firewall, VPN or proxy, or a failure with the Sourcegraph server.`
<img width="1506" alt="Screen Shot 2022-02-09 at 12 37 11 PM" src="https://user-images.githubusercontent.com/69164745/153285776-45d0e34f-b71a-4597-82f7-dcfbca2ef569.png">

**Comment by abeatrix** [comment] 2022-02-09 21:48
We have updated the stream search API endpoint in [3.36.0 ](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-36-0) to avoid CORS issues while using the standard endpoint to run search within the extension. A workaround in this case would be adding the `/.api` endpoint manually in the setting, which the customer has confirmed working for them.

TBD: Should we replace the standard stream search endpoint with the API endpoint to avoid CORS Issues since most of our enterprise customers access their instances with a VPN.

**Comment by jjinnii** [comment] 2022-02-09 22:08
@abeatrix To your TBD question, are there any security implications that we should be aware of?

**Comment by abeatrix** [comment] 2022-02-09 22:45
Based on our [changelog](https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md#3-36-0), it stated that `The endpoint /search/stream will be retired in favor of /.api/search/stream` so I assumed using the `/.api/search/stream` is preferred? 
CC-ing @slimsag to see if he can shed more light on this 🙇  More context can be found in [this slack thread](https://sourcegraph.slack.com/archives/C01LZKLRF0C/p1644439762565469)

**Comment by abeatrix** [comment] 2022-02-18 21:06
@jjinnii The customer has confirmed that the fix in[ this PR ](https://github.com/sourcegraph/sourcegraph/pull/31450)has resolved their issue: [link to thread](https://sourcegraph.slack.com/archives/C015JREMBTR/p1645218006677509?thread_ts=1644361710.845619&cid=C015JREMBTR) 🚀

**Comment by abeatrix** [comment] 2022-02-22 21:17
Fixed and released in v2.0.9: https://marketplace.visualstudio.com/items?itemName=sourcegraph.sourcegraph

**Closed by abeatrix** 2022-02-22 21:17 UTC
Labels: bug, p1, team/growth-and-integrations, vscode-extension

**Comment by jjinnii** [comment] 2022-02-22 23:00
Amazing work @abeatrix ! 🚀
