### ISSUE TITLE
Fuzzy finder: Pressing Escape does not hide the modal in Firefox with Vimium extension installed

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/sourcegraph#28453] opened 2021-12-02 07:51 UTC
- **Sourcegraph version:** sourcegraph.com today
- **Platform information:** Firefox 94.0.2 (64-bit), macOS, Vimium extension

#### Steps to reproduce:

1. Activate fuzzy finder
2. Press escape, unfocuses the input
3. Press escape again, nothing happens

#### Expected behavior:

The modal should disappear in step 2, which is the behavior with Google Chrome. 

#### Actual behavior:

Nothing happens in step 3. I can only reproduce in Firefox.

#### Possible solution

For consistency with the GitHub Command Palette, maybe we should only use Cmd+K as the keyboard shortcut to hide the modal. The Escape key is overloaded with lots of built-in behavior from the browser.

/cc @felixfbecker

**Comment by Numbers88s** [comment] 2021-12-02 20:30
Thanks for bringing it to my attention! 

I was looking into it to see if I could loop it into the PR I'm in, but I cannot reproduce 😢 
Here's a GIF of me trying to reproduce it. It also is on Mac & Firefox 94.0.2

![ezgif com-gif-maker](https://user-images.githubusercontent.com/6225160/144497975-4e0938f3-6853-4e99-8d79-46694613fa9b.gif)

**Comment by fkling** [comment] 2024-06-10 16:06
I'm closing this for now. If this still an issue please reopen.

**Closed** 2024-06-10 16:06 UTC
Labels: team/code-search
