### ISSUE TITLE
Unable to run ./enterprise/dev/start.sh

### ISSUE THREAD

**Issue by nicksnyder** [sourcegraph/sourcegraph#2836] opened 2019-03-19 15:28 UTC
Reproduce

1. `./dev/drop-entire-local-database.sh`
2. `./enterprise/dev/start.sh`
3. Frontend terminates with these logs:
    ```
    08:25:15               frontend | 1 error occurred:
    08:25:15               frontend | 	* Did not find authentication provider matching "https://gitlab.sgdev.org"
    08:25:15               frontend | Terminating frontend
     ```

**Comment by nicksnyder** [comment] 2019-03-19 15:41
I can workaround by commenting out the Gitlab config section in https://github.com/sourcegraph/dev-private/blob/master/enterprise/dev/external-services-config.json

**Comment by beyang** [comment] 2019-03-20 17:14
Another workaround is to simply rerun `./enterprise/dev/start.sh`. I think this is due to a race condition wherein the critical config is not yet initialized by the dev scripts by the regular config is initialized and frontend starts, leading to the expected GitLab entry not yet being present in `auth.providers`.

**Comment by beyang** [comment] 2019-04-24 00:55
Can no longer repro. Please re-open if still an issue.

**Comment by ijt** [comment] 2019-05-09 01:59
I'm getting this now on 001260fc7f927879ef4f0720ba97ede2612414a5.

**Comment by slimsag** [comment] 2019-05-09 02:06
Duplicate of https://github.com/sourcegraph/sourcegraph/issues/2095 which has the same underlying cause (race condition when we initialize DB from file).

**Closed by slimsag** 2019-05-09 02:06 UTC
Labels: ops & tools & dev
