### ISSUE TITLE
eror msg=store.upsert-repos error="DBStore.UpsertRepos did not set ID for Repo

### ISSUE THREAD

**Issue by brndmg** [sourcegraph/sourcegraph#14907] opened 2020-10-20 11:53 UTC
- **Sourcegraph version:** 3.20.1
- **Platform information:** Docker version

#### Steps to reproduce:

1. Started with:
```bash
docker run --publish 7080:7080 --publish 127.0.0.1:3370:3370 --rm \
  --volume ~/.sourcegraph/config:/etc/sourcegraph \
  --volume ~/.sourcegraph/data:/var/opt/sourcegraph \
  sourcegraph/server:3.20.1
```

2. Navigated to localhost:7080, added setup admin user.

2. Added my GitHub Enterprise details and my org here: 

http://localhost:7080/site-admin/external-services/new?id=ghe

```json
{
  "url": "https://github.internal.host.com",
  "token": "mytoken",
  "orgs": [
    "myuserorg"
  ],
  "certificate": "-----BEGIN CERTIFICATE-----\n..."
}
```

#### Expected behavior:

I expected all of my personal repos to be indexed and searchable.

#### Actual behavior:

Repositories are not indexed, and this error is in the logs for each discovered repository in my personal organization.

```bash
11:50:45                      repo-updater | t=2020-10-20T11:50:45+0000 lvl=eror msg=store.upsert-repos error="DBStore.UpsertRepos did not set ID for Repo{ID: 0, Name: \"github.internal.host.com/repo/name\", EID: {https://github.internal.host.com/ github }}" count=1
```

**Comment by asdine** [comment] 2020-11-20 14:33
@brndmg I cannot reproduce the error, could you share more logs to see if this error is not caused by another error?
Also, do you have the same behavior with the latest release?

**Comment by unknwon** [comment] 2021-02-24 14:52
Closing for staleness, feel free to post more details to resume the discussion.

**Closed by unknwon** 2021-02-24 14:52 UTC
Labels: team/core-application
